### ISSUE TITLE
error: InvalidPort

### ISSUE THREAD

**Issue by nyxb** [oven-sh/bun#5760] opened 2023-09-19 19:49 UTC
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

nextjs with bun just wants to start the dev server

`"dev": "next dev -p 3030",`

when i run bun --bun run dev or even bun run dev i get the error.

### What is the expected behavior?

```
bun run dev
$ next dev -p 3030
[0.02ms] ".env"
- info Loaded env from /Users/nyxb/blog/.env

error: InvalidPort

----- bun meta -----
Bun v1.0.2 (37edd5a6) macOS Silicon 22.6.0
AutoCommand:
Elapsed: 0ms | User: 1ms | Sys: 0ms
RSS: 4.06MB | Peak: 4.06MB | Commit: 33.55MB | Faults: 15
----- bun meta -----

0   0x10655b664 WTFGetBacktrace

Crash report saved to:
  ~/.bun-crash/v1.0.2-1695152562612.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
```

```
bun --bun run dev
$ next dev -p 3030
[0.02ms] ".env"
- info Loaded env from /Users/nyxb/blog/.env

error: InvalidPort

----- bun meta -----
Bun v1.0.2 (37edd5a6) macOS Silicon 22.6.0
AutoCommand:
Elapsed: 1ms | User: 1ms | Sys: 1ms
RSS: 4.08MB | Peak: 4.08MB | Commit: 33.55MB | Faults: 26
----- bun meta -----

0   0x104a17664 WTFGetBacktrace

Crash report saved to:
  ~/.bun-crash/v1.0.2-1695152528691.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
```

### Additional information

with the default port it works but i can't set custom ports.

**Comment by Electroid** [comment] 2023-09-19 19:51
Thanks for reporting. Duplicate of #5698

**Closed as not planned by Electroid** 2023-09-19 19:51 UTC
Labels: bug
