### ISSUE TITLE
`request.clone()` -> `Request.prototype.json()` not working from HTTP server

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#2477] opened 2023-03-24 21:10 UTC
Reported: https://discord.com/channels/876711213126520882/876711213126520885/1088916040387395614

The following snippet:
```js
Bun.serve({
  async fetch(request) {
    const req = request.clone();
    const b = await req.json();
    const a = await request.json();
    return new Response(`Bun!`);
  },
});
```

gives me this error with Bun v0.5.8 (and it worked with v0.5.7)
```
16 | Bun.serve({
17 |   async fetch(request) {
18 |     const req = request.clone();
                    ^
SyntaxError: Unexpected end of JSON input
```

**Comment by LuisMalhadas** [comment] 2023-04-08 17:29
This issue still exists with 0.5.9

**Comment by PassiDel** [comment] 2023-06-22 08:25
Still in 0.6.9.

This breaks json validation in hono :confused:  
honojs/middleware#81

**Comment by otherguy** [comment] 2023-09-11 14:03
Still an issue in 1.0.0

**Comment by mirismaili** [comment] 2024-07-22 12:53
Gives me the same error on the next line:
```
7 |   async fetch(request) {
8 |     const req = request.clone()
9 |     const b = await req.json()
                            ^
SyntaxError: Unexpected end of JSON input
```

**Comment by Jarred-Sumner** [comment] 2024-08-29 08:29
Duplicate of #6348

**Comment by Jarred-Sumner** [comment] 2024-08-29 08:29
This issue is being tracked in #6348 . We will fix it, but please follow along there.

**Closed as completed by Jarred-Sumner** 2024-08-29 08:29 UTC
Labels: bug, web-api
