### ISSUE TITLE
`await Bun.file(...).text()` crashes in Docker

### ISSUE THREAD

**Issue by A-D-E-A** [oven-sh/bun#7006] opened 2023-11-09 11:47 UTC
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 5.10.0-8-amd64 x86_64 unknown

### What steps can reproduce the bug?

Use the Docker Image "oven-sh/bun:1.0.11-debian" to build a container.

In that container, add the following file `test.ts`:
```ts#test.ts
const f = Bun.file("test.ts"); // or any other file path that exists
console.log(f);

const e = await f.exists();
console.log(e);

const c = await f.text();
console.log(c);

console.log("end");
```

Then run the program using `bun test.ts`.

### What is the expected behavior?

The program should show the following output:
```txt
FileRef ("test.ts") {
  type: "text/javascript;charset=utf-8"
}
true
// the file's content here
end
```
And it should exit with the error code 0:
```sh
> echo $?
0
```

### What do you see instead?

The program show only the following:
```txt
FileRef ("test.ts") {
  type: "text/javascript;charset=utf-8"
}
true
```

And it exits with 1:
```sh
> echo $?
1
```

### Additional information

It seems to only happen in my containers, it works on the host (sharing the same output for `uname -mprs` with the container).

The method `BunFile#text` seems to exist, since I can log it and receive `[Function: text]`. It just crashes when it is called.

That bug seems to be there since at least 1.0.4

I have a workaround using streams and responses.
```ts
const readFile = async (f: Bun.file) => await new Response(await f.stream()).text();
```

**Comment by Electroid** [comment] 2023-11-09 19:11
Duplicate of https://github.com/oven-sh/bun/issues/5960

**Closed as not planned by Electroid** 2023-11-09 19:11 UTC
Labels: bug, bun.js
