### ISSUE TITLE
v1.1.20 crash issue

### ISSUE THREAD

**Issue by dennicLiu** [oven-sh/bun#12601] opened 2024-07-16 15:47 UTC
### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on linux x86_64 [InstallCommand]

Segmentation fault at address 0x000000B0

- `??`
- [`http.zig:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/http.zig#L0>): `src.http.writeRequest__anon_151227`
- [`uws.zig:977`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/uws.zig#L977>): `src.deps.uws.NewSocketHandler`
- [`bsd.c:497`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bsd.c#L497>): `us_socket_write`
- [`epoll_kqueue.c:487`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/eventing/epoll_kqueue.c#L487>): `us_timer_close`
- [`array_hash_map.zig:2022`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/zig/lib/std/array_hash_map.zig#L2022>): `src.http.HTTPThread.processEvents`
- [`string_immutable.zig:885`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/string_immutable.zig#L885>): `src.http.NewHTTPContext`
- `??`

**Comment by dennicLiu** [comment] 2024-07-17 09:12
=> [6/8] RUN bun install --verbose                                                                                                                                                                             26.8s
 => => # [PackageManager] waiting for 244 tasks
 => => # [PackageManager] waiting for 244 tasks
 => => # [PackageManager] waiting for 244 tasks
 => => # [PackageManager] waiting for 244 tasks
 => => # [PackageManager] waiting for 244 tasks
 => => # [PackageManager] waiting for 244 tasks
 
 
 block in  waiting for 244 tasks

**Comment by Jarred-Sumner** [comment] 2024-07-18 04:05
Duplicate of https://github.com/oven-sh/bun/issues/12591

**Closed as not planned by Jarred-Sumner** 2024-07-18 04:05 UTC
Labels: bun install
