### ISSUE TITLE
Captcha-Canvas Crashing

### ISSUE THREAD

**Issue by lassejlv** [oven-sh/bun#10348] opened 2024-04-18 10:04 UTC
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Using this code

```ts
import { CaptchaGenerator } from "captcha-canvas";

const capcha = new CaptchaGenerator()
    .setDimension(150, 450)
    .setCaptcha({ text: "CUSTOM05", size: 60, color: "deeppink" })
    .setDecoy({ opacity: 0.5 })
    .setTrace({ color: "deeppink" });

  const buffer = capcha.generateSync();
  console.log(buffer);
```

### What is the expected behavior?

It should log the buffer.

### What do you see instead?

I get this error in my terminal whenever i try to run it. There was no issues while installing packages. And i have make sure i have python installted on my pc. And thats working.

```bash
$ bun run --watch .
dyld[89779]: missing symbol called
error: script "dev" was terminated by signal SIGKILL (Forced quit)
[1]    89778 killed     bun dev
```

**Comment by Jarred-Sumner** [comment] 2024-08-08 19:50
Duplicate of https://github.com/oven-sh/bun/issues/5835

**Comment by Jarred-Sumner** [comment] 2024-08-08 19:50
Please follow along in https://github.com/oven-sh/bun/issues/5835

**Closed as not planned by Jarred-Sumner** 2024-08-08 19:50 UTC
Labels: bug, needs investigate
