### ISSUE TITLE
beforeAll lifecycle hooks incompatible with Jest

### ISSUE THREAD

**Issue by edorsey** [oven-sh/bun#4868] opened 2023-09-10 23:20 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Running this test file with jest and bun:

```js
beforeAll(() => {
  console.log('BEFORE ALL 0')
})

beforeEach(() => {
  console.log('BEFORE EACH 0')
})

afterAll(() => {
  console.log('AFTER ALL 0')
})

afterEach(() => {
  console.log('AFTER EACH 0')
})

describe('First test', () => {
  beforeAll(() => {
    console.log('BEFORE ALL 1')
  })

  beforeEach(() => {
    console.log('BEFORE EACH 1')
  })

  afterAll(() => {
    console.log('AFTER ALL 1')
  })

  afterEach(() => {
    console.log('AFTER EACH 1')
  })

  it('true should be true', () => {
    expect(true).toBe(true)
  })
})

describe('Second test', () => {
  beforeAll(() => {
    console.log('BEFORE ALL 2')
  })

  beforeEach(() => {
    console.log('BEFORE EACH 2')
  })

  afterAll(() => {
    console.log('AFTER ALL 2')
  })

  afterEach(() => {
    console.log('AFTER EACH 2')
  })

  it('true should be true', () => {
    expect(true).toBe(true)
  })
})
```

Jest output:

<img width="323" alt="image" src="https://github.com/oven-sh/bun/assets/1857893/bc4c602f-e3c4-439f-ad42-6f72d0efb488">

Bun output:

<img width="238" alt="image" src="https://github.com/oven-sh/bun/assets/1857893/89af860a-19c0-48d9-a4e2-12cf6419765f">

### What is the expected behavior?

It should match the jest lifecycle hooks. Where a nested `beforeAll` is only run just before the tests in the describe block.

### What do you see instead?

It's "hoisting" all the `beforeAll`s and running them as if they were not nested under describe blocks.

**Comment by Electroid** [comment] 2024-02-05 21:22
Duplicate of #5738

**Closed as not planned by Electroid** 2024-02-05 21:22 UTC
Labels: bug, bun:test
