### ISSUE TITLE
bun installed successfully and stuck?

### ISSUE THREAD

**Issue by babarqb** [oven-sh/bun#357] opened 2022-07-07 13:00 UTC
I am trying to install bun on macOS 11.6.6 with the curl command. Bun downloaded successfully and then wrote this line and stuck
"Bun was installed successfully to /Users/babarqb/.bun/bin/bun"
I force quit and manually added the path in .zshrc but bun is not working.

**Comment by neo773** [comment] 2022-07-07 13:46
Had the same issue temporary fix is to copy bun binary to /usr/local/bin
```
cp bun /usr/local/bin
```

**Comment by babarqb** [comment] 2022-07-07 18:52
> Had the same issue temporary fix is to copy bun binary to /usr/local/bin
> 
> ```
> cp bun /usr/local/bin
> ```

same error after cp bun /usr/local/bin when run command 
bun --help  
       --use <<STR>>

**Comment by cmarchena** [comment] 2022-07-07 21:34
I'm experiencing the same issue on Mac. I can confirm that my bash is updated to version 5.1.16

**Comment by Jarred-Sumner** [comment] 2022-07-08 03:45
I'm not sure how to reproduce this :(

**Comment by pierredewilde** [comment] 2022-07-08 07:05
Same issue here on `macOS Catalina version 10.15.7`

```
$ curl https://bun.sh/install | bash
$ bun -v
0.1.2
$ bun -h
	    --use <STR>
```
then hangs. Only CTRL+C will return to the command line.

This prevents us to evaluate Bun on macOS. Thanks.

**Comment by babarqb** [comment] 2022-07-09 08:00
> Same issue here on `macOS Catalina version 10.15.7`
> 
> ```
> $ curl https://bun.sh/install | bash
> $ bun -v
> 0.1.2
> $ bun -h
> 	    --use <STR>
> ```
> 
> then hangs. Only CTRL+C will return to the command line.
> 
> This prevents us to evaluate Bun on macOS. Thanks.

does anyone resolve this issue still not able to run bun v1.2 on macOS 11.6.6

**Comment by FinnRG** [comment] 2022-07-09 11:40
@babarqb Could you please check if your CPU supports AVX2?

**Comment by cmarchena** [comment] 2022-07-09 15:55
> @babarqb Could you please check if your CPU supports AVX2?

```bash
sysctl -a | grep machdep.cpu.features
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS
 ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 CX16 TPR
 PDCM SSE4.1 SSE4.2 x2APIC POPCNT AES PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C
```
2.5 GHz Dual-Core Intel Core i5
MacBook Pro (13-inch, Mid 2012)
macOS Catalina
Version 10.157 (19H1922)
No

**Comment by FinnRG** [comment] 2022-07-09 17:10
@cmarchena Then this is a duplicate of #67. Please follow the instructions there.

**Closed as completed by FinnRG** 2022-07-09 17:10 UTC
