### ISSUE TITLE
fn.toString() should  return author time code instead of optimized code and bun run, bun build, bun build --minify should log the same.

### ISSUE THREAD

**Issue by liquancss** [oven-sh/bun#10488] opened 2024-04-24 20:03 UTC
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.19044.0 x64

### What steps can reproduce the bug?

```js
// main.js
function foo(){
    const a = 1;
    return a+v;
}
console.log("foo.toString", foo.toString())
```

```bash
bun run main.js
```

## it should like this
```js
foo.toString function foo(){
    const a = 1;
    return a+v;
}
```

## I get optimized code.
```js
foo.toString function() {
  return 1 + v;
}
```

## As you can see, ```bun build``` without ```--minify flag``` works fine as node and browser. But ```bun run``` and ```bun build --minify``` just behave very differently.

![image](https://github.com/oven-sh/bun/assets/46746379/65070ad5-aa02-4547-b2b9-86bff31cabaf)

**Comment by anru** [comment] 2024-06-18 10:07
Still actual for bun v1.1.13

**Comment by anru** [comment] 2024-06-18 10:24
@Jarred-Sumner this bug causes runtime inconsistency with node.js runtime. So, in some cases it's blocker for replace node to bun where you have to use fn.toString() functionality. For example dynamically generate js code for submitting it via api

**Comment by anru** [comment] 2024-07-09 10:41
Can confirm this issue has been fixed in version 1.1.18 🎉

**Comment by liquancss** [comment] 2024-07-10 01:02
> Can confirm this issue has been fixed in version 1.1.18 🎉

## I tried it on my mac and windows with bun v1.1.18, it's still unchanged. 
**Please tell me which platform do you use and share me related test code as well.**

### 1.1 mac snopshot
<img width="1018" alt="截屏2024-07-10 08 43 17" src="https://github.com/oven-sh/bun/assets/46746379/487b3b0a-15f1-491d-a64c-fba1de7e479a">

### 1.2 windows snopshot
![image](https://github.com/oven-sh/bun/assets/46746379/cf4e8a56-d2a2-40dd-b0e2-90ae23fd6411)

**Comment by anru** [comment] 2024-07-10 05:51
That's right, I jumped to conslusions too soon.

I have tested only in bun repl.
<img width="796" alt="image" src="https://github.com/oven-sh/bun/assets/130013/ecba14ee-930e-4838-80ee-f54634ca4d48">

But behaviour is still same in bun run/bun build

**Comment by liquancss** [comment] 2024-07-10 06:24
> That's right, I jumped to conslusions too soon.
> 
> I have tested only in bun repl. <img alt="image" width="796" src="https://private-user-images.githubusercontent.com/130013/347272497-ecba14ee-930e-4838-80ee-f54634ca4d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTIxOTksIm5iZiI6MTcyMDU5MTg5OSwicGF0aCI6Ii8xMzAwMTMvMzQ3MjcyNDk3LWVjYmExNGVlLTkzMGUtNDgzOC04MGVlLWY1NDYzNGNhNGQ0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwNjExMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGNiNGFmYzRmODk3YTQzOTYzYmE3MDBkMDcxYWIwNmJmMDJkYTZjZjJmYWJhZDU2ZTgyNjM1ODAwOTM0NDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IS7BEq2Bh6oG7HDa4Gn-4143p983VTPUjji7uBwQBd4">
> 
> But bug is still actual for bun run/bun build

Yep, it’ true.

I’m just curious that bun is a JavaScript runtime thus they should  implement the language runtime as **ecma spec** says.
 
From my view, bun seems to make JavaScript dialect themselves, and plus four kind dialects. One snippet code generate four very different results.

**Comment by paperdave** [comment] 2024-09-01 22:28
Duplicate of #3248 (you should :+1: that issue).

This might be fixed for `bun run`, but it will not be changed for `bun build --minify`, as minification intentionally alters the source code to be smaller.

**Closed as not planned by paperdave** 2024-09-01 22:28 UTC
Labels: bug, transpiler
