### ISSUE TITLE
Implement a text-based lockfile format

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#11863] opened 2024-06-14 06:53 UTC
This is a tracking issue for implementing a text-based lockfile format for `bun install` and making it the default format going forward. There will be a smooth migration path from `bun.lockb` → `bun.lock`.  

### Why?

When first working on the package manager, the flamegraph showed parsing JSON was the biggest number. So instead of a JSON lockfile, we designed two efficient binary formats: one for the registry manifest cache and one for the lockfile.

The binary lockfile format has served us well, but it isn't worth the cost in developer experience, particularly for larger teams working together. We suggest workarounds today for various things, but none of them are great.

- Merge conflicts are hard. Do you pick `bun.lockb.1` or `bun.lockb.2`? What about both?
- How do you inspect the lockfile from a PR on GitHub/GitLab/etc? 
- How do you diff the lockfile? You can [print as a yarn.lock](https://bun.sh/guides/install/yarnlock) and configure git to diff that way, but that's a whole lot more complicated than it not being a problem in the first place
- When there are lockfile changes, it's not clear enough why. Sometimes, you run `bun install` and the lockfile has changes due to hashes changing, package.json `scripts` changing, or other reasons and this is hard to understand right now because it's hard to read in a text editor.
- People too frequently add `bun.lockb` to the `.gitignore` file 

### Will bun install still be fast?

Yes.

### Will it make bun install slower?

Based on what we've seen, about 1-20 milliseconds.

### What will the new format be?

Probably [JSON with Trailing Commas](https://code.visualstudio.com/docs/languages/json#_json-with-comments), like `tsconfig.json`.

Bun already supports this schema format for the runtime (and package.json). TOML is another option and it's what we use for `bunfig.toml`, though I kind of think that was a mistake and it should've been JSON with Trailing Commas. TOML's editor tooling support is not as mature as JSON with Trailing Commas.

#### Why [JSON with Trailing Commas](https://code.visualstudio.com/docs/languages/json#_json-with-comments) instead of JSON?

Too many collective human lifetimes have been spent fixing merge conflicts from diffs caused by adding or removing trailing commas at the end of lists in JSON

```diff
-    }
+    },
```

#### Why JSON with Trailing Commas instead of YAML?

YAML is fine. We don't have a YAML parser in Bun yet, and the indentation gets really confusing sometimes. Also, YAML parsers tend to be slower than JSON parsers (and YAML parsers are also JSON parsers). My favorite YAML fact is that the two-digit [country code for Norway in YAML](https://langdev.stackexchange.com/questions/1123/what-design-trade-offs-led-to-the-norway-problem-in-yaml-and-when-are-they-wo) is parsed as `false`, though this isn't relevant to a lockfile

#### Why JSON with Trailing Commas instead of JSON5?

We don't have a JSON5 parser in Bun, and would like to avoid formats that're slower to parse than JSON

### When will `bun.lock` be released?

Q3.

### What will the migration plan be?

`bun install` will support both `bun.lockb` and `bun.lock` for awhile, but once released, new features will only be supported via `bun.lock`.

#### Do people really edit lockfiles manually?

Yes, for small tweaks it can be important

#### Why not fix merge conflicts via `bun install` instead?

We will support that as well. But, it shouldn't be impossible to do manually.

**Comment by whyman** [comment] 2024-06-14 07:17
Feels like [json5](https://json5.org/) could also be a good choice, that has a real spec at least

**Comment by nolanholden** [comment] 2024-06-14 08:32
Hi, I’ve really enjoyed your great package manager and would like to help as needed. I believe the move to plaintext to ease merge conflicts is best.

My main comment is concerning speed, as I saw a lot of people complaining about this in your Twitter/X post.

You can explore an **efficient encoding**, and maybe turn a 20ms -> 1ms:

A few ideas:
- string lookup table for package names at the top of the file, or even in a separate `bun.lock.map` file. (can even be lazily/manually garbage collected, ie append only, to reduce merge conflicts)
- reference only the compressed names in dep entries
- further, predictably abbreviate package names in the lookup table (offloading the codec to the bun binary)
- explore persistent memory mapping, with a large enough reservation (1M?) that most users never experience a reallocate.

If bun is shipped with a json converter (for ad hoc needs of people who wish to parse this), I imagine nobody will sweat the extra step. (Eg `bun lockfile convert json`)

It’s important we don’t needlessly conflate (a) the switch to plaintext with (b) the switch to having plaintext which is easy to read hermetically per entry, or (c) which has nice default syntax highlighting.

In my experience, while the lockfile is helpful for occasional debugging, not having (b) or (c) would not be a serious thorn in the side. The main present thorn is (a), which takes far less sacrifice to fix.

Hope my comments are welcome and helpful!

**Comment by styfle** [comment] 2024-06-14 10:49
Regarding json5 vs jsonc, there is a related issue with some discussion about tsconfig.json from a few years ago:

- https://github.com/microsoft/vscode/issues/100688

**Comment by anru** [comment] 2024-06-17 11:46
Good design goals from yarn:

1. Must be easy to read by a human
2. Must be easy to diff
3. Must be fast to parse

To achieve 3 it is useful to have a dedicated format and parser. 
Common formats, formats that support many options and functionality require additional logic, branches in the code, etc. which negatively affects the parsing speed.

Diffability at yarn.lock is simply top notch. Yes, commas in JSON fixes the situation from catastrophic to acceptable, but yarn.locks are always more compact and win in readability over JSON files.

The downside of a custom format is that if it is not compatible or is not a subset of some other, more common format, it will be harder to work with it at the user or infrastructure code level.

In any case, this undertaking cannot but rejoice.

**Comment by rhuanbarreto** [comment] 2024-06-17 20:50
This would really unblock bun for being usable in storybooks as parseable outputs are important for it to adopt as a supported package manager. https://github.com/storybookjs/storybook/issues/28164
JSON with trailing commas is good. But it's also important to have a `--json` parameter on the package manager commands so scripts can `JSON.parse` its output.

**Comment by GermanJablo** [comment] 2024-06-29 03:04
I'm not as familiar with the technical implications, but as a user I have to say that YAML makes a lot of sense in a long, auto-generated file like the lock file.

**Comment by nurulhudaapon** [comment] 2024-07-15 20:04
Wondering why just using re-using `package-lock.json` is not an option?

**Comment by rhuanbarreto** [comment] 2024-07-16 06:46
I think it's a good idea to keep a way to support a backwards compatible (package-lock.json) in addition to the current (binary) one. Then people could choose in the bunfig.toml if they are willing to pay the performance penalty in order to be more compatible with the node ecosystem.

**Comment by LitoMore** [comment] 2024-08-19 04:04
Two same lockfile content `bun.lockb` files were generated from different versions of Bun may have different `md5 bun.lockb` results.

This is super annoying with Git.

**Comment by evelant** [comment] 2024-08-19 19:40
Re-using package-lock.json or yarn.lock will cause tooling problems. Lots of things rely on those to detect the package manager (for better or for worse). You'd end up with scripts installing things with yarn or npm if bun were to use the same name and/or format.

**Comment by notramo** [comment] 2024-08-26 10:30
If anyone thinks YAML is a good idea, read this: https://noyaml.com/
Then read all articles the above page links to.

Sure, the basic concept of syntax is great, but there are **too many** pitfalls. That's why there are some simpler configuration languages with similar syntax which retain the same level of readability and diffability, while being simpler and way less error-prone.
https://gura.netlify.app/
https://nestedtext.org/en/latest/
I would bet these are also faster to parse than YAML.

**Comment by evelant** [comment] 2024-08-26 12:29
Maybe not as relevant for a lockfile, but there is some great innovation in better configuration files: https://nickel-lang.org/

**Comment by Jordan-Hall** [comment] 2024-09-26 03:46
If you decide to move to jsonc, does this mean the current binary lock file going to change from yarn lock to the new jsonc. Also is bun going to provide a parser for the new lock file like  yarn does or at least the types like pnpm?

**Comment by hadarziv-army** [comment] 2024-09-27 20:14
Is there any progress on the matter?

It could be a game changer💪🏻

**Comment by jakehamilton** [comment] 2024-10-18 15:56
One additional benefit from a text-based format is the ability for a tool like [Nix](https://nixos.org) to parse it and pull dependencies for reproducible builds. Bun's largest pain point for me is the lack of a way to easily provide package lock information to Nix so that packages can be fetched for use in the sandbox. An awkward conversion of `bun.lockb > yarn.lock > package-lock.json` is possible, but there are some significant issues in the translation which results in some packages missing hash information.

**Comment by jase88** [comment] 2024-11-12 05:47
Another advantage of a text-based approach would be fewer merge conflicts.

Tools like renovate can update buns binary lock files, but merge conflicts arise immediately. Effectively only one update can be merged

**Closed as completed** 2024-12-11 13:05 UTC
Labels: enhancement, bun install

**Comment by adisbladis** [comment] 2025-01-25 07:57
> One additional benefit from a text-based format is the ability for a tool like [Nix](https://nixos.org) to parse it and pull dependencies for reproducible builds. Bun's largest pain point for me is the lack of a way to easily provide package lock information to Nix so that packages can be fetched for use in the sandbox. 

This is still not possible with the current text based lock format because it cannot be parsed by a standard JSON parser.
I'd like to suggest dropping trailing commas from the format and use standard JSON instead so the lock file can be used with standard JSON parsers.

**Comment by kravetsone** [comment] 2025-01-25 08:56
> > One additional benefit from a text-based format is the ability for a tool like [Nix](https://nixos.org) to parse it and pull dependencies for reproducible builds. Bun's largest pain point for me is the lack of a way to easily provide package lock information to Nix so that packages can be fetched for use in the sandbox. 
> 
> This is still not possible with the current text based lock format because it cannot be parsed by a standard JSON parser.
> I'd like to suggest dropping trailing commas from the format and use standard JSON instead so the lock file can be used with standard JSON parsers.

It is problem to use jsonc parser at nix?

**Comment by jakehamilton** [comment] 2025-01-25 11:42
> It is problem to use jsonc parser at nix?

Yes, Nix only includes a standard JSON parser builtin.

**Comment by kravetsone** [comment] 2025-01-25 12:17
> > It is problem to use jsonc parser at nix?
> 
> Yes, Nix only includes a standard JSON parser builtin.

they should include JSONC parser too

trailing comas is important to prevent useless merge conflicts

also configs should be in JSONC

i wait adoption of package.jsonc

**Comment by jakehamilton** [comment] 2025-01-25 16:03
> they should include JSONC parser too
> 
> trailing comas is important to prevent useless merge conflicts
> 
> also configs should be in JSONC
> 
> i wait adoption of package.jsonc

Don't get me wrong, supporting comments and dangling commas is great. But other programs exist that do not support that and it is quite hard to argue that they should all change just to support Bun. Nix builds lots of software (literally everything) and Bun packages currently aren't easily doable because of the lock file format. Previously the binary lock file was an issue for other tools to parse and use, now jsonc is. It is the same issue. It's not really clear to me how comments in a lock file are useful anyway considering the whole thing is auto generated. Dangling commas don't seem entirely necessary for an auto generated file either.

I would like for Nix to have built-in support for jsonc parsing, but you can only pack so many things into one tool before it becomes unmanageable.

**Comment by shinebayar-g** [comment] 2025-01-25 22:10
Or they could've used just `yaml`. ¯\_(ツ)_/¯

**Comment by rhuanbarreto** [comment] 2025-01-27 00:14
Bun as a runtime supports parsing the file directly as a module. It also gives code completion hints by using `@types/bun`. 

Example:

```ts
// As a module import
import lock from "./bun.lock";
console.log(Object.keys(lock.packages));

// As a dynamic import
const lockDynamic = await import("./bun.lock");
console.log(Object.keys(lockDynamic.packages));
```

This code will output the packages used in the whole repo (single project or monorepo).

**Comment by rhuanbarreto** [comment] 2025-01-27 00:31
@Jarred-Sumner I don't remember where this was written but this is worth referencing at the docs page https://bun.sh/docs/install/lockfile#text-based-lockfile
