### ISSUE TITLE
Bun repl crashed

### ISSUE THREAD

**Issue by hal-29** [oven-sh/bun#12088] opened 2024-06-23 16:02 UTC
### How can we reproduce the crash?

I just installed bun on arch linux, and when I  opened bun repl it crashed

### Relevant log output

```shell
➜  ~ bun repl
============================================================
Bun v1.1.16 (bf7b327f) Linux x64
Args: "bun" "bun-repl"
Elapsed: 1ms | User: 0ms | Sys: 5ms
RSS: 1.07GB | Peak: 15.66MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x61902B0AA72F
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.16/lB1bf7b327AA+tlPojmy8Cgtpz3C+ggz3CuouJ20uJyy+y3CA2g5wB+yzqhrB

[1]    38534 illegal hardware instruction (core dumped)  bun repl
➜  ~
```

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on linux x86_64 [BunxCommand]

Segmentation fault at address 0x5C824A75472F

- `??`
- [`semver.zig:268`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/semver.zig#L268>): `src.cli.bunx_command.BunxCommand.exec`
- [`StandaloneModuleGraph.zig:677`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/StandaloneModuleGraph.zig#L677>): `src.cli.Cli.start`
- [`array_list.zig:0`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/deps/zig/lib/std/array_list.zig#L0>): `process.argsAlloc`
- `??`
- `??`
- [`start.zig:487`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/deps/zig/lib/std/start.zig#L487>): `main`

**Comment by kzc** [comment] 2024-06-23 16:47
This is a dup of #11359, although the stack trace in #12088 is slightly better - the function names are correct, but the file names are wrong.

`bun repl` used to work correctly over a month ago, but has been crashing recently. 

Curiously `bun x bun-repl` does work:

```
$ bun x bun-repl -e "console.log(Buffer.from([72,73])+'')"
HI
```

which is odd because they are launched in almost the same way:

https://github.com/oven-sh/bun/blob/314666d8ae67e5cb9f1e1e565062466e76dddfbd/src/cli.zig#L1525-L1541

except for `ctx.debug.run_in_bun = true;` being set in `ReplCommand` for `bun repl`.

**Comment by Jarred-Sumner** [comment] 2024-06-24 05:49
Duplicate of #12070

**Comment by Jarred-Sumner** [comment] 2024-06-24 05:49
To get the fix, please run `bun upgrade --canary`

**Closed as not planned by Jarred-Sumner** 2024-06-24 05:49 UTC
Labels: crash, linux
