### ISSUE TITLE
Bun doesn't log error in docker container, node does

### ISSUE THREAD

**Issue by derekhearst** [oven-sh/bun#9674] opened 2024-03-28 06:23 UTC
### What version of Bun is running?

1.0.35

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

[Fork this repo](https://github.com/derekhearst/ViteBuildFailDockerBun)
run docker build .

### What is the expected behavior?

At RUN bun vite build, the build fails due to prisma not being instantiated. If you uncomment the line above the build will pass 

### Additional information

https://github.com/vitejs/vite/issues/16294#issuecomment-2024352472
I thought this was a vite bug originally, but it's a bun issue.

**Comment by Electroid** [comment] 2024-03-28 15:45
Duplicate of #3827

**Closed as not planned by Electroid** 2024-03-28 15:45 UTC
Labels: bug

**Comment by derekhearst** [comment] 2024-03-28 16:04
While the error is being called from prisma not generating during the install, the bug is that vite doesn't log the error correctly in the build process

**Comment by derekhearst** [comment] 2024-03-28 16:47
> Duplicate of # 3827

In addition to my previous comment, that issue seems to be closed with this PR.
https://github.com/oven-sh/bun/pull/9101
What's also weird is that prisma generate is running after install in the shorter docker file at the end, but not in the larger one.
