### ISSUE TITLE
Bun Upgrade Crashes

### ISSUE THREAD

**Issue by hakkano** [oven-sh/bun#12058] opened 2024-06-22 14:10 UTC
### How can we reproduce the crash?

bun upgrade

### Stack Trace (bun.report)

Bun v1.1.11 ([`4fb6056`](<https://github.com/oven-sh/bun/tree/4fb6056f85c9cf643caa9c2afdefe4917c513fb5>)) on linux x86_64 [UpgradeCommand]

Segmentation fault at address 0x7410C25E1950

- `??`
- [`http.zig:3191`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L3191>): `src.http.handleResponseBodyFromSinglePacket`
- [`http.zig:3176`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L3176>): `src.http.handleResponseBody`
- [`http.zig:2788`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L2788>): `src.http.onData__anon_472662`
- [`http.zig:518`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L518>): `src.deps.uws.NewSocketHandler`
- [`openssl.c:523`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/crypto/openssl.c#L523>): `ssl_on_data`
- [`loop.c:388`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/loop.c#L388>): `us_loop_run_bun_tick`
- [`uws.zig:1278`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/uws.zig#L1278>): `src.http.HTTPThread.processEvents`
- [`http.zig:757`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L757>): `Thread.PosixThreadImpl.spawn__anon_290709.Instance.entryFn`
- `??`

**Comment by Jarred-Sumner** [comment] 2024-06-22 22:39
Duplicate of https://github.com/oven-sh/bun/issues/11516

**Comment by Jarred-Sumner** [comment] 2024-06-22 22:39
This was fixed in Bun v1.1.12. Please reinstall bun via the powershell script:
```powershell
powershell -c "irm bun.sh/install.ps1 | iex"
```

**Closed as completed by Jarred-Sumner** 2024-06-22 22:39 UTC
Labels: crash, linux
