### ISSUE TITLE
bun segfaults when trying to load package `cpu-features`

### ISSUE THREAD

**Issue by gvilums** [oven-sh/bun#9939] opened 2024-04-04 17:11 UTC
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

windows

### What steps can reproduce the bug?

```
bun init
bun install cpu-features
echo "require('cpu-features')" > index.ts
bun index.ts
```

### What is the expected behavior?

nothing happens, or at least a reasonable error message is printed (for reference, this is what bun prints on linux: `bun: symbol lookup error: /tmp/cpufeat/node_modules/cpu-features/build/Release/cpufeatures.node: undefined symbol: node_module_register
`)

### What do you see instead?

```
1 | 'use strict';
2 |
3 | const binding = require('../build/Release/cpufeatures.node');
          ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at C:\test\cpufeat\node_modules\cpu-features\lib\index.js:3:7
      at C:\test\cpufeat\index.ts:1:7
Segmentation fault at address 0x7ffb95a554cc
???:?:?: 0x7ffc00da129b in ??? (ntdll.dll)
???:?:?: 0x7ffc00da0ff6 in ??? (ntdll.dll)
???:?:?: 0x7ffc00da0c9c in ??? (ntdll.dll)
???:?:?: 0x7ffbff057faa in ??? (KERNEL32.DLL)
???:?:?: 0x7ffbfe21bb17 in ??? (ucrtbase.dll)
???:?:?: 0x7ffbfe21bcd8 in ??? (ucrtbase.dll)
???:?:?: 0x7ff6e7701c58 in ??? (bun.exe)
???:?:?: 0x7ff6e74739ab in ??? (bun.exe)
???:?:?: 0x7ff6e778ceab in ??? (bun.exe)
???:?:?: 0x7ff6e9c061ca in ??? (bun.exe)
???:?:?: 0x7ff6e7701b52 in ??? (bun.exe)
???:?:?: 0x7ff6e7704d1a in ??? (bun.exe)
???:?:?: 0x7ff6e771898e in ??? (bun.exe)
???:?:?: 0x7ff6e7441603 in ??? (bun.exe)
???:?:?: 0x7ff6e9fc3ec3 in ??? (bun.exe)
???:?:?: 0x7ffbff05257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffc00daaa57 in ??? (ntdll.dll)
```

### Additional information

With debug info:
```
1 | 'use strict';
2 |
3 | const binding = require('../build/Release/cpufeatures.node');
                        ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at internalRequire (:1:21)
      at C:\test\cpufeat\node_modules\cpu-features\lib\index.js:3:7
      at require (:1:21)
      at C:\test\cpufeat\index.ts:1:7
Segmentation fault at address 0x7ffb95a554cc
???:?:?: 0x7ffc00da129b in ??? (ntdll.dll)
???:?:?: 0x7ffc00da0ff6 in ??? (ntdll.dll)
???:?:?: 0x7ffc00da0c9c in ??? (ntdll.dll)
???:?:?: 0x7ffbff057faa in ??? (KERNEL32.DLL)
???:?:?: 0x7ffbfe21bb17 in ??? (ucrtbase.dll)
???:?:?: 0x7ffbfe21bcd8 in ??? (ucrtbase.dll)
C:\bun\src\__global.zig:99:15: 0x7ff79f4cb641 in exitWide (bun-zig.o)
    std.c.exit(@bitCast(code));
              ^
C:\bun\src\__global.zig:95:13: 0x7ff79f0d5eb4 in exit (bun-zig.o)
    exitWide(@as(u32, code));
            ^
C:\bun\src\bun_js.zig:287:32: 0x7ff79fa708d3 in start (bun-zig.o)
                    Global.exit(1);
                               ^
C:\bun\src\bun.js\javascript.zig:105:21: 0x7ff79f596ef5 in callback (bun-zig.o)
            Function(context);
                    ^
C:\bun\src\bun.js\bindings\bindings.cpp:4632:0: 0x7ff7a1b3b3f4 in JSC__VM__holdAPILock (bindings.cpp.obj)
    callback(ctx);

C:\bun\src\bun.js\bindings\bindings.zig:5539:14: 0x7ff79f133858 in holdAPILock (bun-zig.o)
        cppFn("holdAPILock", .{ this, ctx, callback });
             ^
C:\bun\src\bun_js.zig:248:35: 0x7ff79f4cb443 in boot (bun-zig.o)
        vm.global.vm().holdAPILock(&run, callback);
                                  ^
C:\bun\src\cli.zig:1939:23: 0x7ff79f4f72fa in maybeOpenWithBunJS (bun-zig.o)
        BunJS.Run.boot(
                      ^
C:\bun\src\cli.zig:1804:47: 0x7ff79f4f24be in start (bun-zig.o)
                        if (maybeOpenWithBunJS(&ctx)) {
                                              ^
C:\bun\src\cli.zig:59:22: 0x7ff79f073ac4 in start__anon_5651 (bun-zig.o)
        Command.start(allocator, log) catch |err| {
                     ^
C:\bun\src\main.zig:55:22: 0x7ff79f071498 in main (bun-zig.o)
    bun.CLI.Cli.start(bun.default_allocator, MainPanicHandler);
                     ^
C:\bun\src\deps\zig\lib\std\start.zig:484:101: 0x7ff79f0711e3 in main (bun-zig.o)
    return @call(.always_inline, callMainWithArgs, .{ @as(usize, @intCast(c_argc)), @as([*][*:0]u8, @ptrCast(c_argv)), envp });
                                                                                                    ^
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0: 0x7ff7a3cf5123 in __scrt_common_main_seh (msvcrt.lib)
???:?:?: 0x7ffbff05257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffc00daaa57 in ??? (ntdll.dll)
```

**Comment by Electroid** [comment] 2024-04-09 00:03
Duplicate of #9633

**Closed as not planned by Electroid** 2024-04-09 00:03 UTC
Labels: bug
