### ISSUE TITLE
libp2p package is not working with Bun

### ISSUE THREAD

**Issue by ansarizafar** [oven-sh/bun#3877] opened 2023-07-29 08:41 UTC
### What version of Bun is running?

0.7.1

### What platform is your computer?

Linux 5.19.0-50-generic x86_64 x86_64

### What steps can reproduce the bug?

I have installed libp2p, @libp2p/webtransport, @chainsafe/libp2p-noise packages with bun add command and I am trying to run  following code with bun run index.js command
```javascript
import { createLibp2p } from 'libp2p'
import { webTransport } from '@libp2p/webtransport'
import { noise } from '@chainsafe/libp2p-noise'

const node = await createLibp2p({
  transports: [webTransport()],
  connectionEncryption: [noise()],
 
})

// start libp2p
  await node.start()
  console.log('libp2p has started')

  // print out listening addresses
  console.log('listening on addresses:')
  node.getMultiaddrs().forEach((addr) => {
    console.log(addr.toString())
  })

  // stop libp2p
  await node.stop()
  console.log('libp2p has stopped')
```

### What is the expected behavior?

Code is working with Nodejs and it should run without error with Bun

### What do you see instead?

Error message
```
  origin[keys[i]] = add[keys[i]];
344 |   return origin;
345 | }, kCustomPromisifiedSymbol = Symbol.for("util.promisify.custom"), promisify = function promisify2(original) {
346 |   if (typeof original !== "function")
347 | 
348 |     throw new TypeError('The "original" argument must be of type Function');
             ^
TypeError: The "original" argument must be of type Function
      at promisify2 (node:util:348:10)
      at /home/zafaransari/projects/p2p/node_modules/@libp2p/crypto/dist/src/keys/ed25519.js:5:16
```

**Comment by Electroid** [comment] 2023-07-30 14:09
Looks like this is because Bun is missing support for a Node.js feature: https://nodejs.org/api/util.html#custom-promisified-functions

**Comment by sirenkovladd** [comment] 2023-07-30 14:39
Also in <cut>/node_modules/@libp2p/crypto/dist/src/keys/ed25519.js:5:16
```js
const keypair = promisify(crypto.generateKeyPair);
```

Bun, doesn't support `crypto.generateKeyPair` yet, I'll look into that

**Comment by efossvold** [comment] 2023-09-12 22:48
Any update on this? Having a similar issue on Bun 1.0.1 with the following code.

```js
import { createGrpcTransport } from '@bufbuild/connect-node'

createGrpcTransport({
  httpVersion: '2',
  baseUrl: 'http://127.0.0.1:8080',
})
```

∨∨∨

```360 |   var keys = Object.keys(add), i = keys.length;
361 |   while (i--)
362 |     origin[keys[i]] = add[keys[i]];
363 |   return origin;
364 |
365 | }, kCustomPromisifiedSymbol = Symbol.for("util.promisify.custom"), promisify = function promisify2(original) {
```

**Comment by efossvold** [comment] 2023-09-13 21:01
I've never used libp2p, but a quick glance at the [specs](https://github.com/libp2p/specs/) says it uses protobuf to describe the protocols used.

> The protocols described below all use [protocol buffers](https://developers.google.com/protocol-buffers/docs/proto?hl=en) (aka protobuf) to define message schemas.

So possibly there's some gRPC in there which is built on top of HTTP2. According this [this comment (in #4414)](https://github.com/oven-sh/bun/issues/4414#issuecomment-1700109757), Bun does not support HTTP2 yet, which also explains why the code in my [previous comment](https://github.com/oven-sh/bun/issues/3877#issuecomment-1716621701) doesn't work as it uses @bufbuild/connect-node, a gRPC lib.

**Comment by Electroid** [comment] 2023-10-27 21:59
Duplicate of #5122

**Closed as not planned by Electroid** 2023-10-27 21:59 UTC
Labels: bug, node.js
