### ISSUE TITLE
Bun add doesn't respect install.exact from bunfig.toml

### ISSUE THREAD

**Issue by kvnwolf** [oven-sh/bun#5736] opened 2023-09-19 12:21 UTC
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

1. Create a bun project
2. Add `exact.true` to `bunfig.toml`

**bunfig.toml:**

```toml
[install]
exact = true
```

### What is the expected behavior?

Installing new dependencies (`bun add myDep`) adds the dependency with the exact version.	

### What do you see instead?

The dependency is being added with the caret range.

**Comment by present-g** [comment] 2023-09-19 20:18
I have the same problem too, any news?

**Comment by casret** [comment] 2023-09-20 01:08
I don't think bunfig.toml works at all.

**Comment by present-g** [comment] 2023-09-20 07:58
@casret, part of bunfig.toml works, I use `print = "yarn"` and it works

```toml
[install.lockfile]
print = "yarn"
```

**Comment by Electroid** [comment] 2023-10-03 18:56
Duplicate of #5647

**Closed as not planned by Electroid** 2023-10-03 18:56 UTC
Labels: bug, bun install
