### ISSUE TITLE
Crash in drainMicrotasks

### ISSUE THREAD

**Issue by JiangJie** [oven-sh/bun#13004] opened 2024-08-01 14:41 UTC
### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on linux x86_64 [TestCommand]

Segmentation fault at address 0x0000001A

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `JSC::runJSMicrotask`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`event_loop.zig:849`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/event_loop.zig#L849>): `src.bun.js.event_loop.EventLoop.tickQueueWithCount__anon_119012`
- [`event_loop.zig:1251`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/event_loop.zig#L1251>): `src.bun.js.event_loop.EventLoop.tick`
- [`event_loop.zig:1500`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/event_loop.zig#L1500>): `src.bun.js.event_loop.EventLoop.waitForPromise`

**Comment by Jarred-Sumner** [comment] 2024-08-08 19:42
Closing due to lack of reproduction. If we find another issue with a similar stacktrace we will link it

**Closed as not planned by Jarred-Sumner** 2024-08-08 19:42 UTC
Labels: needs repro, crash, linux

**Comment by eliseumds** [comment] 2024-08-09 08:22
Crashing here as well ("bun test" inside GitHub actions):

Bun v1.1.22 ([`df33f2b`](<https://github.com/oven-sh/bun/tree/df33f2b2a264912c7a742d0c03587082415fbba6>)) on linux x86_64_baseline [TestCommand]

Segmentation fault at address 0x00000001

- [`ModuleLoader.cpp:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/bun.js/bindings/ModuleLoader.cpp#L0>): `Bun::fetchESMSourceCodeAsync`
- [`ZigGlobalObject.cpp:3963`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/bun.js/bindings/ZigGlobalObject.cpp#L3963>): `Zig::GlobalObject::moduleLoaderFetch`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/ld-temp.o#L0>): `JSC::moduleLoaderFetch`

**Comment by Jarred-Sumner** [comment] 2024-08-09 08:24
@eliseumds can you file a new issue and include some code to reproduce? The crash report there says it crashed while loading an ESM module and not much else, so it's really hard for us to take any action on

**Comment by eliseumds** [comment] 2024-08-09 09:03
@Jarred-Sumner yeah sorry I've been trying, I've setup a Docker container using the same Ubuntu, same NodeJS, same Yarn, same Bun and the same project source code but I still can't reproduce it. I can't reproduce it in my MacOS Sonoma either. There might be something else inside Github Actions' image that is causing it. This is all the info I have for now:

```
__tests__/Uploader-test.tsx:
  ============================================================
  Bun Canary v1.1.22-canary.96 (df33f2b2) Linux x64 (baseline)
  Linux Kernel v6.5.0 | glibc v2.35
  CPU: sse42 popcnt avx avx2
  Args: "bun" "test" "--preload" "/bin/bunTestsSetup.ts" "/__tests__/*"...
  Features: jsc dotenv tsconfig(26) 
  Builtins: "node:buffer" "node:child_process" "node:crypto" "node:fs" "node:http" "node:https" "node:net" "node:os" "node:path" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" 
  Elapsed: 1491ms | User: 1500ms | Sys: 169ms
  RSS: 0.98GB | Peak: 0.31GB | Commit: 0.98GB | Faults: 0
  
  panic(main thread): Segmentation fault at address 0x1
  oh no: Bun has crashed. This indicates a bug in Bun, not your code.
  
  To send a redacted crash report to Bun's team,
  please file a GitHub issue using the link below:
  
   https://bun.report/1.1.22/Bt2df33f2bAiogggCu+6/iE+xyQg1uy9Dmh+q6Dsk7xgF_____A2AC
```

**Comment by Jarred-Sumner** [comment] 2024-08-09 09:06
If you can share the code that’s running, we can run it with guard malloc enabled and that will likely make it easier to reproduce 

if you want to try that on your mac, you can do
 ```sh
DYLD_INSERT_LIBRARIES=/usr/lib/libgmalloc.dylib MALLOC_PROTECT_BEFORE=1 MallocScribble=1 MallocGuardEdges=1 MALLOC_FILL_SPACE=1 MALLOC_STRICT_SIZE=1 bun test <…>
```

**Comment by eliseumds** [comment] 2024-08-09 09:29
@Jarred-Sumner seems to work, nice! It wasn't crashing 100% of the time though, I'll report back if it resurfaces, thanks.

<img width="487" alt="image" src="https://github.com/user-attachments/assets/eba8e66a-1af4-410f-9c3a-fc4746827f7e">
