### ISSUE TITLE
toMatchSnapshot breaks when the snapshot contains non latin symbols and `

### ISSUE THREAD

**Issue by LevanKvirkvelia** [oven-sh/bun#8390] opened 2024-01-23 04:06 UTC
### What version of Bun is running?

1.0.25+a8ff7be64

### What steps can reproduce the bug?

Only first two tests will fail
```js
import { expect, test } from "bun:test";

test("emoji test", () => {
  expect(`👦🏻 \``).toMatchSnapshot();
});

test("cyrillic test", () => {
  expect(`привет \``).toMatchSnapshot();
});

test("simple test", () => {
  expect(`\``).toMatchSnapshot();

  expect(`👦🏻 `).toMatchSnapshot();
  expect(`привет `).toMatchSnapshot();

  expect(`\``).toMatchSnapshot();
  expect(`hi `).toMatchSnapshot();
  expect(`hi \``).toMatchSnapshot();
});
```

**Comment by LevanKvirkvelia** [comment] 2024-01-23 04:07
Probably related to:
https://github.com/oven-sh/bun/issues/3769
https://github.com/oven-sh/bun/issues/4967

**Comment by Electroid** [comment] 2024-01-23 16:47
Duplicate of #5272

**Closed as not planned by Electroid** 2024-01-23 16:47 UTC
Labels: bug, bun:test
