### ISSUE TITLE
Segmentation fault at address 0x0

### ISSUE THREAD

**Issue by supfiger** [oven-sh/bun#11529] opened 2024-06-02 01:12 UTC
### How can we reproduce the crash?

I do not know.
But I faced the crash by running a bundled (not source) version my application.

### Relevant log output

```shell
Bun Canary v1.1.12-canary.1 (43f0913c) macOS x64
Args: "/usr/local/bin/bun" "run" "./dist/dev/index.js"
Features: jsc Bun.stdin(2) bunfig dotenv fetch(4) http_server spawn transpiler_cache(2) tsconfig WebSocket 
Builtins: "abort-controller" "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:net" "node:os" "node:path" "node:process" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:punycode" "node-fetch" 
Elapsed: 11911ms | User: 633ms | Sys: 242ms
RSS: 92.28MB | Peak: 92.28MB | Commit: 1.07GB | Faults: 4207


panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

Command was killed with SIGILL (Invalid machine instruction): /usr/local/bin/bun run ./dist/dev/index.js
```

### Stack Trace (bun.report)

Bun v1.1.12-canary ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on macos x86_64 [RunCommand]

Segmentation fault at address 0x00000000

- *2 unknown/js code*
- `Bun::formatStackTrace`
- `computeErrorInfoWithoutPrepareStackTrace`
- `computeErrorInfo`
- `WTF::Detail::CallableWrapper<WTF::String (...)(...), WTF::String, JSC::VM&, WTF::Vector<JSC::StackFrame, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, unsigned int&, unsigned int&, WTF::String&, JSC::JSObject*>::call`
- `JSC::ErrorInstance::computeErrorInfo`
- `JSC::Heap::runEndPhase`
- `JSC::Heap::runCurrentPhase`
- `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`

Features: jsc, Bun.stdin, bunfig, dotenv, fetch, http\_server, spawn, transpiler\_cache, tsconfig, WebSocket

**Comment by Jarred-Sumner** [comment] 2024-06-02 01:36
Can you paste some code for us to run? The error has to do with printing stacktraces in JS. But it’s really hard for us to reproduce this or fix it without an exact line number

**Comment by supfiger** [comment] 2024-06-02 07:38
> Can you paste some code for us to run? The error has to do with printing stacktraces in JS. But it’s really hard for us to reproduce this or fix it without an exact line number

Sorry, I cannot share the code.

But I could share some context, like project deps (package.json) and stuff like this. You need it?

**Comment by Jarred-Sumner** [comment] 2024-06-06 12:28
Duplicate of #11568

**Comment by Jarred-Sumner** [comment] 2024-06-06 12:29
We need some way to trigger the crash, which happens when the finalizer for an `Error` object is called and an exception is thrown.

In the meantime, please follow along in #11568 as soon as we get some way to reproduce this

**Closed as not planned by Jarred-Sumner** 2024-06-06 12:29 UTC
Labels: crash
