### ISSUE TITLE
Discord.js segfault after login

### ISSUE THREAD

**Issue by rover-001** [oven-sh/bun#11489] opened 2024-05-31 04:46 UTC
### How can we reproduce the crash?

all i did was use fs to get my commands from the commands/messageCommands/{subfolders}, everything works fine when i use npm to run the bot.

### JavaScript/TypeScript code that reproduces the crash?

```shell
import { Client, GatewayIntentBits, Message, User } from "discord.js";
import { env } from "bun"
import fs from "fs";
import path from "path";

const client = new Client({
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent]
});

client.on("ready", () => {
    if (client.user) {
      console.log(`Logged in as ${client.user.tag}`);
    }
});


const readFiles = (dir: string) => {
    const files = fs.readdirSync(dir);
    files.forEach(file => {
        const filePath = path.join(dir, file);
        const stat = fs.lstatSync(filePath);
        if (stat.isDirectory()) {
            readFiles(filePath);
        } else if (file.endsWith(".ts")) {
            const command = require(filePath);
            command.setup(client);
        }
    });
};

readFiles(path.join(__dirname, "commands/messageCommands"));


client.login(env.DISCORD_TOKEN);
```

### Relevant log output

```shell
Bun v1.1.7 (b0b7db5c) Windows x64
Args: "C:\Users\{removed the username}\.bun\bin\bun.exe", "run", "main.ts"
Features: jsc Bun.stdin(2) dotenv fetch transpiler_cache(3) tsconfig(4) WebSocket 
Builtins: "bun:main" "node:buffer" "node:events" "node:fs" "node:fs/promises" "node:http" "node:path" "node:string_decoder" "node:timers" "node:timers/promises" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "undici" "ws" 
Elapsed: 1399ms | User: 93ms | Sys: 78ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 0.18GB | Faults: 39320

panic(main thread): Segmentation fault at address 0xFFFFFFFFFFFFFFFF
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.7/wr1b0b7db5AqoiggV+g4g1CuxgyvC82uje41ngeg7kgekp9xG2zn3uC6y+pF0x1qF40uvFA2DD

error: script "start" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](<https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- `??`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`
- [`uws.zig:2619`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/uws.zig#L2619>): `run`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.js/bindings/shimmer.zig#L186>): `cppFn`
- [`run_command.zig:1402`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli/run_command.zig#L1402>): `exec`
- [`cli.zig:1733`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L1733>): `start`

**Comment by Sayrix** [comment] 2024-05-31 20:53
Try upgrading to the latest version and then check if the error is still here

**Comment by ItzGG** [comment] 2024-06-01 05:47
I am on the latest version. The error still persists.

**Comment by Jarred-Sumner** [comment] 2024-06-01 05:56
likely related to `Worker` which is not stable yet

**Comment by shivero** [comment] 2024-06-01 10:44
For me issue was the same when tried to use `bun upgrade` from 1.1.11 to 1.1.12 
- resolved by just running manually `powershell -c "irm bun.sh/install.ps1|iex"`

**Comment by Jarred-Sumner** [comment] 2024-06-01 10:45
> For me issue was the same when tried to use `bun upgrade` from 1.1.11 to 1.1.12
> 
> * resolved by just running manually `powershell -c "irm bun.sh/install.ps1|iex"`

While these are both Segmentation faults, the cause is different. Sort of like `undefined is not an object`

**Comment by Jarred-Sumner** [comment] 2024-06-06 12:03
This is either a duplicate of https://github.com/oven-sh/bun/issues/11617 (a bug on Windows when an error is thrown while reading a file via Bun.file(), or it was fixed via https://github.com/oven-sh/bun/pull/11635 and https://github.com/oven-sh/bun/pull/11494. 

If you're still running into this issue after Bun v1.1.13 (or in the meantime, try `bun upgrade --canary`), please let us know and we'll re-open the issue.

**Closed as completed by Jarred-Sumner** 2024-06-06 12:03 UTC
Labels: crash
