### ISSUE TITLE
NotImplementedError: node:cluster is not yet implemented

### ISSUE THREAD

**Issue by joy-stacks** [oven-sh/bun#11834] opened 2024-06-13 08:44 UTC
### What version of Bun is running?

1.1.13

### What platform is your computer?

NotImplementedError: node:cluster is not yet implemented

### What steps can reproduce the bug?

NotImplementedError: node:cluster is not yet implemented

### What is the expected behavior?

NotImplementedError: node:cluster is not yet implemented

### What do you see instead?

NotImplementedError: node:cluster is not yet implemented

### Additional information

NotImplementedError: node:cluster is not yet implemented

**Comment by Jarred-Sumner** [comment] 2024-06-13 09:23
Duplicate of https://github.com/oven-sh/bun/issues/2428

**Comment by Jarred-Sumner** [comment] 2024-06-13 09:24
@nektro is working on it. Please follow along in https://github.com/oven-sh/bun/issues/2428

**Closed as not planned by Jarred-Sumner** 2024-06-13 09:24 UTC
Labels: bug, needs triage
