### ISSUE TITLE
process 'uncaughtException' event is not triggered

### ISSUE THREAD

**Issue by ArtemGovorov** [oven-sh/bun#5219] opened 2023-09-13 06:21 UTC
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 21.6.0 x86_64 i386

### What steps can reproduce the bug?

test.js
```
process.on('uncaughtException', () => {
    console.log('Caught')
});

throw new Error('boom')
```

node
```
$ node test.js
Caught
```

bun
```
$ bun run test.js
1 |   console.log("Caught");
2 | });
3 | 
4 | throw new Error("boom");
         ^
error: boom
      at ./test.js:63:6
```

### What is the expected behavior?

process 'uncaughtException' event is raised and handled

**Comment by ArtemGovorov** [comment] 2023-09-13 06:39
The same happens to `process` `unhandledRejection` event:

```js
process.on('unhandledRejection', () => {
    console.log('Caught')
});
new Promise((y,n) => {
    n(new Error('boom'));
})
```

**Comment by Electroid** [comment] 2023-10-27 22:26
Duplicate of #429

**Closed as not planned by Electroid** 2023-10-27 22:26 UTC
Labels: bug, node.js
