### ISSUE TITLE
Bun crashed

### ISSUE THREAD

**Issue by masumrpg** [oven-sh/bun#11524] opened 2024-06-01 14:58 UTC
### Stack Trace (bun.report)

Bun v1.1.11 ([`4fb6056`](<https://github.com/oven-sh/bun/tree/4fb6056f85c9cf643caa9c2afdefe4917c513fb5>)) on linux x86_64 [UpgradeCommand]

Segmentation fault at address 0x74B1017D1950

- `??`
- [`http.zig:3381`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L3381>): `src.http.handleResponseBodyChunkedEncoding`
- [`http.zig:2801`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L2801>): `src.http.onData__anon_472662`
- [`http.zig:518`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L518>): `src.deps.uws.NewSocketHandler`
- [`openssl.c:523`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/crypto/openssl.c#L523>): `ssl_on_data`
- [`loop.c:388`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/loop.c#L388>): `us_loop_run_bun_tick`
- [`uws.zig:1278`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/deps/uws.zig#L1278>): `src.http.HTTPThread.processEvents`
- [`http.zig:757`](<https://github.com/oven-sh/bun/blob/4fb6056f85c9cf643caa9c2afdefe4917c513fb5/src/http.zig#L757>): `Thread.PosixThreadImpl.spawn__anon_290709.Instance.entryFn`
- `??`

**Comment by Jarred-Sumner** [comment] 2024-06-02 00:49
Duplicate of #11522 

Fixed in Bun v1.1.12

**Closed as not planned by Jarred-Sumner** 2024-06-02 00:49 UTC
Labels: crash

**Comment by masumrpg** [comment] 2024-06-16 16:13
thanks
