### ISSUE TITLE
Deploying sveltekit + bun on cloudflare resulted in error: lockfile had changes, but lockfile is frozen

### ISSUE THREAD

**Issue by on1force** [oven-sh/bun#6043] opened 2023-09-25 15:52 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

Make a simple landing page with sveltekit and bun.
`bun create svelte@latest`

change the sveltekit adapter to `@sveltejs/adapter-cloudflare`

deploy the sveltekit project to cloudflare pages

### What is the expected behavior?

Deployment success.

### What do you see instead?

error: lockfile had changes, but lockfile is frozen

### Additional information

the dployment logs is trying to install --frozen-lockfile and bun, maybe it's still not supported ?

Full Logs

```
06:21:22.413 | Cloning repository...
06:21:23.763 | From https://github.com/on1force/phosphor
06:21:23.764 | * branch            52fc71eca6f6c63f5eedd79276b4df4ebe46e407 -> FETCH_HEAD
06:21:23.764 |  
06:21:23.824 | HEAD is now at 52fc71e change adapter to cloudflare
06:21:23.824 |  
06:21:23.943 |  
06:21:23.978 | Success: Finished cloning repository files
06:21:24.779 | Detected the following tools from environment: nodejs@16.20.2, bun@1.0.1
06:21:24.780 | Installing nodejs 16.20.2
06:21:24.885 | nodejs 16.20.2 is already installed
06:21:25.555 | Installing project dependencies: bun install --frozen-lockfile
06:21:25.884 | bun install v1.0.1 (31aec4eb)
06:21:25.885 | error: lockfile had changes, but lockfile is frozen
06:21:25.890 | Error: Exit with error code: 1
06:21:25.890 | at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
06:21:25.891 | at Object.onceWrapper (node:events:652:26)
06:21:25.891 | at ChildProcess.emit (node:events:537:28)
06:21:25.891 | at ChildProcess._handle.onexit (node:internal/child_process:291:12)
06:21:25.899 | Failed: build command exited with code: 1
06:21:27.099 | Failed: error occurred while running build command
```

**Comment by Jarred-Sumner** [comment] 2023-09-25 15:57
This should be fixed in 1.0.4

**Comment by Jarred-Sumner** [comment] 2023-09-25 15:58
But for now you can do bun upgrade —canary

**Comment by Electroid** [comment] 2023-09-25 16:41
Also: Duplicate of #5858

**Comment by on1force** [comment] 2023-09-25 19:10
will try on my next project. hasn't even been a month or so when I was installing 1.0.0 and it's already 1.0.4.. thanks guys!

**Comment by smastrom** [comment] 2023-09-25 19:19
It happens to me as well a new build is triggered on cloudflare after push. So far the way I found to fix this is to re-create the lockfile like this:

- `rm -rf node_modules bun.lockb`
- `bun install`
- `bun install --no-frozen-lockfile`
- Push changes

**Comment by smastrom** [comment] 2023-09-25 19:19
It happens to me as well if a new build is triggered on cloudflare after push. So far the way I found to fix this is to re-create the lockfile like this:

- `rm -rf node_modules bun.lockb`
- `bun install`
- `bun install --no-frozen-lockfile`
- Push changes

**Closed as completed** 2023-09-25 23:09 UTC
Labels: bug, bun install
