### ISSUE TITLE
dyld[48878]: missing symbol called

### ISSUE THREAD

**Issue by trongbinhhei** [oven-sh/bun#8724] opened 2024-02-06 13:46 UTC
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

`db.ts`
``` typescript
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
const sqlite = new Database('sqlite.db');
export const db = drizzle(sqlite);
```

I got error when run `bun run db.ts`

### What is the expected behavior?

Create `sqlite.db`

### What do you see instead?

 bun run db.ts
dyld[54012]: missing symbol called
[1]    54012 killed     bun run db.ts

**Comment by Electroid** [comment] 2024-02-06 17:27
Duplicate of https://github.com/oven-sh/bun/issues/4290

**Comment by Electroid** [comment] 2024-02-06 17:28
`better-sqlite3` uses the V8 C++ API, which we do not currently implement. We could do it, but it's not on our priority list right now. In the interim, we'd suggest using `bun:sqlite`, which has an API that is almost identical to better-sqlite3.

**Closed as not planned by Electroid** 2024-02-06 17:27 UTC
Labels: bug
