### ISSUE TITLE
Remove the --bun flag

### ISSUE THREAD

**Issue by birkskyum** [oven-sh/bun#12184] opened 2024-06-26 20:21 UTC
### What is the problem this feature would solve?

It's getting really tiring to remember to add the `--bun` everywhere

### What is the feature you are proposing to solve the problem?

Just default to bun.. if necessary, add a `--node` flag for compat.

**Comment by paperdave** [comment] 2024-06-27 10:08
duplicate of #4464.

note currently you can put in `bunfig.toml` `run.bun = true`: https://bun.sh/docs/runtime/bunfig#run-bun-auto-alias-node-to-bun

but we need to make this the default

**Closed as not planned by paperdave** 2024-06-27 10:08 UTC
Labels: enhancement

**Comment by birkskyum** [comment] 2024-06-27 10:28
Thanks, couldn't find that issue
