### ISSUE TITLE
Bun Version Manger - BVM for windows & linux

### ISSUE THREAD

**Issue by aliahadmd** [oven-sh/bun#7992] opened 2024-01-05 07:03 UTC
### What is the problem this feature would solve?

Version manager is very important and i think it would be great with official support 

### What is the feature you are proposing to solve the problem?

The feature is like nvm that can easily install in computer and can be maintain like Bun install version , Bun add global version Bun add local version.

**Comment by Electroid** [comment] 2024-01-05 13:53
Duplicate of #3917

**Closed as not planned by Electroid** 2024-01-05 13:53 UTC
Labels: enhancement
