### ISSUE TITLE
Error using Bun.js

### ISSUE THREAD

**Issue by jeremiasbots** [oven-sh/bun#15422] opened 2024-11-26 14:37 UTC
### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on windows x86_64 [AutoCommand]

**panic**: attempt to use null value

- [`test_command.zig:1049`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli/test_command.zig#L1049>): `BunTest__shouldGenerateCodeCoverage`
- [`ZigSourceProvider.cpp:86`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/bun.js/bindings/ZigSourceProvider.cpp#L86>): `Zig::SourceProvider::create`
- [`utility:762`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/include/utility#L762>): `std::exchange`
- [`ModuleLoader.cpp:883`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/bun.js/bindings/ModuleLoader.cpp#L883>): `Bun::fetchESMSourceCodeAsync`
- [`ZigGlobalObject.cpp:4232`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/bun.js/bindings/ZigGlobalObject.cpp#L4232>): `Zig::GlobalObject::moduleLoaderFetch`
- [`JSModuleLoader.cpp:277`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSModuleLoader.cpp#L277>): `JSC::JSModuleLoader::fetch`
- [`JSModuleLoader.cpp:486`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSModuleLoader.cpp#L486>): `JSC::moduleLoaderFetch`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stderr, http\_server, jsc, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6006746561/">BUN-759</a></strong></sub>

**Comment by 190n** [comment] 2024-11-26 23:41
Duplicate of #15409

**Closed as not planned** 2024-11-26 23:41 UTC
Labels: crash, windows
