### ISSUE TITLE
Support `apt-get install bun`

### ISSUE THREAD

**Issue by remcohaszing** [oven-sh/bun#4471] opened 2023-09-04 08:08 UTC
### What is the problem this feature would solve?

As an Ubuntu / Debian / Pop!_OS user, I would like to install Bun using the builtin package manager: `apt` (aka `apt-get`). This means it will be kept up-to-date automatically with system dependencies.

### What is the feature you are proposing to solve the problem?

Host a PPA

### What alternatives have you considered?

Many projects use https://launchpad.net. Also a lot of projects use a custom domain.

**Comment by Electroid** [comment] 2023-09-04 18:33
Yep, this is something we definitely want to support!

**Comment by Electroid** [comment] 2023-10-20 20:22
Duplicate of #862

**Closed as not planned by Electroid** 2023-10-20 20:22 UTC
Labels: enhancement
