### ISSUE TITLE
Prisma Cannot find package

### ISSUE THREAD

**Issue by lassejlv** [oven-sh/bun#6115] opened 2023-09-27 21:17 UTC
### What version of Bun is running?

latest

### What platform is your computer?

Using railway.app

### What steps can reproduce the bug?

Getting this error while using a dockerfile for my project using prisma.

```bash
error: Cannot find module ".prisma/client/index" from "/usr/src/app/node_modules/@prisma/client/index.js"
```

here is my dockerfile

```docker
# Use the official Bun image
FROM oven/bun:latest

# Set the Docker working directory as /usr/src/app
WORKDIR /usr/src/app

# Copy everything from the current directory into Docker's /usr/src/app
COPY . .

RUN bun install

# Run the project
CMD bunx prisma generate && bun run src/index.js
```

### What is the expected behavior?

Install packages, and generate schema. Using Mongodb with prisma. And run my project

**Comment by Electroid** [comment] 2023-09-27 22:08
Duplicate of #4959

**Comment by Electroid** [comment] 2023-09-27 22:08
This is likely an issue where the prisma `postinstall` is not being run, check the linked issue for a temporary workaround.

**Closed as completed by Electroid** 2023-09-27 22:08 UTC
Labels: bug, bun install

**Comment by lassejlv** [comment] 2023-09-28 05:35
@Electroid still getting the same issue

**Comment by Jarred-Sumner** [comment] 2023-12-12 07:32
Fixed by @dylan-conway and @paperdave in #7132

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.
