### ISSUE TITLE
Big data subcontract transmission data frame will be corrupted. Why not fix. Isn't that more serious?

### ISSUE THREAD

**Issue by eyesspace** [oven-sh/bun#11718] opened 2024-06-09 03:10 UTC
### What version of Bun is running?

1.1.13

### What platform is your computer?

Darwin 23.0.0 x86_64 i386

### What steps can reproduce the bug?

Source bug #5627

              I created a minimal application to demonstrate the problem https://github.com/acuminous/amqplib-764. The issue is intermittent, but increasingly more likely the larger the payload ~affects payloads that are over the configurable maximum frame size~. RabbitMQ splits large payloads across multiple frames, and when using Bun, they are getting corrupted, with bytes from the frames appearing to be duplicated and interleaved. As can be seen the example this results in a number of different problems from misidentifying the frame type, to the frame's payload size not matching the size specified in the frame header.

**Comment by Jarred-Sumner** [comment] 2024-06-10 07:38
Thank you for the reproduction - its very helpful.

**Comment by Jarred-Sumner** [comment] 2024-06-10 07:38
Duplicate of #5627

**Comment by Jarred-Sumner** [comment] 2024-06-10 07:38
Please follow along in #5627. We will fix it.

**Closed as not planned by Jarred-Sumner** 2024-06-10 07:38 UTC
Labels: bug, needs triage
