### ISSUE TITLE
Segmentation fault on Bun.file('/proc/self/cmdline').text()

### ISSUE THREAD

**Issue by StanislavNikolov** [oven-sh/bun#6505] opened 2023-10-14 12:06 UTC
### What version of Bun is running?

1.0.6

### What platform is your computer?

Linux 6.1.0-13-amd64 x86_64 unknown

### What steps can reproduce the bug?

```sh
echo "Bun.file('/proc/self/cmdline').text()" > crash.ts
bun crash.ts
```

### What is the expected behavior?

Nothing to happen, since nothing is printed.

### What do you see instead?

Segmentation fault (core dumped)

### Additional information

Possibly the null bytes in the file (cmdline)?

**Comment by Electroid** [comment] 2023-10-16 16:53
Duplicate of #6371

**Closed as not planned by Electroid** 2023-10-16 16:53 UTC
Labels: bug, bun.js
