### ISSUE TITLE
swipe between "dependencies" and "devDependencies"

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#7286] opened 2023-11-23 10:39 UTC
### What is the problem this feature would solve?

if a package is already installed in "dependencies" then running bun i package --dev should put it in "devDependencies" and vice versa

### What is the feature you are proposing to solve the problem?

bun i package -P, --prod puts "package" in "dependencies". This is already established in pnpm

### What alternatives have you considered?

copying the package name and version in package.json

**Comment by Electroid** [comment] 2023-11-24 01:30
Duplicate of #4852

**Closed as not planned by Electroid** 2023-11-24 01:30 UTC
Labels: enhancement
