### ISSUE TITLE
"Illegal instruction" in Docker

### ISSUE THREAD

**Issue by khromov** [oven-sh/bun#1342] opened 2022-10-17 18:27 UTC
### Version

0.2.0

### Platform

Linux 92475282fbe3 5.15.68.1-microsoft-standard-WSL2 #1 SMP Mon Sep 19 19:14:52 UTC 2022 x86_64 Linux

### What steps will reproduce the bug?

Build a simple Dockerfile and run it:

```dockerfile
FROM jarredsumner/bun:0.2.0
CMD ["bun", "--version"]
```

```
docker build . -t bun --no-cache
docker run -it bun sh
/ # bun --version
Illegal instruction
```

### How often does it reproduce? Is there a required condition?

I'm pretty sure it's the same issue as https://github.com/oven-sh/bun/issues/733 where my CPU doesn't support AVX2, but that issue was marked as resolved and I can run Bun outside of Docker (but in WSL) on my machine without issues. So perhaps the Docker image is built with forced AVX2 support?

### What is the expected behavior?

It should work

### What do you see instead?

Illegal instruction

**Comment by eclairevoyant** [comment] 2023-09-10 16:18
see https://github.com/oven-sh/bun/issues/67#issuecomment-1205545144, use one of the baseline builds

also this is a duplicate

**Comment by Electroid** [comment] 2023-10-24 23:16
Duplicate of #67

**Closed as not planned by Electroid** 2023-10-24 23:16 UTC
Labels: bug
