### ISSUE TITLE
bun: symbol lookup error (undefined symbol: node_module_register)

### ISSUE THREAD

**Issue by sujjeee** [oven-sh/bun#8862] opened 2024-02-12 08:01 UTC
### What version of Bun is running?

1.0.26

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

``` javascript 
// Import pdfjs-dist library
import { getDocument } from "pdfjs-dist";

// Read the PDF file
const pdfFile = Bun.file("src/examples/pdfs/small.pdf");
const data = await pdfFile.arrayBuffer();

// Asynchronous function to extract text from the first page of the PDF
async function extractTextFromFirstPage(data) {
  // Load the PDF document
  const loadingTask = getDocument(data);
  const pdf = await loadingTask.promise;

  // Get the first page
  const page = await pdf.getPage(1);

  // Get the text content of the first page
  const content = await page.getTextContent();

  // Extract text from the text content
  let text = "";
  content.items.forEach((item) => {
    text += item.str + " ";
  });

  return text;
}

// Call the function and log the extracted text
extractTextFromFirstPage(data)
  .then((text) => {
    console.log("Text extracted from the first page of PDF:");
    console.log(text);
  })
  .catch((error) => {
    console.error("Error extracting text:", error);
  });
```

### What is the expected behavior?

Expected to extract text from the PDF and log it in the terminal.

### What do you see instead?

```bash
bun: symbol lookup error: /home/bun/app/node_modules/canvas/build/release/canvas.node: undefined symbol: node_module_register
```

### Additional information

It's working in Node.js

**Comment by huseeiin** [comment] 2024-02-12 12:18
duplicate of https://github.com/oven-sh/bun/issues/4290

**Closed as not planned** 2024-02-12 20:49 UTC
Labels: bug
