### ISSUE TITLE
--minify breaks source maps for Node

### ISSUE THREAD

**Issue by alxivnov** [oven-sh/bun#10048] opened 2024-04-07 19:32 UTC
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Linux 6.6.16-linuxkit aarch64 unknown

### What steps can reproduce the bug?

Bundle a file which calls a method with `console.trace()` from imported module with `bun build --sourcemap=inline --target=node --outfile ./bundle.mjs --minify ./index.js` and then run it with `node --enable-source-maps bundle.mjs`.
* index.js
```js
/**
 * Comment line 1
 * Comment line 2
 * Comment line 3
 */

const error = require('./error.js');

error.trace();
```
* error.js
```js
/**
 * Error generater
 */
module.exports = {
	/**
	 * Throws error
	 */
	error() {
		throw new Error();
	},
	/**
	 * Prints stack trace
	 */
	trace() {
		console.trace('trace');
	},
}
```

### What is the expected behavior?

Stack trace includes correct line number for `trace()` call: `at Object.trace (/usr/src/app/error.js:15:11)`.

### What do you see instead?

Stack trace includes incorrect line number for `trace()` call: `at <anonymous> (/usr/src/app/error.js:4:8)`.

### Additional information

Bundling works fine without `--minify`.

<img width="739" alt="Снимок экрана 2024-04-07 в 22 16 57" src="https://github.com/oven-sh/bun/assets/19705653/56ba4d71-bca8-40d8-b2e6-556e6bdf63b4">

**Comment by alxivnov** [comment] 2024-04-07 19:48
Bun doesn't support its own source maps.

<img width="795" alt="Снимок экрана 2024-04-07 в 22 47 24" src="https://github.com/oven-sh/bun/assets/19705653/5b481bb5-fb7c-446f-b2f4-3864b6b3d309">

**Comment by Electroid** [comment] 2024-04-08 16:37
Duplicate of #7427

**Closed as not planned by Electroid** 2024-04-08 16:37 UTC
Labels: bug
