### ISSUE TITLE
bun install: Unsupported dependency type `github` and `git`

### ISSUE THREAD

**Issue by malonehedges** [oven-sh/bun#244] opened 2022-07-06 06:36 UTC
I have a project with the following dependencies (url changed for privacy)
- `https://github.com/username/repo-name.git#branch-name`
- `git+https://github.com/ethereumjs/ethereumjs-abi.git`

Respectively, bun returns the following errors on `bun install`:
- `error: Unsupported dependency type github for "https://github.com/username/repo-name.git#branch-name"`
- `error: Unsupported dependency type git for "git+https://github.com/ethereumjs/ethereumjs-abi.git"`

**Comment by ndom91** [comment] 2022-07-06 12:23
Having this issue as well, doesn't seem to recognize the `git+https` prefix type.

**Comment by FinnRG** [comment] 2022-07-07 23:11
Duplicate of #82. Please close.

**Closed as completed** 2022-07-09 00:15 UTC
