### ISSUE TITLE
Bun crashes when running from terminal launched within VSCode that previously terminated.

### ISSUE THREAD

**Issue by naveedn** [oven-sh/bun#15468] opened 2024-11-28 05:25 UTC
### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on windows x86_64 [AutoCommand]

**panic**: attempt to use null value

- [`test_command.zig:601`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/cli/test_command.zig#L601>): `BunTest__shouldGenerateCodeCoverage`
- [`ZigSourceProvider.cpp:86`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/ZigSourceProvider.cpp#L86>): `Zig::SourceProvider::create`
- [`utility:762`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/include/utility#L762>): `std::exchange`
- [`ModuleLoader.cpp:883`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/ModuleLoader.cpp#L883>): `Bun::fetchESMSourceCodeAsync`
- [`ZigGlobalObject.cpp:4140`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/ZigGlobalObject.cpp#L4140>): `Zig::GlobalObject::moduleLoaderFetch`
- [`JSModuleLoader.cpp:277`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSModuleLoader.cpp#L277>): `JSC::JSModuleLoader::fetch`
- [`JSModuleLoader.cpp:486`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSModuleLoader.cpp#L486>): `JSC::moduleLoaderFetch`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stderr, dotenv, http\_server, jsc, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6006746561/">BUN-759</a></strong></sub>

**Comment by Jarred-Sumner** [comment] 2024-11-28 05:25
@naveedn this was fixed in Bun v1.1.37

@RiskyMH this is caused by the control flow profiler thing btw

**Closed as completed by Jarred-Sumner** 2024-11-28 05:25 UTC
Labels: crash, windows
