### ISSUE TITLE
setTimeout runs inconsistently

### ISSUE THREAD

**Issue by klirix** [oven-sh/bun#653] opened 2022-07-12 22:58 UTC
### Version

0.1.2

### Platform

Linux  5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```js
Bun.serve({
  fetch(this, request) {
    const time = Date.now();
    setTimeout(() => {
      Bun.write(Bun.stdout, `Resolved in ${Date.now() - time} \n`);
    }, 1000);
    return new Response("OK");
  },
  port: 3005,
});
```

### How often does it reproduce? Is there a required condition?

This example reproduces consistently

### What is the expected behavior?

```
Resolved in 1000 
Resolved in 1000 
Resolved in 1000 
Resolved in 1000 
Resolved in 1000 
```

### What do you see instead?

When requests are launched via scripts, or by hand in rapid succession
```
Resolved in 1001 
Resolved in 586 
Resolved in 66 
Resolved in 1000 
Resolved in 1001 
```

### Additional information

In a more complex cases I noticed that setTimeouts may resolve instantly or not resolve at all, instead of set period of ms. If I manage to reduce the repro to manageable format I will add it in a comment. From what I noticed the issue only appears when setTimeout is used with Bun server

**Comment by Jarred-Sumner** [comment] 2022-07-13 05:05
Duplicate of #490

**Closed as completed by Jarred-Sumner** 2022-07-13 05:05 UTC
Labels: bug, needs repro
