### ISSUE TITLE
Support for executing code provided right from a flag

### ISSUE THREAD

**Issue by fabiospampinato** [oven-sh/bun#2505] opened 2023-03-29 20:36 UTC
### What is the problem this feature would solve?

Node supports executing code like this:

```
node -e '1+2'
```

### What is the feature you are proposing to solve the problem?

Adding something like:

```
bun -e '1+2'
```

Though I see "e" is already used for something else. Maybe that should be freed first to better align with Node.

### What alternatives have you considered?

Executing a file.

**Comment by Electroid** [comment] 2023-10-26 00:06
Duplicate of #1932

**Closed as not planned by Electroid** 2023-10-26 00:06 UTC
Labels: enhancement
