### ISSUE TITLE
BVM

### ISSUE THREAD

**Issue by Areshkew** [oven-sh/bun#11251] opened 2024-05-22 04:05 UTC
### What is the problem this feature would solve?

Allow developers to install and switch between different versions of Bun easily. 

### What is the feature you are proposing to solve the problem?

The primary feature of this tool would be to allow developers to easily install, switch between, and manage multiple versions of Bun on a single system. Key functionalities would include:
- Users can install any version of Bun by specifying the version number.
- Users can quickly switch between installed Bun versions, ensuring the correct version is used for each project.
- Users can view all installed Bun versions and the currently active version.
- Users can remove unused or outdated Bun versions to free up system resources.
- Users can create aliases for frequently used versions for quicker switching.

**Comment by tomatau** [comment] 2024-05-22 13:35
I've been using [proto](https://github.com/moonrepo/proto) for this - which also manages other binaries

**Comment by Electroid** [comment] 2024-05-22 17:41
Duplicate of #3917

**Closed as not planned by Electroid** 2024-05-22 17:41 UTC
Labels: enhancement
