### ISSUE TITLE
Can't read from Bun file

### ISSUE THREAD

**Issue by AbomaPiet** [oven-sh/bun#6371] opened 2023-10-08 13:24 UTC
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What steps can reproduce the bug?

```
{
    "value": "test"
}
```
 ```
 let file = Bun.file("./file.json");
  console.log(await file.json());
```

bun process exits with exit code 1, no output is printed at all. Same code is ran by others and it works perfectly fine.

### What is the expected behavior?

It should print the contents of the json file.

### What do you see instead?

Nothing, no error message. 
![image](https://github.com/oven-sh/bun/assets/98128072/9088c0be-a2f7-468c-b450-e22a4df41fe6)

### Additional information

What does work and how i fixed it: 

import fs from 'fs';

console.log(fs.readFileSync('week2FILE1.json', 'utf-8'));

**Comment by Electroid** [comment] 2023-10-09 16:36
Duplicate of #5960

**Comment by Abhinavpatel00** [comment] 2023-10-12 15:47
can you please be more specific , because its working fine for me

![image](https://github.com/oven-sh/bun/assets/121427766/13d82233-334b-46d4-9ac2-947b0577f57d)

**Comment by Electroid** [comment] 2023-10-26 18:27
Duplicate of https://github.com/oven-sh/bun/issues/5960

**Closed as not planned by Electroid** 2023-10-26 18:27 UTC
Labels: bug, bun.js
