### ISSUE TITLE
 Segmentation fault at address 0x7FFF2A0856CC

### ISSUE THREAD

**Issue by thisVioletHydra** [oven-sh/bun#12032] opened 2024-06-21 11:51 UTC
### How can we reproduce the crash?

"I don't know how to reproduce the issue, the project is very large, and I suspect the problem might be with the `node-ssh` package."

### package.json
```json
 "engines": {
    "node": ">=20.0.0"
  },
  "os": [
    "darwin",
    "win32",
    "linux"
  ],
  "type": "module",
  "name": "motiv",
  "dependencies": {
    
    "@intlify/unplugin-vue-i18n": "^4.0.0",
    "@stylistic/eslint-plugin": "^2.1.0",
    "@stylistic/eslint-plugin-ts": "^2.1.0",
    "@typescript-eslint/eslint-plugin": "^7.12.0",
    "@vue/eslint-config-typescript": "^13.0.0",
    "archiver": "^7.0.1",
    "autoprefixer": "^10.4.19",
    "del-cli": "^5.1.0",
    "dotenv": "^16.4.5",
    "eslint": "^9.4.0",
    "imask": "^7.6.1",
    "node-html-parser": "^6.1.13",
    "node-ssh": "^13.2.0",
    "npm-run-all2": "^6.2.0",
    "postcss": "^8.4.38",
    "stylelint": "^16.6.1",
    "stylelint-config-html": "^1.1.0",
    "stylelint-config-recommended-vue": "^1.5.0",
    "stylelint-config-standard": "^36.0.0",
    "stylelint-order": "^6.0.4",
    "ts-node": "^10.9.2",
    "typescript": "^5.4.5",
    "unplugin-auto-import": "^0.17.6",
    "unplugin-fonts": "^1.1.1",
    "unplugin-svg-component": "^0.10.3",
    "unplugin-vue-components": "^0.27.0",
    "uuid": "^9.0.1",
    "vite": "^5.2.12",
    "vite-aliases": "^0.11.7",
    "vite-plugin-checker": "^0.6.4",
    "vite-plugin-chunk-split": "^0.5.0",
    "vite-plugin-dts": "^3.9.1",
    "vite-plugin-imp": "^2.4.0",
    "vite-plugin-inspect": "^0.8.4",
    "vite-plugin-mkcert": "^1.17.5",
    "vite-plugin-replace-json": "^1.0.1",
    "vite-svg-loader": "^5.1.0"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^2.20.0",
    
    "@types/archiver": "^6.0.2",
    "@types/eslint": "^8.56.10",
    "@types/node": "^20.14.2",
    "@types/requirejs": "^2.1.37",
    "@types/ssh2": "^1.15.0",
    "@types/uuid": "^9.0.8",
    "@typescript-eslint/parser": "^7.12.0",
    "chalk": "^5.3.0",
    "eslint-plugin-format": "^0.1.1",
    "eslint-plugin-perfectionist": "^2.10.0",
    "eslint-plugin-promise": "^6.2.0",
    "eslint-plugin-unicorn": "^53.0.0",
    "vue-eslint-parser": "^9.4.3"
  },

  ```

### Relevant log output

```shell
🤪 Done
============================================================
Bun v1.1.13 (bd6a6051) Windows x64
Args: "C:\Users\folder\AppData\Local\Microsoft\WinGet\Links\bunx.exe" "--bun" "vite" "build"
Features: jsc Bun.stdin(2) Bun.stdout bunfig dotenv spawn(2) transpiler_cache(19) tsconfig_paths(2) tsconfig(2)
Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws" "node:v8"
Elapsed: 4856ms | User: 1453ms | Sys: 156ms
RSS: 0.82GB | Peak: 0.84GB | Commit: 14.07GB | Faults: 218255

panic(main thread): Segmentation fault at address 0x7FFF2A0856CC
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.13/wB1bd6a605A6qggoH_CU\ntdll.dll43rUCU\ntdll.dllutqUCU\ntdll.dll63oUCa\KERNEL32.DLL26/FCa\ucrtbase.dllwt/GCa\ucrtbase.dllypgHsvlxFkj5Bik+hHA2+//B4srhhqB
```

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x7FFCE6EA0CB0

- *1 unknown/js code*
- ??? at `0x5177c` in ntdll.dll
- ??? at `0x514d7` in ntdll.dll
- ??? at `0x5117d` in ntdll.dll
- ??? at `0x17fab` in KERNEL32.DLL
- ??? at `0x1bed8` in ucrtbase.dll
- ??? at `0x1c099` in ucrtbase.dll
- [`Global.zig:123`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/Global.zig#L123>): `exitWide`
- [`Global.zig:106`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/Global.zig#L106>): `exit`
- [`bun_js.zig:343`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun_js.zig#L343>): `start`

**Comment by thisVioletHydra** [comment] 2024-06-21 11:53
> @thisVioletHydra, the latest version of Bun is v1.1.15, but this crash was reported on Bun v1.1.13.
> 
> Are you able to reproduce this crash on the latest version of Bun?
> 
> ```shell
> bun upgrade
> ```

```q
🤪 Done
============================================================
Bun v1.1.15 (b23ba1fe) Windows x64
Args: "C:\Users\rrybchin\AppData\Local\Microsoft\WinGet\Links\bunx.exe" "--bun" "vite" "build"
Features: jsc Bun.stdin(2) Bun.stdout bunfig dotenv spawn(2) transpiler_cache(20) tsconfig_paths(2) tsconfig(2)
Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws" "node:v8"
Elapsed: 4895ms | User: 1078ms | Sys: 156ms
RSS: 0.81GB | Peak: 0.83GB | Commit: 14.01GB | Faults: 214796

panic(main thread): Segmentation fault at address 0x7FFF21E456CC
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.15/wB1b23ba1fA6qggoH_CU\ntdll.dll43rUCU\ntdll.dllutqUCU\ntdll.dll63oUCa\KERNEL32.DLL26/FCa\ucrtbase.dllwt/GCa\ucrtbase.dllypgHsgr0Fki5Bi3skHA2+//B4srx8hB
 
 ```

**Comment by thisVioletHydra** [comment] 2024-06-24 10:19
```q
$ bunx --bun vite
❗process.env.OS Windows_NT
IDP_THEME_PATH __PATH__/blitz-idp-theme/blitz-config/assets/themes
13:18:33 [vite] [serve-> configResolved] 🪶Writing public to disk
error when starting dev server:
NotImplementedError: node:http2 createSecureServer is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/8823
    at new ::bunternal:: (internal:shared:19:14)
    at ::bunternal:: (internal:shared:2:35)
    at <anonymous> (node:http2:48:33)
    at processTicksAndRejections (:12:39)
============================================================
Bun v1.1.16 (bf7b327f) Windows x64
Args: "C:\www\motiv\node_modules\bun\bin\bun.exe" "--bun" "vite"
Features: jsc Bun.stdin(2) bunfig dotenv spawn(2) transpiler_cache(18) tsconfig_paths(2) tsconfig(2)
Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws" "node:v8" "node:http2"
Elapsed: 2500ms | User: 296ms | Sys: 140ms
RSS: 0.42GB | Peak: 0.42GB | Commit: 13.48GB | Faults: 110840

panic(main thread): Segmentation fault at address 0x7FFF2C6056CC
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.16/wa1bf7b327AqqggoH_CU\ntdll.dll43rUCU\ntdll.dllutqUCU\ntdll.dll63oUCa\KERNEL32.DLL26/FCa\ucrtbase.dllwt/GCa\ucrtbase.dllypgHss+2Fktf6ihrMA2+//B4srhssB
 ```

**Comment by thisVioletHydra** [comment] 2024-06-28 14:56
```q

D:\WWW\simple ❯ bun upgrade
Congrats! You're already on the latest version of Bun (which is v1.1.17)

error when starting dev server:
NotImplementedError: node:http2 createSecureServer is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/8823
    at new ::bunternal:: (internal:shared:19:14)
    at ::bunternal:: (internal:shared:2:35)
    at <anonymous> (node:http2:48:33)
    at processTicksAndRejections (:12:39)
    
```

**Comment by thisVioletHydra** [comment] 2024-07-04 09:19
# 1.1.18

```q
error when starting dev server:
NotImplementedError: node:http2 createSecureServer is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/8823
    at new ::bunternal:: (internal:shared:19:14)
    at ::bunternal:: (internal:shared:2:35)
    at <anonymous> (node:http2:48:33)
    at processTicksAndRejections (:12:39)
============================================================
Bun v1.1.18 (5a0b9352) Windows x64
Args: "C:\Users\rrybchin\AppData\Local\Microsoft\WinGet\Links\bunx.exe" "--bun" "vite"
Features: jsc Bun.stdin(2) bunfig dotenv spawn(2) tsconfig_paths(2) tsconfig(3)
Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws" "node:v8" "node:http2"
Elapsed: 2101ms | User: 46ms | Sys: 31ms
RSS: 0.41GB | Peak: 0.41GB | Commit: 13.48GB | Faults: 115038

panic(main thread): Segmentation fault at address 0x7FF8691656CC
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

**Comment by thisVioletHydra** [comment] 2024-07-15 12:37
# 1.1.20
```q
error when starting dev server:
NotImplementedError: node:http2 createSecureServer is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/8823
    at new ::bunternal:: (internal:shared:19:14)
    at ::bunternal:: (internal:shared:2:35)
    at <anonymous> (node:http2:48:33)
    at processTicksAndRejections (:12:39)
error: script "go" exited with code 1
```

**Comment by thisVioletHydra** [comment] 2024-08-08 08:51
# v1.1.21

```q
$ bunx --bun vite
failed to load config from C:\www\simple\vite.config.ts
error when starting dev server:
undefined
============================================================
Bun v1.1.21 (70ca2b76) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\rrybchin\.bun\bin\bunx.exe" "--bun" "vite"
Features: jsc Bun.stdin(2) bunfig dotenv spawn(2) transpiler_cache(16) tsconfig_paths(2) tsconfig(2)
Builtins: "bun:jsc" "bun:main" "node:assert" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws" "node:v8"
Elapsed: 1583ms | User: 31ms | Sys: 0ms
RSS: 0.33GB | Peak: 0.33GB | Commit: 4.73GB | Faults: 91929

panic(main thread): Segmentation fault at address 0x7FFA203E56CC
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

**Comment by Jarred-Sumner** [comment] 2024-08-08 20:06
@thisVioletHydra I suspect this is caused by using the `cpu-features` package. It will be fixed when we land V8 C++ API support.

@190n is actively working on it in #12821 

Please follow along in #4290

**Closed as not planned by Jarred-Sumner** 2024-08-08 20:06 UTC
Labels: crash, windows, runtime
