### ISSUE TITLE
Symbol Lookup Error: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by mrkking** [oven-sh/bun#8574] opened 2024-01-30 17:12 UTC
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Pop-OS - Linux 6.6.10-76060610-generic x86_64 x86_64

### What steps can reproduce the bug?

`bun create elysia new-app` OR `mkdir new-app && bun init` - I've tried both ways.
`bun add canvas`
create code:

```ts
// index.ts
import {createCanvas} from "canvas";
const canvas = createCanvas(200, 200);
console.log(canvas);
```

Run  `bun index.ts`

Output:
```
 symbol lookup error: /<path-to-project>/node_modules/canvas/build/Release/canvas.node: undefined symbol: node_module_register
```

this happens with other libraries too e.g. dockerode on the latest version of BunJS. Following the same steps with yarn or npm works perfectly fine. 

### What is the expected behavior?

for the canvas, it should create a canvas instance as seen in npm docs:
https://www.npmjs.com/package/canvas

and output should be: [Canvas 200x200]

### What do you see instead?

error:`/<path-to-project>/node_modules/canvas/build/Release/canvas.node: undefined symbol: node_module_register`

### Additional information
Not sure if this is the right area for this, let me know and i can take down and post elsewhere.

**Comment by Electroid** [comment] 2024-02-01 17:38
Duplicate of #5835

**Closed as not planned by Electroid** 2024-02-01 17:38 UTC
Labels: bug
