### ISSUE TITLE
bun crash report with chalk used in typescript, build cmd

### ISSUE THREAD

**Issue by sedlakr** [oven-sh/bun#15103] opened 2024-11-12 13:21 UTC
### How can we reproduce the crash?

- use pnpm
- 
"dependencies": {
    "chalk": "^5.3.0"
  },

index.ts
```
import chalk from "chalk";
export function main() {
	console.log(chalk.red('Hello, World!'));
}
```
bun build --entrypoints ./index.ts --outdir ./dist --target node

### Relevant log output

```shell
panic(thread 50748): Expected pretty file path to have only forward slashes, got 'C:\dev\repos\research\peonBun\node_modules\chalk\source\index.js'
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [BuildCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'D:\@touhouclouddb\node_modules\@touhouclouddb\utils\src\index.ts'

- [`fs.zig:1732`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/fs.zig#L1732>): `assertPrettyIsValid`
- [`bundle_v2.zig:9284`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L9284>): `postProcessJSChunk`
- [`bundle_v2.zig:8174`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L8174>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-qmdn5C/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: bunfig, define, dotenv, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by cirospaciari** [comment] 2024-11-12 23:32
Duplicated of https://github.com/oven-sh/bun/issues/14685

**Comment by nektro** [comment] 2024-11-13 01:40
duplicate of https://github.com/oven-sh/bun/issues/13897

**Closed as completed by nektro** 2024-11-13 01:40 UTC
Labels: crash, windows
