### ISSUE TITLE
`LoadLibrary failed` with malformed error message

### ISSUE THREAD

**Issue by void-soul** [oven-sh/bun#11394] opened 2024-05-27 11:09 UTC
### How can we reproduce the crash?

```
TypeError: LoadLibrary failed: ¨R`þ¥c^(DLL)
      at bindings (node_modules\bindings\bindings.js:112:48)
      at new Database (node_modules\better-sqlite3\lib\database.js:48:29)
      at index.ts:334:24

Bun v1.1.8 (Windows x64)
============================================================
Bun v1.1.8 (89d25807) Windows x64
Args: "C:\Users\Administrator\.bun\bin\bun.exe", ".\src\sql\test.ts"
Features: jsc transpiler_cache(2) tsconfig_paths(2) tsconfig(2)
Builtins: "bun:main" "node:assert" "node:buffer" "node:constants" "node:crypto" "node:fs" "node:net" "node:os" "node:path" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:cluster"
Elapsed: 298ms | User: 109ms | Sys: 78ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.18GB | Faults: 33940

panic(main thread): Segmentation fault at address 0x7FFFB6951620
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### JavaScript/TypeScript code that reproduces the crash?

```shell
import BetterSqlite3 from 'better-sqlite3';
const db = new BetterSqlite3('1.db');
```

### Relevant log output

```shell
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: ¨R`þ¥c^(DLL)
      at bindings (E:\pro\util-man\node_modules\bindings\bindings.js:112:48)
      at new Database (E:\pro\util-man\node_modules\better-sqlite3\lib\database.js:48:29)
      at E:\pro\util-man\src\sql\test.ts:2:12

Bun v1.1.8 (Windows x64)
============================================================
Bun v1.1.8 (89d25807) Windows x64
Args: "C:\Users\Administrator\.bun\bin\bun.exe", ".\src\sql\test.ts"
Features: jsc tsconfig_paths(2) tsconfig(2)
Builtins: "bun:main" "node:fs" "node:path" "node:string_decoder" "node:util" "node:util/types"
Elapsed: 143ms | User: 46ms | Sys: 15ms
RSS: 114.05MB | Peak: 114.05MB | Commit: 0.15GB | Faults: 28115

panic(main thread): Segmentation fault at address 0x7FFF9EE31620
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.8/wa189d2580AiggggG_CU\ntdll.dllqrvXCU\ntdll.dll26tXCU\ntdll.dll6otXCa\KERNEL32.DLL27xHCa\ucrtbase.dll47iICa\ucrtbase.dll+liIs7+pFkr4Boj6xGA2+//Bh+0zjhD
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](<https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FFFB6951620

- *1 unknown/js code*
- ??? at `0x5deb5` in ntdll.dll
- ??? at `0x5dbab` in ntdll.dll
- ??? at `0x5da8d` in ntdll.dll
- ??? at `0x1e3bb` in KERNEL32.DLL
- ??? at `0x205bc` in ucrtbase.dll
- ??? at `0x2045f` in ucrtbase.dll
- [`Global.zig:123`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/Global.zig#L123>): `exitWide`
- [`Global.zig:106`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/Global.zig#L106>): `exit`
- [`bun_js.zig:339`](<https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun_js.zig#L339>): `start`

**Comment by Electroid** [comment] 2024-05-27 16:26
This is a duplicate of #4290, but since the error message is malformed I'll keep this open because that is a separate issue that should be addressed.

**Comment by Jarred-Sumner** [comment] 2024-08-08 20:07
Duplicate of #4290

**Comment by Jarred-Sumner** [comment] 2024-08-08 20:07
The error message should no longer be malformed

Please leave a comment if it is still malformed

Otherwise, we're tracking this in #4290

**Closed as not planned by Jarred-Sumner** 2024-08-08 20:07 UTC
Labels: crash
