### ISSUE TITLE
bun: symbol lookup error: node_modules/robotjs/build/Release/robotjs.node: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by oldwizard1010** [oven-sh/bun#5747] opened 2023-09-19 15:05 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.16-2 x86_64 unknown

### What steps can reproduce the bug?

```
bun install robotjs
bun ./sine.js
```

sine.js:
```js
var robot = require("robotjs");

// Speed up the mouse.
robot.setMouseDelay(2);

var twoPI = Math.PI * 2.0;
var screenSize = robot.getScreenSize();
var height = (screenSize.height / 2) - 10;
var width = screenSize.width;

for (var x = 0; x < width; x++)
{
	y = height * Math.sin((twoPI * x) / width) + height;
	robot.moveMouse(x, y);
}

robot.moveMouseSmooth(100, 100);
```

### What is the expected behavior?

```
npm install robotjs
node ./sine.js
"Works fine"
```

### What do you see instead?

```
bun install robotjs
bun ./sine.js
bun: symbol lookup error: node_modules/robotjs/build/Release/robotjs.node: undefined symbol: node_module_register
```

**Comment by oldwizard1010** [comment] 2023-09-19 15:15
same on
1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

**Comment by jairodealmeida** [comment] 2023-09-26 13:45
Me too. 
 ~/.bun/bin/bun ./bin/www
/home/jdealmeida/.bun/bin/bun: symbol lookup error: /home/.../server/node_modules/bson-ext/build/Release/bson.node: undefined symbol: node_module_register

**Comment by obedm503** [comment] 2023-09-28 14:00
Possible duplicate #4290

**Comment by xhyrom** [comment] 2023-09-28 16:09
Duplicate of https://github.com/oven-sh/bun/issues/4290

**Comment by Jarred-Sumner** [comment] 2023-12-15 06:00
Duplicate of #4290 

GitHub will say "not planned", but it is planned - just a duplicate. Please track the status in #4290.

**Closed as not planned by Jarred-Sumner** 2023-12-15 06:00 UTC
Labels: bug, node.js
