### ISSUE TITLE
bun run dev crashing on rsbuild

### ISSUE THREAD

**Issue by anarchylimes** [oven-sh/bun#13598] opened 2024-08-29 03:58 UTC
### How can we reproduce the crash?

running `bun run dev` on a rsbuild project resulted in a crash. running on `"@rsbuild/core": "1.0.1-rc.0"` 

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on macos aarch64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- *4 unknown/js code*
- `vmEntryToJavaScript`
- `JSC::Interpreter::executeCall`
- `JSC::runJSMicrotask`
- `JSC::VM::drainMicrotasks`
- `Bun::jsFunctionDrainMicrotaskQueue`

**Comment by Jarred-Sumner** [comment] 2024-08-29 08:16
Duplicate of #11628

**Closed as not planned by Jarred-Sumner** 2024-08-29 08:16 UTC
Labels: node.js, crash, macOS, runtime
