### ISSUE TITLE
toMatchSnapshot() breaks when snapshot contains `\`

### ISSUE THREAD

**Issue by aykutkardas** [oven-sh/bun#4967] opened 2023-09-11 16:20 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm65 arm

### What steps can reproduce the bug?

1. Create a simple test contain "\" character.
```js
import { it, expect } from "bun:test";

it("Test", () => {
  expect(`{ "name": "test \\1" }`).toMatchSnapshot();
});

```

2. Generate snaphot
```sh
bun test --update-snapshot
```
```sh
bun test v1.0.0 (822a00c4)

index.test.ts:
✓ Test [0.82ms]

 1 pass
 0 fail
 snapshots: +1 added
 1 expect() calls
Ran 1 tests across 1 files. [17.00ms]
```

3. Run test
```
bun test
```
```sh
bun test v1.0.0 (822a00c4)

index.test.ts:
1 | import { it, expect } from "bun:test";
2 | 
3 | it("Test", () => {
4 |   expect(`{ "name": "test \\1" }`).toMatchSnapshot();
      ^
error: expect(received).toMatchSnapshot(expected)

Expected: "{ "name": "test " }"
Received: "{ "name": "test \1" }"

      at /home/aykutkardas/Developer/bun-snapshot-test/index.test.ts:4:2
✗ Test [0.64ms]

 0 pass
 1 fail
 snapshots: 1 failed
 1 expect() calls
Ran 1 tests across 1 files. [14.00ms]
```

---

### ScreenShot

![image](https://github.com/oven-sh/bun/assets/7966133/b48293b6-cc21-40ad-94cc-8ac7e6718fc2)

### What is the expected behavior?

I expect the test to run correctly. Right now this is failing the test without any changes with the snapshot it created.

### Additional information

My tests like this were working successfully in `jest` and `vitest`.

**Comment by Electroid** [comment] 2024-01-23 16:46
Duplicate of #5272

**Closed as not planned by Electroid** 2024-01-23 16:46 UTC
Labels: bug
