### ISSUE TITLE
1.0.8 won't start the app in docker container

### ISSUE THREAD

**Issue by MrEmanuel** [oven-sh/bun#6882] opened 2023-11-03 21:19 UTC
### What version of Bun is running?

1.0.8

### What platform is your computer?

Linux 6.4.16-linuxkit aarch64 unknown (the docker container where the app is running)

### What steps can reproduce the bug?

Build the app with docker compose using the latest bun image from hub.docker.com ( https://hub.docker.com/layers/oven/bun/latest/images/sha256-60c89603c59af0a742f297027129724203a5a6122380b243aa3e974da103700c?context=explore )

Here is my Dockerfile:

```
FROM oven/bun:latest

WORKDIR /usr/src/app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
COPY . .
EXPOSE 3000
ENTRYPOINT ["bun", "run", "index.ts"]
 ```
 
 Here is my docker-compose.yml 
 ```
 
services: 
  bot: 
    build: . 
    env_file: .env

```

The app works just fine on 1.0.6 so for now I'm pinning the version to that in my Dockerfile (`FROM oven/bun:1.0.6`)

### What is the expected behavior?

After running `docker compose up -d --build && docker compose logs -ft --tail 200 my-app` I expect to see printed messages that indicates that my application is running and listening for request. 

### What do you see instead?

I see the docker build process, then 
` ✔ Container my-app-1  Started                                                                                                                   0.0s`
`my-app-1 exited with code 139`

When I run `docker run --rm -it --entrypoint sh my-app` and `bun run index.ts` I get the following error message: `Segmentation fault`

### Additional information

I'm on a mac, if that matters. 
It runs fine on the local machine, without docker. I tried updating docker desktop, restarting it, and running `docker system prune -af` 
Nothing seems to work. It seems pretty likely that there's something wrong with the 1.0.8 version running in a docker container.

**Comment by adicco** [comment] 2023-11-04 06:23
Same behaviour observed while switching to the 1.0.8 image, no problem with 1.0.7

**Comment by Electroid** [comment] 2023-11-04 17:13
We're working on a fix for this. Duplicate of #6869

**Closed as not planned by Electroid** 2023-11-04 17:13 UTC
Labels: bug
