### ISSUE TITLE
Issue with building native dependencies when installing `canvas`

### ISSUE THREAD

**Issue by sonigeez** [oven-sh/bun#6179] opened 2023-09-29 17:21 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

1. Run `bun install canvas`
2. Observe that the installation completes without any errors
3. Attempt to use the canvas module in a Node.js script
4. Observe the failure due to missing native dependencies

### What is the expected behavior?

The necessary build step to compile the native addon modules should be executed during installation, and the canvas module should work as expected.

### What do you see instead?

The build step is not executed, leading to missing native dependencies and the canvas module not working as expected.

### Additional information

i.g bun probably ignoring `prebenchmark` script in `package.json` file

**Comment by Electroid** [comment] 2023-09-29 17:25
Duplicate of #4959 
Related to #5835

**Closed as completed by Electroid** 2023-09-29 17:25 UTC
Labels: bug

**Comment by Jarred-Sumner** [comment] 2023-12-12 07:33
Fixed by @dylan-conway and @paperdave in #7132

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.

In the meantime, you can run `bun upgrade --canary`
