### ISSUE TITLE
Bun crash in windows 10 while creating expo-stack app

### ISSUE THREAD

**Issue by kuldeep-kth** [oven-sh/bun#15239] opened 2024-11-19 06:49 UTC
### How can we reproduce the crash?

just run `bun create expo-stack example` 

### Relevant log output

```shell
_
   ___  _ __  ___   __ _ | |_  ___
  / __|| '__|/ _ \ / _` || __|/ _ \
 | (__ | |  |  __/| (_| || |_|  __/
  \___||_|   \___| \__,_| \__|\___|
   ___ __  __ _ __    ___
  / _ \\ \/ /| '_ \  / _ \
 |  __/ >  < | |_) || (_) |
  \___|/_/\_\| .__/  \___/
       _     |_|        _
  ___ | |_  __ _   ___ | | __
 / __|| __|/ _` | / __|| |/ /
 \__ \| |_| (_| || (__ |   <
 |___/ \__|\__,_| \___||_|\_\

┌  Let's get started!
│
◇  Would you like to use a saved configuration?
│  No
│
◇  Would you like to use TypeScript with this project?
│  Yes
│ood call, now using TypeScript! 🚀
◇
We've detected bun v1.1.34 as your preferred package manager.
Would you like to continue using it?
│  No
│
◇  Gotcha! Which package manager would you like to use?
│  pnpm
│
◇  What would you like to use for Navigation?
│  Expo Router
│
◇  What type of navigation would you like to use?
│  Stack
│
◇  What would you like to use for styling?
│  NativeWind
You'll be styling with ease using Nativewind!
============================================================
Bun v1.1.34 (5e5e7c60) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "bun" "C:\Users\KRISCE~1\AppData\Local\Temp\bunx-1033068897-create-expo-stack@latest\node_modules\create-expo-stack\bin\create-expo-stack.js" "influencer"
Features: Bun.stdin(2) Bun.stdout jsc transpiler_cache(134) tsconfig(7)
Builtins: "bun:main" "node:assert" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:https" "node:module" "node:os" "node:path" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node-fetch" "node:http2"
Elapsed: 27894ms | User: 1546ms | Sys: 312ms
RSS: 0.23GB | Peak: 0.24GB | Commit: 0.26GB | Faults: 64661

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.34/wa15e5e7c6AsggkggD___8o00jC__s3tnkC___A2AK
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *3 unknown/js code*
- [`LLIntSlowPaths.cpp:946`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L946>): `llint_slow_path_get_by_id`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, fetch, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5616831444/">BUN-2B1</a></strong></sub>

**Comment by nektro** [comment] 2024-11-19 22:50
duplicate of https://github.com/oven-sh/bun/issues/10844

**Closed as completed by nektro** 2024-11-19 22:50 UTC
Labels: crash, windows, runtime

**Comment by Jarred-Sumner** [comment] 2024-11-25 22:32
Fixed in https://github.com/oven-sh/bun/pull/15357
