### ISSUE TITLE
musl build

### ISSUE THREAD

**Issue by hicaru** [oven-sh/bun#9514] opened 2024-03-19 14:48 UTC
### What version of Bun is running?

latest

### What platform is your computer?

Linux 6.6.22_1 x86_64 musl

### What steps can reproduce the bug?

run from website `curl -fsSL https://bun.sh/install | bash` but it downloading binary fro `glibc` but it should be for musl. when try launch it, it returns the error:
```bash
bun -v
exec: Failed to execute process '/home/user/.bun/bin/bun': The file exists and is executable. Check the interpreter or linker?
```

**Comment by Electroid** [comment] 2024-03-19 15:50
Duplicate of #918

**Closed as not planned by Electroid** 2024-03-19 15:50 UTC
Labels: bug
