### ISSUE TITLE
Bun doesn't reload .env file values

### ISSUE THREAD

**Issue by wyrd-code** [oven-sh/bun#8969] opened 2024-02-17 22:10 UTC
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 5.15.0-92-generic x86_64 x86_64

### What steps can reproduce the bug?

When running `bun run --watch server/server.ts` with a new value placed in the `.env` like 
```
SOME_VALUE=a
```

It will read the value and expose it correctly. But if I change the value to `b`, stop and restart the server, it will still hold value `a`. 

I noticed also that placing `bun run --watch server/server.ts` in a package.json `dev` script for example  and calling `bun run  dev` will also cache the value, but not the same one as the direct call. Ie, if I set `SOME_VALUE=c` and run the script, it will also be cached, and will return `c` even if direct call still displays `b` for example and the env file is updated to `d`.

This seems trivial to test so I'm not making a reproduction just for this, but lmk if I should.

### What is the expected behavior?

Bun will read the env file every time `bun run` is called. 

### What do you see instead?

Bun doesn't read the new env file values, but returns cached ones.

### Additional information

Note that I'm using workspaces and the package.json, .env and script call are all in the  workspace folder, even though I doubt that should be affecting things.

**Comment by Electroid** [comment] 2024-02-18 17:14
Duplicate of #2521

**Closed as not planned by Electroid** 2024-02-18 17:14 UTC
Labels: bug

**Comment by wyrd-code** [comment] 2024-02-18 19:34
@Electroid fyi this is not exactly an identical issue. I don't need --watch to hot reload .env, I need it to read the value from the file when stopped/started, instead of a (somehow) cached value.

After the process is stopped (ctrl+c) and started again, it doesn't pick up on actual .env file contents.
