### ISSUE TITLE
Crash on bun install

### ISSUE THREAD

**Issue by name-is-hai** [oven-sh/bun#10677] opened 2024-04-30 02:28 UTC
### How can we reproduce the crash?

![Screenshot 2024-04-30 092815](https://github.com/oven-sh/bun/assets/90458368/f91774c7-b90d-4b61-9c9f-9e86d5f74d48)

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:4872`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L4872): `processDependencyListItem`
- [`logger.zig:850`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/logger.zig#L850): `allocPrint`
- [`install.zig:5652`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L5652): `runTasks`
- [`install.zig:1145`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L1145): `name`
- [`event_loop.zig:2027`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.js/event_loop.zig#L2027): `tick`
- [`install.zig:10795`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L10795): `installWithManager`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1304`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1304): `which`
- [`cli.zig:56`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L56): `start`
- [`main.zig:52`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/main.zig#L52): `main`

**Comment by MettlestateDeveloper** [comment] 2024-05-03 13:56
Deleting lock file fixes it, couldn't reproduce after that

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:42
Duplicate of https://github.com/oven-sh/bun/issues/10565

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:42
To track this issue, please follow along in Duplicate of https://github.com/oven-sh/bun/issues/10565

**Closed as not planned by Jarred-Sumner** 2024-06-04 22:42 UTC
Labels: bug, crash
