### ISSUE TITLE
For await console loop causes core dump (FilePoll.register failed: 1) on systemd service

### ISSUE THREAD

**Issue by raikasdev** [oven-sh/bun#9157] opened 2024-02-29 01:43 UTC
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Linux 5.15.0-1052-oracle x86_64 x86_64

### What steps can reproduce the bug?

1. Write to "index.ts":
```ts
for await (const line of console) {
  console.log(line);
}
```
3. Create a systemd service [like this](https://bun.sh/guides/ecosystem/systemd)
4. Start the service and then check it's status and journalctl

### What is the expected behavior?

In a stdin'less environment some error but not a core dump.

### What do you see instead?

Feb 29 00:49:47 bun-coredump-test bun[22436]: Panic: FilePoll.register failed: 1
Feb 29 00:49:47 bun-coredump-test bun[22436]: bun has crashed :'(
Feb 29 00:49:47 bun-coredump-test bun[22436]: ----- bun meta -----
Feb 29 00:49:47 bun-coredump-test bun[22436]: Bun v1.0.29 (a146856d) Linux x64 #58-Ubuntu SMP Tue Feb 13 19:43:43 UTC 2024
Feb 29 00:49:47 bun-coredump-test bun[22436]: RunCommand: dotenv
Feb 29 00:49:47 bun-coredump-test bun[22436]: Elapsed: 90ms | User: 120ms | Sys: 46ms
Feb 29 00:49:47 bun-coredump-test bun[22436]: RSS: 43.01MB | Peak: 55.02MB | Commit: 43.01MB | Faults: 0
Feb 29 00:49:47 bun-coredump-test bun[22436]: ----- bun meta -----
Feb 29 00:49:47 bun-coredump-test bun[22436]: 0   0x555adafdf37b
Feb 29 00:49:47 bun-coredump-test bun[22436]: 1   ???
Feb 29 00:49:47 bun-coredump-test bun[22436]: 2   ???
Feb 29 00:49:47 bun-coredump-test bun[22436]: 3   ???
Feb 29 00:49:47 bun-coredump-test bun[22436]: 4   ???
Feb 29 00:49:47 bun-coredump-test bun[22436]: 5   ???
Feb 29 00:49:47 bun-coredump-test bun[22436]: Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
Feb 29 00:49:47 bun-coredump-test bun[22436]: thread 22436 panic: FilePoll.register failed: 1
Feb 29 00:49:47 bun-coredump-test bun[22436]: Unwind information for `:0x555ad9baacda` was not available, trace may be incomplete
Feb 29 00:49:47 bun-coredump-test systemd[1]: bun-coredump-test.service: Main process exited, code=dumped, status=6/ABRT
Feb 29 00:49:47 bun-coredump-test systemd[1]: bun-coredump-test.service: Failed with result 'core-dump'.

### Additional information

Might not be just systemd and all environments without a stdin, like child processes :shrug:

**Comment by Electroid** [comment] 2024-02-29 02:01
Duplicate of #8738

**Closed as not planned by Electroid** 2024-02-29 02:01 UTC
Labels: bug

**Comment by raikasdev** [comment] 2024-02-29 02:19
> Duplicate of #8738

@Electroid That seems to be something related to drizzle. #8738 has RunCommand: transpiler_cache, while this has RunCommand: dotenv, so this might be a separate issue regarding FilePoll.
