### ISSUE TITLE
function createBrotliDecompress is present when Brotli isn't supported

### ISSUE THREAD

**Issue by Polygons1** [oven-sh/bun#9493] opened 2024-03-18 16:03 UTC
### What version of Bun is running?

1.0.33+9e91e137f

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

```util.isFunction(zlib.createBrotliDecompress)```

### What is the expected behavior?

to be false

### What do you see instead?

the function returns true

### Additional information

this brakes axios

**Comment by Electroid** [comment] 2024-03-19 16:10
We generally stub out APIs we have not yet implemented so there are better error messages instead of "undefined is not a function". Unfortunately, it doesn't handle every case; we need to support Brotli.

**Comment by Electroid** [comment] 2024-03-19 16:10
Duplicate of https://github.com/oven-sh/bun/issues/267

**Closed as not planned by Electroid** 2024-03-19 16:10 UTC
Labels: bug, node.js
