### ISSUE TITLE
Bun `index out of bounds` error when used with aws cdk

### ISSUE THREAD

**Issue by NimmLor** [oven-sh/bun#11006] opened 2024-05-11 12:30 UTC
### How can we reproduce the crash?

Bun v1.1.8 on Windows using Powershell.

1. Setup a simple cdk project

2. Run `bunx cdk synth ./bin/infrastructure.ts`
Note: adding the `--bun` flag adds a CDK warning that CDK is not tested with the given node version (defaults to the latest even though its not installed)

### JavaScript/TypeScript code that reproduces the crash?

```ts
import { App, CfnOutput, Stack, type StackProps } from 'aws-cdk-lib'
import type { Construct } from 'constructs'

class SampleStack extends Stack {
  public constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    new CfnOutput(this, 'Hello', {
      value: 'world',
    })
  }
}

const app = new App()
new SampleStack(app, 'InfrastructureStack', {})
```

### Relevant log output

```shell
bunx cdk synth .\bin\infrastructure.ts      
============================================================
Bun v1.1.8 (89d25807) Windows x64
Args: "bun", "bin/infrastructure.ts"
Features: jsc transpiler_cache(4) tsconfig(5) 
Builtins: "bun:main" "node:buffer" "node:constants" "node:crypto" "node:fs" "node:path" "node:stream" "node:string_decoder" "node:util" "node:util/types" 
Elapsed: 972ms | User: 218ms | Sys: 31ms
RSS: 1.01GB | Peak: 1.01GB | Commit: 1.45GB | Faults: 249498

panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on windows x86_64 [AutoCommand]

**panic**: index out of bounds

- [`Allocator.zig:228`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/mem/Allocator.zig#L228): `allocBytesWithAlignment`
- [`js_ast.zig:68`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_ast.zig#L68): `append`
- [`js_ast.zig:3385`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_ast.zig#L3385): `joinWithComma`
- [`js_parser.zig:1754`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_parser.zig#L1754): `simpifyUnusedExpr`
- [`js_parser.zig:1755`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_parser.zig#L1755): `simpifyUnusedExpr`
- [`js_parser.zig:1755`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_parser.zig#L1755): `simpifyUnusedExpr`
- [`js_parser.zig:1755`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_parser.zig#L1755): `simpifyUnusedExpr`
- [`js_parser.zig:1755`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_parser.zig#L1755): `simpifyUnusedExpr`
- [`js_parser.zig:1755`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_parser.zig#L1755): `simpifyUnusedExpr`
- [`js_parser.zig:1755`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/js_parser.zig#L1755): `simpifyUnusedExpr`

**Comment by Jarred-Sumner** [comment] 2024-05-12 07:36
Duplicate of #5398

**Comment by Jarred-Sumner** [comment] 2024-05-16 10:32
Closing as duplicate of #5398. Please follow along there. We will fix it.

**Closed as not planned by Jarred-Sumner** 2024-05-16 10:32 UTC
Labels: bug, crash
