### ISSUE TITLE
Another instant segfault when performing Bun.build() on a codebase with plugins.

### ISSUE THREAD

**Issue by l1mey112** [oven-sh/bun#14106] opened 2024-09-23 06:07 UTC
### How can we reproduce the crash?

Clone the repository [randomx.js](https://github.com/l1mey112/randomx.js) at commit hash `b76bb84`. Then perform a simple bun build pointing at the library root, after running `make`.

```ts
await Bun.build({
	entrypoints: ['src/index.ts'],
	outdir: 'dist',
	plugins: [binayloader],
})
```

Keep in mind, `make` is needed to create the WASM files. You will need a simple clang installation, with the WABT and Binaryen toolchains installed.

This is similar to #14037 , but now using a plugin to create a module using `contents` instead of `exports` as that causes the build to just output nothing. The plugin below is being exported to then be called in `scripts/build.ts`

```ts
#!/usr/bin/env bun

import { plugin, type BunPlugin } from "bun"

export const binayloader: BunPlugin = {
	name: "binaryloader",
	async setup(build) {
		// create a toBinary module, one per build
		build.onLoad({ filter: /^__toBinary$/ }, async (args) => {
			return {
				contents: `export default /* @__PURE__ */ (() => {
					var table = new Uint8Array(128);
					for (var i = 0; i < 64; i++) table[i < 26 ? i + 65 : i < 52 ? i + 71 : i < 62 ? i - 4 : i * 4 - 205] = i;
					return (base64) => {
						var n = base64.length, bytes = new Uint8Array((n - (base64[n - 1] == "=") - (base64[n - 2] == "=")) * 3 / 4 | 0);
						for (var i2 = 0, j = 0; i2 < n; ) {
							var c0 = table[base64.charCodeAt(i2++)], c1 = table[base64.charCodeAt(i2++)];
							var c2 = table[base64.charCodeAt(i2++)], c3 = table[base64.charCodeAt(i2++)];
							bytes[j++] = c0 << 2 | c1 >> 4;
							bytes[j++] = c1 << 4 | c2 >> 2;
							bytes[j++] = c2 << 6 | c3;
						}
						return bytes;
					};
				})();`,
			}
		})

		build.onLoad({ filter: /\.(wasm)$/ }, async (args) => {
			const buffer = await Bun.file(args.path).arrayBuffer()

			/* return {
				exports: { default: new Uint8Array(buffer) },
				loader: "object",
			} */
			return {
				contents: `import __toBinary from "__toBinary";
					export default __toBinary("${Buffer.from(buffer).toString('base64')}");`,
			}
		})
	},
}

await plugin(binayloader)
```

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000004

- [`bundle_v2.zig:9588`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bundler/bundle_v2.zig#L9588>): `src.bundler.bundle_v2.LinkerContext.generateChunksInParallel`
- [`bundle_v2.zig:1712`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bundler/bundle_v2.zig#L1712>): `Thread.PosixThreadImpl.spawn__anon_171286.Instance.entryFn`

Features: jsc, bunfig, tsconfig

**Comment by Jarred-Sumner** [comment] 2024-09-23 11:26
This is a duplicate of https://github.com/oven-sh/bun/issues/14106, let's track it there.

**Closed as not planned by Jarred-Sumner** 2024-09-23 11:26 UTC
Labels: crash, linux
