### ISSUE TITLE
GPU.js break down in bun

### ISSUE THREAD

**Issue by PrinOrange** [oven-sh/bun#11371] opened 2024-05-26 12:45 UTC
### How can we reproduce the crash?

[GPU.js is a JavaScript Acceleration library for GPU](https://github.com/gpujs/gpu.js) (General purpose computing on GPUs) in JavaScript for Web and Node. 

First, init a bun project, and install the gpu.js
```bash
bun install gpu.js
```

And paste such code for gpu.js usage example
```typescript
import { GPU } from "gpu.js";

// Create a GPU instance
const gpu = new GPU();

// Create a kernel function to check if a number is divisible by another number
const isDivisibleKernel = gpu
  .createKernel(function (num: number) {
    const i = this.thread.x + 2;
    if (num % i === 0) {
      return 1;
    }
    return 0;
  })
  .setOutput([1024]); // Set output size to 1024

function isPrime(num: number): boolean {
  if (num <= 1) {
    return false;
  }
  if (num <= 3) {
    return true;
  }
  if (num % 2 === 0 || num % 3 === 0) {
    return false;
  }

  const limit = Math.floor(Math.sqrt(num));

  // GPU computation
  const results = isDivisibleKernel(num) as number[];

  // Check results
  for (let i = 0; i < limit - 1; i++) {
    if (results[i] === 1) {
      return false;
    }
  }
  return true;
}

// Test
const number = 104729; // This is a large prime number
console.log(`Is the number ${number} a prime? ${isPrime(number)}`);
```

And it outputs the `segment fault`.

### JavaScript/TypeScript code that reproduces the crash?

```shell
import { GPU } from "gpu.js";

// Create a GPU instance
const gpu = new GPU();

// Create a kernel function to check if a number is divisible by another number
const isDivisibleKernel = gpu
  .createKernel(function (num: number) {
    const i = this.thread.x + 2;
    if (num % i === 0) {
      return 1;
    }
    return 0;
  })
  .setOutput([1024]); // Set output size to 1024

function isPrime(num: number): boolean {
  if (num <= 1) {
    return false;
  }
  if (num <= 3) {
    return true;
  }
  if (num % 2 === 0 || num % 3 === 0) {
    return false;
  }

  const limit = Math.floor(Math.sqrt(num));

  // GPU computation
  const results = isDivisibleKernel(num) as number[];

  // Check results
  for (let i = 0; i < limit - 1; i++) {
    if (results[i] === 1) {
      return false;
    }
  }
  return true;
}

// Test
const number = 104729; // This is a large prime number
console.log(`Is the number ${number} a prime? ${isPrime(number)}`);
```

### Relevant log output

```shell
PS E:\frontend-projects\gpu-js> bun index.ts
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: ¨R`þ¥c^(DLL)
      at bindings (E:\frontend-projects\gpu-js\node_modules\bindings\bindings.js:112:48)
      at E:\frontend-projects\gpu-js\node_modules\gl\src\javascript\native-gl.js:1:7
      at E:\frontend-projects\gpu-js\node_modules\gl\src\javascript\webgl-rendering-context.js:4:42
      at E:\frontend-projects\gpu-js\node_modules\gl\src\javascript\node-index.js:3:32
      at E:\frontend-projects\gpu-js\node_modules\gl\index.js:4:10
      at E:\frontend-projects\gpu-js\node_modules\gpu.js\src\backend\headless-gl\kernel.js:1:7     
      at E:\frontend-projects\gpu-js\node_modules\gpu.js\src\gpu.js:5:9
      at E:\frontend-projects\gpu-js\node_modules\gpu.js\src\index.js:1:9

Bun v1.1.10 (Windows x64)
============================================================
Bun v1.1.10 (5102a944) Windows x64
Args: "C:\Users\PrinOrange\AppData\Roaming\npm\node_modules\bun\bin\bun.exe" "index.ts"
Features: jsc transpiler_cache(2) tsconfig(2) 
Builtins: "bun:main" "node:fs" "node:path" "node:string_decoder" "node:util/types"     
Elapsed: 286ms | User: 46ms | Sys: 46ms
RSS: 122.77MB | Peak: 124.03MB | Commit: 0.14GB | Faults: 30741

panic(main thread): Segmentation fault at address 0x7FFB059A193D
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FFB059A193D

- *1 unknown/js code*
- ??? at `0x5deb5` in ntdll.dll
- ??? at `0x5dbab` in ntdll.dll
- ??? at `0x5da8d` in ntdll.dll
- ??? at `0x1e3bb` in KERNEL32.DLL
- ??? at `0x205bc` in ucrtbase.dll
- ??? at `0x2045f` in ucrtbase.dll
- [`Global.zig:123`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/Global.zig#L123>): `exitWide`
- [`Global.zig:106`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/Global.zig#L106>): `exit`
- [`javascript.zig:1040`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/javascript.zig#L1040>): `eventLoop`

**Comment by Electroid** [comment] 2024-05-27 16:33
Duplicate of #11394

**Closed as not planned by Electroid** 2024-05-27 16:33 UTC
Labels: crash
