### ISSUE TITLE
Add <Request>.ip field to easily access the client's ip in Bun.serve

### ISSUE THREAD

**Issue by ibnz36** [oven-sh/bun#6049] opened 2023-09-25 18:24 UTC
### What is the problem this feature would solve?

This would make it easier to get the IP of any incoming request, which is specially useful for authentification, rate limiting or banning.

### What is the feature you are proposing to solve the problem?

Simply add a public field to the `Request` interface named `ip` that has the IP of the client.

**Comment by Electroid** [comment] 2023-09-25 23:10
Duplicate of #4640

**Closed as completed by Electroid** 2023-09-25 23:10 UTC
Labels: enhancement
