### ISSUE TITLE
Crash when Reading a File in linux/amd64 Docker Image

### ISSUE THREAD

**Issue by p0fi** [oven-sh/bun#7462] opened 2023-12-04 23:15 UTC
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Official bun Docker image on macOS Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

Im trying to run a Bun script inside a Docker container build for the `linux/amd64` platform on macOS. The script instantly crashes when trying to read a file. 

The docker container is build with this command:
```zsh
docker buildx build --platform=linux/amd64 -t test .
```

Just a single line in a script crashes the script.

```js
await Bun.file('file.json').json()
console.log('read the file!')
```

### What is the expected behavior?

Expecting to see the log output and then the container exiting.

### What do you see instead?

Nothing, instant crash.

### Additional information

The script works fine if I build the image for macOS via 
```zsh
docker build -t test .
```

The docker image needs to run on a amd64 arch in the cloud but it always crashes.

**Comment by Electroid** [comment] 2023-12-04 23:21
Duplicate of #5960

**Comment by Electroid** [comment] 2023-12-04 23:21
We will fix this, thanks for reporting!

**Comment by p0fi** [comment] 2023-12-04 23:27
Maybe worth closing it as a duplicate too and not as completed :) 
![CleanShot 2023-12-05 at 00 26 47@2x](https://github.com/oven-sh/bun/assets/6141293/8335ea76-6871-4441-ab83-c0ff86d98de3)

**Closed as not planned** 2023-12-04 23:29 UTC
Labels: bug
