### ISSUE TITLE
Converting a string to a pointer and back again to a string (for ffi) mangles the string

### ISSUE THREAD

**Issue by SorenHolstHansen** [oven-sh/bun#10085] opened 2024-04-08 20:27 UTC
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

I am trying to interface with rust, however I found that when I send a long string to rust with a pointer it often gets mangled. I can reproduce it even without sending to rust by just transforming the string to a pointer and back again to a string. The following example prints the weird stuff at the end (The string is just arbitrary)

```ts
const q = 'Hello there how are you doing fsdh flisdh fisdhf isdf isdugf lisadg fiug<sdfi gzlsidfg ilsd<gf li<sdugf lisfg i<sugf li<dsgf li<sgfl i<gsfli g<slifug li<fg li<agf li<zgfli d<ilfg li<dgf lizgf kjzgf kizgxfl ';
console.log(new CString(ptr(Buffer.from(q, 'utf8'))).toString());
// => "Hello there how are you doing fsdh flisdh fisdhf isdf isdugf lisadg fiug<sdfi gzlsidfg ilsd<gf li<sdugf lisfg i<sugf li<dsgf li<sgfl i<gsfli g<slifug li<fg li<agf li<zgfli d<ilfg li<dgf lizgf kjzgf kizgxfl ) {\n      return t�\u0002tn�\u0004"
```

### What is the expected behavior?

Well, I would expect it to just return back the original string. I might of course be doing something wrong here, but this anyways does not feel like the intended behavior

### What do you see instead?

Stuff will be injected at the end of the strings, like above " ) {\n      return t�\u0002tn�\u0004" was injected, and I have even found for some small strings where it would be suffixed with a "@" or "0" or similar

### Additional information

I could fix the above by choosing "ascii" as the encoding, but that did not fix the error on the rust side. The first part of the rust side looks something like this
```rust
#[no_mangle]
pub extern "C" fn my_function(
    q: *const c_char,
) {
    let q = unsafe { CStr::from_ptr(query) };
    println!("{:#?}", q);
}
```

**Comment by SorenHolstHansen** [comment] 2024-04-08 20:34
Some more info: Doing the above example with the string `"Hello there how are you doing fsdh flisdh fisdhf isdf isdugf lisadg fiug<sdfi gzlsidfg ilsd<gf li<sdugf lisfg i<sugf li<dsgf li<sgfl i<gsfli g<slifug li<fg li<agf li<zgfli d<ilfg li<dgf lizgf "` works fine, but adding a `"k"` at the end of the string suddenly appends the following text `"get done() {\n      return t�\u0002tD�\u0005"`

**Comment by dylan-conway** [comment] 2024-04-08 20:36
Does `CStr` assert or add a null byte to the end of the input? What happens if you end the string with `\0`?

**Comment by SorenHolstHansen** [comment] 2024-04-08 20:38
Uh! yeah that fixes the problem

**Comment by dylan-conway** [comment] 2024-04-08 21:00
This is a difference in string representation between languages. Strings in c expect null byte termination, while strings in js don't. I don't know rust very well, but if `CStr` has a way to create from pointer and length you could pass the length as another argument with the pointer. If not, in the constructor for `CString` you can append a null byte before passing the pointer to rust.

Closing because it is working as intended

**Closed as completed by dylan-conway** 2024-04-08 21:00 UTC
Labels: bug, bun:ffi
