### ISSUE TITLE
panic(main thread): Segmentation fault at address 0x0

### ISSUE THREAD

**Issue by ImBIOS** [oven-sh/bun#14405] opened 2024-10-08 09:59 UTC
### How can we reproduce the crash?

I'm running a ai.google.dev gemini code inside a docker container (containerized app), and this happen while I'm doing some "smoke" test before I deploy this container to the "BIG MUSCLE" cloud. I don't the ai gen code is the cause because in this particular script I'm running I have this setup and several custom utils, I'm trying to gather some data for my research:

```

  System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.85 GB / 15.41 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.proto/shims/node
    Yarn: 3.4.1 - ~/.proto/shims/yarn
    npm: 10.8.1 - ~/.proto/shims/npm
    bun: 1.1.29 - ~/.bun/bin/bun
    Watchman: 2024.10.07.00 - /home/linuxbrew/.linuxbrew/bin/watchman
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
    Go: 1.23.1 - /home/imbios/.proto/shims/go
    Java: 11.0.24 - /home/imbios/.cache/coursier/arc/https/github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.24%252B8/OpenJDK11U-jdk_x64_linux_hotspot_11.0.24_8.tar.gz/jdk-11.0.24+8/bin/javac
    Perl: 5.38.2 - /usr/bin/perl
    Python3: 3.12.7 - /home/linuxbrew/.linuxbrew/bin/python3
    Rust: 1.80.0 - /home/imbios/.cargo/bin/rustc
  Browsers:
    Chrome: 129.0.6668.89
  npmPackages:
    @catdevnull/twitter-scraper: ^0.14.5 => 0.14.5 
    @commander-js/extra-typings: ^12.1.0 => 12.1.0 
    @google/generative-ai: ^0.21.0 => 0.21.0 
    @logtail/pino: ^0.5.0 => 0.5.0 
    @t3-oss/env-nextjs: ^0.11.1 => 0.11.1 
    @types/bun: ^1.1.10 => 1.1.10 
    @types/k6: ^0.54.1 => 0.54.1 
    @types/node: ^22.7.4 => 22.7.4 
    @types/user-agents: ^1.0.4 => 1.0.4 
    bun-bagel: ^1.1.0 => 1.1.0 
    canvas: ^3.0.0-rc2 => 3.0.0-rc2 
    crawlee: ^3.11.5 => 3.11.5 
    csv-string: ^4.1.1 => 4.1.1 
    dotenv-checker: ^1.1.7 => 1.1.7 
    escape-string-regexp: ^5.0.0 => 5.0.0 
    p-debounce: ^4.0.0 => 4.0.0 
    pino: ^9.4.0 => 9.4.0 
    pino-pretty: ^11.2.2 => 11.2.2 
    puppeteer: * => 23.5.0 
    puppeteer-cluster: ^0.24.0 => 0.24.0 
    puppeteer-extra: ^3.3.6 => 3.3.6 
    puppeteer-extra-plugin-stealth: ^2.11.2 => 2.11.2 
    puppeteer-screen-recorder: 3.0.5 => 3.0.5 
    sharp: ^0.33.5 => 0.33.5 
    typescript: ^5.6.2 => 5.6.2 
    user-agents: latest => 1.1.325 
    zod: ^3.23.8 => 3.23.8 


```

It can only reproduced once after I tried several times.

Might Related:
- https://github.com/oven-sh/bun/issues/14402
- https://github.com/oven-sh/bun/issues/14239

### Relevant log output

```
============================================================
Bun v1.1.29 (6d43b366) Linux x64
Linux Kernel v6.8.0 | glibc v2.39
CPU: sse42 popcnt avx avx2 avx512
Args: "bun" "index.ts" "-b" "false" "-l" "trace" "--serial"
Features: jsc Bun.stdin(2) bunfig dotenv(466) fetch(95) http_server spawn(653) transpiler_cache(39) tsconfig_paths tsconfig(17) WebSocket(20) workers_spawned(465) workers_terminated(433)
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:path/win32" "node:perf_hooks" "node:process" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:timers/promises" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "node:punycode" "ws" "node-fetch"
Elapsed: 1426877ms | User: 165993ms | Sys: 48017ms
RSS: 0.02ZB | Peak: 1.79GB | Commit: 0.02ZB | Faults: 2609

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
(redacted)
```

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000000

- [`napi.cpp:447`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/bindings/napi.cpp#L447>): `NAPIFunction::call`
- *1 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_call_javascript`

Features: workers\_spawned, workers\_terminated, jsc, Bun.stdin, bunfig, dotenv, fetch, http\_server, spawn, transpiler\_cache, tsconfig\_paths, tsconfig, WebSocket

**Comment by ImBIOS** [comment] 2024-10-08 10:03
Let me know if you need anything.

**Comment by RiskyMH** [comment] 2024-10-12 06:03
Duplicate of #14402

**Closed as not planned by RiskyMH** 2024-10-12 06:03 UTC
Labels: crash, linux, runtime
