### ISSUE TITLE
Bun can not use the package which is added with `pnpm` in Windows

### ISSUE THREAD

**Issue by PrinOrange** [oven-sh/bun#10218] opened 2024-04-12 15:34 UTC
### What version of Bun is running?

1.1.3

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

First, init a empty project
```bash
bun init
```
Then add any packages with `pnpm`, take the `lodash` for example
```bash
pnpm add lodash
pnpm add @types/lodash -D
```
Then use the lodash's exported function in main script file, in `hello.ts`
```typescript
import _ from 'lodash';

console.log(_.chunk(['a', 'b', 'c', 'd'], 2));
```

And execute it.
```bash
bun run hello.ts
```

Then it throws the error:
```
PS E:\frontend-projects\bun-test> bun hello.ts
error: Unexpected reading "E:\frontend-projects\bun-test\node_modules\lodash"
```

### What is the expected behavior?

For compatibility with node.js, bun is excepted to correctly use the `pnpm`

**Comment by PrinOrange** [comment] 2024-04-12 15:43
I guess the reason may be this: pnpm will use symbolic links for some packages to link the exported packages, and bun will have an error when reading the symbolic links.
![image](https://github.com/oven-sh/bun/assets/73331790/4cd05535-f033-4465-87f9-dac4192cd23a)

**Comment by gvilums** [comment] 2024-04-12 19:39
Duplicate of #10013

**Closed as not planned** 2024-04-12 19:39 UTC
Labels: bug
