### ISSUE TITLE
crash: Failed to enable File Watcher (bun --hot)

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#11954] opened 2024-06-18 15:19 UTC
### Stack Trace (bun.report)

Bun v1.1.14-canary ([`9621721`](<https://github.com/oven-sh/bun/tree/9621721e3df4f618cc1f975b043dbefd7fd61c07>)) on linux x86_64 [AutoCommand]

**panic**: Failed to enable File Watcher

- [`javascript.zig:3836`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/bun.js/javascript.zig#L3836>): `src.bun.js.javascript.NewHotReloader`
- [`bun_js.zig:267`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/bun_js.zig#L267>): `src.bun.js.javascript.OpaqueWrap__anon_53574__struct_287229.callback`
- [`bindings.cpp:4633`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/bun.js/bindings/bindings.cpp#L4633>): `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/bun.js/bindings/shimmer.zig#L186>): `src.bun_js.Run.boot`
- [`cli.zig:2016`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/cli.zig#L2016>): `src.cli.Command.maybeOpenWithBunJS`
- [`cli.zig:1883`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/cli.zig#L1883>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/9621721e3df4f618cc1f975b043dbefd7fd61c07/src/main.zig#L50>): `main`

Features: jsc, tsconfig

**Comment by paperdave** [comment] 2024-06-20 00:57
When my linked PR is merged, can you re-try your reproduction? otherwise i will close as duplicate of #6856 / has no reproduction.

**Comment by huseeiin** [comment] 2024-06-20 09:36
> When my linked PR is merged, can you re-try your reproduction? otherwise i will close as duplicate of #6856 / has no reproduction.

i lost my code :)) you can close as duplicate

**Closed as not planned** 2024-06-20 18:54 UTC
Labels: crash, linux
