### ISSUE TITLE
Bun.serve throw Error log on async error

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#8217] opened 2024-01-17 00:05 UTC
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

```ts
Bun.serve({
    port: 3000,
    fetch: async () => {
        throw new Error("A");

        return new Response("A");
    },
    error: async () => {
        // here we need to perform some async operation
        await Bun.sleep(100);

        return new Response("Handled");
    },
});
```

### What is the expected behavior?

the expected behavior is to return `Handled`

### What do you see instead?

An error log.

![CleanShot 2024-01-17 at 01 03 00](https://github.com/oven-sh/bun/assets/6713842/5f6f0d07-de1f-46ba-8842-2161d0b53783)

**Comment by LukasKastern** [comment] 2024-01-17 00:07
Got this working [here](https://github.com/oven-sh/bun/compare/main...LukasKastern:bun:serve-async-on-error).
Will add tests and try to get a pull request up tomorrow.

**Comment by TiBianMod** [comment] 2024-01-17 00:09
Really cool, many thanks @LukasKastern

❤️

**Comment by Electroid** [comment] 2024-01-17 06:16
Duplicate of #3779

**Closed as completed** 2024-01-19 19:01 UTC
Labels: bug, bun.js
