### ISSUE TITLE
dynamic required not working 

### ISSUE THREAD

**Issue by FaizanAqeek** [oven-sh/bun#3148] opened 2023-06-01 08:02 UTC
### What version of Bun is running?

0.6.5

### What platform is your computer?

windows subsystem 

### What steps can reproduce the bug?

I just run bun start it give me an error like this 

![image](https://github.com/oven-sh/bun/assets/11156849/8f53b0bc-bf68-4f1f-a246-cdd3b9b4f28f)

### What is the expected behavior?

it should be easily run as usual.

**Comment by Electroid** [comment] 2024-02-05 18:21
Duplicate of #299

**Comment by Electroid** [comment] 2024-02-05 18:21
This should now be fixed, let us know if you're still experiencing this issue.

**Closed as not planned by Electroid** 2024-02-05 18:21 UTC
Labels: bug, node.js
