### ISSUE TITLE
Cast 104[handle] -> FDImpl.UV makes closing impossible!

### ISSUE THREAD

**Issue by malooski** [oven-sh/bun#13702] opened 2024-09-03 00:34 UTC
### How can we reproduce the crash?

When using the Bluesky API library, seems to crash when setting up credential session.

```
import { CredentialSession } from "@atproto/api";

const session = new CredentialSession(new URL(ENV.BSKY_SERVICE_URL));
```

### Relevant log output

```shell
The supplier of this FileDescriptor should call 'bun.toLibUVOwnedFD'
or 'FDImpl.makeLibUVOwned', probably where open() was called.
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

https://bun.report/1.1.26/wa10a37423AioigwD0q9lQq3ol3C__24xsyBA0eNo1zbEKwjAURuG9T/E7VUGLgrOLpSAILtZFHJLmaoK3uSG3pfj2ouh84Hx7owM26+3Vm+iYbljt0NSHPnHVXtCbJyk6Fg3xgdAnUQ2WaVYUZ0/QMSUOlCF3DD4omsBUk3Y5pEEy1MvIDp1hRmnHWA1yDLa9nKZIrqnLQjLKn/ah/pFcuUTKYo3lFyZPmSCJ4nyByej3R656A5dYQK0
```

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on windows x86_64 [AutoCommand]

**panic**: Cast 488[handle] -> FDImpl.UV makes closing impossible!

The supplier of this FileDescriptor should call 'bun.toLibUVOwnedFD'
or 'FDImpl.makeLibUVOwned', probably where open() was called.

- [`js_ast.zig:3211`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/src/js_ast.zig#L3211>): `assert`
- [`JSCJSValue.h:752`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/C:/buildkite-agent/builds/windows-x64-hetzner-6/bun/bun/build/bun-webkit/include/JavaScriptCore/JSCJSValue.h#L752>): `JSC::ensureStillAliveHere`
- *2 unknown/js code*
- `llint_entry`

**Comment by Jarred-Sumner** [comment] 2024-09-03 08:20
Duplicate of https://github.com/oven-sh/bun/issues/13653

**Comment by Jarred-Sumner** [comment] 2024-09-03 08:20
This will get fixed, but we are tracking it in https://github.com/oven-sh/bun/issues/13653

**Closed as completed by Jarred-Sumner** 2024-09-03 08:20 UTC
Labels: crash, windows
