### ISSUE TITLE
custom transformer for `Bun.Transpiler`

### ISSUE THREAD

**Issue by HairyRabbit** [oven-sh/bun#3936] opened 2023-08-03 00:56 UTC
### What is the problem this feature would solve?

would we plan to support custom transformers ?

### What is the feature you are proposing to solve the problem?

like tsc transpiler:

```ts
ts.transpileModule(source, {
  //...
  transformers: {
    before: [],
    after: [],
  }
})
```

**Comment by Electroid** [comment] 2023-08-03 01:02
Are you referring to AST transformers?

**Comment by HairyRabbit** [comment] 2023-08-03 01:07
yup, i need rewrite ast before build.

**Comment by Electroid** [comment] 2023-10-26 22:24
Closing as duplicate of #2729

**Closed as not planned by Electroid** 2023-10-26 22:24 UTC
Labels: enhancement
