### ISSUE TITLE
Error when importing third party library

### ISSUE THREAD

**Issue by scarletjack** [oven-sh/bun#1309] opened 2022-10-11 09:38 UTC
### Version

0.1.13

### Platform

Linux dev 5.15.0-48-generic #54-Ubuntu SMP

### What steps will reproduce the bug?

1. Run `bun install stimulsoft-reports-js` in new project
2. 
```ts

import { Stimulsoft } from "stimulsoft-reports-js"

console.log(Stimulsoft)
```

3. Execute

### How often does it reproduce? Is there a required condition?

Every run

### What do you see instead?

https://user-images.githubusercontent.com/68049836/195055281-23e1f925-90f4-4d81-b9b7-4d6de5725538.mp4

**Comment by Electroid** [comment] 2023-10-25 19:39
```js
SyntaxError: Import named 'Stimulsoft' not found in module 'node_modules/stimulsoft-reports-js/index.js'.
```

Duplicate of #1137

**Comment by Electroid** [comment] 2023-10-25 19:39
Duplicate of #1137

**Closed as not planned by Electroid** 2023-10-25 19:39 UTC
Labels: bug
