### ISSUE TITLE
Creating a database using `better-sqlite3` crashes upon calling the constructor

### ISSUE THREAD

**Issue by MarByteBeep** [oven-sh/bun#14214] opened 2024-09-27 15:03 UTC
### How can we reproduce the crash?

All you need to call is the following:
```ts
import Database from 'better-sqlite3';
const db = new Database('./test.sqlite');
```

### Relevant log output

```shell
When using `--watch` a little more output is generated:

107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at bindings (.\node_modules\bindings\bindings.js:112:48)
      at new Database (.\node_modules\better-sqlite3\lib\database.js:48:29)
```

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x7FFA56F14D80

- *1 unknown/js code*
- ??? at `0x5175c` in ntdll.dll
- ??? at `0x514b7` in ntdll.dll
- ??? at `0x5115d` in ntdll.dll
- ??? at `0x17fab` in KERNEL32.DLL
- [`exit.cpp:137`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/appcrt/startup/exit.cpp#L137>): `exit_or_terminate_process`
- [`exit.cpp:274`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/appcrt/startup/exit.cpp#L274>): `common_exit`
- [`Global.zig:121`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/Global.zig#L121>): `exit`
- [`javascript.zig:1316`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L1316>): `globalExit`
- [`javascript.zig:1228`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L1228>): `eventLoop`

Features: jsc, tsconfig

**Comment by 190n** [comment] 2024-09-27 22:21
Duplicate of #4290.

This happens because better-sqlite3 uses some V8 methods Bun doesn't implement yet. Track progress in that issue.

**Closed as not planned by 190n** 2024-09-27 22:21 UTC
Labels: crash, windows
