### ISSUE TITLE
Multer-s3 breaks on bun but works fine with node when contentType: multerS3.AUTO_CONTENT_TYPE

### ISSUE THREAD

**Issue by aditya-kumarr** [oven-sh/bun#7879] opened 2023-12-28 03:32 UTC
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

When I try to upload an image file to s3 in a way that it doesn't get downloaded when I click the link, it should use the contentType of the upload and and contentDesposition to be inline so that It opens a preview in browser, but the  `contentType: multerS3.AUTO_CONTENT_TYPE`
freezes the multer middleware,
I thought this was a multer issue but it worked fine with node, I faced a similar issue with file upload on device storage but it was fixed in latest update, hope this gets fixed as well.

```javascript
import multer from "multer";
import multerS3 from "multer-s3";
import { S3 } from "./video-upload.js";
import express, { Router } from "express";

const s3 = S3();

const upload = multer({
  storage: multerS3({
    s3: s3,
    bucket: "bucket-0",
    acl: "public-read", // Set the ACL for uploaded files
    contentDisposition: "",
    contentType: multerS3.AUTO_CONTENT_TYPE, // Set the content type for uploaded files
    cacheControl: "max-age=31536000", // Set the cache control for uploaded files
    shouldTransform: true, // Enable automatic transformation of uploaded files
    transforms: [{ id: "original", key: "original" }],
    metadata: function (req, file, cb) {
      cb(null, { fieldName: file.fieldname });
    },
    key: function (req, file, cb) {
      cb(null, Date.now().toString() + "-" + file.originalname);
    },
  }),
});

const router = Router();

router.post("/upload", upload.single("file"), (req, res) => {
  // Access uploaded file details using req.file
  const s3Url = req.file;
  res.json({ message: "File uploaded successfully", url: s3Url.location });
});

// export function VideoRoutes() {
//   return router;
// }

const app = express();
app.use("/video", router);

app.listen(3000, () => console.log("app started"));

//import express

```

just in case this is the curl request I was making
```bash
curl -X POST -H "Content-Type: multipart/form-data" -F "file=@who.png" http://localhost:3000/video/upload
```

### What is the expected behavior?

The middleware shouldn't freeze and assign the mimetype of the file correctly

### What do you see instead?

The multer middleware freezes

**Comment by sp90** [comment] 2024-01-08 09:56
In the latest revision `1.0.21+437faa944` I got both single-file, multi-file, and s3 uploads working

https://github.com/sp90/bun-multer-busboy

This issue is related to #2026

**Comment by Electroid** [comment] 2024-01-17 06:19
Duplicate of #2026

**Closed as not planned by Electroid** 2024-01-17 06:19 UTC
Labels: bug
