### ISSUE TITLE
Do not pass posix paths to Windows APIs, was given '\package.json'.

### ISSUE THREAD

**Issue by chirantanaditya** [oven-sh/bun#12922] opened 2024-07-29 20:11 UTC
### How can we reproduce the crash?

I tried to add 

```javascript
bunx add shadcn-ui@latest 
``` 

### Relevant log output

```shell
bun add v1.1.21 (70ca2b76)
============================================================
Bun v1.1.21 (70ca2b76) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\chira\AppData\Roaming\npm\node_modules\bun\bin\bun.exe" "add" "shadcn-ui@latest"
Elapsed: 4484ms | User: 0ms | Sys: 93ms
RSS: 0.21GB | Peak: 0.21GB | Commit: 0.33GB | Faults: 50824

panic(main thread): Internal Error: Do not pass posix paths to Windows APIs, was given '\package.json'. Please open an issue on GitHub with a reproduction.
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on windows x86_64 [AddCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '\package.json'. Please open an issue on GitHub with a reproduction.

- [`string_immutable.zig:814`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/string_immutable.zig#L814>): `eqlComptimeCheckLenU8`
- [`encoding.zig:853`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/webcore/encoding.zig#L853>): `Bun__encoding__toString`
- [`fs.zig:258`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/deps/zig/lib/std/fs.zig#L258>): `cwd`
- [`array_list.zig:881`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/deps/zig/lib/std/array_list.zig#L881>): `swapRemove`
- [`windows.zig:2091`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/deps/zig/lib/std/os/windows.zig#L2091>): `teb`
- [`semver.zig:277`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/semver.zig#L277>): `slice`
- [`install.zig:13146`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/install.zig#L13146>): `installPackages`
- [`install.zig:13986`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/install.zig#L13986>): `installWithManager`
- [`install.zig:10155`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/install.zig#L10155>): `updatePackageJSONAndInstallWithManagerWithUpdates`
- [`install.zig:9734`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/install.zig#L9734>): `updatePackageJSONAndInstall`

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:55
Duplicate of https://github.com/oven-sh/bun/issues/11215

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:55
Please follow along in https://github.com/oven-sh/bun/issues/11215

**Closed as not planned by Jarred-Sumner** 2024-08-06 07:55 UTC
Labels: crash, windows
