### ISSUE TITLE
ESM bundling for Node produces code for Bun

### ISSUE THREAD

**Issue by AlexXanderGrib** [oven-sh/bun#4861] opened 2023-09-10 21:07 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.2.0-23-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create node-js typescript example project
2. Add similar `build.js` script to it
```javascript
// eslint-disable-next-line no-undef
const result = await Bun.build({
  entrypoints: ["./src/entries/index.ts", "./src/entries/test.ts"],
  outdir: "./bun",
  minify: false,
  target: "node",
  // format: "esm",
  splitting: true,
  sourcemap: "external",
  external: [
    "@prisma/client",
    "tdlib-native/addon",
    "tdlib-native",
    "tdlib-native/markup",
    "tdlib-native/types",
    "sharp",
    "dotenv/config",
    "consola",
  ],
});


console.log(result)
```
3.
```bash
bun run build.js
```

### What is the expected behavior?

Bun produces file `bun/index.js` with following code at the top

```javascript
import sharp$1 from "sharp";
import fs$1 from "fs";
...
```

### What do you see instead?

Bun produces file `bun/index.js` with following code at the top

```javascript
import {
__commonJS,
__esm,
__export,
__require,
__toCommonJS,
__toESM
} from "./chunk-cfa6763f1a4ae00a.js";
```

Which uses `import.meta.require()` to load modules, so it crashes when i try to run it with node.

**Comment by SijmenHuizenga** [comment] 2023-09-11 15:21
Possible duplicate of #2858

**Comment by mathiasrw** [comment] 2023-10-04 04:07
A number of issues are connected to this

- https://github.com/oven-sh/bun/issues/6168
- https://github.com/oven-sh/bun/issues/5707
- https://github.com/oven-sh/bun/issues/5154
- https://github.com/oven-sh/bun/issues/4861
- https://github.com/oven-sh/bun/issues/2858

Looks like https://github.com/oven-sh/bun/issues/6168#issuecomment-1745990151 got a workaround while we wait for a solution.

**Comment by Electroid** [comment] 2023-10-27 21:45
This is a duplicate of the many issues already linked above. We will fix these issues. https://github.com/oven-sh/bun/issues/2858

**Closed as not planned by Electroid** 2023-10-27 21:45 UTC
Labels: bug
