### ISSUE TITLE
issues with fastify.inject

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5188] opened 2023-09-13 01:36 UTC
I'm getting the following error when I try to run `bun test` my tests uses `fastify.inject`for fake HTTP injection (https://fastify.dev/docs/latest/Guides/Testing/#benefits-of-using-fastifyinject)

```sh
622 | }
623 | var OriginalWriteHeadFn, OriginalImplicitHeadFn;
624 |
625 | class ServerResponse extends Writable {
626 |
627 |   constructor({ req, reply }) {
                              ^
TypeError: Cannot call a class constructor without |new|
      at ServerResponse (node:http:627:26)
      at new Response (/home/ander-server/Desktop/ossound/node_modules/light-my-request/lib/response.js:10:2)
      at /home/ander-server/Desktop/ossound/node_modules/light-my-request/index.js:62:18
      at new Promise (:1:20)
      at doInject (/home/ander-server/Desktop/ossound/node_modules/light-my-request/index.js:60:11)
      at /home/ander-server/Desktop/ossound/node_modules/light-my-request/index.js:137:20
      at /home/ander-server/Desktop/ossound/node_modules/light-my-request/index.js:83:8
      at processTicksAndRejections (:1:2602)
      at /home/ander-server/Desktop/ossound/tests/user/create-user.test.ts:5:0
```

_Originally reported on Discord: [`issues with fastify.inject`](https://discord.com/channels/876711213126520882/1150898011380142090/1150898011380142090)_

**Comment by sirenkovladd** [comment] 2023-09-13 20:28
Duplicate of https://github.com/oven-sh/bun/issues/4415

**Closed as completed** 2024-01-25 08:21 UTC
Labels: bug, node.js
