### ISSUE TITLE
Function.toString() omits function name in output

### ISSUE THREAD

**Issue by luckydye** [oven-sh/bun#9543] opened 2024-03-21 13:34 UTC
### What version of Bun is running?

1.0.33+9e91e137f

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Run:

```bash
echo "function myFunction() {
  console.log('Test function');
  if (true) {
    return 1;
  }
}
console.log('export ' + myFunction.toString());" > test.js && bun test.js
```

### What is the expected behavior?

Expected ouput:

```ts
export function myFunction() {
  console.log('Test function');
  if (true) {
    return 1;
  }
}
```

### What do you see instead?

```ts
export function() {
  console.log("Test function");
  return 1;
}
```

### Additional information

I came across this issue when trying to run [@vitejs/plugin-vue-jsx](https://github.com/vitejs/vite-plugin-vue) which relies on Function.toString to include the name for export, like in my example above.

**Comment by Electroid** [comment] 2024-03-21 17:30
Duplicate of #3248

**Closed as not planned by Electroid** 2024-03-21 17:30 UTC
Labels: bug
