### ISSUE TITLE
bun crashedd

### ISSUE THREAD

**Issue by llaallii** [oven-sh/bun#11033] opened 2024-05-13 10:29 UTC
### How can we reproduce the crash?

PS C:\Users\Ratan\Desktop\Deviika\devika\ui> bun install
bun install v1.1.8 (89d25807)
  🔒 Saving lockfile... ============================================================
Bun v1.1.8 (89d25807) Windows x64
Args: "C:\Users\Ratan\.bun\bin\bun.exe", "install"
Elapsed: 649ms | User: 15ms | Sys: 31ms
RSS: 53.65MB | Peak: 53.65MB | Commit: 92.44MB | Faults: 13283

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`debug.zig:348`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/debug.zig#L348): `panic`
- [`output.zig:356`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/output.zig#L356): `panic`
- [`bun.zig:3177`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.zig#L3177): `assertionFailure`
- [`lockfile.zig:4902`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/lockfile.zig#L4902): `save`
- [`lockfile.zig:1643`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/lockfile.zig#L1643): `saveToDisk`
- [`install.zig:10942`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/install/install.zig#L10942): `installWithManager`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1440`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L1440): `start`
- [`cli.zig:62`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/cli.zig#L62): `start`

**Comment by dylan-conway** [comment] 2024-05-13 21:33
Duplicate of https://github.com/oven-sh/bun/issues/10849

**Closed as not planned by dylan-conway** 2024-05-13 21:33 UTC
Labels: bug, crash
