### ISSUE TITLE
`ProxyAgent` in `"undici"` doesn't work

### ISSUE THREAD

**Issue by yunyu950908** [oven-sh/bun#4457] opened 2023-09-02 15:43 UTC
### What version of Bun is running?

0.8.2+5288178c865cd9dcb500b00a65197bf2641d4e5c

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

hi, I got some problem with undici

I've already get undici installed by bun
```
╰>>> bun add undici
bun add v0.8.2 (5288178c)

 installed undici@5.23.0
```

and here is the sample code 
```ts
import { ProxyAgent } from "undici";

console.log(ProxyAgent.name);

```

but bun reports me the export class `ProxyAgent` not found in undici
```
╰>>> bun run index.ts 
SyntaxError: Import named 'ProxyAgent' not found in module 'undici'.
```

### What is the expected behavior?

ts-node can run this piece of code properly, print the name of the imported class `ProxyAgent`

```
╰>>> ts-node-esm index.ts 
ProxyAgent
```

### What do you see instead?

```
╰>>> bun run index.ts 
SyntaxError: Import named 'ProxyAgent' not found in module 'undici'.
```

**Comment by Hebilicious** [comment] 2023-09-04 11:05
Related to lack of proxy support : https://github.com/oven-sh/bun/issues/4474

**Comment by Electroid** [comment] 2023-10-27 18:59
Closing as duplicate of https://github.com/oven-sh/bun/issues/4474

**Closed as not planned by Electroid** 2023-10-27 18:59 UTC
Labels: bug, node.js
