### ISSUE TITLE
Worker doesn't accept a Data URL

### ISSUE THREAD

**Issue by uhop** [oven-sh/bun#11030] opened 2024-05-13 05:35 UTC
### What version of Bun is running?

1.1.8

### What platform is your computer?

Linux 6.5.0-28-generic x86_64 x86_64

### What steps can reproduce the bug?

It can be reproduced in `bun-repl`:

```bash
$ bunx bun-repl
Welcome to Bun v1.1.8
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> new Worker('data:text/javascript,' + encodeURIComponent('console.log(123456789)'), {type: 'module'})
Worker {}
> new Worker('data:text/javascript;base64,' + btoa('console.log(123456789)'), {type: 'module'})
Worker {}
```

The very same code works in `deno`. Removing `{type: 'module'}` doesn't help.

### What is the expected behavior?

Something like that:

```bash
$ deno
Deno 1.43.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> new Worker('data:text/javascript,' + encodeURIComponent('console.log(123456789)'), {type: 'module'})
123456789
Worker { onerror: null, onmessage: null, onmessageerror: null }
> new Worker('data:text/javascript;base64,' + btoa('console.log(123456789)'), {type: 'module'})
Worker { onerror: null, onmessage: null, onmessageerror: null }
> 123456789
```

In short: it should print something.

### What do you see instead?

It doesn't run any code encoded as a Data URL.

### Additional information

My use case is simple: I want to run some tasks on spare CPUs. The tasks require some additional information. Using a Data URL I can modify a task using some simple templating, like the back-quote operator. It can be done by loading an external file, but:

* It is a hassle to bundle a file.
* I need to organize some `postMessage()` interactions to pass arguments.
* I need to load some stuff dynamically.

In short: it complicates the code needlessly yet significantly. It would be preferable to avoid it.

**Comment by uhop** [comment] 2024-05-13 05:56
I assumed that it should also accept a blob URL (as per the standard). I tried to create one with `URL.createObjectURL()` only to find that it is not implemented yet: it returns `undefined` instead of a string. So it looks like a working data URL is the only option.

**Comment by Electroid** [comment] 2024-05-13 17:18
Duplicate of #6377

**Closed as not planned by Electroid** 2024-05-13 17:18 UTC
Labels: bug

**Comment by uhop** [comment] 2024-05-14 05:57
I respect your decision, but at least throw an error if data URLs are not accepted. It'll save you and your users some time and aggravation.
