### ISSUE TITLE
Better support for bun workspaces

### ISSUE THREAD

**Issue by zemse** [oven-sh/bun#9204] opened 2024-03-02 17:41 UTC
### What is the problem this feature would solve?

I am experimenting with the bun workspaces. 

```
- project-a
    - src 
    - package.json 
- project-b
    - src
    - package.json
- package.json
```

I found that it lacks these following issues:

- allow installing packages in workspace projects from the root e.g. `bun add <dep-name> --workspace project-a`
- allow triggering scripts in workspace projects from the root e.g. `bun run <script> --workspace project-a`
- allow triggering scripts in all workspace projects from the root e.g. `bun run build  --workspaces --if-present`

### What is the feature you are proposing to solve the problem?

Cli commands like the following could be added to add this feature.

```
bun add <dep-name> --workspace project-a

bun run <script> --workspace project-a

bun run build  --workspaces --if-present
```

**Comment by with-heart** [comment] 2024-03-02 17:50
Related: #2232

**Comment by Electroid** [comment] 2024-03-03 17:26
We will do this, closing as a duplicate of #2232

**Comment by Electroid** [comment] 2024-03-03 17:26
Duplicate of #2232

**Closed as not planned by Electroid** 2024-03-03 17:26 UTC
Labels: enhancement, bun install
