### ISSUE TITLE
Does not run on AMD FX-4100

### ISSUE THREAD

**Issue by Lambdac0re** [oven-sh/bun#1044] opened 2022-08-10 08:56 UTC
### Version

0.1.7

### Platform

Linux Vulcan 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```
$ curl https://bun.sh/install | bash
$ bun
Illegal instruction
```

### How often does it reproduce? Is there a required condition?

Always fails

### What is the expected behavior?

Bun runs

### What do you see instead?

`Illegal instruction`

**Comment by xhyrom** [comment] 2022-08-10 12:22
Already fixed, use canary build:
Check https://github.com/oven-sh/bun/issues/1011

**Comment by xhyrom** [comment] 2022-08-10 12:23
Duplicate of https://github.com/oven-sh/bun/issues/1011

**Closed as completed by xhyrom** 2022-08-10 12:22 UTC
Labels: bug, needs repro

**Comment by AsuToki360** [comment] 2026-05-30 00:51
Still crashing on FX-6300, can't run, just pure SEGILL, even tried as root, CachyOS (Arch Linux based). Tried all versions with "downgrade" package from Cachy, no success.

<img width="1148" height="605" alt="Image" src="https://github.com/user-attachments/assets/5a94c4be-3e7f-468a-927f-1657aa132ca9" />

```
[zsh] > bun --verbose
[1]    24685 illegal hardware instruction (core dumped)  bun --verbose

```

```
[root@calliope-cachyos calli]# bun
Illegal instruction        (core dumped) bun
[root@calliope-cachyos calli]# bun --verbose
Illegal instruction        (core dumped) bun --verbose
[root@calliope-cachyos calli]# 

```
