### ISSUE TITLE
error: AccessDenied

### ISSUE THREAD

**Issue by nirajchaurasiya** [oven-sh/bun#9084] opened 2024-02-24 07:29 UTC
### What version of Bun is running?

1.0.28

### What platform is your computer?

Linode 1 GB 25 GB 

### What steps can reproduce the bug?

root@localhost:/simple-backend# bun init -y

error: AccessDenied

----- bun meta -----
Bun v1.0.28 (70563847) Linux x64 #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023
Unknown:
Elapsed: 2ms | User: 7ms | Sys: 24ms
RSS: 33.55MB | Peak: 18.87MB | Commit: 33.55MB | Faults: 1
----- bun meta -----

0   0x55d225db070b
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

### What is the expected behavior?

It should create a basic backend app.

### What do you see instead?

error: AccessDenied

**Comment by Electroid** [comment] 2024-02-27 18:03
Duplicate of https://github.com/oven-sh/bun/issues/5723

**Closed as not planned by Electroid** 2024-02-27 18:03 UTC
Labels: bug, crash
