### ISSUE TITLE
[plugin:vanilla-extract] Module._load is not a function. (In 'Module._load(file, parentModule)', 'Module._load' is undefined)

### ISSUE THREAD

**Issue by ritikdoijod** [oven-sh/bun#6187] opened 2023-09-29 21:25 UTC
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 6.1.44-1-lts x86_64 unknown

### What steps can reproduce the bug?

Create react app using vite and install vanilla-extract/css then add the below code to respective files
`vite.config.ts` file:

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import {vanillaExtractPlugin} from "@vanilla-extract/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), vanillaExtractPlugin()],
});
```

`package.json` file:
```json
{
  "name": "test-ve",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@vanilla-extract/css": "^1.13.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vanilla-extract/vite-plugin": "^3.9.0",
    "@vitejs/plugin-react": "^4.0.3",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}
```
`app.css.ts` file: 
```ts
import { style } from '@vanilla-extract/css';

export const container = style({
  padding: 10
});
```

`App.tsx` file: 
```tsx
import { container } from "./app.css.ts";

function App() {

  return (
    <>
      <div className={container}></div>
    </>
  );
}

export default App;
```

### What is the expected behavior?

With nodejs and npm it is working as expected

### What do you see instead?

[plugin:vanilla-extract] Module._load is not a function. (In 'Module._load(file, parentModule)', 'Module._load' is undefined)

**Comment by Electroid** [comment] 2023-10-02 18:21
Duplicate of #5925

**Closed as not planned by Electroid** 2023-10-02 18:21 UTC
Labels: bug, node.js
