### ISSUE TITLE
1.0.8 unable to build containers on docker

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#6881] opened 2023-11-03 20:09 UTC
### What version of Bun is running?

1.0.8

### What platform is your computer?

Microsoft Windows NT 10.0.22000.0 x64

### What steps can reproduce the bug?

I built my containers with docker-compose, with this Dockerfile configs:

```docker
FROM oven/bun:latest

WORKDIR /app

COPY package.json .
COPY ./bun.lockb ./

RUN bun install

COPY . .

ENV PORT 3000
EXPOSE $PORT

CMD ["bun", "run", "start"]
```

### What is the expected behavior?

getting built normally!

### What do you see instead?

but these simple sets of configs throw an error titled: `0.458 Illegal instruction` 
and followed with coded with `exit code: 132`.

### Additional information

I believe that these bugs are because of making memory usage faster in this last version!

**Comment by andrebrito16** [comment] 2023-11-03 20:55
Same problem here, It works just for arm, tried to build for x86 and fails.

**Comment by Electroid** [comment] 2023-11-04 17:13
We're working on a fix for this. Duplicate of https://github.com/oven-sh/bun/issues/6869

**Closed as not planned by Electroid** 2023-11-04 17:13 UTC
Labels: bug
