### ISSUE TITLE
Decorators (probably circular issue) – ReferenceError: Cannot access uninitialized variable.

### ISSUE THREAD

**Issue by vprodan** [oven-sh/bun#6605] opened 2023-10-19 17:21 UTC
### What version of Bun is running?

1.0.7+378385ba60900be7bd797923c219ec489101f2f5

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Use decorator that uses type/class as the property type:
```js
...
@PrimaryColumn({ type: "varchar", length: 3 })
@ManyToOne(() => Country, (country) => country.cities)
country: Country
...
```

Simple fix:
```js
...
@PrimaryColumn({ type: "varchar", length: 3 })
@ManyToOne(() => Country, (country) => country.cities)
country: any
...
```

### What is the expected behavior?

Do not throw an `ReferenceError`

### What do you see instead?

```bash
9  | 
10 | @Entity()
11 | export class City {
12 |   @PrimaryColumn({ type: "varchar", length: 3 })
13 |   @ManyToOne(() => Country, (country) => country.cities)
14 |   country: Country
       ^
ReferenceError: Cannot access uninitialized variable.
      at /src/city.entity.ts:14:2
      at processTicksAndRejections (:61:76)
```

**Comment by Electroid** [comment] 2023-10-26 18:43
Duplicate of #2927

**Closed as not planned by Electroid** 2023-10-26 18:43 UTC
Labels: bug, typescript, bundler

**Comment by basemkhirat** [comment] 2023-12-27 01:19
Same for me: bun v1.0.20

```
     at processTicksAndRejections (:61:77)
16 |    @PrimaryGeneratedColumn("uuid")
17 |    id: string;
18 | 
19 |    @ManyToOne(() => Role, (role) => role.translations)
20 |    @JoinColumn({ name: "role_id" })
21 |    role: Role;
      ^
ReferenceError: Cannot access uninitialized variable.
      at /Users/basem/www/express-typescript/app/database/entities/role_translation.entity.ts:21:2
      at processTicksAndRejections (:61:77)

```
