### ISSUE TITLE
Add compile flag to Bun.build api

### ISSUE THREAD

**Issue by emirsassan** [oven-sh/bun#9121] opened 2024-02-26 19:25 UTC
### What is the problem this feature would solve?

Currently you can only provide compile flag via cli it will be a great thing to have it in the Bun.build api

### What is the feature you are proposing to solve the problem?

Adding compile flag into the Bun.build api

**Comment by paperdave** [comment] 2024-09-20 04:24
duplicate of #6249

**Closed as not planned by paperdave** 2024-09-20 04:24 UTC
Labels: enhancement, bundler
