### ISSUE TITLE
Nextjs 14 app development server

### ISSUE THREAD

**Issue by tuncatunc** [oven-sh/bun#13443] opened 2024-08-21 10:45 UTC
### How can we reproduce the crash?

bun --bun run dev

```json
{
  "name": "lit-airdrop",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "prisma": {
    "seed": "bun prisma/seed.ts"
  },
  "dependencies": {
    "@clerk/nextjs": "^5.3.2",
    "@heroicons/react": "^2.1.5",
    "@prisma/client": "5.18.0",
    "@tanstack/react-query": "^5.52.0",
    "@web3modal/wagmi": "^5.1.1",
    "dayjs": "^1.11.12",
    "next": "^14.2.5",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^2.19.8",
    "wagmi": "^2.12.7"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10",
    "eslint": "^8",
    "eslint-config-next": "13.5.4",
    "postcss": "^8",
    "prisma": "^5.18.0",
    "tailwindcss": "^3",
    "typescript": "^5"
  }
}

```

### Relevant log output

```shell
➜  git:(main) ✗ bun --bun run dev  
$ next dev
  ▲ Next.js 14.2.5
  - Local:        http://localhost:3000
  - Environments: .env.local, .env

 ✓ Starting...
 ✓ Ready in 4.1s
 ○ Compiling /src/middleware ...
 ✓ Compiled /src/middleware in 676ms (181 modules)
============================================================
Bun v1.1.25 (fe62a614) macOS Silicon
macOS v13.0.1
Args: "/opt/homebrew/Cellar/bun/1.1.25/bin/bun" "/Users/tuncatunc/repos/xxxx/node_modules/next/dist/server/lib/start-server.js"
Features: jsc Bun.stdin dotenv(2) fetch(3) http_server spawn(2) transpiler_cache(13) tsconfig_paths tsconfig 
Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns/promises" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:stream" "node:stream/web" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8" "node:diagnostics_channel" 
Elapsed: 7894ms | User: 3689ms | Sys: 592ms
RSS: 0.47GB | Peak: 0.47GB | Commit: 1.01GB | Faults: 79

panic(main thread): Segmentation fault at address 0x4000081B
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.25/Ma1fe62a61Aqoih0D__2q10D+u1l5Butwl5B+hrwrCuk92rC2xl3rCmm/2rCuk92rCA2A2hkgggC
```

### Stack Trace (bun.report)

Bun v1.1.25 ([`fe62a61`](<https://github.com/oven-sh/bun/tree/fe62a614046948ebba260bed87db96287e67921f>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x4000081B

- *2 unknown/js code*
- `WebCore::jsDOMURL_searchParams`
- `JSC::LLInt::performLLIntGetByID`
- `llint_slow_path_get_by_id`
- `llint_entry`
- `llint_entry`
- `llint_entry`
- `llint_entry`
- `llint_entry`

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:19
Duplicate of https://github.com/oven-sh/bun/issues/13629

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:19
Please follow along in https://github.com/oven-sh/bun/issues/13629. It will get fixed.

**Closed as completed by Jarred-Sumner** 2024-09-01 04:19 UTC
Labels: crash, macOS, runtime
