### ISSUE TITLE
Bun does not detect file changes with `--watch` flag when running inside a docker container with mounted volumes

### ISSUE THREAD

**Issue by lkuoch** [oven-sh/bun#14380] opened 2024-10-06 06:30 UTC
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

Here's the repo you can clone to reproduce it https://github.com/lkuoch/bun-hot-reload-error

On a high-level, the bun hot-reloading doesn't seem to work with docker volumes

Steps from the repo:
1. Run `docker-compose up --build`
2. Change the `console.log` in src/index.ts to anything

Should expect bun to pick up the changes and restart

It's very similar to https://github.com/oven-sh/bun/issues/2725 where in a mono-repo project I can reproduce the same error

Trying with external tools like watchexec also causes bun to report issues like `script not found` (similar to the above issue)

### What is the expected behavior?

Bun should pick up file changes and restart the application when the `--watch` flag is enabled and files are changed and synced across in docker via the mounted docker volume.

### What do you see instead?

Bun doesn't pick up the changes.
When restarting the service in docker you get a error: `Module not found`

### Additional information

I want this bug to be fixed to achieve a nice hot-reloading experience with Bun when developing on docker containers

**Comment by Jarred-Sumner** [comment] 2024-10-07 05:47
Duplicate of https://github.com/oven-sh/bun/issues/5841

**Comment by Jarred-Sumner** [comment] 2024-10-07 05:47
Please follow along in https://github.com/oven-sh/bun/issues/5841

**Closed as not planned by Jarred-Sumner** 2024-10-07 05:47 UTC
Labels: bug, needs triage
