### ISSUE TITLE
pdfjs-dist bug dyld[33775]: missing symbol called zsh: killed bun index.ts

### ISSUE THREAD

**Issue by itsyoboieltr** [oven-sh/bun#9711] opened 2024-03-29 18:43 UTC
### What version of Bun is running?

1.0.36+40f61ebb9

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

1. bun init
2. bun i pdfjs-dist
3. bun i -D @types/pdfjs-dist
5. index.ts
```ts
import { getDocument } from 'pdfjs-dist';

const document = await getDocument('https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf').promise;

console.log(document.numPages);
```

### What is the expected behavior?

1

### What do you see instead?

dyld[34117]: missing symbol called
zsh: killed     bun index.ts

**Comment by Electroid** [comment] 2024-03-29 18:44
Duplicate of #6506

**Closed as not planned by Electroid** 2024-03-29 18:44 UTC
Labels: bug
