### ISSUE TITLE
req.on('data',...)  and req.on('end',....)  are not firing

### ISSUE THREAD

**Issue by diegovelascommerce** [oven-sh/bun#5817] opened 2023-09-20 17:28 UTC
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```shell 
$ git clone https://github.com/ruahman/javascript.git
$ cd ./javascript/nodejs/nodejs_tut
$ bun server.js
```
- go to broswer `localhost:3000`
- submit a simple text.

### What is the expected behavior?

the text you submitted should show up in messsage.txt.  also there should be some console log messages firing on `req.on('data',..) and req.on('end',...)`

### What do you see instead?

text never shows up in message.txt and neither do the console.log messages.   this works in node js

![image](https://github.com/oven-sh/bun/assets/113631804/9f301ceb-e73a-4982-83f2-39e7539e26ba)

**Comment by Electroid** [comment] 2023-09-20 18:11
Duplicate of #5632

**Closed as not planned by Electroid** 2023-09-20 18:11 UTC
Labels: bug, node.js
