### ISSUE TITLE
Jest: next jest config got validation warning and failed test

### ISSUE THREAD

**Issue by Kadphol** [oven-sh/bun#14547] opened 2024-10-14 07:19 UTC
### What version of Bun is running?

1.1.30

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

- Create next using `next/jest`

`jest.config.ts`:

```ts
import type { Config } from 'jest'
import nextJest from 'next/jest'

const createJestConfig = nextJest({
  dir: './',
})

const config: Config = {
  collectCoverageFrom: ['<rootDir>/src/**/*.(ts|tsx)'],
  coverageProvider: 'v8',
  coveragePathIgnorePatterns: ['/node_modules/', 'layout.tsx', '<rootDir>/src/types'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  moduleDirectories: ['node_modules', '<rootDir>/'],
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    customExportConditions: [''],
  },
  setupFiles: ['./jest.polyfills.js'],
  setupFilesAfterEnv: ['@testing-library/jest-dom', '@testing-library/react', '<rootDir>/jest.setup.ts'],
}

export default createJestConfig(config)
```

- Run `bun --bun run test` to run command `jest`

### What is the expected behavior?

- When run with `bun run test` which I assume it run with node mode.
- ![Image](https://github.com/user-attachments/assets/6f87cf09-98ef-4add-aa3c-53fd8d81d190)

### What do you see instead?

- Got this warning messages and error.
- ![Image](https://github.com/user-attachments/assets/c9c48df7-651a-4928-b580-74bd43bbb155)
- ![Image](https://github.com/user-attachments/assets/c336ebed-fe85-40fe-8aea-7e83e87dac8d)

### Additional information

Is it a problem with `next/jest` config? any workaround to run jest with node mode on ci?

**Comment by nektro** [comment] 2024-10-14 23:31
Duplicate of https://github.com/oven-sh/bun/issues/14346

**Closed as not planned by nektro** 2024-10-14 23:31 UTC
Labels: bug, needs triage
