### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by terrablue** [oven-sh/bun#10835] opened 2024-05-04 20:05 UTC
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Linux 6.8.9-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. Put `import gi from "node-gtk";` into a JS file `app.js`
2. Run `bun app.js`

### What is the expected behavior?

Bun should run without an error.

### What do you see instead?

`bun: symbol lookup error: /home/blue/test-native/node_modules/node-gtk/lib/binding/node-v115-linux-x64/node_gtk.node: undefined symbol: node_module_register`

**Comment by ralyodio** [comment] 2024-05-04 20:11
I'm also having this issue

**Comment by Jarred-Sumner** [comment] 2024-05-04 23:49
Duplicate of #4290

**Comment by Jarred-Sumner** [comment] 2024-05-04 23:49
Please follow along in #4290 to track this issue

**Closed as not planned by Jarred-Sumner** 2024-05-04 23:49 UTC
Labels: bug
