### ISSUE TITLE
Cannot find module "./util.inspect"

### ISSUE THREAD

**Issue by alansaji123** [oven-sh/bun#747] opened 2022-07-16 15:41 UTC
### Version

0.1.4

### Platform

Darwin Reons-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Install express
create a sample express app
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
run with bun
it shows the following error 
Cannot find module "./util.inspect"

### What is the expected behavior?

Example app listening on port 3000

### What do you see instead?

Cannot find module "./util.inspect"

**Comment by FinnRG** [comment] 2022-07-16 20:28
Duplicate of #679. Express support is tracked in #496.

**Closed as not planned by FinnRG** 2022-07-16 20:28 UTC
Labels: bug, needs repro

**Comment by xHyroM** [comment] 2022-08-04 05:52
Closed as not planned because this is duplicate (no because this is not planned), follow original issue for more informations.

**Comment by daivier** [comment] 2024-09-14 12:50
Reinstall, delete node_modules folder and run
npm install
