### ISSUE TITLE
Attach to Bun in VSCode on Windows does not work

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#11273] opened 2024-05-22 18:58 UTC
### What version of Bun is running?

1.1.9

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Follow the same steps as #8851 

In a command line:

bun --inspect=ws://localhost:6499/sokscp34lw index.ts
Listening on localhost:80
--------------------- Bun Inspector ---------------------
Listening:
  ws://localhost:6499/sokscp34lw
--------------------- Bun Inspector ---------------------
Inspect in browser:
  https://debug.bun.sh/#localhost:6499/sokscp34lw

Browsing to this URL in Chrome works as expected and I can hit breakpoints in Chrome.

Running "Attach to Bun" with the following launch.json configuration:

    {
      "type": "bun",
      "request": "attach",
      "name": "Attach to Bun",

      // The URL of the WebSocket inspector to attach to.
      // This value can be retrieved by using `bun --inspect`.
      "url": "ws://localhost:6499/sokscp34lw",
    }

### What is the expected behavior?

Bun will attach to the Chrome remote debugger and I will be able to hit breakpoints in VSCode.

### What do you see instead?

In the debug console:

Debugger detached.
connect ECONNREFUSED 127.0.0.1:6499
2 Debugger detached.
connect ECONNREFUSED 127.0.0.1:6499
2 Debugger detached.
connect ECONNREFUSED 127.0.0.1:6499
Debugger detached.

### Additional information

Probably related to #8851

**Comment by Electroid** [comment] 2024-05-22 20:37
Duplicate of #8851

**Closed as not planned by Electroid** 2024-05-22 20:37 UTC
Labels: bug
