### ISSUE TITLE
bun repl crash

### ISSUE THREAD

**Issue by eslym** [oven-sh/bun#12121] opened 2024-06-24 13:50 UTC
### How can we reproduce the crash?

```
bun repl
```

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on linux x86_64 [BunxCommand]

Segmentation fault at address 0x560C6A26972F

- `??`
- [`semver.zig:268`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/semver.zig#L268>): `src.cli.bunx_command.BunxCommand.exec`
- [`StandaloneModuleGraph.zig:677`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/StandaloneModuleGraph.zig#L677>): `src.cli.Cli.start`
- [`array_list.zig:0`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/deps/zig/lib/std/array_list.zig#L0>): `process.argsAlloc`

**Comment by Jarred-Sumner** [comment] 2024-06-24 20:10
Duplicate of #12070

**Comment by Jarred-Sumner** [comment] 2024-06-24 20:10
Fixed in #12071, to get the fix now run `bun upgrade --canary`

**Closed as not planned by Jarred-Sumner** 2024-06-24 20:10 UTC
Labels: crash, linux
