### ISSUE TITLE
Response Handling Issue - Google Cloud

### ISSUE THREAD

**Issue by adi-tomar** [oven-sh/bun#6889] opened 2023-11-04 04:29 UTC
### What version of Bun is running?

1.0.8+2a405f691e80725fe0b97b93afd3b8cfed13fa5f

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```js
const fs = require('fs');

// Imports the Google Cloud client library
const speech = require('@google-cloud/speech').v1p1beta1;

// Creates a client
const client = new speech.SpeechClient();

/**
 * TODO(developer): Uncomment the following lines before running the sample.
 */
// const fileName = 'Local path to audio file, e.g. /path/to/audio.raw';

const config = {
  encoding: 'LINEAR16',
  sampleRateHertz: 44100,
  languageCode: 'en-US'

};

const audio = {
  content: fs.readFileSync(fileName).toString('base64'),
};

const request = {
  config: config,
  audio: audio,
};

const [response] = await client.recognize(request);
const transcription = response.results
  .map(result => result.alternatives[0].transcript)
  .join('\n');
```

We are getting the same problem as in issue #4746 

### What is the expected behavior?

The program should send the information to the client and return the transcription.

### What do you see instead?

We are receiving a TypeError,

`
function getErrorStackString(error) {
      return error.stack.split('\n').slice(1).join('\n'); `

TypeError: undefined is not an object (evaluating 'error.stack.split')`

**Comment by Electroid** [comment] 2023-11-04 17:08
Thanks for reporting, we will fix this. Going to close as a duplicate of #4746

**Closed as not planned by Electroid** 2023-11-04 17:08 UTC
Labels: bug
