### ISSUE TITLE
Package and publish Bun on the Snap store

### ISSUE THREAD

**Issue by vanillajonathan** [oven-sh/bun#6623] opened 2023-10-20 20:18 UTC
### What is the problem this feature would solve?

Easy install, update and uninstall on Linux.

### What is the feature you are proposing to solve the problem?

Package Bun as a [Snap](https://snapcraft.io/) package and publish it on the Snap app store.

You can do this with the [snapcore/action-build](https://github.com/snapcore/action-build) GitHub Action.

**Comment by Electroid** [comment] 2023-10-20 20:21
Duplicate of #862

**Closed as not planned by Electroid** 2023-10-20 20:21 UTC
Labels: enhancement
