### ISSUE TITLE
`bunx prisma generate` fails with infinite hang

### ISSUE THREAD

**Issue by vedantroy** [oven-sh/bun#15655] opened 2024-12-08 19:13 UTC
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Linux 6.8.0-36-generic x86_64 x86_64

### What steps can reproduce the bug?

`bunx prisma generate` fails (infinite hang), while `npx prisma generate` succeeds.

### Additional information

I wish I could provide more details, but once I ran `npx prisma generate` the error went away, even when doing `bunx prisma generate`.

**Comment by nektro** [comment] 2024-12-10 07:58
duplicate of https://github.com/oven-sh/bun/issues/14536

**Closed as not planned by nektro** 2024-12-10 07:58 UTC
Labels: bug, needs triage
