### ISSUE TITLE
`bun update` doesn't update `package.json` in windows and WSL

### ISSUE THREAD

**Issue by AhmedBaset** [oven-sh/bun#10088] opened 2024-04-08 20:59 UTC
### What version of Bun is running?

1.1.3

### What platform is your computer?

WSL: Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64 /n Windows: Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

- install any previous version of package for example `react@^18.0.0` (latest is `18.2.0`)
- run any of these:
	- `bun update`
	- `bun update react`
	- `bun update --force`

### What is the expected behavior?

update the package(s) to the latest

### What do you see instead?

the first (`bun update`) doesn't do anything at all. The others print to the console:
```bash
> bun update react
bun update v1.1.3 (2615dc74)

 installed react@18.2.0

[1004.00ms] done
```

but the package.json isn't updated:
```json
    "react": "^18.0.0"
```

Actually, it does update the package in node_modules. When I run this code:
```ts
import { version } from "react";

console.log("React version: ", version);
```
I get 
```bash
React version:  18.2.0
```

When I `rm node_modules -rf && bun i && bun run src/index.ts` again, I get `React version:  18.2.0`. It seems like it updates `bun.lockb` but not `package.json`

### Additional information

I tried on:
- bash (windows)
- wsl

**Comment by Electroid** [comment] 2024-04-08 22:55
Duplicate of #5856

**Closed as not planned by Electroid** 2024-04-08 22:55 UTC
Labels: bug
