### ISSUE TITLE
bun install crash

### ISSUE THREAD

**Issue by dennicLiu** [oven-sh/bun#12587] opened 2024-07-16 10:06 UTC
### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on linux x86_64 [InstallCommand]

Segmentation fault at address 0x000000B0

- `??`
- [`array_list.zig:1221`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/deps/zig/lib/std/array_list.zig#L1221>): `src.http.writeRequest__anon_139808`
- [`http.zig:514`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/http.zig#L514>): `src.deps.uws.NewSocketHandler`
- [`openssl.c:0`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/crypto/openssl.c#L0>): `us_socket_write`
- [`epoll_kqueue.c:450`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/eventing/epoll_kqueue.c#L450>): `us_timer_set`
- [`output.zig:844`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/output.zig#L844>): `src.output.printError__anon_123521`
- [`fmt.zig:1778`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/deps/zig/lib/std/fmt.zig#L1778>): `src.Progress.refreshWithHeldLock`
- `??`

**Comment by rohit-nayak123** [comment] 2024-07-17 07:48
Dude, try to upgrade bun to its latest version.

**Comment by dennicLiu** [comment] 2024-07-17 07:58
After the upgrade, I encountered the same issue. Please refer to my other issue report.

https://github.com/oven-sh/bun/issues/12601

**Comment by Jarred-Sumner** [comment] 2024-07-17 08:09
Duplicate of #12601

**Closed as not planned by Jarred-Sumner** 2024-07-17 08:09 UTC
Labels: crash, bun install, linux
