### ISSUE TITLE
Bun.serve + fetch segmentation fault

### ISSUE THREAD

**Issue by sh4den** [oven-sh/bun#6460] opened 2023-10-12 15:51 UTC
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 6.1.0-12-amd64 x86_64 unknown

### What steps can reproduce the bug?

```ts
Bun.serve({
    port: 80,
    async fetch(req, srv) {
        const url = req.url;
        const urlProxies = url.replace("#ipReverse#", "#ipTarget#");

        const res = await fetch(urlProxies, req);
        return res;
    },
});
```

### What is the expected behavior?

It had to forward the traffic as a reverse-proxy

### What do you see instead?

Segmentation fault

**Comment by Electroid** [comment] 2023-10-12 17:00
Duplicate of #6415

**Closed as not planned by Electroid** 2023-10-12 17:00 UTC
Labels: bug, bun.js
