### ISSUE TITLE
Segmentation fault when using Rsbuild

### ISSUE THREAD

**Issue by askareija** [oven-sh/bun#15046] opened 2024-11-08 03:23 UTC
### How can we reproduce the crash?

1. `bun create rsbuild@latest`
2. Options:
3. - Use Typescript
4. - Use Biome
5. Run `bun run dev`

I'm running this on VSCode Dev container, using latest Bun 1.1.34 with `oven/bun:debian` image

### Relevant log output

```bash
bun:/workspaces/react-boilerplate$ bun run dev
$ rsbuild dev
  Rsbuild v1.1.0

  ➜ Local:    http://localhost:3000/
  ➜ Network:  http://172.18.0.9:3000/
  ➜ press h + enter to show shortcuts

start   Building...
============================================================
Bun v1.1.34 (5e5e7c60) Linux x64 (baseline)
Linux Kernel v6.9.3 | glibc v2.31
CPU: sse42 popcnt avx avx2 avx512
Args: "node" "/workspaces/react-boilerplate/node_modules/.bin/rsbuild" "dev"
Features: Bun.stdin(2) http_server jsc tsconfig 
Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:v8" "node:inspector" 
Elapsed: 460ms | User: 494ms | Sys: 87ms
RSS: 1.04GB | Peak: 0.27GB | Commit: 1.04GB | Faults: 0

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.34/Bn15e5e7c6AkgglggCu0g2jE+8mO__msq35Dyvgt4E2g5nmF41ht7D__A2AK

error: script "dev" was terminated by signal SIGILL (Illegal instruction)
Illegal instruction (core dumped)
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`BunProcess.cpp:2646`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/BunProcess.cpp#L2646>): `Bun::jsFunctionDrainMicrotaskQueue`

Features: Bun.stdin, http\_server, jsc, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5870489603/">BUN-5R4</a></strong></sub>

**Comment by nektro** [comment] 2024-11-08 22:21
duplicate of https://github.com/oven-sh/bun/issues/11628

**Closed as not planned by nektro** 2024-11-08 22:21 UTC
Labels: crash, linux, runtime
