### ISSUE TITLE
`bun upgrade` upgrades to canary build without `--canary` flag

### ISSUE THREAD

**Issue by barbancho** [oven-sh/bun#13204] opened 2024-08-09 16:03 UTC
### What version of Bun is running?

1.1.22-canary.96+df33f2b2a

### What platform is your computer?

Linux 6.8.0-39-generic x86_64 x86_64

### What steps can reproduce the bug?

With 1.1.22, execute `bun upgrade` on shell and it will upgrade to `1.1.23-canary`

Cannot fully confirm bun revision before upgrade as using `bun upgrade --stable` downgrades to `1.1.22-canary.96+df33f2b2a`.

Issue persists with `1.1.22-canary` version when upgrading without flag. 

### What is the expected behavior?

To confirm bun is running on latest stable version and not upgrading it.

### What do you see instead?

Upgraded to canary

![bun-report](https://github.com/user-attachments/assets/abc328b0-92fc-46ae-bce4-54df76eae8e3)

**Comment by zoto-ff** [comment] 2024-08-09 16:24
duplicate of #13169

**Comment by paperdave** [comment] 2024-08-10 03:02
closing as duplicate

**Closed as not planned by paperdave** 2024-08-10 03:02 UTC
Labels: bug, needs triage
