### ISSUE TITLE
"Illegal instruction (core dumped)" when using bun through code-server

### ISSUE THREAD

**Issue by iwa** [oven-sh/bun#634] opened 2022-07-12 16:02 UTC
### Version

0.1.3

### Platform

Linux aed3b8b99da9 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

### What steps will reproduce the bug?

- Setup a code-server Docker container [(with official image)](https://coder.com/docs/code-server/latest/install#docker)
- Login into the online VSCode instance
- Open a terminal
- Install bun
- Try to run it (running `bun` or `bun help` will produce the issue)

### How often does it reproduce? Is there a required condition?

anytime you input a command with bun
the only exception seems to be `bun -v`

### What do you see instead?

![image](https://user-images.githubusercontent.com/19956672/178539274-3e993de5-085d-43ab-8fae-1c2a2b6dddd4.png)

### Additional information

I can provide that 'core' file if needed

**Comment by forinda** [comment] 2022-07-12 16:35
Have you checked the troubleshooting section of the `README.md` and tried it out if able to fix your issue with `sde`

**Comment by forinda** [comment] 2022-07-12 16:39
It's on issue #67 So this may be a duplicate of the issue already tackled in the troubleshooting section

**Comment by FinnRG** [comment] 2022-07-12 20:03
Duplicate of #67. Docker won't emulate AVX2 instructions.

**Closed as completed by FinnRG** 2022-07-12 20:03 UTC
Labels: bug, needs repro
