### ISSUE TITLE
Support for yarn version command in bun

### ISSUE THREAD

**Issue by chakrihacker** [oven-sh/bun#6483] opened 2023-10-13 16:05 UTC
### What is the problem this feature would solve?

Currently `yarn version` provides the current version and prompts you with the new version you want to use.I Would like to have this functionality for feature parity, so I can migrate from yarn to bun

https://classic.yarnpkg.com/lang/en/docs/cli/version/

### What is the feature you are proposing to solve the problem?

Provide new command called `bun version` that does what `yarn version` does

**Comment by Electroid** [comment] 2023-10-13 16:30
Duplicate of #5291

**Closed as completed by Electroid** 2023-10-13 16:30 UTC
Labels: enhancement, bun install
