### ISSUE TITLE
bun audit not exists

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#10520] opened 2024-04-25 20:50 UTC
### What version of Bun is running?

1.1.4

### What platform is your computer?

windows 11, build 22000

### What steps can reproduce the bug?

```sh
bun audit fix
error: Script not found "audit"
```

**Comment by Electroid** [comment] 2024-04-25 21:16
Duplicate of #5359

**Closed as not planned by Electroid** 2024-04-25 21:16 UTC
Labels: enhancement
