### ISSUE TITLE
SvelteKit Node adapter not working

### ISSUE THREAD

**Issue by notramo** [oven-sh/bun#14299] opened 2024-10-02 17:22 UTC
### What version of Bun is running?

latest from nightly Docker

### What platform is your computer?

Linux 6.1.94_1 x86_64 unknown

### What steps can reproduce the bug?

1. Create SvelteKit project
2. Install `@sveltejs/adapter-node`
3. Enable Node adapter in `svelte.config.js`
4. `bun run build`
5. `bun run ./build/`

### What is the expected behavior?

Server starts (Node can run the same build output properly).

### What do you see instead?

```
$ bun run ./build/
176 | 				(req, _, next) => {
177 | 					if (typeof base === 'string') {
178 | 						let len = base.length;
179 | 						base.startsWith('/') || len++;
180 | 						req.url = req.url.substring(len) || '/';
181 | 						req.path = req.path.substring(len) || '/';
      ^
TypeError: Cannot specify both hostname and unix
 code: "ERR_INVALID_ARG_TYPE"

      at serve (native:1:1)
      at node:http:540:16
      at listen (node:http:497:9)
      at listen (/home/bun/js/mydeals/build/index.js:181:29)
      at module code (/home/bun/js/mydeals/build/index.js:270:9)

Bun v1.1.30-canary.71+af82a446d (Linux x64 baseline)
```

### Additional information

**Why not use SvelteKit with Bun adapter?**

There are multiple Bun adapters for SvelteKit, but those are not officially supported by the Svelte team, and have serious, deployment-blocking bugs.

**Why not run the server with Node instead?**

I'm using Bun-specific APIs.

**Comment by Niewdanka** [comment] 2024-10-05 12:48
This error has been occurring since Bun version 1.1.21. If I use older versions, it works fine.

**Comment by Jarred-Sumner** [comment] 2024-11-03 00:34
Are you still running into this on Bun v1.1.32 or later? We reverted the original change that caused this

**Comment by Niewdanka** [comment] 2024-11-03 11:02
> Are you still running into this on Bun v1.1.32 or later? We reverted the original change that caused this

Unfortunately, yes. I can confirm that the issue still exists in version 1.1.34.

```199 | 		return this; // chainable
200 | 	}
201 |
202 | 	listen() {
203 | 		(this.server = this.server || http.createServer()).on('request', this.attach);
204 | 		this.server.listen.apply(this.server, arguments);
      ^
TypeError: Cannot specify both hostname and unix
 code: "ERR_INVALID_ARG_TYPE"

      at serve (native:1:1)
      at node:http:345:16
      at listen (node:http:303:9)
      at listen (/app/build/index.js:204:22)
      at module code (/app/build/index.js:270:9)
      at unknown:2:1
      at processTicksAndRejections (unknown:7:39)

Bun v1.1.34 (Linux arm64)```

**Comment by notramo** [comment] 2024-11-03 13:46
@Jarred-Sumner, the issue still occurs. Did you try the linked pull request #14307 ?

**Comment by DontMash** [comment] 2024-11-15 17:54
@notramo @Niewdanka 
I ran into this issue myself.
In my case it was even more painful since newer versions of bun fix some memory leaks we are facing.
But I found a solution, although I also would like to see a fix to be compatible with the @sveltejs/adapter-node.

You can use any new version of bun with sveltekit, if you use this community adapter package: https://github.com/gornostay25/svelte-adapter-bun. It is also mentioned in one of the official bun guides: https://bun.sh/guides/ecosystem/docker

**Comment by ttmx** [comment] 2024-11-17 15:42
Can confirm it is still an issue.

**Comment by Bewinxed** [comment] 2024-11-20 14:18
Facing this as well on the latest versions of bun/sveltekit

**Comment by ierror** [comment] 2024-11-23 11:30
same here, svelte kit stopped working with bun

**Comment by RiskyMH** [comment] 2024-11-25 05:47
The issue seems to be from Bun's `http.createServer().listen()` implementation and accepting list in the `.apply`

```ts
const http = require('http')

// this works in node and bun
const server1 = http.createServer()
server1.listen.apply(server1, {'0': { path: false, host: "0.0.0.0", port: "3000" }});

// this throws the error in bun (node works)
const server2 = http.createServer()
server2.listen.apply(server2, [{ path: false, host: "0.0.0.0", port: "3000" }]);
```

The error is kind of confusing because [`node:http` is a fancy polyfill of `Bun.serve`](https://github.com/oven-sh/bun/blob/main/src/js/node/http.ts#L607)

**Comment by Jarred-Sumner** [comment] 2024-11-25 23:42
THe fix for this will be part of Bun v1.1.37, which releases in an hour

**Closed as completed** 2024-11-25 23:42 UTC
Labels: bug, needs investigate

**Comment by VityaSchel** [comment] 2025-09-20 13:35
This is still happening for me on v1.2.20. Tried both with and without --bun flag. I confirmed that this issue is not present with node.js v22.18.0. Can this be reopened?

**Comment by nektro** [comment] 2025-09-20 17:58
if this has indeed regressed at any point please open a new issue with your reproduction
