### ISSUE TITLE
Bun.build with sourcemap: 'inline' changes assets imports URLs

### ISSUE THREAD

**Issue by KatSick** [oven-sh/bun#7888] opened 2023-12-28 11:10 UTC
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

1. `bun init`
2. add some `file.png`  (does not matter)
3. write:
```ts
import png from "./file.png";

console.log(png);
```
4. run `bun build --sourcemap=inline index.ts --target=browser --outdir=dist`
5. inspect `index.js` file

### What is the expected behavior?

```js
// file.png
var file_default = "./file-98f44bdbb51a95dc.png";

// index.ts
console.log(file_default);
```

### What do you see instead?

```js
// file.png
var file_default = "/home/panas/projects/github/bun-bug-build-assets-sourcemap/file.png";

// index.ts
console.log(file_default);
```

### Additional information

it is only affected with `--sourcemap=inline`. if you remove it, you will see expected result

**Comment by antonlyap** [comment] 2024-03-23 16:57
Isn't this a duplicate of https://github.com/oven-sh/bun/issues/6553?

**Comment by paperdave** [comment] 2024-07-19 05:39
this no longer reproduces

**Closed as completed by paperdave** 2024-07-19 05:39 UTC
Labels: bug, bundler, sourcemaps
