### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by R0N1n-dev** [oven-sh/bun#1012] opened 2022-08-07 06:55 UTC
### Version

Illegal instruction

### Platform

Linux ronin-HP-Laptop 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

1. install bun using script (page says 0.1.5(beta))
2. Add to bash

### How often does it reproduce? Is there a required condition?

Any bun command brings 'illegal instruction'

### What is the expected behavior?

A bun version is displayed 
e.g.

bun -v
0.1.5

### What do you see instead?

illegal instruction

### Additional information

The previous suggestion to fix this does not work and you closed my issue saying its 'fixed in 0.1.6'.

**Comment by R0N1n-dev** [comment] 2022-08-07 08:30
Have removed and installed bun 5 times now. And same thing.

**Comment by Brawl345** [comment] 2022-08-07 09:16
Have the same problem - it was indeed fixed in 0.1.6 but now it happens again on 0.1.7. Running on Arch in WSL: `Linux ... 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux`

And yes, I'm using the `baseline` one.

**Comment by xhyrom** [comment] 2022-08-07 09:17
Not duplicate of https://github.com/oven-sh/bun/issues/1011 but closing.

You can use *-baseline builds that doesn't requires AVX2 but its broken in 0.1.7 (check more info in issue)

**Closed as completed by xhyrom** 2022-08-07 09:17 UTC
Labels: bug, needs repro

**Comment by R0N1n-dev** [comment] 2022-08-07 09:31
Have tried baseline build. Same thing

**Comment by xhyrom** [comment] 2022-08-07 12:11
try canary baseline build, read issue #1011
