### ISSUE TITLE
Implement native monitoring documents | 实现原生的文件监控

### ISSUE THREAD

**Issue by vamsaya** [oven-sh/bun#10271] opened 2024-04-15 01:26 UTC
### What is the problem this feature would solve?

```js
import { watch } from "fs/promises";

for await (const event of watch('.', { recursive: true })) {
    console.log(event);
}
```
Nodejs's Watch function is not easy to use. Windows11 WSL2 When creating a file, the rename event will be triggered, and the content of the file is modified, but it cannot trigger the Change event. Is this the defect of design?

In addition, the creation and deletion files will trigger the rename event. Obviously it is not easy to determine what the file is currently in. I hope that the Bun team can native Watch API.

When creating a file, the Create event is triggered.

When modifying the file, trigger the change event.

When renamed, Rename was triggered.

When deleting files, the remove event is triggered.

nodejs的watch功能并不好用，当创建文件时会触发rename事件，然后修改这个文件内容，却不能触发change事件，这是设计的缺陷吗？

另外，创建和删除文件都会触发rename事件，显然不好确定文件当前处于什么状态，希望bun团队能原生实现watch api。
创建文件时，触发create事件。
修改文件时，触发change事件。
重命名时，触发rename。
删除文件时，触发remove事件。

### What is the feature you are proposing to solve the problem?

file watch

**Comment by Electroid** [comment] 2024-04-15 16:15
Duplicate of #5841

**Closed as not planned by Electroid** 2024-04-15 16:15 UTC
Labels: bug, node.js, needs repro
