### ISSUE TITLE
Workspaces -> Not being able to find workspace dependency

### ISSUE THREAD

**Issue by gfffrtt** [oven-sh/bun#10833] opened 2024-05-04 17:42 UTC
### What version of Bun is running?

v1.1.7

### What platform is your computer?

Linux 6.5.0-28-generic x86_64 x86_64

### What steps can reproduce the bug?

Step 1:

Create a turborepo monorepo:

```sh
bun create turbo workspaces-bug
```

Step 2:

Try installing

```
bun i
```

(This should work as expected)

Step 3:

Create a new folder called config, then add it to the package.json:

```sh
mkdir config
```

```json
"workspaces": [
    "config/*"
]
```

Step 4:

Move typescript-config and eslint-config in there, and remove apps, and packages from repo

```sh
mv packages/typescript-config config/
mv packages/eslint-config config/

rm -rf packages
rm -rf apps
```

Step 5:

Try to run bun install again, this should fail

### What is the expected behavior?

![image](https://github.com/oven-sh/bun/assets/153773731/1a0ee068-67d4-41b3-bf8a-d2faefd9328b)

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/153773731/58c6221f-9fa7-4db1-8a95-720253903a51)

**Comment by zackradisic** [comment] 2024-05-06 20:39
This is a duplicate of #5413, as a temporary fix deleting bun.lockb and running `bun i` again should fix this

**Closed as completed** 2024-05-08 21:46 UTC
Labels: bug
