### ISSUE TITLE
Unable to look up `cpu-features`

### ISSUE THREAD

**Issue by timbrinded** [oven-sh/bun#9633] opened 2024-03-26 11:51 UTC
### What version of Bun is running?

1.0.35+940448d6b

### What platform is your computer?

```sh
Darwin 23.3.0 arm64 arm
```

and

```sh
Linux 6.8.1-zen1-1-zen x86_64 unknown
```

### What steps can reproduce the bug?

Install and try to use the `cpu-features` package, which is a popular dep of some low level libraries.

---

Execute the following:
```sh
mkdir test-repro && cd test-repro
bun init --yes
bun add cpu-features
echo -e 'import features from "cpu-features"\n\nconsole.log("Hello via Bun!");\nconsole.log(features());' > index.ts
bun run ./index.ts
```

### What is the expected behavior?

> [!NOTE]  
> The following output has been done by executing the file via `tsx` instead of bun

```sh
Hello via Bun!
{
  arch: 'x86',
  brand: 'Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz',
  family: 6,
  model: 165,
  stepping: 5,
  uarch: 'INTEL_CML',
  flags: {
    fpu: true,
    tsc: true,
    cx8: true,
    clfsh: true,
    mmx: true,
    aes: true,
    erms: true,
    f16c: true,
    fma3: true,
    bmi1: true,
    bmi2: true,
    rdseed: true,
    clflushopt: true,
    sse: true,
    sse2: true,
    sse3: true,
    ssse3: true,
    sse4_1: true,
    sse4_2: true,
    avx: true,
    avx2: true,
    pclmulqdq: true,
    smx: true,
    sgx: true,
    cx16: true,
    popcnt: true,
    movbe: true,
    rdrnd: true,
    ss: true,
    adx: true,
    lzcnt: true
  }
}
```

### What do you see instead?

> [!CAUTION]  
> Symbol lookup error thrown

```sh
bun: symbol lookup error: /home/timbo/test-repro/node_modules/cpu-features/build/Release/cpufeatures.node: undefined symbol: node_module_register
```

### Additional information

Unrelated to ESM/CJS.
Not an issue with other runtimes it seems.

For Mac the error you get is:
```sh
dyld[5453]: missing symbol called
```

**Comment by timbrinded** [comment] 2024-04-02 20:12
This is still an issue in bun 1.1.0

**Comment by m-radmacher** [comment] 2024-04-04 12:24
I encountered a related issue while installing `testcontainers` (running Bun version `1.1.0+5903a6141`):

```
~/vezumonitoring# bun i testcontainers -D
[0.54ms] ".env"
bun add v1.1.0 (5903a614)
  ⚙️  cpu-features [1/2] /root/vezumonitoring/node_modules/buildcheck/lib/index.js:115
  throw new Error('Unable to detect compiler type');
  ^

Error: Unable to detect compiler type
    at BuildEnvironment.getKind (/root/vezumonitoring/node_modules/buildcheck/lib/index.js:115:9)
    at BuildEnvironment.tryCompile (/root/vezumonitoring/node_modules/buildcheck/lib/index.js:537:15)
    at BuildEnvironment.checkHeader (/root/vezumonitoring/node_modules/buildcheck/lib/index.js:423:25)
    at Object.<anonymous> (/root/vezumonitoring/node_modules/cpu-features/buildcheck.js:16:4)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.5.1

error: install script from "cpu-features" exited with 1
```

**Comment by micalevisk** [comment] 2024-04-05 15:51
here, `npm i cpu-features` breaks on Nodejs as well with the same error

but `npm i ssh2` went fine while `bun i ssh2` doesn't

and `ssh2` uses `buildcheck` on 'install'

**Comment by timbrinded** [comment] 2024-04-08 08:36
@micalevisk that isn't the case for me. Cpu-features works fine for both esm/cjs running with node.

---
For context:
What i actually care about is `testcontainers` which is a very important library for me (of which cpu-features is a core req).

**Comment by felipecrs** [comment] 2024-05-01 22:11
Same issue when trying to run [Renovate](https://github.com/renovatebot/renovate) with bun:

```console
❯ bun lib/renovate.ts
/home/vscode/.pkgx/bun.sh/v1.1.6/bin/bun: symbol lookup error: /workspaces/renovate/node_modules/re2/build/Release/re2.node: undefined symbol: node_module_register
```

**Comment by Jarred-Sumner** [comment] 2024-05-09 06:29
Duplicate of #4290

**Comment by Jarred-Sumner** [comment] 2024-05-09 06:29
Please follow along in #4290. It says "not planned" but we'll get it working

**Closed as not planned by Jarred-Sumner** 2024-05-09 06:29 UTC
Labels: bug
