### ISSUE TITLE
Bun crash when enable `pino-pretty`

### ISSUE THREAD

**Issue by joeynq** [oven-sh/bun#11401] opened 2024-05-27 16:14 UTC
### JavaScript/TypeScript code that reproduces the crash?

```ts
Bun.serve({
  websocket: {
    message: (ws, data) => {
      const sid = uuid();
      return asyncLocalStorage.run({ sid }, {
        try {
          throw new Error("it crash after caught this");
        } catch (err) {
          ws.publish(err.message);
        }
      });
    }
  }
});
```

### Relevant log output

```shell
Bun v1.1.10 (5102a944) Linux x64
Args: "bun" "src/index.ts"
Features: jsc Bun.stdin(2) bunfig dotenv(8) fetch http_server transpiler_cache(4) tsconfig(47)
Builtins: "bun:main" "bun:sqlite" "node:assert" "node:async_hooks" "node:buffer" "node:events" "node:fs" "node:module" "node:os" "node:path" "node:process" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:worker_threads"
Elapsed: 150928ms | User: 1480ms | Sys: 1398ms
RSS: 0.69GB | Peak: 0.35GB | Commit: 0.69GB | Faults: 0

panic: Segmentation fault at address 0x6EA0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.10/la15102a94AqqihgF280ujE+xyQksllBA2Agq3B

Illegal instruction
```

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00006EA0

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- `??`

**Comment by Electroid** [comment] 2024-05-27 16:19
Could you share some code to reproduce this issue? It looks like the stack trace doesn't give us enough information.

**Comment by joeynq** [comment] 2024-05-27 16:30
@Electroid I added example. I think the problem come from `AsyncLocalStorage`. When I remove als, it run without any crashes.

**Comment by joeynq** [comment] 2024-05-31 17:06
@Electroid I think I found the root cause. Turns out `pino-pretty` is the main problem.

The codes below only will throw `panic: Segmentation fault at address 0x6EA0`
```ts
const logger = pino({
  base: {},
    transport: {
      target: "pino-pretty", // disable this, the issue disappeared
      options: {
        crlf: true,
        translateTime: "SYS:HH:MM:ss.l",
        messageFormat: "{{traceId}} {msg}",
        ignore: "traceId,userIp,serverUrl,userAgent",
     },
  },
})
setInterval(() => {
  logger.info("Received message: %o", message);
}, 1000);
```

**Comment by sirenkovladd** [comment] 2024-05-31 18:19
```ts
import { pino } from "pino";

const logger = pino({
  base: {},
  transport: {
    target: "pino-pretty", // disable this, the issue disappeared
    options: {
      crlf: true,
      translateTime: "SYS:HH:MM:ss.l",
      messageFormat: "{{traceId}} {msg}",
      ignore: "traceId,userIp,serverUrl,userAgent",
    },
  },
});
setInterval(() => {
  logger.info({ traceId: 123, test: 1 }, "Received message: %o", {
    version: Bun.version,
    revision: Bun.revision,
  });
}, 1000);
```

```sh
❯ bun run index.ts
[11:18:02.025] INFO: {123} Received message: {"version":"1.1.10","revision":"4b8f89cb73ac2b38f1da6a28eb91861eb7222264"}
    test: 1
[11:18:03.014] INFO: {123} Received message: {"version":"1.1.10","revision":"4b8f89cb73ac2b38f1da6a28eb91861eb7222264"}
    test: 1
[11:18:04.020] INFO: {123} Received message: {"version":"1.1.10","revision":"4b8f89cb73ac2b38f1da6a28eb91861eb7222264"}
    test: 1
```

Please, can you add more details?

**Comment by joeynq** [comment] 2024-06-01 03:56
I'm running on:

- WSL2, Ubuntu 22 on Windows 11
- Bun 1.10

And that's code crash after less than 30 seconds after started. Sometimes it crash after second log. Just a very basic pino code as I posted. No more details.

**Comment by Codex-** [comment] 2024-08-24 11:58
Also encountering a similar crach with `pino-pretty` enabled: https://bun.report/1.1.26/wa10a37423AigghgC0q9lQq3ol3C__24xsyBA0eNo1zbEKwjAURuG9T/E7VUE7iK4uloIguFgXcUiaqwne5obcluLbi6LzgfPtjQ7YrjdXb6JjumG1Q1Mf+sRVe0FvnqToWDTEB0KfRDVYpllRnD1Bx5Q4UIbcMfigaAJTTdrlkAbJUC8jO3SGGaUdYzXIMdj2cpoiuaYuC8kof9qH+kdy5RIpizWWX5g8ZYIkivMFJqPfH7nqDZuaQLM

```
$ bun ./src/app.ts
============================================================
Bun v1.1.26 (0a37423b) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\x\.bun\bin\bun.exe" "./src/app.ts"
Features: jsc http_server(2) tsconfig(10) 
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:dns" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:os" "node:path" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:worker_threads" "node:diagnostics_channel" 
Elapsed: 256ms | User: 156ms | Sys: 15ms
RSS: 0.23GB | Peak: 0.23GB | Commit: 0.32GB | Faults: 56054

panic(thread 41904): Cast 524[handle] -> FDImpl.UV makes closing impossible!

The supplier of this FileDescriptor should call 'bun.toLibUVOwnedFD'
or 'FDImpl.makeLibUVOwned', probably where open() was called.
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

```ts
import Fastify from "fastify";

const fastify = Fastify({
  logger: {
    transport: {
      target: "pino-pretty",
      options: {
        translateTime: "HH:MM:ss Z",
        ignore: "pid,hostname",
      },
    },
  },
});
try {
  await fastify.listen({ port: 3000 });
} catch (err) {
  fastify.log.error(err);
  process.exit(1);
}
```

```json
"dependencies": {
  "fastify": "^4.28.1",
  "pino": "^9.3.2",
  "pino-pretty": "^11.2.2"
}
```

**Comment by Jarred-Sumner** [comment] 2024-09-03 08:21
@Codex- we are tracking that in https://github.com/oven-sh/bun/issues/13653

**Comment by Jarred-Sumner** [comment] 2024-09-03 08:22
Duplicate of https://github.com/oven-sh/bun/issues/13653

**Comment by Jarred-Sumner** [comment] 2024-09-03 08:22
Tracking this in https://github.com/oven-sh/bun/issues/13653, please follow along in https://github.com/oven-sh/bun/issues/13653

**Closed as completed by Jarred-Sumner** 2024-09-03 08:22 UTC
Labels: crash
