### ISSUE TITLE
Bun crash

### ISSUE THREAD

**Issue by jnjambrin0** [oven-sh/bun#13604] opened 2024-08-29 11:23 UTC
### How can we reproduce the crash?

I was running my Next.js app with 'bun run dev' just after configuring my middleware. The code of the middleware is: 

'''
import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";

const isPublicRoute = createRouteMatcher(["/sign-in(.*)", "/sign-up(.*)"]);

export default clerkMiddleware((auth, request) => {
  if (!isPublicRoute(request)) {
    auth().protect();
  }
});

export const config = {
  matcher: [
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    "/(api|trpc)(.*)",
  ],
};
'''

### Relevant log output

```shell
Starting...
 ✓ Ready in 8.5s
 ○ Compiling /middleware ...
 ✓ Compiled /middleware in 3.2s (179 modules)
============================================================
Bun v1.1.26 (0a37423b) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2 avx512
Args: "C:\Users\02jnj\AppData\Local\Temp\bun-node-0a37423ba\node.exe" "C:\Users\02jnj\Desktop\Projects\Fluxion\node_modules\next\dist\server\lib\start-server.js"
Features: jsc Bun.stdin dotenv fetch(3) http_server spawn(2) transpiler_cache(22) tsconfig_paths(4) tsconfig(4) 
Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns/promises" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:stream" "node:stream/web" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8" "node:diagnostics_channel" 
Elapsed: 16948ms | User: 1328ms | Sys: 359ms
RSS: 0.94GB | Peak: 0.94GB | Commit: 18.57GB | Faults: 250019

panic(main thread): Segmentation fault at address 0x2A15ECCDC30
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x27C0C989810

- [`HashTable.h:302`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/C:/buildkite-agent/builds/windows-x64-hetzner-6/bun/bun/build/bun-webkit/include/wtf/HashTable.h#L302>): `WTF::IdentityHashTranslator<WTF::HashMap<const JSC::ClassInfo *,JSC::WriteBarrier<JSC::Structure,WTF::RawPtrTraits<JSC::Structure> >,WTF::DefaultHash<const JSC::ClassInfo *>,WTF::HashTraits<const JSC::ClassInfo *>,WTF::HashTraits<JSC::WriteBarrier<JSC::Structure,WTF::RawPtrTraits<JSC::Structure> > >,WTF::HashTableTraits>::KeyValuePairTraits,WTF::DefaultHash<const JSC::ClassInfo *> >::equal`
- *2 unknown/js code*
- `llint_entry`

**Comment by rustynail1984** [comment] 2024-09-01 00:45
got the same issue on Linux Debian 12.

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:18
Duplicate of https://github.com/oven-sh/bun/issues/13629

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:19
Please follow along in https://github.com/oven-sh/bun/issues/13629. It will get fixed.

**Closed as completed by Jarred-Sumner** 2024-09-01 04:19 UTC
Labels: crash, windows
