### ISSUE TITLE
Windows CWD: POSIX path

### ISSUE THREAD

**Issue by frobinsonj** [oven-sh/bun#12914] opened 2024-07-29 10:26 UTC
### How can we reproduce the crash?

```js
import { chdir } from 'node:process';
chdir("/test");
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on windows x86_64 [RunAsNodeCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '/test\'. Please open an issue on GitHub with a reproduction.

- [`string_immutable.zig:814`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/string_immutable.zig#L814>): `eqlComptimeCheckLenU8`
- [`windows.zig:3251`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/windows.zig#L3251>): `Bun__UVSignalHandle__close`
- [`server.zig:1638`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/api/server.zig#L1638>): `handleReject`
- [`bindings.zig:6070`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/bindings/bindings.zig#L6070>): `arguments`
- [`SmallStrings.h:70`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/C:/a/bun/bun/build/bun-webkit/include/JavaScriptCore/SmallStrings.h#L70>): `JSC::SmallStrings::singleCharacterString`
- *2 unknown/js code*
- `llint_entry`

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:57
Duplicate of https://github.com/oven-sh/bun/issues/11215

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:57
Please follow along in https://github.com/oven-sh/bun/issues/10830

**Closed as not planned by Jarred-Sumner** 2024-08-06 07:57 UTC
Labels: crash, windows
