### ISSUE TITLE
toThrow is overly strict with error types

### ISSUE THREAD

**Issue by LandonSchropp** [oven-sh/bun#8243] opened 2024-01-18 03:47 UTC
### What version of Bun is running?

1.0.18+36c316a24

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

``` ts
import { test, expect } from "bun:test";

export class ExampleError extends Error {
  constructor(message?: string | undefined) {
    super(message);
    this.name = this.constructor.name;
  }
}

test("throws an error", () => {
  expect(() => {
    throw new ExampleError();
  }).toThrow(ExampleError);
});
```

### What is the expected behavior?

The `toThrow` matcher should assert that the error was thrown.

### What do you see instead?

I get the following TypeScript error

```
typescript: Argument of type 'typeof ExampleError' is not assignable to parameter of type 'string | RegExp | ErrorConstructor | Error | │
 undefined'.                                                                                                                           │
 Type 'typeof ExampleError' is not assignable to type 'ErrorConstructor'.                                                              │   Type 'typeof ExampleError' provides no match for the signature '(message?: string | undefined): Error'. [2345]
 ```

**Comment by wojtekmaj** [comment] 2024-01-19 10:38
Potential duplicate of #6934

**Comment by jdalton** [comment] 2024-01-22 19:16
Dup of https://github.com/oven-sh/bun/issues/6934

**Closed as completed by jdalton** 2024-01-22 19:16 UTC
Labels: bug, types
