### ISSUE TITLE
Crash during install

### ISSUE THREAD

**Issue by sockmaster27** [oven-sh/bun#11710] opened 2024-06-08 19:49 UTC
### How can we reproduce the crash?

Only happened one time, but what I did was
- Cloned [knip](https://github.com/webpro-nl/knip).
- Bumped the patch version of a dependency in `packages/knip/package.json`.
- Installed Bun for Windows via the recommended `powershell -c "irm bun.sh/install.ps1 | iex"` in the VS Code terminal.
- Restarted VS Code.
- Ran `bun install`.

Rerunning `bun install` worked though.

### Relevant log output

```shell
bun install v1.1.12 (43f0913c)
  📦 Installing [903/1174] ============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\Holger\.bun\bin\bun.exe" "install"
Features: extracted_packages(923) 
Elapsed: 30776ms | User: 4328ms | Sys: 32265ms
RSS: 0.65GB | Peak: 0.65GB | Commit: 0.98GB | Faults: 279045
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:5156`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5156>): `processDependencyListItem`
- [`logger.zig:850`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/logger.zig#L850>): `allocPrint`
- [`install.zig:5937`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5937>): `runTasks`
- [`install.zig:10031`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L10031>): `installPackageWithNameAndResolution`
- [`event_loop.zig:1875`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/event_loop.zig#L1875>): `tick`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1450`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1450>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/main.zig#L51>): `main`
- [`cell.rs:769`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cell.rs#L769>): `core::cell::panic_already_borrowed`

**Comment by Jarred-Sumner** [comment] 2024-06-09 05:19
Duplicate of #10565

**Comment by Jarred-Sumner** [comment] 2024-06-09 05:19
We are tracking this in https://github.com/oven-sh/bun/issues/10565, it will get fixed but please follow along there.

**Closed as not planned by Jarred-Sumner** 2024-06-09 05:19 UTC
Labels: bun install
