### ISSUE TITLE
InstructionError at 41970069 on manjaro

### ISSUE THREAD

**Issue by sheyzi** [oven-sh/bun#461] opened 2022-07-08 23:37 UTC
Whenever I run any bun command on Manjaro it keeps throwing an `InstructionError at 41970069`

When i run `bun create react ./app`
```
Fetching package.json... 
InstructionError at 41970069


–––– bun meta ––––
Bun v0.1.2 Linux x64 #1 SMP PREEMPT Wed May 18 09:20:01 UTC 2022
CreateCommand: 
HTTP: 1
Elapsed: 58ms | User: 44ms | Sys: 9ms
RSS: 69.21MB | Peak: 10.72MB | Commit: 69.21MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

When i run `bun install` on an existing app

```
bun install v0.1.2
  🔍 Resolving [1/17] 
InstructionError at 41970069


–––– bun meta ––––
Bun v0.1.2 Linux x64 #1 SMP PREEMPT Wed May 18 09:20:01 UTC 2022
InstallCommand: 
HTTP: 17
Elapsed: 325ms | User: 310ms | Sys: 73ms
RSS: 71.31MB | Peak: 30.91MB | Commit: 71.31MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

When i run `bun dev`
```
[19.00ms] bun!! v0.1.2


  Link: http://localhost:3000



InstructionError at 41970069


–––– bun meta ––––
Bun v0.1.2 Linux x64 #1 SMP PREEMPT Wed May 18 09:20:01 UTC 2022
DevCommand: public_folder 
HTTP: 1
Elapsed: 2008ms | User: 186ms | Sys: 96ms
RSS: 71.32MB | Peak: 13.07MB | Commit: 71.32MB | Faults: 0
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by FinnRG** [comment] 2022-07-08 23:56
@sheyzi  Duplicate of #197. Please post your message there.

**Closed as completed** 2022-07-09 00:21 UTC
