### ISSUE TITLE
Bun v1.1.12: does not allocate SWAP, Uses memory till panic

### ISSUE THREAD

**Issue by Yonle** [oven-sh/bun#11531] opened 2024-06-02 05:38 UTC
### How can we reproduce the crash?

Do whatever it takes that will allocate memory till it runs out

### Expected behavior
If memory almost runs out, It should take SWAP

### Actual behavior
It took memory till it runs out and panic.

### Relevant log output

```shell
pure virtual method called
============================================================
Bun v1.1.12 (43f0913c) Linux x64
Args: "bun" "run" "http.js"
Features: jsc abort_signal(18) http_server transpiler_cache WebSocket(4022)
Builtins: "bun:main" "node:buffer" "node:crypto" "node:fs" "node:http" "node:querystring" "node:string_decoder" "node:
util/types" "node:worker_threads" "undici" "ws" "node:http2"
Elapsed: 378315ms | User: 56329ms | Sys: 16147ms
RSS: 0.02ZB | Peak: 0.46GB | Commit: 0.02ZB | Faults: 1

panic(main thread): A C++ exception occurred
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.12/......

Illegal instruction (core dumped)
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64 [RunCommand]

**panic**: A C++ exception occurred

- [`string.zig:657`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/string.zig#L657>): `DirentPrototype__getName`
- `??`
- [`SentinelLinkedList.h:60`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/wtf/SentinelLinkedList.h#L60>): `WebCore::MessageEvent::create`
- [`MessageEvent.cpp:105`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/webcore/MessageEvent.cpp#L105>): `WebCore::MessageEvent::create`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::JSDestructibleObjectHeapCellType::finishSweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::MarkedBlock::Handle::sweep`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::MachineThreads::gatherConservativeRoots`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::LocalAllocator::tryAllocateIn`
- [`tuple:127`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/tuple#L127>): `WebCore::JSErrorEvent::create`
- [`RefPtr.h:71`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/wtf/RefPtr.h#L71>): `WebCore::identifierToByteString`

**Comment by Yonle** [comment] 2024-06-02 06:18
Looks like Bun does not try to allocate memory in SWAP.

**Comment by Jarred-Sumner** [comment] 2024-06-04 07:51
`Worker` in Bun is not stable yet. This is a duplicate of https://github.com/oven-sh/bun/issues/7338

**Comment by Jarred-Sumner** [comment] 2024-06-04 07:52
Duplicate of https://github.com/oven-sh/bun/issues/7338

**Closed as not planned** 2024-06-04 07:52 UTC
Labels: crash
