### ISSUE TITLE
better-sqlite3 error: symbol lookup error

### ISSUE THREAD

**Issue by gustavocadev** [oven-sh/bun#7819] opened 2023-12-25 00:52 UTC
### What version of Bun is running?

1.0.20+09d51486e

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Repo: https://github.com/gustavocadev/clean-architecture-bun-2

Install deps
```bash
bun i
```

Execute main file
```bash
bun run ./src/main.ts
```

### What is the expected behavior?

I expect that Bun can run the file well

### What do you see instead?

bun: symbol lookup error: /home/gustavocadev/documents/clean-architecture-deno/node_modules/better-sqlite3/build/Release/better_sqlite3.node: undefined symbol: node_module_register

![image](https://github.com/oven-sh/bun/assets/84424661/cd4bd303-106d-4344-9870-60a67346268b)

**Comment by Electroid** [comment] 2023-12-25 04:59
Duplicate of #4290

**Closed as not planned by Electroid** 2023-12-25 04:59 UTC
Labels: bug

**Comment by gustavocadev** [comment] 2023-12-25 14:44
> Duplicate of #4290

Ok, thx didnt notice
