### ISSUE TITLE
Bun crash using nextjs and turborepo

### ISSUE THREAD

**Issue by darklight9811** [oven-sh/bun#13240] opened 2024-08-12 00:45 UTC
### How can we reproduce the crash?

Repository: https://github.com/darklight9811/sharedway

Just started the web server using `bun --bun next dev`

### Relevant log output

```shell
PS C:\projects\javascript\yamiassu\company\sharedway> bun dev --filter=app      
$ dotenv -- turbo dev --filter=app
turbo 2.0.12

 WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available: could not resolve workspaces
• Packages in scope: app
• Running dev in 1 packages
• Remote caching disabled
app:dev: cache bypass, force executing 2330ac6cebae20b1
app:dev: yarn run v1.22.22
app:dev: $ bun --bun next dev
app:dev:   ▲ Next.js 14.2.5
app:dev:   - Local:        http://localhost:3000
app:dev: 
app:dev:  ✓ Starting...
app:dev:  ✓ Ready in 9.8s
app:dev:  ○ Compiling /src/middleware ...
app:dev:  ✓ Compiled /src/middleware in 4s (199 modules)
app:dev: ============================================================
app:dev: Bun Canary v1.1.23-canary.28 (7d018fb3) Windows x64
app:dev: Windows v.win10_fe
app:dev: CPU: sse42 avx avx2
app:dev: Args: "C:\Users\rafae\AppData\Local\Temp\bun-node-7d018fb32\node.exe" "C:\projects\javascript\yamiassu\company\sharedway\node_modules\next\dist\server\lib\start-server.js" 
app:dev: Features: jsc Bun.stdin fetch(3) http_server spawn(2) transpiler_cache(7) tsconfig_paths(2) tsconfig(9)
app:dev: Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns/promises" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:stream" "node:stream/web" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8" "node:diagnostics_channel"
app:dev: Elapsed: 499552ms | User: 8750ms | Sys: 6625ms
app:dev: RSS: 1.08GB | Peak: 1.08GB | Commit: 18.94GB | Faults: 373180
app:dev:
app:dev: panic(main thread): Segmentation fault at address 0x100000012
app:dev: oh no: Bun has crashed. This indicates a bug in Bun, not your code.
app:dev:
app:dev: To send a redacted crash report to Bun's team,
app:dev: please file a GitHub issue using the link below:
app:dev:
app:dev:  https://bun.report/1.1.23/wn27d018fbAqgih0D47123C__+o/hyBA2CkB
app:dev:
app:dev:
app:dev: Done in 501.13s.
```

### Stack Trace (bun.report)

Bun v1.1.23 ([`7d018fb`](<https://github.com/oven-sh/bun/tree/7d018fb323ec13118368df8e9773d7604efec65a>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x100000012

- [`HashTable.h:595`](<https://github.com/oven-sh/bun/blob/7d018fb323ec13118368df8e9773d7604efec65a/C:/buildkite-agent/builds/windows-x64-hetzner-2/bun/bun/build/bun-webkit/include/wtf/HashTable.h#L595>): `WTF::HashTable<const JSC::ClassInfo *,WTF::KeyValuePair<const JSC::ClassInfo *,JSC::WriteBarrier<JSC::Structure,WTF::RawPtrTraits<JSC::Structure> > >,WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<const JSC::ClassInfo *,JSC::WriteBarrier<JSC::Structure,WTF::RawPtrTraits<JSC::Structure> > > >,WTF::DefaultHash<const JSC::ClassInfo *>,WTF::HashMap<const JSC::ClassInfo *,JSC::WriteBarrier<JSC::Structure,WTF::RawPtrTraits<JSC::Structure> >,WTF::DefaultHash<const JSC::ClassInfo *>,WTF::HashTraits<const JSC::ClassInfo *>,WTF::HashTraits<JSC::WriteBarrier<JSC::Structure,WTF::RawPtrTraits<JSC::Structure> > >,WTF::HashTableTraits>::KeyValuePairTraits,WTF::HashTraits<const JSC::ClassInfo *> >::tableSizeMask`
- *2 unknown/js code*
- `llint_entry`

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:20
Duplicate of https://github.com/oven-sh/bun/issues/13629

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:21
Please follow along in https://github.com/oven-sh/bun/issues/13629. It will get fixed

**Closed as completed by Jarred-Sumner** 2024-09-01 04:21 UTC
Labels: crash, windows
