### ISSUE TITLE
TypeError: Not a string or buffer (while gunzipping a HTTP Response)

### ISSUE THREAD

**Issue by K-Mistele** [oven-sh/bun#6963] opened 2023-11-07 15:56 UTC
### What version of Bun is running?

1.0.10+d85bd49d8

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

I wrote a simple recursive algorithm that involves RPC calls to a quicknode RPC URL: 
https://gist.github.com/K-Mistele/9d592f4d630c87c8a78b2a69aff06e58

Run the script with `bun run index.ts` 3-6 times to get the bug to happen - it only happens part of the time. 

### What is the expected behavior?

I expect that the code would run like normal instead of throwing an error

### What do you see instead?

I see the following error: 
```
2274 |           buf = Buffer2.concat(buffers, nread);
2275 |         buffers = [], engine.close(), callback(err, buf);
2276 |       }
2277 |     }
2278 | 
2279 |     function zlibBufferSync(engine, buffer) {
                                                         ^
TypeError: Not a string or buffer
      at zlibBufferSync (node:zlib:2279:54)
      at /Users/kyle/Documents/Work/Projects/Scratch/get-native-coin-balances/node_modules/ethers/lib.esm/utils/geturl.js:71:40
      at endReadableNT (node:stream:2387:52)
      at processTicksAndRejections (:61:76)
```

### Additional information

I followed the stack trace and found that it is this code from ethers.js library that is responsible for gunzipping gzipped HTTP responses from RPC Providers (this line in the stack trace: `at /Users/kyle/Documents/Work/Projects/Scratch/get-native-coin-balances/node_modules/ethers/lib.esm/utils/geturl.js:71:40`):

```javascript
resp.on("end", () => {
                    if (headers["content-encoding"] === "gzip" && body) {
                        body = getBytes(gunzipSync(body));
                    }
                    resolve({ statusCode, statusMessage, headers, body });
                });
```
(error comes from `getBytes(gunzipSync(body))`) 

I have confirmed that this is NOT an issue with malformed or poorly-gzipped responses by compiling the code to Node.js (using `tsc` and running it with the `node` binary) - the error only happens when I am running the code with bun. I have tested this exhaustively - the error doesn't happen every time, but it only happens when running with `bun` - not with `node`

**Comment by Electroid** [comment] 2023-11-07 17:29
Duplicate of #5309

**Closed as not planned by Electroid** 2023-11-07 17:29 UTC
Labels: bug, node.js
