### ISSUE TITLE
No result when running prisma generate with bun

### ISSUE THREAD

**Issue by eslym** [oven-sh/bun#9508] opened 2024-03-19 08:03 UTC
### What version of Bun is running?

1.0.33+9e91e137f

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

1. create a project
2. install prisma and configure prisma to use postgresql (other db not tested)
3. run prisma generate with `--bun`

### What is the expected behavior?

prisma successfully generate type files

### What do you see instead?

```
$ bunx --bun prisma generate
$
```
no error message, exit code 0, the files supposed to generate is not generated.

### Additional information

this problem also present in v1.0.32 and happens on arm64

**Comment by Electroid** [comment] 2024-03-19 15:52
Duplicate of #3827

**Closed as not planned by Electroid** 2024-03-19 15:52 UTC
Labels: bug
