### ISSUE TITLE
Multer File Upload Hangs Forever When Using Sessions

### ISSUE THREAD

**Issue by airamstudio** [oven-sh/bun#8225] opened 2024-01-17 05:59 UTC
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

1. Set up an Express application with Bun.js
2. Integrate sessions using express-session with connect-redis as a Redis storage
3. Use Multer for handling file uploads
4. Create an endpoint for posting multipart form data
5. Start a session before making a request to the endpoint with file upload

`Route.post("/upload", multer().any(), (req,res)=>{
//...
})`

### What is the expected behavior?

Multer should successfully handle file uploads even when sessions are active, and the request should not hang indefinitely.

### What do you see instead?

When sessions are started, Multer fails to handle file uploads, and the request remains in a loading state indefinitely. When I remove the session cookie, it works again. 

### Additional information

connect-redis version 7.1.0
express version  4.18.2
express-session version 1.17.3
multer 1.4.5-lts.1
redis version 4.6.12

After running with node, no isues arise.

**Comment by Electroid** [comment] 2024-01-17 06:19
Duplicate of #2026

**Closed as not planned by Electroid** 2024-01-17 06:19 UTC
Labels: bug
