### ISSUE TITLE
test.each does not interpolate test case variables

### ISSUE THREAD

**Issue by supermacro** [oven-sh/bun#6990] opened 2023-11-08 18:09 UTC
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 6.5.6-76060506-generic x86_64 x86_64

### What steps can reproduce the bug?

Create a test suite that uses `it.each`:

```typescript
import { describe, it, expect } from 'bun:test'

const extractAsinFromURL = (a: URL) => ''

describe('Shared utils', () => {
  it.each([
    { url: 'https://www.amazon.com/gp/aw/d/B0753KDX7X/', expected: 'B0753KDX7X' },
    { url: 'https://www.amazon.com/gp/aw/B0753KDX7X/', expected: 'B0753KDX7X' },
    { url: 'https://www.amazon.com/crocs-Unisex-Classic-Black-Women/dp/B0014BYHGC/ref=sr_1_2', expected: 'B0014BYHGC' },
    { url: 'https://www.amazon.com/Columbia-Womens-Maiden-Snow-Black/dp/B00GW97YXE/ref=cm_cr_arp_d_product_top?ie=UTF8', expected: 'B00GW97YXE' },
  ])('Extract from $url', ({ url, expected }) => {
    const asin = extractAsinFromURL(new URL(url))

    expect(asin).toBe(expected)
  })
})
```

### What is the expected behavior?

Shell output should be:

```
✗ Shared utils > Extract from https://www.amazon.com/gp/aw/d/B0753KDX7X/', expected: 'B0753KDX7X [0.32ms]
✓ Shared utils > Extract from https://www.amazon.com/gp/aw/B0753KDX7X/ [0.02ms]
✓ Shared utils > Extract from https://www.amazon.com/crocs-Unisex-Classic-Black-Women/dp/B0014BYHGC/ref=sr_1_2
✓ Shared utils > Extract from https://www.amazon.com/Columbia-Womens-Maiden-Snow-Black/dp/B00GW97YXE/ref=cm_cr_arp_d_product_top?ie=UTF8

 3 pass
 1 fail
```

### What do you see instead?

Shell output was:

```✗ Shared utils > Extract from $url [0.32ms]
✓ Shared utils > Extract from $url [0.02ms]
✓ Shared utils > Extract from $url
✓ Shared utils > Extract from $url

 3 pass
 1 fail```

### Additional information

_No response_

**Comment by Electroid** [comment] 2023-11-08 18:10
Duplicate of #6306

**Closed as not planned by Electroid** 2023-11-08 18:10 UTC
Labels: bug, bun:test
