### ISSUE TITLE
Memory Leak with Blob/ArrayBuffer and Bun's Garbage Collection

### ISSUE THREAD

**Issue by ReD-GuardiaN** [oven-sh/bun#12941] opened 2024-07-30 09:46 UTC
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64
Same happens on Linux

### What steps can reproduce the bug?

1. Create an array of URLs to fetch videos.
2. Fetch the videos as Blob or ArrayBuffer and store them in an array.
3. Clear the array and invoke Bun.gc(true) to trigger garbage collection.
4. Observe that the memory is not released.

Here's a simplified code snippet to reproduce the issue:
```ts
const urls: string[] = [...Array(400)].map(() => `https://www.w3schools.com/html/mov_bbb.mp4`)

let blobs: (Blob | ArrayBuffer)[] = []

let i = 1

for (const u of urls) {
  await fetch(u, { cache: 'force-cache' })
    .then((x) => x.blob())
    // .then((x) => x.arrayBuffer())
  .then((x) => blobs.push(x))
  const rssInMB = process.memoryUsage().rss / 1024 / 1024
  console.log(`fetched ${i++}, memory usage: ${rssInMB.toFixed()}mb`)
}

setTimeout(() => {
  blobs = []
  global.gc?.()
  Bun.gc(true)
  const rssInMB = process.memoryUsage().rss / 1024 / 1024
  console.log(`cleared, memory usage: ${rssInMB.toFixed()}mb`)
}, 20000)

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

await sleep(1000 * 60 * 60 * 5)

```

### What is the expected behavior?

Memory should be released after invoking `Bun.gc(true)`.

### What do you see instead?

Memory is not released after invoking `Bun.gc(true)`.

### Additional information

I tested the same logic with Node.js, and garbage collection works as expected. To test with Node.js, I commented out the Bun.gc line, uncommented global.gc, built the script with bun build ./index.ts --outfile=index.js, and ran it with node --expose-gc ./index.js. In Node.js, the memory is correctly released after garbage collection.
![image](https://github.com/user-attachments/assets/486737d2-4f0b-42a3-9c14-b7029bd61f44)
![image](https://github.com/user-attachments/assets/b77c42a5-b8ed-4d9e-8e66-a6c0d3539c1c)

**Comment by ReD-GuardiaN** [comment] 2024-07-30 10:21
Same bug happens when using a local blob/arrayBuffer
tested with `Bun.file(u).arrayBuffer()`

**Comment by TiBianMod** [comment] 2024-07-30 11:01
also `Bun.file(u).text()` has a high memory usage.

**Comment by Jarred-Sumner** [comment] 2024-07-30 11:29
Note that in Bun we have not implemented support for the web cache api, so cache: “force-cache” doesn’t do anything 

that being said, it should still be collected here since the URLs array is empty and there are no other references to it.

**Comment by tth05** [comment] 2024-08-03 02:08
I have noticed similar behavior when rendering long videos using remotion. I wanted to try out Bun for this, but the process crashes quite quickly because the memory usage spikes out of control.

Looking at the heap snapshot generated in the Bun web debugger I could see a lot of ArrayBuffers hanging around...

**Comment by Jarred-Sumner** [comment] 2024-08-03 05:47
With `.arrayBuffer()`, memory usage between Bun and Node are basically the same. The issue is the array holding on to the body value for too long. I don't like this answer, but it does feel like a memory leak in the code snippet rather than in the engine or runtime.

if you can come up with a code snippet where Bun is using much more memory than Node, we're happy to investigate. For now, I'm closing as won't fix.

left: node v22.4.1
right: bun

<img width="782" alt="image" src="https://github.com/user-attachments/assets/20c78c42-94d1-4670-ab3b-116f3bb2a6e2">

`blob()` is similar:
<img width="912" alt="image" src="https://github.com/user-attachments/assets/9e132caf-bd7b-41d6-bc99-6af57b1afd2f">


```ts
const urls = [...Array(400)].map(
  () => `https://www.w3schools.com/html/mov_bbb.mp4`
);
async function main() {
  await (async function wrap() {
    let blobs = [];

    let i = 1;

    for (const u of urls) {
      blobs.push(
        await fetch(u, { cache: "force-cache" }).then((x) => x.blob())
      );
      const rssInMB = process.memoryUsage().rss / 1024 / 1024;
      console.log(`fetched ${i++}, memory usage: ${rssInMB.toFixed()}mb`);
    }
    blobs = [];
  })();
  setTimeout(() => {
    global.gc?.();
    Bun.gc(true);
    const rssInMB = process.memoryUsage().rss / 1024 / 1024;
    console.log(`cleared, memory usage: ${rssInMB.toFixed()}mb`);
    if (process.versions.bun) console.log(require("bun:jsc").heapStats());
  }, 1000);

  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  await sleep(1000 * 60 * 60 * 5);
}
globalThis.Bun ??= {
  gc() {},
};
main();
```

**Closed as not planned by Jarred-Sumner** 2024-08-03 05:47 UTC
Labels: bug, needs triage

**Comment by tth05** [comment] 2024-08-03 17:08
@Jarred-Sumner I've gone ahead and created an example project https://github.com/tth05/remotion-bun-memory-usage. Because my use case where I've noticed this issue is remotion, the example project uses that, making it not very minimal, but it should be enough to at least verify the existence of the issue. Hopefully it helps. 

Sadly, I'm not experienced enough to dig further into this nor do I have proper WebKit analysis tools easily available on Windows. All I could, as I mentioned before, is ArrayBuffers hanging around.
