### ISSUE TITLE
Uploading file to AWS s3, Bun is slower than Node

### ISSUE THREAD

**Issue by stan023** [oven-sh/bun#11128] opened 2024-05-16 21:01 UTC
### What version of Bun is running?

1.1.8

### What platform is your computer?

Linux 6.5.0-28-generic x86_64 x86_64

### What steps can reproduce the bug?

Run the following script:
```
import { PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import * as fs from 'fs';
import * as path from 'path';
const config = {
  key: "",
  secret: '',
  bucket: "",
  endpoint: "",
}

const s3Client = new S3Client({
  endpoint: config.endpoint,
  region: "auto",
  credentials: {
    accessKeyId: config.key,
    secretAccessKey: config.secret,
  }
});
let bucketName = config.bucket

async function uploadFile(filePath) {
  const fileName = path.basename(filePath);
  const startTime = new Date().getTime();
  const fileContent = fs.readFileSync(filePath);

  const params = {
    Bucket: bucketName,
    Key: fileName,
    Body: fileContent
  };

  try {
    await s3Client.send(new PutObjectCommand(params));
    const elapsedTime = new Date().getTime() - startTime;
    console.log(`Successfully uploaded ${fileName} to ${bucketName} in ${elapsedTime} ms`);
  } catch (err) {
    console.error(`Failed to upload file: ${err}`);
  }
}

uploadFile('./test.jpg');
```

### What is the expected behavior?

Uploading speed  should be same  with Node.

**Comment by Electroid** [comment] 2024-05-16 22:21
Duplicate of #7428

**Closed as not planned by Electroid** 2024-05-16 22:21 UTC
Labels: bug
