### ISSUE TITLE
bun doesn't handle dynamic network imports as expected - prints the script for Data URL, cannot find package Blob URL

### ISSUE THREAD

**Issue by guest271314** [oven-sh/bun#8183] opened 2024-01-15 18:06 UTC
### What version of Bun is running?

1.0.22

### What platform is your computer?

x64

### What steps can reproduce the bug?

Try to use dynamic `import()` with remote (HTTPS) URL, Blob URL, or Data URL. 

### What is the expected behavior?

The Ecmascript Module to be imported.

### What do you see instead?

For Data URL the Data URL and URL are printed to `console`; for Blob URL the error `Cannot find package "undefined" from...` is thrown.

### Additional information

Looks like no two (2) JavaScript runtimes implement dynamic `import()` the same 

```
const url =
  "https://gist.githubusercontent.com/guest271314/08b19ba88c98a465dd09bcd8a04606f6/raw/aac580355cfe4b4a0d6e20a493fca028dfe62dbb/buffer.js";

console.log(navigator.userAgent);

if (navigator.userAgent.includes("Bun")) {
  {
    try {
      const text = await (await fetch(url)).text();
      const dataURL = `data:text/javascript;base64,${btoa(text)}`;
      const { Buffer } = await import(dataURL);
      console.log(Buffer.from([0]));
    } catch (e) {
      console.log(e);
    }
  }
  {
    const ab = new Blob([
      await (await fetch(url)).arrayBuffer(),
    ], {
      type: "text/javascript",
    });
    try {
      const { Buffer } = await import(URL.createObjectURL(ab));
      console.log(Buffer.from([0]));
    } catch (e) {
      console.log(e);
    }
  }
}

if (navigator.userAgent.includes("txiki.js")) {
  try {
    const { Buffer } = await import(url);
    console.log(Buffer.from([0]));
  } catch (e) {
    console.log(e);
  }
}

if (navigator.userAgent.includes("quickjs-ng")) {
  try {
    const { Buffer } = await import("../buffer/buffer.js");
    console.log(JSON.stringify([...Buffer.from([0])]));
  } catch (e) {
    console.log(e);
  }
}

if (navigator.userAgent.includes("Deno")) {
  const ab = new Blob([
    await (await fetch(url)).arrayBuffer(),
  ], {
    type: "text/javascript",
  });
  try {
    const { Buffer } = await import(URL.createObjectURL(ab));
  } catch (e) {
    console.log(e);
  }
}

if (navigator.userAgent.includes("Node")) {
  try {
    const text = await (await fetch(url)).text();
    const dataURL = `data:text/javascript;base64,${btoa(text)}`;
    const { Buffer } = await import(dataURL);
    console.log(Buffer.from([0]));
  } catch (e) {
    console.log(e);
  }
}
```

- https://github.com/oven-sh/bun/discussions/8173
- https://gist.github.com/guest271314/08b19ba88c98a465dd09bcd8a04606f6

**Comment by Electroid** [comment] 2024-01-15 19:28
Duplicate of #38

**Closed as not planned by Electroid** 2024-01-15 19:28 UTC
Labels: bug

**Comment by guest271314** [comment] 2024-01-15 20:52
@Electroid What's the "not planned" label for?

**Comment by Electroid** [comment] 2024-01-15 20:53
> @Electroid What's the "not planned" label for?

Disregard that, Github labels duplicate issues as "not planned". This is planned.
