### ISSUE TITLE
Polyfill process.stdin and process.stdout

### ISSUE THREAD

**Issue by franciscop** [oven-sh/bun#952] opened 2022-08-02 00:15 UTC
### What is the problem this feature will solve?

Allow for people to use `process.stdin` and `process.stdout` as expected. Allow those to work with libraries that require them. In my specific case, allow `spinnies` to work `spinnies` => `readline` => `process.stdin/out`.

This is a follow-up/prework needed to fix https://github.com/oven-sh/bun/issues/311

### What is the feature you are proposing to solve the problem?

Polyfill `Bun.stdin` and `Bun.stdout` into `process.stdin` and `process.stdout`

### What alternatives have you considered?

Create the polyfill myself, however I'm [stuck here](https://github.com/oven-sh/bun/issues/311#issuecomment-1186720781):

```js
console.log(Bun.stdin.stream(), Bun.stdout.stream());
// ReadableStream { } ReadableStream { }
```

How do I get the "WritableStream" from Bun.stdout?

**Comment by xhyrom** [comment] 2022-08-04 05:19
Duplicate of https://github.com/oven-sh/bun/issues/894

**Closed as not planned by xhyrom** 2022-08-04 05:19 UTC
Labels: enhancement

**Comment by xhyrom** [comment] 2022-08-04 05:51
Closed as not planned because this is duplicate (no because this is not planned), follow original issue for more informations.
