### ISSUE TITLE
`bun run` throws error

### ISSUE THREAD

**Issue by SunPodder** [oven-sh/bun#4697] opened 2023-09-09 14:03 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 4.19.127-22457755 aarch64 unknown

### What steps can reproduce the bug?

```
bun init
```
Add a `script` in package.json. then run
```bash
bun run test #test is the script name
```

### What is the expected behavior?

The script should exit without any errors

### What do you see instead?

```
Error loading current directory

error: CouldntReadCurrentDirectory

----- bun meta -----
Bun v1.0.0 (822a00c4) Linux arm64 #1 SMP PREEMPT Wed Jan 5 15:59:46 +07 2022
RunCommand:
Elapsed: 2ms | User: 0ms | Sys: 31ms
RSS: 33.55MB | Peak: 5.64MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x726b8df478
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
```

**Comment by eluce2** [comment] 2023-09-09 18:35
I'm having this same issue

**Comment by SunPodder** [comment] 2023-09-10 03:06
The same error occurs when trying to run a non-existing file. So probably bun isn't reading the package.json at all and trying to look for a file with that name.

**Comment by laaledesiempre** [comment] 2023-09-11 23:33
i have the same problem and also have problems installing packages, i can copy the files in cache to nodemodules. but it seems that bun cant. maybe problems with permission or something? 

> edit: verbose output at installing IM USING ROOT

``` bash
bun add v1.0.0 (822a00c4)
Loaded 1 hoisted_dependencies
Loaded 2 resolutions
Loaded 2 dependencies
Loaded 0 extern_strings
Loaded 77 string_bytes

-- BEGIN SHA512/256(`${alphabetize(name)}@${order(version)}`) --
bun-types@1.0.1
-- END HASH--
Saving 1 trees
Saving 1 hoisted_dependencies
Saving 2 resolutions
Saving 2 dependencies
Saving 0 extern_strings
Saving 77 string_bytes
error: AccessDenied installing bun-types

 installed bun-types@1.0.1

Failed to install 1 packages
[61.00ms] done
```


# UPDATE

``` bash
bun install --backend=copyfile
bun install v1.0.0 (822a00c4)
 + @types/node@20.6.0
 + bun-types@1.0.1

 2 packages installed [2.41s]
```

this trick seems to work on arm64 devices as seem in [#362](https://github.com/oven-sh/bun/issues/362#issuecomment-1177680128) this issue is techincally not solved, and is the only one with this specific error so is not duplicated.  this solution solves instalation problems but not the main one asked here. if it can helps to solve the issue...

**Comment by Electroid** [comment] 2023-10-27 20:37
Duplicate of #5182

**Closed as not planned by Electroid** 2023-10-27 20:37 UTC
Labels: bug
