### ISSUE TITLE
`bun update --save` does not change package.json

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#7214] opened 2023-11-19 02:13 UTC
### What version of Bun is running?

1.0.13+f5bf67bd1

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Try to run `bun update --save` in a project that has old packages.

### What is the expected behavior?

`package.json` and `bun.lockb` get updated correctly

### What do you see instead?

the version gets installed but the package.json and bun.lockb do not

### Additional information

Regarding `bun.lockb`:

the `version` does change what doesnt change is the main name, here is an example:
![image](https://github.com/oven-sh/bun/assets/80978939/8be24b15-2b35-4397-82e8-166fc86e4f83)

Regarding `bun update -f`:

There seems to be an issue where `-f` causes bun to say it updated packages that it rly didnt:
![image](https://github.com/oven-sh/bun/assets/80978939/f17b1bcc-7f03-4b48-ba0f-e091db089901)

**Comment by Electroid** [comment] 2023-11-20 17:18
Duplicate of #7214

**Comment by Electroid** [comment] 2023-11-20 17:18
Duplicate of #4312

**Closed as not planned by Electroid** 2023-11-20 17:18 UTC
Labels: bug
