### ISSUE TITLE
workspaces config wildcard not fully supported

### ISSUE THREAD

**Issue by justnewbee** [oven-sh/bun#5223] opened 2023-09-13 06:50 UTC
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

project structure is like below

```txt
workspace-demo/
├─ packages-dev/
│  └─ ts-config/
│     ├─ index.json
│     └─ package.json
├─ packages-hook/
│  ├─ react-hook-is-unmounted/
│  │  ├─ src/
│  │  │  └─ index.ts
│  │  ├─ package.json
│  │  └─ tsconfig.json
│  └─ react-hook-safe-state/
│     ├─ src/
│     │  └─ index.ts
│     ├─ package.json
│     └─ tsconfig.json
├─ .gitignore
└─ package.json
```

root **package.json** has `workspaces` like:

```json
"workspaces": [
    "packages-*/*"
  ],
```

`bun install` will raise this issue

### What is the expected behavior?

can successfully install workspaces' deps

### What do you see instead?

warn: workspaces directory prefix not found "packages-"

<img width="897" alt="image" src="https://github.com/oven-sh/bun/assets/2276086/50985a00-09ba-464e-99b4-bc932f132ed6">

### Additional information

i have to change `workspaces` like below to make bun work:

```
"workspaces": [
    "packages-dev/*",
    "packages-hook/*"
  ],
```

while, npm, yarn@1, pnpm all support `packages-*/*`

**Comment by infodusha** [comment] 2023-09-13 06:55
It actually seems to be not a bug but a feature:
From [docs](https://bun.sh/docs/install/workspaces):
> Glob support — Bun supports simple <directory>/* globs in "workspaces". Full glob syntax (e.g. ** and ?) is not yet supported.

They actually have no glob package in zig yet, so it does not work for now

**Comment by Hotell** [comment] 2023-09-13 11:33
~I'd say not even basic `/*` is supported as documented within docs.~

_**UPDATE:**_ so basic glob is supported, one just needs to migrate whole monorepo to use `"workspace:*" protocol instead of `"*"` or package name + version

<img width="1157" alt="image" src="https://github.com/oven-sh/bun/assets/1223799/1b08e910-d1c6-4275-9efc-c1b6f2942cd0">

not to mention `nohoist` and `resolutions` config, which might be crucial for some monorepos in production.


looking forward for full workspace compatibility with other package manages 🙌

**Comment by justnewbee** [comment] 2023-10-21 14:00
> It actually seems to be not a bug but a feature: From [docs](https://bun.sh/docs/install/workspaces):
> 
> > Glob support — Bun supports simple /* globs in "workspaces". Full glob syntax (e.g. ** and ?) is not yet supported.
> 
> They actually have no glob package in zig yet, so it does not work for now

right, i saw that right after i submitted this issue

**Comment by dylan-conway** [comment] 2024-05-30 10:17
Glob support was added in #10462, closing as complete. If you continue to have issues with bun workspaces please reopen this issue or create a new one

**Closed as completed by dylan-conway** 2024-05-30 10:17 UTC
Labels: bug
