### ISSUE TITLE
the command bun run <filename>.js leads to bun crashing

### ISSUE THREAD

**Issue by varssha1** [oven-sh/bun#12109] opened 2024-06-24 08:33 UTC
### How can we reproduce the crash?

import { serve } from "bun";
import Database from "better-sqlite3";

const db = new Database('tasks.db');

db.exec(`
  CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    isdone BOOLEAN NOT NULL DEFAULT 0
  )
`);

const handlers = {
  GET: {
    '/tasks': () => {
      const stmt = db.prepare('SELECT * FROM tasks');
      const tasks = stmt.all();
      return new Response(JSON.stringify(tasks), { status: 200 });
    },
  },
  POST: {
    '/tasks': async (req) => {
      const { name } = await req.json();
      const stmt = db.prepare('INSERT INTO tasks (name) VALUES (?)');
      stmt.run(name);
      return new Response('Task added', { status: 201 });
    },
  },
  PUT: {
    '/tasks/:id': async (req, params) => {
      const { id } = params;
      const { isdone } = await req.json();
      const stmt = db.prepare('UPDATE tasks SET isdone = ? WHERE id = ?');
      stmt.run(isdone, id);
      return new Response('Task updated', { status: 200 });
    },
  },
  DELETE: {
    '/tasks/:id': (req, params) => {
      const { id } = params;
      const stmt = db.prepare('DELETE FROM tasks WHERE id = ?');
      stmt.run(id);
      return new Response('Task deleted', { status: 200 });
    },
  },
};

serve({
  async fetch(req) {
    const { method, pathname } = new URL(req.url);
    const handler = handlers[method]?.[pathname];
    if (handler) {
      return handler(req, pathname.match(/\/tasks\/(\d+)/)?.groups);
    }
    return new Response('Not found', { status: 404 });
  },
  port: 3000,
});

console.log('Server running on http://localhost:3000');

### Relevant log output

```shell
bun server.js -debug
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at bindings (D:\zoho\bun2\node_modules\bindings\bindings.js:112:48)
      at new Database (D:\zoho\bun2\node_modules\better-sqlite3\lib\database.js:48:29)
      at D:\zoho\bun2\server.js:4:12

Bun v1.1.15 (Windows x64)
============================================================
Bun v1.1.15 (b23ba1fe) Windows x64
Args: "bun" "server.js" "-debug"
Features: jsc tsconfig(2)
Builtins: "bun:main" "node:fs" "node:path" "node:string_decoder" "node:util" "node:util/types"
Elapsed: 815ms | User: 109ms | Sys: 109ms
RSS: 115.67MB | Peak: 115.67MB | Commit: 0.16GB | Faults: 28511

panic(main thread): Segmentation fault at address 0x7FF822C54340
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.15/wa1b23ba1fAiggggE_CU\ntdll.dll43rUCU\ntdll.dllutqUCU\ntdll.dll63oUCa\KERNEL32.DLL26/FCa\ucrtbase.dllwt/GCa\ucrtbase.dllypgHsgr0Fki5B+/pkHA2w//Bg0h14iB
```

### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x7FFC67DF0C70

- *1 unknown/js code*
- ??? at `0x5177c` in ntdll.dll
- ??? at `0x514d7` in ntdll.dll
- ??? at `0x5117d` in ntdll.dll
- ??? at `0x17fab` in KERNEL32.DLL
- ??? at `0x1bed8` in ucrtbase.dll
- ??? at `0x1c099` in ucrtbase.dll
- [`Global.zig:123`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/Global.zig#L123>): `exitWide`
- [`Global.zig:106`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/Global.zig#L106>): `exit`
- [`javascript.zig:1094`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.js/javascript.zig#L1094>): `eventLoop`

**Comment by Jarred-Sumner** [comment] 2024-06-24 08:49
Duplicate of https://github.com/oven-sh/bun/issues/4290

**Closed as not planned** 2024-06-24 08:49 UTC
Labels: crash, windows, runtime
