### ISSUE TITLE
SolidStart issues with bun and vite building

### ISSUE THREAD

**Issue by itsyoboieltr** [oven-sh/bun#7429] opened 2023-12-03 01:52 UTC
### What version of Bun is running?

1.0.15+b3bdf22eb

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

The bug came up as I was developing my bun-based stack, called [DBEST](https://github.com/itsyoboieltr/dbest-stack) (DrizzleORM, Bun, ElysiaJS, SolidStart, Tailwind CSS). I made a reproduction branch available here: [reprod](https://github.com/itsyoboieltr/dbest-stack/tree/reprod)

Steps:
1. Clone repo, switch to reprod branch, which is a minimal reprod based on the original branch.
2. bun i
3. bun run build:node
  - This should behave as expected, producing a production build.
4. bun run build:bun
  - Errors, and hangs forever.

### What is the expected behavior?

```bash
$ solid-start build
 solid-start build 
 version  0.3.10
 adapter  node

solid-start building client...
solid-start rendering index.html...
solid-start index.html rendered in: 930.784ms
vite v4.4.9 building for production...
node_modules/solid-start/islands/A.tsx (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/solid-start/islands/A.tsx" was ignored.
✓ 59 modules transformed.
dist/public/.solid/index.html           0.18 kB │ gzip:  0.16 kB
dist/public/manifest.json               0.52 kB │ gzip:  0.21 kB
dist/public/ssr-manifest.json           1.42 kB │ gzip:  0.36 kB
dist/public/assets/index-6d4de98c.css   6.22 kB │ gzip:  1.87 kB
dist/public/assets/index-d53cc4fb.js    4.74 kB │ gzip:  2.08 kB
dist/public/assets/index-e212aa18.js   37.15 kB │ gzip: 14.57 kB
✓ built in 638ms
solid-start client built in: 1.585s

solid-start building server...
vite v4.4.9 building SSR bundle for production...
node_modules/solid-start/islands/A.tsx (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/solid-start/islands/A.tsx" was ignored.
✓ 54 modules transformed.
.solid/server/manifest.json     0.24 kB
.solid/server/entry-server.js  14.97 kB
✓ built in 284ms
solid-start server built in: 294.301ms
```

### What do you see instead?

```bash
$ bun --bun solid-start build
 solid-start build 
 version  0.3.10
[bun] Warning: worker_threads.Worker option "execArgv" is not implemented.
 adapter  bun

solid-start building client...
solid-start rendering index.html...
[bun] Warning: worker_threads.Worker option "execArgv" is not implemented.
[942.59ms] solid-start index.html rendered in
386 |             }
387 |           );
388 | 
389 |           const terminateShell = () => {
390 |             if (process.platform === 'win32') proc.kill()
391 |             else process.kill(-proc.pid);
                       ^
RangeError: pid must be a positive integer
      at terminateShell (node_modules/solid-start/bin.cjs:391:18)
      at node_modules/solid-start/bin.cjs:418:11
      at processTicksAndRejections (:61:77)
```

**Comment by itsyoboieltr** [comment] 2023-12-07 22:28
Interesting observation: this only happens if `ssr: false` in vite.config.ts. If the default options are used, it builds.

**Comment by birkskyum** [comment] 2023-12-08 14:59
Duplicate of
- #3736 

It'll be interesting to see how the upcoming SolidStart release (Vite 5, Nitro, Vinxi) will fare with bun.

**Closed as not planned by birkskyum** 2023-12-08 14:59 UTC
Labels: bug

**Comment by AritraBanik08** [comment] 2024-02-09 20:07
Can anyone please check [here](https://github.com/AritraBanik08/Shoppers) and tell me the problem or can you help me fix it. It is giving the error `[bun] Warning: worker_threads.Worker option "execArgv" is not implemented.`

**Comment by birkskyum** [comment] 2024-02-10 02:43
What version of bun do you use?

**Comment by AritraBanik08** [comment] 2024-02-10 12:10
@birkskyum bun version 1.0.11

**Comment by birkskyum** [comment] 2024-02-10 12:49
It might help to upgrade to the latest, 1.0.26. `bun upgrade`
