### ISSUE TITLE
Make test.only available without a flag

### ISSUE THREAD

**Issue by gkiely** [oven-sh/bun#6898] opened 2023-11-04 15:59 UTC
### What is the problem this feature would solve?

Allows developers to test a single test using `test.only` without having to use the `--only` flag.

This is particularly useful when testing with `bun test --watch` and debugging a single test. Having to stop and start bun to use `test.only` is time-consuming.

It would also match jest/vitest functionality.

### What is the feature you are proposing to solve the problem?

When a developer uses `test.only`, only those tests are run, regardless of if a flag is set. Otherwise testing proceeds as normal.

### What alternatives have you considered?

Switch between `bun test --watch` and `bun test --watch --only` as needed.

**Comment by Electroid** [comment] 2024-02-05 19:16
Duplicate of #7701

**Closed as not planned by Electroid** 2024-02-05 19:16 UTC
Labels: enhancement, bun:test
