### ISSUE TITLE
bun run build not working on wsl2 ubuntu

### ISSUE THREAD

**Issue by aigix** [oven-sh/bun#9102] opened 2024-02-25 12:36 UTC
### What version of Bun is running?

1.0.29

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64 and Linux 4.4.0-19041-Microsoft x86_64 x86_64

### What steps can reproduce the bug?

```shell
bun run build
``` 
![image](https://github.com/oven-sh/bun/assets/113825545/692aafb5-c313-4caa-aa16-0372fa394b69)

### What is the expected behavior?

The code can't be build for production on wsl2 but on my old laptop with linux or vercel/any nextjs host or any host who supports bunjs it's working with no errors

**Comment by Electroid** [comment] 2024-02-27 18:07
Duplicate of #8725

**Closed as not planned by Electroid** 2024-02-27 18:07 UTC
Labels: bug
