### ISSUE TITLE
NotImplementedError: worker_threads.Worker option "eval" is not yet implemented in Bun.

### ISSUE THREAD

**Issue by shaikahmadnawaz** [oven-sh/bun#10067] opened 2024-04-08 11:55 UTC
### What version of Bun is running?

1.1.2+c8d072c2a

### What platform is your computer?

Linux 6.2.0-1019-azure x86_64 x86_64

### What steps can reproduce the bug?

It's just a Next.js application, and I tried to start it. However, I can only see this issue when I try to render images. It's fine without the images.

bun --bun run dev

### What is the expected behavior?

It has to start the server without any issues.

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/96189881/47af0ce6-da59-48cb-9bd9-df2b9e1caea9)

**Comment by Electroid** [comment] 2024-04-08 16:23
Duplicate of #4165

**Closed as not planned by Electroid** 2024-04-08 16:23 UTC
Labels: bug
