### ISSUE TITLE
Porting a Jest test to Bun fails because of some node issue

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#2442] opened 2023-03-20 18:10 UTC
### What version of Bun is running?

0.5.8

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

I have this [repo](https://github.com/nikitavoloboev/isomorphic-git/tree/sparse-checkout).

Inside it has some jest tests, if I run one I get: 

```
~/clones/isomorphic-git sparse-checkout
❯ jest __tests__/test-pull.js
  console.log
    /var/folders/bn/br2v7mf14zb2yqhsyd4xd7nw0000gn/T/jest-fixture-AC7TDe

      at log (src/api/pull.js:95:13)

  console.log
    /var/folders/bn/br2v7mf14zb2yqhsyd4xd7nw0000gn/T/jest-fixture-SN5gFA

      at log (src/api/pull.js:95:13)

  console.log
    /var/folders/bn/br2v7mf14zb2yqhsyd4xd7nw0000gn/T/jest-fixture-utX6f8

      at log (src/api/pull.js:95:13)

 PASS  __tests__/test-pull.js
  pull
    ✓ pull (217 ms)
    ✓ pull fast-forward only (55 ms)
    ✓ pull no fast-forward (50 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        0.939 s, estimated 2 s
Ran all test suites matching /__tests__\/test-pull.js/i.
```

However jest is slow and I want to run it in bun. So I created this file:

https://github.com/nikitavoloboev/isomorphic-git/blob/sparse-checkout/__tests__/pull.test.ts

It should in theory work out of the box however there is now this issue:

```
❯ bun test
bun test v0.5.8 (5d296f62)

pull.test.ts:
SyntaxError: Missing 'default' import in module '/Users/nikiv/clones/isomorphic-git/http/node/index.d.ts'.

 0 pass
 1 fail
Ran 1 tests across 1 files [37.00ms]
```

For some reason, `import http from 'isomorphic-git/http'` is okay in node/jest bun in bun it fails.

Would love to solve this issue and move away from jest.

### What is the expected behavior?

bun test should succeed.

### What do you see instead?

It fails to import when in node it works fine.

**Comment by Electroid** [comment] 2023-10-25 23:49
Closing since the reproduction repo is no longer active. If you are still running into this issue, please re-open this issue and we'll investigate.

**Closed as not planned by Electroid** 2023-10-25 23:49 UTC
Labels: bug
