### ISSUE TITLE
Error verifying https certificates

### ISSUE THREAD

**Issue by jalvarezit** [oven-sh/bun#7200] opened 2023-11-18 11:53 UTC
### What version of Bun is running?

1.0.12

### What platform is your computer?

Linux 5.10.0-23-amd64 x86_64 unknown

### What steps can reproduce the bug?

* [Install kind](https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries)
* Create a kubernetes cluster using kind: `kind create cluster`
* Create a bun project: `bun init -y`
* Install kubernetes client library: `bun install @kubernetes/client-node`
* Create the following `index.js` file:

  ```typescript
  import k8s from '@kubernetes/client-node';

  const kc = new k8s.KubeConfig();

  kc.loadFromDefault();

  const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

  const main = async () => {
      try {
          const podsRes = await k8sApi.listNamespacedPod('default');
          console.log(podsRes.body);
      } catch (err) {
          console.error(err);
      }
  };
  
  main();

  ```
  
* Execute it with bun: `bun index.js` 

### What is the expected behavior?

It should list the pods in the kubernetes cluster, below is the same program file executed with `ts-node`:

```javascript
V1PodList {
  apiVersion: 'v1',
  items: [],
  kind: 'PodList',
  metadata: V1ListMeta {
    _continue: undefined,
    remainingItemCount: undefined,
    resourceVersion: '120519',
    selfLink: undefined
  }
}
```

### What do you see instead?

Instead it throws the following error validating the certificates:

```
UNABLE_TO_VERIFY_LEAF_SIGNATURE: unable to verify the first certificate
 path: "https://127.0.0.1:35781/api/v1/namespaces/default/pods"
```

### Additional information

Other software versions that may be of interest:

* ts-node: v10.9.1
* kind: 0.20.0

**Comment by medzhidov** [comment] 2023-11-22 10:23
I have the same bug with local certificates created by mkcert

**Comment by lionelquellery** [comment] 2023-12-09 16:04
I have the same issue, but I'm working on Elysia JS a framework based on Bun. When, I have added my keys. I had this error when a run the server. 

UNABLE_TO_VERIFY_LEAF_SIGNATURE: unable to verify the first certificate

Someone has a solution against that?

**Comment by david-plugge** [comment] 2023-12-13 16:57
duplicate of https://github.com/oven-sh/bun/issues/7332

**Comment by dpeek** [comment] 2024-01-29 23:32
Adding some hopefully helpful context: I'm also getting this issue when using [devcert](https://www.npmjs.com/package/devcert) issued certificates.

From their docs:

> When it installs or upgrades, devcert creates a self-signed certificate authority (CA) which it uses to sign all certificates it creates. It will try to register this CA with OS keychains in OSX, Linux, and Windows. However, some HTTP clients (such as Firefox and NodeJS itself) use their own trusted certificate list instead of the operating system's keychain.

To prevent SSL errors with Node, I had to add this to my profile:
`export NODE_EXTRA_CA_CERTS="$HOME/Library/Application Support/devcert/certificate-authority/certificate.cert"`

I guess bun needs to support this to be a drop in replacement for Node. It would also be cool if bun just supported the OS keychains so you didn't have to do this :)

Edit: looks like loading keychain certs was investigated in #6588 but the result was slow. Perhaps this is why Node went with `NODE_EXTRA_CA_CERTS`?

For now, `export NODE_TLS_REJECT_UNAUTHORIZED=0` (while a bad idea TM) works around the issue.

**Comment by malthe** [comment] 2024-02-17 09:21
Suggest rename to "Add support for NODE_EXTRA_CA_CERTS".

**Comment by Anprotaku** [comment] 2024-03-06 08:13
Hi, im also having this issue right now and export NODE_TLS_REJECT_UNAUTHORIZED=0 does not fix the issue

**Closed as completed** 2024-08-07 20:21 UTC
Labels: bug, needs investigate

**Comment by kahirokunn** [comment] 2025-05-23 05:22
Hello,

I noticed this issue was closed after implementing `NODE_EXTRA_CA_CERTS` support, but I believe the core problem remains unresolved.

### The Original Problem
This issue reports a problem with dynamic certificate handling when using the Kubernetes client library. The key requirement is to **dynamically specify certificates per request**, as shown in the original code:

```javascript
const kc = new k8s.KubeConfig();
kc.loadFromDefault(); // Dynamically loads certificates
```

### Why NODE_EXTRA_CA_CERTS is insufficient

While `NODE_EXTRA_CA_CERTS` (implemented in Bun v1.1.22) is a valuable addition, it has fundamental limitations:

1. **Static configuration only**: Certificates are loaded once at startup
2. **Global scope**: Applies to all HTTPS connections uniformly  
3. **No runtime flexibility**: Cannot change certificates during execution
4. **No client certificate support**: Only handles CA certificates, not client cert/key pairs

### Real-world use cases that remain unsupported

- Kubernetes clients that need different certificates for different clusters
- Multi-tenant applications requiring per-request certificate selection
- Certificate rotation without restarting the application
- mTLS scenarios requiring client certificates

### Suggested approach

To properly resolve this issue, Bun would need to support dynamic certificate configuration similar to Node.js:

```javascript
// What we need - dynamic certificate support
const agent = new https.Agent({
  cert: dynamicCert,
  key: dynamicKey,
  ca: dynamicCA
});

// Or with fetch
fetch(url, {
  tls: {
    cert: clientCert,
    key: clientKey,
    ca: customCA
  }
});
```

### Recommendation

I suggest reopening this issue or creating a new one specifically for dynamic certificate support. The current `NODE_EXTRA_CA_CERTS` implementation is helpful for some use cases but doesn't address the core problem reported here.

Related issue #9376 has the same underlying requirement and was also closed prematurely.

Thank you for all the great work on Bun! I hope this feedback helps improve certificate handling for complex use cases.

**Comment by anthonyhoegberg** [comment] 2025-05-23 05:26
> Hello,
> 
> I noticed this issue was closed after implementing `NODE_EXTRA_CA_CERTS` support, but I believe the core problem remains unresolved.
> 
> ### The Original Problem
> This issue reports a problem with dynamic certificate handling when using the Kubernetes client library. The key requirement is to **dynamically specify certificates per request**, as shown in the original code:
> 
> ```javascript
> const kc = new k8s.KubeConfig();
> kc.loadFromDefault(); // Dynamically loads certificates
> ```
> 
> ### Why NODE_EXTRA_CA_CERTS is insufficient
> 
> While `NODE_EXTRA_CA_CERTS` (implemented in Bun v1.1.22) is a valuable addition, it has fundamental limitations:
> 
> 1. **Static configuration only**: Certificates are loaded once at startup
> 2. **Global scope**: Applies to all HTTPS connections uniformly  
> 3. **No runtime flexibility**: Cannot change certificates during execution
> 4. **No client certificate support**: Only handles CA certificates, not client cert/key pairs
> 
> ### Real-world use cases that remain unsupported
> 
> - Kubernetes clients that need different certificates for different clusters
> - Multi-tenant applications requiring per-request certificate selection
> - Certificate rotation without restarting the application
> - mTLS scenarios requiring client certificates
> 
> ### Suggested approach
> 
> To properly resolve this issue, Bun would need to support dynamic certificate configuration similar to Node.js:
> 
> ```javascript
> // What we need - dynamic certificate support
> const agent = new https.Agent({
>   cert: dynamicCert,
>   key: dynamicKey,
>   ca: dynamicCA
> });
> 
> // Or with fetch
> fetch(url, {
>   tls: {
>     cert: clientCert,
>     key: clientKey,
>     ca: customCA
>   }
> });
> ```
> 
> ### Recommendation
> 
> I suggest reopening this issue or creating a new one specifically for dynamic certificate support. The current `NODE_EXTRA_CA_CERTS` implementation is helpful for some use cases but doesn't address the core problem reported here.
> 
> Related issue #9376 has the same underlying requirement and was also closed prematurely.
> 
> Thank you for all the great work on Bun! I hope this feedback helps improve certificate handling for complex use cases.
> 

Maybe reopen as new issue specifying this problem and use cases etc? Feels valid

**Comment by Jarred-Sumner** [comment] 2025-05-23 05:29
@kahirokunn both of these approaches shown should work:
```ts
// What we need - dynamic certificate support
const agent = new https.Agent({
  cert: dynamicCert,
  key: dynamicKey,
  ca: dynamicCA
});

// Or with fetch
fetch(url, {
  tls: {
    cert: clientCert,
    key: clientKey,
    ca: customCA
  }
});
```

What error did you see when you gave it a try?

**Comment by cromega** [comment] 2025-06-19 13:29
same issue, can't connect to a Kubernetes cluster using @kubernetes/client-node

**Comment by kelvinwop** [comment] 2025-06-23 14:26
same issue

**Comment by kelvinwop** [comment] 2025-06-23 15:12
yooooooooooo gang i figured out a workaround
https://github.com/kubernetes-client/javascript/issues/1509

bun add @kubernetes/client-node@0.22.3

you need to use the version prior to 1.0.0, which is 0.22.3
