### ISSUE TITLE
bun install dependencies of os incompatible optionalDependencies

### ISSUE THREAD

**Issue by ArnaudBarre** [oven-sh/bun#1205] opened 2022-09-04 11:17 UTC
### Version

0.1.10

### Platform

Mac intel

### What steps will reproduce the bug?

```sh
bun add @swc/core
```

### What is the expected behavior?

```
node_modules
    @swc
        core
            package.json
        core-darwin-x64
            package.json
```

### What do you see instead?

```
node_modules
    @swc
        core
            package.json
        core-android-arm-eabi
            node_modules
                @swc
                    wasm
                        package.json
        core-darwin-x64
            package.json
        wasm
            package.json
```

**Comment by xhyrom** [comment] 2022-09-04 13:15
Can you try canary build? It can be because missing os implementation in stable version.

**Comment by ArnaudBarre** [comment] 2022-09-04 14:39
Same issue with canary.

bun ignore installing packages for other os/cpu. but the issue is that the dependencies of these skipped package are still installed. You can see that these is no `package.json` for `core-android-arm-eabi`
This is not a common use case, often packages with these conditions are "leaf" of the dependency tree (this is the case for esbuild or parcel css)

**Comment by asottile-sentry** [comment] 2022-09-20 15:18
I think (?) this is the same problem -- using bun 0.1.3 on linux x86_64:

here's a minimal reproduction:

```console
$ cat package.json 
{"dependencies": {"chokidar": "*"}}
$ bun install --yarn
bun install v0.1.13
 + chokidar@3.5.3

 14 packages installed [693.00ms]
```

this creates a yarn lockfile that has incorrect dependencies:

```console
$ rm -rf node_modules
$ yarn install
yarn install v1.22.19
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error fsevents@2.3.2: The platform "linux" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

the difference between the lockfiles appears to be handling of `optionalDependencies`:

```diff
$ diff -u <(sed 's/tgz#.*"/tgz"/g' yarn.lock) yarn.lock.bun
--- /dev/fd/63	2022-09-20 11:15:59.289446454 -0400
+++ yarn.lock.bun	2022-09-20 11:13:57.065443600 -0400
@@ -1,5 +1,6 @@
 # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 # yarn lockfile v1
+# bun ./bun.lockb --hash: 678F5BC3C2B30D95-fe2de4c5fdc85003-83B2DE77992FC7A0-2a5d090942fac8b9
 
 
 anymatch@~3.1.2:
@@ -34,7 +35,6 @@
     is-glob "~4.0.1"
     normalize-path "~3.0.0"
     readdirp "~3.6.0"
-  optionalDependencies:
     fsevents "~2.3.2"
 
 fill-range@^7.0.1:
```

**Comment by asottile-sentry** [comment] 2023-01-05 17:35
so I started looking into this -- the yarn printer seems like it _should_ handle this -- or at least there's code for it.  that would make me think that the actual resolution is incorrect? or something earlier?

https://github.com/oven-sh/bun/blob/0873a15a637339506207fe9bd628e2839d78dbbc/src/install/lockfile.zig#L1313-L1315

**Comment by Jarred-Sumner** [comment] 2023-01-05 20:55
The intended current behavior is they appear in the lockfile and are resolved, but are not actually downloaded/installed to disk. This is so if people working on the project have different hardware/os, the lockfile doesn’t change. 

If they are being downloaded/installed to disk anyway, that is indeed a bug and from the first directory tree shown that is what seems to be happening

**Comment by asottile-sentry** [comment] 2023-01-05 21:20
I guess my usecase is a little weird: I want to incrementally introduce bun -- first as an installer in CI (where it is way faster than `yarn`) -- but in order to do that gradual step I need to not break `yarn` (since there's still some special stuff that only works there).  since `optionalDependencies` isn't preserved correctly in the yarn lockfile it breaks any dev still using yarn (even if `bun` correctly installs)

**Comment by Electroid** [comment] 2023-02-27 16:59
This is fixed as of Bun 0.5.8.

```
❯ bun add @swc/core
bun add v0.5.8 (5d296f62)

 installed @swc/core@1.3.36


 2 packages installed [817.00ms]

❯ ls node_modules/@swc
core/              core-darwin-arm64/
```

**Closed as completed by Electroid** 2023-02-27 16:59 UTC
Labels: bug, bun install

**Comment by asottile-sentry** [comment] 2023-02-27 17:27
@Electroid do you have a specific link to the fix? I'm not seeing it working with 0.5.7 (the currently released version):

```console
$ bun install --yarn
bun install v0.5.7 (5929daee)
 + chokidar@3.5.3

 14 packages installed [375.00ms]
$ rm -rf node_modules/
$ yarn install
yarn install v1.22.19
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error fsevents@2.3.2: The platform "linux" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by Electroid** [comment] 2023-02-27 17:31
@asottile-sentry Oops, forgot I was on our canary build when testing this. Could you try again after running: `bun upgrade --canary`? If you're running into the same issue will re-open.

**Comment by Jarred-Sumner** [comment] 2023-02-27 17:31
@asottile-sentry I think the issue you're running into is in the yarn lockfile printer. It should report that the fsevents module is an optional dependency but it isn't. That is a different issue than installing the module. 

Regardless though, we would love for Sentry to use Bun and we will prioritize making it work for your usecase.

**Comment by asottile-sentry** [comment] 2023-02-27 17:35
sounds good -- will follow #2216!  (fwiw the --canary also failed in the same way)
