### ISSUE TITLE
Slower when calculating Fibonacci using BigInt (1M)

### ISSUE THREAD

**Issue by rafaell-lycan** [oven-sh/bun#5975] opened 2023-09-23 17:06 UTC
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

**Disclaimer**

Many could say this test doesn't count as it's not a web app or CLI, but still, this is a simple Fibonacci using huge numbers.

Running the following script with both `node` and `bun` which can handle `BigInt` for a fib of 1.000.000 took almost 3x longer than Node.js v20.
 
```js
// fibonacci.js
console.time("Execution Time");
function fibonacci(n) {
  let a = BigInt(0);
  let b = BigInt(1);
  for (let i = BigInt(0); i < n; i++) {
    [a, b] = [b, a + b];
  }
  console.log(`fib: ${a}`);
}
fibonacci(1000000);
console.timeEnd("Execution Time");
```

```bash
# Node
for i in {1..10}; do node fibonacci.js; done

# Bun
for i in {1..10}; do bun fibonacci.js; done
```

**Node:** 6.153s
**Bun:** 15.02s

Btw, this is a silly benchmark, I can't tell if this is an issue within Bun itself, WebKit, or even something with the Apple Silicon (M1) architecture. For context, I've run the same script with different values 10 times to get an average.

After running with smaller values like ~15.000 it proves that can be the fastest.

**For 100.000**
**Node:** 100.532ms
**Bun:** 181.12ms

**For 50.000**
**Node:** 39.026ms
**Bun:** 49.56ms

**For 20.000**
**Node:** 10.759ms
**Bun:** 14.63ms

**For 15.000**
**Node:** 9.087ms
**Bun:** 8.18ms

**For 10.000**
**Node:** 7.932ms
**Bun:** 4.97ms

After that, I dropped all `BitInt` from the code (renders `Intinify`) to check if that was the case, and although it was faster, it didn't take the lead for 1.000.000.

**For 1.000.000**
**Node:** 8.595ms
**Bun:** 11.08ms

**For 500.000**
**Node:** 7.096ms
**Bun:** 4.68ms

**For 100.000**
**Node:** 6.45ms
**Bun:** 2.26ms

### What is the expected behavior?

I believe that the expected behavior would be at least performing similarly to Node for a huge value would be fair.

### What do you see instead?

Slower performance than Node, especially when using `BigInt`.

### Additional information

I ran these tests on a base Macbook Pro with M1 +8GB. There's probably the best way to run this test or make it more interesting using recursion, or even having a sample with more than 10x.

I haven't tested on another CPU (Intel/AMD) to compare, so I can't tell if _Apple Silicon_ would be the problem.

I hope this can be insightful _(probably not)_ as Bun aims for performance.

**Comment by jimmywarting** [comment] 2023-09-23 18:33
Maybe try comparing v8 vs webkit (aka: chrome vs safari)
*edit*: i did it for u

- Safari - Execution Time: 29266.086ms 
- Chrome - Execution Time: 5895.7451171875 ms

Macbook Pro M1

**Comment by rafaell-lycan** [comment] 2023-09-23 18:36
@jimmywarting It could be an engine issue or something else, but that's why I reinforced otherwise they should at least perform similarly.

**Comment by jimmywarting** [comment] 2023-09-23 18:39
this feels more like a Webkit Bug than a Bun issue. 
cuz not much Bun or NodeJS stuff is going on here in this bench code.

**Comment by Electroid** [comment] 2023-09-23 19:26
Duplicate of #3723

**Closed as not planned by Electroid** 2023-09-23 19:26 UTC
Labels: bug

**Comment by Electroid** [comment] 2023-09-23 19:27
For what it's worth, there are some micro-benchmarks where V8 will beat JSC, or JSC will beat V8. This is just the nature of different implementations.
