### ISSUE TITLE
bun add <package> Compatibility Behaviour

### ISSUE THREAD

**Issue by djamez** [oven-sh/bun#15190] opened 2024-11-16 15:16 UTC
### What version of Bun is running?

1.1.34

### What platform is your computer?

Linux 6.9.3-76060903-generic x86_64 x86_64

### What steps can reproduce the bug?

Assuming a package is already installed and is listed in `package.json`'s `dependencies` section; invoking `npm i <package> -d` moves the package from `dependencies` to `devDependencies`.

### What is the expected behavior?

`bun add <package> -d` does not behave the same. One is required to first remove the package and then re-add it with the `-d` flag; or manually edit `package.json`.

**Comment by RiskyMH** [comment] 2024-11-25 02:49
Duplicate of #15209

**Closed as duplicate by RiskyMH** 2024-11-25 02:49 UTC
Labels: bug, bun install
