### ISSUE TITLE
Ability to patch packages like yarn patch or pnpm patch

### ISSUE THREAD

**Issue by deathemperor** [oven-sh/bun#3930] opened 2023-08-02 16:23 UTC
### What is the problem this feature would solve?

Patches for packages that no longer maintained or patches to customize packages without forking

### What is the feature you are proposing to solve the problem?

bun patch like https://yarnpkg.com/cli/patch or https://pnpm.io/cli/patch

**Comment by xhyrom** [comment] 2023-08-03 08:01
Duplicate of https://github.com/oven-sh/bun/issues/2336

**Closed as not planned** 2023-08-03 17:51 UTC
Labels: enhancement, bun install
