### ISSUE TITLE
Bun installs wrong architecture

### ISSUE THREAD

**Issue by almahdi404** [oven-sh/bun#12859] opened 2024-07-26 21:24 UTC
### What version of Bun is running?

v1.1.20

### What platform is your computer?

Linux 5.4.0-190-generic x86_64 x86_64

### What steps can reproduce the bug?

```bash
bun
```

### What is the expected behavior?

Should be running the `repl`

### What do you see instead?

============================================================
Bun v1.1.20 (ae194892) Linux x64 (baseline)
Illegal instruction (core dumped)

**Comment by Electroid** [comment] 2024-07-26 21:33
How did you install Bun? Based on the error message, it installed the right architecture, but there is probably another bug going on.

**Comment by almahdi404** [comment] 2024-07-26 23:27
```bash
curl -fsSL https://bun.sh/install | bash
```

**Comment by Jarred-Sumner** [comment] 2024-08-08 22:07
Duplicate of #3312

**Comment by Jarred-Sumner** [comment] 2024-08-08 22:08
Bun supports CPUs up to about 10 years ago

If you're using a CPU emulator, make sure to enable more recent hardware features.

**Closed as not planned by Jarred-Sumner** 2024-08-08 22:08 UTC
Labels: bug, needs triage
