### ISSUE TITLE
No support for fs.statfs

### ISSUE THREAD

**Issue by sancho1952007** [oven-sh/bun#10347] opened 2024-04-18 08:49 UTC
### What version of Bun is running?

1.1.4+fbe2fe0c3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

fs.statSync gives an error that it isn't supported.

### What is the expected behavior?

Show folder information.

### What do you see instead?

const fs = require('fs');
13 | const path = require('path');
14 | 
15 | const spaceAvailableOnDisk = fs.statfsSync('/');
                                  ^
TypeError: fs.statfsSync is not a function. (In 'fs.statfsSync("/")', 'fs.statfsSync' is undefined)
      at C:\Users\---\functions\cache.js:15:30
      at C:\Users\---\functions\verify-session.js:4:7
      at C:\Users\---\app.js:27:7

**Comment by RiskyMH** [comment] 2024-10-12 05:03
duplicate of #5517

**Closed as completed by RiskyMH** 2024-10-12 05:03 UTC
Labels: bug, node.js

**Comment by RiskyMH** [comment] 2024-10-12 05:05
Duplicate of #5517

**Comment by Jarred-Sumner** [comment] 2025-01-20 08:43
Implemented in https://github.com/oven-sh/bun/pull/16519
