### ISSUE TITLE
yarn works but bun install gives error with some MUI package

### ISSUE THREAD

**Issue by ramsane** [oven-sh/bun#5252] opened 2023-09-13 09:06 UTC
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Mac OS

### What steps can reproduce the bug?

Keep the following as dependancy

@mui/icons-material": "^5.11.11",
    "@mui/lab": "^5.0.0-alpha.124",
    "@mui/material": "^5.11.13",
    "@mui/x-data-grid": "^6.10.0",
    "@mui/x-date-pickers": "^6.4.0",

And run bun install

### What is the expected behavior?

It should install properly like yarn does

### What do you see instead?

error: package "@mui/x-tree-view" with tag "https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view" not found, but package exists

### Additional information

I've seen that there is no dependency that is specified for this. but still gave the error

**Comment by Hanaasagi** [comment] 2023-09-13 09:15
Related to https://github.com/oven-sh/bun/issues/4666

**Comment by Electroid** [comment] 2023-10-13 04:20
Duplicate of https://github.com/oven-sh/bun/issues/4666

**Closed as not planned by Electroid** 2023-10-13 04:20 UTC
Labels: bug
