### ISSUE TITLE
Best approach to make edits to dependencies locally

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#2189] opened 2023-02-25 19:07 UTC
### What is the issue?

I can't find out how I can from my one bun project use dependencies of a local package.

i.e. I cloned https://github.com/Schniz/cmd-ts into `~/clones`

Then in my bun project I want to somehow link into this `cmd-ts` local dependency so I can make changes to ~/clones/cmd-ts and the imports of my other bun project reflect those changes.

Actually though I realise I can just modify the `node_modules` directly. 

Is this how you would do it? And it would be nice to maybe have a section in docs for `how to hack on dependencies locally`.

Thank you.

**Comment by Electroid** [comment] 2023-10-25 22:56
Duplicate of #2336

**Closed as not planned by Electroid** 2023-10-25 22:56 UTC
Labels: docs
