### ISSUE TITLE
Does not support Github dependencies

### ISSUE THREAD

**Issue by robogeek** [oven-sh/bun#465] opened 2022-07-08 23:55 UTC
I have an existing package that has some dependencies in Github.  Attempting to run `bun install` gives the following error

```
$ bun install
bun install v0.1.2


error: Unsupported dependency type github for "github:akashacms/akasharender"

$ bun install
bun install v0.1.2


error: Unsupported dependency type github for "akashacms/akasharender"
```

I tried both with- and without the `github` prefix.

`package.json`:

```json
{
  "name": "t",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "akasharender": "github:akashacms/akasharender"
  }
}
```

**Comment by FinnRG** [comment] 2022-07-08 23:57
@robogeek  Duplicate of #81.

**Closed as completed** 2022-07-09 00:13 UTC
