### ISSUE TITLE
Segmentation fault at address 0xFFFFFFFFFFFFFFFF when using bun serve

### ISSUE THREAD

**Issue by tiagozip** [oven-sh/bun#11467] opened 2024-05-30 18:07 UTC
### How can we reproduce the crash?

Check "JavaScript/TypeScript code that reproduces the crash". Command ran: `bun run dev`

### JavaScript/TypeScript code that reproduces the crash?

```shell
**index.js**

Bun.serve({
    development: true,
    fetch(req) {
      const url = new URL(req.url);
      const pathParts = url.pathname.split("/");
      const fileName = pathParts.pop();
      const dir = pathParts.join("/");
      const filePath = `./src/${dir}/${fileName}`;
      if (Bun.file(filePath)) return new Response(Bun.file(filePath));

      return new Response("404!");
    },
});


**package.json**
```json
{
  "name": "name",
  "module": "index.js",
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "scripts": {
    "dev": "bun run index.js --hot"
  },
  "type": "module"
}
```
```


### Relevant log output

```shell
GET - http://localhost:3000/ failed
============================================================
Bun v1.1.10 (5102a944) Windows x64
Args: "C:\Users\HUAWEI\.bun\bin\bun.exe" "run" "index.js" "--hot"
Features: jsc abort_signal http_server 
Builtins: "bun:main" 
Elapsed: 2463ms | User: 46ms | Sys: 156ms
RSS: 118.42MB | Peak: 118.42MB | Commit: 0.19GB | Faults: 29160

panic(main thread): Segmentation fault at address 0xFFFFFFFFFFFFFFFF
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.10/wr15102a94AihgBwlnzb8rv+Y+1shXolyhXw4yteut2uegtzueqz00G2rx61C60+tFA2DD

error: script "dev" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0xFFFFFFFFFFFFFFFF

- [`server.zig:2235`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/api/server.zig#L2235>): `onReadFile`
- [`ReadFile.zig:588`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/webcore/blob/ReadFile.zig#L588>): `finalize`
- [`ReadFile.zig:629`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/webcore/blob/ReadFile.zig#L629>): `onFileOpen`
- [`blob.zig:1765`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/webcore/blob.zig#L1765>): `callback`
- `uv__work_done`
- `??`
- `uv_run`
- [`uws.zig:2828`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/deps/uws.zig#L2828>): `run`
- `JSC__VM__holdAPILock`
- [`shimmer.zig:186`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/bindings/shimmer.zig#L186>): `cppFn`

**Comment by Jarred-Sumner** [comment] 2024-06-06 11:59
Duplicate of https://github.com/oven-sh/bun/issues/11617

**Closed as not planned by Jarred-Sumner** 2024-06-06 11:59 UTC
Labels: crash
