### ISSUE TITLE
symbol lookup error napi-v6-linux-x64/node_sqlite3.node: undefined symbol: uv_async_init

### ISSUE THREAD

**Issue by oldwizard1010** [oven-sh/bun#6392] opened 2023-10-10 02:18 UTC
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Linux 6.2.16-2-arch x86_64 unknown

### What steps can reproduce the bug?
`bun install @journeyapps/sqlcipher`
````
var sqlite3 = require('@journeyapps/sqlcipher').verbose();
var db = new sqlite3.Database('test.db');

db.serialize(function() {
  // This is the default, but it is good to specify explicitly:
  db.run("PRAGMA cipher_compatibility = 4");

  // To open a database created with SQLCipher 3.x, use this:
  // db.run("PRAGMA cipher_compatibility = 3");

  db.run("PRAGMA key = 'mysecret'");
  db.run("CREATE TABLE lorun (info TEXT)");

  var stmt = db.prepare("INSERT INTO lorun VALUES (?)");
  for (var i = 0; i < 10; i++) {
      stmt.run("Ipsum " + i);
  }
  stmt.finalize();

  db.each("SELECT rowid AS id, info FROM lorun", function(err, row) {
      console.log(row.id + ": " + row.info);
  });
});

db.close();
````

### What is the expected behavior?

1: Ipsum 0
2: Ipsum 1
3: Ipsum 2
4: Ipsum 3
5: Ipsum 4
6: Ipsum 5
7: Ipsum 6
8: Ipsum 7
9: Ipsum 8
10: Ipsum 9

### What do you see instead?

bun: symbol lookup error: node_modules/@journeyapps/sqlcipher/lib/binding/napi-v6-linux-x64/node_sqlite3.node: undefined symbol: uv_async_init

### Additional information

it logs this error, but still works, by the way

**Comment by Electroid** [comment] 2023-12-21 21:38
Duplicate of #5019

**Closed as not planned by Electroid** 2023-12-21 21:38 UTC
Labels: bug, node.js
