### ISSUE TITLE
Dockerode works with tsx, but not with bun

### ISSUE THREAD

**Issue by benjick** [oven-sh/bun#5112] opened 2023-09-12 15:04 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Create a new nextjs app: https://bun.sh/guides/ecosystem/nextjs
2. Install deps: `bun install dockerode uuid`
3. Create `src/run.ts`:

```ts
import Docker from "dockerode";
import { v4 as uuidv4 } from "uuid";

const docker = new Docker({ socketPath: "/var/run/docker.sock" });

async function main() {
  const jobUuid = uuidv4();

  const container = await docker.createContainer({
    Image: "hello-world",
    name: jobUuid,
  });

  const inspect = await container.inspect();

  console.log("🚚", inspect.Name);

  await container.remove();
}

main();
```
4. Run it: `bun run src/run.ts`

### What is the expected behavior?

If I run it with `tsx` I get the correct expected output:

```sh
npx tsx src/run.ts
🚚 /d30f8bf9-9bd5-42eb-97a3-3f7c2aa5b280
```

### What do you see instead?

With bun I get the following:

```sh
bun run src/run.ts
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost/containers/create?Image=hello-world&name=cca63638-4201-429a-855f-61b5791337ce"
```

**Comment by sirenkovladd** [comment] 2023-09-20 17:29
Duplicate of https://github.com/oven-sh/bun/issues/2734

**Closed as not planned** 2023-09-20 17:50 UTC
Labels: bug

**Comment by chrisvander** [comment] 2023-10-10 12:00
Interesting! Why does tsx work?
