### ISSUE TITLE
URL Pattern API

### ISSUE THREAD

**Issue by fkdiomande** [oven-sh/bun#6403] opened 2023-10-10 17:26 UTC
### What is the problem this feature would solve?

- https://deno.land/api@v1.37.1?s=URLPattern
- https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API

### What is the feature you are proposing to solve the problem?

To create a custom Router

### What alternatives have you considered?

https://github.com/pillarjs/path-to-regexp

**Comment by Electroid** [comment] 2023-10-10 17:35
Duplicate of #2286

**Closed as not planned by Electroid** 2023-10-10 17:35 UTC
Labels: enhancement
