### ISSUE TITLE
Consider static linking build binaries

### ISSUE THREAD

**Issue by Zaczero** [oven-sh/bun#11638] opened 2024-06-06 07:12 UTC
### What is the problem this feature would solve?

Static linking will increase code compatibility, as all necessary methods will be self-contained within the build file. It would no longer depend on system libraries. It can also improve performance since more aggressive optimizations can be made.

![image](https://github.com/oven-sh/bun/assets/10835147/612b7c5e-fc74-41ab-a6d0-9a90918065b8)

### What is the feature you are proposing to solve the problem?

During the build process, instruct GCC to statically link necessary libraries.

For example like [biome](https://github.com/biomejs/biome/releases) does in their musl builds:

![image](https://github.com/oven-sh/bun/assets/10835147/9b273631-59ca-49d6-9c71-0d581352e070)

**Comment by Jarred-Sumner** [comment] 2024-06-06 07:15
Duplicate of #918

**Comment by Jarred-Sumner** [comment] 2024-06-06 07:15
We are tracking this in #918, please follow along there

**Closed as not planned by Jarred-Sumner** 2024-06-06 07:15 UTC
Labels: enhancement
