### ISSUE TITLE
Bun watch command doesn't work for shareable folder in vmbox or vmware!

### ISSUE THREAD

**Issue by ToxicalNoob3062** [oven-sh/bun#3244] opened 2023-06-08 03:54 UTC
### What version of Bun is running?

0.6.6

### What platform is your computer?

Linux 6.1.0-kali9-amd64 x86_64 unknown

### What steps can reproduce the bug?

[video explanation](https://www.vidline.com/share/V02WHZ3N6D/f98d206fba9c3e404e3f827d15a63bee)

watch mode not working when running "bun run --watch file."
the thing I was doing in connecting my VMware with host windows 11 and giving access to a specific folder as shareable to the VMware. Now if I change the file from my VMware, it could detect the changes. But when I change the file from my host it got automatically changed in in VMware OS too, but the problem is bun can't detect that change.

I will just say that bun team could give a slight focus here to improve their bun commands works in different circumstances. 

### What is the expected behavior?

Should auto execute after detecting file changes but that is not happening.

**Comment by Electroid** [comment] 2024-02-05 18:47
Duplicate of #5841

**Closed as not planned by Electroid** 2024-02-05 18:47 UTC
Labels: bug
