### ISSUE TITLE
support `npm:` and `jsr:` specifers like Deno

### ISSUE THREAD

**Issue by sigmaSd** [oven-sh/bun#9331] opened 2024-03-09 15:38 UTC
### What is the problem this feature would solve?

Make people who are used to Deno ecosystem transition more easily, by allowing bun to run their existing projects.

### What is the feature you are proposing to solve the problem?

support `npm:` and `jsr:`

- `npm:` is probably easy , since bun already supports npm so I expect `import {} from "npm:cowsay";` to work with bun as well
- `jsr:` https://jsr.io/docs/introduction jsr already supports bun so bun supporting it would be great as well

### What alternatives have you considered?

Do nothing

**Comment by Jarred-Sumner** [comment] 2024-03-09 15:48
Duplicate of #6987

**Closed as not planned by Jarred-Sumner** 2024-03-09 15:48 UTC
Labels: enhancement

**Comment by Malix-Labs** [comment] 2025-05-14 14:39
#6987 being closed as not planned, using jsr in bun is unfortunatly not optimal in the current condition

Also see https://github.com/oven-sh/bun/issues/6987#issuecomment-2041438328
