### ISSUE TITLE
randomUUIDv7 isn't exported in type definitions

### ISSUE THREAD

**Issue by kaanozdokmeci** [oven-sh/bun#14961] opened 2024-11-02 17:45 UTC
### What version of Bun is running?

1.1.34+5e5e7c60f

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

bun add -D @types/bun -> doesn't have randomUUIDv7
bun add -D bun-types -> doesn't export randomUUIDv7

### What is the expected behavior?

@types/bun is up to date and exports randomUUIDv7
bun-types exports randomUUIDv7

### What do you see instead?

@types/bun is not up to date, doesn't contain randomUUIDv7
bun-types contains randomUUIDv7 but doesn't export it.

**Comment by kaandok** [comment] 2024-11-03 09:20
works as intended, closing.

**Closed as completed by kaandok** 2024-11-03 09:20 UTC
Labels: bug, types

**Comment by pma9** [comment] 2024-11-22 18:51
@kaandok I'm still not getting the types for this function, can you help me understand how it works as intended? thanks!
