### ISSUE TITLE
Add a way to exclude/ignore extensions to `Bun.Glob`

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#8192] opened 2024-01-16 01:34 UTC
### What is the problem this feature would solve?

Currently there is no way to exclude extensions from glob, this turns into a bit of a mess when you have a glob like `**/*.{ts,tsx,js,jsx}` and you are compiling your code using `tsc` or people using your code are compiling js, because, extensions like `.d.ts` will also be returned and you have to manually check for those

### What is the feature you are proposing to solve the problem?

Something among the lines of `new Bun.Glob(patterns, { ignorePatterns: Array<patterns> })`

### What alternatives have you considered?

Other alternatives could also be added but this is the first that came to mind

**Comment by Electroid** [comment] 2024-01-16 16:07
Duplicate of #8182

**Closed as not planned by Electroid** 2024-01-16 16:07 UTC
Labels: enhancement, bun.js
