### ISSUE TITLE
Repl crashes immediately on macOS

### ISSUE THREAD

**Issue by ItsRealmy** [oven-sh/bun#12229] opened 2024-06-28 13:57 UTC
### How can we reproduce the crash?

Run `bun repl` on macOS Sonoma 14.5, on a MacBook Pro with M3 Pro. It crashes immediately upon running the command.

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on macos aarch64 [BunxCommand]

Bus error at address 0x10389DBE0

- *2 unknown/js code*
- `src.cli.bunx_command.BunxCommand.getBinNameFromTempDirectory`
- `src.cli.Cli.start`
- `_mh_execute_header`
- *2 unknown/js code*

**Comment by Jarred-Sumner** [comment] 2024-06-28 22:24
Duplicate of #12070

**Comment by Jarred-Sumner** [comment] 2024-06-28 22:25
Fixed in #12071, please run `bun upgrade`

**Closed as not planned by Jarred-Sumner** 2024-06-28 22:25 UTC
Labels: crash, macOS
