### ISSUE TITLE
error: script "dev" was terminated by signal SIGABRT

### ISSUE THREAD

**Issue by warcayac** [oven-sh/bun#9038] opened 2024-02-21 21:03 UTC
### What version of Bun is running?

1.0.28

### What platform is your computer?

Linux 6.7.5-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

1. start server: `bun run dev`
2. make a GET request for:  `http://localhost:3001/`
3. wait for some seconds

### What is the expected behavior?

running server without any unexpected errors

### What do you see instead?

```
$ bun run dev
$ NODE_ENV=development bun --env-file=.env run --watch src/index.tsx
🦊 Elysia is running at localhost:3001
2024-02-21T20:34:10.720Z | GET / - 200 (7.45 ms) 
2024-02-21T20:34:10.756Z | GET /public/output.css - 200 (3.46 ms) 
error: script "dev" was terminated by signal SIGABRT (Abort)
[1]    12585 IOT instruction (core dumped)  bun run dev
```

### Additional information

This is a new Elysia project which use Typescript, React, Htmx and Tailwind. My previous projects working with Elysia and Typescript run OK, the only difference in this project is I'm trying these packages: tailwindcss, drizzle-orm. I've configured Tailwind according to [its doc](https://tailwindcss.com/docs/installation).

My project is in this repo: [https://github.com/warcayac/elysia-htmx-tailwind_demo1](https://github.com/warcayac/elysia-htmx-tailwind_demo1)

**Comment by Electroid** [comment] 2024-02-21 21:04
Duplicate of #9031

**Closed as not planned by Electroid** 2024-02-21 21:04 UTC
Labels: bug, crash

**Comment by warcayac** [comment] 2024-02-23 12:35
In my case I found this error appears when using **@elysiajs/static** package.
