### ISSUE TITLE
Windows ARM64 bun build

### ISSUE THREAD

**Issue by brrock** [oven-sh/bun#15970] opened 2024-12-23 20:29 UTC
### What is the problem this feature would solve?

With the number of new copilot plus snapdragon cpus rolling out it would be nice to let ARM64 Windows users also have support 

### What is the feature you are proposing to solve the problem?

Add windows ARM64 support in bun build

**Comment by Jarred-Sumner** [comment] 2024-12-23 20:37
Duplicate of #9824

**Closed as duplicate by Jarred-Sumner** 2024-12-23 20:37 UTC
Labels: enhancement
