### ISSUE TITLE
Accessing sqlite db results in crash - "Segmentation fault at address 0x0"

### ISSUE THREAD

**Issue by crtr-luke** [oven-sh/bun#14462] opened 2024-10-10 09:26 UTC
### Relevant log output

2024-10-10T09:49:22: ============================================================
2024-10-10T09:49:22: Bun v1.1.30 (7996d06b) Linux x64
2024-10-10T09:49:22: Linux Kernel v4.15.0 | glibc v2.27
2024-10-10T09:49:22: CPU: sse42 popcnt avx avx2 avx512
2024-10-10T09:49:22: Args: "/home/#####/.bun/bin/bun" "/home/#####/###-############.####.###/index.ts"
2024-10-10T09:49:22: Features: dotenv fetch http_server jsc tsconfig
2024-10-10T09:49:22: Builtins: "bun:main" "bun:sqlite" "node:fs/promises"
2024-10-10T09:49:22: Elapsed: 147053ms | User: 47ms | Sys: 27ms
2024-10-10T09:49:22: RSS: 1.07GB | Peak: 47.25MB | Commit: 1.07GB | Faults: 0
2024-10-10T09:49:22:
2024-10-10T09:49:22: panic(main thread): Segmentation fault at address 0x0
2024-10-10T09:49:22: oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Stack Trace (bun.report)

Bun v1.1.30 ([`7996d06`](<https://github.com/oven-sh/bun/tree/7996d06b8f5869ccc9ad9a421cd06469da4273fc>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x00000000

- [`sqlite3.c:39643`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/sqlite/sqlite3.c#L39643>): `unixLock`
- [`sqlite3.c:25840`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/sqlite/sqlite3.c#L25840>): `sqlite3PagerSharedLock`
- [`sqlite3.c:73349`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/sqlite/sqlite3.c#L73349>): `btreeBeginTrans`
- [`sqlite3.c:73839`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/sqlite/sqlite3.c#L73839>): `sqlite3InitOne`
- [`sqlite3.c:141093`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/sqlite/sqlite3.c#L141093>): `sqlite3LocateTable`
- [`sqlite3.c:121060`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/sqlite/sqlite3.c#L121060>): `selectExpander`
- [`sqlite3.c:106067`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/sqlite/sqlite3.c#L106067>): `sqlite3WalkSelect`
- [`sqlite3.c:148069`](<https://github.com/oven-sh/bun/blob/7996d06b8f5869ccc9ad9a421cd06469da4273fc/src/bun.js/bindings/sqlite/sqlite3.c#L148069>): `sqlite3SelectPrep`

Features: dotenv, fetch, http\_server, jsc, tsconfig

**Comment by crtr-luke** [comment] 2024-10-10 09:26
Reverting to v1.1.29 stops the crash from happening.

**Comment by nektro** [comment] 2024-10-30 01:54
duplicate of https://github.com/oven-sh/bun/issues/14442

**Closed as completed by nektro** 2024-10-30 01:54 UTC
Labels: crash, linux
