### ISSUE TITLE
bug: bun run rsbuild api crash

### ISSUE THREAD

**Issue by veaba** [oven-sh/bun#15106] opened 2024-11-12 16:11 UTC
### How can we reproduce the crash?

- rsbuild api: https://rsbuild.dev/api/start/index

```js
// app.mjs

import { createRsbuild } from '@rsbuild/core'

const startDev = async () => {
  const rsbuild = await createRsbuild({
    rsbuildConfig: {
      root: './',
      environments: {
        web: {
          source: {
            entry: {
              index: './src/renderer/src/main.tsx'
            }
          },
        }
      }
    }
  })

  const server = await rsbuild.startDevServer()
  console.log('server=>', server)
 
}

startDev()

```

- use `bun run ` command

```shell
bun run app.mjs
```

![Image](https://github.com/user-attachments/assets/4bd3ca36-c901-4ba4-815e-23c67e61a839)

node is working.

### Relevant log output

```shell
log

Bun v1.1.34 (5e5e7c60) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\Veaba\.bun\bin\bun.exe" ".\run-script-main.mjs"
Features: Bun.stdin(2) http_server jsc transpiler_cache(11) tsconfig(2) 
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:inspector" 
Elapsed: 308ms | User: 62ms | Sys: 15ms
RSS: 0.49GB | Peak: 0.49GB | Commit: 0.65GB | Faults: 122145

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`JSCellInlines.h:243`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSCellInlines.h#L243>): `JSC::JSCell::isString`

Features: Bun.stdin, bunfig, http\_server, jsc, spawn, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5615604075/">BUN-29T</a></strong></sub>

**Comment by nektro** [comment] 2024-11-13 01:41
duplicate of https://github.com/oven-sh/bun/issues/11628

**Closed as not planned by nektro** 2024-11-13 01:41 UTC
Labels: crash, windows, runtime
