### ISSUE TITLE
Worker bug

### ISSUE THREAD

**Issue by AkioSarkiz** [oven-sh/bun#14527] opened 2024-10-13 00:23 UTC
### Stack Trace (bun.report)

Bun v1.1.30 ([`7996d06`](<https://github.com/oven-sh/bun/tree/7996d06b8f5869ccc9ad9a421cd06469da4273fc>)) on macos aarch64 [RunCommand]

Segmentation fault at address 0x41413B4F41416134

- *1 unknown/js code*
- `src.http.HTTPClientResult.Callback.New`
- `src.http.HTTPClientResult.Callback.New`
- `src.http.progressUpdate__anon_189130`
- `src.http.handleOnDataHeaders__anon_189139`
- `src.deps.uws.NewSocketHandler`
- `ssl_on_data`
- `us_internal_dispatch_ready_poll`
- `us_loop_run_bun_tick`
- `src.http.HTTPThread.processEvents`

Features: workers\_spawned, workers\_terminated, dotenv, fetch, jsc, transpiler\_cache, tsconfig

**Comment by nstfkc** [comment] 2024-11-10 15:05
Do you have a reproduction? I am having the same issue but I am not able to reproduce it in a sandbox.

**Comment by Jarred-Sumner** [comment] 2024-12-23 18:01
Strongly suspect this is #15964, a worker is closing while the fetch() is in progress

**Closed as duplicate by Jarred-Sumner** 2024-12-23 18:01 UTC
Labels: crash, macOS, Worker
