### ISSUE TITLE
Properly resolve `"extends"` in tsconfig.json

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5337] opened 2023-09-14 03:14 UTC
In my `tsconfig.json` file:
```json
{
  "extends": "@package-org/package/tsconfig.json",
  // ...
}
```

bun logs the following warning to stderr. It can't find the file because it attempts to resolve it as a relative path instead of using the node resolution algorithm (e.g., by prepending `node_modules/`, which is where the actual target file is located)
```
warn: FileNotFound loading tsconfig.json extends "/path/to/project/root/@package-org/package/tsconfig.json"
```

_Originally reported on Discord: [`tsconfig.json "extends" file from node_modules`](https://discord.com/channels/876711213126520882/1151703355463303199/1151703355463303199)_

**Comment by colinhacks** [comment] 2023-09-14 03:32
Oops duplicate of https://github.com/oven-sh/bun/issues/5277

For a workaround, provide a relative path to the tsconfig.json being extended:

```ts
  "extends": "./node_modules/@package-org/package/tsconfig.json",
```

**Closed as completed by colinhacks** 2023-09-14 03:32 UTC
Labels: bug
