### ISSUE TITLE
Bun doesn't keep alive setInterval

### ISSUE THREAD

**Issue by LiberaTeMetuMortis** [oven-sh/bun#988] opened 2022-08-05 08:46 UTC
### Version

0.1.6

### Platform

Linux metumortis-monster 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Try using setInterval

### How often does it reproduce? Is there a required condition?

You shouldn't have any other thing than intervalto keep alive your process. 

### What do you see instead?

The process dead.

**Comment by xhyrom** [comment] 2022-08-07 05:16
Duplicate of https://github.com/oven-sh/bun/issues/506

**Closed as not planned by xhyrom** 2022-08-07 05:16 UTC
Labels: bug, needs repro
