### ISSUE TITLE
Bunx doesn't work with Prisma

### ISSUE THREAD

**Issue by iamnobodysir** [oven-sh/bun#6799] opened 2023-10-30 12:46 UTC
### What version of Bun is running?

1.0.7

### What platform is your computer?

Ubuntu x86

### What steps can reproduce the bug?

Don't install NodeJS in your OS. You can try WSL.

Do "bunx prisma migrate dev" or other command won't work. Need NodeJS installed to work the command.

**Comment by Electroid** [comment] 2023-10-30 17:51
Duplicate of #4848

**Closed as not planned by Electroid** 2023-10-30 17:51 UTC
Labels: bug
