### ISSUE TITLE
PR #7666 - breaks packages like dotenv

### ISSUE THREAD

**Issue by TiBianMod** [oven-sh/bun#8003] opened 2024-01-05 18:11 UTC
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

here I have a simple example using `dotenv` to load environment variables from `env_path` dir.

```ts
import dotenv from "dotenv";

const envPath = "./env_path/.env";
const envs = `NODE_ENV=prod
APP_KEY=key_123
APP_DEBUG=true
PORT=3000
`;

await Bun.write(envPath, envs);

const result = dotenv.config({
    path: envPath,
});

if (result.error) {
    throw result.error;
}

console.log("# Parsed ENVs from dotenv #");
console.log(result.parsed);
console.log("#---------------------------------------------------------------#");
console.log("NODE_ENV:", process.env.NODE_ENV);
console.log("APP_KEY:", process.env.APP_KEY);
console.log("APP_DEBUG:", process.env.APP_DEBUG);
console.log("PORT:", process.env.PORT);
```

> make `index.ts` for example and run `bun index.ts`

### What is the expected behavior?

The expected behavior is, packages like `dotenv` to work and have the opportunity to set the `NODE_ENV` var.

> https://github.com/oven-sh/bun/issues/7829
> personally, I don't mind the default `NODE_ENV` to be `development`, but we need to make sure packages like `dotenv` to work

### What do you see instead?

`NODE_ENV` is always set to `development`

![CleanShot 2024-01-05 at 18 31 28](https://github.com/oven-sh/bun/assets/6713842/bfec1e04-8531-4501-9731-436f82d5fc10)

### Additional information

The `NODE_ENV` behavior, breaks on version `1.0.19` from PR #7666

![CleanShot 2024-01-05 at 18 29 45](https://github.com/oven-sh/bun/assets/6713842/1f028773-193e-43e1-b02c-4d49274e3077)

**Comment by Electroid** [comment] 2024-01-08 17:12
Duplicate of #7829

**Closed as not planned by Electroid** 2024-01-08 17:12 UTC
Labels: bug

**Comment by TiBianMod** [comment] 2024-01-08 19:42
lol

**Comment by Electroid** [comment] 2024-01-08 19:44
@TiBianMod In Bun v1.1, we plan on fixing that issue, which would fix this issue as well. Ignore the "not planned" from Github, as not planned also includes "duplicate" for some reason.
