### ISSUE TITLE
Debugging in VS Code for Windows not works

### ISSUE THREAD

**Issue by Filyus** [oven-sh/bun#10250] opened 2024-04-13 17:54 UTC
### What version of Bun is running?

1.1.3+7b5065c1c

### What platform is your computer?

Microsoft Windows NT 10.0.19042.0 x64

### What steps can reproduce the bug?

1. Install Bun for Windows
2. Install VS Code extension "Bun for Visual Studio Code"
3. Create launch.json with standard Bun configuration
4. Trying to run or debug with the created commands

### What is the expected behavior?

Proper start or debug session

### What do you see instead?

Immediately stop with a following error:
```
Failed to start inspector:
 40 |     },
41 |     close: () => {
42 |       writer.close(), pendingMessages.length = 0;
43 |     }
44 |   };
45 | }, parseUrl = function(input) {
                                                 ^
TypeError: "ws+unix://C:\Users\Filyus\AppData\Local\Temp\4m9b6onv4e.sock?wait=1" cannot be parsed as a URL.
      at internal:debugger:45:45
      at new Debugger (internal:debugger:124:27)
      at internal:debugger:100:25
```

### Additional information

Debugging with a command line and a browser works, but I don't fun of using it.

**Comment by Electroid** [comment] 2024-04-15 16:17
Duplicate of #8851

**Closed as not planned by Electroid** 2024-04-15 16:17 UTC
Labels: bug

**Comment by vvhellohivv** [comment] 2024-04-20 14:39
me too
