### ISSUE TITLE
missing asset file crash on bun build with wasm file

### ISSUE THREAD

**Issue by happy-turtle** [oven-sh/bun#6437] opened 2023-10-12 08:36 UTC
### What version of Bun is running?

1.0.5+1bf28e0d77a8b2261befbdb708cefd03e0126960

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Run `bun build index.ts` with the following index.ts:
```
import wasmModule from 'pkg/my-wasm.wasm'

console.log(wasmModule)
```

### What is the expected behavior?

bun build should run successfully and import the .wasm file as an asset as stated in the documentation. https://bun.sh/docs/bundler#content-types

### What do you see instead?

uh-oh: Internal error: missing asset file
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.5 (1bf28e0d) Linux x64 #1 SMP Fri Jan 27 02:56:13 UTC 2023
BuildCommand: 
Elapsed: 92ms | User: 13ms | Sys: 13ms
RSS: 40.92MB | Peak: 28.00MB | Commit: 40.92MB | Faults: 0
----- bun meta -----

0   0x55cbc418ea1b
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

### Additional information

`bun index.ts` is running fine, it outputs the resolved absolute path to the wasm file.

**Comment by Jarred-Sumner** [comment] 2023-12-05 12:43
Duplicate of #3903

**Closed as not planned by Jarred-Sumner** 2023-12-05 12:43 UTC
Labels: bug, crash, wasm
