### ISSUE TITLE
SvelteKit does not work with wrangler/cloudflare adapter?

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#10062] opened 2024-04-08 08:32 UTC
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Linux 6.5.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

Created a repo reprod here:
https://github.com/huseeiin/sveltekit-wrangler-bun-bug-reprod
without --bun (using node) it works just fine

**Comment by Electroid** [comment] 2024-04-08 22:57
Thanks for reporting. Cloned your repo and got:

```js
❯ bun run dev
$ bun --bun vite
12834 |       );
12835 |     }
12836 |     __name(finalizeAndReportTiming, "finalizeAndReportTiming");
12837 |     function markResourceTiming(timingInfo, originalURL, initiatorType, globalThis2, cacheState) {
12838 |       if (nodeMajor > 18 || nodeMajor === 18 && nodeMinor >= 2) {
12839 |         performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState);
                ^
TypeError: performance.markResourceTiming is not a function. (In 'performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState)', 'performance.markResourceTiming' is undefined)
      at markResourceTiming (/Users/ashcon/Desktop/code/sandbox/sveltekit-wrangler-bun-bug-reprod/node_modules/wrangler/wrangler-dist/cli.js:12839:9)
      at finalizeAndReportTiming (/Users/ashcon/Desktop/code/sandbox/sveltekit-wrangler-bun-bug-reprod/node_modules/wrangler/wrangler-dist/cli.js:12828:7)
      at /Users/ashcon/Desktop/code/sandbox/sveltekit-wrangler-bun-bug-reprod/node_modules/wrangler/wrangler-dist/cli.js:12771:109
      at /Users/ashcon/Desktop/code/sandbox/sveltekit-wrangler-bun-bug-reprod/node_modules/wrangler/wrangler-dist/cli.js:13115:44
error: "vite" exited with code 1
error: script "dev" exited with code 1
```

Related: #8867

Is that the same error you ran into? (regardless, it's an error we have to fix)

**Comment by huseeiin** [comment] 2024-04-09 08:40
> Thanks for reporting. Cloned your repo and got:
> 
> ```js
> ❯ bun run dev
> $ bun --bun vite
> 12834 |       );
> 12835 |     }
> 12836 |     __name(finalizeAndReportTiming, "finalizeAndReportTiming");
> 12837 |     function markResourceTiming(timingInfo, originalURL, initiatorType, globalThis2, cacheState) {
> 12838 |       if (nodeMajor > 18 || nodeMajor === 18 && nodeMinor >= 2) {
> 12839 |         performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState);
>                 ^
> TypeError: performance.markResourceTiming is not a function. (In 'performance.markResourceTiming(timingInfo, originalURL.href, initiatorType, globalThis2, cacheState)', 'performance.markResourceTiming' is undefined)
>       at markResourceTiming (/Users/ashcon/Desktop/code/sandbox/sveltekit-wrangler-bun-bug-reprod/node_modules/wrangler/wrangler-dist/cli.js:12839:9)
>       at finalizeAndReportTiming (/Users/ashcon/Desktop/code/sandbox/sveltekit-wrangler-bun-bug-reprod/node_modules/wrangler/wrangler-dist/cli.js:12828:7)
>       at /Users/ashcon/Desktop/code/sandbox/sveltekit-wrangler-bun-bug-reprod/node_modules/wrangler/wrangler-dist/cli.js:12771:109
>       at /Users/ashcon/Desktop/code/sandbox/sveltekit-wrangler-bun-bug-reprod/node_modules/wrangler/wrangler-dist/cli.js:13115:44
> error: "vite" exited with code 1
> error: script "dev" exited with code 1
> ```
> 
> Related: #8867
> 
> Is that the same error you ran into? (regardless, it's an error we have to fix)

yeah sounds like its the same.

**Comment by Electroid** [comment] 2024-04-09 17:26
Duplicate of https://github.com/oven-sh/bun/issues/8867

**Closed as not planned by Electroid** 2024-04-09 17:26 UTC
Labels: bug
