### ISSUE TITLE
Resizable ArrayBuffer reaches memory limit early

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#10248] opened 2024-04-13 17:14 UTC
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
function t() {
    const buff = new ArrayBuffer(102, { maxByteLength: 2 ** 32 });
    return buff.slice(0, Math.floor(Math.random() * 102));
}

t();
t();
t();
t();
t();
t();
t();
t();
t();
t();
t();
t();
t();
t();
t();
// Enable this line to make bun error
// t();
```

### What is the expected behavior?

The expected is to not error.

### What do you see instead?

It runs out of memory

### Additional information

I tested this in node by calling the function like this more than 1000x and it didnt run out of memory.

**Comment by Electroid** [comment] 2024-04-15 16:19
Duplicate of #8000

**Closed as not planned by Electroid** 2024-04-15 16:19 UTC
Labels: bug
