### ISSUE TITLE
Bun crashing when doing node fs/promises file operations (found in package rotating-file-stream)

### ISSUE THREAD

**Issue by christo-sw** [oven-sh/bun#7545] opened 2023-12-09 06:57 UTC
### What version of Bun is running?

1.0.15

### What platform is your computer?

Linux 6.2.0-37-generic x86_64 x86_64 (Ubuntu 22.04 LTS)

### What steps can reproduce the bug?

In an empty directory, run 

```bash
bun add rotating-file-stream ts-node
```
> I was using `rotating-file-stream` `^3.1.1` and `ts-node` `^10.9.2`

then create ```index.ts``` and paste the following:

```typescript
import { createStream } from "rotating-file-stream";

let count = 0;
function nameGenerator() {
  console.log("Name generator running, implying that the log file is rotating");
  return `log/access_${count++}.log`; // The new log file name
}

// Create a rotating file stream, but we're not going to use it
// since the bug is clear without it
createStream(nameGenerator, {
  interval: "5s",
});

// This is just to allow the program to run indefinitely and produce
// output roughly each time the log should be rotated (every 5 seconds)
function loop() {
  setTimeout(() => {
    console.log("Rotation event");
    loop();
  }, 5000);
}

loop();
```

Now, for the bug. Run 

```bash
npx ts-node index.ts
```

and compare it to

```bash
bun run index.ts
```

### What is the expected behavior?

We expect the log to be rotated every five seconds, creating the following console output:

![image](https://github.com/oven-sh/bun/assets/103880515/8c20f6f1-909d-4ee6-a920-0ed0cb900e50)
> Note that the generator sometimes runs more than once initially due to quirks of the package we're using

And when listing the log directory (`ls log`) it should show the following:

![image](https://github.com/oven-sh/bun/assets/103880515/2437bfd3-52e0-4a49-8904-053471fa95e4)

This is in fact what happens when using `ts-node`. 

### What do you see instead?

When using `bun run` to execute `index.ts`, the following output is produced:

![image](https://github.com/oven-sh/bun/assets/103880515/21387a8f-9520-4415-9300-d49b1c7cee91)

In essence, only the first log file is produced and then the rotation never occurs.

### Additional information

I believe I have found roughly where the bug occurs. After going into the `rotating-file-stream` package and doing some classic printf debugging, I found that if I add a `console.log()` statement to the try-catch on line 290 of `node_modules/rotating-file-stream/dist/cjs/index.js` and run it with `Bun`, it produces the following output:

![image](https://github.com/oven-sh/bun/assets/103880515/664117d7-9e7e-4380-823e-3eea8fa68ca0)

The same does not happen when using `ts-node`

My LSP says that the `file` object is of type `fs_1.promises.FileHandle`:

![image](https://github.com/oven-sh/bun/assets/103880515/4957e9e0-846f-4743-a0f6-d92892a97c92)

Which is assigned here:

![image](https://github.com/oven-sh/bun/assets/103880515/93230eec-6665-47f0-8ffd-36c9e6d87240)

I noted that it uses `promises_1` to open the file. I thought this might be some foreign thing that the author created, thus causing this problem. However, upon further inspection, I found that `promises_1` is simply the default export of the `node` `fs/promises` module:

![image](https://github.com/oven-sh/bun/assets/103880515/d9c4fa6b-c7df-4a54-b9a1-ba03d90c4f16)

All in all, this leads me to conclude, from my limited knowledge and understanding of Bun and node, that Bun somehow does not properly implement node's `fs/promises` library. This is quite unfortunate, since I now have no choice but to switch my whole project to node in order to use this module. I hope there is an easy solution to this problem!

**Comment by Jarred-Sumner** [comment] 2023-12-09 07:09
Thank you for the investigative work. I appreciate the time you put into debugging this. The issue is caused by our incomplete FileHandle implementation which is being tracked in #3167 

Closing as duplicate of #3167 

GitHub will say “not planned” but I promise it is planned (just a duplicate)

**Closed as completed by Jarred-Sumner** 2023-12-09 07:09 UTC
Labels: bug

**Comment by christo-sw** [comment] 2023-12-09 07:13
Wow, what a quick response time! Thank you so much @Jarred-Sumner! If I may ask, is there any ETA on when #3167 might be fixed/implemented?

**Comment by Jarred-Sumner** [comment] 2024-01-16 07:22
Fixed in https://github.com/oven-sh/bun/pull/8141
