### ISSUE TITLE
`node:stream` Duplex.toWeb throwing TypeError: undefined is not a function

### ISSUE THREAD

**Issue by flakey5** [oven-sh/bun#6909] opened 2023-11-05 09:07 UTC
### What version of Bun is running?

1.0.8

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

 * Create a Node.js `net.Socket` instance
 * Call `Duplex.toWeb` on it to get a ReadableStream and WritableStream from it

```js
import net from 'node:net';
import { Duplex } from 'node:stream';

const socket = net.connect({
    host: 'gopher.floodgap.com',
    port: 70
});

const { readable, writable } = Duplex.toWeb(socket); // This throws
```

### What do you see instead?

```
3201 |       return webStreamsAdapters;
3202 |     }
3203 |     Duplex.fromWeb = function(pair, options) {
3204 |       return lazyWebStreams().newStreamDuplexFromReadableWritablePair(pair, options);
3205 | 
3206 |     }, Duplex.toWeb = function(duplex) {
                                                               ^
TypeError: undefined is not a function
      at node:stream:3206:60
      at /home/code/connect-demo/src/bun-repro.mjs:9:31
```

### Additional information

The code that errors is here https://github.com/oven-sh/bun/blob/main/src/js/node/stream.js#L4455, it looks to be calling a function on an object that never has any properties. The function it calls doesn't appear to be defined anywhere within the Bun codebase either

**Comment by Electroid** [comment] 2024-02-14 18:22
Duplicate of #3927

**Closed as not planned by Electroid** 2024-02-14 18:22 UTC
Labels: bug, node.js
