### ISSUE TITLE
panic(thread 4048): Expected pretty file path to have only forward slashes, got 'C:\Users\...

### ISSUE THREAD

**Issue by Gustav-Eikaas** [oven-sh/bun#15030] opened 2024-11-07 07:20 UTC
### How can we reproduce the crash?

Looks like a mix of `\` and `/` caused bun to crash.
I tried running the following command `bun build ./src/index.tsx --minify --outfile ../../../dist/index.js`

panic(thread 4048): Expected pretty file path to have only forward slashes, got 'C:\Users\gustav.eikaas\repo\project\s
rc\pages\item\node_modules\@project\inject\dist\index.js'

@project/inject is a workspace project referenced like this `"@project/inject": "workspace:^",`

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [BuildCommand]

**panic**: Expected pretty file path to have only forward slashes, got 'C:\Users\foxxorcat\Documents\ipfs\helia-cli\node_modules\.pnpm\@multiformats+dns@1.0.6\node_modules\hashlru\index.js'

- [`fs.zig:1732`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/fs.zig#L1732>): `assertPrettyIsValid`
- [`bundle_v2.zig:9284`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L9284>): `postProcessJSChunk`
- [`bundle_v2.zig:8174`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bundler/bundle_v2.zig#L8174>): `generateChunk`
- [`atomic.zig:40`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0//opt/homebrew/var/buildkite-agent/builds/darwin-aarch64-studio-2-qmdn5C/bun/bun/vendor/zig/lib/std/atomic.zig#L40>): `load`

Features: define, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5954707159/">BUN-6EX</a></strong></sub>

**Comment by nektro** [comment] 2024-11-08 22:03
duplicate of https://github.com/oven-sh/bun/issues/13897

**Closed as not planned by nektro** 2024-11-08 22:03 UTC
Labels: crash, windows
