### ISSUE TITLE
Top-level await not handled correctly in bun build

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#13418] opened 2024-08-20 06:57 UTC
### What version of Bun is running?

1.1.25-canary.39+5eb053fa3

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

1. Create a file named `foo.ts` with the following contents:
```ts
await import("./foo.ts");
```

This produces the following invalid code:
```js
// @bun
var __esm = (fn, res) => () => (fn && (res = fn(fn = 0)), res);

// foo.ts
var exports_foo = {};
var init_foo = __esm(() => {
  await Promise.resolve().then(() => (init_foo(), exports_foo));
});
init_foo();
```

The `__esm` function is missing an `async`. This is also too much code.

### What is the expected behavior?

It should not throw an error

### Additional information

We need an equivalent of esbuild's `validateTLA` function. `is_async_or_has_async_dependency` is seemingly never set to true

**Comment by huseeiin** [comment] 2024-08-20 09:05
maybe duplicate of #12508?

**Comment by paperdave** [comment] 2024-08-26 20:28
Duplicate.

**Closed as completed by paperdave** 2024-08-26 20:28 UTC
Labels: bug, bundler

**Comment by Jarred-Sumner** [comment] 2024-09-30 23:51
Fixed by @snoglobe in https://github.com/oven-sh/bun/pull/14218
