### ISSUE TITLE
Invariant: Render expects to have requestAsyncStorage

### ISSUE THREAD

**Issue by nyxb** [oven-sh/bun#5784] opened 2023-09-20 06:58 UTC
### What version of Bun is running?

1.0.3+edee1e3d04c80f5301b4eeb8eef2a92a0ed5823c

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

idk install bun latest canary swith the port to any other in next dev and start!?

### What is the expected behavior?

That I see my dev side

### What do you see instead?

<img width="1281" alt="Screenshot 2023-09-20 at 08 58 22" src="https://github.com/oven-sh/bun/assets/98586665/50468994-89a6-482e-acfc-d14896b7c2f3">

### Additional information

thats the fail: 

```
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
0 && (module.exports = {
    deserializeErr: null,
    invokeIpcMethod: null
});
function _export(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name]
    });
}
_export(exports, {
    deserializeErr: function() {
        return deserializeErr;
    },
    invokeIpcMethod: function() {
        return invokeIpcMethod;
    }
});
const _utils = require("../../../shared/lib/utils");
const _invokerequest = require("./invoke-request");
const deserializeErr = (serializedErr)=>{
    if (!serializedErr || typeof serializedErr !== "object" || !serializedErr.stack) {
        return serializedErr;
    }
    let ErrorType = Error;
    if (serializedErr.name === "PageNotFoundError") {
        ErrorType = _utils.PageNotFoundError;
    }
    const err = new ErrorType(serializedErr.message);
    err.stack = serializedErr.stack;
    err.name = serializedErr.name;
    err.digest = serializedErr.digest;
    if (process.env.NEXT_RUNTIME !== "edge") {
        const { decorateServerError  } = require("next/dist/compiled/@next/react-dev-overlay/dist/middleware");
        decorateServerError(err, serializedErr.source || "server");
    }
    return err;
};
async function invokeIpcMethod({ fetchHostname ="localhost" , method , args , ipcPort , ipcKey  }) {
    if (ipcPort) {
        const res = await (0, _invokerequest.invokeRequest)(`http://${fetchHostname}:${ipcPort}?key=${ipcKey}&method=${method}&args=${encodeURIComponent(JSON.stringify(args))}`, {
            method: "GET",
            headers: {}
        });
        const body = await res.text();
        if (body.startsWith("{") && body.endsWith("}")) {
            const parsedBody = JSON.parse(body);
            if (parsedBody && typeof parsedBody === "object" && "err" in parsedBody && "stack" in parsedBody.err) {
                throw deserializeErr(parsedBody.err);
            }
            return parsedBody;
        }
    }
}

//# sourceMappingURL=request-utils.js.map
```

**Comment by Electroid** [comment] 2023-09-20 16:44
It's hard to figure out where the issue is happening from that code.

**Comment by 1eldiego** [comment] 2023-09-20 21:29
Kind of the same error happens to me:

` ⨯ error: Invariant: Render expects to have requestAsyncStorage, none found`

This is a fresh install of nextjs using bunx create-next-app@latest, all defaults. I'm using Ubuntu in WSL2 (also a fresh install, so no node or any package installed other than bun). Bun is v1.0.2.

Start the server with `bun dev` and then modify some text from the example page.tsx and this error pops up. The page localhost:3000 must be open in the browser tho, otherwise there's no error.

**Comment by cdecompilador** [comment] 2023-09-20 21:53
same error here

**Comment by The-Code-Monkey** [comment] 2023-09-21 08:09
Getting this same error on mac.

Its failing at 

```
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
0 && (module.exports = {
    deserializeErr: null,
    invokeIpcMethod: null
});
function _export(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: true,
        get: all[name]
    });
}
_export(exports, {
    deserializeErr: function() {
        return deserializeErr;
    },
    invokeIpcMethod: function() {
        return invokeIpcMethod;
    }
});
const _utils = require("../../../shared/lib/utils");
const _invokerequest = require("./invoke-request");
const deserializeErr = (serializedErr)=>{
    if (!serializedErr || typeof serializedErr !== "object" || !serializedErr.stack) {
        return serializedErr;
    }
    let ErrorType = Error;
    if (serializedErr.name === "PageNotFoundError") {
        ErrorType = _utils.PageNotFoundError;
    }
    const err = new ErrorType(serializedErr.message);
    err.stack = serializedErr.stack;
    // Fails at the line above
    err.name = serializedErr.name;
    err.digest = serializedErr.digest;
    if (process.env.NEXT_RUNTIME !== "edge") {
        const { decorateServerError  } = require("next/dist/compiled/@next/react-dev-overlay/dist/middleware");
        decorateServerError(err, serializedErr.source || "server");
    }
    return err;
};
```

**Comment by hlxdev** [comment] 2023-09-21 23:36
Any update? I have the same problem (using WSL)

**Comment by ericklarsen** [comment] 2023-09-23 11:39
same error here, 
![image](https://github.com/oven-sh/bun/assets/32609329/8ec468ea-2ed8-423d-825c-0932641a707f)

**Comment by Electroid** [comment] 2023-09-23 16:09
Looks like this is an error in Next.js, when used in Bun. Not sure yet of the cause.

https://github.com/vercel/next.js/blob/19f2fe45ad9b642fbf05079c89f1cc174a533e2e/packages/next/src/server/app-render/app-render.tsx#L273-L278

**Comment by kayandra** [comment] 2023-09-27 15:17
I had this same issue because i tried to use turbopack with nextjs via the `next dev --turbo`... the way i temporarily solved the problem was by removing node modules and .next directory. then disabling turbopack.

**Comment by Jarred-Sumner** [comment] 2023-09-28 10:55
Fixed by @paperdave in https://github.com/oven-sh/bun/pull/6095

**Closed as completed by Jarred-Sumner** 2023-09-28 10:55 UTC
Labels: bug, node.js
