### ISSUE TITLE
Bun Bundler: Generate d.ts 

### ISSUE THREAD

**Issue by itsezc** [oven-sh/bun#12877] opened 2024-07-27 14:36 UTC
### What is the problem this feature would solve?

Currently the Bun Bundler does not generate `d.ts` files from entryPoints

### What is the feature you are proposing to solve the problem?

Create a new option `generateDeclarations` or based on `tsconfig.json` (`declarations`), generate `d.ts` files

**Comment by paperdave** [comment] 2024-07-30 06:42
duplicate of 5141

**Closed as not planned by paperdave** 2024-07-30 06:42 UTC
Labels: enhancement
