### ISSUE TITLE
TypeError: FormData parse error missing final boundary in SolidStart

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#10789] opened 2024-05-03 10:38 UTC
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Linux 6.5.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

https://github.com/huseeiin/bun-sld-pwd
you have to submit any of the forms in the index page to see the error.

### What is the expected behavior?

for the FormData to be parsed correctly.

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/122984423/59bb86cf-1726-4078-98aa-d676f7130b96)

### Additional information

**important detail**: it works in prod for some reason
```bash
bun --bun run build
bun .output/server/index.mjs
```

**Comment by huseeiin** [comment] 2024-05-03 10:40
you have to submit any of the forms in the index page to see the error.

**Comment by Electroid** [comment] 2024-05-04 15:57
Duplicate of #2644

**Closed as completed by Electroid** 2024-05-04 15:57 UTC
Labels: bug
