### ISSUE TITLE
 code: "ERR_INVALID_ARG_TYPE" running Bun on Namecheap Webuzo ubuntu

### ISSUE THREAD

**Issue by Akumzy** [oven-sh/bun#11372] opened 2024-05-26 14:18 UTC
### What version of Bun is running?

Bun v1.1.10 (Linux x64 baseline)

### What platform is your computer?

Linux 5.15.0-107-generic x86_64 x86_64

### What steps can reproduce the bug?
```ts
Bun.serve({
  fetch(req: Request): Response | Promise<Response> {
    return new Response("Hello World!");
  },

  // Optional port number - the default value is 3000
  port: process.env.PORT || 3000,
});
```

### What is the expected behavior?

Just run

### What do you see instead?
```log
 | Bun.serve({
    ^
TypeError: 湕捩摯潨瑳慮敭⁳畭瑳愠牬慥祤戠湥潣敤潦⁲潮⹷渊睥唠䱒椨灮瑵⸩潨瑳慮敭猠潨汵潤琠敨琠楲正.慢敳剕⁉慣❮⁴慨敶愠甠敳湲浡牯瀠獡睳牯d畢彮敶獲潩灮慬晴牯晭慲敭潷歲牦浡睥牯彫敶獲潩䥮癮污摩
 code: "ERR_INVALID_ARG_TYPE"

      at /home/nebor/github/test.ts:1:1

Bun v1.1.10 (Linux x64 baseline)
```

**Comment by yus-ham** [comment] 2024-05-26 15:40
duplicate of #3312

**Comment by Akumzy** [comment] 2024-05-26 15:41
> duplicate of #3312

it's closed and non of the suggestions works

**Comment by Electroid** [comment] 2024-05-27 16:16
I re-opened the issue.

**Comment by Electroid** [comment] 2024-05-27 16:17
Duplicate of https://github.com/oven-sh/bun/issues/3312

**Closed as not planned by Electroid** 2024-05-27 16:17 UTC
Labels: bug
