### ISSUE TITLE
provide FreeBSD port

### ISSUE THREAD

**Issue by lucarinaorg** [oven-sh/bun#4940] opened 2023-09-11 12:44 UTC
### What is the problem this feature would solve?

on FreeBSD the command:
#pkg install bun
does not provide bun installed

### What is the feature you are proposing to solve the problem?

provide a working port

### What alternatives have you considered?

drop Javascript forever and migrate to Ada for web development

**Comment by Electroid** [comment] 2023-10-27 20:39
Duplicate of #1524

**Closed as not planned by Electroid** 2023-10-27 20:39 UTC
Labels: enhancement
