### ISSUE TITLE
[BUG] Using in Bun `form-data-encoder` with `undici` throw errors, but it works fine in NodeJS

### ISSUE THREAD

**Issue by kravetsone** [oven-sh/bun#8750] opened 2024-02-07 09:36 UTC
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
// client.ts
import { FormDataEncoder } from "form-data-encoder";
import { fetch } from "undici";
const formData = new FormData();

formData.set(
	"file",
	new File(["test"], "test.txt", {
		type: "text/plain",
	}),
);

const enc = new FormDataEncoder(formData);
const res = await fetch("http://localhost:3555", {
	method: "POST",
	headers: enc.headers,
	body: enc.encode(),
});
```

```ts
// server.ts (tested not only with Elysia)
import { Elysia, t } from "elysia";

new Elysia()
	.post(
		"/",
		({ body: { file } }) => {
			console.log(file);
		},
		{
			body: t.Object({
				file: t.File(),
			}),
		},
	)
	.listen(3555, console.log);
```

```bash
kravets@KravetsBook:/mnt/z/PROJECTS/some-tests/nodefetch$ bunx tsx test/client.ts 
/mnt/z/PROJECTS/some-tests/nodefetch/node_modules/undici/index.js:103
      Error.captureStackTrace(err, this)
            ^

TypeError: RequestInit: duplex option is required when sending a body.
    at fetch (/mnt/z/PROJECTS/some-tests/nodefetch/node_modules/undici/index.js:103:13)
    at <anonymous> (/mnt/z/PROJECTS/some-tests/nodefetch/test/client.ts:14:13)

Node.js v20.10.0
kravets@KravetsBook:/mnt/z/PROJECTS/some-tests/nodefetch$ bun test/client.ts
{
  name: "Error",
  message: "FormData missing final boundary",
}
kravets@KravetsBook:/mnt/z/PROJECTS/some-tests/nodefetch$
```

When i set duplex to half

```ts
const res = await fetch("http://localhost:3555", {
	method: "POST",
	headers: enc.headers,
	body: enc.encode(),
	duplex: "half",
});

```

```bash
kravets@KravetsBook:/mnt/z/PROJECTS/some-tests/nodefetch$ bun test/client.ts
{
  name: "Error",
  message: "FormData missing final boundary",
}
kravets@KravetsBook:/mnt/z/PROJECTS/some-tests/nodefetch$ bunx tsx test/client.ts
{ message: 'ok!' }
```

**Comment by Electroid** [comment] 2024-02-07 18:09
Duplicate of #2644

**Closed as not planned by Electroid** 2024-02-07 18:09 UTC
Labels: bug

**Comment by kravetsone** [comment] 2024-02-07 18:14
> Duplicate of #2644

not exactly...

- duplex option behaviour
- and it's client bug!
- usage of form-data-encoder and udici

**Comment by Electroid** [comment] 2024-02-07 19:47
The root cause in Bun's `FormData` is the same. We don't support `duplex` in `fetch()`, will make that a seperate issue.
