### ISSUE TITLE
Bun.file arrayBuffer crash

### ISSUE THREAD

**Issue by CeebDev** [oven-sh/bun#7246] opened 2023-11-21 09:44 UTC
### What version of Bun is running?

1.0.13

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```ts
const img = Bun.file(path.resolve("./src/assets/test.jpg"))
console.log("Loaded test.jpg")
const buff = await img.arrayBuffer()
    .catch(err => console.log(err))
```

### What is the expected behavior?

Create the arrayBuffer from the image

### What do you see instead?

```
$ bun src/index.ts
Loaded test.jpg
error: script "start" exited with code 1 (SIGHUP)
```

It log my console.log but not the error and script exit

### Additional information

I dont know if i am doing wrong
File path is good because img.size return the good value

**Comment by Electroid** [comment] 2023-11-21 22:24
Likely a duplicate of #5960

**Closed as not planned by Electroid** 2023-11-21 22:24 UTC
Labels: bug, bun.js
