### ISSUE TITLE
Bun throws "Illegal instruction (core dumped)" on install

### ISSUE THREAD

**Issue by Andrmist** [oven-sh/bun#555] opened 2022-07-10 21:19 UTC
### Version

0.1.2

### Platform

Linux AndrComp 5.15.48-1-lts #1 SMP Thu, 16 Jun 2022 13:32:35 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

I tried to install using shell script on https://bun.sh/install (I'm using `zsh`, but `bash` doesn't work too)

### What do you see instead?

It fails on line 110: 
```bash
$ curl -fsSL https://bun.sh/install | bash
######################################################################## 100.0%
Bun was installed successfully to /home/master/.bun/bin/bun
bash: line 110: 142279 Illegal instruction     (core dumped) IS_BUN_AUTO_UPDATE="true" $exe completions > /dev/null 2>&1
Run 'bun --help' to get started
```
I tried to run help page, but it failed partly:
```bash
$ bun --help
	   --use <STR>[1]    142417 illegal hardware instruction (core dumped)  bun --help
```

### Additional information

I'm using `zsh 5.9`, `oh my zsh` for plugins and themes

**Comment by FinnRG** [comment] 2022-07-10 23:12
Duplicate of #67. Look here for further instructions: https://github.com/oven-sh/bun#illegal-instruction-core-dumped.

**Closed as completed by FinnRG** 2022-07-10 23:12 UTC
