### ISSUE TITLE
Issue with using bun and rsbuild in docker

### ISSUE THREAD

**Issue by kfiku** [oven-sh/bun#13749] opened 2024-09-05 14:14 UTC
### How can we reproduce the crash?

Here is repo that you can test the issue: https://github.com/kfiku/bun.sh-rsbuild-error

you will need docker installed, and then:

```sh
./run.sh
```

### Stack Trace (bun.report)

Bun v1.1.26 ([`0a37423`](<https://github.com/oven-sh/bun/tree/0a37423bafab6aebe803e5f1594cffa9796f2ae6>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/ld-temp.o#L0>): `JSC::runJSMicrotask`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`BunProcess.cpp:2665`](<https://github.com/oven-sh/bun/blob/0a37423bafab6aebe803e5f1594cffa9796f2ae6/src/bun.js/bindings/BunProcess.cpp#L2665>): `Bun::jsFunctionDrainMicrotaskQueue`

**Comment by Jarred-Sumner** [comment] 2024-09-06 20:51
Duplicate of #11628

**Comment by Jarred-Sumner** [comment] 2024-09-06 20:51
We are tracking this in #11628 - please follow along there.

**Closed as not planned by Jarred-Sumner** 2024-09-06 20:51 UTC
Labels: crash, linux
