### ISSUE TITLE
Using Playwright to connect to a Browserless instance never connects

### ISSUE THREAD

**Issue by stauersbol** [oven-sh/bun#9223] opened 2024-03-03 16:57 UTC
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Linux 6.7.6-arch1-2 x86_64 unknown

### What steps can reproduce the bug?

1. Create bun project
2. Run browserless in a local docker container, using `ghcr.io/browserless/chromium:latest`
3. install playwright
4. use example code from: https://www.browserless.io/docs/playwright#javascript-playwright
5. run file with `bun run index.js`
6. Connection hangs

### What is the expected behavior?

With the example code it should create a screenshot of `example.com` and save it to the project folder.

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/9026132/0af52771-d626-4db3-a3d5-790fa95ab829)
Running with node first, to indicate the expected behaviour

![image](https://github.com/oven-sh/bun/assets/9026132/f18af464-cd43-4c39-ae89-b9339e264e25)
Running with bun run index.js, and it never proceeds, (essentially the script never exits until after a timeout or when you terminate the process yourself)

### Additional information

The connection when you use `pw.chromium.connect()` is a WebSocket connection, but it sends a HTTP request instead:
`browserless.io:error No route or file found for resource GET: /playwright/chromium +14m`, which is incorrect, as that is not a HTTP route but a WebSocket endpoint.

**Comment by Electroid** [comment] 2024-04-09 16:56
Duplicate of #9223

**Closed as not planned by Electroid** 2024-04-09 16:56 UTC
Labels: bug

**Comment by stauersbol** [comment] 2024-04-09 16:59
> Duplicate of #9223

Just a question, I know this is closed, but why did you mark it as duplicate of the ticket itself?

**Comment by odylewski** [comment] 2024-05-05 01:15
I just faced exactly the same issue on Bun `v1.1.7` and browserless `v2.8.0`.

@Electroid would you be able to link the right ticket? It looks like a problem with how Bun handles websocket connections.

**Comment by iSuslov** [comment] 2024-11-25 07:44
@Electroid you marked this issue as a duplicate of itself. Please edit your message and link it to the real duplicate

> Duplicate of [#9223](https://github.com/oven-sh/bun/issues/9223)
