### ISSUE TITLE
Segmentation Fault After Bun Upgrade to version 16

### ISSUE THREAD

**Issue by Yummy-Yums** [oven-sh/bun#12124] opened 2024-06-24 15:32 UTC
### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on linux x86_64 [BunxCommand]

Segmentation fault at address 0x56C0A9C9372F

- `??`
- [`semver.zig:268`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/semver.zig#L268>): `src.cli.bunx_command.BunxCommand.exec`
- [`StandaloneModuleGraph.zig:677`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/StandaloneModuleGraph.zig#L677>): `src.cli.Cli.start`
- [`array_list.zig:0`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/deps/zig/lib/std/array_list.zig#L0>): `process.argsAlloc`

**Comment by Yummy-Yums** [comment] 2024-06-24 15:33
how does one downgrade bun ?

**Comment by Jarred-Sumner** [comment] 2024-06-24 20:09
Duplicate of #12070

**Comment by Jarred-Sumner** [comment] 2024-06-24 20:10
Fixed in #12071 

To get the fix now, run `bun upgrade --canary`

**Closed as not planned by Jarred-Sumner** 2024-06-24 20:10 UTC
Labels: crash, linux
