### ISSUE TITLE
bun install Crash

### ISSUE THREAD

**Issue by netokey** [oven-sh/bun#10962] opened 2024-05-10 00:14 UTC
### How can we reproduce the crash?

Just execute "bun install" in 'ui' folder of repo https://github.com/stitionai/devika?tab=readme-ov-file

### Relevant log output

```shell
D:\Code\devika\ui>bun install
bun install v1.1.7 (b0b7db5c)
  🔒 Saving lockfile... ============================================================
Bun v1.1.7 (b0b7db5c) Windows x64
Args: "bun", "install"
Elapsed: 1708ms | User: 46ms | Sys: 93ms
RSS: 58.80MB | Peak: 58.80MB | Commit: 98.47MB | Faults: 14563

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.7/wi1b0b7db5AAgin5L+7yuIwkz1F+oiCm7vwH05v3Dg3+jEo2+iE8pvvFq4kBA0eNrzzCtJLcpLzFFILC5OLSrJzM9TSEvMzCktSgUAiSkKPg
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`debug.zig:348`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L348): `panic`
- [`output.zig:356`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/output.zig#L356): `panic`
- [`bun.zig:3159`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L3159): `assertionFailure`
- [`lockfile.zig:4883`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/lockfile.zig#L4883): `save`
- [`lockfile.zig:1643`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/lockfile.zig#L1643): `saveToDisk`
- [`install.zig:10880`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/install.zig#L10880): `installWithManager`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1440`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L1440): `start`
- [`cli.zig:62`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L62): `start`

**Comment by dylan-conway** [comment] 2024-05-13 21:33
Duplicate of https://github.com/oven-sh/bun/issues/10849

**Closed as not planned by dylan-conway** 2024-05-13 21:33 UTC
Labels: bug, crash
