### ISSUE TITLE
[PackageManager] Bun can skip some package dependency installation

### ISSUE THREAD

**Issue by IvanAfonin** [oven-sh/bun#5110] opened 2023-09-12 14:45 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

I'm not sure how to correctly reproduce it, but you can try to create a private package on npm, install it and you will see this result. For me, this issue occurs with re-reselect library(it's a dependency of a private package). Installing is smooth and everything looks good, but after the build start(expo) it shows this error. I managed to fix it by installing re-reselect using `bun install` but this shouldn't be the case.

### What is the expected behavior?

Package dependencies installs correctly

### What do you see instead?

iOS Bundling failed 2892ms
Unable to resolve "re-reselect" from "node_modules/@PRIVATE_PACKAGE_FROM_NPM/redux/user/selectors/userLocks.js"

**Comment by Electroid** [comment] 2023-10-27 22:02
Duplicate of #4959

**Closed as completed by Electroid** 2023-10-27 22:02 UTC
Labels: bug, bun install

**Comment by Jarred-Sumner** [comment] 2023-12-12 06:12
Fixed by @dylan-conway and @paperdave in #7132
