### ISSUE TITLE
bun exits prematurely when not awaiting

### ISSUE THREAD

**Issue by micon4sure** [oven-sh/bun#9956] opened 2024-04-04 22:14 UTC
### What version of Bun is running?

1.1.0

### What platform is your computer?

windows

### What steps can reproduce the bug?
```
// run this
import { $ } from "bun";

const action = async () => {
  await $`bun run ./foo.ts`
  console.log('post')
}

action()
```

### What is the expected behavior?

Run the action

### What do you see instead?

The script exits prematurely if `action` is not awaited

**Comment by micon4sure** [comment] 2024-04-04 22:20
This actually is not shell but bun itself it would seem:
```
import { $ } from "bun";

const action = async () => {
  console.log('pre')
  await new Promise((resolve) => {
    setTimeout(() => resolve, 1000);
  })
  console.log('post')
}
action()
```
unexpected behaviour of top level await?

**Comment by Jarred-Sumner** [comment] 2024-09-06 20:57
Duplicate of https://github.com/oven-sh/bun/issues/13713

**Comment by Jarred-Sumner** [comment] 2024-09-06 20:57
This is being tracked in https://github.com/oven-sh/bun/issues/13713. Please follow along there.

**Closed as not planned by Jarred-Sumner** 2024-09-06 20:57 UTC
Labels: bug
