### ISSUE TITLE
Possible memory leak 

### ISSUE THREAD

**Issue by thibaultleouay** [oven-sh/bun#7377] opened 2023-11-30 08:16 UTC
### What version of Bun is running?

1.0.14

### What platform is your computer?

fly.io container 

### What steps can reproduce the bug?

We are running the bun from the latest docker image. 

The code of our apps is here : 
https://github.com/openstatusHQ/openstatus/tree/822093042ce5b2ea028d51c0f090bdcfbb0cb302/apps/server

We have one machine that dont get garbage collected 
Here's what we see 
![image](https://github.com/oven-sh/bun/assets/13894054/ed169749-30cc-4d81-9774-c373425080b5)

Here's what we expect 
![CleanShot 2023-11-30 at 09 10 39](https://github.com/oven-sh/bun/assets/13894054/7c1b5645-e7b0-4930-9d0c-7ce23f48913c)

and it happened twice for the same machine 
![image](https://github.com/oven-sh/bun/assets/13894054/2201e030-d4f8-47d5-99bc-666317055674)

Here's a snapshot 
https://snapshots.raintank.io/dashboard/snapshot/K7G90ajb9deOwkRtePmIAzAi7y9reE9v?orgId=2

**Comment by aqibgatoo** [comment] 2023-11-30 10:30
We have a same story on our bun service.
<img width="2437" alt="image" src="https://github.com/oven-sh/bun/assets/4655062/1502f44a-64a4-4c67-af49-573365202712">

**Comment by Jarred-Sumner** [comment] 2023-11-30 10:33
We will investigate this soon

**Comment by edwinbrowwn** [comment] 2024-02-09 00:55
Same issue when running within a container `node:20-bookworm-slim`.
![Screenshot 2024-02-08 185402](https://github.com/oven-sh/bun/assets/11434660/6e60ec6e-1eb6-41ef-b740-c59e70d5a896)

**Comment by goldo** [comment] 2024-02-21 10:40
We got a memory leak with bun `1.0.26` too. 
![image](https://github.com/oven-sh/bun/assets/518930/06b2de68-5392-4ba0-800f-84f8e63e19a5)

I will try to narrow it down to a simple example, but we are on a very small project, using mainly: `fastify@4.24.3` and `prisma@5.9.1` 
A simple HTTP call to this is leaking:
```ts
  fastify.get("/health", async (request) => {
    const count = await request.server.prisma.user.count();
    return { ok: count > 0 };
  });
  ```
(Without using prisma in this call, it was OK OFC)

Then I tried to build this code for `node`, using `bun build`, to run it in node 20, and it was a leaking a LOT less, and the GC could free the memory regularly, where it couldnt be possible when the same code (built or not) was run with bun.

I made my tests using `htop` and `autocannon`  with params `-c 30 -d 15`

**Comment by goldo** [comment] 2024-07-30 09:30
Hi, im no expert at all, but I tried to make a minimal reproduction with bun + fastify + prisma with results in readme 
https://github.com/goldo/bun-memory

**Comment by Jarred-Sumner** [comment] 2024-07-31 09:33
This was fixed in https://github.com/oven-sh/bun/pull/12955, and will be available in the next release of Bun. To get it early, run `bun upgrade --canary`

The memory leak in this issue was caused by creating an AbortError when the HTTP request finished if the body was not yet consumed. This error object was never reachable from the garbage collector, and the garbage collector would take a very long time to ever clean these up because it’d only happen during a full collection

**Comment by Jarred-Sumner** [comment] 2024-07-31 09:34
@goldo im not sure yet if the memory leak in this issue is the same as the one you’re running into.

**Closed as completed** 2024-11-20 19:01 UTC
Labels: bug
