### ISSUE TITLE
Re-exporting typescript types generates syntax errors

### ISSUE THREAD

**Issue by theakman2** [oven-sh/bun#1852] opened 2023-01-20 06:49 UTC
## What version of Bun is running?

0.5.0

## What platform is your computer?

Xubuntu 22.10 x86-64
Linux-5.19.0-29-generic-x86_64-with-glibc2.36

## What steps can reproduce the bug?

1. Create file `IFoo.ts`:

```ts
export interface IFoo {
	bar: number;
}

export class Foo {};
```

2. Create file `IFooRexport.ts`:

```ts
export { Foo, IFoo } from "./IFoo";
```

3. Create file `main.ts`:

```ts
import { Foo } from "./IFooReexport";

new Foo();
```

4. Execute `main.ts`:

```sh
bun main.ts
```

## What is the expected behaviour?

The script executes without any errors.

## What do you see instead?

The script returns exit code 1 with the following error:

```
SyntaxError: Indirectly exported binding name 'IFoo' is not found.
```
## Additional information

Compiling `main.ts` with `tsc` doesn't throw any errors.

**Comment by Jarred-Sumner** [comment] 2023-01-20 06:59
As a temporary workaround, try `export type { IFoo }`

**Comment by theakman2** [comment] 2023-01-20 07:12
That seems to work, thank you!

**Comment by Electroid** [comment] 2023-10-25 22:36
Duplicate of #5426

**Closed as not planned by Electroid** 2023-10-25 22:36 UTC
Labels: bug, typescript, transpiler
