### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by R0N1n-dev** [oven-sh/bun#1023] opened 2022-08-08 04:13 UTC
### Version

illegal instruction

### Platform

Linux ronin-HP-Laptop 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

install bun using script (downloaded  canary baseline build linux x64 )
Add to bash
Use any bun command

### How often does it reproduce? Is there a required condition?

any bun command

### What is the expected behavior?

A bun version is displayed
e.g.

bun -v
0.1.7

### What do you see instead?

Illegal instruction

### Additional information

Please stop closing my issue assuming that ur solution has worked for me yet it has not. I will keep opening it again.

**Comment by JoshuaRaison** [comment] 2022-08-08 05:30
```md

system@system01:~$ bun --help

Illegal instruction (core dumped)

```
edit:
Haven't found any fix.

passing `bun-v0.1.6` as argument installed v0.1.6 :)

**Comment by xhyrom** [comment] 2022-08-08 05:54
Duplicate of https://github.com/oven-sh/bun/issues/1011

**Closed as completed by xhyrom** 2022-08-08 05:54 UTC
Labels: bug, needs repro
