### ISSUE TITLE
bug: http request to bun server freezes incase of underscore in headers

### ISSUE THREAD

**Issue by shivamsouravjha** [oven-sh/bun#6102] opened 2023-09-27 10:51 UTC
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What steps can reproduce the bug?

```
const server = Bun.serve({
    fetch(req) {
      const res = new Response('hello world');
      res.headers.set('Access-Control-Allow-Origin', '*');
      res.headers.set('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
      res.headers.set('Access-Control-Allow-Headers', '*');
      return res;
    },
  });
  
  console.log(`Listening on localhost: ${server.port}`);

```
```
curl --location 'localhost:3000' \
--header 'Keploy_test_id: test-1'
```
make a curl request

this would hang the bun server 

<img width="618" alt="image" src="https://github.com/oven-sh/bun/assets/60891544/72fabb7d-7266-47f4-8db3-2a3366d9a0eb">

### What is the expected behavior?

Should return response 

<img width="646" alt="image" src="https://github.com/oven-sh/bun/assets/60891544/aa0a86f6-d0cb-4ae5-bc69-6cf62c3f6461">

**Comment by Jarred-Sumner** [comment] 2023-09-27 11:05
Duplicate of #3580

**Closed as not planned by Jarred-Sumner** 2023-09-27 11:05 UTC
Labels: bug
