### ISSUE TITLE
Bun for Windows 

### ISSUE THREAD

**Issue by Lakshaybogal** [oven-sh/bun#6402] opened 2023-10-10 15:27 UTC
### What is the problem this feature would solve?

Bun for Windows 

### What is the feature you are proposing to solve the problem?

Bun for Windows 

### What alternatives have you considered?

Bun for Windows

**Comment by Electroid** [comment] 2023-10-10 16:01
We will release a build soon.

Duplicate of #43

**Closed as not planned by Electroid** 2023-10-10 16:01 UTC
Labels: enhancement
