### ISSUE TITLE
SIGBUS sometimes when running `bun install` and `nx postscript` runs

### ISSUE THREAD

**Issue by ffMathy** [oven-sh/bun#14207] opened 2024-09-27 06:56 UTC
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Linux 6.10.4-linuxkit aarch64 unknown

### What steps can reproduce the bug?

N/A - it happens inconsistently. We're running inside a DevContainer.

### What is the expected behavior?

Bun install succeeds.

### What do you see instead?

```
error: postinstall script from "nx" terminated by SIGBUS (Misaligned address error)
93 Bus error               (core dumped) bun install -y
```

**Comment by 190n** [comment] 2024-09-27 22:51
Are you able to share an nx workspace that the issue reproduces in? I haven't been able to trigger this in a new workspace.

**Comment by ffMathy** [comment] 2024-09-30 05:41
Unfortunately not. The code is under NDA, and I tried spending several hours creating a repro.

Since it's flaky, I have no idea what triggers it.

However, it always complains about the NX post install scripts. So must have something to do with whatever NX is trying to run after install.

**Comment by ffMathy** [comment] 2024-09-30 05:42
Is there a way to create a memory dump of some sorts that doesn't contain sensitive information?

**Comment by Leolainen** [comment] 2024-09-30 08:13
I'm facing this issue too within my org. We're building private npm packages with nx & bun. 

The error only shows up when running `bun install` in the CI. I've not faced the error locally. 
I created a repro: here:https://github.com/Leolainen/sigbus-repro

Here's a failing workflow:
https://github.com/Leolainen/sigbus-repro/actions/runs/11101969512/job/30840735737?pr=1

I hope it's something trivial. :) 🤞

**Comment by Leolainen** [comment] 2024-09-30 08:15
I forgot to add that, like in @ffMathy's case, the issue is flaky. Rerunning the workflow may or may not result in a complete run without issues.

**Comment by 190n** [comment] 2024-09-30 18:28
Thanks a lot for the repro, I can start looking into this.

I'm noticing the CI machine is x86_64 Linux -- @ffMathy is that the kind of machine that you got this on, too? You said it's a dev container; what was the host platform?

**Comment by ffMathy** [comment] 2024-09-30 19:21
For me, the host platform is a MacBook M1. But it happens on my GitHub Actions build too, which is an ubuntu-latest that is also running Bun commands inside a devcontainer via the official "devcontainers/ci" action.

**Comment by ffMathy** [comment] 2024-09-30 19:22
The base image of the devcontainer is node:lts.

**Comment by 190n** [comment] 2024-09-30 19:39
> For me, the host platform is a MacBook M1.

And is the container also running ARM, or is it emulated x86?

**Comment by ffMathy** [comment] 2024-09-30 20:06
The container is also running ARM. But in the CI environment where it's also happening in ubuntu-latest, both host and container is in X86.

**Comment by 190n** [comment] 2024-10-01 02:42
Thanks again for the repro @Leolainen, that was invaluable. After some debugging I think this is a duplicate of nrwl/nx#26517. In the meantime, a workaround that worked for me and for a few people in that issue thread is forcing the install scripts to run sequentially. You can do that in Bun by passing `--concurrent-scripts 1` to `bun install`. Does that resolve the issue on your production codebases?

**Comment by Jarred-Sumner** [comment] 2024-10-03 21:19
Pretty confident this is an upstream bug in nx that we are unable to help with much on our end

If you think there's anything we can do to help, please leave a comment and we'll re-open this

**Closed as not planned by Jarred-Sumner** 2024-10-03 21:19 UTC
Labels: bug, atw

**Comment by Leolainen** [comment] 2024-10-04 14:44
Sorry, I never responded. @190n Your suggestion seems to have solved the issue. Thanks a lot. :)
