### ISSUE TITLE
When I install react-native-skia it doesn't execute the command bun install postinstall

### ISSUE THREAD

**Issue by meftunca** [oven-sh/bun#1912] opened 2023-01-27 10:40 UTC
### What version of Bun is running?

0.5.1

### What platform is your computer?

Darwin 22.1.0 x86_64 i386

### What steps can reproduce the bug?

When I install react-native-skia it doesn't execute the command bun install postinstall.
I can't run my android project because of this problem

**Comment by birkskyum** [comment] 2023-10-18 02:18
@meftunca , have you tried adding it to [trustedDependencies](https://bun.sh/guides/install/trusted)?

**Comment by meftunca** [comment] 2023-10-18 05:34
@birkskyum No, but I will try tomorrow ?

**Comment by Electroid** [comment] 2023-10-25 22:32
Duplicate of #4959

**Closed as completed by Electroid** 2023-10-25 22:32 UTC
Labels: bug

**Comment by Jarred-Sumner** [comment] 2023-12-12 06:13
Fixed by @dylan-conway and @paperdave  in #7132 

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.
