### ISSUE TITLE
trying to start my node.js+express app on bun and it fails with error about bcrypt/bcrypt.js

### ISSUE THREAD

**Issue by tigrazone** [oven-sh/bun#5280] opened 2023-09-13 15:39 UTC
### What version of Bun is running?

1.0.1

### What platform is your computer?

Linux/debian, WSL

### What steps can reproduce the bug?

I use these packege.json
```
{
  "name": "jaroslavna-node",
  "version": "1.0.0",
  "description": "Jaroslavna on Node",
  "main": "./server.js",
  "scripts": {
    "start": "nohup node server.js > output.log &",
    "local": "set NODE_ENV=dev && nodemon -e js,ejs,json,art,css server.js",
    "linuxlocal": "export NODE_ENV=devlinux && nodemon -e js,ejs,json,art,css server.js",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "pm2": "pm2 start ecosystem.config.js"
  },
  "nodemonConfig": {
    "ignore": [
      "public/*"
    ]
  },
  "dependencies": {
    "@joi/date": "^2.1.0",
    "adm-zip": "^0.5.10",
    "art-template": "^4.13.2",
    "bcrypt": "^5.1.0",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "express-art-template": "^1.0.1",
    "express-async-errors": "^3.1.1",
    "express-ip": "^1.0.4",
    "express-session": "^1.17.3",
    "helmet": "^7.0.0",
    "joi": "^17.9.2",
    "jsdom": "^22.1.0",
    "locutus": "^2.0.16",
    "mime": "^3.0.0",
    "morgan": "^1.10.0",
    "multer": "^1.4.5-lts.1",
    "mysql2": "^3.5.2",
    "node-cache": "^5.1.2",
    "nodemailer": "^6.9.4",
    "nodemailer-smtp-transport": "^2.4.2",
    "passport": "^0.6.0",
    "passport-local": "^1.0.0",
    "path": "^0.12.7",
    "sanitize-filename": "^1.6.3",
    "sequelize": "^6.32.1",
    "serve-static": "^1.15.0",
    "sharp": "^0.32.3",
    "stoppable": "^1.1.0",
    "timezones.json": "^1.7.0",
    "winston": "^3.10.0"
  },
  "devDependencies": {
    "eslint": "^8.45.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.27.5"
  }
}
```

Before use bun I removed node_modules folder and package-lock.json

First of all, I run bun install and all packages installed without errors.
I run my app with command export NODE_ENV=devlinux && bun server.js

I have error 
error: Cannot find module "/home/thr/jaroslavna/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" from "/home/thr/jaroslavna/node_modules/bcrypt/bcrypt.js"

With node.js app started without errors

**Comment by sirenkovladd** [comment] 2023-09-13 20:06
Duplicate of https://github.com/oven-sh/bun/issues/299

But you can use it
https://github.com/oven-sh/bun/pull/3204
https://bun.sh/guides/util/hash-a-password
or
this is fix https://github.com/oven-sh/bun/issues/4969#issuecomment-1714679629

**Comment by Electroid** [comment] 2023-09-13 20:18
See #299

**Closed as not planned by Electroid** 2023-09-13 20:18 UTC
Labels: bug, node.js

**Comment by tigrazone** [comment] 2023-09-14 07:13
I used solve my problem with npm install vs bun install and my app started.
But I have new error
Executing (default): SELECT * FROM users WHERE user_login = 'thr' and is_active=1
Segmentation fault

For sql calls I use mysql2 and sequalize

**Comment by sirenkovladd** [comment] 2023-09-14 08:58
@tigrazone, can you create a new issue with steps to reproduce?

**Comment by tigrazone** [comment] 2023-09-14 11:13
I dont know ho to reproduce. My project is my ready express site which works ok on node.js but fails with Segmentation Fault

**Comment by tigrazone** [comment] 2023-09-14 11:19
Maybe i can do it with debugger. Show me how
