### ISSUE TITLE
Segfault during vite build with Prisma (Docker, Alpine image)

### ISSUE THREAD

**Issue by EmilHeilbo** [oven-sh/bun#13983] opened 2024-09-16 09:35 UTC
### How can we reproduce the crash?

Configure and run [EmilHeilbo/jobsearch-overview@8e37ad7](https://github.com/EmilHeilbo/jobsearch-overview/tree/8e37ad7). I'm reverting to 1.0.18 for now which seems to fix the issue, so I'm thinking it could be related to #7864 😅 

### Relevant log output

```shell
$ docker build .
[+] Building 10.1s (11/11) FINISHED                               docker:desktop-linux
 => [internal] load build definition from Dockerfile                              0.1s
 => => transferring dockerfile: 233B                                              0.0s 
 => [internal] load metadata for docker.io/oven/bun:alpine                        0.6s 
 => [internal] load .dockerignore                                                 0.0s
 => => transferring context: 70B                                                  0.0s 
 => [1/7] FROM docker.io/oven/bun:alpine@sha256:223b266d24de57a3aec1701a10e513be  0.1s 
 => => resolve docker.io/oven/bun:alpine@sha256:223b266d24de57a3aec1701a10e513be  0.0s 
 => [internal] load build context                                                 0.1s 
 => => transferring context: 39.14kB                                              0.1s 
 => CACHED [2/7] WORKDIR /usr/src/app                                             0.0s
 => CACHED [3/7] COPY package*.json .                                             0.0s 
 => CACHED [4/7] RUN bun install --force                                          0.0s 
 => [5/7] COPY . .                                                                1.7s
 => [6/7] RUN bunx prisma generate                                                3.4s 
 => ERROR [7/7] RUN bun run build                                                 4.0s 
------
 > [7/7] RUN bun run build:
0.423 $ vite build
1.935 vite v5.4.5 building SSR bundle for production...
2.042 transforming...
2.935 ✓ 84 modules transformed.
3.085 rendering chunks...
3.855 ============================================================
3.855 Bun v1.1.27 (267afa29) Linux x64 (baseline)
3.855 WSL Kernel v5.15.153 | glibc v2.34
3.855 CPU: sse42 popcnt avx avx2
3.855 Args: "node" "/usr/src/app/node_modules/.bin/vite" "build"
3.855 Features: jsc Bun.stdin(3) dotenv(2) spawn(2) tsconfig_paths(3) tsconfig(5) workers_spawned
3.855 Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws" "node:v8"
3.855 Elapsed: 3431ms | User: 4596ms | Sys: 730ms
3.855 RSS: 2.82GB | Peak: 0.58GB | Commit: 2.82GB | Faults: 0
3.855
3.855 panic: Segmentation fault at address 0x4A0D0
3.855 oh no: Bun has crashed. This indicates a bug in Bun, not your code.
3.855
3.855 To send a redacted crash report to Bun's team,
3.855 please file a GitHub issue using the link below:
3.855
3.855  https://bun.report/1.1.27/Bn1267afa2CqoggkDu8rklEA2AgtwS
3.855
3.907 error: script "build" was terminated by signal SIGILL (Illegal instruction)      
------
Dockerfile:9
--------------------
   7 |     COPY . .
   8 |     RUN bunx prisma generate
   9 | >>> RUN bun run build
  10 |
  11 |     EXPOSE 3000
--------------------
ERROR: failed to solve: process "/bin/sh -c bun run build" did not complete successfully: exit code: 139
```

### Stack Trace (bun.report)

Bun v1.1.27 ([`267afa2`](<https://github.com/oven-sh/bun/tree/267afa293483d5ed5f834a6d35350232188e3f98>)) on linux x86_64_baseline [AutoCommand]

Segmentation fault at address 0x0004A0D0

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/267afa293483d5ed5f834a6d35350232188e3f98/ld-temp.o#L0>): `char32_t WTF::Unicode::next<(...)0, char8_t>`

**Comment by Jarred-Sumner** [comment] 2024-09-17 08:05
Duplicate of #918

**Comment by Jarred-Sumner** [comment] 2024-09-17 08:05
Please switch to the debian slim build instead of alpine

We don't officially support alpine yet.

**Closed as not planned by Jarred-Sumner** 2024-09-17 08:05 UTC
Labels: crash, linux

**Comment by EmilHeilbo** [comment] 2024-09-17 08:39
I didn't realise alpine wasn't officially supported yet. Thanks for the heads up, and apologies for taking up time ^^

**Comment by Jarred-Sumner** [comment] 2024-09-17 08:40
Not your fault, we need to make this more clear
