### ISSUE TITLE
`bun install` exits with `0` when not all packages could be installed

### ISSUE THREAD

**Issue by elyobo** [oven-sh/bun#8863] opened 2024-02-12 09:15 UTC
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

I have a private package installed, but running in CI (GitHub Actions) I haven't set up the `bunfig.toml` yet, so the install fails. However because the exit code is `0`, the `bun install` steps passes, and failure occur elsewhere in the steps.

### What is the expected behavior?

`npm install` will exit with a non-zero exit code in the same situation; I think `bun` should too

### What do you see instead?

The exit code is `0`

```
➜ bun i
bun install v1.0.26 (c75e768a)
  🔍 Resolving...
GET https://registry.npmjs.org/@raywhite/prettier-config/-/prettier-config-0.1.0.tgz - 404
  🔍 Resolving...
GET https://registry.npmjs.org/@raywhite/eslint-config/-/eslint-config-1.1.0.tgz - 404

Checked 452 installs across 427 packages (no changes) [1.52s]
➜ echo $?
0
```

**Comment by Electroid** [comment] 2024-02-20 19:59
Duplicate of #4200

**Closed as not planned by Electroid** 2024-02-20 19:59 UTC
Labels: bug, bun install

**Comment by elyobo** [comment] 2024-02-20 21:49
Thanks, don't know how I missed that one.
