### ISSUE TITLE
Bun has crashed

### ISSUE THREAD

**Issue by denisdpc** [oven-sh/bun#15079] opened 2024-11-10 15:48 UTC
### How can we reproduce the crash?

After running the command:
bunx shadcn-svelte@latest init

Result:

```
Bun v1.1.34 (5e5e7c60) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "bun" "C:\Users\denis\AppData\Local\Temp\bunx-4192139991-shadcn-svelte@latest\node_modules\shadcn-svelte\dist\index.js" "init"
Features: Bun.stdin(2) Bun.stdout fetch jsc transpiler_cache(3) tsconfig(2) tsconfig_paths
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:console" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "node:http2" "node:diagnostics_channel"
Elapsed: 7000ms | User: 218ms | Sys: 171ms
RSS: 0.25GB | Peak: 0.25GB | Commit: 4.60GB | Faults: 63732

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *5 unknown/js code*
- [`CodeBlock.h:292`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/bytecode/CodeBlock.h#L292>): `JSC::CodeBlock::bytecodeOffset`
- [`CommonSlowPaths.cpp:924`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/CommonSlowPaths.cpp#L924>): `slow_path_enter`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, fetch, jsc, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5697723847/">BUN-40F</a></strong></sub>

**Comment by nektro** [comment] 2024-11-11 22:40
duplicate of https://github.com/oven-sh/bun/issues/14926

**Closed as not planned by nektro** 2024-11-11 22:40 UTC
Labels: crash, windows, runtime
