### ISSUE TITLE
unable to watch in docker

### ISSUE THREAD

**Issue by Bader-Idris** [oven-sh/bun#6829] opened 2023-10-31 14:46 UTC
In my Docker app, I embarked on a journey to create something extraordinary - an image that would embody progress and innovation. Excitement filled my heart as I longed to witness the magic of my code unfolding effortlessly before my eyes. However, the commands `bun --watch run start` and `bun --hot run start` failed to reveal the desired transformation.

Faced with this challenge, I found myself trapped in a cycle of rebuilding my container for even the smallest changes, draining both time and spirit. It felt as though my creative spark was being stifled, unable to flourish amidst the repetitive labor.

Yet, a glimmer of hope ignited within me. I yearned for a solution that would seamlessly synchronize with my creative journey - one that would recognize the subtlest shifts and breathe life into my application effortlessly.

Today, I humbly seek your guidance, dear friends. Together, let us unravel the mysteries of the 'bun' tool, overcoming configuration complexities, compatibility hurdles, and any lurking bugs that impede our progress.

Should our search for resolution prove elusive, fear not. We shall explore alternative bundlers and build tools that offer the watchful gaze we crave. With unwavering determination and shared purpose, we will find the perfect companion to accompany us on this remarkable journey of code and creation.

For it is in the face of adversity that our strength shines brightest, and through collaboration, we forge a path to endless possibilities. Let us embrace the art of transformation and breathe life into our dreams, for in doing so, we elevate not only our creations but also the very essence of our souls.

**Comment by Electroid** [comment] 2023-10-31 16:40
Duplicate of #5841

**Closed as not planned by Electroid** 2023-10-31 16:40 UTC
