### ISSUE TITLE
`weakrefObj.deref()` returns `undefined` in setInterval context

### ISSUE THREAD

**Issue by palamarchukser** [oven-sh/bun#5942] opened 2023-09-23 01:11 UTC
### What version of Bun is running?

1.0.3

### What platform is your computer?

Darwin 22.1.0 arm64 arm

### What steps can reproduce the bug?

**index.js:**
```
console.time('test');

const weakrefObj = new WeakRef({ counter: 1 });
const interval = setInterval(() => {
  let derefObj = weakrefObj.deref();

  if(derefObj) {
    console.log(derefObj.counter);
    derefObj = undefined; // clear strong reference
  } else {
    console.log('weakref gone');
    clearInterval(interval);
  }
}, 10);

console.timeEnd('test');
```

run `bun run index.js`

**Results:**
<img width="447" alt="image" src="https://github.com/oven-sh/bun/assets/10272176/39cc0bcc-5591-463f-a40c-2bbb245eb800">

### What is the expected behavior?

```
1
weakref gone
```

### What do you see instead?

```weakref gone```

**Comment by dylan-conway** [comment] 2023-09-23 02:46
This is a difference in gc implementation between v8 and JSC and likely not a bug. The object passed to `WeakRef` becomes unreachable immediately

**Comment by cyfung1031** [comment] 2023-09-26 20:21
I think the result is correct. You have no strong reference to `{ counter: 1 }`, so it will be cleared after "a while"
This should NOT be considered as a bug.

that "a while" is not deterministic. You cannot say it should be 15000ms so you can still get the value at 10000ms

and you don't need the `derefObj = undefined` because `derefObj` only lives within the 
```
() => {
  let derefObj = weakrefObj.deref();

  if(derefObj) {
    // ...
  } else {
    // ...
  }
}
```

**Comment by palamarchukser** [comment] 2023-09-26 21:59
@cyfung1031 In fact, for this particular case, it doesn't matter whether there is a reference or not, I don’t focus on the context it's just example... 

> You cannot say it should be 15000ms so you can still get the value at 10000ms

yeah, but it definitely has to be more than 0, right? - that was the main thing - we get `undefined` in ANY `setInterval` context even with 0ms.

But it won't work with `bun` even in that case with 0ms
```
const interval = setInterval(() => {
....
}, 0);
```

**Comment by Jarred-Sumner** [comment] 2024-01-13 00:45
The behavior of the GC is by design. if you want to keep the object alive, you could assign it to a global or to a value which is reference inside the setInterval callback.

**Closed as not planned by Jarred-Sumner** 2024-01-13 00:45 UTC
Labels: bug, jsc
