### ISSUE TITLE
bun install needs to normalize line endings for bins

### ISSUE THREAD

**Issue by renhiyama** [oven-sh/bun#3416] opened 2023-06-26 13:08 UTC
### What version of Bun is running?

0.6.9

### What platform is your computer?

Linux

### What steps can reproduce the bug?

`bunx live-server`

### What is the expected behavior?

Live server running

### What do you see instead?

```js
bunx live-server
/usr/bin/env: ‘node\r’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
error: "live-server" exited with code 127
```

**Comment by godalming123** [comment] 2023-09-16 16:03
Dupe of: #1125

**Comment by Electroid** [comment] 2023-10-03 01:31
Duplicate of #1125

**Closed as not planned by Electroid** 2023-10-03 01:31 UTC
Labels: bug, bun install
