### ISSUE TITLE
Package installing failed for @mui/x-tree-view

### ISSUE THREAD

**Issue by laki944** [oven-sh/bun#5129] opened 2023-09-12 16:57 UTC
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

In React application trying to install dependencies using the command `bun install`

for dependencies:
 "dependencies": {
    "@auth0/auth0-spa-js": "^1.20.1",
    "@emotion/cache": "^11.7.1",
    "@emotion/react": "^11.8.2",
    "@emotion/styled": "^11.8.1",
    "@fullcalendar/daygrid": "^5.10.1",
    "@fullcalendar/interaction": "^5.10.1",
    "@fullcalendar/list": "^5.10.1",
    "@fullcalendar/react": "^5.10.1",
    "@fullcalendar/timegrid": "^5.10.1",
    "@fullcalendar/timeline": "^5.10.1",
    "@hookform/resolvers": "^2.8.8",
    "@iconify/react": "^3.1.4",
    "@mui/lab": "^5.0.0-alpha.72",
    "@mui/material": "^5.5.0",
    "@mui/x-data-grid": "^5.6.1",
    "@react-pdf/renderer": "^2.1.1",
    "@reduxjs/toolkit": "^1.8.0",
    "@turf/bbox": "^6.5.0",
    "amazon-cognito-identity-js": "^5.2.8",
    "apexcharts": "^3.33.2",
    "assert": "^2.0.0",
    "autosuggest-highlight": "^3.2.1",
    "axios": "^0.26.1",
    "browserify-zlib": "^0.2.0",
    "buffer": "^6.0.3",
    "change-case": "^4.1.2",
    "d3-array": "^3.1.1",
    "d3-scale": "^4.0.2",
    "date-fns": "^2.28.0",
    "deck.gl": "^8.7.0",
    "emoji-mart": "^3.0.0",
    "firebase": "^9.6.8",
    "framer-motion": "^6.2.8",
    "highlight.js": "^11.5.0",
    "history": "^5.3.0",
    "i18next": "^21.6.14",
    "i18next-browser-languagedetector": "^6.1.3",
    "immutable": "^4.0.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "mapbox-gl": "^2.7.0",
    "notistack": "^2.0.3",
    "nprogress": "^0.2.0",
    "numeral": "^2.0.6",
    "process": "^0.11.10",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-apexcharts": "^1.4.0",
    "react-app-rewired": "^2.2.1",
    "react-beautiful-dnd": "^13.1.0",
    "react-copy-to-clipboard": "^5.0.4",
    "react-dom": "^17.0.2",
    "react-dropzone": "^12.0.4",
    "react-helmet-async": "^1.2.3",
    "react-hook-form": "^7.27.1",
    "react-i18next": "^11.15.6",
    "react-image-lightbox": "^5.1.4",
    "react-lazy-load-image-component": "^1.5.1",
    "react-map-gl": "^6.1.19",
    "react-markdown": "^8.0.0",
    "react-quill": "^2.0.0-beta.4",
    "react-redux": "^7.2.6",
    "react-router": "^6.2.2",
    "react-router-dom": "^6.2.2",
    "react-scripts": "^5.0.0",
    "react-slick": "^0.28.0",
    "react-social-login-buttons": "^3.6.1",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "rehype-raw": "^6.1.1",
    "simplebar": "^5.3.6",
    "simplebar-react": "^2.3.6",
    "slick-carousel": "^1.8.1",
    "stream-browserify": "^3.0.0",
    "stylis": "^4.0.13",
    "stylis-plugin-rtl": "^2.1.1",
    "util": "^0.12.4",
    "web-vitals": "^2.1.4",
    "worker-loader": "^3.0.8",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@babel/eslint-parser": "^7.17.0",
    "@typescript-eslint/eslint-plugin": "^5.12.1",
    "@typescript-eslint/parser": "^5.12.1",
    "babel-eslint": "^10.1.0",
    "eslint": "^8.9.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.4.0",
    "eslint-config-react-app": "^7.0.0",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "prettier": "^2.5.1",
    "typescript": "^4.5.5"
  }

### What do you see instead?

`error: package "@mui/x-tree-view" with tag "https://pkg.csb.dev/mui/mui-x/commit/1f23b33d/@mui/x-tree-view" not found, but package exists`

**Comment by sirenkovladd** [comment] 2023-09-12 17:53
Duplicate of https://github.com/oven-sh/bun/issues/4666

**Comment by Electroid** [comment] 2023-10-13 04:21
Duplicate of #4666

**Closed as not planned by Electroid** 2023-10-13 04:21 UTC
Labels: bug
