### ISSUE TITLE
Incomplete WebAssembly namespace implementation

### ISSUE THREAD

**Issue by ProphetLamb** [oven-sh/bun#15930] opened 2024-12-21 22:17 UTC
### What version of Bun is running?

1.1.42

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 unknown, Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

The WebAssembly class is missing the suggested method for interacting with Wasm. This causes compatibility issues compared to node.
Instead of [`WebAssembly.instantiateStreaming()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming_static) I need to use [`WebAssembly.instantiate()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate_static).

1. Compile a trivial Wasm module, e.g. `add.wasm`
2. Place the module in the directory of `index.ts`
3. load the wasm module
```js
const url = new URL('add.wasm', import.meta.url)
const rsp = await fetch(url)
const dat = await rsp.arrayBuffer()
const wsm = await WebAssembly.instantiate(dat);
const mod = wsm.instance.exports
console.log(mod.add(1,2))
```

```log
3
```

Perfect, all working as intended. But we are using a `WebAssembly.instantiate` which MDN advises against. 4. Let's use the suggested method instead: `WebAssembly.instantiateStreaming`.

```js
console.log(WebAssembly)
const wsm = await WebAssembly.instantiateStreaming(fetch(new URL('add.wasm', import.meta.url)));
```

```log
WebAssembly {
  CompileError: [class CompileError extends Error],
  Exception: [class Exception],
  Global: [class Global],
  Instance: [class Instance],
  LinkError: [class LinkError extends Error],
  Memory: [class Memory],
  Module: [class Module],
  RuntimeError: [class RuntimeError extends Error],
  Table: [class Table],
  Tag: [class Tag],
  compile: [Function: compile],
  instantiate: [Function: instantiate],
  validate: [Function: validate],
}
4 | console.log(WebAssembly)
5 | const wsm = await WebAssembly.instantiateStreaming(dat);
                                  ^
TypeError: WebAssembly.instantiateStreaming is not a function. (In 'WebAssembly.instantiateStreaming(dat)', 'WebAssembly.instantiateStreaming' is undefined)
      at /com.docker.devenvironments.code/index.ts:5:30

Bun v1.1.42 (Linux x64)
```

This same example is reproducible on Windows native, as well as Linux native

### What is the expected behavior?

The signature conforms to node, or the wasm compatibility for bun is corrected to "partially implemented"
https://github.com/oven-sh/bun/blob/14b44aeb49122db206feabca82b3aee8563e368b/docs/runtime/nodejs-apis.md?plain=1#L444

### What do you see instead?

I text patch my node_modules after installing. I add a simple implementation to the next best js file
```js
WebAssembly.instantiateStreaming = async (
    source,
    importObject
) => {
const rsp = await source;
const buf = await rsp.arrayBuffer();
return WebAssembly.instantiate(buf, importObject);
};
  
```

### Additional information

`instantiateStreaming` is declared in the namespace `WebAssembly` for main 
https://github.com/oven-sh/bun/blob/14b44aeb49122db206feabca82b3aee8563e368b/packages/bun-types/wasm.d.ts#L263
aswell as 1.1.42
https://github.com/oven-sh/bun/blob/bun-v1.1.42/packages/bun-types/wasm.d.ts#L263

**Comment by Jarred-Sumner** [comment] 2024-12-23 16:37
Duplicate of https://github.com/oven-sh/bun/issues/14219

**Closed as duplicate by Jarred-Sumner** 2024-12-23 16:37 UTC
Labels: bug, needs triage
