### ISSUE TITLE
process.binding("spawn_sync") is not implemented in Bun

### ISSUE THREAD

**Issue by nektro** [oven-sh/bun#14342] opened 2024-10-04 03:06 UTC
this currently blocks running the test suite of https://www.npmjs.com/package/level

```
❯ node
Welcome to Node.js v22.9.0.
Type ".help" for more information.
> process.binding("spawn_sync")
{ spawn: [Function: spawn] }
```

**Comment by RiskyMH** [comment] 2024-10-12 08:49
Duplicate of #8694

**Closed as not planned by RiskyMH** 2024-10-12 08:49 UTC
Labels: bug, node.js
