### ISSUE TITLE
The `connectOverCDP` method of `playwright` does not work in `bun`, and the program just hangs.

### ISSUE THREAD

**Issue by iamobj** [oven-sh/bun#9357] opened 2024-03-11 10:05 UTC
### What version of Bun is running?

1.0.30

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

The `connectOverCDP` method of `playwright` does not work in bun, and the program just hangs.This is a reason that hinders me from using `bun`.

### Additional information

```
import { chromium } from 'playwright'

const browser = await chromium.connectOverCDP('http://127.0.0.1:9222')
```

**Comment by maxxnino** [comment] 2024-04-02 03:58
I was thrilled when I discovered the Playwright support in the latest release. Eager to try it out, I jumped right in. However, to my surprise, I encountered the same issue, no error messages, no stack traces, just `silence...`
```typescript
try {
    const browser = await chromium.connectOverCDP(`http://${remote_url}`);
} catch (error) {
    console.log(error);
}
```

**Comment by rossanmol** [comment] 2024-04-08 10:08
Experiencing same issue.

**Comment by Electroid** [comment] 2024-04-09 16:55
Duplicate of #9911

**Closed as not planned by Electroid** 2024-04-09 16:55 UTC
Labels: bug, needs investigate
