### ISSUE TITLE
panic(main thread): Segmentation fault at address 0x0

### ISSUE THREAD

**Issue by XavierGeerinck** [oven-sh/bun#12511] opened 2024-07-11 11:57 UTC
### How can we reproduce the crash?

We are trying to upload a file to Azure through the Blob Container API

### Relevant log output

```shell
2024-07-11T11:55:10.949794875Z error: script "start" was terminated by signal SIGKILL (Forced quit)
2024-07-11T11:55:10.950467664Z ============================================================
2024-07-11T11:55:10.951041768Z Bun v1.1.18 (5a0b9352) Linux x64 (baseline)
2024-07-11T11:55:10.951496647Z Linux Kernel v5.15.158 | glibc v2.31
2024-07-11T11:55:10.951519336Z Args: "bun" "run" "start"
2024-07-11T11:55:10.951524171Z Features: spawn 
2024-07-11T11:55:10.951528150Z Elapsed: 61039ms | User: 11ms | Sys: 17ms
2024-07-11T11:55:10.951532328Z RSS: 1.07GB | Peak: 19.62MB | Commit: 1.07GB | Faults: 28
2024-07-11T11:55:10.951536227Z 
2024-07-11T11:55:10.951540220Z panic(main thread): Segmentation fault at address 0x0
2024-07-11T11:55:10.951544242Z oh no: Bun has crashed. This indicates a bug in Bun, not your code.
2024-07-11T11:55:10.951547604Z 
2024-07-11T11:55:10.951551333Z To send a redacted crash report to Bun's team,
2024-07-11T11:55:10.951554854Z please file a GitHub issue using the link below:
2024-07-11T11:55:10.951558081Z 
2024-07-11T11:55:10.951567728Z  https://bun.report/1.1.18/Br15a0b935AggggI+1mOwqr28Cktiq9C2spq9Cgm413Cgtg13CA2AA
2024-07-11T11:55:10.951571406Z
```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000000

- `??`
- [`Global.zig:128`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/Global.zig#L128>): `src.Global.raiseIgnoringPanicHandler__anon_69424`
- [`run_command.zig:407`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/cli/run_command.zig#L407>): `src.cli.run_command.RunCommand.runPackageScriptForeground`
- [`run_command.zig:1461`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/cli/run_command.zig#L1461>): `src.cli.run_command.RunCommand.exec__anon_72360`
- [`cli.zig:1801`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/cli.zig#L1801>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/main.zig#L50>): `main`

**Comment by Jarred-Sumner** [comment] 2024-07-11 17:06
Duplicate of https://github.com/oven-sh/bun/issues/12169

**Comment by Jarred-Sumner** [comment] 2024-07-11 17:07
Please follow along in https://github.com/oven-sh/bun/issues/12169

**Closed as not planned by Jarred-Sumner** 2024-07-11 17:07 UTC
Labels: crash, linux
