### ISSUE TITLE
Segmentation fault at address 0x0000001A

### ISSUE THREAD

**Issue by Sayrix** [oven-sh/bun#12158] opened 2024-06-25 20:08 UTC
### How can we reproduce the crash?

`TypeScript`
`Bun 1.1.17 Ubuntu 22.04.4 LTS aarch64`
`discord.js@14.15.3`
`mongodb@6.7.0`

On my Bun 1.1.17 Windows 11 23H2 22631.3737 x64 (for dev) works perfectly (#10695 may be closed, but since the PR is still not merged idk).

### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on linux aarch64 [AutoCommand]

Segmentation fault at address 0x0000001A

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/ld-temp.o#L0>): `WTF::jscSignalHandler`
- [`process_common.rs:0`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/sys/pal/unix/process/process_common.rs#L0>): `??`
- *2 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/ld-temp.o#L0>): `JSC::runJSMicrotask`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`BunProcess.cpp:2558`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/bindings/BunProcess.cpp#L2558>): `Bun::jsFunctionDrainMicrotaskQueue`
- *1 unknown/js code*

Features: jsc, Bun.stdin, fetch, http\_server, transpiler\_cache, tsconfig\_paths, tsconfig, WebSocket

**Comment by Sayrix** [comment] 2024-06-25 20:09
Same as #10695, sometimes i get the error, sometimes not. Very strange :(

**Comment by Jarred-Sumner** [comment] 2024-06-26 22:59
Duplicate of #10695

**Closed as not planned by Jarred-Sumner** 2024-06-26 22:59 UTC
Labels: crash, linux

**Comment by Sayrix** [comment] 2024-06-27 19:32
Yes but #10695 is for Windows, should i edit the issue to also add Linux aarch64 ?
