### ISSUE TITLE
Unable to use `eval` safely due to bun optimization

### ISSUE THREAD

**Issue by ghoullier** [oven-sh/bun#6849] opened 2023-11-02 06:52 UTC
### What version of Bun is running?

1.0.7

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

`index.js`
```js
const content = `Hello World!`
eval(`content = null`)
console.log(content)
```

➜  bun index.js

### What is the expected behavior?

TypeError: Assignment to constant variable.

### What do you see instead?

Hello World!

### Additional information

➜  bun build --target=node --minify index.js
```js
// index.js
(0, eval)("content = null");console.log("Hello World!");
```

Optimization inline `content` variable usage

**Comment by Electroid** [comment] 2023-11-04 17:33
Duplicate of #2875

**Closed as not planned by Electroid** 2023-11-04 17:33 UTC
Labels: bug
