### ISSUE TITLE
clone-deep package failing to run

### ISSUE THREAD

**Issue by iloveitaly** [oven-sh/bun#4049] opened 2023-08-08 00:14 UTC
### What version of Bun is running?

0.7.2

### What platform is your computer?

uname -mprs

### What steps can reproduce the bug?

The `clone-deep` package is failing with this stack trace:

```
TypeError: utils.forOwn is not a function. (In 'utils.forOwn(obj, function(obj, key) {
        this[key] = cloneDeep(obj, instanceClone);
      }, res)', 'utils.forOwn' is undefined)
      at cloneObjectDeep (/Users/mike/Projects/lunchmoney/lunchmoney-assets/node_modules/clone-deep/index.js:27:4)
      at cloneDeep (/Users/mike/Projects/lunchmoney/lunchmoney-assets/node_modules/clone-deep/index.js:16:13)
      at mergeDeep (/Users/mike/Projects/lunchmoney/lunchmoney-assets/node_modules/merge-deep/index.js:19:15)
      at new PuppeteerExtraPlugin (/Users/mike/Projects/lunchmoney/lunchmoney-assets/node_modules/puppeteer-extra-plugin/dist/index.cjs.js:61:21)
      at new StealthPlugin (/Users/mike/Projects/lunchmoney/lunchmoney-assets/node_modules/puppeteer-extra-plugin-stealth/index.js:74:4)
      at defaultExport (/Users/mike/Projects/lunchmoney/lunchmoney-assets/node_modules/puppeteer-extra-plugin-stealth/index.js:172:52)
```

This was generated by using the `puppeteer-extra-plugin-stealth` plugin

### What is the expected behavior?

On node 19.x it runs fine.

### Additional information

the project which triggered this action is open source https://github.com/iloveitaly/lunchmoney-assets

**Comment by Hanaasagi** [comment] 2023-08-09 11:11
Related to https://github.com/oven-sh/bun/issues/3823

**Comment by Electroid** [comment] 2023-10-26 22:32
Duplicate of #3823

**Closed as not planned by Electroid** 2023-10-26 22:32 UTC
Labels: bug, node.js
