### ISSUE TITLE
nodejs incompatibility in toString()

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12749] opened 2024-07-23 18:32 UTC
duplicate

**Comment by Electroid** [comment] 2024-07-23 18:34
Duplicate of #8624

**Comment by Electroid** [comment] 2024-07-23 18:34
This is a similar duplicate of the linked issue. Essentially, bun does not preserve the original content of `Function.toString()`, so it's showing a minified version. It's a known issue.

**Closed as not planned by Electroid** 2024-07-23 18:34 UTC
Labels: bug

**Comment by huseeiin** [comment] 2024-07-23 19:08
> This is a similar duplicate of the linked issue. Essentially, bun does not preserve the original content of `Function.toString()`, so it's showing a minified version. It's a known issue.

but in the second example. its node that is showing the minified version
