### ISSUE TITLE
Implement multi level globs

### ISSUE THREAD

**Issue by Kleywalker** [oven-sh/bun#6321] opened 2023-10-05 14:54 UTC
### What version of Bun is running?

1.0.4+745b6b94ee56cad24d475799690cc9a89957d15b

### What platform is your computer?

Darwin 23.0.0 x86_64 i386

### What steps can reproduce the bug?

Ad multilevel glob to package.json
```json
{
  "workspaces": {
    "packages": [
      "packages/**/*"
    ]
  }
}
```

### What is the expected behavior?

Packages in ./packages/**/* are found in subdirectories.

### What do you see instead?

```zsh
bun install v1.0.4 (745b6b94)


error: TODO multi level globs. For now, try something like "packages/*"

      "packages/**/*"
      ^
```

**Comment by Electroid** [comment] 2023-10-09 18:15
Duplicate of #1918

**Closed as not planned** 2023-10-30 19:34 UTC
Labels: bug, bun install
