### ISSUE TITLE
FileNotFound opening root directory ""

### ISSUE THREAD

**Issue by giri-jeedigunta** [oven-sh/bun#6050] opened 2023-09-25 18:26 UTC
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Tried these commands with the existing NextJS 12 project: 

`bun add bun-framework-next`

`bun bun`

### What is the expected behavior?

Bun should be added to existing NextJS project to replace node.

### What do you see instead?

Errors: 

FileNotFound opening root directory ""

### Additional information

Tried running the next app with the below cmd: 

`bun run --bun dev`

```js
~/content/package.json:8:5 266

error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
 6 | (function (LogLevel) {
 7 |     LogLevel[LogLevel["INFO"] = 1] = "INFO";
 8 |     LogLevel[LogLevel["WARN"] = 2] = "WARN";
 9 |     LogLevel[LogLevel["ERROR"] = 3] = "ERROR";
10 | })(LogLevel || (LogLevel = {}));
11 | var stderrConsole = new console_1.Console(process.stderr);
                        ^
TypeError: undefined is not a constructor (evaluating 'new console_1.Console(process.stderr)')
      at ~/content/node_modules/tsconfig-paths-webpack-plugin/lib/logger.js:11:20
      at globalThis (~/content/node_modules/tsconfig-paths-webpack-plugin/lib/logger.js:52:21)
      at require (:1:20)
      at ~/content/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:19:4
      at globalThis (~/content/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:84:30)
      at require (:1:20)
      at ~/content/node_modules/tsconfig-paths-webpack-plugin/lib/index.js:4:4
      at globalThis (~/content/node_modules/tsconfig-paths-webpack-plugin/lib/index.js:15:17)
      at require (:1:20)
      at ~/content/next.config.js:7:6
      at globalThis (~/content/next.config.js:352:81)
      at processTicksAndRejections (:1:2602)
```

commented out `const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin')` and references

```js
Error: Process 97843 doesn't have open IPC channels
Error: Process 97844 doesn't have open IPC channels
error - ./src/pages/_app.tsx
TypeError: undefined is not a constructor (evaluating 'new console_1.Console(process.stderr)')
    at anonymous (native)
    at anonymous (native)
    at anonymous (native)
    at anonymous (native)

error: InvalidPort

----- bun meta -----
Bun v1.0.1 (31aec4eb) macOS Silicon 22.6.0
AutoCommand: bunfig
Elapsed: 3ms | User: 2ms | Sys: 1ms
RSS: 4.69MB | Peak: 4.69MB | Commit: 33.55MB | Faults: 11
----- bun meta -----

0   0x105dccd24 WTFGetBacktrace

Crash report saved to:
  ~/.bun/.bun-crash/v1.0.1-1695666341233.crash
```

**Comment by Electroid** [comment] 2023-09-25 23:07
Duplicate of #5698

**Comment by Electroid** [comment] 2023-09-25 23:08
Also, the error you're seeing here:

```js
TypeError: undefined is not a constructor (evaluating 'new console_1.Console(process.stderr)')
```

This has been fixed, try upgrading using: `bun upgrade`

**Closed as not planned by Electroid** 2023-09-25 23:07 UTC
Labels: bug, crash
