### ISSUE TITLE
Ubuntu/Linux Bun.serve throwing Segmentation error/INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by Eltik** [oven-sh/bun#5947] opened 2023-09-23 02:37 UTC
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Linux 5.15.0-78-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Run `bun init`.
2. Copy the following code into `index.ts`
```ts
Bun.serve({
    port: 3000,
    async fetch(req: Request) {
        return new Response("Hello World");
    }
})
```
3. On Linux/Ubuntu v22, run `bun run index.ts`

### What is the expected behavior?

The server should listen to the port given. I've tested on my other Ubuntu machine and on other ports. The issue does not persist on my MacBook Pro (Darwin 22.4.0 arm64 arm).

### What do you see instead?

<img width="1094" alt="image" src="https://github.com/oven-sh/bun/assets/76538547/5578c9f9-70af-4a5d-ad85-a2979fac3b96">

```
1 | Bun.serve({
  port: 3009,
  async fetch(req) {
    return new Response("Hello World");
  }
});
   ^
TypeError: 湕捩摯⁥潨瑳慮敭⁳畭瑳愠牬慥祤戠⁥湥潣敤⁤潦⁲潮⹷渊睥唠䱒椨灮瑵⸩潨瑳慮敭猠潨汵⁤潤琠敨琠楲正.湉整湲污挠湯楳瑳湥祣攠牲牯›慷捴敨⁲畭整⁸獩氠捯敫⁤桷湥椠⁴桳畯摬渠瑯戠⹥䤀呎㐶呟彏半䅖啌⡅半
 code: "ERR_INVALID_ARG_TYPE"

      at À Ùsting/index.ts:1:0
```

Error does not persist on MacOS! Mainly happens on Ubuntu/Linux.

### Additional information

Issue likely is thrown [here](https://github.com/oven-sh/bun/blob/ee93f1b88c141f1cc5d917a60ddb4a3e2706f1ff/src/bun.js/api/server.zig#L803).

**Comment by Eltik** [comment] 2023-09-23 02:38
If it helps, I've tested on version 1.0.0 as well as the canary build and version 1.0.3. The error exists on all versions.

**Comment by Hanaasagi** [comment] 2023-09-23 02:44
Related to https://github.com/oven-sh/bun/issues/5457 and https://github.com/oven-sh/bun/issues/3312#issuecomment-1704486463

**Comment by Eltik** [comment] 2023-09-23 02:53
Ah thanks. Appreciate it. From what I've gathered, it's a CPU issue. The problem is that I can't change the CPU on my VPS since I'm not renting the actual machine itself. Would it be possible to fix this without modifying the hardware?

**Comment by Hanaasagi** [comment] 2023-09-23 03:03
Could you please try the baseline version in your linux? https://github.com/oven-sh/bun/releases/download/bun-v1.0.3/bun-linux-x64-baseline.zip

**Comment by AeolusDev** [comment] 2023-09-23 15:14
Is this only on linux?
I get no such error on WSL.

**Comment by Electroid** [comment] 2023-09-23 16:32
Duplicate of #3312

**Closed as not planned by Electroid** 2023-09-23 16:32 UTC
Labels: bug
