### ISSUE TITLE
bun file upload on image

### ISSUE THREAD

**Issue by MutedOne** [oven-sh/bun#5198] opened 2023-09-13 03:08 UTC
![image](https://github.com/oven-sh/bun/assets/47779436/6aafca8a-ff32-4874-bb9c-59c076f168d0)
![image](https://github.com/oven-sh/bun/assets/47779436/c2d072e6-4d54-4e23-a703-868ec1f0df64)
![image](https://github.com/oven-sh/bun/assets/47779436/9e82bc03-6c19-4725-a3e3-9eaffabdae77)

it doesn't replace or create the "file" and error code 1 SIGHUP

**Comment by MutedOne** [comment] 2023-09-13 04:13
Is there problem with wsl?

**Comment by Electroid** [comment] 2023-10-27 22:31
Duplicate of https://github.com/oven-sh/bun/issues/5960

**Closed as not planned by Electroid** 2023-10-27 22:31 UTC
Labels: bug, bun.js
