### ISSUE TITLE
Reading files with `Bun.file` fails in Cloudflare Pages build image

### ISSUE THREAD

**Issue by oliverjam** [oven-sh/bun#5861] opened 2023-09-21 13:48 UTC
### What version of Bun is running?

1.0.2

### What platform is your computer?

Ubuntu 22.04.2

### What steps can reproduce the bug?

Trying to read a file during a build on Cloudflare Pages with `Bun.file`:

```js
let file = Bun.file("README.md");
console.log(file);
let content = await file.text();
console.log(content);
```

### What is the expected behavior?

Bun should not error when reading a file that exists.

### What do you see instead?

Logs:
```
14:14:36.303    FileRef ("README.md") {
14:14:36.306      type: "text/markdown"
14:14:36.306    }
14:14:36.307    error: script "build" exited with code 1 (SIGHUP)
```

The file exists but the second I try to read it Bun errors. I can read it fine with Node's `fs.readFile`, so the issue appears to be Bun-specific.

### Additional information

I think this is the same problem as #5479, except Cloudflare Pages' build image is running Ubuntu 22.04.2 with 6.3.13-linuxkit (according to a CF engineer on Discord), so not an outdated kernel.

Any idea what's going on?

**Comment by Electroid** [comment] 2023-09-21 20:04
> The file exists but the second I try to read it Bun errors. I can read it fine with Node's fs.readFile, so the issue appears to be Bun-specific.

Are you saying that running `fs.readFile` on your machine in Bun works?

**Comment by oliverjam** [comment] 2023-09-21 22:12
Yeah `fs.readFile` worked. You can see the actual process of elimination I went through in the commits on [this PR](https://github.com/oliverjam/oliverjames-v4/pull/1). This is [the commit](https://github.com/oliverjam/oliverjames-v4/pull/1/commits/2d1a307cea4952b6cbe06ddcceab200551d8a0d5) where I tried `readFile` and the build passed.

Edit: I should probably mention I saw the same issue with `Bun.file(path).arrayBuffer()`—it's not limited to just `.text()`

**Comment by Electroid** [comment] 2023-10-30 18:43
Duplicate of #5960

**Closed as not planned by Electroid** 2023-10-30 18:43 UTC
Labels: bug, bun.js
