### ISSUE TITLE
missing correct message error when using await inside a non async function

### ISSUE THREAD

**Issue by huilensolis** [oven-sh/bun#8339] opened 2024-01-22 00:42 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.5.5-arch1-1 x86_64

### What steps can reproduce the bug?

```js
async function test(){
   const a = await fetch('/asdfas')
   return Promise.resolve({test: a})
}

function run(){
  const { test } = await test()
}
```

### What is the expected behavior?

a more descriptive message, something like what the linters do.

 "'await' expressions are only allowed within async functions and at the top levels of modules"

### What do you see instead?

```js
error: Expected ";" but found "test"

  const {test} = await test()
                       ^
/home/huilensolis/test.js:7:24 137


error: Expected "=>" but found "}"

}
^
/home/huilensolis/test.js:8:1 144
```

**Comment by Electroid** [comment] 2024-01-22 16:37
Duplicate of #108

**Closed as not planned by Electroid** 2024-01-22 16:37 UTC
Labels: bug
