### ISSUE TITLE
Bun install v1.1.20 crash in docker build

### ISSUE THREAD

**Issue by dennicLiu** [oven-sh/bun#12622] opened 2024-07-17 09:39 UTC
### Relevant log output

```shell
593.8  index.d.ts
593.8  LICENSE.txt
593.9 [PackageManager] waiting for 694 tasks
594.2 [PackageManager] waiting for 693 tasks
595.2 [PackageManager] waiting for 693 tasks
596.2 [PackageManager] waiting for 693 tasks
596.2 [PackageManager] waiting for 693 tasks
597.2 [PackageManager] waiting for 693 tasks
598.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.2 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
599.3 [PackageManager] waiting for 693 tasks
600.2 [PackageManager] waiting for 693 tasks
600.2 [PackageManager] waiting for 693 tasks
600.2 [PackageManager] waiting for 693 tasks
601.2 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
601.3 [PackageManager] waiting for 693 tasks
602.2 [PackageManager] waiting for 693 tasks
603.2 [PackageManager] waiting for 693 tasks
604.2 [PackageManager] waiting for 693 tasks
604.2 [PackageManager] waiting for 693 tasks
605.2 [PackageManager] waiting for 693 tasks
606.2 [PackageManager] waiting for 693 tasks
607.2 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 [PackageManager] waiting for 693 tasks
607.4 ============================================================


Dockerfile:12
--------------------
  10 |     COPY bun.lockb ./
  11 |
  12 | >>> RUN bun install --verbose
  13 |
  14 |     COPY . .
--------------------
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on linux x86_64 [InstallCommand]

Segmentation fault at address 0x000000B0

- `??`
- [`http.zig:0`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/http.zig#L0>): `src.http.writeRequest__anon_151227`
- [`uws.zig:977`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/uws.zig#L977>): `src.deps.uws.NewSocketHandler`
- [`bsd.c:497`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/bsd.c#L497>): `us_socket_write`
- [`epoll_kqueue.c:487`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/eventing/epoll_kqueue.c#L487>): `us_timer_close`
- [`array_hash_map.zig:2022`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/zig/lib/std/array_hash_map.zig#L2022>): `src.http.HTTPThread.processEvents`
- [`string_immutable.zig:885`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/string_immutable.zig#L885>): `src.http.NewHTTPContext`
- `??`

**Comment by rohit-nayak123** [comment] 2024-07-17 10:42
Hey, I too have a similar problem. In my project bun is not installing the optional dependencies during dockerization.

**Comment by dennicLiu** [comment] 2024-07-18 02:22
ERROR: failed to solve: process "/bin/sh -c bun install --verbose" did not complete successfully: exit code: 132

**Comment by Jarred-Sumner** [comment] 2024-07-18 02:24
Duplicate of https://github.com/oven-sh/bun/issues/12591

**Closed as not planned by Jarred-Sumner** 2024-07-18 02:24 UTC
Labels: bun install
