### ISSUE TITLE
setInterval Takes 100% CPU Usage

### ISSUE THREAD

**Issue by zytanic** [oven-sh/bun#652] opened 2022-07-12 22:32 UTC
### Version

0.1.3

### Platform

Linux test 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

### What do you see instead?

![image](https://user-images.githubusercontent.com/78568660/178608816-6ffea58a-4c0a-4786-b36e-144aa5058782.png)
![image](https://user-images.githubusercontent.com/78568660/178608925-dfb3825b-b3dd-48c4-a3d1-6191a6568880.png)

**Comment by Jarred-Sumner** [comment] 2022-07-13 05:10
Duplicate of #490 

Or rather, it's the same underlying cause

**Closed as completed by Jarred-Sumner** 2022-07-13 05:10 UTC
Labels: bug, needs repro
