### ISSUE TITLE
Using await inside a try...catch block removes the stack trace and other variables.

### ISSUE THREAD

**Issue by NyxaYu** [oven-sh/bun#5719] opened 2023-09-19 06:19 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

Using await inside a try...catch block removes the stack trace and other variables. Sample code:

```js
(async () => {
	try{
		throw new Error('test');
	}catch(error){
		await new Promise(resolve => setTimeout(() => resolve(), 1));
		console.error(error);
		console.log(Object.getOwnPropertyNames(error));
	}
})();
```

Which outputs:

```
error: test

[ "message" ]
```

### What is the expected behavior?

The code should output a valid stack trace for debugging. Sample code:

```js
(async () => {
	try{
		throw new Error('test');
	}catch(error){
		// await new Promise(resolve => setTimeout(() => resolve(), 1));
		console.error(error);
		console.log(Object.getOwnPropertyNames(error));
	}

	console.log('oki');
})();
```

Which outputs:
```
1 | (async () => {
2 |     try{
3 |             throw new Error('test');
            ^
error: test
      at test.js:3:8
      at test.js:1:1
      at test.js:10:18

[ "message", "originalLine", "originalColumn", "line", "column", "sourceURL", "stack" ]
```

Note: Directory removed from stack trace for privacy.

### Additional information
Moving the `console.error(error);` above the await statement fixes the issue.

_No response_

**Comment by Electroid** [comment] 2023-10-28 00:27
Duplicate of #2704

**Closed as not planned by Electroid** 2023-10-28 00:27 UTC
Labels: bug
