### ISSUE TITLE
Bun crashes

### ISSUE THREAD

**Issue by metaspartan** [oven-sh/bun#12021] opened 2024-06-20 23:26 UTC
### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x00000020

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/ld-temp.o#L0>): `end_hquery`

**Comment by Jarred-Sumner** [comment] 2024-06-20 23:56
Duplicate of https://github.com/oven-sh/bun/issues/11882

**Comment by Jarred-Sumner** [comment] 2024-06-20 23:56
We are tracking this in https://github.com/oven-sh/bun/issues/11882, please follow along in that issue

**Closed as completed by Jarred-Sumner** 2024-06-20 23:56 UTC
Labels: crash, linux
