### ISSUE TITLE
Bun hangs on `createPool` with postgres library `slonik`

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#6061] opened 2023-09-26 02:42 UTC
Reproducible  repository here: https://github.com/cooperaustinj/bun-slonik-issue

Bun simply freezes with no output. I'm not sure how I can get more information about the issue.

Slonik: https://github.com/gajus/slonik

_Originally reported on Discord: [`Bun freezes when used with slonik. Any ideas for debugging/workarounds?`](https://discord.com/channels/876711213126520882/1155612258928431226/1155612258928431226)_

**Comment by cooperaustinj** [comment] 2023-09-26 05:03
The discord bot made a duplicate of the issue I created for this: https://github.com/oven-sh/bun/issues/6018

**Comment by Electroid** [comment] 2023-09-26 15:47
Duplicate of #6018

**Closed as not planned by Electroid** 2023-09-26 15:47 UTC
