### ISSUE TITLE
EBADF: Bad file descriptor  on Ubuntu (Bun.file)

### ISSUE THREAD

**Issue by rajeshpillai** [oven-sh/bun#5797] opened 2023-09-20 10:33 UTC
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.4.0-156-generic x86_64 x86_64

### What steps can reproduce the bug?

 const mdFile = await Bun.file(filePath, { type: "text/markdown" });
 const md = await mdFile.text();

Throwing error at mdFile.text() method.  Yes, the file is present in the current directly, verified the file exist in the correct path as well.

### What is the expected behavior?

The content of the file should be be returned back.

### Additional information

I see EBADF: Bad file descriptor

**Comment by Electroid** [comment] 2023-09-20 16:36
Duplicate of #1446

**Closed as completed by Electroid** 2023-09-20 16:36 UTC
Labels: bug, bun.js
