### ISSUE TITLE
Add SQLite cursor API

### ISSUE THREAD

**Issue by broccolihighkicks** [oven-sh/bun#10925] opened 2024-05-08 12:16 UTC
### What is the problem this feature would solve?

Queries must load all of the data into RAM. But SQLite has a cursor API which would allow row at a time processing. Combined with read transactions this is useful for larger than RAM datasets.

### What is the feature you are proposing to solve the problem?

A JS API mapped to the C cursor API

### What alternatives have you considered?

Buy more RAM or delete some data.

**Comment by SoundOfTheSky** [comment] 2024-07-24 08:52
Duplicate of #8507

**Closed as completed** 2024-10-12 04:43 UTC
Labels: enhancement, bun:sqlite
