### ISSUE TITLE
Crash when overriding dependency with local package

### ISSUE THREAD

**Issue by hborchardt** [oven-sh/bun#12964] opened 2024-07-31 10:07 UTC
### How can we reproduce the crash?

Have this `./package.json` file:
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@swagger-api/apidom-ls": "0.81.0"
  },
  "overrides": {
     "@swagger-api/apidom-parser-adapter-yaml-1-2": "..\\..\\o"
  }
}
```
As well as a `./o/package.json` file:
```json
{
  "name": "o",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

Run `bun i`, it reports this:
```
bun install v1.1.21 (70ca2b76)
error: moving "@swagger-api/apidom-parser-adapter-json" to cache dir failed
EPERM: Operation not permitted (NtSetInformationFile())
  From: .17f7fffcfafdebff-00000014.apidom-parser-adapter-json
    To: @swagger-api/apidom-parser-adapter-json@0.81.0@@@1

error: InstallFailed extracting tarball from @swagger-api/apidom-parser-adapter-json
```
Run `bun i` a second time, and it gives the crash.

### Relevant log output

```shell
bun install v1.1.21 (70ca2b76)
  🔒 Saving lockfile... ============================================================
Bun v1.1.21 (70ca2b76) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\nice\bin\bun.exe" "i"
Features: binlinks(2) 
Elapsed: 2232ms | User: 78ms | Sys: 5046ms
RSS: 0.15GB | Peak: 0.15GB | Commit: 0.25GB | Faults: 38029

panic(main thread): Internal assertion failure
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:439`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/deps/zig/lib/std/debug.zig#L439>): `panicExtra`
- [`bun.zig:3297`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.zig#L3297>): `assertionFailure`
- [`lockfile.zig:2035`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/lockfile.zig#L2035>): `saveToDisk`
- [`install.zig:7371`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/install/install.zig#L7371>): `save`
- [`string_immutable.zig:822`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/string_immutable.zig#L822>): `eqlComptimeCheckLenU8`
- [`cli.zig:1377`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/cli.zig#L1377>): `which`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/main.zig#L51>): `main`
- [`dloadsup.h:335`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/vctools/delayimp/dloadsup.h#L335>): `DloadUnlock`
- ??? at `0x1257d` in KERNEL32.DLL

**Comment by Electroid** [comment] 2024-09-06 00:41
Duplicate of #11250

**Closed as not planned by Electroid** 2024-09-06 00:41 UTC
Labels: bun install
