### ISSUE TITLE
Escaped " in package.json are not escaped inside bun run

### ISSUE THREAD

**Issue by Twiggeh** [oven-sh/bun#896] opened 2022-07-28 06:52 UTC
### Version

0.1.5

### Platform

Linux twiggeh-linux 5.18.6-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jun 22 14:16:20 UTC 2022 x86_64 GNU/Linux

### What steps will reproduce the bug?

package.json
```json
{
    "scripts": { 
        "test": "externalProgram --argument \"somePrefix $ENV_VARIABLE\""
    }
}
```

`bun test`
`yarn test`

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

That the command that is being run is (like yarn / npm): 
`externalProgram --argument "somePrefix superSecret"`

### What do you see instead?

That the command that is being run is: 
`externalProgram --argument \"somePrefix superSecret\"`

Errors occur like ' "somePrefix' bad input etc

**Comment by Twiggeh** [comment] 2022-07-28 07:00
current workaround :

```
"test": "externalProgram --argument somePrefix\\ $ENV_VARIABLE"
```

**Comment by Electroid** [comment] 2022-11-03 00:00
Also duplicate of #794

**Closed as completed by Electroid** 2022-11-03 00:00 UTC
Labels: bug
