### ISSUE TITLE
Next.js crash when middleware.ts is used

### ISSUE THREAD

**Issue by jlucaso1** [oven-sh/bun#9447] opened 2024-03-15 21:19 UTC
### What version of Bun is running?

1.0.31+e25675121

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create a nextjs project and add a simple middleware.ts in src folder.
Command: `bun --bun dev`
Example:
```ts
// src/middleware.ts
import { NextRequest, NextResponse } from "next/server";

export default function pathnameMiddleware(request: NextRequest) {
	const requestHeaders = new Headers(request.headers);
	requestHeaders.set("x-pathname", request.nextUrl.pathname);

	const query = request.nextUrl.searchParams;
	const redirectUrl = query.get("redirect_url");

	requestHeaders.set("x-search-params", request.nextUrl.search);

	if (redirectUrl) {
		requestHeaders.set("x-redirect-url", redirectUrl);
	}

	return NextResponse.next({
		request: {
			headers: requestHeaders,
		},
	});
}

export const config = {
	matcher: [
		"/((?!api|_next/static|_next/image|favicon.ico).*)",
	],
};

```

### What is the expected behavior?

Don't crash

### What do you see instead?

```bash
   ▲ Next.js 14.1.3 (turbo)
   - Local:        http://localhost:3000
   - Environments: .env.local

 ✓ Ready in 998ms
 ⨯ error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (file:///home/jlucaso/projects/t3x-barber/node_modules/next/dist/compiled/edge-runtime/index.js:1:1)
      at addPrimitives (file:///home/jlucaso/projects/t3x-barber/node_modules/next/dist/compiled/edge-runtime/index.js:13902:25)
      at extend (file:///home/jlucaso/projects/t3x-barber/node_modules/next/dist/compiled/edge-runtime/index.js:13854:113)
      at new VM (file:///home/jlucaso/projects/t3x-barber/node_modules/next/dist/compiled/edge-runtime/index.js:13946:88)
      at new EdgeVM (file:///home/jlucaso/projects/t3x-barber/node_modules/next/dist/compiled/edge-runtime/index.js:13854:16)
      at file:///home/jlucaso/projects/t3x-barber/node_modules/next/dist/server/web/sandbox/context.js:96:163

 ○ Compiling /_error ...
 ✓ Compiled /_error in 579ms
 ○ Compiling /not-found ...
```
and a massive random string

### Additional information

Nextjs version: `14.1.3`

**Comment by Electroid** [comment] 2024-03-15 22:30
Duplicate of #5648

**Closed as not planned by Electroid** 2024-03-15 22:30 UTC
Labels: bug, web-api
