### ISSUE TITLE
Install crash

### ISSUE THREAD

**Issue by JeffJacobson** [oven-sh/bun#12439] opened 2024-07-08 21:56 UTC
### How can we reproduce the crash?

- I was doing a git rebase of a branch with a bun package lock file to one with a npm package lock file.
- After resolving a conflict with the package.json file, I ran `bun install --lock-only` and got the error.
- I was able to work around this by deleting the bun lockfile and node_modules folder and then running `bun install`. (I don't know if I needed to delete both.)

### Relevant log output

```shell
bun install --lock-only
[0.50ms] ".env"
bun install v1.1.15 (b23ba1fe)
  📦 Installing [23/664] ============================================================
Bun v1.1.15 (b23ba1fe) Windows x64
Args: "C:\Users\[username]\.bun\bin\bun.exe" "install" "--lock-only"
Features: bunfig dotenv extracted_packages(6) 
Elapsed: 4466ms | User: 140ms | Sys: 4390ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 0.25GB | Faults: 40697

panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:4885`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/install/install.zig#L4885>): `enqueueDependencyWithMain`
- [`install.zig:5772`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/install/install.zig#L5772>): `processDependencyList`
- [`install.zig:6595`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/install/install.zig#L6595>): `runTasks`
- [`install.zig:12707`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/install/install.zig#L12707>): `installPackages`
- [`install.zig:13531`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/install/install.zig#L13531>): `installWithManager`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1466`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli.zig#L1466>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/src/startup/exe_common.inl#L78>): `invoke_main`

**Comment by dylan-conway** [comment] 2024-07-08 22:00
Duplicate of https://github.com/oven-sh/bun/issues/9932

**Closed as not planned** 2024-07-08 22:00 UTC
Labels: crash, bun install, windows

**Comment by JeffJacobson** [comment] 2024-07-09 18:10
> @JeffJacobson, the latest version of Bun is v1.1.17, but this crash was reported on Bun v1.1.15.
> 
> Are you able to reproduce this crash on the latest version of Bun?
> 
> ```shell
> bun upgrade
> ```

No, and I couldn't reproduce again before upgrading. I'm not sure of the exact conditions that caused it, and it's working now. I only created the issue because the error message suggested I do so.
