### ISSUE TITLE
Crash when building with mongoose

### ISSUE THREAD

**Issue by vexcited** [oven-sh/bun#6522] opened 2023-10-15 20:34 UTC
### What version of Bun is running?

1.0.6+969da088f5db3258a803ec186012e30f992829b4

### What platform is your computer?

Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 unknown

### What steps can reproduce the bug?

Make a new Bun project `mkdir mongoose-error && cd mongoose-error && bun init` (y to everything)

Install `mongoose`: `bun add mongoose`

You don't even need to start a MongoDB server, the issue is here whenever you import and use `mongoose`.

Inside `index.ts` write the following...

```typescript
import mongoose from "mongoose";
mongoose; // just so the bundler understands we used it
```

Now bundle using `bun build ./index.ts --outdir=dist --target=bun`

### What is the expected behavior?

Bundles in `./dist` successfully

### What do you see instead?

```console
uh-oh: Internal error: missing asset file
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.0.6 (969da088) Linux x64 #1 SMP Fri Apr 2 22:23:49 UTC 2021
BuildCommand:
Elapsed: 68ms | User: 178ms | Sys: 192ms
RSS: 0.20GB | Peak: 0.16GB | Commit: 0.20GB | Faults: 0
----- bun meta -----

0   0x557cab7dc6bb
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???
9   ???
10  ???
11  ???
12  ???
13  ???

Crash report saved to:
  ~/.bun/.bun-crash/v1.0.6-1697401862950.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 28160 panic: Internal error: missing asset file
Unwind information for `:0x557caae77bf0` was not available, trace may be incomplete

[1]    28160 IOT instruction  bun build ./index.ts --outdir=dist --target=bun
```

### Additional information

When removing `mongoose` from the build using `--external mongoose` (so `bun build ./index.ts --outdir=dist --target=bun --external mongoose`) it works without any issue.

The installed version is `mongoose@7.6.2`

Also doesn't work on `mongoose@6.x` but works on `mongoose@5.x`
![image](https://github.com/oven-sh/bun/assets/59152884/94e06083-9b1e-47e3-a246-d1f10a29e616)

**Comment by Electroid** [comment] 2023-10-16 16:49
Related #6437

**Comment by Jarred-Sumner** [comment] 2023-12-05 12:43
Duplicate of #3903

**Closed as not planned by Jarred-Sumner** 2023-12-05 12:43 UTC
Labels: bug, crash, bundler

**Comment by RajaShanmugamJM** [comment] 2023-12-31 10:50
> ### What version of Bun is running?
> 1.0.6+969da088f5db3258a803ec186012e30f992829b4
> 
> ### What platform is your computer?
> Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 unknown
> 
> ### What steps can reproduce the bug?
> Make a new Bun project `mkdir mongoose-error && cd mongoose-error && bun init` (y to everything)
> 
> Install `mongoose`: `bun add mongoose`
> 
> You don't even need to start a MongoDB server, the issue is here whenever you import and use `mongoose`.
> 
> Inside `index.ts` write the following...
> 
> ```ts
> import mongoose from "mongoose";
> mongoose; // just so the bundler understands we used it
> ```
> 
> Now bundle using `bun build ./index.ts --outdir=dist --target=bun`
> 
> ### What is the expected behavior?
> Bundles in `./dist` successfully
> 
> ### What do you see instead?
> ```
> uh-oh: Internal error: missing asset file
> bun will crash now 😭😭😭
> 
> ----- bun meta -----
> Bun v1.0.6 (969da088) Linux x64 #1 SMP Fri Apr 2 22:23:49 UTC 2021
> BuildCommand:
> Elapsed: 68ms | User: 178ms | Sys: 192ms
> RSS: 0.20GB | Peak: 0.16GB | Commit: 0.20GB | Faults: 0
> ----- bun meta -----
> 
> 0   0x557cab7dc6bb
> 1   ???
> 2   ???
> 3   ???
> 4   ???
> 5   ???
> 6   ???
> 7   ???
> 8   ???
> 9   ???
> 10  ???
> 11  ???
> 12  ???
> 13  ???
> 
> Crash report saved to:
>   ~/.bun/.bun-crash/v1.0.6-1697401862950.crash
> 
> Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
> 
> thread 28160 panic: Internal error: missing asset file
> Unwind information for `:0x557caae77bf0` was not available, trace may be incomplete
> 
> [1]    28160 IOT instruction  bun build ./index.ts --outdir=dist --target=bun
> ```
> 
> ### Additional information
> When removing `mongoose` from the build using `--external mongoose` (so `bun build ./index.ts --outdir=dist --target=bun --external mongoose`) it works without any issue.
> 
> The installed version is `mongoose@7.6.2`
> 
> Also doesn't work on `mongoose@6.x` but works on `mongoose@5.x` ![image](https://private-user-images.githubusercontent.com/59152884/275353496-94e06083-9b1e-47e3-a246-d1f10a29e616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjAwNzksIm5iZiI6MTcwNDAxOTc3OSwicGF0aCI6Ii81OTE1Mjg4NC8yNzUzNTM0OTYtOTRlMDYwODMtOWIxZS00N2UzLWEyNDYtZDFmMTBhMjllNjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDEwNDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNDNlMDc1NThmZjcxZTM4YjE3NDZhYjkxOWJmZDM1MmMyMjJmOGY1NGRmMWFkOTU2MmMxOTA2MDkzZTJiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HnTKcKWq0UbzVYDK36syER5SzlJrOtUOgAUyrBYtAZY)

adding `--external` flag allows to build. Tested with mongoose version `^8.0.3`
