### ISSUE TITLE
Typegoose prop() decorator causes error: Type is invalid! Type is: "undefined"

### ISSUE THREAD

**Issue by igoramidzic** [oven-sh/bun#5764] opened 2023-09-19 20:42 UTC
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. `$ bun init -y`
2. `$ bun i @typegoose/typegoose@11.5.0 mongoose@7.5.2`
3. Update `index.ts`
```
// index.ts

import { prop, getModelForClass } from '@typegoose/typegoose';
class User {
  @prop()
  name!: string;
}
export const UserModel = getModelForClass(User);

```
4. `$ bun index.ts`

### What is the expected behavior?

Expect index.ts file to run without errors.

### What do you see instead?

```
exports.CacheDisabledError = exports.DuplicateOptionsError = exports.NoDiscriminatorFunctionError = exports.PathNotInSchemaError = exports.InvalidOptionsConstructorError = exports.InvalidEnumTypeError = exports.ExpectedTypeError = exports.ResolveTypegooseNameError = exports.OptionDoesNotSupportOptionError = exports.StringLengthExpectedError = exports.FunctionCalledMoreThanSupportedError = exports.NotValidModelError = exports.RefOptionIsUndefinedError = exports.SelfContainingClassError = exports.CannotBeSymbolError = exports.InvalidPropTypeError = exports.AssertionFallbackError = exports.NoValidClassError = exports.NotAllVPOPElementsError = exports.NotStringTypeError = exports.NotNumberTypeError = exports.InvalidTypeError = void 0;
4 | const utils_1 = require("./utils");
5 | // Note: don't forget to use "toStringNoFail" on values that are "unknown" or "any"
6 | class InvalidTypeError extends Error {
7 |     constructor(targetName, key, Type) {
8 |         super(`"${targetName}.${key}"'s Type is invalid! Type is: "${(0, utils_1.toStringNoFail)(Type)}" [E009]`);
            ^
error: "User.name"'s Type is invalid! Type is: "undefined" [E009]
      at new InvalidTypeError (/Users/igoramidzic/code/bun-test/node_modules/@typegoose/typegoose/lib/internal/errors.js:8:8)
      at processProp (/Users/igoramidzic/code/bun-test/node_modules/@typegoose/typegoose/lib/internal/processProp.js:207:14)
      at _buildSchema (/Users/igoramidzic/code/bun-test/node_modules/@typegoose/typegoose/lib/internal/schema.js:35:12)
      at buildSchema (/Users/igoramidzic/code/bun-test/node_modules/@typegoose/typegoose/lib/typegoose.js:145:4)
      at getModelForClass (/Users/igoramidzic/code/bun-test/node_modules/@typegoose/typegoose/lib/typegoose.js:77:40)
      at /Users/igoramidzic/code/bun-test/index.ts:6:25
      at processTicksAndRejections (:55:76)
```

### Additional information

Its something to do with the `prop()`.
It works if I remove it:

```
import { prop, getModelForClass } from '@typegoose/typegoose';
class User {
  //@prop()
  name!: string;
}
export const UserModel = getModelForClass(User);

```

**Comment by Electroid** [comment] 2023-09-19 21:35
We'll need to add decorator support, which is almost done and is being tracked in another issue.

Duplicate of #4136

**Closed as not planned by Electroid** 2023-09-19 21:35 UTC
Labels: bug
