### ISSUE TITLE
Errors when starting hapi server while testing

### ISSUE THREAD

**Issue by marc-niclas** [oven-sh/bun#8161] opened 2024-01-13 21:59 UTC
### What version of Bun is running?

1.0.22+b400b36ca

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

I'm getting a strange error when starting a hapi server to run an API test

```
// myTest.test.ts
import { init } from '../server';
import { mock, afterAll, beforeAll, describe, it } from 'bun:test';

let server: Server;

describe('GET /api/v1/...', () => {
  beforeAll(async () => {
    server = await init();
  });

  it(...)
});
```

Here's my init code, nothing special, with manifest defining my API routes and options simply `{ relativeTo: __dirname }`:
```
// server.ts
let server: Server;

export async function init(): Promise<Server> {
  server = await Glue.compose(manifest, options);
  return server;
}
```

I realize this may be difficult to replicate, given how highly specific the nature of the problem is to my repo. Any insight here is helpful, as I can't find anything online or in this GitHub

### What is the expected behavior?

Test passes, as it does with `npm test`.

Interestingly, if I run `bun dev`, which is simply a script for `ts-node-dev --respawn --transpile-only ./src/index.ts`, it will start my hapi server with no problems, even though it is running the same `init` function.

### What do you see instead?

This is the error I get:
```
src/tests/myTest.test.ts:
✗ GET /api/v1/... > responds with 200
37 |         Validate.assert(options, internals.schema, 'Invalid load monitoring options');
38 |         this.settings = Hoek.applyToDefaults(internals.defaults, options);
39 |         Hoek.assert(this.settings.sampleInterval || (!this.settings.maxEventLoopDelay && !this.settings.maxHeapUsedBytes && !this.settings.maxRssBytes && !this.settings.maxEventLoopUtilization), 'Load sample interval must be set to enable load limits');
40 |
41 |         this._eventLoopTimer = null;
42 |         this._eventLoopUtilization = PerfHooks.performance.eventLoopUtilization();
                                          ^
TypeError: PerfHooks.performance.eventLoopUtilization is not a function. (In 'PerfHooks.performance.eventLoopUtilization()', 'PerfHooks.performance.eventLoopUtilization' is undefined)
      at new Heavy (/Users/mnhmbp/PycharmProjects/my-app/node_modules/@hapi/heavy/lib/index.js:42:38)
      at new  (/Users/mnhmbp/PycharmProjects/my-app/node_modules/@hapi/hapi/lib/core.js:122:22)
      at /Users/mnhmbp/PycharmProjects/my-app/node_modules/@hapi/hapi/lib/server.js:22:18
      at /Users/mnhmbp/PycharmProjects/my-app/node_modules/@hapi/glue/lib/index.js:34:20
      at processTicksAndRejections (:61:77)
      at /Users/mnhmbp/PycharmProjects/my-app/packages/server/src/tests/myTest.test.ts:21:1
      at processTicksAndRejections (:61:77)
```

### Additional information

For what's worth, my hapi related dependencies:
```
    "@hapi/bell": "^13.0.0",
    "@hapi/boom": "^10.0.0",
    "@hapi/glue": "^9.0.0",
    "@hapi/h2o2": "^10.0.0",
    "@hapi/hapi": "^21.2.0",
    "@hapi/inert": "^7.1.0",
    "@hapi/joi": "^17.1.1",
```

**Comment by Electroid** [comment] 2024-01-13 22:22
Duplicate of #5804

**Closed as not planned by Electroid** 2024-01-13 22:22 UTC
Labels: bug
