### ISSUE TITLE
Bun crashed with running `bunx sv create`

### ISSUE THREAD

**Issue by ThatMarko** [oven-sh/bun#15021] opened 2024-11-06 16:50 UTC
### How can we reproduce the crash?

How to reproduce (Windows 11 Pro, Version 24H2, Build 26120.2213, Bun v1.1.34):

PowerShell in Terminal app

```╰─ bunx sv create my-skeleton-app
┌  Welcome to the Svelte CLI! (v0.6.1)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  prettier, eslint, vitest, playwright, tailwindcss, drizzle, lucia, mdsvex, paraglide, storybook
│
◇  tailwindcss: Which plugins would you like to add?
│  none
│
◇  drizzle: Which database would you like to use?
│  SQLite
│
◇  drizzle: Which SQLite client would you like to use?
│  Turso
│
◇  lucia: Do you want to include a demo? (includes a login/register page)
│  Yes
============================================================
Bun v1.1.34 (5e5e7c60) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "bun" "C:\Users\marko\AppData\Local\Temp\bunx-579857038-sv@latest\node_modules\sv\dist\bin.js" "create" "my-skeleton-app"
Features: Bun.stdin(2) Bun.stdout jsc spawn
Builtins: "bun:main" "node:buffer" "node:child_process" "node:events" "node:fs" "node:fs/promises" "node:module" "node:os" "node:path" "node:process" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:tty" "node:url" "node:util/types" "node:zlib"
Elapsed: 78357ms | User: 1203ms | Sys: 593ms
RSS: 0.22GB | Peak: 0.24GB | Commit: 0.26GB | Faults: 88403

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.34/wa15e5e7c6AsggkgC___8o00jC__s3tnkC___A2AK
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *3 unknown/js code*
- [`LLIntSlowPaths.cpp:946`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L946>): `llint_slow_path_get_by_id`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, fetch, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5616831444/">BUN-2B1</a></strong></sub>

**Comment by Jarred-Sumner** [comment] 2024-11-07 04:57
Not yet able to reproduce on macOS/Linux

**Comment by nektro** [comment] 2024-11-08 21:58
duplicate of https://github.com/oven-sh/bun/issues/14926

**Closed as not planned by nektro** 2024-11-08 21:58 UTC
Labels: crash, windows, runtime
