### ISSUE TITLE
Unhandled Rejections within async functions

### ISSUE THREAD

**Issue by SheetJSDev** [oven-sh/bun#970] opened 2022-08-02 19:46 UTC
1) Bun 0.1.6 prints no error message and successfully ends when an async function or IIFE throws an error that is not caught:

```js
import { promises as fs } from 'fs';
(async() => {
  console.log(await fs.readFile('./this_file_exists'));
  console.log(await fs.readFile('./this_file_does_not_exist'));
  console.log(await fs.readFile('./this_file_exists'));
})();
```

Testing:

```bash
$ touch this_file_exists
$ rm -f this_file_does_not_exist
$ bun error.mjs; echo $?
Uint8Array(0) [  ] ### <-- this is the first read result
0                  ### <-- process exited successfully
```

(to contrast, Node 18.7.0 exits with status code 1 and prints the error by default).

2) The `unhandledRejection` handler in `process` is not called:

```js
import process from 'process';
process.on('unhandledRejection', e => console.log(`!! ${e.message} !!`));

import { promises as fs } from 'fs';
(async() => {
  console.log(await fs.readFile('./this_file_exists'));
  console.log(await fs.readFile('./this_file_does_not_exist'));
  console.log(await fs.readFile('./this_file_exists'));
})();
```

(if the callback was called, the error message would be printed)

**Comment by Jarred-Sumner** [comment] 2022-08-02 21:07
Duplicate of https://github.com/oven-sh/bun/issues/953

**Closed as completed by Jarred-Sumner** 2022-08-02 21:07 UTC
