### ISSUE TITLE
Segfault in Bun v1.1.29 when using "gl" package 

### ISSUE THREAD

**Issue by nachat-ayoub** [oven-sh/bun#14138] opened 2024-09-24 13:44 UTC
### How can we reproduce the crash?

 I encountered a segmentation fault while trying to run my TypeScript file (createVideo.ts) that uses the [FFCreator](https://github.com/tnfe/FFCreator) with Bun. The error occurred when executing a function related to loading a dynamic link library (DLL).
 
 
 Environment:

Bun Version: v1.1.29 (latest stable)
Node Version: v22.9.0
Operating System: Windows 11
Architecture: x64
CPU Features: SSE4.2, AVX, AVX2

### Relevant log output

```shell
elysia-app git:(master) bun run .\src\createVideo.ts
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at bindings (C:\Users\...\elysia-app\node_modules\bindings\bindings.js:112:48)
      at C:\Users\...\elysia-app\node_modules\gl\src\javascript\native-gl.js:1:7
      at C:\Users\...\elysia-app\node_modules\gl\src\javascript\webgl-rendering-context.js:4:42
      at C:\Users\...\elysia-app\node_modules\gl\src\javascript\node-index.js:3:32
      at C:\Users\...\elysia-app\node_modules\gl\index.js:4:10
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\canvas-gl.js:120:11
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\polyfill\Canvas.js:7:5
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\polyfill\Doc.js:8:15
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\renderers\SystemRenderer.js:11:12
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\renderers\canvas\CanvasRenderer.js:7:23
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\core.js:318:23
      at C:\Users\...\elysia-app\node_modules\inkpaint\lib\index.js:480:5
      at C:\Users\...\elysia-app\node_modules\ffcreator\lib\node\cons.js:16:20
      at C:\Users\...\elysia-app\node_modules\ffcreator\lib\creator.js:23:7
      at C:\Users\...\elysia-app\node_modules\ffcreator\lib\index.js:14:7

Bun v1.1.29 (Windows x64)
============================================================
Bun v1.1.29 (6d43b366) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\Nachat Ayoub\.bun\bin\bun.exe" "run" ".\src\createVideo.ts"
Features: jsc transpiler_cache(2) tsconfig(4) 
Builtins: "bun:main" "node:assert" "node:buffer" "node:constants" "node:crypto" "node:events" "node:fs" "node:os" "node:path" "node:stream" "node:string_decoder" "node:util" "node:util/types" 
Elapsed: 1499ms | User: 62ms | Sys: 62ms
RSS: 0.15GB | Peak: 0.15GB | Commit: 0.17GB | Faults: 36790

panic(main thread): Segmentation fault at address 0x7FF915A71947
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x7FF915A71947

- *1 unknown/js code*
- ??? at `0x5177c` in ntdll.dll
- ??? at `0x514d7` in ntdll.dll
- ??? at `0x5117d` in ntdll.dll
- ??? at `0x17fab` in KERNEL32.DLL
- [`exit.cpp:137`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/appcrt/startup/exit.cpp#L137>): `exit_or_terminate_process`
- [`exit.cpp:274`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/appcrt/startup/exit.cpp#L274>): `common_exit`
- [`Global.zig:121`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/Global.zig#L121>): `exit`
- [`javascript.zig:1316`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L1316>): `globalExit`
- [`javascript.zig:1228`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/javascript.zig#L1228>): `eventLoop`

Features: jsc, transpiler\_cache, tsconfig

**Comment by 190n** [comment] 2024-09-30 18:45
Duplicate of #4290.

This happens because gl uses some V8 methods Bun doesn't implement yet. Please follow progress in that issue.

**Closed as not planned by 190n** 2024-09-30 18:45 UTC
Labels: crash, windows, runtime
