### ISSUE TITLE
NODE_ENV=test does not read .env.test file

### ISSUE THREAD

**Issue by purefun** [oven-sh/bun#6630] opened 2023-10-21 03:57 UTC
According to the document: https://github.com/oven-sh/bun/blob/969da088f5db3258a803ec186012e30f992829b4/docs/runtime/env.md?plain=1#L5-L10, Bun should read `.env.test` file, but it does not actually.

How to repreduce:

```sh
$ bun --version
1.0.6
```

```sh
$ cat index.ts
───────┬──────────────────────────────────────────────────
       │ File: index.ts
       │ Size: 47 B
───────┼──────────────────────────────────────────────────
   1   │ console.log(`AWESOME=${process.env.AWESOME}`);
───────┴──────────────────────────────────────────────────
```

```sh
$ cat .env.production
───────┬──────────────────────────────────────────────────
       │ File: .env.production
       │ Size: 19 B
───────┼──────────────────────────────────────────────────
   1   │ AWESOME=production
───────┴──────────────────────────────────────────────────
```

```sh
$  cat .env.test
───────┬──────────────────────────────────────────────────
       │ File: .env.test
       │ Size: 13 B
───────┼──────────────────────────────────────────────────
   1   │ AWESOME=test
───────┴──────────────────────────────────────────────────
```

```sh
$ NODE_ENV=production bun run index.ts
AWESOME=production
```

```sh
$ NODE_ENV=test bun run index.ts
AWESOME=undefined # ❌ should be AWESOME=test
```

**Comment by Electroid** [comment] 2023-10-23 21:08
Duplicate of #4118

**Comment by chadacious** [comment] 2024-02-26 17:17
Actually, this doesn't seem to be a duplicate of #4118 . Indeed `bun run index.ts` won't load the `.env.test` file even when `NODE_ENV=test`. The other environments for `.env.development` and `.env.production` work as expected. Perhaps it's because `.env.test` is specifically intended for `bun test` and not `bun run`?

Since there isn't support for `.env.staging` (see #9090 ), I encountered this problem by trying to use `.env.test` in a staging environment but it doesn't work like the others. In fact, in my testing it loads `.env.development` instead.

**Comment by moshOntong-IT** [comment] 2024-03-06 03:31
what is the status of this issue?

**Closed as completed** 2024-03-07 11:36 UTC
