### ISSUE TITLE
`bun run` not handling escaped quotes in package.json script

### ISSUE THREAD

**Issue by ghost** [oven-sh/bun#1079] opened 2022-08-15 03:24 UTC

**Comment by xhyrom** [comment] 2022-08-15 10:54
Duplicate of https://github.com/oven-sh/bun/issues/896

**Comment by xhyrom** [comment] 2022-08-15 10:54
And.... you have old bun version

**Comment by invrainbow** [comment] 2022-08-15 11:23
Oh yeah, but 0.1.8 didn't fix it either.

**Comment by Jarred-Sumner** [comment] 2022-08-16 01:35
(accidentally re-opened, previous duplicate is the right issue)

**Closed as completed** 2022-08-16 01:34 UTC
Labels: bug, needs repro
