### ISSUE TITLE
[Bun.serve] should allow status is 103

### ISSUE THREAD

**Issue by truongan07** [oven-sh/bun#9549] opened 2024-03-22 00:15 UTC
### What is the problem this feature would solve?

Let's allow developers create early hints base on their idea to fit assets that they want to send client on per API

### What is the feature you are proposing to solve the problem?

Reduce response wait time & assets loading

**Comment by Electroid** [comment] 2024-03-22 02:21
Duplicate of #8690

**Closed as not planned by Electroid** 2024-03-22 02:21 UTC
Labels: enhancement, bun.js
