### ISSUE TITLE
`Request.clone()` does not clone body

### ISSUE THREAD

**Issue by danthegoodman1** [oven-sh/bun#8515] opened 2024-01-27 03:30 UTC
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

macOS

### What steps can reproduce the bug?

clone an incoming request

### What is the expected behavior?

the body is cloned

### What do you see instead?

blank body

**Comment by danthegoodman1** [comment] 2024-01-27 03:32
https://github.com/oven-sh/bun/pull/6468 related

**Comment by Electroid** [comment] 2024-01-29 04:05
Duplicate of #1381

**Closed as not planned by Electroid** 2024-01-29 04:05 UTC
Labels: bug
