### ISSUE TITLE
Error: Segmentation fault: 11

### ISSUE THREAD

**Issue by sandervspl** [oven-sh/bun#6684] opened 2023-10-24 12:10 UTC
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

1. `bun init`
2. Add this to package.json

```
"trustedDependencies": ["sharp"]
```

3. Run `bun add @xenova/transformers`
4. Add this to index.ts

```ts
import { pipeline } from "@xenova/transformers";

const generateEmbedding = await pipeline("feature-extraction");
```

5. Run `bun index.ts`

### What is the expected behavior?

It should run without a segmentation fault

### What do you see instead?

Error output:

```
Segmentation fault: 11
```

**Comment by Jarred-Sumner** [comment] 2023-10-24 12:21
This is a duplicate of https://github.com/oven-sh/bun/issues/4619

**Closed as not planned by Jarred-Sumner** 2023-10-24 12:21 UTC
Labels: bug
