### ISSUE TITLE
I gues problem based on nodejs

### ISSUE THREAD

**Issue by burakakca** [oven-sh/bun#11810] opened 2024-06-12 15:43 UTC
### How can we reproduce the crash?

Version 1.1.4 works but not 1.1.13

I can't share my code but

```json
{
  "name": "jetstream",
  "module": "server/index.ts",
  "type": "module",
  "scripts": {
    "dev": "bun run --watch server/index.ts"
  },
  "dependencies": {
    "@temporalio/client": "^1.9.3",
    "nats": "^2.25.0",
    "surrealdb.js": "^0.11.0"
  },
  "devDependencies": {
    "@types/bun": "^1.1.2"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}
```

that's all what I'm using

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x00000020

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `end_hquery`

**Comment by Jarred-Sumner** [comment] 2024-06-20 23:57
Duplicate of https://github.com/oven-sh/bun/issues/11882

**Comment by Jarred-Sumner** [comment] 2024-06-20 23:57
We are tracking this in https://github.com/oven-sh/bun/issues/11882, please follow along in that issue

**Closed as completed by Jarred-Sumner** 2024-06-20 23:57 UTC
Labels: crash
