### ISSUE TITLE
Bun AST Parser

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12896] opened 2024-07-28 11:36 UTC
### What is the problem this feature would solve?
This can be highly useful for manipulation, compilation optimization, static analysis, etc.
Expose a JavaScript API to parse JavaScript code from a string
like Babel.transform or swc.transform

### What is the feature you are proposing to solve the problem?

suggestions for the name:
Bun.ast (recommended)
Bun.parse
Bun.transform

**Comment by Electroid** [comment] 2024-07-28 18:07
Duplicate of https://github.com/oven-sh/bun/issues/2729

**Closed as not planned by Electroid** 2024-07-28 18:07 UTC
Labels: enhancement
