### ISSUE TITLE
Do not pass posix paths to Windows APIs, was given '\lib\esm\in'.

### ISSUE THREAD

**Issue by AliceCooper214** [oven-sh/bun#11351] opened 2024-05-25 13:49 UTC
### How can we reproduce the crash?

When I try to import an external file for a function and run this code, the code will throw an exception about bun.

### JavaScript/TypeScript code that reproduces the crash?

```typescript
//location: ./transform.ts
export function transformHtmlToVue(input: string) {
// ignore code
}
```

```typescript
// location ./index.ts
import { transformHtmlToVue } from "./transform";

// and use
```

```json
//package.json
{
  "version": "1.0.0",
  "description": "",
  "module": "index.ts",
  "type": "module",
  "scripts": {
    "start": "bun run index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cheerio": "1.0.0-rc.12",
    "figlet": "^1.7.0",
    "ofetch": "^1.3.4",
    "p-limit": "^5.0.0"
  },
  "devDependencies": {
    "@types/bun": "^1.0.0",
    "@types/figlet": "^1.5.8",
    "typescript": "^5.4.5"
  }
}
```
```


### Relevant log output

```shell
============================================================
Bun v1.1.10 (5102a944) Windows x64
Args: "C:\Users\~\.bun\bin\bun.exe" "run" "index.ts"
Features: jsc tsconfig(2) 
Builtins: "bun:main" 
Elapsed: 57ms | User: 0ms | Sys: 15ms
RSS: 116.54MB | Peak: 116.54MB | Commit: 0.16GB | Faults: 28689

panic(main thread): Internal Error: Do not pass posix paths to Windows APIs, was given '\lib\esm\in'. Please open an issue on GitHub with a reproduction.
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.10/wr15102a94AiggggEkzgrT+0l9Pu917Kgsm6L6uh7GotqSs/ryG2/pzJitmyJun40JA0eNoFwTEOwjAMBdCr/K0L6gHYkEDQrRtLFpda1FKwI9shHJ/3Fk12pYqbu/kZV4NaolEEmoX80CiPQBqeoruNwGVd4oRBgbd8WTGVKlvh+BTRacZamYJhjRWkkIjOMMVd8tE3DMkDBOfmtvdXiun8B1kBL0s

error: script "start" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [RunCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '\lib\esm\in'. Please open an issue on GitHub with a reproduction.

- [`Allocator.zig:225`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/deps/zig/lib/std/mem/Allocator.zig#L225>): `allocBytesWithAlignment`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`bun.zig:3279`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.zig#L3279>): `unsafeAssert`
- [`sys.zig:832`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/sys.zig#L832>): `openFileAtWindowsNtPath`
- [`sys.zig:975`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/sys.zig#L975>): `openFileAtWindowsT`
- [`sys.zig:1136`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/sys.zig#L1136>): `openA`
- [`cache.zig:187`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cache.zig#L187>): `readFileWithAllocator`
- [`bundler.zig:1337`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bundler.zig#L1337>): `parseMaybeReturnFileOnlyAllowSharedBuffer`
- [`module_loader.zig:1685`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/module_loader.zig#L1685>): `transpileSourceCode`
- [`module_loader.zig:2328`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/module_loader.zig#L2328>): `Bun__transpileFile`

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:53
Duplicate of https://github.com/oven-sh/bun/issues/10830

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:53
Please follow along in #10830

**Closed as not planned by Jarred-Sumner** 2024-08-06 07:53 UTC
Labels: crash, windows
