### ISSUE TITLE
Running workable test in Node.js + Jest results in fail with bun for Sharp.js

### ISSUE THREAD

**Issue by tom10271** [oven-sh/bun#5257] opened 2023-09-13 10:13 UTC
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 21.5.0 arm64 arm

### What steps can reproduce the bug?

All I can say is I use `"sharp": "^0.31.3",` and my code convert image from format to format with Sharp.js, it fails with the following message

```
MBP:code me$ bun test
bun test v1.0.1 (31aec4eb)

test/conversion-format.test.ts:
29 |     if (loadedModule) {
30 |       const [, loadedPackage] = loadedModule.match(/node_modules[\\/]([^\\/]+)[\\/]/);
31 |       help.push(`- Ensure the version of sharp aligns with the ${loadedPackage} package: "npm ls sharp"`);
32 |     }
33 |   }
34 |   throw new Error(help.join('\n'));
            ^
error: 
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-darwin-arm64v8.node" from "/Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
      at /Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/sharp.js:34:8
      at globalThis (/Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/sharp.js:34:33)
      at require (:1:20)
      at /Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/constructor.js:8:0
      at globalThis (/Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/constructor.js:429:17)
      at require (:1:20)
      at /Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/index.js:3:6
      at globalThis (/Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/index.js:13:17)

test/web-server-served-requests.test.ts:
error: 
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-darwin-arm64v8.node" from "/Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install

test/misc-cases.test.ts:
error: 
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-darwin-arm64v8.node" from "/Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install

test/s3-related-requests.test.ts:
error: 
Something went wrong installing the "sharp" module

Cannot find module "../build/Release/sharp-darwin-arm64v8.node" from "/Users/me/Sites/ImageConverter/code/node_modules/sharp/lib/sharp.js"

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install

 0 pass
 4 fail
Ran 4 tests across 4 files. [1086.00ms]
MBP:code me$ 
```

When I run `npm test`, it works properly
```
Test Suites: 4 passed, 4 total
Tests:       30 passed, 30 total
Snapshots:   0 total
Time:        16.229 s
Ran all test suites.
```

**Comment by Electroid** [comment] 2023-10-27 23:04
Duplicate of #4549

**Closed as not planned by Electroid** 2023-10-27 23:04 UTC
Labels: bug
