### ISSUE TITLE
`Bun.$` exception message does not highlight the line where the exception occured in the program

### ISSUE THREAD

**Issue by dragonflyfree** [oven-sh/bun#14203] opened 2024-09-27 03:20 UTC
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Run the following code:

```ts
import { $ } from "bun";

await $`mkdir some/unique/paths`;
```

This should throw an exception (unless those paths there aren't unique in the directory containing your bun application...)

### What is the expected behavior?

```
$ bun run index.ts
mkdir: No such file or directory: /.../some/unique/paths
2 |
3 | await $`mkdir some/unique/paths`;
                   ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "mkdir: No such file or directory: /.../some/unique/paths\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at /.../index.ts:3:7

Bun v1.1.29 (macOS arm64)
```

### What do you see instead?

```
$ bun run index.ts
mkdir: No such file or directory: /.../some/unique/paths
2 | import { $ } from "bun";
3 |
                   ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "mkdir: No such file or directory: /.../some/unique/paths\n",
  "stdout": ""
}

      at new ShellError (12:16)
      at new ShellPromise (72:16)
      at BunShell (187:35)
      at /.../index.ts:3:7

Bun v1.1.29 (macOS arm64)
```

**Comment by Jarred-Sumner** [comment] 2024-09-30 06:30
Duplicate of #2704

**Closed as not planned** 2024-09-30 06:30 UTC
Labels: bug, needs triage
