### ISSUE TITLE
BunFileSystemRouter has limit of 64 routes

### ISSUE THREAD

**Issue by 1bye** [oven-sh/bun#8278] opened 2024-01-19 12:49 UTC
### What version of Bun is running?

1.0.23+83f2432da

### What platform is your computer?

Linux 6.2.0-26-generic x86_64 x86_64 (Ubuntu)

### What steps can reproduce the bug?

I using `elysia` as server with plugin `elysia-autoroutes` which allows to add routes from any folder. 
When I adding new file to routes it occur following error. I've tried adding coupe of files, rename, with another content, nothing works.
I think error can be occur with bun file system router, or some limitations, idk
File count using `find ./routes -type f | wc -l` is `64` error occur when `65`

Thanks

### What is the expected behavior?

![Screenshot from 2024-01-19 12-38-23](https://github.com/oven-sh/bun/assets/51824506/b75d9bf7-2071-43b6-93e6-be8403014bdd)

### What do you see instead?

![Screenshot from 2024-01-19 12-39-02](https://github.com/oven-sh/bun/assets/51824506/a0c2e2b4-d207-4b71-b721-ec72d02afdbd)

**Comment by Electroid** [comment] 2024-01-19 17:10
Duplicate of #8276

**Closed as not planned by Electroid** 2024-01-19 17:10 UTC
Labels: bug, bun.js
