### ISSUE TITLE
Bcrypt Compare Segmentation Fault

### ISSUE THREAD

**Issue by ansgarlichter** [oven-sh/bun#6902] opened 2023-11-04 20:24 UTC
### What version of Bun is running?

1.0.7

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64 using WSL Ubuntu 22.10

### What steps can reproduce the bug?
I am using a Nest.js Project and I am trying to migrate to Bun as runtime. The projects uses currently bcrypt to hash the passwords and compare the hashes during the validation of the login process or during registering.

The project can be found here: [nestjs-api](https://github.com/AnsgarLichter/nestjs-api/tree/migrate-to-bun).

Clone the project, execute ``bun i``, run the server with ``bun run src/main.ts``. Now send a post request to the endpoint to register an user (localhost:3000/api/v1/auth/register) with the following body:
```json
{
    "name": "test2",
    "username": "test2",
    "password": "test123",
    "roles": "admin",
    "email": "test2@tester.de",
    "isAccountDisabled": false
}
```
Now 

### What is the expected behavior?

The bcrypt functions to compare and hash a password should work without problems.

### What do you see instead?

Everytime bcrypt.compare is called the server stops with the message "Segmentation Fault":
const match = await compare(pass, user.password);
![image](https://github.com/oven-sh/bun/assets/43957906/66a6d1cc-d811-4e9d-8ce2-7ebd51f3de4b)

The same happens registering a new user. Every time the password is hashed the server crashes with "Segmentation Fault"
user.password = await hash(input.password, 10);

### Additional information

I know I can use the functions from Bun to hash a password (see [docs](https://bun.sh/guides/util/hash-a-password)) Shouldn't bcrypt work for compatibility reasons with current Node.js projects to be a drop-in replacement? Or is this just not possible because bcrypt is a node binding written in C++?

**Comment by Jarred-Sumner** [comment] 2023-11-06 08:59
Duplicate of https://github.com/oven-sh/bun/issues/3201

**Closed as completed by Jarred-Sumner** 2023-11-06 08:59 UTC
Labels: bug, crash, needs investigate
