### ISSUE TITLE
segmentation fault  await request.formData()

### ISSUE THREAD

**Issue by alhimikix** [oven-sh/bun#5082] opened 2023-09-12 11:34 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

code: 
Bun.serve({
	port: 3000,
	async fetch(request: Request, server: Server) {
		return Response.json(await request.formData())
	},

})

img.png size 3.83mb

request 
POST http://localhost:3000/test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png

### What is the expected behavior?

zsh: segmentation fault  bun run --watch test/run-server.ts
app crush

**Comment by akx** [comment] 2023-09-12 11:37
Duplicate of #4966, I believe.

**Closed as completed** 2023-09-14 17:15 UTC
Labels: bug, crash, web-api
