### ISSUE TITLE
error: script "dev" exited with code 3

### ISSUE THREAD

**Issue by mseptiaan** [oven-sh/bun#15132] opened 2024-11-13 13:55 UTC
### How can we reproduce the crash?

```
F:\folder>bun run dev
$ rsbuild dev

  Rsbuild v1.1.1

  ➜ Network:  http://192.168.1.5:3000/
  ➜ Local:    http://localhost:3000/
  ➜ press h + enter to show shortcuts

start   Building...
============================================================
Bun v1.1.34 (5e5e7c60) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "node" "F:\erika-rs\node_modules\@rsbuild\core\bin\rsbuild.js" "dev"
Features: Bun.stdin(2) jsc transpiler_cache(17)
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:process" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:inspector"
Elapsed: 459ms | User: 406ms | Sys: 281ms
RSS: 0.33GB | Peak: 0.33GB | Commit: 0.43GB | Faults: 81936

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.34/wn15e5e7c6AkggkggBsijyvC__A2AK

error: script "dev" exited with code 3
```

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`JSCellInlines.h:243`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSCellInlines.h#L243>): `JSC::JSCell::isString`

Features: Bun.stdin, bunfig, http\_server, jsc, spawn, tsconfig

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5615604075/">BUN-29T</a></strong></sub>

**Comment by nektro** [comment] 2024-11-14 01:54
duplicate of https://github.com/oven-sh/bun/issues/11628

**Closed as not planned by nektro** 2024-11-14 01:54 UTC
Labels: crash, windows, runtime
