### ISSUE TITLE
There is no sources in the debugger web UI

### ISSUE THREAD

**Issue by mifopen** [oven-sh/bun#5372] opened 2023-09-14 12:56 UTC
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. `bun --inspect-brk file.ts`
2. go to https://debug.bun.sh
3. open Source tab

### What is the expected behavior?

see file.ts content execution stopped at the first line and with ability to set breakpoints

### What do you see instead?

empty tab

### Additional information

also evaluation in the console tab doesn't work (`2+2` + enter)

**Comment by Electroid** [comment] 2023-09-14 15:53
What browser were you using? Also, would it be possible to share the code you ran?

**Comment by mifopen** [comment] 2023-09-14 20:44
I use Chrome Version 116.0.5845.179 (Official Build) (arm64)
The code is just `console.log('hello');` :)

**Comment by mauskin** [comment] 2023-09-18 13:49
Same for me.

    echo 'console.log("hello")' > hello.js
    bun --inspect-brk hello.js

Bun v1.0.2
Safari Version 16.6 (18615.3.12.11.2) (same for STP Release 178 (Safari 17.0, WebKit 18617.1.6)
macOS v13.5.2 on M1

I get the same if I run a long running application with `--inspect`: no sources and `debugger` statements are ignored.

**Comment by adamszigeti** [comment] 2023-10-08 08:47
Same issue here, command line scripts cannot be debugged until this is fixed.

**Comment by KilianB** [comment] 2023-10-25 14:06
For me files are also not showing up. 

WSL windows, 
Bun 1.0.3

**Comment by Electroid** [comment] 2023-10-27 20:32
Duplicate of #4716

**Closed as not planned by Electroid** 2023-10-27 20:32 UTC
Labels: bug, debugger
