### ISSUE TITLE
fetch does not force signal timeout on certain missconfigured domains

### ISSUE THREAD

**Issue by jordinl** [oven-sh/bun#14560] opened 2024-10-14 14:01 UTC
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Linux 6.10.12-100.fc39.x86_64 x86_64 unknown

### What steps can reproduce the bug?

Executing fetch with a signal timeout takes significantly longer on certain domains. Don't know if it's a DNS issue.

For instance, when executing fetch with a timeout of 1s:

```
bun -e "                                                                                                  
const start = Date.now();
try {
    await fetch('https://edwardsnowden.com', { signal: AbortSignal.timeout(1000) })
} catch(e) {
    console.log(Date.now() - start, e.message)
}
"
```

I'm seeing it times out after 35s:

```
#=> 35251 The operation timed
```

It's also not consistent, I've seen timeouts between 10s and 35s.

### What is the expected behavior?

Should timeout after 1 second.

### What do you see instead?

Ditto

### Additional information

Works fine on node:

```
node -e "                                                                                                
const start = Date.now();
try {
    await fetch('https://edwardsnowden.com', { signal: AbortSignal.timeout(1000) })
} catch(e) {
    console.log(Date.now() - start, e.message)
}
"
```

Produces:

```
1005 The operation was aborted due to timeout
```

I like to call this the Edward Snowden test. But it also happens with `https://home.comcast.net` for instance

**Comment by RiskyMH** [comment] 2024-11-20 09:29
Duplicate of #13302

**Closed as not planned by RiskyMH** 2024-11-20 09:29 UTC
Labels: bug, web:fetch
