### ISSUE TITLE
bun install crash on windows

### ISSUE THREAD

**Issue by metaspartan** [oven-sh/bun#12286] opened 2024-07-02 03:14 UTC
### Stack Trace (bun.report)

Bun v1.1.18 ([`861be55`](<https://github.com/oven-sh/bun/tree/861be5560ec776ea1a737b360cde2544a71b37c9>)) on windows x86_64 [InstallCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '\packages\'. Please open an issue on GitHub with a reproduction.

- [`libuv.zig:2806`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/deps/libuv.zig#L2806>): `errEnum`
- [`sys.zig:1280`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/sys.zig#L1280>): `open`
- [`install.zig:8349`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/install/install.zig#L8349>): `initWithCLI`
- [`cli.zig:1494`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/cli.zig#L1494>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/861be5560ec776ea1a737b360cde2544a71b37c9/src/src/startup/exe_common.inl#L78>): `invoke_main`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5af28` in ntdll.dll

**Comment by dylan-conway** [comment] 2024-07-02 03:15
Can you share your package.json, specifically the `"workspaces"` field?

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:56
Duplicate of https://github.com/oven-sh/bun/issues/11215

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:56
Please follow along in https://github.com/oven-sh/bun/issues/11215

**Closed as not planned by Jarred-Sumner** 2024-08-06 07:56 UTC
Labels: bug, needs repro, bun install
