### ISSUE TITLE
"Expected Scope" Canary Crash

### ISSUE THREAD

**Issue by TotalTechGeek** [oven-sh/bun#2694] opened 2023-04-19 08:09 UTC
### What version of Bun is running?

v0.6.0 (ea47ed0e)

### What platform is your computer?

Darwin 21.4.0 arm64 arm

### What steps can reproduce the bug?

```bash
git clone https://github.com/TotalTechGeek/json-logic-engine
cd json-logic-engine/bench
yarn install
bun test.js
```

### What is the expected behavior?

```
> bun test.js
258 17 0.9381818181818182
[326.19ms] json-logic-js
[562.55ms] le interpreted
[20.94ms] le built
[64.50ms] le async built
```

Rather than a crash. This was created by Bun v0.5.9

### What do you see instead?

```
> bun test.js
error: Expected scope (src.js_ast.Scope.Kind.function_args, 18) in /Users/jesse/Documents/Projects/forbun/json-logic-engine/utilities/declareSync.js, found scope (src.js_ast.Scope.Kind.function_args, 82)

})
  ^
/Users/jesse/Documents/Projects/forbun/json-logic-engine/utilities/declareSync.js:8:3 159


uh-oh:

error: Expected scope (src.js_ast.Scope.Kind.function_args, 18) in /Users/jesse/Documents/Projects/forbun/json-logic-engine/utilities/declareSync.js, found scope (src.js_ast.Scope.Kind.function_args, 82)

})
  ^
/Users/jesse/Documents/Projects/forbun/json-logic-engine/utilities/declareSync.js:8:3 159

bun will crash now 😭😭😭

----- bun meta -----
Bun v0.6.0 (ea47ed0e) macOS Silicon 21.4.0
AutoCommand:
Elapsed: 16ms | User: 11ms | Sys: 8ms
RSS: 26.46MB | Peak: 26.46MB | Commit: 33.55MB | Faults: 88
----- bun meta -----

0   0x10656d118 WTFGetBacktrace
1   ??? Bun__crashReportDumpStackTrace
2   ??? src.report.fatal
3   ??? Zig::GlobalObject::moduleLoaderFetch(JSC::JSGlobalObject*, JSC::JSModuleLoader*, JSC::JSValue, JSC::JSValue, JSC::JSValue)
4   ??? JSC::moduleLoaderFetch(JSC::JSGlobalObject*, JSC::CallFrame*)
5   ???
6   ??? llint_entry
7   ???
8   ???
9   ??? llint_entry
10  ??? llint_entry
11  ??? llint_entry
12  ??? llint_entry
13  ???
14  ??? vmEntryToJavaScript
15  ??? JSC::Interpreter::executeCall(JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
16  ??? JSC::runJSMicrotask(JSC::JSGlobalObject*, WTF::ObjectIdentifierGeneric<JSC::MicrotaskIdentifierType, WTF::ObjectIdentifierThreadSafeAccessTraits>, JSC::JSValue, JSC::JSValue, JSC::JSValue, JSC::JSValue, JSC::JSValue)
17  ??? JSC::VM::drainMicrotasks()
18  ??? JSC__JSModuleLoader__loadAndEvaluateModule
19  ??? src.bun.js.javascript.VirtualMachine.reloadEntryPoint

Crash report saved to:
  ~/.bun/.bun-crash/v0.6.0-1681891401091.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

thread 16395846 panic:

error: Expected scope (src.js_ast.Scope.Kind.function_args, 18) in /Users/jesse/Documents/Projects/forbun/json-logic-engine/utilities/declareSync.js, found scope (src.js_ast.Scope.Kind.function_args, 82)

})
  ^
/Users/jesse/Documents/Projects/forbun/json-logic-engine/utilities/declareSync.js:8:3 159

zsh: abort      bun test.js
```

### Additional information

N/A

**Comment by TotalTechGeek** [comment] 2023-04-19 08:23
Some additional information... and a smaller test vector to reproduce:


Create a file called "export.js" with the following:
```javascript
// A comment
'use strict'
const wtf = Symbol('What')
export default (function test () {})
```

Create a file called "index.js" with the following:
```javascript
import fun from './export.js';
console.log(fun());
```

This will crash the canary build of bun, but not the 0.5.9 build.

What is interesting is that removing any of the following will cause it to not crash:
- The comment
- The string (it doesn't have to be `'use strict'`, but that makes the most sense to have).
- The symbol assignment line
- The parenthesis around the function

**Comment by TotalTechGeek** [comment] 2023-04-19 08:33
Oh, hey, my "export.js" file might be a bit misleading, I think the problem could be a bit simpler:

"export.js": 
```javascript
// A comment that is long enough to trigger it.
export default (function test () {})
```

Will trigger it. Removing a single character from the comment line will cause it to succeed.

I think there may be a quirk with slicing when there are parenthesis around the exported function.

**Comment by Jarred-Sumner** [comment] 2023-04-19 08:38
either a bug in our comment pragma parsing

or a bug in function hoisting

will investigate

**Comment by TotalTechGeek** [comment] 2023-04-19 08:45
```javascript
'A string that is long enough to trigger it...'
export default (function test () {})
```

And

```javascript
let str = 'A string long enough to trigger it.'
export default (function test () {})
```

Fail as well, so I'm not sure if it's comment pragmas.

**Comment by Jarred-Sumner** [comment] 2023-04-19 09:14
okay its our hoisting

we need to make it so that scopes_in_order is consistent

**Comment by Electroid** [comment] 2023-10-26 00:15
This has been fixed as of Bun v1.0.7.

```
❯ bun test.js
258 17 0.9381818181818182
[273.05ms] json-logic-js
[347.99ms] le interpreted
[18.28ms] le built
[62.18ms] le async built
```

If you are still running into this issue, please re-open and we'll investigate.

**Comment by KaHLK** [comment] 2023-10-30 10:48
I'm running into this error when trying to build a react project. I've managed to isolate the lines that seem to cause the error.

The `Line` component is from `react-konva`, but I have removed the import from the file, as it is not the cause of the error:
```js
export const DrawLine = ({ line }) => {
    return (
        <Line key={line.map((l) => l).join(",")} points={line.map((c) => c)} />
    );
};
```

Running `bun build index.jsx` (assuming the above is called `index.jsx`) causes the error to occur.
Removing the `key={line.map((l) => l).join(",")}` or `points={line.map((c) => c)}` causes the error to disappear.

Crash message is (output from `bat ~/.bun/.bun-crash/v1.0.7-1698662448875.crash` with minor modifications to paths):
```
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ~/.bun/.bun-crash/v1.0.7-1698662448875.crash
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │
   2   │ uh-oh:
   3   │
   4   │ error: Expected scope (src.js_ast.Scope.Kind.function_args, 119) in index.jsx, found scope (src.js_ast.Scope.Kind.
       │ function_args, 81)
   5   │
   6   │ };
   7   │   ^
   8   │ ./index.jsx:5:3 143
   9   │
  10   │ bun will crash now 😭😭😭
  11   │
  12   │ ----- bun meta -----
  13   │ Bun v1.0.7 (b0393fba) macOS Silicon 23.0.0
  14   │ BuildCommand:
  15   │ Elapsed: 7ms | User: 6ms | Sys: 7ms
  16   │ RSS: 12.08MB | Peak: 12.08MB | Commit: 39.88MB | Faults: 42
  17   │ ----- bun meta -----
  18   │
  19   │ 0   0x1021bb7e4 WTFGetBacktrace
  20   │ 1   ??? Bun__crashReportDumpStackTrace
  21   │
  22   │ Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
  23   │
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by Jarred-Sumner** [comment] 2023-10-30 11:20
Confirming it reproduces with `bun build ./file.js`

**Comment by Jarred-Sumner** [comment] 2023-10-30 11:29
Minimum reproduction:
```js
<A key={() => {}} b={() => {}} />;
```

Or anything that creates a scope defined after the `key` prop creates a function

```js
<A key={() => {}} b={class {}} />;
```

**Closed as completed** 2023-11-03 05:56 UTC
Labels: bug, crash, bundler
