### ISSUE TITLE
DELETE request method is empty

### ISSUE THREAD

**Issue by lau1944** [oven-sh/bun#1009] opened 2022-08-07 04:49 UTC
### Version

0.1.6

### Platform

Darwin 192.168.6.192 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

I try to call the rest api using bun
```
curl -X DELETE http://localhost:3000/xxxx/xxxx
```
Then I want to get the request method using `req.method` inside the `fetch` function
But I get a empty string instead of `DELETE`

### How often does it reproduce? Is there a required condition?

Every time I call delete method.

### What is the expected behavior?

`DELETE` string in `req.method`

### What do you see instead?

Empty string
 ``

**Comment by xhyrom** [comment] 2022-08-07 05:14
Duplicate of https://github.com/oven-sh/bun/issues/677

**Closed as not planned by xhyrom** 2022-08-07 05:14 UTC
Labels: bug, needs repro
