### ISSUE TITLE
`Bun.serve` never closes `ReadableStream` on request cancellation.

### ISSUE THREAD

**Issue by ffss92** [oven-sh/bun#8334] opened 2024-01-21 18:07 UTC
### What version of Bun is running?

1.0.24+6fa35839c

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```typescript
Bun.serve({
  fetch(_req) {
    let id: NodeJS.Timeout;

    const stream = new ReadableStream({
      start(controller) {
        id = setInterval(() => {
          console.log(`Server: Writing to client...`);
          controller.enqueue(`data: ${new Date().toLocaleString()}\n\n`);
        }, 1000);
      },
      cancel() {
        // Never gets called, even if client closes connection.
        console.log(`Connection closed.`); 
        clearInterval(id);
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
      },
    });
  },
  port: 3000,
});
```

### What is the expected behavior?

`ReadableStream` should be closed on request cancellation or it should be unlocked for manual cancellation.

### What do you see instead?

`stream.cancel` never gets called, `setInterval` is never cleared even after client closes connection.

**Comment by Electroid** [comment] 2024-01-21 18:55
Duplicate of #6758

**Closed as not planned by Electroid** 2024-01-21 18:55 UTC
Labels: bug, web-api
