### ISSUE TITLE
node:stream Duplex.toWeb(process.<stdin,stdout>) throws

### ISSUE THREAD

**Issue by guest271314** [oven-sh/bun#8894] opened 2024-02-14 03:57 UTC
### What version of Bun is running?

1.0.26

### What platform is your computer?

x64

### What steps can reproduce the bug?

Try using `node`, `deno`, then try using `bun`

```
bun run stdout_stream.js
```

Write lowercase letter in the terminal, e.g., `test`

```
//  stdout_stream.js
import { Duplex } from "node:stream";
import { exit, stdin, stdout } from "node:process";

const runtime = navigator.userAgent;

const { readable } = /Node|Bun/.test(runtime)
  ? Duplex.toWeb(stdin)
  : Deno.stdin;
const { writable } = /Node|Bun/.test(runtime)
  ? Duplex.toWeb(stdout)
  : Deno.stdout;

const encoder = new TextEncoder();
const decoder = new TextDecoder();

function encodeMessage(message) {
  return encoder.encode(JSON.stringify(message));
}

async function* getMessage() {
  for await (let message of readable) {
    yield encoder.encode(decoder.decode(message).toUpperCase());
  }
}
async function sendMessage(message) {
  // Closing WritableStream causes host to exit
  await new Blob([
    message,
  ])
    .stream()
    .pipeTo(writable, { preventClose: true });
}

try {
  for await (const message of getMessage()) {
    await sendMessage(message);
  }
} catch (e) {
  exit();
}
```

### What is the expected behavior?

`TEST` to be printed in terminal.

### What do you see instead?

```
bun run stdout_stream.js
2 | import { exit, stdin, stdout } from "node:process";
3 | 
4 | const runtime = navigator.userAgent;
5 | 
6 | const { readable } = /Node|Bun/.test(runtime)
7 |   ? Duplex.toWeb(stdin)
        ^
TypeError: undefined is not a function
      at node:stream:3206:61
      at /home/user/stdout_stream.js:7:5
```

### Additional information

Is is possible to create a WHATWG `ReadableStream` from `process.stdin` and a `WritableStream` from `process.stdout` in `node` v22 using `Duplex.toWeb()` from `"node:stream"`  https://github.com/guest271314/native-messaging-nodejs/blob/818da9325bf478ca0a0ea5ebd8a5aa5e84750414/nm_nodejs.js#L45C1-L51C47

```
  // Closing WritableStream causes host to exit
  await new Blob([
    new Uint8Array(new Uint32Array([message.length]).buffer),
    message,
  ])
    .stream()
    .pipeTo(writable, { preventClose: true });
```

Deno implements `Deno.stdin.readable` and `Deno.stdout.writable` out of the box https://github.com/guest271314/native-messaging-deno/blob/6c2cc3a221a8557b6a90fd5a2436e8867a2c0b72/nm_deno.js#L40-L45

```
  await new Blob([
    new Uint8Array(new Uint32Array([message.length]).buffer),
    message,
  ])
    .stream()
    .pipeTo(Deno.stdout.writable, { preventClose: true });
```

Ideally there should be a `Bun.stdout.writable`. 

It looks like something similar has been proposed here

- https://github.com/oven-sh/bun/issues/1969
- https://github.com/oven-sh/bun/issues/3928

Presently `bun` throws for Node.js API `Duplex.toWeb(process.<stdin, stdout>)`.

**Comment by Electroid** [comment] 2024-02-14 18:22
Duplicate of #3927

**Closed as not planned by Electroid** 2024-02-14 18:22 UTC
Labels: bug, node.js
