### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by wczhou5697** [oven-sh/bun#13051] opened 2024-08-03 17:09 UTC
### How can we reproduce the crash?

https://github.com/mimloader/devkit
I clone this repo, then do a 'bun run dev init".

### Relevant log output

```shell
PS C:\Users\wczho\Downloads\DevKit-main\DevKit-main> bun run dev init
$ bun run src/index.ts init
┌  Using devkit@1.0.1 to build your project.
│
◇  Project name
│  C:\Users\wczho\Downloads\DevKit-main\DevKit-main\Test
│
◇  Description
│  None
│
◇  Author
│  wczhou5697
│
◇  Version
│  1.0.0
│
◇  Homepage
│  Null
│
◇  Preload (empty or relative path)
│  undefined
│
◇  Main
│  index.js
============================================================
Bun v1.1.21 (70ca2b76) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\wczho\.bun\bin\bun.exe" "run" "src/index.ts" "init"
Features: jsc Bun.stdin(2) Bun.stdout tsconfig(2)
Builtins: "bun:main" "node:assert" "node:buffer" "node:constants" "node:events" "node:fs" "node:path" "node:process" "node:readline" "node:stream" "node:string_decoder" "node:tty" "node:util" "node:util/types" "node:zlib"
Elapsed: 26084ms | User: 78ms | Sys: 31ms
RSS: 0.15GB | Peak: 0.15GB | Commit: 0.19GB | Faults: 36690
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- *5 unknown/js code*
- [`CallFrame.cpp:173`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/C:/a/WebKit/WebKit/Source/JavaScriptCore/interpreter/CallFrame.cpp#L173>): `JSC::CallFrame::callerFrame`
- *3 unknown/js code*

**Comment by nektro** [comment] 2024-10-23 02:12
this reproduces the issue. removing the 8th call eliminates the crash

```ts
import * as prompts from "@clack/prompts";
await prompts.text({ message: "Description 1" });
await prompts.text({ message: "Description 2" });
await prompts.text({ message: "Description 3" });
await prompts.text({ message: "Description 4" });
await prompts.text({ message: "Description 5" });
await prompts.text({ message: "Description 6" });
await prompts.text({ message: "Description 7" });
await prompts.text({ message: "Description 8" });
```

**Comment by nektro** [comment] 2024-10-23 02:30
Duplicate of https://github.com/oven-sh/bun/issues/10844

**Closed as completed by nektro** 2024-10-23 02:30 UTC
Labels: crash, windows, runtime, confirmed bug

**Comment by Jarred-Sumner** [comment] 2024-11-25 22:32
Fixed in https://github.com/oven-sh/bun/pull/15357
