### ISSUE TITLE
my bun app just crashes

### ISSUE THREAD

**Issue by andrevandal** [oven-sh/bun#12097] opened 2024-06-23 23:11 UTC
### How can we reproduce the crash?

I'm using an self project called ipx-server to serve images using ipx + s3 as external cache.
https://github.com/andrevandal/ipx-server

I used Bun as runtime for learning purpose and it just cashed this time while was processing an image.

### Relevant log output

```shell
ipx-server-ipx-1      | [ipx-server:app] ℹ Request: GET /f_auto,q_90,w_1920/https://files.vandal.services/pedrohenri.design/posts/ui-design_lucas-ribeiro/lp_lucas-ribeiro_03.png
ipx-server-ipx-1      | [ipx-server:externalCache] ℹ skipped external cache: c37215df0d26a9ef2525ab8f178a9bde737bd00d01a8641fd9cc0e6933ad48fd
ipx-server-ipx-1      | [ipx-server:externalCache] ℹ skipped external cache: 45c5c1d44a9e5d9da4360eae5597ce10ca7bafb65542ac8d318f5d3e3e7c0793
ipx-server-ipx-1      | error: script "start" was terminated by signal SIGKILL (Forced quit)
ipx-server-ipx-1      | ============================================================
ipx-server-ipx-1      | Bun v1.1.15 (b23ba1fe) Linux x64 (baseline)
ipx-server-ipx-1      | Args: "bun" "run" "start"
ipx-server-ipx-1      | Features: spawn 
ipx-server-ipx-1      | Elapsed: 251696446ms | User: 18ms | Sys: 37ms
ipx-server-ipx-1      | RSS: 1.07GB | Peak: 12.69MB | Commit: 1.07GB | Faults: 7
ipx-server-ipx-1      | 
ipx-server-ipx-1      | panic(main thread): Segmentation fault at address 0x0
ipx-server-ipx-1      | oh no: Bun has crashed. This indicates a bug in Bun, not your code.
ipx-server-ipx-1      | 
ipx-server-ipx-1      | To send a redacted crash report to Bun's team,
ipx-server-ipx-1      | please file a GitHub issue using the link below:
ipx-server-ipx-1      | 
ipx-server-ipx-1      |  https://bun.report/1.1.15/Br1b23ba1fAggggI+1mOw1vq5C6k1/5Cmu8/5C6q/p0Cg9zp0CA2AA
ipx-server-ipx-1      |
```

### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000000

- `??`
- [`Global.zig:128`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/Global.zig#L128>): `src.Global.raiseIgnoringPanicHandler__anon_86950`
- [`run_command.zig:407`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli/run_command.zig#L407>): `src.cli.run_command.RunCommand.runPackageScriptForeground`
- [`run_command.zig:1461`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli/run_command.zig#L1461>): `src.cli.run_command.RunCommand.exec__anon_273122`
- [`cli.zig:1773`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli.zig#L1773>): `src.cli.Cli.start`
- [`main.zig:50`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/main.zig#L50>): `main`

**Comment by andrevandal** [comment] 2024-06-23 23:37
I tried, but it happens again.
```
ipx-server-ipx-2      | [ipx-server:externalCache] ℹ update external cache: 0dd236f7f3f1fd61a582ca614761094d4d858ad0d778449bbf464b51127a232a
ipx-server-ipx-2      | error: script "start" was terminated by signal SIGKILL (Forced quit)
ipx-server-ipx-2      | ============================================================
ipx-server-ipx-2      | Bun v1.1.16 (bf7b327f) Linux x64 (baseline)
ipx-server-ipx-2      | Args: "bun" "run" "start"
ipx-server-ipx-2      | Features: spawn 
ipx-server-ipx-2      | Elapsed: 112506ms | User: 23ms | Sys: 38ms
ipx-server-ipx-2      | RSS: 1.07GB | Peak: 13.53MB | Commit: 1.07GB | Faults: 0
ipx-server-ipx-2      | 
ipx-server-ipx-2      | panic(main thread): Segmentation fault at address 0x0
ipx-server-ipx-2      | oh no: Bun has crashed. This indicates a bug in Bun, not your code.
ipx-server-ipx-2      | 
ipx-server-ipx-2      | To send a redacted crash report to Bun's team,
ipx-server-ipx-2      | please file a GitHub issue using the link below:
ipx-server-ipx-2      | 
ipx-server-ipx-2      |  https://bun.report/1.1.16/Br1bf7b327AggggI+1mOwp2u8Ck6mk9C25tk9Cg2uz3Cg92y3CA2AA
```

**Comment by Jarred-Sumner** [comment] 2024-07-11 17:07
Duplicate of https://github.com/oven-sh/bun/issues/12169

**Comment by Jarred-Sumner** [comment] 2024-07-11 17:08
Please follow along in https://github.com/oven-sh/bun/issues/12169

**Closed as not planned by Jarred-Sumner** 2024-07-11 17:08 UTC
Labels: crash, linux
