### ISSUE TITLE
Bun.js not fetching firestore data but Node.js does with the same code

### ISSUE THREAD

**Issue by slyofzero** [oven-sh/bun#6675] opened 2023-10-24 05:30 UTC
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

Just run the below code with a firebase service account key that you get from project settings

```
var admin = require("firebase-admin");
var serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();
const usersCollection = db.collection("users");

usersCollection.get().then((users) => {
  console.log(users);
});

```

### What is the expected behavior?

One would expect the code to log each of the documents one by one.

Output I get using Node -

```
{
  kyc_status: '',
  password: '',
  phone: '',
  dob: '',
  name: { firstname: '', lastname: '' },
  tax_id: '',
  last_otp_time: Timestamp { _seconds: 1697440446, _nanoseconds: 196000000 }
}
```

### What do you see instead?

Instead of seeing the documents, I get the error 

```
29 | const CALL_INVOCATION_TRANSFORMER_SYMBOL = Symbol();
30 | function isFunction(arg) {
31 |     return typeof arg === 'function';
32 | }
33 | function getErrorStackString(error) {
34 |     return error.stack.split('\n').slice(1).join('\n');
               ^
TypeError: undefined is not an object (evaluating 'error.stack.split')
      at getErrorStackString (/home/sly_of_zero/Projects/firebase-test/node_modules/@grpc/grpc-js/build/src/client.js:34:11)
      at onReceiveStatus (/home/sly_of_zero/Projects/firebase-test/node_modules/@grpc/grpc-js/build/src/client.js:356:40)
      at onReceiveStatus (/home/sly_of_zero/Projects/firebase-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:177)
      at /home/sly_of_zero/Projects/firebase-test/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:74
      at processTicksAndRejections (:55:76)
```

### Additional information

When using nodejs to run the same code file however using `node index.js` instead of `bun index.js` the code runs fine and I see the documents in my Firestore database. I am not sure if this is a bun issue or a firebase-admin issue, so clarification on that would be helped.

**Comment by Electroid** [comment] 2023-10-24 13:32
Duplicate of #4746

**Closed as not planned by Electroid** 2023-10-24 13:32 UTC
Labels: bug, node.js

**Comment by acoyfellow** [comment] 2023-11-30 19:01
I can attest this is still an issue.. Unable to use Firestore. Realtime database works as expected, though. What do you need @Electroid to re-open this?

```js
  const col = firestore.collection('data');
  const doc = await col.doc('hello').get();
  const firestoreData = doc.data();
  // should return { world: 'foobar' }, instead it just hangs
```

All i see in terminal:
```error: script "dev" exited with code 11 (SIGSEGV)```

**Comment by Electroid** [comment] 2023-11-30 19:18
> I can attest this is still an issue.. Unable to use Firestore. Realtime database works as expected, though. What do you need @Electroid to re-open this?
> 
> ```js
>   const col = firestore.collection('data');
>   const doc = await col.doc('hello').get();
>   const firestoreData = doc.data();
>   // should return { world: 'foobar' }, instead it just hangs
> ```
> 
> All i see in terminal: `error: script "dev" exited with code 11 (SIGSEGV)`

If you could open a new issue with a small reproduction, that would be great. Indeed we need to fix that

**Comment by brianmhunt** [comment] 2024-07-21 12:23
@Electroid I've reproduced Firestore not working in #12432.  I feel like it's one of a few issue, but a start.   Please share if you need any more details.
