### ISSUE TITLE
error: node:v8 createHook is not yet implemented in Bun.

### ISSUE THREAD

**Issue by mxvsh** [oven-sh/bun#6707] opened 2023-10-25 15:35 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

I am trying to ru Temporal using Bun, but while starting workers in Temporal it throws the following error:

```js
48 |             this.requestIdToCompletion.delete(requestId);
49 |             if (result.type === 'error') {
50 |                 const ctor = errorNameToClass(result.name);
51 |                 const err = new ctor(result.message);
52 |                 err.stack = result.stack;
53 |                 completion.reject(err);
                                        ^
error: node:v8 createHook is not yet implemented in Bun.
```

### What is the expected behavior?

It should be able to run the code

**Comment by Electroid** [comment] 2023-10-30 19:27
Duplicate of #6136

**Closed as not planned by Electroid** 2023-10-30 19:27 UTC
Labels: bug, node.js
