### ISSUE TITLE
Segmentation fault at address 0x4A0D0

### ISSUE THREAD

**Issue by mikr13** [oven-sh/bun#14908] opened 2024-10-30 09:04 UTC
### What version of Bun is running?

alpine latest

### What platform is your computer?

Linux 6.1.112-122.189.amzn2023.x86_64 x86_64 x86_64

### What steps can reproduce the bug?

My docker file looks like this:

```Dockerfile
# Setup the base image

FROM oven/bun:alpine AS base
WORKDIR /usr/src/app

# Install the dependencies

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# install with --production (exclude devDependencies)
RUN mkdir -p /temp/prod
COPY package.json bun.lockb /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

# Copy the dependencies

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules

# Bundle app source
COPY . .

# Generate Prisma client
RUN bunx prisma generate

# Build the TypeScript files
ENV NODE_ENV=production
RUN bun run build

# Final stage
FROM base AS release
COPY --from=prerelease /usr/src/app/dist ./dist
COPY --from=prerelease /usr/src/app/node_modules ./node_modules
COPY --from=prerelease /usr/src/app/package.json ./package.json
COPY --from=prerelease /usr/src/app/secrets ./secrets

# Copy Prisma schema and generated client
COPY --from=prerelease /usr/src/app/prisma ./prisma
COPY --from=prerelease /usr/src/app/node_modules/.prisma ./node_modules/.prisma

# Start the app
USER bun
EXPOSE 3000/tcp
CMD bun run start
```

Bun is failing at `RUN bunx prisma generate`, it runs normally on macos but failing on AWS Linux.

Logs:
![Image](https://github.com/user-attachments/assets/ccc791c0-2ab2-44f8-9289-b46bf08656d9)

### Additional information

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x0004A0D0

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/ld-temp.o#L0>): `WTF::jscSignalHandler`

Features: Bun.stdin, dotenv, jsc, spawn, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5296035737/">BUN-7G</a></strong></sub>

**Comment by Jarred-Sumner** [comment] 2024-10-30 09:08
Duplicate of #918

**Comment by Jarred-Sumner** [comment] 2024-10-30 09:20
Please follow along in #918. @nektro is actively working on shipping a musl build of Bun. The glibc build in our current alpine image doesn't work well.

**Closed as not planned by Jarred-Sumner** 2024-10-30 09:20 UTC
Labels: bug, needs triage
