### ISSUE TITLE
Bun build --compile output in wrong path

### ISSUE THREAD

**Issue by andreszorro** [oven-sh/bun#9048] opened 2024-02-22 13:48 UTC
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

1. Having a simple file structure like this:
```
dist
main.ts
test.hbs
```

```ts
// main.ts
import text from "./test.hbs";
console.log(text);
```

2. Run `bun build ./main.ts --compile --outfile ./dist/main`

### What is the expected behavior?

The output file is correctly created in `dist/main` folder.

### What do you see instead?

The output file is created adjacent to main.ts.

### Additional information

This happens with other unsupported file extensions. This does not happen with `txt` file extension.

**Comment by masad-frost** [comment] 2024-02-25 20:44
Probably duplicate of #8697

**Comment by timonaldenhoff** [comment] 2024-03-02 08:43
Same issue in v1.0.29

**Comment by Jarred-Sumner** [comment] 2024-04-19 20:14
Duplicate of #8697

**Closed as not planned by Jarred-Sumner** 2024-04-19 20:14 UTC
Labels: bug, bundler
