### ISSUE TITLE
Segmentation fault at adress 0x18

### ISSUE THREAD

**Issue by gmc091** [oven-sh/bun#13440] opened 2024-08-21 08:23 UTC
### How can we reproduce the crash?

After comipling the /middleware, copied from clerk documentation, I get this error.

### Relevant log output

```shell
This is my middleware.ts file:

import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";

const isProtectedRoute = createRouteMatcher(["/"]);

export default clerkMiddleware((auth, req) => {
  if (isProtectedRoute(req)) {
    auth().protect();
  }

  return NextResponse.next();
});

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    // Always run for API routes
    "/(api|trpc)(.*)",
  ],
};
```

### Stack Trace (bun.report)

Bun v1.1.24 ([`85a3299`](<https://github.com/oven-sh/bun/tree/85a32991152871b06becd6b411eb663008369769>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000018

- [`HashTable.h:676`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/C:/buildkite-agent/builds/windows-x64-hetzner-3/bun/bun/build/bun-webkit/include/wtf/HashTable.h#L676>): `WTF::HashTable<void *,WTF::KeyValuePair<void *,JSC::Weak<JSC::JSObject> >,WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<void *,JSC::Weak<JSC::JSObject> > >,WTF::DefaultHash<void *>,WTF::HashMap<void *,JSC::Weak<JSC::JSObject>,WTF::DefaultHash<void *>,WTF::HashTraits<void *>,WTF::HashTraits<JSC::Weak<JSC::JSObject> >,WTF::HashTableTraits>::KeyValuePairTraits,WTF::HashTraits<void *> >::inlineLookup`
- [`JSCJSValueInlines.h:265`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSCJSValueInlines.h#L265>): `JSC::JSValue::decode`
- [`VMTraps.h:206`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/VMTraps.h#L206>): `JSC::VMTraps::maybeNeedHandling`
- [`LLIntSlowPaths.cpp:967`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L967>): `llint_slow_path_get_by_id`
- `llint_entry`

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:19
Duplicate of https://github.com/oven-sh/bun/issues/13629

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:19
Please follow along in https://github.com/oven-sh/bun/issues/13629. It will get fixed

**Closed as completed by Jarred-Sumner** 2024-09-01 04:19 UTC
Labels: crash, windows
