### ISSUE TITLE
A version manager like nvm (or volta, fnm, etc) being built into Bun

### ISSUE THREAD

**Issue by sak2** [oven-sh/bun#6235] opened 2023-10-02 12:01 UTC
### What is the problem this feature would solve?

Eventually as Bun grows and has more versions coming out and people start building projects on it - like with Node and its versions and incompatibility in older projects - people will run into compatibility issues. Node does not solve this problem but we need tools like nvm for it.

### What is the feature you are proposing to solve the problem?

The the Bun runtime and installation allow you to run projects as if you're running different versions of Bun - essentially what nvm does but baked in instead of virtual installations managed by your node version manager program.

**Comment by Electroid** [comment] 2023-10-02 16:53
Duplicate of #3917

**Closed as not planned by Electroid** 2023-10-02 16:53 UTC
Labels: enhancement

**Comment by robcresswell** [comment] 2025-01-04 21:07
@fardarter read the linked duplicate
