### ISSUE TITLE
Puppeteer creates a corrupt PDF file

### ISSUE THREAD

**Issue by lacikawiz** [oven-sh/bun#8482] opened 2024-01-25 13:11 UTC
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 5.15.0-91-generic x86_64 x86_64

### What steps can reproduce the bug?

Run the following code and try to open the PDF file created.

```JS
const headless=true

async function generatePDF() {
  const browser = await puppeteer.launch({ headless: headless ? 'new' : false });
  const page = (await browser.pages())[0]

  // await page.setContent('<h1>Hello, Puppeteer!</h1>');
  await page.goto('https://news.ycombinator.com/')

  await page.waitForSelector("body")
  await page.waitForNetworkIdle()

  await page.pdf({  path:'test02.pdf'  })
  await browser.close()
}

await generatePDF()
```

### What is the expected behavior?

A valid PDF created that can be opened by PDF readers.

### What do you see instead?

A corrupt PDF file is created. When trying to open with Xreader I get: `PDF document is damaged`. Google Chrome (v120) says: `Failed to load PDF document.`. Midnight commander says: `Syntax Error: Couldn't find trailer dictionary`

### Additional information

The same code when run with `node` generates a valid PDF file that can be opened by all readers.

The simple page (commented out line) with the `Hello, Puppeteer!` H1 message generates a correct PDF file. Also tested with `.setContent` but with larger HTML code and the resulting PDF file was also corrupt. So it might be a buffering issue that only comes up when the content is larger.

This issue might be related to https://github.com/oven-sh/bun/issues/7728 but the manifestation is different (no error message, only a corrupt file generated).

### Workaround

By replacing the line:
```JS
await page.pdf({  path:'test02.pdf'  })
```
with:
```JS
await Bun.write("test02.pdf", await page.pdf({}))
```
The generated PDF file will be valid.

**Comment by Electroid** [comment] 2024-01-25 17:33
Duplicate of #7728

**Closed as not planned by Electroid** 2024-01-25 17:33 UTC
Labels: bug, node.js

**Comment by hayyangovinda** [comment] 2025-01-30 14:23
res.status(200).send(**### Buffer.from**(pdfBuffer));

in node it solve the issue
