### ISSUE TITLE
Didn't support TextDecoderStream

### ISSUE THREAD

**Issue by grapewheel** [oven-sh/bun#10163] opened 2024-04-11 07:49 UTC
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Linux 6.6.25-1-lts x86_64 unknown (archlinux)

### What steps can reproduce the bug?

While I used the module `modelfusion` 's `streamText` function

```js 
import { streamText } from 'modelfusion'

const textStream = await streamText({
  model,
  prompt,
})
```
The `streamText` function use the `TextDecoderStream` which includes in the Node >= 16.6, [MDN DOC](https://developer.mozilla.org/zh-CN/docs/Web/API/TextDecoderStream), but the bunjs runs in error below:

```js 
// src/util/streaming/parseEventSourceStream.ts
async function parseEventSourceStream({
  stream
}) {
const eventStream = stream.pipeThrough(new TextDecoderStream()).pipeThrough(new EventSourceParserStream());

ReferenceError: Can't find variable: TextDecoderStream
```

**Comment by Jarred-Sumner** [comment] 2024-04-11 07:54
Duplicate of #5648

**Closed as not planned by Jarred-Sumner** 2024-04-11 07:54 UTC
Labels: bug
