### ISSUE TITLE
console.log not able to log actual error metadata like node js

### ISSUE THREAD

**Issue by rdev06** [oven-sh/bun#9656] opened 2024-03-27 09:59 UTC
### What version of Bun is running?

1.0.35+940448d6b

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

create a file index.js and copy pase below code
```
try {
    const err = new Error('Document failed validation');
    const meta = {
        index: 0,
        code: 121,
        errInfo: {
          failingDocumentId: '6603d051d45be464c7c11b25',
          details: {
            operatorName: '$jsonSchema',
            title: 'An initial user details in the platform',
            schemaRulesNotSatisfied: []
          }
        }
      }
      for (const name in meta) {
        err[name] = meta[name]
      }
    throw err;
} catch (error) {
    console.log(error)
}
```

### What is the expected behavior?

this show print the error like below, i get the error while executing code with nodejs.
`node index.js`
```
Error: Document failed validation
    at file:///Users/roshandev/work/study/bunt/index.js:20:17
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  index: 0,
  code: 121,
  errInfo: {
    failingDocumentId: '6603d051d45be464c7c11b25',
    details: {
      operatorName: '$jsonSchema',
      title: 'An initial user details in the platform',
      schemaRulesNotSatisfied: []
    }
  }
}
```

### What do you see instead?

when i execute it with bun, it does not show all meta data.
```
16 | 
17 | 
18 | 
19 | try {
20 |     const err = new Error('Document failed validation');
21 |     const meta = {
                   ^
error: Document failed validation
 code: "121"

      at module code (/Users/roshandev/work/study/bunt/index.js:21:15)
      
```

One more thing stack trance also don't contain all files locations. Since this error manually generated so it gives the file path from where it fired but while using it inside project, it does not give actual file location.

### Additional information

I am relatively new with bun.js and started migrating my code to bun.js, so i am missing something or if i missed any flag please let me know. Since i didn't found same bug anywhere over internet.

**Comment by Electroid** [comment] 2024-03-27 18:39
Duplicate of #185

**Closed as not planned by Electroid** 2024-03-27 18:39 UTC
Labels: bug
