### ISSUE TITLE
TypeError: FormData parse error missing final boundary with bun

### ISSUE THREAD

**Issue by Liliandev** [oven-sh/bun#6038] opened 2023-09-25 14:08 UTC
### What version of Bun is running?

1.0.3

### What platform is your computer?

Linux

### What steps can reproduce the bug?

Clone an astrobuild project with Form and form data submission, an error will throw with : TypeError: FormData parse error missing final boundary when running bun with following command : bun ./dist/server/entry.mjs

If i run in dev mode, no error appears

### What is the expected behavior?

No error should throw

**Comment by Electroid** [comment] 2023-09-25 16:49
Duplicate of #2644

**Closed as not planned by Electroid** 2023-09-25 16:49 UTC
Labels: bug
