### ISSUE TITLE
bun upgrade fails on wsl2 ubuntu

### ISSUE THREAD

**Issue by malisetti** [oven-sh/bun#443] opened 2022-07-08 15:02 UTC
```console
abbiya@LAPTOP-BQ34OVAE:~$ bun upgrade
error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
abbiya@LAPTOP-BQ34OVAE:~$ strace bun upgrade
execve("/home/abbiya/.bun/bin/bun", ["bun", "upgrade"], 0x7ffcf28bc858 /* 21 vars */) = 0
brk(NULL)                               = 0x6942000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffef47b59b0) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=32421, ...}) = 0
mmap(NULL, 32421, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fe88e352000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \22\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=18848, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe88e350000
mmap(NULL, 20752, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe88e34a000
mmap(0x7fe88e34b000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7fe88e34b000
mmap(0x7fe88e34d000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fe88e34d000
mmap(0x7fe88e34e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fe88e34e000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\323\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1369384, ...}) = 0
mmap(NULL, 1368336, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe88e1fb000
mmap(0x7fe88e208000, 684032, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xd000) = 0x7fe88e208000
mmap(0x7fe88e2af000, 626688, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb4000) = 0x7fe88e2af000
mmap(0x7fe88e348000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14c000) = 0x7fe88e348000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220q\0\0\0\0\0\0"..., 832) = 832
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0{E6\364\34\332\245\210\204\10\350-\0106\343="..., 68, 824) = 68
fstat(3, {st_mode=S_IFREG|0755, st_size=157224, ...}) = 0
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0{E6\364\34\332\245\210\204\10\350-\0106\343="..., 68, 824) = 68
mmap(NULL, 140408, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe88e1d8000
mmap(0x7fe88e1de000, 69632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7fe88e1de000
mmap(0x7fe88e1ef000, 24576, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7fe88e1ef000
mmap(0x7fe88e1f5000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c000) = 0x7fe88e1f5000
mmap(0x7fe88e1f7000, 13432, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fe88e1f7000close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300A\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32, 848) = 32
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\30x\346\264ur\f|Q\226\236i\253-'o"..., 68, 880) = 68
fstat(3, {st_mode=S_IFREG|0755, st_size=2029592, ...}) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32, 848) = 32
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\30x\346\264ur\f|Q\226\236i\253-'o"..., 68, 880) = 68
mmap(NULL, 2037344, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe88dfe6000
mmap(0x7fe88e008000, 1540096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7fe88e008000
mmap(0x7fe88e180000, 319488, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19a000) = 0x7fe88e180000
mmap(0x7fe88e1ce000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e7000) = 0x7fe88e1ce000
mmap(0x7fe88e1d4000, 13920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fe88e1d4000close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe88dfe4000
mmap(NULL, 339968, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe88df91000
arch_prctl(ARCH_SET_FS, 0x7fe88dfe2140) = 0
mprotect(0x7fe88e1ce000, 16384, PROT_READ) = 0
mprotect(0x7fe88e1f5000, 4096, PROT_READ) = 0
mprotect(0x7fe88e348000, 4096, PROT_READ) = 0
mprotect(0x7fe88e34e000, 4096, PROT_READ) = 0
mprotect(0x4c89000, 765952, PROT_READ)  = 0
mprotect(0x7fe88e387000, 4096, PROT_READ) = 0
munmap(0x7fe88e352000, 32421)           = 0
set_tid_address(0x7fe88dfe2410)         = 50
set_robust_list(0x7fe88dfe2420, 24)     = 0
rt_sigaction(SIGRTMIN, {sa_handler=0x7fe88e1debf0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7fe88e1ec420}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7fe88e1dec90, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7fe88e1ec420}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
getrandom("\xe7\x77\x11\x33\xf4\x4a\x43\x88\x8c\x73\x58\x34\x81\x31\xe5\x26\x99\x68\x79\x88\xb9\xae\xd5\xfc\xd7\xa9\x43\xc2\x99\xca\x7d\x26", 32, GRND_NONBLOCK) = 32
openat(AT_FDCWD, "/proc/sys/vm/overcommit_memory", O_RDONLY) = 3
read(3, "0\n", 32)                      = 2
close(3)                                = 0
brk(NULL)                               = 0x6942000
brk(0x6963000)                          = 0x6963000
futex(0x62f0cfc, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x62f0d08, FUTEX_WAKE_PRIVATE, 2147483647) = 0
prlimit64(0, RLIMIT_STACK, {rlim_cur=12500*1024, rlim_max=12500*1024}, NULL) = 0
rt_sigaction(SIGABRT, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO, sa_restorer=0x7fe88e1ec420}, NULL, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO, sa_restorer=0x7fe88e1ec420}, NULL, 8) = 0
rt_sigaction(SIGFPE, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO, sa_restorer=0x7fe88e1ec420}, NULL, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO, sa_restorer=0x7fe88e1ec420}, NULL, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO, sa_restorer=0x7fe88e1ec420}, NULL, 8) = 0
rt_sigaction(SIGTRAP, {sa_handler=0x3e110a0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_RESETHAND|SA_SIGINFO, sa_restorer=0x7fe88e1ec420}, NULL, 8) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
access("/sys/devices/system/node/node1", R_OK) = -1 ENOENT (No such file or directory)
mmap(0x37a54000000, 67108864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x37a54000000
getcwd("/home/abbiya", 4096)            = 13
getcwd("/home/abbiya", 4096)            = 13
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=12500*1024, rlim_max=12500*1024}) = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=1024*1024}) = 0
prlimit64(0, RLIMIT_NOFILE, {rlim_cur=1024*1024, rlim_max=1024*1024}, NULL) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
mmap(NULL, 67112960, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fe889f90000
mprotect(0x7fe889f91000, 67108864, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fe88df3f5b0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[51], tls=0x7fe88df90700, child_tidptr=0x7fe88df909d0) = 51
futex(0x37a540c00f8, FUTEX_WAIT_PRIVATE, 0, NULLerror: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
) = ?
+++ exited with 1 +++

**Comment by FinnRG** [comment] 2022-07-08 17:11
@malisetti  Duplicate of #233. Please try ```wsl --update``` (and then restart). If this doesn't work, please make sure that you are using WSL2.

**Closed as completed** 2022-07-09 00:21 UTC
