### ISSUE TITLE
Malformed_HTTP_Response: fetch() failed on amazon cloudfront 302 responses

### ISSUE THREAD

**Issue by glensc** [oven-sh/bun#8599] opened 2024-01-31 20:25 UTC
### What version of Bun is running?

1.0.25

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

Rather randomly a request fails:

```
$ bun -e 'await fetch("https://turnoff.us/geek/frontenders-and-backenders")'
$ bun -e 'await fetch("https://turnoff.us/geek/frontenders-and-backenders")'
$ bun -e 'await fetch("https://turnoff.us/geek/frontenders-and-backenders")'
$ bun -e 'await fetch("https://turnoff.us/geek/frontenders-and-backenders")'
$ bun -e 'await fetch("https://turnoff.us/geek/frontenders-and-backenders")'
Malformed_HTTP_Response: fetch() failed. For more information, pass `verbose: true` in the second argument to fetch()
 path: "https://turnoff.us/geek/frontenders-and-backenders"
```

### What is the expected behavior?

No error.

another the problem is that it's too much noise to enable `verbose: true` for every request, and the exception throw has no details.  

please improve the api to be able to get those verbose logs post mortem, not require whole code to run in verbose mode.

### Additional information

doing same with `curl`, yields no errors

```
$ curl -iL https://turnoff.us/geek/frontenders-and-backenders
```

and URL with slash (omitting 302 redirect) does not reproduce the errors. (at least not that often that I noticed error with retries).

```
$ bun -e 'await fetch("https://turnoff.us/geek/frontenders-and-backenders/")'
```

first response headers. note the age is huge, so I don't see the response being different time to time on retries.

```
➜ curl -i https://turnoff.us/geek/frontenders-and-backenders 
HTTP/2 302 
content-type: text/html; charset=utf-8
content-length: 313
x-amz-error-code: Found
x-amz-error-message: Resource Found
location: /geek/frontenders-and-backenders/
date: Wed, 31 Jan 2024 00:23:34 GMT
server: AmazonS3
x-cache: Hit from cloudfront
via: 1.1 c68aa4270b22c7e4e7044fd6df451f70.cloudfront.net (CloudFront)
x-amz-cf-pop: HEL50-C1
x-amz-cf-id: eC-2viVDuZguvad733yV2M4pVg535x8cp3ycFXA-MHEIDoieTyzuqw==
age: 72186

<html>
<head><title>302 Moved Temporarily</title></head>
<body>
<h1>302 Moved Temporarily</h1>
<ul>
<li>Code: Found</li>
<li>Message: Resource Found</li>
<li>RequestId: 33PJQ2MDZJ8ZSD02</li>
<li>HostId: 1xr/a0gwVb28L/PaP1226wGlFnD8D+LF04vI2NjRuApcl6u9ROFMJBBHCCVGn+YwkmYA80Aq1Ak=</li>
</ul>
<hr/>
</body>
</html>
```

```
➜ curl -i https://turnoff.us/geek/frontenders-and-backenders  --http1.1
HTTP/1.1 302 Moved Temporarily
Content-Type: text/html; charset=utf-8
Content-Length: 313
Connection: keep-alive
x-amz-error-code: Found
x-amz-error-message: Resource Found
Location: /geek/frontenders-and-backenders/
Date: Thu, 01 Feb 2024 00:24:19 GMT
Server: AmazonS3
X-Cache: Hit from cloudfront
Via: 1.1 78dbcb60ca54760934851cf8d8476f3a.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: HEL50-C1
X-Amz-Cf-Id: 0gN9XvwJuJ1pFgnlYRzhi9-mQn6E5LfG2F0txVHlKzQ8sIBnhFxw5w==
Age: 80351

<html>
<head><title>302 Moved Temporarily</title></head>
<body>
<h1>302 Moved Temporarily</h1>
<ul>
<li>Code: Found</li>
<li>Message: Resource Found</li>
<li>RequestId: XN1XSMTC2GJDJPE3</li>
<li>HostId: /a63Tkd7pzZGqpA1FTA4aGolCT5GdXcKU6KrSsarV/iPevXYm3+IW8tpzAILDr4oTTsyavwWIMY=</li>
</ul>
<hr/>
</body>
</html>
```

**Comment by glensc** [comment] 2024-01-31 20:32
I created some script to loop, run with verbose true and print output if exit code is non-zero.

- [8599-loop.sh](https://github.com/oven-sh/bun/files/14117000/8599-loop.sh.txt) 207 bytes


but two things happened:
1. it still suggests to pass verbose: true
2. I don't see anything fishy in the verbose

```
➜ sh 8599-loop.sh
Request: GET /geek/frontenders-and-backenders
	Connection: keep-alive
	User-Agent: Bun/1.0.25
	Accept: */*
	Host: turnoff.us
	Accept-Encoding: gzip, deflate, br

Response: < 302 Moved Temporarily
< 	Content-Type: text/html; charset=utf-8
< 	Content-Length: 313
< 	Connection: keep-alive
< 	x-amz-error-code: Found
< 	x-amz-error-message: Resource Found
< 	Location: /geek/frontenders-and-backenders/
< 	Date: Wed, 31 Jan 2024 00:40:58 GMT
< 	Server: AmazonS3
< 	X-Cache: Hit from cloudfront
< 	Via: 1.1 16680cb8308307715d75bb3354b1ae38.cloudfront.net (CloudFront)
< 	X-Amz-Cf-Pop: HEL50-C1
< 	X-Amz-Cf-Id: 6cgYZXxmHdqL2fBJTwlFeGBlFFhWLweMbK4dac_M8zRYoivQMfLZhA==
< 	Age: 71339

Request: GET /geek/frontenders-and-backenders/
	Connection: keep-alive
	User-Agent: Bun/1.0.25
	Accept: */*
	Host: turnoff.us
	Accept-Encoding: gzip, deflate, br

Malformed_HTTP_Response: fetch() failed. For more information, pass `verbose: true` in the second argument to fetch()
 path: "https://turnoff.us/geek/frontenders-and-backenders"
```

**Comment by glensc** [comment] 2024-01-31 20:33
for compare. this is output when error did not happen

```
++ bun -e 'await fetch("https://turnoff.us/geek/frontenders-and-backenders", {verbose: true})'
+ out='Request: GET /geek/frontenders-and-backenders
	Connection: keep-alive
	User-Agent: Bun/1.0.25
	Accept: */*
	Host: turnoff.us
	Accept-Encoding: gzip, deflate, br

Response: < 302 Moved Temporarily
< 	Content-Type: text/html; charset=utf-8
< 	Content-Length: 313
< 	Connection: keep-alive
< 	x-amz-error-code: Found
< 	x-amz-error-message: Resource Found
< 	Location: /geek/frontenders-and-backenders/
< 	Date: Wed, 31 Jan 2024 00:40:58 GMT
< 	Server: AmazonS3
< 	X-Cache: Hit from cloudfront
< 	Via: 1.1 71208833688838f959b0e70682af50b2.cloudfront.net (CloudFront)
< 	X-Amz-Cf-Pop: HEL50-C1
< 	X-Amz-Cf-Id: j7ymzF87Z_YUX48QzQ6GoEh02RRtY8JeeID5DMg0-NZcVp-9D4y4Ug==
< 	Age: 71501

Request: GET /geek/frontenders-and-backenders/
	Connection: keep-alive
	User-Agent: Bun/1.0.25
	Accept: */*
	Host: turnoff.us
	Accept-Encoding: gzip, deflate, br

Response: < 200 OK
< 	Content-Type: text/html
< 	Transfer-Encoding: chunked
< 	Connection: keep-alive
< 	Last-Modified: Tue, 30 Jan 2024 00:15:41 GMT
< 	Server: AmazonS3
< 	Content-Encoding: gzip
< 	Date: Wed, 31 Jan 2024 00:33:18 GMT
< 	Cache-Control: max-age=86400
< 	ETag: W/"71e9c33891feabe954ed7f553eeb97ef"
< 	Vary: Accept-Encoding
< 	X-Cache: Hit from cloudfront
< 	Via: 1.1 71208833688838f959b0e70682af50b2.cloudfront.net (CloudFront)
< 	X-Amz-Cf-Pop: HEL50-C1
< 	X-Amz-Cf-Id: FUIxEwsQq7XXWrJRcDC7RckCkWnpbysfJ8aXLmfi2qaUy2BzT5ghAA==
< 	Age: 71963'
+ rc=0
```

**Comment by Jarred-Sumner** [comment] 2024-01-31 20:48
Bun doesn't implement HTTP/2 in fetch yet. Cloudfront seems to always be returning HTTP/2.

**Comment by glensc** [comment] 2024-01-31 20:50
Eeh? but how do you explain that I get the responses most of the time... even shows location headers, etc...

To my knowledge you can't mistakenly do half of http2, as it's binary protocol vs http1

**Comment by Jarred-Sumner** [comment] 2024-02-13 06:44
This seems to be fixed by @cirospaciari in https://github.com/oven-sh/bun/pull/8874, as I am able to reproduce the issue in v1.0.26 but no longer in canary.

Please run `bun upgrade --canary` and leave a comment if you continue to run into this and i'll re-open

**Closed as completed by Jarred-Sumner** 2024-02-13 06:44 UTC
Labels: bug
