### ISSUE TITLE
Commitlint not supported

### ISSUE THREAD

**Issue by notramo** [oven-sh/bun#6184] opened 2023-09-29 19:18 UTC
### What version of Bun is running?

official Docker image 1.0.3

### What platform is your computer?

x64

### What steps can reproduce the bug?

1. Setup Husky
2. Add the following to `.husky/commit-msg`
```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

bun run commitlint --edit ${1}
```
4. Try to create a new commit in Git.

### What is the expected behavior?

Commitlint checks the commit message.

### What do you see instead?

```
131 |     process[exports.REGISTER_INSTANCE] = service;
132 |     // Register the extensions.
133 |     registerExtensions(service.options.preferTsExts, service.extensions.compiled, service, originalJsHandler);
134 |     (0, cjs_resolve_hooks_1.installCommonjsResolveHooksIfNecessary)(service);
135 |     // Require specified modules before start-up.
136 |     module_1.Module._preloadModules(service.options.require);
        ^
TypeError: module_1.Module._preloadModules is not a function. (In 'module_1.Module._preloadModules(service.options.require)', 'module_1.Module._preloadModules' is undefined)
      at register (/home/bun/project/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.7.2_typescript@5.2.2/node_modules/ts-node/dist/index.js:136:4)
      at TypeScriptLoader (/home/bun/project/node_modules/.pnpm/cosmiconfig-typescript-loader@4.4.0_@types+node@20.5.1_cosmiconfig@8.3.6_ts-node@10.9.1_typescript@5.2.2/node_modules/cosmiconfig-typescript-loader/dist/cjs/index.js:52:8)
      at /home/bun/project/node_modules/.pnpm/@commitlint+load@17.7.2/node_modules/@commitlint/load/lib/utils/load-config.js:12:10
      at loadConfig (/home/bun/project/node_modules/.pnpm/@commitlint+load@17.7.2/node_modules/@commitlint/load/lib/utils/load-config.js:10:26)
      at /home/bun/project/node_modules/.pnpm/@commitlint+load@17.7.2/node_modules/@commitlint/load/lib/load.js:19:19
      at load (/home/bun/project/node_modules/.pnpm/@commitlint+load@17.7.2/node_modules/@commitlint/load/lib/load.js:17:20)
      at /home/bun/project/node_modules/.pnpm/@commitlint+cli@17.7.2/node_modules/@commitlint/cli/lib/cli.js:189:19
      at processTicksAndRejections (:55:76)
error: "commitlint" exited with code 1 (SIGHUP)
```

### Additional information

Same error when launched with `bun x` instead of `bun run`.

**Comment by imcm7** [comment] 2023-10-02 04:36
The same is here with mikro-orm https://github.com/mikro-orm/mikro-orm/discussions/4771#discussioncomment-7159217.
And not import if run with `bun x` instead of ` bun run`.
Was ok prior.

**Comment by Electroid** [comment] 2023-10-02 18:23
Duplicate of #6227

**Closed as not planned by Electroid** 2023-10-02 18:23 UTC
Labels: bug
