### ISSUE TITLE
Sentinel Mismatch

### ISSUE THREAD

**Issue by lrbateman2611** [oven-sh/bun#11854] opened 2024-06-13 19:45 UTC
### How can we reproduce the crash?

Running on windows 10 through proxmox. Error occurs during powershell install or when trying to run any bun command after scoop install.

### Relevant log output

```shell
################################################################################################################ 100.0%
============================================================
Bun v1.1.13 (bd6a6051) Windows x64 (baseline)
Args:
Elapsed: 2ms | User: 0ms | Sys: 15ms
RSS: 16.12MB | Peak: 16.13MB | Commit: 61.68MB | Faults: 4084

panic(thread 6680): sentinel mismatch
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

[removed]

Install Failed - could not verify bun.exe
The command 'C:\Users\Versa\.bun\bin\bun.exe --revision' exited with code 3

1
```

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on windows x86_64_baseline [_]

**panic**: sentinel mismatch

- [`string_builder.zig:188`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/string_builder.zig#L188>): `writable`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/src/startup/exe_common.inl#L78>): `invoke_main`
- ??? at `0x17344` in 
- ??? at `0x4cc91` in

**Comment by Jarred-Sumner** [comment] 2024-06-13 19:46
Duplicate of #3312

**Closed as not planned** 2024-06-13 19:46 UTC
Labels: crash
