### ISSUE TITLE
Bun not supported on virtual machines using CPU-emulation

### ISSUE THREAD

**Issue by ahoys** [oven-sh/bun#6768] opened 2023-10-28 11:00 UTC
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux 5.15.0-86-generic x86_64 x86_64

### What steps can reproduce the bug?

Run Ubuntu Server VM on Proxmox, with the default kmv64 CPU emulation.

`bun index.ts`
```
// index.ts
Bun.serve({
  fetch(req) {
    return new Response("Hello World!");
  },
});
```

### What is the expected behavior?

Run the code without crashing on emulated kvm64 CPUs, instead of forcing to reveal the host CPU.

### What do you see instead?

```
TypeError: 湕捩摯⁥潨瑳慮敭⁳畭瑳愠牬慥祤戠⁥湥潣敤⁤潦⁲潮⹷渊睥唠䱒椨灮瑵⸩潨瑳慮敭猠潨汵⁤潤琠敨琠楲正.慢敳剕⁉慣❮⁴慨敶愠甠敳湲浡⁥牯瀠獡睳牯d畏⁴景洠浥牯⁹桷汩⁥污潬慣楴杮爠煥敵瑳戠摯⁹畢
 code: "ERR_INVALID_ARG_TYPE"
```

### Additional information

You can avoid this issue by setting the VM hardware/CPU to be of type "Host", instead of the kvm64 (default) emulation. This however is not practical in production, considering that usually these VMs run on top of some emulated CPU type that will preserve the VM if it is moved to a different machine with different CPU/architecture.

Flags of kvm64 (not working):
```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36
clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid
tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
```

Flags of Host (working):
```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse
                         36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm const
                         ant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni
                          pclmulqdq vmx ssse3 fma cx16 pdcm sse4_1 sse4_2 x2apic movbe popcnt 
                         tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3
                         dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shado
                         w vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 sme
                         p bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt x
                         savec xgetbv1 xsaves avx_vnni arat umip pku ospke waitpkg gfni vaes v
                         pclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_capabi
                         lities
```

**Comment by Jarred-Sumner** [comment] 2023-10-28 11:23
Duplicate of #3312

**Closed as not planned by Jarred-Sumner** 2023-10-28 11:23 UTC
Labels: bug
