### ISSUE TITLE
Implement `process.stderr` and `process.stdout`

### ISSUE THREAD

**Issue by avin-kavish** [oven-sh/bun#1143] opened 2022-08-25 05:46 UTC
### Version

0.1.10

### Platform

Linux avin-mint 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Run this script

```ts
import b from 'benny'

const testData = Array.from({ length: 10_000 }, () => new Object())

let x, y, z

b.suite(
  'iteration',

  b.add('for i', () => {
    for (let i = 0; i < testData.length; i++) {
      x = testData[i]
    }
  }),

  b.add('for of', () => {
    for (let testDatum of testData) {
      y = testDatum
    }
  }),

  b.add('for each', () => {
    testData.forEach((value, index) => {
      z = value
    })
  }),

  b.cycle(),
  b.complete(),
  b.save({ file: 'array-iteration', version: '1.0.0' }),
  b.save({ file: 'array-iteration', format: 'chart.html' }),
)
```

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behavior?

The program runs.

### What do you see instead?

```
[0.01ms] ".env"
4 | const wrapAnsi = require('wrap-ansi');
5 | const sliceAnsi = require('slice-ansi');
6 | 
7 | const defaultTerminalHeight = 24;
8 | 
9 | const getWidth = stream => {
                               ^
TypeError: Right side of assignment cannot be destructured
      at /home/avin/code/viduli/super/node_modules/log-update/index.js:9:27
      at /home/avin/code/viduli/super/node_modules/log-update/index.js:36:21
      at /home/avin/code/viduli/super/node_modules/log-update/index.js:82:17
      at bun:wrap:1:16354
      at /home/avin/code/viduli/super/node_modules/benny/lib/complete.js:14:26
      at bun:wrap:1:16354
      at /home/avin/code/viduli/super/node_modules/benny/lib/index.js:6:27
      at bun:wrap:1:16354
      at /home/avin/code/viduli/super/benchmark/array-iteration.mts:1:0
```

**Comment by Jarred-Sumner** [comment] 2022-08-25 06:03
The error and stack trace is confusing but 

The issue is missing `process.stderr`

The error is saying "cannot destructure undefined/null"

**Comment by xhyrom** [comment] 2022-08-25 11:44
This is duplicate of https://github.com/oven-sh/bun/issues/894

**Closed as not planned** 2022-08-26 05:16 UTC
Labels: bug

**Comment by avin-kavish** [comment] 2022-08-26 05:54
So this won't be implemented? `process.std...` is very common in npm packages.

**Comment by Jarred-Sumner** [comment] 2022-08-26 05:55
It will be implemented

This is just a duplicate issue

**Comment by Jarred-Sumner** [comment] 2022-08-26 05:55
It will be implemented

This is a duplicate issue
