### ISSUE TITLE
Can't parse bun run arguments to package.json script

### ISSUE THREAD

**Issue by ranuwp** [oven-sh/bun#5427] opened 2023-09-15 01:34 UTC
### What is the problem this feature would solve?

Now bun doesn't support npm_config_* variables in package.json scripts
```.json
// package.json
{
  // ...
  "scripts": {
    "e2e:ios:tag": "npx wdio run ./config/wdio.ios.local.conf.ts --cucumberOpts.tagExpression=\"$npm_config_tag\"",
  }
  // ...
}
```

### What is the feature you are proposing to solve the problem?

I want to simplify argument when running script like `bun run e2e:ios:tag --tag=@feature`

**Comment by Electroid** [comment] 2023-10-27 23:41
Duplicate of #73

**Closed as not planned by Electroid** 2023-10-27 23:41 UTC
Labels: enhancement, bun install
