### ISSUE TITLE
Segmentation Fault at 26 on macOS 12.4 M1

### ISSUE THREAD

**Issue by OfficialDelta** [oven-sh/bun#607] opened 2022-07-12 00:23 UTC
### Version

0.1.2

### Platform

Darwin MACBOOK-NAME_CENSORED.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### What steps will reproduce the bug?

Run the following code block with bun:
```js
// const fetch = require('node-fetch');
import fs from 'node:fs'
// const tqdm = require('tqdm')

function sleep_async(seconds) {
    return new Promise(resolve => setTimeout(resolve, seconds * 1000));
}

function sleep(seconds) {
    let e = new Date().getTime() + (seconds * 1000);
    while (new Date().getTime() <= e) { }
}

// let uniqueNbtKeys = {};

async function getItemInfo(itemId) {
    let soldItems = [];
    let page = 0;

    function loop(resolve) {
        return fetchPage(itemId, page)
            .then(res => {
                if (res.length) {
                    soldItems = soldItems.concat(res);
                    page++;
                    sleep(0.2);
                    loop(resolve);
                } else {
                    return resolve();
                }
            })
    }

    await new Promise(resolve => {
        return loop(resolve);
    });

    // soldItems is an array of objects.
    for (const soldItem of soldItems) {
        let nbtData = soldItem.nbtData.data;
        if (typeof (nbtData.petInfo) == 'string') {
            nbtData.petInfo = JSON.parse(nbtData.petInfo);
        }

        // for (const key of Object.keys(nbtData)) {
        //     if (!Object.keys(uniqueNbtKeys).includes(key)) {
        //         uniqueNbtKeys[key] = {
        //             key: key,
        //             value: nbtData[key],
        //             itemId: itemId
        //         };
        //     }
        // }

        let enchantments = {};

        if (soldItem.enchantments) {
            for (const enchantment of soldItem.enchantments) {
                enchantments[enchantment.type] = enchantment.level;
            }
        }

        let skyblockId = itemId;

        if (itemId.match(/^PET_(?!ITEM)(?!SKIN)\w+/)) {
            skyblockId = 'PET';
        } else if (itemId.match(/^RUNE_\w+/)) {
            skyblockId = 'RUNE';
        } else if (itemId.match(/^POTION_\w+/)) {
            skyblockId = 'POTION';
        }

        const parsedData = {
            uuid: soldItem.uuid,
            item_id: skyblockId,
            price: soldItem.highestBidAmount,
            wood_singularity_count: nbtData.wood_singularity_count ?? 0,
            tuned_transmission: nbtData.tuned_transmission ?? 0,
            stars: nbtData.dungeon_item_level ?? -1,
            reforge: soldItem.reforge == 'None' ? '' : soldItem.reforge,
            rarity_upgrades: nbtData.rarity_upgrades ?? 0,
            power_ability_scroll: nbtData.power_ability_scroll ?? '',
            hot_potato_count: nbtData.hot_potato_count ?? 0,
            gems: nbtData.gems ?? {},
            ethermerge: nbtData.ethermerge ?? -1,
            drill_fuel: nbtData.drill_fuel ?? -1,
            drill_part_upgrade_module: nbtData.drill_part_upgrade_module ?? '',
            drill_part_fuel_tank: nbtData.drill_part_fuel_tank ?? '',
            drill_part_engine: nbtData.drill_part_engine ?? '',
            stored_drill_fuel: nbtData.stored_drill_fuel ?? -1,
            art_of_war_count: nbtData.art_of_war_count ?? 0,
            ability_scroll: nbtData.ability_scroll ?? [],
            count: nbtData.count ?? 1,
            enchantments: enchantments,
            winning_bid: nbtData.winning_bid ?? 0,
            pet_exp: nbtData.petInfo?.exp ?? -1.0,
            pet_candy_used: nbtData.petInfo?.candyUsed ?? -1,
            pet_type: nbtData.petInfo?.type ?? '',
            pet_tier: nbtData.petInfo?.tier ?? '',
            pet_held_item: nbtData.petInfo?.heldItem ?? '',
            pet_skin: nbtData.petInfo?.skin ?? '',
            potion_type: nbtData?.potion ?? '',
            potion_level: nbtData?.potion_level ?? -1,
            potion_enchanced: nbtData?.enchanced ?? -1,
            potion_extended: nbtData?.portion_extended ?? -1,
            potion_splash: nbtData?.splash ?? -1,
            potion_name: nbtData?.potion_name ?? '',
            dungeon_potion: nbtData?.dungeon_potion ?? -1,
            upgrade_level: nbtData?.upgrade_level ?? -1,
            party_hat_year: nbtData?.party_hat_year ?? -1,
            party_hat_color: nbtData?.party_hat_color ?? '',
            talisman_enrichment: nbtData?.talisman_enrichment ?? '',
            dungeon_paper_id: nbtData?.dungeon_paper_id ?? '',
            runes: nbtData?.runes ?? {}, // needs preprocessing
            stats_book: nbtData?.stats_book ?? '',
            base_stat_boost_percentage: nbtData?.baseStatBoostPercentage ?? -1,
            item_tier: nbtData?.item_tier ?? -1,
            item_durability: nbtData?.item_durability ?? -1,
            traps_defused: nbtData?.trapsDefused ?? -1,
            training_weights_held_time: nbtData?.trainingWeightsHeldTime ?? -1,
            maxed_stats: nbtData?.maxed_stats ?? -1,
            skin: nbtData?.skin ?? '',
            basket_edition: nbtData?.basket_edition ?? -1,
            basket_player_name: nbtData?.basket_player_name ?? '',
            boss_id: nbtData?.bossId ?? '',
            spawned_for: nbtData?.spawnedFor ?? '',
            radius: nbtData?.radius ?? -1,
            year_obtained: nbtData?.yearObtained ?? -1,
            cake_owner: nbtData?.cake_owner ?? '',
            soul_durability: nbtData?.soul_durability ?? -1,
            ultimate_soul_eater_data: nbtData?.ultimateSoulEaterData ?? -1,
            expertise_kills: nbtData?.expertise_kills ?? -1,
            is_shiny: nbtData?.is_shiny ?? -1,
            date: nbtData?.date ?? -1,
            edition: nbtData?.edition ?? -1,
            sender_name: nbtData?.sender_name ?? '',
            recipient_name: nbtData?.recipient_name ?? '',
            farmed_cultivating: nbtData?.farmed_cultivating ?? -1,
            farming_for_dummies_count: nbtData?.farming_for_dummies_count ?? -1,
            ranchers_speed: nbtData?.ranchers_speed ?? -1,
            skeletor_kills: nbtData?.skeletorKills ?? -1,
            zombies_killed: nbtData?.zombiesKilled ?? -1,
            necromancer_souls: nbtData?.necromancer_souls ?? [], // needs preprocessing
            sword_kills: nbtData?.sword_kills ?? -1,
            spider_kills: nbtData?.spider_kills ?? -1,
            health: nbtData?.health ?? -1,
            rep_radius: nbtData?.rep_radius ?? -1,
            blocks_broken: nbtData?.blocksBroken ?? -1,
            gilded_gifted_coins: nbtData?.gilded_gifted_coins ?? -1,
            compact_blocks: nbtData?.compact_blocks ?? -1,
            zombie_kills: nbtData?.zombie_kills ?? -1,
            last_potion_ingredient: nbtData?.last_potion_ingredient ?? '',
            should_give_alchemy_exp: nbtData?.should_give_alchemy_exp ?? -1,
            boss_tier: nbtData?.boss_tier ?? -1,
            raider_kills: nbtData?.raider_kills ?? -1,
            bow_kills: nbtData?.bow_kills ?? -1,
            ammo: nbtData?.ammo ?? -1,
            bottle_of_jyrre_seconds: nbtData?.bottle_of_jyrre_seconds ?? -1,
            new_years_cake: nbtData?.new_years_cake ?? -1,
            magma_cubes_killed: nbtData?.magmaCubesKilled ?? -1,
            fishes_caught: nbtData?.fishes_caught ?? -1,
            leader_votes: nbtData?.leaderVotes ?? -1,
            leader_position: nbtData?.leaderPosition ?? -1,
            blood_god_kills: nbtData?.blood_god_kills ?? -1,
            tuning_fork_tuning: nbtData?.tuning_fork_tuning ?? -1,
            eman_kills: nbtData?.eman_kills ?? -1,
            wishing_compass_uses: nbtData?.wishing_compass_uses ?? -1,
            blocks_walked: nbtData?.blocks_walked ?? -1,
            yogs_killed: nbtData?.yogsKilled ?? -1,
            recall_potion_biome: nbtData?.recall_potion_biome ?? '',
            gemstone_slots: nbtData?.gemstone_slots ?? -1,
            attributes: nbtData?.attributes ?? {}, // needs preprocessing
            thunger_charge: nbtData?.thunger_charge ?? -1,
            ghast_blaster: nbtData?.ghast_blaster ?? -1,
            EXE: nbtData?.EXE ?? -1,
            WAI: nbtData?.WAI ?? -1,
            glowing: nbtData?.glowing ?? -1,
            ZEE: nbtData?.ZEE ?? -1,
            blaze_consumer: nbtData?.blaze_consumer ?? -1,
            magma_cube_absorber: nbtData?.magma_cube_absorber ?? -1,
            td_attune_mode: nbtData?.td_attune_mode ?? -1
        };

        const json = JSON.stringify(parsedData);

        fs.appendFileSync('auctions.jsonl', `${json}\n`);
    }
}

function dump() {
    // fetch('https://api.hypixel.net/resources/skyblock/items')
    //     .then(res => res.json())
    //     .then(response => {
    //         if (!response) {
    //             return false;
    //         }

    //         if (!response.success) {
    //             // According to the skyblock documentation, this should never occur. However I don't believe them.
    //             // https://api.hypixel.net/#tag/SkyBlock/paths/~1resources~1skyblock~1items/get
    //             console.log(`Failed to get items, hypixel returned success: false. Error: '${response.cause}'`);
    //             return false;
    //         }

    const itemsApi = 'https://sky.coflnet.com/api/items';
    fetch(itemsApi) // we trust that the api is up and running
        .then(res => res.json())
        .then(async itemTags => {
            let ids = []

            for (const itemTag of itemTags) {
                if (itemTag.flags.includes('AUCTION')) ids.push(itemTag.tag);
            }

            for (const item of ids) {
                await getItemInfo(item);
                sleep(0.3);
                // console.log(`Done with ${item}, ${ids.indexOf(item) + 1}/${ids.length - 1}`);
            }
        });
    // })
    // .catch(reason => {
    //     console.log(`Failed to get items from hypixel: '${reason}'`);
    // });
}

async function fetchPage(itemId, page) {
    const response = await fetch(`https://sky.coflnet.com/api/auctions/tag/${itemId}/sold?page=${page}`);
    const result = await response.text();

    try {
        return JSON.parse(result);
    } catch (e) {
        console.log(`Failed to parse response: '${result}'`);
        return [];
    }
}


dump();
```

### How often does it reproduce? Is there a required condition?

It is reproduced every time I try to run the code block above.

### What do you see instead?

```
SegmentationFault at 26


–––– bun meta ––––
Bun v0.1.2 macOS Silicon 21.5.0
RunCommand: 
Elapsed: 322ms | User: 232ms | Sys: 83ms
RSS: 0.24GB | Peak: 0.24GB | Commit: 73.42MB | Faults: 1
–––– bun meta ––––
```

**Comment by jesus-escalona** [comment] 2022-07-12 00:27
Seeing this exact same issue on Mac M1

Replicated doing:
```
function getUsingFetch() {
    fetch('https://jsonplaceholder.typicode.com/todos/1')
        .then((response) => response.json())
        .then(console.log)
}
getUsingFetch()

export {};
```

**Comment by FinnRG** [comment] 2022-07-12 08:20
@Jesus-Escalona Duplicate of #337. Please upvote the issue there.

**Closed as completed by FinnRG** 2022-07-12 08:20 UTC
Labels: bug, needs repro
