### ISSUE TITLE
bun update --force doesn't update to latest version

### ISSUE THREAD

**Issue by ashish-ts** [oven-sh/bun#10263] opened 2024-04-14 09:14 UTC
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

bun update --force

### What is the expected behavior?

it should ignore version range and update to most latest version but it doesn't

### What do you see instead?

it gives list of packages in terminal with latest version info of package

![image](https://github.com/oven-sh/bun/assets/126181206/dd35e938-b441-4b1a-b4de-4811f598f422)

**Comment by kaminskypavel** [comment] 2024-04-14 09:32
use the `--latest` flag.

this is not a bug.

**Comment by ashish-ts** [comment] 2024-04-15 04:49
I tried --latest flag too even both --force --latest together, still same issue.
Also it just update packages but not update versions in package.json file.

**Comment by adydetra** [comment] 2024-04-15 09:09
Yes, this is not a fix, and I also really need it, because I am also used to `pnpm up --latest`. Hopefully @Jarred-Sumner  and the bun team fix it quickly.

btw i use windows 10 `bun v1.1.3`, and u issue is related to: https://github.com/oven-sh/bun/issues/5856

![image](https://github.com/oven-sh/bun/assets/108399634/b5fd7630-a80d-4f59-8526-dbefe5b4171a)

**Comment by Electroid** [comment] 2024-04-15 16:20
Duplicate of https://github.com/oven-sh/bun/issues/5856

**Closed as not planned by Electroid** 2024-04-15 16:20 UTC
Labels: bug
