### ISSUE TITLE
Can't using `bunx --bun` to run Astro Starlight project

### ISSUE THREAD

**Issue by torn4dom4n** [oven-sh/bun#9989] opened 2024-04-05 15:47 UTC
### What version of Bun is running?

1.1.1+ca1dbb4eb

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

1. Clone [my repo](https://github.com/MedPocket/18-months/actions/runs/8572128829/job/23494027785)
2. Run `bun run dev`

### What is the expected behavior?

Start the dev server with bunx.

### What do you see instead?

```
msg.match is not a function. (In 'msg.match(/ec\.config\.mjs.*(imported from|resolved id)/)', 'msg.match' is undefined)
  Stack trace:
    at <anonymous> (/home/runner/work/1[8](https://github.com/MedPocket/18-months/actions/runs/8572128829/job/23494027785#step:5:8)-months/18-months/node_modules/astro-expressive-code/dist/index.js:39:10)
error: script "build" exited with code 1
Error: Process completed with exit code 1.
```

### Additional information

[Full logs](https://github.com/MedPocket/18-months/actions/runs/8572128829/job/23494027785)

**Comment by Electroid** [comment] 2024-04-08 21:46
Duplicate of https://github.com/oven-sh/bun/issues/7531

**Closed as not planned by Electroid** 2024-04-08 21:46 UTC
Labels: bug
