### ISSUE TITLE
Regression v0.1.5, http, "Importing binding name 'EventEmitter' is not found"

### ISSUE THREAD

**Issue by 19h** [oven-sh/bun#884] opened 2022-07-26 19:24 UTC
### Version

0.1.5

### Platform

Darwin xxx.local 22.0.0 Darwin Kernel Version 22.0.0: Tue Jun 28 20:46:36 PDT 2022; root:xnu-8792.0.134.131.2~1/RELEASE_ARM64_T6000 arm64

### What steps will reproduce the bug?

```
import m3u8stream from 'm3u8stream';

(async () => {
    m3u8stream(
        "https://foooo",
        {
            requestOptions: {
                headers: {
                    cookie: "asd",
                },
            },
        },
    );
})();
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Should work fine and it did in v0.1.4

### What do you see instead?

```
bun run src/index.ts
1 | "use strict";
2 | var __importDefault = (this && this.__importDefault) || function (mod) {
3 |     return (mod && mod.__esModule) ? mod : { "default": mod };
4 | };
5 | const http_1 = __importDefault(require("http"));
                                          ^
SyntaxError: Importing binding name 'EventEmitter' is not found.
      at /Users/xxx/project/node_modules/miniget/dist/index.js:5:39
      at bun:wrap:1:16430
      at /Users/xxx/project/node_modules/m3u8stream/dist/index.js:6:42
      at bun:wrap:1:16430
      at /Users/xxx/project/src/index.ts:1:0
```

### Additional information

This started happening immediately after upgrading to 0.1.5.

**Comment by evanwashere** [comment] 2022-07-26 20:34
caused by imports in #572 @Jarred-Sumner

**Comment by xhyrom** [comment] 2022-08-07 05:31
Fixed by https://github.com/oven-sh/bun/pull/973

**Closed as completed by xhyrom** 2022-08-07 05:31 UTC
Labels: bug
