### ISSUE TITLE
Top-level `using` statement break `export` statement

### ISSUE THREAD

**Issue by codehz** [oven-sh/bun#14098] opened 2024-09-22 16:02 UTC
### What version of Bun is running?

1.1.29+6d43b3662

### What platform is your computer?

Darwin 24.1.0 arm64 arm

### What steps can reproduce the bug?

```js
using a = {}
export default {}
```

### What is the expected behavior?

no syntax error (a runtime error is expected)

### What do you see instead?

```
2 | using a = {}
    ^
SyntaxError: Unexpected keyword 'export'
      at <parse>
```

### Additional information

the proposal [^1] say
> When a using declaration is parsed with BindingIdentifier Initializer, the bindings created in the declaration are tracked for disposal at the end of the containing Block or Module (a using declaration cannot be used at the top level of a Script)

so it should be able to use in the top level of a **Module**

[^1]: https://github.com/tc39/proposal-explicit-resource-management?tab=readme-ov-file#using-declarations-with-explicit-local-bindings

**Comment by codehz** [comment] 2024-09-22 16:06
As reference, this is how typescript handle top level using statement:

```js
var __addDisposableResource = (this && this.__addDisposableResource) || function (env, value, async) {
    if (value !== null && value !== void 0) {
        if (typeof value !== "object" && typeof value !== "function") throw new TypeError("Object expected.");
        var dispose, inner;
        if (async) {
            if (!Symbol.asyncDispose) throw new TypeError("Symbol.asyncDispose is not defined.");
            dispose = value[Symbol.asyncDispose];
        }
        if (dispose === void 0) {
            if (!Symbol.dispose) throw new TypeError("Symbol.dispose is not defined.");
            dispose = value[Symbol.dispose];
            if (async) inner = dispose;
        }
        if (typeof dispose !== "function") throw new TypeError("Object not disposable.");
        if (inner) dispose = function() { try { inner.call(this); } catch (e) { return Promise.reject(e); } };
        env.stack.push({ value: value, dispose: dispose, async: async });
    }
    else if (async) {
        env.stack.push({ async: true });
    }
    return value;
};
var __disposeResources = (this && this.__disposeResources) || (function (SuppressedError) {
    return function (env) {
        function fail(e) {
            env.error = env.hasError ? new SuppressedError(e, env.error, "An error was suppressed during disposal.") : e;
            env.hasError = true;
        }
        var r, s = 0;
        function next() {
            while (r = env.stack.pop()) {
                try {
                    if (!r.async && s === 1) return s = 0, env.stack.push(r), Promise.resolve().then(next);
                    if (r.dispose) {
                        var result = r.dispose.call(r.value);
                        if (r.async) return s |= 2, Promise.resolve(result).then(next, function(e) { fail(e); return next(); });
                    }
                    else s |= 1;
                }
                catch (e) {
                    fail(e);
                }
            }
            if (s === 1) return env.hasError ? Promise.reject(env.error) : Promise.resolve();
            if (env.hasError) throw env.error;
        }
        return next();
    };
})(typeof SuppressedError === "function" ? SuppressedError : function (error, suppressed, message) {
    var e = new Error(message);
    return e.name = "SuppressedError", e.error = error, e.suppressed = suppressed, e;
});
export { _default as default };
var a, _default;
const env_1 = { stack: [], error: void 0, hasError: false };
try {
    a = __addDisposableResource(env_1, {}, false);
    _default = {};
}
catch (e_1) {
    env_1.error = e_1;
    env_1.hasError = true;
}
finally {
    __disposeResources(env_1);
}
```

**Comment by Jarred-Sumner** [comment] 2024-09-23 22:43
Duplicate of https://github.com/oven-sh/bun/issues/13734

**Comment by Jarred-Sumner** [comment] 2024-09-23 22:44
Please follow along in https://github.com/oven-sh/bun/issues/13734

**Closed as not planned by Jarred-Sumner** 2024-09-23 22:44 UTC
Labels: bug, needs triage
