### ISSUE TITLE
 Bun v1.1.20 (ae194892)  crashed

### ISSUE THREAD

**Issue by dennicLiu** [oven-sh/bun#12637] opened 2024-07-18 02:24 UTC
### Relevant log output

```shell
828.0 
828.0     [182.63ms]
828.0 Downloaded d3-color versions
828.0 [PackageManager] waiting for 130 tasks
828.0    - "d3-color": "^3.1.0" - d3-color@3.1.0
828.2 < 200 OK
828.2 < Date: Thu, 18 Jul 2024 02:20:19 GMT
828.2 < Content-Type: application/vnd.npm.install-v1+json
828.2 < Transfer-Encoding: chunked
828.2 < Connection: keep-alive
828.2 < CF-Ray: 8a4efdedcd4667b3-SJC
828.2 < CF-Cache-Status: HIT
828.2 < Access-Control-Allow-Origin: *
828.2 < Age: 165
828.2 < Cache-Control: public, max-age=300
828.2 < ETag: W/"d7f20e25726e897b0f61f95fb3c8c3b9"
828.2 < Last-Modified: Fri, 15 Mar 2024 11:56:30 GMT
828.2 < Vary: accept-encoding, accept
828.2 < Server: cloudflare
828.2 < Content-Encoding: br
828.2 
828.2 ============================================================
828.2 Bun v1.1.20 (ae194892) Linux x64
828.2 Linux Kernel v5.15.0 | glibc v2.36
828.2 CPU: sse42 popcnt avx avx2 avx512
828.2 Args: "bun" "install" "--verbose"
828.2 Features: extracted_packages(7) 
828.2 Elapsed: 827902ms | User: 242ms | Sys: 196ms
828.2 RSS: 0.69GB | Peak: 90.67MB | Commit: 0.69GB | Faults: 255
828.2 
828.2 panic: Segmentation fault at address 0x0
828.2 oh no: Bun has crashed. This indicates a bug in Bun, not your code.
828.2 
828.2 To send a redacted crash report to Bun's team,
828.2 please file a GitHub issue using the link below:
828.2 
828.2  https://bun.report/1.1.20/li1ae19489AggB+kgP8/+zvD6//6uDg8m0tDi0mr/Di27q/DsiuzvDghk0rDmzoiBA2AA
828.2 
828.6 Illegal instruction (core dumped)
------
Dockerfile:12
--------------------
  10 |     #COPY bun.lockb ./
  11 |     
  12 | >>> RUN bun install --verbose
  13 |     
  14 |     COPY . .
--------------------
ERROR: failed to solve: process "/bin/sh -c bun install --verbose" did not complete successfully: exit code: 132
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on linux x86_64 [InstallCommand]

Segmentation fault at address 0x00000000

- `??`
- [`mem.zig:4126`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/zig/lib/std/mem.zig#L4126>): `src.http.handleResponseMetadata`
- [`hive_array.zig:45`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/hive_array.zig#L45>): `src.http.NewHTTPContext`
- [`main.zig:64`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/main.zig#L64>): `src.deps.uws.NewSocketHandler`
- [`openssl.c:1107`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/crypto/openssl.c#L1107>): `create_ssl_context_from_bun_options`
- [`epoll_kqueue.c:380`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/eventing/epoll_kqueue.c#L380>): `us_loop_run_bun_tick`
- [`array_hash_map.zig:2022`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/zig/lib/std/array_hash_map.zig#L2022>): `src.http.HTTPThread.processEvents`
- [`string_immutable.zig:885`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/string_immutable.zig#L885>): `src.http.NewHTTPContext`
- `??`

**Comment by dennicLiu** [comment] 2024-07-18 02:53
861.4  README.md
861.4  eslint-plugin-prettier.d.ts
861.4  recommended.d.ts
861.4 [eslint-plugin-prettier] Extracted
861.4 [PackageManager] waiting for 59 tasks
861.4 ============================================================
861.4 Bun v1.1.20 (ae194892) Linux x64
861.4 Linux Kernel v5.15.0 | glibc v2.36
861.4 CPU: sse42 popcnt avx avx2 avx512
861.4 Args: "bun" "install" "--verbose"
861.4 Features: extracted_packages(3) 
861.4 Elapsed: 861053ms | User: 150ms | Sys: 86ms
861.4 RSS: 0.93GB | Peak: 29.88MB | Commit: 0.93GB | Faults: 155
861.4 
861.4 panic: Floating point error at address 0x55C513D73BA3
861.4 oh no: Bun has crashed. This indicates a bug in Bun, not your code.
861.4 
861.4 To send a redacted crash report to Bun's team,
861.4 please file a GitHub issue using the link below:
861.4 
861.4  https://bun.report/1.1.20/li1ae19489AggB+kgPw3u0vDg8m0tDi0mr/Di27q/DsiuzvDghk0rDmzoiBA5q8qBm6986T
861.4 
861.6 Illegal instruction (core dumped)
------

**Comment by Jarred-Sumner** [comment] 2024-07-18 04:05
Duplicate of https://github.com/oven-sh/bun/issues/12591

**Closed as not planned by Jarred-Sumner** 2024-07-18 04:05 UTC
Labels: bun install
