### ISSUE TITLE
panic(main thread): index out of bounds oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### ISSUE THREAD

**Issue by hiraaziz** [oven-sh/bun#11270] opened 2024-05-22 14:04 UTC
### Relevant log output

```shell
panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.9/wi1bb13798AgihQkxwwH6/1wHuy7sE0tj4Hw6lpE063nE82xzFqg4BiiJouzs+CA0eNrLzEtJrVDILy1RyE9TSMovzUspBgBHeAcx
```

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:4263`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/install/install.zig#L4263>): `enqueueDependencyWithMain`
- [`install.zig:5103`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/install/install.zig#L5103>): `processDependencyList`
- [`install.zig:5823`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/install/install.zig#L5823>): `runTasks`
- [`install.zig:10362`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/install/install.zig#L10362>): `isDone`
- [`event_loop.zig:1904`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/bun.js/event_loop.zig#L1904>): `tick`
- [`filter_run.zig:428`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/cli/filter_run.zig#L428>): `install`
- [`cli.zig:1452`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/cli.zig#L1452>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/src/startup/exe_common.inl#L78>): `invoke_main`

**Comment by skylee03** [comment] 2024-06-11 16:55
Is this issue also a duplicate of #10565?

**Closed as completed** 2024-06-11 16:57 UTC
Labels: needs repro, crash, bun install
