### ISSUE TITLE
Add a support for windows distribution

### ISSUE THREAD

**Issue by itsmeadarsh2008** [oven-sh/bun#486] opened 2022-07-09 10:21 UTC
I know bun is _extremely fast_ than any other **JavaScript** Runtime but we need the windows os support because most developers are compatible with the windows operating system.

Therefore, I request you to kindly look at the 🪟 windows distribution.

**Comment by FinnRG** [comment] 2022-07-09 10:22
Duplicate of #43

**Closed as completed by FinnRG** 2022-07-09 10:22 UTC
