### ISSUE TITLE
Error on creating a Elysia app

### ISSUE THREAD

**Issue by engboustani** [oven-sh/bun#11220] opened 2024-05-21 11:04 UTC
### How can we reproduce the crash?

it's happend when i want to create a new elysia app with bun create command

### Relevant log output

```shell
Fetching package.json... ============================================================
Bun v1.1.8 (89d25807) Windows x64
Args: "C:\Users\Develop22\.bun\bin\bun.exe", "create", "elysia"
Elapsed: 1208ms | User: 0ms | Sys: 0ms
RSS: 42.45MB | Peak: 42.45MB | Commit: 91.27MB | Faults: 10555

panic(thread 39112): reached unreachable code
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on windows x86_64 [CreateCommand]

**panic**: reached unreachable code

- [`Progress.zig:251`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/Progress.zig#L251): `clearWithHeldLock`
- [`Mutex.zig:131`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/zig/lib/std/Thread/Mutex.zig#L131): `unlock`
- [`http.zig:1421`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/http.zig#L1421): `getBodyBuffer`
- [`http.zig:2787`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/http.zig#L2787): `onData`
- [`uws.zig:736`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/deps/uws.zig#L736): `on_data`
- `??`
- `??`
- `uv__process_poll_req`
- `??`
- `uv_run`

**Comment by Jarred-Sumner** [comment] 2024-06-06 13:31
Duplicate of https://github.com/oven-sh/bun/issues/11649

**Comment by Jarred-Sumner** [comment] 2024-06-06 13:31
Tracking this in #11649. Please follow along there.

**Closed as not planned by Jarred-Sumner** 2024-06-06 13:31 UTC
Labels: crash
