### ISSUE TITLE
Bun does not read env properly

### ISSUE THREAD

**Issue by brudyr** [oven-sh/bun#5310] opened 2023-09-13 20:56 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

In a new project with `bun init`:
- create .env file with:
`MYENVVAR='test$Crest'`
- change index.ts to:
`console.log(process.env.MYEVNVAR`
- run "bun index.ts"

### What is the expected behavior?

That the console logs `test$Crest`

### What do you see instead?

The console logs `test`

### Additional information

I encountered this problem with a more complex Bearer Token but could narrow it down to `$C` as the cause of the problem and could reproduce it with the given example

**Comment by sirenkovladd** [comment] 2023-09-13 20:59
Duplicate of https://github.com/oven-sh/bun/issues/4994

**Closed as not planned** 2023-09-13 21:01 UTC
Labels: bug
