### ISSUE TITLE
Error  undefined is not a constructor (evaluating 'new console_1.Console(process.stderr)')

### ISSUE THREAD

**Issue by alfianlensun** [oven-sh/bun#4898] opened 2023-09-11 07:30 UTC
### What version of Bun is running?

1.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

- using docker images oven/bun with nestjs when bun run build show "Error  undefined is not a constructor (evaluating 'new console_1.Console(process.stderr)')"

**Comment by alfianlensun** [comment] 2023-09-11 07:32
bun run build success run in local machine but error on docker

**Comment by craigotis** [comment] 2023-09-12 01:35
Seeing the same thing on a pretty barebones NestJS project running in GitLab CI. I believe this is likely a duplicate of https://github.com/oven-sh/bun/issues/3625

Logs include:
```
$ nest build
[0.01ms] ".env"
 6 | (function (LogLevel) {
 7 |     LogLevel[LogLevel["INFO"] = 1] = "INFO";
 8 |     LogLevel[LogLevel["WARN"] = 2] = "WARN";
 9 |     LogLevel[LogLevel["ERROR"] = 3] = "ERROR";
10 | })(LogLevel || (LogLevel = {}));
11 | var stderrConsole = new console_1.Console(process.stderr);
                        ^
TypeError: undefined is not a constructor (evaluating 'new console_1.Console(process.stderr)')
      at /builds/backend/node_modules/tsconfig-paths-webpack-plugin/lib/logger.js:11:20
      at globalThis (/builds/backend/node_modules/tsconfig-paths-webpack-plugin/lib/logger.js:52:21)
      at require (:1:20)
      at /builds/backend/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:19:4
      at globalThis (/builds/backend/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:80:30)
      at require (:1:20)
      at /builds/backend/node_modules/tsconfig-paths-webpack-plugin/lib/index.js:4:4
      at globalThis (/builds/backend/node_modules/tsconfig-paths-webpack-plugin/lib/index.js:15:17)
      at require (:1:20)
      at /builds/backend/node_modules/@nestjs/cli/lib/compiler/defaults/webpack-defaults.js:6:6
      at globalThis (/builds/backend/node_modules/@nestjs/cli/lib/compiler/defaults/webpack-defaults.js:95:33)
      at require (:1:20)
      at /builds/backend/node_modules/@nestjs/cli/lib/compiler/webpack-compiler.js:7:6
      at globalThis (/builds/backend/node_modules/@nestjs/cli/lib/compiler/webpack-compiler.js:92:26)
      at require (:1:20)
      at /builds/backend/node_modules/@nestjs/cli/actions/build.action.js:22:6
      at globalThis (/builds/backend/node_modules/@nestjs/cli/actions/build.action.js:108:22)
      at require (:1:20)
      at /builds/backend/node_modules/@nestjs/cli/actions/index.js:18:0
      at globalThis (/builds/backend/node_modules/@nestjs/cli/actions/index.js:23:45)
      at require (:1:20)
      at /builds/backend/node_modules/@nestjs/cli/commands/command.loader.js:14:6
      at globalThis (/builds/backend/node_modules/@nestjs/cli/commands/command.loader.js:42:24)
      at require (:1:20)
      at /builds/backend/node_modules/@nestjs/cli/commands/index.js:17:0
      at globalThis (/builds/backend/node_modules/@nestjs/cli/commands/index.js:18:48)
      at require (:1:20)
      at /builds/backend/node_modules/@nestjs/cli/bin/nest.js:14:6
      at globalThis (/builds/backend/node_modules/@nestjs/cli/bin/nest.js:34:10)
```

**Comment by rvbuelow** [comment] 2023-09-12 08:18
Seems to be this issue https://github.com/oven-sh/bun/issues/3625

**Closed as completed** 2023-09-18 23:29 UTC
Labels: bug

**Comment by anhlvt96** [comment] 2023-09-20 09:13
I had the same issue. How to fix it?
