### ISSUE TITLE
Cannot load DLL for leveldown

### ISSUE THREAD

**Issue by sensiblearts** [oven-sh/bun#11781] opened 2024-06-11 10:41 UTC
### How can we reproduce the crash?

Create a Bun project on WIndows 10, and in `index.ts`

```
import PouchDB from 'pouchdb';

let pdb = PouchDB();
```

Then `bun add pouchdb` and  `bun run ./index.ts`.

### Relevant log output

```shell
15 | var uv = (process.versions.uv || '').split('.')[0]
16 |
17 | module.exports = load
18 |
19 | function load (dir) {
20 |   return runtimeRequire(load.path(dir))
              ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at load (C:\Users\david\experiment\pdb-bun\node_modules\node-gyp-build\index.js:20:10)
      at C:\Users\david\experiment\pdb-bun\node_modules\leveldown\binding.js:1:8
      at C:\Users\david\experiment\pdb-bun\node_modules\leveldown\leveldown.js:3:7
      at C:\Users\david\experiment\pdb-bun\node_modules\level\level.js:1:8
      at C:\Users\david\experiment\pdb-bun\node_modules\pouchdb\lib\index.js:21:13

Bun v1.1.12 (Windows x64)
============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\david\.bun\bin\bun.exe" "run" "./index.ts"
Features: jsc dotenv transpiler_cache(2) tsconfig(9)
Builtins: "abort-controller" "bun:main" "detect-libc" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:net" "node:os" "node:path" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:punycode" "node-fetch"
Elapsed: 774ms | User: 421ms | Sys: 203ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 0.18GB | Faults: 39775

panic(main thread): Segmentation fault at address 0x7FFE922B8384
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x7FFE88D08384

- ??? at `0x28384` in sharp-win32-x64.node

**Comment by Electroid** [comment] 2024-06-11 21:12
Duplicate of #4290

**Closed as not planned by Electroid** 2024-06-11 21:12 UTC
Labels: crash
