### ISSUE TITLE
Add `--peer` flag to `bun add`

### ISSUE THREAD

**Issue by Didas-git** [oven-sh/bun#9962] opened 2024-04-05 01:24 UTC
### What is the problem this feature would solve?

Currently there is no way to add peer dependencies using bun.

### What is the feature you are proposing to solve the problem?

Add a `--peer` flag just like we have `--dev` and `--optional`

**Comment by jack-weilage** [comment] 2024-04-05 20:12
Is this a duplicate of https://github.com/oven-sh/bun/issues/1820?

**Closed as completed** 2024-04-05 22:12 UTC
Labels: enhancement
