### ISSUE TITLE
Bun build | define | contains invalid identifier

### ISSUE THREAD

**Issue by danielbarion** [oven-sh/bun#15493] opened 2024-11-29 13:34 UTC
### What version of Bun is running?

1.1.38+bf2f153f5

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

try to build some file with the following config:

```ts
...
define: {
  '${process.env.APP_ASSETS_URL}': JSON.stringify(""),
}
...
```

When this specific replace is removed, I'm able to build the project.

### What is the expected behavior?

Be able to replace the string successfully.

### What do you see instead?

The build breaks.

![Image](https://github.com/user-attachments/assets/da35045e-b3ae-4f56-a45a-cc616cd20a5e)

### Additional information

![Image](https://github.com/user-attachments/assets/e3c9008a-cb50-4549-8a13-dba9d0bc9a2e)

I have the following Rollup build config file:

```ts
/* eslint-disable no-template-curly-in-string */
import { aliasConfig, outputConfig } from './config/rollup'
import { string } from 'rollup-plugin-string'
import { terser } from 'rollup-plugin-terser'
import { version } from './package.json'
import alias from '@rollup/plugin-alias'
import babel from '@rollup/plugin-babel'
import commonjs from '@rollup/plugin-commonjs'
import copy from 'rollup-plugin-copy'
import dotenv from 'dotenv'
import json from '@rollup/plugin-json'
import nodePolyfills from 'rollup-plugin-node-polyfills'
import nodeResolve from '@rollup/plugin-node-resolve'
import postcss from 'rollup-plugin-postcss'
import progress from 'rollup-plugin-progress'
import replace from '@rollup/plugin-replace'
import ts from '@rollup/plugin-typescript'
import typescript from 'typescript'
import fs from 'fs'
import updateHtmlBundle from './plugins/update-html-bundle'
import generateServiceWorker from './plugins/generate-service-worker'
import {
  isGitInstalled,
  isGitRepository,
  getCommitCount,
  swInstallTemplate,
  swUninstallTemplate,
} from './utils'

const SW_ENABLED = false

if (!isGitInstalled()) {
  console.error('Git is not installed on the system.')
  process.exit(1)
}

if (!isGitRepository()) {
  console.error('The current directory is not a Git repository.')
  process.exit(1)
}

const commitCount = getCommitCount()

const buildVersion = `${version}.${commitCount}`

console.log(`Build Version: ${buildVersion}`)

dotenv.config({
  path: '.env.production',
})

const loader = fs.readFileSync('./build/loader.js', 'utf8')

export default [
  {
    input: ['src/index.ts'],
    output: { ...outputConfig.esm.outputConfig },
    plugins: [
      nodePolyfills(),
      progress(),
      alias({
        resolve: ['.styl', '.css', '.svg', '/index.js'],
        entries: aliasConfig,
      }),
      string({ include: '**/*.html' }),
      ts({
        typescript,
      }),
      json(),
      postcss({
        include: '**/*.css',
        extensions: ['.css', '.sss', '.stylus', '.styl', '.pcss', '.scss'],
      }),
      nodeResolve(),
      babel({
        babelHelpers: 'bundled',
      }),
      commonjs(),
      copy({
        targets: [
          { src: 'assets', dest: 'build/' },
          { src: 'public/manifest.json', dest: 'build/' },
          { src: 'public/offline.html', dest: 'build/' },
          { src: 'public/html.html', dest: 'build/' },
          {
            src: 'src/maps/**/*',
            dest: 'build/assets/maps',
            transform: (contents, filename) => {
              if (filename.endsWith('.json')) {
                return JSON.stringify(JSON.parse(contents))
              }
              return contents
            },
          },
        ],
        verbose: false,
      }),
      updateHtmlBundle({
        canvasLoader: loader,
        assetsUrl: process.env.APP_ASSETS_URL,
        serviceWorker: SW_ENABLED ? swInstallTemplate : swUninstallTemplate,
      }),
      replace({
        // https://github.com/rollup/plugins/tree/master/packages/replace#preventassignment
        preventAssignment: true,
        values: {
          'process.env.NODE_ENV': JSON.stringify('production'),
          'process.env.APP_ASSETS_URL': JSON.stringify(process.env.APP_ASSETS_URL),
          '${process.env.APP_ASSETS_URL}': JSON.stringify(process.env.APP_ASSETS_URL),
          'process.env.GAME_VERSION': JSON.stringify(buildVersion),
          'process.env.SW_ENABLED': JSON.stringify(SW_ENABLED),
          'process.env.SW_CACHE_NAME': JSON.stringify(`game-${buildVersion}`),
        },
      }),
      terser(),
      SW_ENABLED &&
        generateServiceWorker({
          cacheId: `game-${buildVersion}-pre-cache`, // pre-cache cache name
          // next 2 lines commented to disable pre-cache
          // globDirectory: './build/',
          // globPatterns: ['**/*.{webp,css,ttf,png,js,jpeg,json,html}'],
          globIgnores: ['**/assets/maps/**'], // Exclude files with URL containing "/assets/maps/" from the pre-cache list
          swDest: './build/sw.js',
          ignoreURLParametersMatching: [/^utm_/, /^fbclid$/],
          skipWaiting: true, // Force the new SW to become active immediately
          clientsClaim: true, // Force the new SW to take control of all pages immediately
          runtimeCaching: [
            {
              // Exclude files with URL containing "/assets/maps/"
              urlPattern: /\/assets\/maps\//,
              handler: 'NetworkOnly', // Exclude from cache
            },
            {
              urlPattern: /\.(webp|css|ttf|png|js|jpeg|json|html)$/,
              handler: 'CacheFirst',
              options: {
                cacheName: `game-${buildVersion}`, // runtime cache name
              },
            },
          ],
        }),
    ],
    onwarn: (warning, warn) => {
      // ignore circular dependency warning
      if (warning.code === 'CIRCULAR_DEPENDENCY') return

      // show others
      warn(warning)
    },
  },
]
```

And I'm trying to test Bun to build the project to replace rollup, at least in development mode, here's my current Bun build config (`build.js`) file:

```ts
import { version } from './package.json'
import { isGitInstalled, isGitRepository, getCommitCount } from './utils'

const SW_ENABLED = false

if (!isGitInstalled()) {
  console.error('Git is not installed on the system.')
  process.exit(1)
}

if (!isGitRepository()) {
  console.error('The current directory is not a Git repository.')
  process.exit(1)
}

const commitCount = getCommitCount()

const buildVersion = `${version}.${commitCount}`

const result = await Bun.build({
  entrypoints: ['./src/index.ts'],
  outdir: './build',
  splitting: true,
  format: 'esm', // default
  naming: '[dir]/[name].[ext]', // default
  sourcemap: 'linked', // default 'none'
  minify: false, // default false
  experimentalCss: true,
  define: {
    'process.env.NODE_ENV': JSON.stringify('production'),
    'process.env.APP_ASSETS_URL': JSON.stringify(process.env.APP_ASSETS_URL),
    '${process.env.APP_ASSETS_URL}': JSON.stringify(process.env.APP_ASSETS_URL),
    'process.env.GAME_VERSION': JSON.stringify(buildVersion),
    'process.env.SW_ENABLED': JSON.stringify(SW_ENABLED),
    'process.env.SW_CACHE_NAME': JSON.stringify(`game-${buildVersion}`),
  },
  drop: ['console.log', 'console.info', 'console.debug', 'console.warn'],
})

if (!result.success) {
  console.error('Build failed')
  for (const message of result.logs) {
    // Bun will pretty print the message object
    console.error(message)
  }
}
```

I'm trying to replicate the replace plugin behavior from rollup:

```ts
      replace({
        // https://github.com/rollup/plugins/tree/master/packages/replace#preventassignment
        preventAssignment: true,
        values: {
          'process.env.NODE_ENV': JSON.stringify('production'),
          'process.env.APP_ASSETS_URL': JSON.stringify(process.env.APP_ASSETS_URL),
          '${process.env.APP_ASSETS_URL}': JSON.stringify(process.env.APP_ASSETS_URL),
          'process.env.GAME_VERSION': JSON.stringify(buildVersion),
          'process.env.SW_ENABLED': JSON.stringify(SW_ENABLED),
          'process.env.SW_CACHE_NAME': JSON.stringify(`game-${buildVersion}`),
        },
      }),
```

It would be nice not need refactor the project to test Bun, that's why I'm trying to replicate the bundle configuration.

**Comment by RiskyMH** [comment] 2024-12-02 16:57
@danielbarion You should be able define `process.env.APP_ASSETS_URL` without needing the `${}` around it.

If you add `--minify-syntax` or `--minify` then it will inline the value into the template string also.

**Comment by danielbarion** [comment] 2024-12-02 18:46
yeap @RiskyMH, I was able to build the project since I realized it will still be a template string, the live project: https://pixi-js-game.netlify.app/

I still have the rollup build config (not in use anymore), but I'm now using bun+tsc (bun to build and TSC to check the types) to develop and to build to production.

But I left the issue open because it looks like a bug in the "replace" option, right? 

### A few metrics

Average Rollup build time:
```
created build in 11.9s
✨  Done in 16.39s.
```

Average Bun+tsc build time:
```
Build Time: 185 ms  |  0.185 s
```

It's 88x faster with Bun on my local (same speed improvement with Bun simulating live reload during development).

Rollup on Netlify:
```
(build.command completed in 19s)
```

Bun+tsc on Netlify:
```
(build.command completed in 2.1s)
```

It's building 9x faster on Netlify.

**Comment by paperdave** [comment] 2024-12-03 04:42
this is not a bug, since `define` only replaces global variables and property accesses on them. `${...}` isn't a valid variable name. note that bun already replaces these in the template string, so its enough to specify just:
```
    'process.env.APP_ASSETS_URL': JSON.stringify(process.env.APP_ASSETS_URL),
```
as you already have done.

while testing this out myself i am noticing that the string isn't being merged into the template string, even with `--minify`. that is a bug.

**Comment by paperdave** [comment] 2024-12-03 04:47
nevermind, i had confused myself passing --minify-syntax as cli arguments instead of adding `minify: true` to your script. there are no bugs with this in the bundler.

to enable constant folding, use

```diff
  minify: true,
```
or
```
  minify: { syntax: true },
```

**Closed as not planned by paperdave** 2024-12-03 04:47 UTC
Labels: bug, bundler
