### ISSUE TITLE
`bun repl` crashes Bun

### ISSUE THREAD

**Issue by tutinoko2048** [oven-sh/bun#12996] opened 2024-08-01 07:30 UTC
### How can we reproduce the crash?

- Type `bun repl` and it starts resolving dependencies
- Crashed when it has completed installing(probably)

### Relevant log output
```
Bun v1.1.21 (70ca2b76) Linux x64 (baseline)
Linux Kernel v5.15.0 | glibc v2.35
Args: "node" "postinstall.js"
Features: jsc no_avx no_avx2 
Builtins: "bun:main" "node:assert" "node:child_process" "node:fs" "node:path" "node:string_decoder" "node:util/types" 
Elapsed: 19748ms | User: 17223ms | Sys: 2527ms
RSS: 13.83GB | Peak: 7.97GB | Commit: 13.83GB | Faults: 0

panic(main thread): Segmentation fault at address 0x3C49A000000
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.21/Bn170ca2b7AiggggwBuos3iE+xyQunq+jDus78+Cyj6vjDwgkn4D__6lmq1D6lmq1DA2o8BhggggmD


error: postinstall script from "@swc/core" terminated by SIGILL (Illegal instruction)
Illegal instruction (core dumped)
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on linux x86_64_baseline [RunAsNodeCommand]

Segmentation fault at address 0x3C49A000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`encoding.zig:905`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/webcore/encoding.zig#L905>): `src.string.SliceWithUnderlyingString.transcodeFromOwnedSlice`
- [`node_fs.zig:5492`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/node/node_fs.zig#L5492>): `src.bun.js.node.node_fs.NodeFS.readFile__anon_95439`
- [`node_fs_binding.zig:64`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/node/node_fs_binding.zig#L64>): `NodeJSFSPrototype__readFileSync`
- [`ZigGeneratedClasses.cpp:26010`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b//build/bun/build/codegen/ZigGeneratedClasses.cpp#L26010>): `WebCore::NodeJSFSPrototype__readFileSyncCallback`
- *2 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/ld-temp.o#L0>): `llint_op_call`

**Comment by Jarred-Sumner** [comment] 2024-08-01 07:44
> RSS: 13.83GB | Peak: 7.97GB | Commit: 13.83GB | Faults: 0

13 GB is a lot of memory. 

> no_avx no_avx2 

What year is your CPU from?

**Comment by tutinoko2048** [comment] 2024-08-01 10:59
I don't have detailed CPU information because we are running in a virtualized environment.

**Comment by Electroid** [comment] 2024-08-01 16:10
> I don't have detailed CPU information because we are running in a virtualized environment.

What virtual environment / cloud platform are you running on?

**Comment by tutinoko2048** [comment] 2024-08-01 16:21
I'm using the server which hosted by my friend.
Also according to `require('os').cpus()`, it says `Common KVM processor`.

**Comment by Jarred-Sumner** [comment] 2024-08-05 06:01
Duplicate of #3312

**Closed as not planned by Jarred-Sumner** 2024-08-05 06:01 UTC
Labels: crash, linux
