### ISSUE TITLE
Support Expo/Metro bundler

### ISSUE THREAD

**Issue by itsyoboieltr** [oven-sh/bun#8596] opened 2024-01-31 19:41 UTC
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

1. initialize an expo app:

feel free to use my stack for this
```sh
bun create itsyoboieltr/bender-stack
```
or the expo cli
```sh
bunx create-expo-app
```

2. run the dev server using bun:
```sh
bun --bun dev
```

### What is the expected behavior?

Metro bundler starts, dev server starts, so I can develop using Bun.

### What do you see instead?

```sh
583 |     if (aNeedle[aLineName] <= 0) {
584 |       throw new TypeError('Line must be greater than or equal to 1, got '
585 |                           + aNeedle[aLineName]);
586 |     }
587 |     if (aNeedle[aColumnName] < 0) {
588 |       throw new TypeError('Column must be greater than or equal to 0, got '
                  ^
TypeError: Column must be greater than or equal to 0, got -1
      at SourceMapConsumer_findMapping (node_modules/source-map-support/node_modules/source-map/lib/source-map-consumer.js:588:13)
      at SourceMapConsumer_originalPositionFor (node_modules/source-map-support/node_modules/source-map/lib/source-map-consumer.js:653:17)
      at mapSourcePosition (node_modules/source-map-support/source-map-support.js:244:28)
      at wrapCallSite (node_modules/source-map-support/source-map-support.js:397:20)
      at prepareStackTrace (node_modules/source-map-support/source-map-support.js:446:39)
      at logCmdError (node_modules/@expo/cli/build/src/utils/errors.js:59:26)
error: script "dev" exited with code 1
```

**Comment by nvsd** [comment] 2024-02-01 01:06
@itsyoboieltr 
~~I got this, and oddly enough, it was after I wiped my computer, so I didn't have node installed. I installed node, and it worked.~~

~~Please check if you have node and that it's updated, and then try again.~~

edit: Am wrong

**Comment by itsyoboieltr** [comment] 2024-02-01 01:08
If I run it with node, it works. I want to run it with Bun only. Node should not be required in any way.

**Comment by nvsd** [comment] 2024-02-01 01:20
~~No, I get you. I'm just saying that I wiped my computer, installed bun without node, got the error you did, installed node, ran it with bun and then didn't get the error.~~

~~I'm not saying run it with node; I'm asking if node is installed and if that will fix your issue like mine.~~

~~I agree it **shouldn't** be needed but in my case having it installed did seem to fix the issue.~~

edit: Am wrong

**Comment by itsyoboieltr** [comment] 2024-02-01 01:21
But did you run it with --bun after? Btw, I do have the latest node installed.
Maybe it worked for you because bun defaults to node :) unless you specify --bun

**Comment by nvsd** [comment] 2024-02-01 16:52
Oh interesting, yeah, i'm wrong. I had no idea. So when I didn't have node it was probably defaulting to `--bun` which was causing the bug. So if I'm now understanding the whole thing [the only benefit from running expo with bun](https://docs.expo.dev/guides/using-bun/) is package installation speed? lol.

**Comment by Electroid** [comment] 2024-02-01 17:33
Duplicate of #2375

**Closed as not planned by Electroid** 2024-02-01 17:33 UTC
Labels: bug
