### ISSUE TITLE
key defined via `--define` flag is not recognized in `process.env`

### ISSUE THREAD

**Issue by Saeid-Za** [oven-sh/bun#10167] opened 2024-04-11 10:54 UTC
### What version of Bun is running?

1.1.3

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. Create a `test.ts` file, containing:

```ts
const keys = Object.keys(process.env)

console.log("Is `custom` in process.env ?", keys.includes("custom"))
console.log("Could `custom` be accessed directly ?", !!process.env.custom)
```

2. Run the script file using `bun -d process.env.custom:'value' test.ts`

### What is the expected behavior?

Is `custom` in process.env ? true
Could `custom` be accessed ? true

### What do you see instead?

Is `custom` in process.env ? false
Could `custom` be accessed ? true

### Additional information

related [issue](https://github.com/oven-sh/bun/issues/10165).

**Comment by Electroid** [comment] 2024-04-11 16:06
Duplicate of #10165

**Closed as not planned by Electroid** 2024-04-11 16:06 UTC
Labels: bug

**Comment by Saeid-Za** [comment] 2024-04-11 16:25
This was in fact an other issue, not sure if the underlying problem is the same, but the surface level reproduction is not the **same**.

This issue is about bun `process.env` and it's weird behavior.
1. Unlike #10165  We do not import `process` from `node:process`, this is infact the bun's global.
2. in #10165 we could not use `process.env.somevar` as it's undefined, even though injected, in this issue, we could use `somevar` but not in a conventional way.

I was afraid that the title would seem duplicate of previous one and be flagged duplicate.
Please do try the reproduction and compare them if I couldn't explain properly.

**Comment by Electroid** [comment] 2024-04-11 16:43
The underlying issues are the same, we will fix all these scenarios.
