### ISSUE TITLE
Shell masks user input after `ctrl + c`ing out of Vite dev server

### ISSUE THREAD

**Issue by andriygm** [oven-sh/bun#7012] opened 2023-11-09 18:19 UTC
### What version of Bun is running?

1.0.11+f7f6233ea

### What platform is your computer?

Linux 5.15.0-1043-aws x86_64 x86_64

### What steps can reproduce the bug?

Create a project with Vite version 4.5.0 and install packages using Bun

### What is the expected behavior?

After ctrl + c, shell returns to usable state

### What do you see instead?

After ctrl + c, shell returns but input is not visible

### Additional information

Running the same project with `npm run dev` instead of `bun run dev' produces correct behavior.

**Comment by Jarred-Sumner** [comment] 2023-11-15 08:51
Duplicate of #6929

**Closed as completed** 2023-11-15 16:04 UTC
Labels: bug, needs investigate
