### ISSUE TITLE
Bun repl doesn't recognize destructure-binding top-level `await`

### ISSUE THREAD

**Issue by guyutongxue** [oven-sh/bun#9826] opened 2024-04-02 05:16 UTC
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Linux 6.5.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

Enter `bun repl`, then input `let { } = await 0`.

### What is the expected behavior?

With `node`:

```
Welcome to Node.js v20.12.0.
Type ".help" for more information.
> let { } = await 0;
undefined
```

### What do you see instead?

Bun cannot recognize the syntax :confused: 
```
Welcome to Bun v1.1.0
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> let { } = await 0;
SyntaxError: Unexpected keyword 'let'

```

**Comment by RiskyMH** [comment] 2024-11-20 10:12
Duplicate of #10422 for similar I mentioned in https://github.com/oven-sh/bun/issues/10422#issuecomment-2488134669
![Image](https://github.com/user-attachments/assets/bed938f0-1c0a-41fa-807d-f3bf5fb53ae7)

**Closed as not planned by RiskyMH** 2024-11-20 10:12 UTC
Labels: bug, repl
