### ISSUE TITLE
Bun Safe mode

### ISSUE THREAD

**Issue by bornjre** [oven-sh/bun#8210] opened 2024-01-16 18:58 UTC
### What is the problem this feature would solve?

i would i like to run script like u would inside `nsjail`  which allows to just scope paths to specific folder and restricting other resources. But i want to do it with JS script in cross-platform way.

https://github.com/google/nsjail

### What is the feature you are proposing to solve the problem?

a flags to disable filesystem access to specific folder  (other resources ?) and which would also disable other features that are not safe like spawning threads etc so it cannot be bypassed.

### What alternatives have you considered?

Nothing. If bun supported it would be really helpful but don't know if it's in scope of bun. Currently, there is no cross-platform way to run sth from semi-trusted source (without running Linux in a micro vm)

**Comment by Electroid** [comment] 2024-01-16 23:03
Duplicate of #6617

**Comment by Electroid** [comment] 2024-01-16 23:04
This is something that has been asked for before. It’s not a priority right now, but is something we could theoretically do in the future.

**Closed as not planned by Electroid** 2024-01-16 23:03 UTC
Labels: enhancement
