### ISSUE TITLE
Bun v1.0.30 reintroduced a bug that causes a signal error to crash the server

### ISSUE THREAD

**Issue by alexkahndev** [oven-sh/bun#9258] opened 2024-03-05 07:35 UTC
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Have a server which builds the source code using Bun and then uses Elysia to server side render the React components. 

```
/// server.ts
import { Elysia, t } from "elysia";
import { staticPlugin } from "@elysiajs/static";
import { renderToReadableStream } from "react-dom/server";
import { swagger } from "@elysiajs/swagger";
import { createElement } from "react";
import Home from "./pages/Home";
import About from "./pages/About";
import Help from "./pages/Help";

await Bun.build({
  entrypoints: [
    "./src/indexes/HomeIndex.tsx",
    "./src/indexes/AboutIndex.tsx",
    "./src/indexes/HelpIndex.tsx"
  ],
  outdir: "./build",
  minify: true,
});

const doYouLikeSwaggerUIBetter = false;

async function handleRequest(
  pageComponent: React.ComponentType,
  index: string,
) {
  const page = createElement(pageComponent);
  const stream = await renderToReadableStream(page, {
    bootstrapScripts: [index],
  });

  return new Response(stream, {
    headers: { "Content-Type": "text/html" },
  });
}

export const server = new Elysia()
  .use(
    staticPlugin({
      assets: "./build",
      prefix: "",
    }),
  )
  .use(
    swagger({
      provider: doYouLikeSwaggerUIBetter ? "swagger-ui" : "scalar",
    }),
  )
  .get("/", () => handleRequest(Home, "/HomeIndex.js"))
  .get("/about", () => handleRequest(About, "/AboutIndex.js"))
  .get("/help", () => handleRequest(Help, "/HelpIndex.js"))

  .listen(3000, () => {
    console.log(`server started on http://${host}:${port}`);
  })
  .on("error", (error) => {
    console.error(`Server error: ${error.code}`);
  });
```

Each entrypoint in the build step corresponds to an index for each page. The index file is used to hydrate the component after the server has rendered it.

```
/// HomeIndex.tsx
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
import { hydrateRoot } from "react-dom/client";
import Home from "../pages/Home";

hydrateRoot(document, <Home />);
```

Each page component returns html tags wrapping the actual page content

```
/// Home.tsx

import { Navbar } from "../components/utils/Navbar";
import { Demo } from "../components/content/Demo";
import { Demo2 } from "../components/content/Demo2";
import { Banner } from "../components/content/Banner";
import { Footer } from "../components/utils/Footer";
import { Testimonials } from "../components/content/Testimonials";

const Home = () => {
  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <title>Awesome.Social</title>
        <meta name="description" content="Bun, Elysia & React" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/styles/Home.css" />
        <link rel="icon" href="/assets/favicon.ico" />
      </head>
      <body>
        <Navbar />
        <Demo />
        <Demo2 />
        <Banner />
        <Testimonials />
        <Footer />
      </body>
    </html>
  );
};

export default Home;
```

```bun run server.ts``` will cause a SIGSEGV error when you try to load the page

### What is the expected behavior?

The expected behavior is that ```bun run server.ts``` should start the server and going to the localhost triggers the "/" route which gets the home page html and then hydrates it with css and javascript once its been loaded. 

### What do you see instead?

The server starts on ```bun run server.ts``` but when you go to the localhost the server crashes due to a SIGSEGV error. Depending on how long the server was able to serve the request before it crashes different amounts of css are loaded onto the page often times with most of it missing. The localhost website is no longer usable and if you click any of the links it will try to navigate and fail since the server is not running. 

### Additional information

If you want to reproduce the code here is the package.json

```
{
  "name": "awesome-social",
  "version": "0.2.0",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "format": "prettier --write \"./**/*.{js,jsx,ts,tsx,css}\"",
    "dev": "bun run --watch src/server.ts",
    "db:generate": "drizzle-kit generate:pg --schema ./db/schema.ts --out=./db/migrations",
    "db:migrate": "bun run ./db/migrate.ts"
  },
  "dependencies": {
    "@auth0/auth0-react": "auth0/auth0-react",
    "@elysiajs/static": "^0.8.0",
    "@elysiajs/swagger": "^0.8.0",
    "@neondatabase/serverless": "^0.8.1",
    "drizzle-orm": "^0.29.4",
    "elysia": "^0.8.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-modal": "^3.16.1",
    "react-router-dom": "^6.22.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.21",
    "@types/react-dom": "^18.2.7",
    "bun-types": "^1.0.26",
    "drizzle-kit": "^0.20.14"
  },
  "module": "src/server.ts"
}
```

I will also include two screenshots one is the expected behavior the other is the current behavior. The screenshots also show that this issue was started in v1.0.23 and fixed in v1.0.29 then reintroduced by v1.0.30.
![bun-versions-not-working](https://github.com/oven-sh/bun/assets/140863288/e18621a7-6af8-4821-a92b-14bc2af901d7)
![bun-versions-working](https://github.com/oven-sh/bun/assets/140863288/33fd1945-dc2e-46c9-821f-675178e5c6da)

**Comment by alexkahndev** [comment] 2024-03-05 08:51
For testing purposes, I have set up a repository with the isolated issue.

https://github.com/alexkahndev/bun-server-bug

**Comment by Jarred-Sumner** [comment] 2024-08-04 06:51
I'm not able to reproduce this on Bun v1.1.22 on macOS arm64. I was able to reproduce sockets left hung open in Bun v1.0.30, but not a crash.

I believe this was fixed in these two PRs:
- https://github.com/oven-sh/bun/pull/12979 
- https://github.com/oven-sh/bun/pull/12978

**Closed as completed by Jarred-Sumner** 2024-08-04 06:51 UTC
Labels: bug
