### ISSUE TITLE
Bundler: Support for Named entrypoints

### ISSUE THREAD

**Issue by arkmech** [oven-sh/bun#4714] opened 2023-09-09 17:45 UTC
### What is the problem this feature would solve?

Inspiration from `tsup`, allow `entrypoints` key to take in an object to specify output name, the `key` and the `entrypoints` as `value`

```typescript
import { defineConfig, Options } from 'tsup';

export default defineConfig((options: Options) => ({
  entry: {
    'Button/index': 'src/components/atoms/Button/Button.tsx',
  },
  splitting: false,
  format: ['esm', 'cjs'],
  dts: true,
  minify: true,
  external: ['react'],
  ...options,
}));
```

### What is the feature you are proposing to solve the problem?

Desired

```typescript
await Bun.build({
  entrypoints: {
    'Button/index': 'src/components/atoms/Button/Button.tsx',
  },
  splitting: true,
  format: 'esm',
  dts: true,
  minify: true,
  external: ['react'],
  outdir: './dist',
});
```

### What alternatives have you considered?

None

**Comment by Electroid** [comment] 2023-10-27 22:14
Duplicate of https://github.com/oven-sh/bun/issues/3323

**Closed as not planned by Electroid** 2023-10-27 22:14 UTC
Labels: enhancement, bundler
