### ISSUE TITLE
WSL bun init failed 

### ISSUE THREAD

**Issue by Phascolarctos** [oven-sh/bun#7266] opened 2023-11-22 13:46 UTC
### What version of Bun is running?

1.0.13

### What platform is your computer?

5.15.133.1-microsoft-standard-WSL2
适用于 Linux 的 Windows 子系统分发:
Ubuntu-22.04 (默认) 
download from microsoft store

### What steps can reproduce the bug?

curl -fsSL https://bun.sh/install | bash
bun --version
mkdir bun-dev
bun init

### What is the expected behavior?
success build a sample project
_No response_

### What do you see instead?

$ bun init
bun init helps you get started with a minimal project and tries to guess sensible defaults. Press ^C anytime to quit

package name (bun-dev):
entry point (index.ts):

error: AccessDenied

----- bun meta -----
Bun v1.0.13 (f5bf67bd) Linux x64 #1 SMP Thu Oct 5 21:02:42 UTC 2023
Unknown:
Elapsed: 3355ms | User: 4ms | Sys: 0ms
RSS: 33.55MB | Peak: 18.01MB | Commit: 33.55MB | Faults: 35
----- bun meta -----

0   0x560a653bb7bb
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

**Comment by Electroid** [comment] 2023-11-22 17:26
Duplicate of #5723

**Closed as not planned by Electroid** 2023-11-22 17:26 UTC
Labels: bug
