### ISSUE TITLE
CPU Features fails with undefined symbol: node_module_register

### ISSUE THREAD

**Issue by NightPotato** [oven-sh/bun#10942] opened 2024-05-09 06:26 UTC
### What version of Bun is running?

1.1.7

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Install dockernode & npm i @types/dockerode
Try Running the following code.
```
console.log("Hello via Bun!");

import Dockerode from "dockerode";

const docker = new Dockerode({socketPath: '/var/run/docker.sock'});

console.log(docker.listContainers());
```

### What is the expected behavior?

Returns the containers currently running within the local docker instance.

### What do you see instead?
```
bun: symbol lookup error: /home/devon/projects/Reforged-Controller/node_modules/cpu-features/build/Release/cpufeatures.node: undefined symbol: node_module_register
```
### Additional information

Last working Bun version was `1.0.15`
Looks like `cpu-features` is a dependency of `ssh2` which is used within `dockernode`.

**Comment by Jarred-Sumner** [comment] 2024-05-09 06:28
Duplicate of #4290

**Comment by Jarred-Sumner** [comment] 2024-05-09 06:28
Please follow along in #4290

**Closed as not planned by Jarred-Sumner** 2024-05-09 06:28 UTC
Labels: bug
