### ISSUE TITLE
node runs js file even if it doesn't have `.js` extension

### ISSUE THREAD

**Issue by lorypelli** [oven-sh/bun#12724] opened 2024-07-22 20:29 UTC
### What is the problem this feature would solve?

node runs js file even if it doesn't have `.js` extension

### What is the feature you are proposing to solve the problem?

add it to bun also please

### What alternatives have you considered?

renaming to `.js`

**Comment by Electroid** [comment] 2024-07-22 20:58
Duplicate of #3824

**Closed as not planned by Electroid** 2024-07-22 20:58 UTC
Labels: enhancement
