### ISSUE TITLE
Cross-compile executable for target platform

### ISSUE THREAD

**Issue by ThatOneCalculator** [oven-sh/bun#7950] opened 2024-01-02 22:15 UTC
### What is the problem this feature would solve?

Currently, `bun build --compile` can only target the architecture and OS of the computer running the compilation.

### What is the feature you are proposing to solve the problem?

When compiling with Deno, it [supports the `--target <target>` flag](https://docs.deno.com/runtime/manual/tools/compiler#cross-compilation) allowing compilation for `x86_64-unknown-linux-gnu`, `x86_64-pc-windows-msvc`, `x86_64-apple-darwin`, and `aarch64-apple-darwin`.  Something similar for Bun would be very useful.

### What alternatives have you considered?

Using virtual machines or a matrix of Github Actions runners.

**Comment by Electroid** [comment] 2024-01-02 23:01
Duplicate of #3473

**Closed as completed by Electroid** 2024-01-02 23:01 UTC
Labels: enhancement, bundler

**Comment by ThatOneCalculator** [comment] 2024-01-02 23:30
Sorry about the duplicate, Github search didn't show it.
