### ISSUE TITLE
[Bun.write] high memory usage

### ISSUE THREAD

**Issue by truongan07** [oven-sh/bun#9057] opened 2024-02-22 23:20 UTC
### What version of Bun is running?

1.0.27+c34bbb2e3

### What platform is your computer?

Linux 6.3.6-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

I don't know is this leak memory when i create new files by Bun.write method and then Bun doesn't release memory after finish at all

```js
const file = globalThis.Bun.file('./26mb.json');
const fileLimit = 26, cutter = async () => {
    for(let i=0;i<fileLimit;i++) {
        const chunks = (await file.arrayBuffer()).slice(0, 1e6);
    
       // comment below line to see Bun automates free memory & uncomment to see memory consumed by Bun.write method
        globalThis.Bun.write(`./${i}.txt`, chunks);
    }
};

cutter();

[
    5000, 10000, 15000, 20000, 25000, 
    30000, 35000, 40000, 45000, 50000,
    55000, 60000, 65000, 70000, 75000
].forEach(time => setTimeout(() => {
    console.log(`start at ${time}`);

    cutter();
}, time));

```

download json file for testing : https://drive.google.com/file/d/1guA66f7_6smvVslAOJCTMBiUOtv5y0nQ/view?usp=drive_link

### What is the expected behavior?

Bun will release memory after finishing creating each new file by Bun.write

### What do you see instead?

Bun's process consumes high memory

**Comment by Jarred-Sumner** [comment] 2024-02-23 01:27
In Bun.write, we clone the ArrayBuffer passed to it. This is not a memory leak, but the memory usage is high due to that. 

If it was a memory leak, the memory would be roughly the same whether or not `Bun.write` is `await`'d. However, if we run this and `await` it, the memory usage is lower.

```js
const file = globalThis.Bun.file("./26mb.json");
const fileLimit = 26,
  cutter = async () => {
    for (let i = 0; i < fileLimit; i++) {
      const chunks = (await file.arrayBuffer()).slice(0, 1e6);

      // comment below line to see Bun automates free memory & uncomment to see memory consumed by Bun.write method
      Bun.write(`./${i}.txt`, chunks);
    }
  };

cutter();

[1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000].forEach(time =>
  setTimeout(() => {
    console.log(`start at ${time}`);

    cutter();
    console.log("RSS", process.memoryUsage.rss() / 1024 / 1024, "MB");
  }, time),
);

```

`require("fs").promises.writeFile` does not clone the data, and consequently has lower memory usage.

```js
const file = globalThis.Bun.file("./26mb.json");
const fileLimit = 26,
  cutter = async () => {
    for (let i = 0; i < fileLimit; i++) {
      const chunks = (await file.arrayBuffer()).slice(0, 1e6);

      // comment below line to see Bun automates free memory & uncomment to see memory consumed by Bun.write method
      require("fs/promises").writeFile(`./${i}.txt`, chunks);
    }
  };

cutter();

[1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000].forEach(time =>
  setTimeout(() => {
    console.log(`start at ${time}`);

    cutter();
    console.log("RSS", process.memoryUsage.rss() / 1024 / 1024, "MB");
  }, time),
);
```

We should consider not cloning the data in Bun.write.

**Comment by truongan07** [comment] 2024-02-23 02:18
> We should consider not cloning the data in Bun.write

I think you allow an option in Bun.write method as Bun.write(destination, arrayBuffer, isClone = true)

>  require("fs/promises") is not native Bun ?

**Comment by truongan07** [comment] 2024-03-12 06:53
@Jarred-Sumner Hi, If we have a function allows manually release memory after finish at all ? It can widespread using in most scenarios

**Comment by Jarred-Sumner** [comment] 2024-04-28 02:54
Fixed in #10588

debug build:
```
start at 1000
RSS 248.640625 MB
start at 2000
RSS 276.984375 MB
start at 3000
RSS 303.046875 MB
start at 4000
RSS 303.578125 MB
start at 5000
RSS 303.734375 MB
start at 6000
RSS 279.28125 MB
start at 7000
RSS 279.28125 MB
start at 8000
RSS 254.953125 MB
start at 9000
RSS 279.953125 MB
start at 10000
RSS 279.984375 MB
```

latest release build:
```
start at 1000
RSS 154.046875 MB
start at 2000
RSS 281.921875 MB
start at 3000
RSS 332.140625 MB
start at 4000
RSS 342.015625 MB
start at 5000
RSS 422.984375 MB
start at 6000
RSS 429.03125 MB
start at 7000
RSS 460.890625 MB
start at 8000
RSS 511.09375 MB
start at 9000
RSS 536.359375 MB
start at 10000
RSS 570.09375 MB
```

**Closed as completed** 2024-04-28 08:10 UTC
Labels: bug, bun.js

**Comment by truongan07** [comment] 2024-04-28 21:10
I tested a "971mb.json" file on [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000]: 
```
// eat 354.9MB memory
require("fs/promises").writeFile(`./${i}.txt`, chunks);

// eat 2.3GB memory
Bun.write(`./${i}.txt`, chunks);
```

Maybe issue of JavascriptCore. Thank you for support.

**Comment by truongan07** [comment] 2024-04-28 22:26
> I tested a "971mb.json" file on [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000]:
> 
> ```
> // eat 354.9MB memory
> require("fs/promises").writeFile(`./${i}.txt`, chunks);
> 
> // eat 2.3GB memory
> Bun.write(`./${i}.txt`, chunks);
> ```
> 
> Maybe issue of JavascriptCore. Thank you for support.

It tested in v1.1.5 and then upgrade to v1.1.6 of Bun. My issue was resolved. Bun's processing only eats 270.6MB. Very perfect

```
// only eats 270.6MB
Bun.write(`./${i}.txt`, chunks);
```
Thank you very much

**Comment by Jonatthu** [comment] 2024-08-15 22:01
@Jarred-Sumner  bun 1.1.24 on azure docker containers linux

<img width="996" alt="image" src="https://github.com/user-attachments/assets/ed76282d-9563-4f76-abb3-f8345b1367cf">

**Comment by Jarred-Sumner** [comment] 2024-08-15 22:04
@Jonatthu we are happy to look into this if you can open a new issue and include a code sample for us that you verify reproduces the issue. A screenshot of memory usage over time is difficult for us to do anything about though

**Comment by Jonatthu** [comment] 2024-08-15 22:06
@Jarred-Sumner I am willing to do it, even share my environment over discord screenshare if you prefer, I am just not sure how to strip out my company's repository to the point I can reproduce this

**Comment by Jarred-Sumner** [comment] 2024-08-15 22:08
if you try sticking a `Bun.gc(true)` in places that might allocate memory  and then `console.log((process.memoryUsage.rss() / 1024 / 1024 )| 0, "MB")`

that will help narrow it down to where it is occurring

**Comment by Jonatthu** [comment] 2024-08-15 22:11
@Jarred-Sumner 
I use elysiajs, prisma, drizzle, redis and trpc (with elysia)
the bun app is an api on this case, do you recoment to set 
Bun.gc(true)
and console.log((process.memoryUsage.rss() / 1024 / 1024 )| 0, "MB")
On each api endpoint or mostly middleware?

**Comment by Jonatthu** [comment] 2024-08-15 22:14
@Jarred-Sumner we have traces like this, I can share with you on discord
<img width="733" alt="image" src="https://github.com/user-attachments/assets/5730f2cc-0544-40ac-8ac3-73eb80ee2650">

**Comment by Jonatthu** [comment] 2024-08-21 08:10
@Jarred-Sumner I found out that drizzle-orm is the one having huge amount of memory usage per request with simple queries on a big schema, 1MB per request in average.
