### ISSUE TITLE
bun: symbol lookup error: /node_modules/@newrelic/native-metrics/prebuilds/linux-x64/@newrelic+native-metrics.abi115.uv1.glibc.node: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by monkfromearth** [oven-sh/bun#12453] opened 2024-07-09 08:54 UTC
### What version of Bun is running?

1.1.18+5a0b93523

### What platform is your computer?

Linux 6.8.0-36-generic x86_64 x86_64

### What steps can reproduce the bug?

Installed `newrelic` and add it using `import` on top of the main file.

**Comment by Jarred-Sumner** [comment] 2024-07-09 20:18
Duplicate of #4290

**Comment by Jarred-Sumner** [comment] 2024-07-09 20:18
Please follow along in #4290

**Closed as not planned by Jarred-Sumner** 2024-07-09 20:18 UTC
Labels: bug, needs triage
