### ISSUE TITLE
`beforeAll` execution order behaviour not the same between jest and bun

### ISSUE THREAD

**Issue by branks** [oven-sh/bun#8589] opened 2024-01-31 12:55 UTC
### What version of Bun is running?

1.0.25+a8ff7be64

### What platform is your computer?

Linux 6.5.0-15-generic x86_64 x86_64

### What steps can reproduce the bug?

We are using the `beforeAll` to reset mocks etc and the issue is that all the `beforeAll`'s  are all running at the start and so the tests happen, the mocks  / call counts etc are all wrong. You can see a reproduciton using the following code 

```
describe('A', () => {
  beforeAll(() => {
    console.log('beforeAll a');
  });
  it('a1', () => console.log('a1'));
  it('a2', () => console.log('a2'));
})

describe('B', () => {
  beforeAll(() => {
    console.log('beforeAll B');
  });
  it('b1', () => console.log('b1'));
  it('b2', () => console.log('b2'));
})
```

when we run `npx jest` we get an output of 

```
  A
    ✓ a1 (6ms)
    ✓ a2 (2ms)
  B
    ✓ b1 (1ms)
    ✓ b2 (5ms)

  console.log my.test.js:3
    beforeAll a

  console.log my.test.js:5
    a1

  console.log my.test.js:6
    a2

  console.log my.test.js:11
    beforeAll B

  console.log my.test.js:13
    b1

  console.log my.test.js:14
    b2
```

but when we run `bun test` we get an output of 
```
my.test.ts:
beforeAll a
beforeAll B
a1
✓ A > a1 [0.17ms]
a2
✓ A > a2 [0.11ms]
b1
✓ B > b1 [0.09ms]
b2
✓ B > b2 [0.08ms]
```

It seems the `beforeAlls`, even though they are scoped to a `decribe`, are all being run at the start but the tests are then sequential from then on

### What is the expected behavior?

I think the order should be consistent with Jest

**Comment by Electroid** [comment] 2024-02-01 17:34
Duplicate of #5738

**Closed as not planned by Electroid** 2024-02-01 17:34 UTC
Labels: bug, bun:test
