### ISSUE TITLE
 build --compile: include embedded filesystem in module resolution

### ISSUE THREAD

**Issue by ctjlewis** [oven-sh/bun#14320] opened 2024-10-03 06:55 UTC
### What is the problem this feature would solve?

Some modules misbehave when we try to compile them into a binary and it's hard to work around.

Motivated by issues with `yoga-wasm-web`. This should affect any case where someone does `bun build --compile -e [excluded] [entry]` and needs to resolve a runtime dependency from within the binary.

### What is the feature you are proposing to solve the problem?

An escape hatch where we can exclude a module from inlining and just put it in the embedded filesystem, and resolve to it that way.

We can already embed directories into `/$bunfs/root`, but I don't think Bun tries to resolve runtime imports from there.

```bash
# exclude package from inlining, we will resolve to it
# at runtime from the embedded filesystem 
bun build --compile -e package test.ts node_modules/package/** --outfile dist/out
```

```ts
// test.ts

// should resolve to /$bunfs/root/node_modules/package
// i.e., ./node_modules/package,
// since it is available and satisfies node resolution algo
import "package"
```

### What alternatives have you considered?

Just about all of them. Right now, the best I've got is excluding `yoga-wasm-web`, and distributing `node_modules` alongside it. But this only works as `./thing`, it will always try to resolve relative to `pwd`, so linking a binary is difficult. 

What *breaks* the algorithm is trying to call the binary from `pwd`:

```bash
#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_PATH="$SCRIPT_DIR/../app"

"$APP_PATH" "$@"
```

It will throw, and fail to resolve the module. It can't find it, because you're in `$(pwd)`, not `$SCRIPT_DIR`, and its dependencies are at `$SCRIPT_DIR/../node_modules`.

What works is changing to that directory for the process and running as `./thing`:

```bash
#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_PATH="$SCRIPT_DIR/.."

cd $APP_PATH
./app "$@"
```

But now, the working directory is the installation directory, which is not really what you want.

I think I can work around by taking `--cwd` as an argument, passing it into the application, and then once Bun has the process changing right back, a sort of hot potato thing.

**Comment by paperdave** [comment] 2024-11-16 01:23
thank you for the write up, but this is a duplicate of #8967

**Closed as not planned** 2024-11-16 01:29 UTC
Labels: enhancement
