### ISSUE TITLE
linux-aarch64 throws IllegalInstruction for v1.1.16 and higher on Raspberry pi 3+

### ISSUE THREAD

**Issue by sudhakar-selva** [oven-sh/bun#12254] opened 2024-06-29 22:57 UTC
### What version of Bun is running?

1.1.17

### What platform is your computer?

linux aarch64

### What steps can reproduce the bug?

Run latest version of bun in linux aarch64 (throws IllegalInstruction in raspberry pi 3 b+)

**Comment by Jarred-Sumner** [comment] 2024-06-30 00:23
Duplicate of #12076

**Comment by Jarred-Sumner** [comment] 2024-06-30 00:23
We are tracking this in #12076, please follow along there

**Closed as not planned** 2024-06-30 00:24 UTC
Labels: bug, needs triage
