### ISSUE TITLE
NotImplementedError: worker_threads.Worker option "eval" is not yet implemented in Bun

### ISSUE THREAD

**Issue by mrbrianevans** [oven-sh/bun#10212] opened 2024-04-12 11:56 UTC
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Install eslint in a project.
Run `bun --bun x eslint ./`

### What is the expected behavior?

It should just run eslint, without using nodejs and provide eslint output.

### What do you see instead?

```
$ bun --bun x eslint ./
```
```
14 |   warned.add(feature), console.warn(new NotImplementedError(feature, issue));
15 | }, $;
16 |
17 | class NotImplementedError extends Error {
18 |   code;
19 |   constructor(feature, issue) {
                               ^
NotImplementedError: worker_threads.Worker option "eval" is not yet implemented in Bun.
 code: "ERR_NOT_IMPLEMENTED"

      at new NotImplementedError (internal:shared:19:27)
      at internal:shared:9:73
      at new Worker (node:worker_threads:117:27)
      at startWorkerThread (/home/username/project/node_modules/.pnpm/synckit@0.8.8/node_modules/synckit/lib/index.cjs:310:18)
      at createSyncFn (/home/username/project/node_modules/.pnpm/synckit@0.8.8/node_modules/synckit/lib/index.cjs:90:18)
      at Program (/home/username/project/node_modules/.pnpm/eslint-plugin-prettier@5.1.3_eslint@8.56.0_prettier@3.2.4/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:166:15)
      at ruleErrorHandler (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1076:28)
      at /home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/safe-emitter.js:45:75
      at forEach (:1:21)
      at emit (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/safe-emitter.js:45:17)
      at applySelector (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/node-event-generator.js:297:13)
      at applySelectors (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/node-event-generator.js:326:17)
      at enterNode (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/node-event-generator.js:340:9)
      at enterNode (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:803:9)
      at /home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1111:17
      at forEach (:1:21)
      at runRules (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1106:5)
      at _verifyWithoutProcessors (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1355:31)
      at verify (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1437:60)
      at verifyAndFix (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:2068:24)
      at verifyText (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/cli-engine/cli-engine.js:254:41)
      at executeOnFiles (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/cli-engine/cli-engine.js:834:28)
      at /home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/eslint/eslint.js:551:13
      at lintFiles (/home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/eslint/eslint.js:543:21)
      at /home/username/project/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/cli.js:421:29
```

### Additional information

It looks like eslint is actually somehow running after this error message, cause it logs any linting errors.

**Comment by Electroid** [comment] 2024-04-12 15:52
Duplicate of https://github.com/oven-sh/bun/issues/4165

**Closed as not planned by Electroid** 2024-04-12 15:52 UTC
Labels: bug
