### ISSUE TITLE
TextEncoderStream / TextDecoderStream possibly causing segfault

### ISSUE THREAD

**Issue by uplusion23** [oven-sh/bun#13361] opened 2024-08-17 06:42 UTC
### How can we reproduce the crash?

Using the standard Clerk middleware for NextJS causes the issue, tested on 1.1.24 and 1.1.25-canary

```tsx
import { clerkMiddleware } from "@clerk/nextjs/server";

export default clerkMiddleware();

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    // Always run for API routes
    '/(api|trpc)(.*)',
  ],
};
```

### Relevant log output

```shell
============================================================
Bun v1.1.24 (85a32991) Linux x64
Linux Kernel v5.15.0 | glibc v2.35
CPU: sse42 popcnt avx avx2
Args: "/home/uplusion23/.bun/bin/bun" "/home/uplusion23/[PROJECT-DIR]/node_modules/next/dist/server/lib/start-server.js"
Features: jsc Bun.stdin dotenv fetch(3) http_server spawn(2) transpiler_cache(22) tsconfig_paths tsconfig 
Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns/promises" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:stream" "node:stream/web" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8" "node:diagnostics_channel" 
Elapsed: 5767ms | User: 2195ms | Sys: 595ms
RSS: 1.05GB | Peak: 0.38GB | Commit: 1.05GB | Faults: 1
```

### Stack Trace (bun.report)

Bun v1.1.24 ([`85a3299`](<https://github.com/oven-sh/bun/tree/85a32991152871b06becd6b411eb663008369769>)) on linux x86_64 [AutoCommand]

Segmentation fault at address 0x151332720480

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `llint_op_construct_varargs`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `llint_op_construct_varargs`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `llint_op_construct_varargs`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `llint_op_call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/85a32991152871b06becd6b411eb663008369769/ld-temp.o#L0>): `llint_op_call_ignore_result`

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:20
Duplicate of https://github.com/oven-sh/bun/issues/13629

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:20
Please follow along in https://github.com/oven-sh/bun/issues/13629. It will get fixed

**Closed as completed by Jarred-Sumner** 2024-09-01 04:20 UTC
Labels: crash, linux, runtime
