### ISSUE TITLE
using jsonwebtoken with bun throws TypeError while signing new token

### ISSUE THREAD

**Issue by mo1nammad** [oven-sh/bun#5378] opened 2023-09-14 14:13 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### using this code in a simple express app built with bun

`jwt.sign({ id: "xx" }, process.env.TOKEN_SECRET_KEY, {
    expiresIn: "1h",
});`

### What is the expected behavior?

the expected bahavior is to provide a jwt token

### What do you see instead?

instead i get the error down bellow 

TypeError: Right hand side of instanceof is not an object
      at /home/mohammad/Desktop/JWT auth/node_modules/jsonwebtoken/sign.js:114:38
      at /home/mohammad/Desktop/JWT auth/app.js:25:0
      at processTicksAndRejections (:1:2602)
109 | 
110 |   if (!secretOrPrivateKey && options.algorithm !== 'none') {
111 |     return failure(new Error('secretOrPrivateKey must have a value'));
112 |   }
113 | 
114 |   if (secretOrPrivateKey != null && !(secretOrPrivateKey instanceof KeyObject)) {
                                         ^

**Comment by sirenkovladd** [comment] 2023-09-14 14:27
Duplicate of https://github.com/oven-sh/bun/issues/2036

**Closed as not planned** 2023-09-14 15:54 UTC
Labels: bug

**Comment by muchekechege** [comment] 2023-10-04 15:13
why are you guys closing the issue with no solution

**Comment by userunknownn** [comment] 2023-10-11 19:34
For me the workaround was downgrading jwt to 8.5.1, just as @AlexRoosWork replied on this issue:
 https://github.com/auth0/node-jsonwebtoken/issues/939

**Comment by Electroid** [comment] 2023-10-11 20:05
If you upgrade to Bun v1.0.5, the issue should be fixed. If you're still experiencing the same issue, we can re-open.

**Comment by userunknownn** [comment] 2023-10-11 20:29
> If you upgrade to Bun v1.0.5, the issue should be fixed. If you're still experiencing the same issue, we can re-open.

I was on v1.0.0, I've just tested on v1.0.5, and it fixed
