### ISSUE TITLE
Crash while running bun update

### ISSUE THREAD

**Issue by shaunluedeke** [oven-sh/bun#11597] opened 2024-06-04 12:24 UTC
### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [UpdateCommand]

**panic**: index out of bounds

- [`install.zig:5119`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5119>): `processDependencyListItem`
- [`install.zig:5177`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5177>): `processDependencyList`
- [`install.zig:5895`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5895>): `runTasks`
- [`install.zig:10411`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L10411>): `installPackages`
- [`install.zig:8801`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L8801>): `updatePackageJSONAndInstallWithManagerWithUpdates`
- [`install.zig:7679`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L7679>): `updatePackageJSONAndInstallCatchError`
- [`cli.zig:1475`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L1475>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/src/startup/exe_common.inl#L78>): `invoke_main`

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:43
Duplicate of https://github.com/oven-sh/bun/issues/10565

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:44
To track this issue, please follow along in https://github.com/oven-sh/bun/issues/10565

**Closed as not planned by Jarred-Sumner** 2024-06-04 22:44 UTC
Labels: crash
