### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by guest271314** [oven-sh/bun#504] opened 2022-07-09 16:41 UTC
I downloaded the latest release and ran the following code on Linux 5.4.0-42-lowlatency

```
#!/usr/bin/env -S ./bun 
console.log('Hello, World!');
```

```
$ ./test.js
```

Result 

```
Illegal instruction (core dumped)
```

**Comment by mikrosystheme** [comment] 2022-07-09 17:04
Please use the search before posting new issues.

https://github.com/Jarred-Sumner/bun/issues?q=Illegal+instruction

**Comment by FinnRG** [comment] 2022-07-09 17:11
Duplicate of #67.

**Closed as completed by FinnRG** 2022-07-09 17:11 UTC

**Comment by guest271314** [comment] 2022-07-09 17:17
I did search first.

Where are instructions for basic usage in the linked issue?

**Comment by guest271314** [comment] 2022-07-09 17:26
The instructions in #67 don't change anything.
