### ISSUE TITLE
Adding same package via `tar.gz` twice with different URLs gives `DependencyLoop`

### ISSUE THREAD

**Issue by nomadshiba** [oven-sh/bun#5402] opened 2023-09-14 20:08 UTC
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Linux 5.15.0-82-generic x86_64 x86_64

### What steps can reproduce the bug?

Install a package via `.tar.gz` or `.tgz` URL
```
bun i https://registry.npmjs.org/zod/-/zod-3.21.4.tgz
```
Then install the same package with a different version (so, different URL)
```
bun i https://registry.npmjs.org/zod/-/zod-3.21.3.tgz
```
```sh
error: DependencyLoop
```

### What is the expected behavior?

New install should replace the old one if the package name is the same.

### What do you see instead?

error: DependencyLoop

### Additional information

Didn't check if same issue also exists while installing from `git:` or `github:`

**Comment by Electroid** [comment] 2023-09-20 16:34
Duplicate of #5789

**Closed as not planned by Electroid** 2023-09-20 16:34 UTC
Labels: bug
