### ISSUE TITLE
QOL Improvement: Support Automatically Managing Type Definitions

### ISSUE THREAD

**Issue by avasilic** [oven-sh/bun#4788] opened 2023-09-10 10:37 UTC
### What is the problem this feature would solve?

TypeScript developers need to manually install and uninstall type definitions for packages using `bun add @types/<package-name> -D`. The process can look something like this

1. Install a new package.
2. Wait for installation (1, 2 seconds at most)
3. Import the new package
4. Encounter TypeScript errors due to missing type definitions.
5. Manually run `bun add @types/<name> -D` to install type definitions.
6. Wait again for type definition installation (1, 2 seconds at most)

A similar process exists when uninstalling, where forgetting to uninstall the type definitions is more common in my experience.

### Indication of interest

There are several utilities, Reddit, and StackOverflow posts for people asking if such functionality exists for other package managers[^1][^2][^3][^4][^5], and utilities for other package managers which do this[^6][^7][^8][^9]. While we could ask one of them to support Bun, native is always faster.

[^1]: https://www.reddit.com/r/typescript/comments/6d3m16/is_it_possible_to_automatically_npm_install/
[^2]: https://stackoverflow.com/questions/56623737/how-to-install-types-from-an-npm-package-that-has-in-its-name
[^3]: https://stackoverflow.com/questions/60339541/does-npm-or-yarn-have-feature-to-automatically-install-types-if-they-exist-in-t
[^4]: https://stackoverflow.com/questions/48857430/install-type-definitions-automatically-when-i-install-an-npm-package
[^5]: https://www.reddit.com/r/typescript/comments/9i4age/installuninstall_types_packages_automatically/?rdt=55158 
[^6]: https://github.com/jeffijoe/typesync
[^7]: https://github.com/xavdid/typed-install
[^8]: https://www.npmjs.com/package/@yarnpkg/plugin-typescript
[^9]: https://github.com/T-Specht/ts-typie

### Potential Roadblock

What if a package has embedded type definitions but also an old `@types` package that does not have a deprecation flag?

### What is the feature you are proposing to solve the problem?

Bun would look up whether `@types/<package-name>` exists when installing a package. For example, if I run `bun add common-tags` Bun would also look up `@types/common-tags`, see that it exists, and install it.

There are two ways I see to configure this:
1. Explicit opt-in: `autoManageTypeDefinitions = true` in `bunfig.toml` (default to false)
2. Explicit opt-out: Same as above but default would be `true`
3. Prompt: If bun detects a type definitions package it asks `Install @types/<package-name>?`. Users would most likely still want a `bunfig.toml` option so they don't have to answer `yes` every time. Same for uninstalling: `Uninstall @types/<package-name>?`

### What alternatives have you considered?

1. Creating custom scripts to automate the installation of type definitions in Bun
2. Asking one of the aforementioned tools to add Bun support

**Comment by Electroid** [comment] 2023-10-27 21:29
Duplicate of #6493

**Closed as not planned by Electroid** 2023-10-27 21:29 UTC
Labels: enhancement
