### ISSUE TITLE
Converting node streams to web streams throws an error

### ISSUE THREAD

**Issue by leonardoraele** [oven-sh/bun#16087] opened 2024-12-31 17:43 UTC
### What version of Bun is running?

1.1.42+50eec0025

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Minimum reproducible script:

```ts
import { Readable, Writable } from 'node:stream';

Readable.toWeb(process.stdin).pipeTo(Writable.toWeb(process.stdout));
```

### What is the expected behavior?

The script should run without errors. It should echo the input into the output.

### What do you see instead?

```bash
$ npx bun main.ts
1 | import { Readable, Writable } from 'node:stream';
2 |
3 | Readable.toWeb(process.stdin).pipeTo(Writable.toWeb(process.stdout));
                                                  ^
TypeError: lazyWebStreams().newWritableStreamFromStreamWritable is not a function. (In 'lazyWebStreams().newWritableStreamFromStreamWritable(streamWritable)', 'lazyWebStreams().newWritableStreamFromStreamWritable' is undefined)
      at node:stream:2941:66
      at C:\Users\Leonardo Raele\Workspace\testapp\src\main.ts:3:47

Bun v1.1.42 (Windows x64)
```

### Additional information
The script works on Node:
```bash
$ node --import=tsx .\src\main.ts
Hello
Hello
```

Piping `stdin` to `stdout` without converting to web streams work as expected.
```bash
$ npx bun -e "process.stdin.pipe(process.stdout)"
Hello
Hello
```

**Comment by Jarred-Sumner** [comment] 2024-12-31 18:10
Duplicate of https://github.com/oven-sh/bun/issues/3927

**Closed as duplicate** 2024-12-31 18:10 UTC
Labels: bug
