### ISSUE TITLE
`socketPath` issue with node:http

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#6055] opened 2023-09-25 22:05 UTC
Building a docker extension and am using bun.serve which is working great when the front end wants to talk to the backend. But I want to initiate some UNIX socket requests and am having some issues doing that. What would be the best way to go about it?

_Originally reported on Discord: [`UNIX socket requests in BUN`](https://discord.com/channels/876711213126520882/1155912666544607262/1155912666544607262)_

**Comment by Zampare** [comment] 2023-09-25 22:50
went over to just using http.request and that still doesnt work in bun. So I'm wondering if socketPath as an option just didn't get implemented.
What my code looks like:
```javascript
import http from 'node:http';
​
async function getDockerContainers(): Promise<Container[]> {
  const options = {
    socketPath: '/var/run/docker.sock',
    method: 'GET',
    path: '/containers/json',
  };
  const data = await new Promise<Container[]>((resolve, reject) => {
    const req = http.request(options, res => {
      console.log(res);
      let rawData = '';
      res.on('data', chunk => {
        rawData += chunk;
      });
      res.on('end', () => {
        resolve(JSON.parse(rawData));
      });
    });
    req.end();
  });
  const containers = data;
​
  return containers;
}

**Comment by hazelnutcloud** [comment] 2023-10-24 10:11
the `dockerode` package is unusable because of this bug.

**Comment by ImLunaHey** [comment] 2023-10-29 01:27
Duplicate of https://github.com/oven-sh/bun/issues/2853?

**Comment by siinghd** [comment] 2024-02-11 15:39
Any update on this? Can't use dockerode

**Comment by isaced** [comment] 2024-02-11 15:43
+1, for dockerode

**Comment by Anprotaku** [comment] 2024-03-06 09:56
+1 for dockerode
is there any temp fix for this?

**Comment by ImLunaHey** [comment] 2024-03-06 22:38
please stop bumping this to leave a +1

**Closed as completed** 2024-03-06 23:28 UTC
Labels: bug, node.js
