### ISSUE TITLE
GIthub action failed during tauri build

### ISSUE THREAD

**Issue by aravindhnivas** [oven-sh/bun#10622] opened 2024-04-29 01:46 UTC
### Stack Trace (bun.report)

Bun v1.1.6 ([#10596](https://github.com/oven-sh/bun/pull/10596)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:4872`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L4872): `processDependencyListItem`
- [`logger.zig:850`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/logger.zig#L850): `allocPrint`
- [`install.zig:5650`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L5650): `runTasks`
- [`install.zig:10115`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L10115): `installPackages`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1304`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1304): `which`
- [`cli.zig:56`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L56): `start`
- [`main.zig:52`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/main.zig#L52): `main`
- `_ZN9hashbrown3raw21RawTable$LT$T$C$A$GT$14reserve_rehash17h6e5acef1e33143a1E`
- ??? at `0x14cb0` in /KERNEL32.DLL

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:42
Duplicate of https://github.com/oven-sh/bun/issues/10565

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:42
To track this issue, please follow along in https://github.com/oven-sh/bun/issues/10565

**Closed as not planned by Jarred-Sumner** 2024-06-04 22:42 UTC
Labels: bug, crash
