### ISSUE TITLE
--hot: Capacity to read .env file changes

### ISSUE THREAD

**Issue by Areshkew** [oven-sh/bun#4624] opened 2023-09-08 22:31 UTC
### What is the problem this feature would solve?

Bun lacks the ability to detect changes in the .env file while using the --hot tag. This limitation results in the application not reflecting changes made to environment variables during runtime, potentially leading to incorrect behavior or the need for manual server restarts.

### What is the feature you are proposing to solve the problem?

To address this issue, would be good  the addition of a new feature that enables the application to dynamically detect changes in the .env file when the --hot flag is used. This feature would allow the application to automatically reload or update its configuration based on changes made to environment variables in the .env file without requiring a manual restart.

**Comment by oliverjam** [comment] 2023-09-17 21:35
https://github.com/oven-sh/bun/issues/5278 is probably related since it would solve this problem by letting you explicitly opt-in to watching `.env` changes.

**Comment by simylein** [comment] 2023-09-22 12:43
Duplicate of #2521

**Comment by Electroid** [comment] 2023-10-27 20:29
Duplicate of https://github.com/oven-sh/bun/issues/2521

**Closed as not planned by Electroid** 2023-10-27 20:29 UTC
Labels: enhancement
