### ISSUE TITLE
Incorrect ReadableStreamDefaultController runtime TypeError

### ISSUE THREAD

**Issue by ethanniser** [oven-sh/bun#5537] opened 2023-09-16 06:27 UTC
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

https://github.com/ethanniser/jank-rsc
`bun go`
visit http://localhost:3000
look at stdout

### What is the expected behavior?

```ts
console.log(
    "is controller a ReadableStreamDefaultController?",
    controller instanceof ReadableStreamDefaultController
  );
controller.enqueue(content);
```

The method is called correctly

### What do you see instead?

Even though `controller instanceof ReadableStreamDefaultController` logs out as 'true', a TypeError still appears

stdout:
```
whatplan@GAMER:~/code/tests/jank-rsc$ bun go
$ bun run --hot src/example.tsx
app is listening on http://localhost:3000
is controller a ReadableStreamDefaultController? true
1 | (function (chunk) {"use strict";
                       ^
TypeError: Can only call ReadableStreamDefaultController.enqueue on instances of ReadableStreamDefaultController
      at enqueue (:1:20)
      at /home/whatplan/code/tests/jank-rsc/src/lib/suspense.ts:48:4
```

the error message was slightly different in 1.01
```
whatplan@GAMER:~/code/tests/jank-rsc$ bun go
$ bun run --hot src/example.tsx
app is listening on http://localhost:3000
is controller a ReadableStreamDefaultController? true
1 | (function (chunk){"use strict";if(!@isReadableStreamDefaultController(this))throw @makeThisTypeError("ReadableStreamDefaultController","enqueue");if(!@readableStreamDefaultControllerCanCloseOrEnqueue(this))@throwTypeError("ReadableStreamDefaultController is not in a state where chunk can be enqueued");return @readableStreamDefaultControllerEnqueue(this,chunk)})
                       ^
TypeError: Can only call ReadableStreamDefaultController.enqueue on instances of ReadableStreamDefaultController
```

**Comment by ethanniser** [comment] 2023-09-16 14:45
I think I was closing the stream before enqueuing, which after fixing that the issue went away

but the error message could be clearer to what is the actually problem

**Comment by Electroid** [comment] 2023-10-24 13:35
Duplicate of #6664

**Closed as completed by Electroid** 2023-10-24 13:35 UTC
Labels: bug, web-api
