### ISSUE TITLE
Support node env variables - a la: npm_package_config

### ISSUE THREAD

**Issue by tommyboylab** [oven-sh/bun#7510] opened 2023-12-07 09:20 UTC
### What is the problem this feature would solve?

I am trying to get the env variables I set within my package.json as is documented in the[ npm documentation](https://docs.npmjs.com/cli/v6/using-npm/config#per-package-config-settings) with bun but they don't seem to be present within the `bun run env` list.

### What is the feature you are proposing to solve the problem?

The list of env variables found within the package.json config should be present in bun env and available to process.env to be used within the rest of the application

### What alternatives have you considered?

Using node and npm presents the list of env variables -- but I would prefer to use bun to run my application.

**Comment by bjon** [comment] 2024-06-12 13:50
Yes, it would be great if we could access `$npm_package_config_` variables

**Comment by Chinoman10** [comment] 2024-06-30 11:53
+1

**Comment by Jarred-Sumner** [comment] 2024-06-30 12:03
Duplicate of https://github.com/oven-sh/bun/issues/2793

**Comment by Jarred-Sumner** [comment] 2024-06-30 12:04
Tracking this in #2793. Not yet decided on whether or not we will support it

**Closed as not planned by Jarred-Sumner** 2024-06-30 12:04 UTC
Labels: enhancement
