### ISSUE TITLE
url.fileURLToPath does not support argument as string

### ISSUE THREAD

**Issue by ggrossetie** [oven-sh/bun#1069] opened 2022-08-13 17:31 UTC
### Version

0.1.8

### Platform

Linux xb64 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

```js
import { fileURLToPath } from 'url'

console.log(fileURLToPath(import.meta.url))
```

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behavior?

It should convert the URL (string) to a path.

### What do you see instead?

```console
$ bun main.mjs
1 | import { fileURLToPath } from 'url'
2 | 
3 | console.log(fileURLToPath(import.meta.url))
               ^
TypeError: Argument must be a URL
      at /path/to/main.mjs:3:12
```

### Additional information

Node.js supports both an URL and a string as argument: https://nodejs.org/api/url.html#urlfileurltopathurl

**Comment by robogeek** [comment] 2022-08-13 18:39
I'm concerned that the issue I filed (a duplicate of this) was closed with "notplanned".  Does that mean the Bun team does not see this as an important issue to solve?

The code related to the example are directly derived from Node.js documentation:  https://nodejs.org/api/esm.html

The `import.meta.url` variable is supposed to contain a `file:` URL for the module that had been loaded.  In order to compute `__dirname` and `__filename` it is documented to use `fileURLToPath` to process the URL into the pathnames.

This is a common practice, and will be widely used in Node.js packages.  If Bun does not fix this for compatibility with Node.js, that will make it harder to write code which works on both Node.js and Bun.

**Comment by xhyrom** [comment] 2022-08-13 22:57
> I'm concerned that the issue I filed (a duplicate of this) was closed with "notplanned".  Does that mean the Bun team does not see this as an important issue to solve?
> 
> The code related to the example are directly derived from Node.js documentation:  https://nodejs.org/api/esm.html
> 
> The `import.meta.url` variable is supposed to contain a `file:` URL for the module that had been loaded.  In order to compute `__dirname` and `__filename` it is documented to use `fileURLToPath` to process the URL into the pathnames.
> 
> This is a common practice, and will be widely used in Node.js packages.  If Bun does not fix this for compatibility with Node.js, that will make it harder to write code which works on both Node.js and Bun.
> 

Every duplicate issues is closed as not planned, but it's planned (I'll close it normally).

Sorry for confusion.

**Comment by xHyroM** [comment] 2022-08-13 22:58
Sorry for confusion.

**Comment by robogeek** [comment] 2022-08-14 01:27
Thank you

**Closed as completed** 2022-08-18 08:13 UTC
Labels: bug
