### ISSUE TITLE
BUN on WSL (Alpine)

### ISSUE THREAD

**Issue by anime-shed** [oven-sh/bun#4764] opened 2023-09-10 05:35 UTC
### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 unknown

![image](https://github.com/oven-sh/bun/assets/67512697/927b5503-8b4f-454c-8662-f6fae9dd2f8c)

### What steps can reproduce the bug?

`curl -fsSL https://bun.sh/install | bash`

### What is the expected behavior?

`bun --version`
Should run

### What do you see instead?

`-ash: bun: not found`

### Additional information

![image](https://github.com/oven-sh/bun/assets/67512697/ea6f3b4d-e8f3-429d-bc47-943184014d16)

**Comment by brynne8** [comment] 2023-09-10 07:19
It's related to https://github.com/oven-sh/bun/issues/918.

**Comment by Electroid** [comment] 2023-10-27 21:06
Closing as a duplicate of https://github.com/oven-sh/bun/issues/918

**Closed as not planned by Electroid** 2023-10-27 21:06 UTC
Labels: bug
