### ISSUE TITLE
Node https interop bug with https.request to fetch mapping

### ISSUE THREAD

**Issue by mpodwysocki** [oven-sh/bun#2253] opened 2023-03-01 20:18 UTC
### What version of Bun is running?

0.5.7

### What platform is your computer?

Darwin 22.3.0 arm64 arm

### What steps can reproduce the bug?

```javascript
import * as https from "node:https";

const body = `{ "aps" : { "alert" : "Hello" } }`;
const method = "POST";

const headers = {
  "Authorization": "",
  "x-ms-version": API_VERSION,
  "Content-Type": "application/json",
  "apns-priority": "10",
  "apns-push-type": "alert",
};

async function sendRequest(url, headers, body, method) {
  const options = {
    headers,
    method
  };

  return new Promise((resolve, reject) => {
    const request = https.request(url, options, (response) => {
      const res = {
        body: "",
        headers: response.headers
      }

      response.on("data", (data) => {
        res.body += data;
      });

      response.on("end", () => {
        resolve(res);
      });
    });

    request.on("error", (err) => {
      reject(err);
    });

    request.write(body);
    request.end();
  });
}

const url = new URL("https://some-fake-address.servicebus.windows.net");

const result = await sendRequest(url, headers, body, method);
```

### What is the expected behavior?

The headers and body are returned with the response such as:

```bash
$ node sendDirectNotificationWithNode.js
Tracking ID: f5e8e6a8-bc8b-4a4b-b452-3e3c93299870
Correlation ID: f2340956-f677-447a-9d95-8eb2061e66b0
```

### What do you see instead?

```bash
$ bun run sendDirectNotificationWithNode.js
Sample: Error occurred:  939 |   }
940 |
941 |   _final(callback) {
942 |     this.#finished = true;
943 |
944 |     this.#fetchRequest = fetch(`${this.#protocol}//${this.#host}:${this.#port}${this.#path}`, {
                            ^
TypeError: fetch() request with GET/HEAD/OPTIONS method cannot have body.
```

### Additional information

This is blocking our usage of Bun for the Azure SDK as we are running into compatibility issues for the HTTPS stack

**Comment by ThatOneBro** [comment] 2023-03-01 20:21
Thank you for reporting this. I'll look into it

**Comment by ThatOneBro** [comment] 2023-03-01 21:50
Is there by any chance a redirect at the URL you're getting this particular error on? I'm having a hard time reproducing this locally, and because your POST is turning into a GET, I'm wondering if you're getting a 3xx status code on your initial request and we're trying to follow that (which by default converts POSTs into GETs for safety)


EDIT: Potentially the redirect is unexpected and it's due to an error in how we are parsing the URL object you're passing in. Investigating that now

**Comment by ThatOneBro** [comment] 2023-03-02 02:14
@mpodwysocki I think I may have solved the problem in `https.request` you were running into, can you check if you're still having this issue in canary?

**Comment by Jarred-Sumner** [comment] 2023-03-02 02:15
Once the build https://github.com/oven-sh/bun/actions/runs/4309875038/jobs/7517745263 finishes, please run

```
bun upgrade --canary
```

**Comment by mpodwysocki** [comment] 2023-03-02 03:01
@Jarred-Sumner @ThatOneBro 

new error:

```bash
1030 |     }
1031 |
1032 |     if (protocol !== expectedProtocol) {
1033 |
1034 |       throw new Error(`Protocol mismatch. Expected: ${expectedProtocol}. Got: ${protocol}`);
               ^
error: Protocol mismatch. Expected: http:. Got: https:
      at new ClientRequest (node:http:1034:12)
      at request (node:http:1451:9)
```

**Comment by Jarred-Sumner** [comment] 2023-03-02 03:42
Please try again once more after this commit builds

https://github.com/oven-sh/bun/commit/706a3e8169ae27b1b5c3694d46b593f220c41b80

**Comment by mpodwysocki** [comment] 2023-03-02 04:02
@Jarred-Sumner perfect, works now!

**Comment by ThatOneBro** [comment] 2023-03-02 04:16
@mpodwysocki Awesome! Thanks for working with us through this. 

I'm going to go ahead and close this issue, but please let us know if you run into any other compatibility problems and we'll try to get them fixed ASAP. We appreciate the bug reports 😄

**Closed as completed by ThatOneBro** 2023-03-02 04:16 UTC
Labels: bug, node.js
