### ISSUE TITLE
Vercel deploy fails with Next.js 11 (Blitz)

### ISSUE THREAD

**Issue by fungilation** [oven-sh/bun#5148] opened 2023-09-12 20:28 UTC
### What version of Bun is running?

1.0

### What platform is your computer?

Darwin 22.6.0 arm64 arm | macOS 13.5.1

### What steps can reproduce the bug?

Vercel deploy:

- succeeds on bun install, truly blazing speed with virgin installs taking 3.2s, when yarn used to take 70s+ on Vercel!
- but `bun run build` step fails due to esbuild install failure:

<img width="898" alt="image" src="https://github.com/oven-sh/bun/assets/3803466/2d8d8232-8429-49ea-ba61-d4c8a1874804">

`node_modules/esbuild/bin/esbuild` should be a binary if installed correctly, but instead it's a script with the error boilerplate

### What is the expected behavior?

`node_modules/esbuild/bin/esbuild` should be a binary after `bun install`

Same output on my Mac local as well as the Vercel build output above

### What do you see instead?

node_modules/esbuild/bin/esbuild is error boilerplate script

**Comment by colinhacks** [comment] 2023-09-12 23:03
This is due to Bun not running esbuild's postinstall: https://github.com/oven-sh/bun/issues/4959

**Comment by Electroid** [comment] 2023-10-26 22:18
Duplicate of #4959 (we will fix this)

**Closed as not planned by Electroid** 2023-10-26 22:18 UTC
Labels: bug
