### ISSUE TITLE
subshells: `bun install` failing on Windows

### ISSUE THREAD

**Issue by Kinjalkashyap** [oven-sh/bun#9780] opened 2024-04-01 17:03 UTC
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

- Create a project having Sharp as a dependency 
- Run `bun install`
- The command throws an error (see below)

### What do you see instead?

This is the error: 

```sh
bun install v1.1.0 (5903a614)
  ⚙️  sharp [2/3] error: Failed to run script D:\vs code\my-astro-project\node_modules\sharp\[eval] due to error Unexpected `(`, subshells are currently not supported right now. Escape the `(` or open a GitHub issue.

error: install script from "sharp" exited with 1
```

**Comment by aczw** [comment] 2024-04-02 04:07
The same error with `sharp` and Astro is also being tracked at #9781

**Comment by Jarred-Sumner** [comment] 2024-04-02 04:13
Duplicate of #9781 

Since #9781 has more upvotes, we'll use that one as the tracking issue



We'll close this one as duplicate, but we are still definitely going to fix it. Please follow along in #9781

**Closed as not planned by Jarred-Sumner** 2024-04-02 04:13 UTC
Labels: bug
