### ISSUE TITLE
Error.captureStackTrace() behavior is different from node

### ISSUE THREAD

**Issue by devlzcode** [oven-sh/bun#6923] opened 2023-11-06 10:51 UTC
### What version of Bun is running?

1.0.8

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

```js
class CustomError extends Error {
  constructor(message) {
    super(message);
    Error.captureStackTrace(this, CustomError);
  }
}

throw new CustomError("This is a custom error");
```

### What is the expected behavior?

```sh
node index.js
file:///path/to/dir/index.js:8
throw new CustomError("This is a custom error");
      ^

CustomError: This is a custom error
    at file:///path/to/dir/index.js:8:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
```

### What do you see instead?

```sh
 bun index.js
1 | class CustomError extends Error {
2 |   constructor(message) {
3 |     super(message);
4 |     Error.captureStackTrace(this, CustomError);
        ^
error: This is a custom error
      at new CustomError (/path/to/dir/index.js:4:4)
      at /path/to/dir/index.js:8:6
```

### Additional information

The expected function signature for `Error.captureStackTrace` has an optional second argument: `ErrorConstructor.captureStackTrace(targetObject: object, constructorOpt?: Function | undefined): void`
That does not exist in Bun's implementation.
https://github.com/oven-sh/bun/blob/main/src/js/internal/primordials.js#L80-#L84
```js
function ErrorCaptureStackTrace(targetObject) {
  const stack = new Error().stack;
  // Remove the second line, which is this function
  targetObject.stack = stack.replace(/.*\n.*/, "$1");
}
```

**Comment by ayonli** [comment] 2023-12-17 18:05
Error.captureStackTrace is a special builtin function of V8 engine, which cannot be fully polyfilled.

Bun supports this function by simply calling new Error().stack.

To fully support this function, some changes must be done in the JavaScriptCore engine, which is maintained by Apple.

**Comment by Jarred-Sumner** [comment] 2023-12-17 20:58
There’s definitely a bug here, but Bun does support the optional second argument. The link you provided is not the code for Error.captureStackTrace. `Error.captureStackTrace` is implemented in C++ in ZigGlobalObject.cpp

**Comment by paperdave** [comment] 2024-06-04 05:18
This seems to be fixed as of Bun 1.1

**Closed as completed by paperdave** 2024-06-04 05:18 UTC
Labels: bug, node.js

**Comment by TiBianMod** [comment] 2024-06-04 06:44
I don't think this has been fixed @paperdave
using `Error.captureStackTrace(this, CustomError)`, the stack trace is still off

**Comment by FelixZY** [comment] 2024-06-15 21:01
@TiBianMod 

```
$ bun repro.ts 
3 |     super(message);
4 |     Error.captureStackTrace(this, CustomError);
5 |   }
6 | }
7 | 
8 | throw new CustomError("This is a custom error");
          ^
error: This is a custom error
      at module code (/workspaces/labelt/repro.ts:8:7)
      at moduleEvaluation (native:1:1)
      at moduleEvaluation (native:1:1)
      at native:1:1

Bun v1.1.13 (Linux x64)
```

LGTM?

**Comment by TiBianMod** [comment] 2024-06-16 06:28
@FelixZY

yes, now in version `v1.1.13`, looks OK. thanks to this PR https://github.com/oven-sh/bun/pull/11581

if you see @FelixZY, I wrote the comment 2 weeks ago!!!

**Comment by guillemus** [comment] 2025-11-17 20:43
There might be a regression in `v1.3.2` @TiBianMod

this produces different stack traces, whether you run it with `bun <scriptname>.ts` or `bunx tsx <scriptname>.ts`:

```typescript
function err1() {
    let error = new Error('aa')
    return error
}

function err2() {
    let e = err1()
    return e
}

function err3() {
    let e = err2()
    return e
}

console.log(err3())
```

outputs:

```bash
➜  gitrapid git:(dev) ✗ bun tsx src/errts.ts 
Error: aa
    at err1 (/Users/guillem/Documents/projects/gitrapid/src/errts.ts:120:17)
    at err2 (/Users/guillem/Documents/projects/gitrapid/src/errts.ts:125:13)
    at err3 (/Users/guillem/Documents/projects/gitrapid/src/errts.ts:130:13)
    at <anonymous> (/Users/guillem/Documents/projects/gitrapid/src/errts.ts:134:13)
    at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)


➜  gitrapid git:(dev) ✗ bun src/errts.ts     
129 | function err3() {
130 |     let e = err2()
131 |     return e
132 | }
133 | 
134 | console.log(err3())
                  ^
error: aa
      at /Users/guillem/Documents/projects/gitrapid/src/errts.ts:134:13
      at loadAndEvaluateModule (2:1)
```
