### ISSUE TITLE
TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by mrceperka** [oven-sh/bun#11754] opened 2024-06-10 15:10 UTC
### What version of Bun is running?

1.1.12+43f0913c3

### What platform is your computer?

Linux 6.8.11-300.fc40.x86_64 x86_64 unknown

### What steps can reproduce the bug?

```ts
// src/main.ts
import puppeteer from 'puppeteer-extra'
import stealth from 'puppeteer-extra-plugin-stealth'

puppeteer.use(stealth())
await puppeteer.launch(/* does not really matter */)
```

```shell
bun build --compile --target=bun-linux-x64 ./src/main.ts --outfile main
./main
```

```txt
82525 | 
82526 | // node_modules/clone-deep/utils.js
82527 | var require_utils6 = __commonJS((exports, module) => {
82528 |   var utils = require_lazy_cache()(import.meta.require);
82529 |   var fn = import.meta.require;
82530 |   import.meta.require = utils;
          ^
TypeError: Attempted to assign to readonly property.
      at /$bunfs/root/main:82530:3
      at /$bunfs/root/main:18:75
      at /$bunfs/root/main:82572:15
      at /$bunfs/root/main:18:75
      at /$bunfs/root/main:82724:15
      at /$bunfs/root/main:18:75
      at /$bunfs/root/main:82755:16
      at /$bunfs/root/main:18:75
      at /$bunfs/root/main:82892:34
      at /$bunfs/root/main:18:75
```

### What is the expected behavior?

It should work

### What do you see instead?

TypeError: Attempted to assign to readonly property

### Additional information

Bun v1.1.12 (Linux x64)

**Comment by Jarred-Sumner** [comment] 2024-08-08 21:44
Confirming this still occurs as of Bun v1.1.22

The bug is caused by a library attempting to reassign `import.meta.require`

**Comment by wimil** [comment] 2024-11-01 21:38
I have the same problem, any solution?

**Closed as completed** 2024-11-01 22:35 UTC
Labels: bundler
