### ISSUE TITLE
bun build --compile --minify index out of bounds on windows

### ISSUE THREAD

**Issue by marianoguerra** [oven-sh/bun#9979] opened 2024-04-05 11:27 UTC
### What version of Bun is running?

1.1.1

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

setup:

```sh
bun install nodejs-polars
```

server.js file:

```js
import pl from "nodejs-polars";
```

this works:

```sh
bun build server.js --compile
```

but this crashes:

```sh
bun build server.js --compile --minify
```

crash:

```
uh-oh: index out of bounds
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.1 (ca1dbb4e) Windows x64
BuildCommand:
Elapsed: 63ms | User: 0ms | Sys: 31ms
RSS: 0.15GB | Peak: 0.15GB | Commit: 0.25GB | Faults: 37580
----- bun meta -----

0   00007FF768D4ED58
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 13180 panic: index out of bounds
???:?:?: 0x7ff76804c246 in ??? (bun.exe)
???:?:?: 0x7ff767e1b9ad in ??? (bun.exe)
???:?:?: 0x7ff767f090f8 in ??? (bun.exe)
???:?:?: 0x7ff7677912e0 in ??? (bun.exe)
???:?:?: 0x7ff767c1d829 in ??? (bun.exe)
???:?:?: 0x7ffacd24257c in ??? (KERNEL32.DLL)
???:?:?: 0x7fface6caa47 in ??? (ntdll.dll)
```

another issue is that the resulting exe (built without --minity) fails when running with:

```
17 | };
18 | var __commonJS = (cb, mod) => () => (mod || cb((mod = { exports: {} }).exports, mod), mod.exports);
19 |
20 | // node_modules/nodejs-polars-win32-x64-msvc/nodejs-polars.win32-x64-msvc.node
21 | var require_nodejs_polars_win32_x64_msvc = __commonJS((exports, module) => {
22 |   module.exports = import.meta.require("B:/~BUN/root/nodejs-polars.win32-x64-msvc-c86a974a4af1b141.node");
                        ^
TypeError: LoadLibrary failed: No se puede encontrar el
      at B:/~BUN/root/server.js:22:20
      at B:/~BUN/root/server.js:18:75
      at B:/~BUN/root/server.js:86:31
      at B:/~BUN/root/server.js:18:75
      at B:/~BUN/root/server.js:251:44
      at B:/~BUN/root/server.js:18:75
      at B:/~BUN/root/server.js:4194:43
      at B:/~BUN/root/server.js:18:75
      at B:/~BUN/root/server.js:4713:29
```

### What is the expected behavior?

it should build the exe and it should run without an error

### What do you see instead?

```
uh-oh: index out of bounds
bun will crash now 😭😭😭

----- bun meta -----
Bun v1.1.1 (ca1dbb4e) Windows x64
BuildCommand:
Elapsed: 63ms | User: 0ms | Sys: 31ms
RSS: 0.15GB | Peak: 0.15GB | Commit: 0.25GB | Faults: 37580
----- bun meta -----

0   00007FF768D4ED58
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???
7   ???
8   ???

Search GitHub issues https://bun.sh/issues or join in #windows channel in https://bun.sh/discord

thread 13180 panic: index out of bounds
???:?:?: 0x7ff76804c246 in ??? (bun.exe)
???:?:?: 0x7ff767e1b9ad in ??? (bun.exe)
???:?:?: 0x7ff767f090f8 in ??? (bun.exe)
???:?:?: 0x7ff7677912e0 in ??? (bun.exe)
???:?:?: 0x7ff767c1d829 in ??? (bun.exe)
???:?:?: 0x7ffacd24257c in ??? (KERNEL32.DLL)
???:?:?: 0x7fface6caa47 in ??? (ntdll.dll)
```

**Comment by m1abdullahh** [comment] 2024-04-06 11:13
Possibly related to #9796.

**Comment by Electroid** [comment] 2024-04-08 22:52
Duplicate of #10026

**Closed as not planned by Electroid** 2024-04-08 22:52 UTC
Labels: bug
