### ISSUE TITLE
Bun install

### ISSUE THREAD

**Issue by mannuramesh** [oven-sh/bun#11622] opened 2024-06-05 08:33 UTC
### How can we reproduce the crash?

This crash happened after, bun install of this github project, server dependencies https://github.com/MiladSadeghi/NoteBook

### Relevant log output

```shell
bun install v1.1.12 (43f0913c)
[43.37ms] migrated lockfile from package-lock.json
  📦 Installing [176/1586] ============================================================
Bun v1.1.12 (43f0913c) Windows x64
Args: "C:\Users\Manoj\.bun\bin\bun.exe" "install"
Features: extracted_packages(102) lockfile_migration_from_package_lock 
Elapsed: 29239ms | User: 2328ms | Sys: 18890ms
RSS: 0.34GB | Peak: 0.34GB | Commit: 0.49GB | Faults: 106957

panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:5156`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5156>): `processDependencyListItem`
- [`logger.zig:850`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/logger.zig#L850>): `allocPrint`
- [`install.zig:5937`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L5937>): `runTasks`
- [`install.zig:10695`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/install/install.zig#L10695>): `installPackages`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1450`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L1450>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/main.zig#L51>): `main`
- [`cell.rs:769`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/cell.rs#L769>): `core::cell::panic_already_borrowed`
- ??? at `0x1257d` in KERNEL32.DLL

**Comment by Jarred-Sumner** [comment] 2024-06-09 05:19
Duplicate of https://github.com/oven-sh/bun/issues/10565

**Comment by Jarred-Sumner** [comment] 2024-06-09 05:19
We are tracking this in https://github.com/oven-sh/bun/issues/10565, it will get fixed but please follow along there.

**Closed as not planned by Jarred-Sumner** 2024-06-09 05:19 UTC
Labels: bug, bun install
