### ISSUE TITLE
`bun install --global .` does not work

### ISSUE THREAD

**Issue by ivawzh** [oven-sh/bun#9405] opened 2024-03-14 06:07 UTC
### What version of Bun is running?

1.0.28+705638470

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

When try to install a local CLI lib with bun：

 ```sh
 bun install --force --global .
 ```

### What is the expected behavior?

Install successfully like running 

```sh
npm install --global --force .
```

### What do you see instead?

Got error:
```log
bun add v1.0.28 (70563847)

error: MissingPackageJSON
Bun could not find a package.json file.
```

### Additional information

Bun documentation does mention that local installation is supported. But no details on how to achieve it:

> [Non-npm dependencies](https://bun.sh/docs/cli/install#non-npm-dependencies)
Bun supports installing dependencies from Git, GitHub, and local or remotely-hosted tarballs. For complete documentation refer to [Package manager > Git, GitHub, and tarball dependencies](https://bun.sh/docs/cli/add).

**Comment by Electroid** [comment] 2024-03-14 16:28
Duplicate of #5682

**Closed as not planned by Electroid** 2024-03-14 16:28 UTC
Labels: bug, bun install
