### ISSUE TITLE
bun pack isn't a thing

### ISSUE THREAD

**Issue by Polygons1** [oven-sh/bun#8692] opened 2024-02-05 14:42 UTC
### What version of Bun is running?

1.0.26+c75e768a6

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

`bun pack` or any package that requires that

### What is the expected behavior?

everything to work

### What do you see instead?

script not found "pack" or `bun pack` exited with error code 1

**Comment by Electroid** [comment] 2024-02-05 16:20
Duplicate of #487

**Closed as not planned by Electroid** 2024-02-05 16:20 UTC
Labels: bug
