### ISSUE TITLE
[Web APIs] - Request clone causes body data to be lost

### ISSUE THREAD

**Issue by medz** [oven-sh/bun#4765] opened 2023-09-10 05:44 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
Bun.serve({
    fetch(request) {
        const data1 = request.clone().text();
        const data2 = request.clone().text();
        console.log(data1, data2)// Output "" empty string.
        // ...
    }
});
```

### What is the expected behavior?

https://developer.mozilla.org/en-US/docs/Web/API/Request/clone

The request object's stream should be copied correctly

### What do you see instead?

No errors, but wrong behavior.

**Comment by ceopaludetto** [comment] 2023-09-11 19:30
This can be related also https://github.com/jacob-ebey/bun-remix/issues/3. When I tried to run a simple remix app using bun as a server, every version that I tried greater than or equal 0.8.0 doesn't work. So I'm stucked into 0.7.3 right now

**Comment by ceopaludetto** [comment] 2023-09-11 19:37
A minimal remix repro https://codesandbox.io/p/sandbox/suspicious-cloud-7fxrwk

**Comment by hjonasson** [comment] 2023-09-13 01:27
I got here through @ceopaludetto 's comment on `bun-remix`. If it helps, I built the example from his reference issue in both Node and Bun and found that this repros, body is preserved in Node and not Bun.

**Comment by ceopaludetto** [comment] 2023-09-22 12:47
Seems to be fixed on Bun 1.0.2

**Comment by medz** [comment] 2023-09-23 12:27
> Seems to be fixed on Bun 1.0.2

No

**Comment by liz3** [comment] 2023-10-12 04:33
Ive worked on this and hve found the solution but the pr isnt quite ready yet, give me a day and there should be a pr for this.

**Comment by Electroid** [comment] 2023-10-27 21:44
Duplicate of #6348

**Closed as not planned by Electroid** 2023-10-27 21:44 UTC
Labels: bug, web-api
