### ISSUE TITLE
bun install --production crashes without package cache

### ISSUE THREAD

**Issue by shyim** [oven-sh/bun#7755] opened 2023-12-20 19:33 UTC
### What version of Bun is running?

1.0.18+36c316a24

### What steps can reproduce the bug?

- Delete bun cache `rm -rf ~/.bun`
- Create package.json like this
```
{
  "dependencies": {
    "left-pad": "^1.3.0"
  },
  "devDependencies": {
    "is-even": "^1.0.0"
  }
}
```

Run `bun install --production` instant 💥 

### What is the expected behavior?

Just works like without `--production`

### What do you see instead?

```
bun install v1.0.18 (36c316a2)
  🚚 is-even... error: IntegrityCheckFailed extracting tarball for is-even[62.00ms] done
```

### Additional information

related to #1952

**Comment by Electroid** [comment] 2024-02-05 17:21
Duplicate of #1590

**Closed as not planned by Electroid** 2024-02-05 17:21 UTC
Labels: bug, crash, bun install
