### ISSUE TITLE
`ServerResponse`: Cannot call a class constructor without |new|

### ISSUE THREAD

**Issue by jsoneaday** [oven-sh/bun#6667] opened 2023-10-23 17:33 UTC
### What version of Bun is running?

1.0.7

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

This is my code I'm running to test fastify

```
describe("ProfileRoute", () => {
  it("should return profile", async () => {
    console.log("start test");
    const response = await fastify.inject({
      method: "GET",
      url: "/profile?userName=foo",
    });
    console.log("got response", response);
    expect(response.statusCode).toEqual(200);
  });
});
```

### What is the expected behavior?

Test should succeed or at least complete

### What do you see instead?

```
622 | }
623 | var OriginalWriteHeadFn, OriginalImplicitHeadFn;
624 | 
625 | class ServerResponse extends Writable {
626 | 
627 |   constructor(c) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at ServerResponse (node:http:627:26)
      at new Response (/Users/davidchoi/Work/udemy/build-servers-with-bun-fastify/sec-3/lec-13/routes/end/routes/node_modules/light-my-request/lib/response.js:10:2)
      at /Users/davidchoi/Work/udemy/build-servers-with-bun-fastify/sec-3/lec-13/routes/end/routes/node_modules/light-my-request/index.js:62:18
      at new Promise (:1:20)
      at doInject (/Users/davidchoi/Work/udemy/build-servers-with-bun-fastify/sec-3/lec-13/routes/end/routes/node_modules/light-my-request/index.js:60:11)
      at /Users/davidchoi/Work/udemy/build-servers-with-bun-fastify/sec-3/lec-13/routes/end/routes/node_modules/light-my-request/index.js:137:20
      at /Users/davidchoi/Work/udemy/build-servers-with-bun-fastify/sec-3/lec-13/routes/end/routes/node_modules/light-my-request/index.js:83:8
      at processTicksAndRejections (:61:76)
✗ ProfileRoute > should return profile [9.08ms]

 0 pass
 9 fail
```

**Comment by Electroid** [comment] 2023-10-27 18:45
Duplicate of #4415

**Closed as not planned by Electroid** 2023-10-27 18:45 UTC
Labels: bug, node.js
