### ISSUE TITLE
bun install different version than yarn install

### ISSUE THREAD

**Issue by chj-damon** [oven-sh/bun#5074] opened 2023-09-12 09:52 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

checkout https://github.com/thundersdata-frontend/rn-template this repo
1. install dependencies using `yarn install`, check the `dag-map` in `node-modules`, you can see the version is `1.0.2`
2. install dependencies using `bun install`, check the `dag-map` in `node-modules`, you can see the version is `1.0.0`

### What is the expected behavior?

the version should remain the same as `1.0.2`

### What do you see instead?

the versions are different

**Comment by Glinkis** [comment] 2023-09-12 11:09
When moving from yarn to bun, the versions would need to be resolved from the existing lock file to not break behaviour. Especially for patch versions.

Yarn also have different lock file formats depending on the version.

**Comment by raimondlume** [comment] 2023-09-12 13:08
Duplicate of #1751

**Comment by chj-damon** [comment] 2023-09-13 01:37
well I don't think they are related. when I say `bun install`, I mean I've already deleted `node_modules` and `yarn.lock` and any other package manager configuration files. in this case, I'm not migrating from yarn to bun.

**Comment by Electroid** [comment] 2023-10-27 22:05
This has been fixed as of Bun v1.0.7. If you are still experiencing this issue, let us know and we'll re-open and investigate.

**Closed as completed by Electroid** 2023-10-27 22:05 UTC
Labels: bug
