### ISSUE TITLE
Using re2 with Bun seems to be challenging?

### ISSUE THREAD

**Issue by Zer0xxxx** [oven-sh/bun#12560] opened 2024-07-14 13:27 UTC
### What version of Bun is running?

1.1.20

### What platform is your computer?

Linux

### What steps can reproduce the bug?

`bun i re2`

Where:
    "re2": "^1.21.3",

The install process can be very long. (It is the case on my machine.)

And then, when running my tests with `bun test`:
> bun: symbol lookup error: ~/Project/node_modules/re2/build/Release/re2.node: undefined symbol: node_module_register

### What is the expected behavior?

It should just work, I guess

### What do you see instead?

:/

### Additional information

I also have Node v20.15.1 installed on my machine

**Comment by Anyoks** [comment] 2024-07-22 15:37
Same issue here

`bun: symbol lookup error: .../node_modules/re2/build/Release/re2.node: undefined symbol: node_module_register`

**Comment by xhyrom** [comment] 2024-08-07 15:51
Duplicate of https://github.com/oven-sh/bun/issues/4290

**Comment by 190n** [comment] 2024-09-03 17:23
Follow this in #4290

**Closed as not planned by 190n** 2024-09-03 17:23 UTC
Labels: bug, needs triage
