### ISSUE TITLE
Aarch64 builds

### ISSUE THREAD

**Issue by leap0x7b** [oven-sh/bun#418] opened 2022-07-08 07:33 UTC
Build Aarch64 builds for Aarch64-based SBCs, computers, and embedded devices like Raspberry Pi 3 and 4, Pine64-made devices like Pinebook and PinePhone, etc.

**Comment by moderation** [comment] 2022-07-08 16:08
Related https://github.com/Jarred-Sumner/bun/issues/75

**Comment by FinnRG** [comment] 2022-07-11 07:52
Duplicate of #75.

**Closed as completed by FinnRG** 2022-07-11 07:52 UTC
