### ISSUE TITLE
Bun crashes when running rspack with --bun or in container

### ISSUE THREAD

**Issue by lkuoch** [oven-sh/bun#14970] opened 2024-11-03 09:45 UTC
### How can we reproduce the crash?

1. Run `bun create @tanstack/router`
2. Select `rspack` as bundler
3. Run the project using `bun --bun run dev`
  - This causes a crash however `bun run dev` works
  - Running in container always fails with the error above

However, if I install node on my os, it works

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on linux x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`BunProcess.cpp:2646`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/BunProcess.cpp#L2646>): `Bun::jsFunctionDrainMicrotaskQueue`
- *2 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `llint_call_javascript`

Features: Bun.stdin, http\_server, jsc, transpiler\_cache, tsconfig

**Comment by heimskr** [comment] 2024-11-05 22:56
This appears to be fixed in the [ben/fix-node-napi-tests branch](https://github.com/oven-sh/bun/tree/ben/fix-node-napi-tests). Please try again using an artifact from [Buildkite](https://buildkite.com/bun/bun/builds/5658). For @lkuoch and anyone else using Linux on x86_64, the relevant artifact you want is [here](https://buildkite.com/organizations/bun/pipelines/bun/builds/5658/jobs/0192fe3e-5af3-47cb-8a32-ec7ac6f9c2bb/artifacts/0192fe4e-d2ce-4b83-8a46-9b9fd93e9d20). Please let me know if this resolves the issue.

**Comment by 190n** [comment] 2024-11-05 23:09
We're tracking rspack/rsbuild support in #11628, so if you do run into more crashes even using the build from CI, leave a comment on that issue instead.

**Comment by 190n** [comment] 2024-11-05 23:09
Duplicate of #11628

**Closed as not planned by 190n** 2024-11-05 23:09 UTC
Labels: napi, crash, linux
