### ISSUE TITLE
Suppor for aarch64 for musl linux

### ISSUE THREAD

**Issue by 1412031** [oven-sh/bun#1243] opened 2022-09-16 18:16 UTC
Trying to evaluate the framework on an Apple silicon macbook running alpinelinux with the linux-asahi kernel.

I'm getting this error:
`Error relocating /home/user/.bun/bin/bun: __res_init: symbol not found
Error relocating /home/user/.bun/bin/bun: fcntl64: symbol not found`

In case there isn't any support for the target consider handling it in the installer and aborting the installation altogether.

**Comment by catdevnull** [comment] 2023-03-11 19:55
related to #918

**Comment by Electroid** [comment] 2023-10-25 18:46
Duplicate of #918

**Closed as not planned by Electroid** 2023-10-25 18:46 UTC
