### ISSUE TITLE
Child process interaction becomes super slow

### ISSUE THREAD

**Issue by davidgomes** [oven-sh/bun#12704] opened 2024-07-21 10:49 UTC
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

```
const prompts = require("prompts");
const { execSync } = require("child_process");

async function handler() {
  const response = await prompts({
    type: "text",
    name: "name",
    message: "What is your name?",
  });

  execSync("npx vercel deploy", { stdio: "inherit" });
}

handler();
```

`bun add vercel prompts`

### What is the expected behavior?

The sub process stdin interaction should be smooth as if we're using Node. But, instead, it is super slow.

### What do you see instead?

The subprocess's stdin interaction is very slow.

**Comment by davidgomes** [comment] 2024-08-09 05:31
@paperdave this is a duplicate of #9855.

**Comment by Jarred-Sumner** [comment] 2024-08-09 05:52
Duplicate of #9855

**Closed as not planned** 2024-08-09 05:52 UTC
Labels: bug, atw
