### ISSUE TITLE
Segmentation fault on sharp

### ISSUE THREAD

**Issue by KrysKruk** [oven-sh/bun#11771] opened 2024-06-11 07:26 UTC
### How can we reproduce the crash?

```typescript
async function photoToPlaceholder(photo: ArrayBuffer) {
  const { data, info } = await sharp(photo)
    .resize(100, 100, { fit: "inside" })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
}
```

### Stack Trace (bun.report)

Bun v1.1.12 ([`43f0913`](<https://github.com/oven-sh/bun/tree/43f0913c3875cbf260c60868268adc5953b09a80>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`StringImpl.h:1154`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/wtf/text/StringImpl.h#L1154>): `Bun::formatStackTrace`
- [`ZigGlobalObject.cpp:554`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/ZigGlobalObject.cpp#L554>): `computeErrorInfoWithoutPrepareStackTrace`
- [`ZigGlobalObject.cpp:649`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/src/bun.js/bindings/ZigGlobalObject.cpp#L649>): `computeErrorInfo`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80//build/bun/bun-webkit/include/wtf/Function.h#L53>): `WTF::Detail::CallableWrapper<WTF::String (...)(...), WTF::String, JSC::VM&, WTF::Vector<JSC::StackFrame, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, unsigned int&, unsigned int&, WTF::String&, JSC::JSObject*>::call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::ErrorInstance::computeErrorInfo`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::Heap::runEndPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `JSC::Heap::runCurrentPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/43f0913c3875cbf260c60868268adc5953b09a80/ld-temp.o#L0>): `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`

**Comment by Jarred-Sumner** [comment] 2024-06-11 07:34
Is this using alpine linux?

**Comment by Jarred-Sumner** [comment] 2024-06-11 07:36
Unfortunately, this isn't enough to reproduce the issue. Can you provide the image?

**Comment by KrysKruk** [comment] 2024-06-11 07:41
I'm sorry, after posting the issue I tried to reproduce it and I cannot do it easily.

Here is a Dockerfile:
```dockerfile
FROM oven/bun:1
WORKDIR /usr/src/app
ENV NODE_ENV=production

RUN bun i sharp@^0.33.4
COPY ./dist/index.js ./index.js
COPY ./dist/index.js.map ./index.js.map

USER bun
ENTRYPOINT ["bun", "--bun", "run", "index.js"]
```

Works on Mac, fails on Linux. There are a lot of concurrency and http calls but I can confirm it definitely faults at the code snippet I've posted.

Also tried on v1.1.10 and no changes.

**Comment by KrysKruk** [comment] 2024-06-11 07:57
I tried to prepare a minimal code for reproduction and I cannot. I will try to spend some more time on it. It happens every time in my app though. Should I close the issue for now?

**Comment by 7f8ddd** [comment] 2024-06-11 12:05
> No let’s keep it open. It’s entirely possible the condition causing this to happen is necessary for sharp runs, but the underlying cause is much earlier. Like if an exception is thrown, and then another exception is thrown. Or the machine is a lot busier before the sharp invocation and then sharp runs and it’s almost out of ram

https://github.com/oven-sh/bun/issues/8400 this is still an issue btw, not sure if it could be related.

**Comment by Jarred-Sumner** [comment] 2024-06-24 03:07
I'll close as a duplicate of https://github.com/oven-sh/bun/issues/11568, as I was unable to reproduce and we are tracking this in #11568

**Comment by Jarred-Sumner** [comment] 2024-06-24 03:07
Duplicate of https://github.com/oven-sh/bun/issues/11568

**Closed as not planned by Jarred-Sumner** 2024-06-24 03:07 UTC
Labels: crash
