### ISSUE TITLE
Cannot watch files in `/mnt` directory on WSL

### ISSUE THREAD

**Issue by reserved-word** [oven-sh/bun#4335] opened 2023-08-25 20:05 UTC
### What version of Bun is running?

0.8.1+16b4bf341acc0f4804f0b6bdf5298c180cd00366

### What platform is your computer?

Microsoft Windows NT 10.0.22621.0 x64

### What steps can reproduce the bug?

1. Create `index.ts` file in` /mnt/c/Users/User/something/` directory
2. `cd /mnt/c/Users/User/something/` (in WSL console)
3. `bun run --watch index.ts` (in WSL console)
4. Modify `index.ts` (change console.log text or something)

### What is the expected behavior?

index.ts restarted

### What do you see instead?

Nothing happened

**Comment by infrahead** [comment] 2023-08-26 15:37
The issue is that the Plan 9 server in WSL 2 does not support file watching on Windows files. The workaround is to place your files into the Linux file system (plus you'll get a performance boost).

see https://github.com/microsoft/WSL/issues/4739

**Comment by ravinsharma7** [comment] 2023-09-11 18:43
Probably nice to put in the docs somewhere. I was wondering why the example in the docs that I was trying doesn't work at all.

**Comment by angelhdzmultimedia** [comment] 2023-09-14 20:19
> The issue is that the Plan 9 server in WSL 2 does not support file watching on Windows files. The workaround is to place your files into the Linux file system (plus you'll get a performance boost).
> 
> see [microsoft/WSL#4739](https://github.com/microsoft/WSL/issues/4739)

Thank you! Solved for me.

**Comment by brunolm** [comment] 2023-10-02 19:33
I can confirm it doesn't work on Windows folders.

I tried the following example provided in the official documentation: https://bun.sh/docs/runtime/hot#:~:text=In%20this%20example%2C%20Bun%20is

```ts
import { serve } from "bun";
console.log("I restarted at:", Date.now());

serve({
  port: 4003,

  fetch(request) {
    return new Response("Sup");
  },
});
```

The page makes no mention of `Windows`, `WSL`, `folder`, `dir`, `issue`, and it doesn't have any sort of a warning for Windows users.

**For any Windows users reading this, currently** you need to place your projects somewhere in the folder `\\wsl$`, I choose to place my projects in `\\wsl.localhost\Ubuntu\home\USER\dev`.

**Comment by Electroid** [comment] 2024-02-05 18:47
Duplicate of #5841

**Comment by Electroid** [comment] 2024-02-05 18:47
We fill fix this so it works on `/mnt`

**Closed as not planned by Electroid** 2024-02-05 18:47 UTC
Labels: bug
