### ISSUE TITLE
Don't  resolve node_modules correctly

### ISSUE THREAD

**Issue by aslan0402** [oven-sh/bun#9163] opened 2024-02-29 06:42 UTC
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

```
 "dependencies": {
    "@kyvg/vue3-notification": "^3.1.3",
    "@mdi/font": "5.9.55",
    "axios": "^1.6.6",
    "lodash-es": "^4.17.21",
    "pinia": "^2.1.7",
    "ramda": "^0.29.1",
    "register-service-worker": "^1.7.2",
    "single-spa-vue": "^3.0.0",
    "vue": "^3.4.20",
    "vue-router": "^4.2.5",
    "vuetify": "^3.5.2"
  },
  "devDependencies": {
    "@types/lodash-es": "^4.17.12",
    "@types/ramda": "^0.29.10",
    "@typescript-eslint/eslint-plugin": "^6.18.1",
    "@vitejs/plugin-vue": "^5.0.4",
    "@vitest/coverage-istanbul": "^1.2.2",
    "@vue/cli-plugin-eslint": "^5.0.8",
    "@vue/cli-plugin-router": "^5.0.8",
    "@vue/cli-plugin-typescript": "^5.0.8",
    "@vue/cli-service": "^5.0.8",
    "@vue/test-utils": "^2.4.4",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-config-standard-with-typescript": "^43.0.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-n": "^16.6.2",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-vue": "^9.20.0",
    "jsdom": "^24.0.0",
    "prettier": "^3.2.1",
    "sass": "^1.69.5",
    "sass-loader": "^13.3.2",
    "typescript": "^5.2.2",
    "vite": "^5.1.3",
    "vite-tsconfig-paths": "^4.3.1",
    "vitest": "^1.2.2",
    "vue-cli-plugin-single-spa": "^3.3.0",
    "vue-cli-plugin-vuetify": "~2.5.8"
  }
  ```
  Have these deps. With nodejs I'm able to build and run the project, but with bun getting an error.

### What is the expected behavior?

Run/build the project without error.

### What do you see instead?

```
$ vue-cli-service build
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


✔  Building for production...
 ERROR  Error: Cannot find module 'ajv/dist/compile/codegen'
        Require stack:
        - /Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/definitions/typeof.js
        - /Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/keywords/typeof.js
        - /Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/keywords/index.js
        - /Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/index.js
        - /Users/work/proj/web-main-vue3/node_modules/schema-utils/dist/validate.js
        - /Users/work/proj/web-main-vue3/node_modules/schema-utils/dist/index.js
        - /Users/work/proj/web-main-vue3/node_modules/eslint-webpack-plugin/dist/options.js
        - /Users/work/proj/web-main-vue3/node_modules/eslint-webpack-plugin/dist/index.js
        - /Users/work/proj/web-main-vue3/node_modules/@vue/cli-plugin-eslint/index.js
        - /Users/work/proj/web-main-vue3/node_modules/@vue/cli-service/lib/Service.js
        - /Users/work/proj/web-main-vue3/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- /Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/definitions/typeof.js
- /Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/keywords/typeof.js
- /Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/keywords/index.js
- /Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/index.js
- /Users/work/proj/web-main-vue3/node_modules/schema-utils/dist/validate.js
- /Users/work/proj/web-main-vue3/node_modules/schema-utils/dist/index.js
- /Users/work/proj/web-main-vue3/node_modules/eslint-webpack-plugin/dist/options.js
- /Users/work/proj/web-main-vue3/node_modules/eslint-webpack-plugin/dist/index.js
- /Users/work/proj/web-main-vue3/node_modules/@vue/cli-plugin-eslint/index.js
- /Users/work/proj/web-main-vue3/node_modules/@vue/cli-service/lib/Service.js
- /Users/work/proj/web-main-vue3/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/work/proj/web-main-vue3/node_modules/ajv-keywords/dist/definitions/typeof.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
error: script "build" exited with code 1
```

**Comment by Jarred-Sumner** [comment] 2024-03-01 06:50
Duplicate of https://github.com/oven-sh/bun/issues/8201

**Closed as completed by Jarred-Sumner** 2024-03-01 06:50 UTC
Labels: bug
