### ISSUE TITLE
Running Playwright does not work as expected

### ISSUE THREAD

**Issue by B3none** [oven-sh/bun#4751] opened 2023-09-10 01:38 UTC
### What version of Bun is running?

`1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983`

I also tested it on: `1.0.0+ffe4f561a3af53b9f5a41c182de55d7199b5d692`

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

I've uploaded the code I used to run the test locally: https://github.com/B3none/bun-playwright-test

### What is the expected behavior?

It should open the headless browser page in playwright without erroring.

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/24966460/e4106b48-1dd4-4007-bf79-395999592dd2)

```
$ bun src/index.ts
47 |     const e = new _errors.TimeoutError(error.error.message);
48 |     e.stack = error.error.stack || '';
49 |     return e;
50 |   }
51 |   const e = new Error(error.error.message);
52 |   e.stack = error.error.stack || '';
                ^
TypeError: launch: launch: undefined is not an object (evaluating 'pipeRead.on')
=========================== logs ===========================
<launching> /home/b3none/.cache/ms-playwright/chromium-1076/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-a1EZ12 --remote-debugging-pipe --no-startup-window
<launched> pid=124108
============================================================
      at /home/b3none/github/b3none/bun-playwright-test/node_modules/playwright-core/lib/protocol/serializers.js:52:12
error: script "start" exited with code 1 (SIGHUP)
b3none@localhost:~/github/b3none/bun-playwright-test$ 
```

Instead there is an error from the cli.

### Additional information

It seems to be related to `NodeJS.ReadableStream` but I'm not really sure what's erroring because I can't see the stack trace.

https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/pipeTransport.ts#L23

**Comment by angelsbv** [comment] 2023-09-10 16:59
Same issue here. It also happens with firefox and webkit.

**Comment by Hebilicious** [comment] 2023-09-11 11:08
Duplicate https://github.com/oven-sh/bun/issues/2492

**Comment by Electroid** [comment] 2023-10-27 20:49
This is a duplicate of https://github.com/oven-sh/bun/issues/2492, but since a lot of people have upvoted this, we'll keep it open until it's fixed.

**Comment by nektro** [comment] 2024-01-16 22:30
#2492 has now been resolved

**Closed as completed by nektro** 2024-01-16 22:30 UTC
Labels: bug
