### ISSUE TITLE
TypeError code: "ERR_INVALID_ARG_TYPE" with very simple script

### ISSUE THREAD

**Issue by woxxo** [oven-sh/bun#6880] opened 2023-11-03 18:29 UTC
### What version of Bun is running?

1.0.7+b0393fba6200d8573f3433fb0af258a0e33ac157

### What platform is your computer?

Linux vm79243 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What steps can reproduce the bug?

```javascript
const server = Bun.serve({
  port: 8008,
  fetch(req, srv) {
    console.log(req, srv);
    return new Response('Bun!\n' + new Date().getMilliseconds());
  },
});
console.log(`Listening on http://localhost:${server.port} ...`);
```

### What is the expected behavior?

~/js> bun server-bun.js
Listening on http://localhost:8008 ...

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/147440887/d5166623-d480-4f82-af43-cc7582f6f385)

### Additional information

The same script is working as expected with the same Bun version on this system: 
Linux 6.5.4-1-default #1 SMP PREEMPT_DYNAMIC Wed Sep 20 05:07:04 UTC 2023 (fdd7e9e) x86_64 x86_64 x86_64 GNU/Linux

**Comment by Jarred-Sumner** [comment] 2023-11-07 03:55
Duplicate of #3312

**Closed as not planned by Jarred-Sumner** 2023-11-07 03:55 UTC
Labels: bug
