### ISSUE TITLE
Request: make official AWS Lambda layer "more official" & support SSR frameworks

### ISSUE THREAD

**Issue by gitblit** [oven-sh/bun#4330] opened 2023-08-25 14:31 UTC
### What is the problem this feature would solve?

There is an open docs ticket #2712 for documenting the "official" Lambda layer. The Lambda layer seems like an excellent starting point, but I think there are more opportunities to grow it.

Ultimately, I'd like to be able to build & deploy a Bun+SvelteKit app as a Lambda function. I imagine there are other folks who would like to build & deploy a Bun+Next app, Bun+Nuxt, app, and so on.

I'm also eager to see what Oven hosting looks like in the future, but for my current requirements, I have to be in AWS for reasons.

### What is the feature you are proposing to solve the problem?

I'd like to see the lambda layer improved or a lambda docker container base created. I'd like to see integrations & guides outlining how to use it.

### What alternatives have you considered?

I have considered a Docker container deployed to AppSail, Fargate, etc, but these are lightweight apps and I prefer a more dynamic, lightweight compute solution.

**Comment by Electroid** [comment] 2023-10-26 22:42
Duplicate of #2712

**Closed as not planned by Electroid** 2023-10-26 22:42 UTC
Labels: enhancement
