### ISSUE TITLE
file.watch((change)=>{})

### ISSUE THREAD

**Issue by arreehm** [oven-sh/bun#2306] opened 2023-03-04 20:14 UTC
### What is the problem this feature would solve?

Problem of reacting to file change...

### What is the feature you are proposing to solve the problem?

Just watch on files

### What alternatives have you considered?

Nodes file system API

**Comment by gaurishhs** [comment] 2023-03-05 16:05
Duplicate of https://github.com/oven-sh/bun/issues/832

**Comment by e3dio** [comment] 2023-05-23 22:09
I'd request a built-in debounce option so don't need to manually add debounce like is needed for node:fs.watch(): `Bun.watch(fileOrDirectory, { debounce: 100 })`

```js
const debounce = (wait, fn) => {
   let timeout;
   return (...args) => {
      clearTimeout(timeout);
      timeout = setTimeout(() => fn(...args), wait);
   };
};

fs.watch(file, debounce(200, (event, file) => {
   // do something with file
   // runs 200ms after the last change event
}));

```

**Comment by e3dio** [comment] 2023-05-23 22:27
If anyone wants a temporary solution for Bun, I am using this to watch files currently, uses polling and only emits event on file size change

```js
export const watch = (file, fn) => {
   let size = Bun.file(file).size;
   setInterval(() => {
      const newSize = Bun.file(file).size;
      if (newSize != size) {
         console.log('File change:', file);
         size = newSize;
         fn();
      };
   }, 1000);
};
```

**Closed as not planned** 2023-05-30 23:53 UTC
Labels: enhancement
