### ISSUE TITLE
Bun has crashed. This indicates a bug in Bun, not your code.

### ISSUE THREAD

**Issue by ProMehedi** [oven-sh/bun#11601] opened 2024-06-04 15:30 UTC
### How can we reproduce the crash?

bun install
[0.00ms] ".env"
bun install v1.1.10 (5102a944)
warn: incorrect peer dependency "eslint@9.4.0"

warn: incorrect peer dependency "eslint@9.4.0"

warn: incorrect peer dependency "eslint@9.4.0"

warn: incorrect peer dependency "eslint@9.4.0"
  🚚 @babel/traverse... ============================================================
Bun v1.1.10 (5102a944) Windows x64
Args: "C:\Users\Mehedi\.bun\bin\bun.exe" "install"
Features: dotenv extracted_packages(390) 
Elapsed: 13422ms | User: 125ms | Sys: 265ms
panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:5119`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5119>): `processDependencyListItem`
- [`install.zig:5177`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5177>): `processDependencyList`
- [`install.zig:5895`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5895>): `runTasks`
- [`install.zig:10457`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L10457>): `isDone`
- [`event_loop.zig:1935`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/bun.js/event_loop.zig#L1935>): `tick`
- [`filter_run.zig:430`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli/filter_run.zig#L430>): `install`
- [`cli.zig:1461`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L1461>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/src/startup/exe_common.inl#L78>): `invoke_main`

**Comment by Electroid** [comment] 2024-06-04 22:23
Could you share your `package.json`?

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:44
Duplicate of https://github.com/oven-sh/bun/issues/10565

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:44
To track this issue, please follow along in https://github.com/oven-sh/bun/issues/10565

**Closed as not planned by Jarred-Sumner** 2024-06-04 22:44 UTC
Labels: needs repro, crash, bun install
