### ISSUE TITLE
Loading i2c.node module crashes bun with undefined symbol: _ZNK2v85Value8ToStringENS_5LocalINS_7ContextEEE

### ISSUE THREAD

**Issue by SchizoDuckie** [oven-sh/bun#14447] opened 2024-10-09 21:55 UTC
### What version of Bun is running?

1.1.30+7996d06b8

### What platform is your computer?

Linux 6.6.31+rpt-rpi-v8 aarch64 unknown

### What steps can reproduce the bug?

- install `bun@latest`, `node@22.9.0` and `node-gyp v10.2.0` on a Raspi Zero W2 on Debian Bookworm
- start a new project
- `bun install i2c `
- `cd node_modules/i2c/node_modules`
- `curl -L https://github.com/oc-soft/npm-nan/archive/refs/heads/main.zip -O && unzip main.zip`
- `mv nan _nan && mv npm-nan-main nan && cd ..`
- `node-gyp configure && node-gyp build`
- Now the `i2c.node` is built, prebuilt with the .node and .o for your debugging pleasure: [i2c.zip](https://github.com/user-attachments/files/17319187/i2c.node.zip)
- Execute the adafruit-pca9685 example code: 
 ```javascript
    I2C = require('i2c'),
    let meCrash = new I2C(0x40, { device:  '/dev/i2c-1' });
```
- *you may need to repeat this procedure for the `sleep` dependency if you want to repeat this process, but that module didnt crash for me (yet).*

I confirmed by running it with `node@22.9.0` that this is a bun bug. This same module is loaded by node properly, which also confirms that it's not a problem with the ifdefs in the compiled module
(The exception there is expected as my test rig currently has no i2c interface soldered to it) 

![Image](https://github.com/user-attachments/assets/407abf52-7360-4e67-98b6-5bad61de5e6e)

### What is the expected behavior?

There is no symbol lookup error.

### What do you see instead?

`bun: symbol lookup error: /home/pi/stairleds/node/node_modules/i2c/build/Release/i2c.node: undefined symbol: _ZNK2v85Value8ToStringENS_5LocalINS_7ContextEEE`

### Additional information

I feel like living on the edge and am trying to use Bun to run on my new Raspi Zero W 2 that upgrades my Stairleds project, since I feel this is one of the most rabbit-holey things you can try for a javascript stack, interface with hardware.

The stairleds project interfaces with native [I2C](https://www.npmjs.com/package/i2c) bindings (a node-gyp built .node module), which required some [voodoo](https://github.com/nodejs/nan/pull/976) to get working (read: raw-dog somebody's yet-unmerged PR) , which in turn uses the [node-sleep](https://www.npmjs.com/package/sleep) native bindings for usleep.

After confirming it works by recompiling the node-gyp modules using `node@22.9.0` and said node-gyp nvm hack, bun crashes with an awesome exception that warrants a bug status

**Comment by 190n** [comment] 2024-10-10 00:26
Thanks for the report -- this is because i2c uses some V8 APIs that we don't support yet. You can track our progress in #4290, and I've added i2c to the list of packages affected.

**Comment by 190n** [comment] 2024-10-10 00:27
Duplicate of #4290

**Closed as not planned by 190n** 2024-10-10 00:27 UTC
Labels: bug
