### ISSUE TITLE
Impossible to use

### ISSUE THREAD

**Issue by CarlosNunezMX** [oven-sh/bun#655] opened 2022-07-13 02:13 UTC
### Version

0.1.3

### Platform

Linux Hokimasu 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

OS Specs
Linux Distribution: Linux Lite
Kernel: 5.15.0-33-generic
And i tryed in Chrome OS linux enviroment

Downloaded by script and from releases page

### How often does it reproduce? Is there a required condition?

It's repeat's all times, with any command, even if i check the help the get out the error.

### What is the expected behavior?

So, the help text, and run program, and any command

### What do you see instead?

Is not possible to do nothing
![image](https://user-images.githubusercontent.com/25675386/178636250-3c59d1b3-3079-4887-ab39-82d7a6eaa82d.png)

**Comment by SamuraiCrow** [comment] 2022-07-13 02:28
It also happens on an up-to-date Manjaro install on a 3rd generation i7 CPU with 32 GB of DDR3.

**Comment by sno2** [comment] 2022-07-13 04:26
Most likely duplicate of https://github.com/oven-sh/bun/issues/67

**Comment by SamuraiCrow** [comment] 2022-07-13 05:02
Probably.  Is there a way to work around it?  I've heard of a patch that intercepts AVX2 in favor of an SSE variant but I don't know how efficient it is.  Is recompiling with different flags an option?

**Comment by sno2** [comment] 2022-07-13 05:03
@SamuraiCrow See the last comment on the linked issue.

**Comment by SamuraiCrow** [comment] 2022-07-13 05:15
Thanks!  I'll try that.

**Comment by FinnRG** [comment] 2022-07-13 09:28
Duplicate of #67.

**Closed as completed by FinnRG** 2022-07-13 09:28 UTC
Labels: bug, needs repro
