### ISSUE TITLE
toHaveBeenCalledWith function

### ISSUE THREAD

**Issue by Guilhrib** [oven-sh/bun#4883] opened 2023-09-11 04:55 UTC
### What is the problem this feature would solve?

I can only verify with the dependency have been called but idk with the crrect values are being passed,

### What is the feature you are proposing to solve the problem?

It would be nice to have the "toHaveBeenCalledWith" function to write more accurated tests

**Comment by simylein** [comment] 2023-09-11 05:04
This is a duplicate of #4365. Please search the issues before submitting new ones. Can someone close this?

**Comment by Guilhrib** [comment] 2023-09-11 05:10
Yeah of course, ty

Em seg., 11 de set. de 2023 às 02:05, simylein ***@***.***>
escreveu:

**Closed as completed** 2023-09-11 05:11 UTC
Labels: enhancement
