### ISSUE TITLE
url.fileURLToPath(import.meta.url) says Argument must be a URL

### ISSUE THREAD

**Issue by robogeek** [oven-sh/bun#1070] opened 2022-08-13 17:39 UTC
### Version

0.1.8

### Platform

Linux davidpc 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

Execute the following code on Node.js and on Bun

```js
import { fileURLToPath, pathToFileURL } from 'node:url';
import * as path from 'path';

console.log(import.meta.url);
console.log(fileURLToPath(import.meta.url));

const __asciidoctorDistDir__ = path.dirname(fileURLToPath(import.meta.url))
console.log(__asciidoctorDistDir__);
```

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

This is common code to compute the filesystem location of the application so it can refer to local files.

The expected behavior is something like this Node.js output:

```
$ node -v
v18.6.0

$ node filepath.mjs 
file:///home/david/Projects/akasharender/akashacms-perftest/bench/filepath.mjs
/home/david/Projects/akasharender/akashacms-perftest/bench/filepath.mjs
/home/david/Projects/akasharender/akashacms-perftest/bench
```

The first line prints `import.meta.url` and shows that it is a legitimate `file:` URL.

### What do you see instead?

Bun is incorrectly saying that the URL is not a URL.

```
$ bun -v
0.1.8

$ bun filepath.mjs 
file:///home/david/Projects/akasharender/akashacms-perftest/bench/filepath.mjs
1 | 
2 | import { fileURLToPath, pathToFileURL } from 'node:url';
3 | import * as path from 'path';
4 | 
5 | console.log(import.meta.url);
6 | console.log(fileURLToPath(import.meta.url));
               ^
TypeError: Argument must be a URL
      at /home/david/Projects/akasharender/akashacms-perftest/bench/filepath.mjs:6:12
```

### Additional information

This was uncovered while debugging a failure to use the Asciidoctor package on Bun.  Asciidoctor is like Markdown, but different.  That package is transliterated from Ruby code, and relies on the Opal framework.

A corresponding issue has been filed against Opal in relation to getting Asciidoctor to work on Bun: 
 https://github.com/Mogztter/opal-node-runtime/issues/65

**Comment by robogeek** [comment] 2022-08-13 17:41
Duplicate of: https://github.com/oven-sh/bun/issues/1069

**Comment by xhyrom** [comment] 2022-08-13 17:46
Duplicate of #1069

**Closed as completed by xhyrom** 2022-08-13 17:46 UTC
Labels: bug, needs repro
