### ISSUE TITLE
[WINDOWS ONLY] "bunx --bun npm-check-updates -i" does not detect keystrokes

### ISSUE THREAD

**Issue by cpakken** [oven-sh/bun#10195] opened 2024-04-12 02:53 UTC
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Make sure you have package.json with outdated packages

```json
{
  "name": "vitest",
  "module": "index.ts",
  "devDependencies": {
    "vite": "4",
    "vitest": "1.4.0"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "type": "module"
}
```
```bash
bunx npm-check-updates -i #works without --bun
bunx --bun npm-check-updates -i #no keystrokes detected with --bun
```

with --bun, does not detect ctrl-c, and accept up down arrow keys 

Tested in WSL and works fine with --bun

### Additional information

Tested in WSL and works fine with --bun

**Comment by Electroid** [comment] 2024-04-12 15:54
Duplicate of #10217

**Closed as not planned by Electroid** 2024-04-12 15:54 UTC
Labels: bug
