### ISSUE TITLE
Bug on Prompts js Package with Bun on Windows

### ISSUE THREAD

**Issue by on1force** [oven-sh/bun#10029] opened 2024-04-06 20:00 UTC
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 (x64)

### What steps can reproduce the bug?

1. Install [prompts js](https://www.npmjs.com/package/prompts) package with bun i
2. Install the [type ](https://www.npmjs.com/package/@types/prompts)
3. Add to project
4. try "prompting" something with the type "select" (or anything that require interaction with the arrow keys)

### What is the expected behavior?

User can choose options with arrow keys

### What do you see instead?

Selection not responding with arrow keys

### Additional information

I tried this with ts-node and it's working fine, package have full ts support too.. It's only not working when I use bun

**Comment by Electroid** [comment] 2024-04-09 00:30
Duplicate of #10087

**Closed as not planned by Electroid** 2024-04-09 00:30 UTC
Labels: bug
