### ISSUE TITLE
Add XDG support for the cache dir

### ISSUE THREAD

**Issue by RaafatTurki** [oven-sh/bun#696] opened 2022-07-14 04:46 UTC
### What is the problem this feature will solve?

the XDG spec is already implemented pretty nicely in this project, however I've noticed the `cache` dir `~/.bun/install/cache/` was neglected in that regard (I think it can be configure but having it work out of the box is better).

adding XDG support to the cache dir is a good idea because:
- makes wiping cache easier (deleting the cache dir will delete buns cache excluding its configs)
- unclutters the $HOME directory

### What is the feature you are proposing to solve the problem?

Implementing this is pretty simple, instead of writing cache files into `~/.bun/install/cache/` a simple series of checks is performed to pick the right path with backward compatibility in mind ofc:
- if `~/.bun/` exists use it
- else if environment variable `XDG_CACHE_HOME` is set use `$XDG_CACHE_HOME/bun/`
- else use `XDG_CACHE_HOME`s default value which is `~/.cache/bun/`

If this gets implemented:
- Current users can move their `~/.bun/install/cache` to `XDG_CACHE_HOME` (default is `~/.cache`)
- New users will have to do nothing and it will just work as it should

### What alternatives have you considered?

I don't think there is, Most of unix software supports this for a reason, I think bun should definitely have it.

**Comment by Electroid** [comment] 2023-10-24 22:32
Duplicate of #1678

**Closed as not planned by Electroid** 2023-10-24 22:32 UTC
Labels: enhancement, bun install
