### ISSUE TITLE
Invalid cache key "\wsl.localhost"

### ISSUE THREAD

**Issue by xpvishal1d** [oven-sh/bun#10648] opened 2024-04-29 15:43 UTC
### Stack Trace (bun.report)

Bun v1.1.6 ([#10596](https://github.com/oven-sh/bun/pull/10596)) on windows x86_64 [RunCommand]

**panic**: Internal Assertion Failure: Invalid cache key "\\wsl.localhost\"
See Resolver.assertValidCacheKey for details.

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`array_list.zig:630`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/deps/zig/lib/std/array_list.zig#L630): `initCapacity`
- [`resolver.zig:1628`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/resolver/resolver.zig#L1628): `assertValidCacheKey`
- [`resolver.zig:2550`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/resolver/resolver.zig#L2550): `readDirInfo`
- [`javascript.zig:1398`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun.js/javascript.zig#L1398): `init`
- [`bun_js.zig:170`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/bun_js.zig#L170): `boot`
- [`run_command.zig:1401`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/run_command.zig#L1401): `exec`
- [`cli.zig:1483`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1483): `start`
- [`cli.zig:56`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L56): `start`
- [`main.zig:52`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/main.zig#L52): `main`

**Comment by Jarred-Sumner** [comment] 2024-05-16 10:39
Duplicate of https://github.com/oven-sh/bun/issues/10281

**Comment by Jarred-Sumner** [comment] 2024-05-16 10:40
Closing as duplicate

We will fix this, but please follow along in #10281

**Closed as not planned by Jarred-Sumner** 2024-05-16 10:40 UTC
Labels: bug, crash, windows

**Comment by Jarred-Sumner** [comment] 2024-05-21 20:53
Fixed by @paperdave in https://github.com/oven-sh/bun/pull/11155

This will be part of the Bun v1.1.9 release.
