### ISSUE TITLE
[Linux ARM64] readdir OOM with Bun running inside Docker container on invalid path

### ISSUE THREAD

**Issue by saturna** [oven-sh/bun#5820] opened 2023-09-20 18:02 UTC
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Using `oven/bun:latest` image and expressjs framework when using readdir on a path that doesn't exist (I've tried both with bound volumes and also with COPY local directories) the app freezes and runs out of memory.
This works just fine if not running inside Docker.

### What is the expected behavior?

Correctly throws an exception denoting that directory doesn't exist.

### What do you see instead?

Bun app running inside Docker doesn't respond to a request, runs out of memory and crashes.

**Comment by Electroid** [comment] 2023-09-20 18:03
Mind sharing a snippet of your code?

**Comment by saturna** [comment] 2023-09-20 18:47
```js
import {readdir} from 'node:fs';

app.get('/files/:path(*)', async (req: Request, res: Response) => {

  try {
    const basePath = '${myBaseDir}/${req.params.path}';
    console.log('Reading files...');
    const allFiles = await fs.readdirSync(basePath); // Hangs here
    console.log('Done Reading files.');// never gets printed out
    res.json(<payload>);
 catch (e: any) {
   res.status(500).send(e.message);
 }
app.listen(3030, '0.0.0.0', () => { // or localhost if running outside of docker
  console.log('Server is running...');
});
```

Dockerfile:
```
FROM oven/bun:latest

ENV NODE_ENV=production
COPY build/index.js /app/  -> using bun bundler with target bun (also tried node)
WORKDIR /app
...
ENTRYPOINT ["bun"]
CMD ["run", "index.js"]
```

Then command to run is:
```
docker run -it --rm --init -v `pwd`/base_dir:/app/base_dir -p 3030:3030 <my_bun_image>
```

Also worth to note that same exact code works when switching to node and I get exception:
`ENOENT: no such file or directory, scandir <dir>` which I expected with Bun.

**Comment by tarruda** [comment] 2023-09-26 01:39
Experiencing something similar when deploying an empty next.js app with bun on an arm64 k8s cluster. `kubectl get events` shows: `System OOM encountered, victim process: bun...`

No idea if it is caused by readdir though.

**Comment by Jarred-Sumner** [comment] 2023-09-26 01:55
I believe this is a similar issue as #4627 (Docker doesn’t virtualize macOS, it runs Linux)

**Comment by tarruda** [comment] 2023-09-26 14:28
>  We probably need to not use the Linux system-call interface on arm64 Linux because Zig's bindings for it are less stable than libc.

@Jarred-Sumner how difficult and/or big is this task? If it is not a lot of work, I could give it a shot and send a PR.

I was planning to evaluate bun as a production runtime for a next.js app, but this is blocking me since my server is arm64.

**Comment by tarruda** [comment] 2023-09-26 19:42
I confirmed this is caused by passing a non-existent directory to `readdir`.

As a workaround, I've prepended the following snippet to the app entrypoint js file:

```js
const fs = require('fs/promises');
const readdirOrig = fs.readdir;
fs.readdir = async function (p, opts) {
        if (!(await fs.exists(p))) {
                throw new Error('ENOENT: no such file or directory')
        }
        return readdirOrig(p, opts);
}
```

Here's a simple script that reproduces the bug 100% of the times in an arm64 linux box:

```js
const fs = require('fs/promises');
console.log('reading non-existent dir');
setInterval(() => {
        console.log('memory usage in mb:', process.memoryUsage().rss / 1024 / 1024);
}, 100);
await fs.readdir('/invalid-directory')
```

**Comment by Jarred-Sumner** [comment] 2023-11-07 02:28
Fixed in https://github.com/oven-sh/bun/pull/6942

**Closed as completed by Jarred-Sumner** 2023-11-07 02:28 UTC
Labels: bug, docker
