### ISSUE TITLE
Bun doesn't run, error: ([1]    257521 illegal hardware instruction (core dumped))

### ISSUE THREAD

**Issue by vedantnn71** [oven-sh/bun#537] opened 2022-07-10 11:56 UTC
### Version

0.1.2

### Platform

Linux doozy 5.18.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:06 +0000 x86_64 GNU/Linux

### What steps will reproduce the bug?

On linux, install bun through command this command as guided in official website (bun.sh)[https://bun.sh]
```bash
curl https://bun.sh/install | bash
```
Now run any command, for ex: `bun --help` and see the error, like this:
![image](https://user-images.githubusercontent.com/70624701/178143774-5f4303bb-baed-4487-8f20-b5728f8d023b.png)

### How often does it reproduce? Is there a required condition?

This error reproduces on running every time.

### What is the expected behavior?

Successfully run and show the output of the command `bun` or `bun --help`.

### What do you see instead?

some core dumped error: 
`[1]    263503 illegal hardware instruction (core dumped)  bun
`

**Comment by FinnRG** [comment] 2022-07-10 14:29
Duplicate of #67. See additional instructions here: https://github.com/Jarred-Sumner/bun#illegal-instruction-core-dumped

**Closed as completed by FinnRG** 2022-07-10 14:29 UTC
