### ISSUE TITLE
Crashing when using bun create cloudflare

### ISSUE THREAD

**Issue by adityabrahmankar** [oven-sh/bun#15282] opened 2024-11-20 10:38 UTC
### How can we reproduce the crash?

Try bun create cloudflare@latest or bunx create-cloudflare@latest in windows cmd

### Relevant log output

```shell
D:\SAAS>bunx create-cloudflare@latest


============================================================
Bun v1.1.36 (ededc168) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "bun" "create" "cloudflare@latest"
Features: spawn 
Elapsed: 187ms | User: 15ms | Sys: 0ms
RSS: 44.54MB | Peak: 44.54MB | Commit: 79.07MB | Faults: 11137

panic(main thread): index out of bounds: index 29, len 13
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.36/wc1ededc16AgggggC4786FqrsnFkqinF+2v9F48hBi8I4ykwkDCYKERNEL32.DLLu+tLCSntdll.dll4+93BA0eNrLzEtJrVDILy1RyE9TSMovzUsptlLIBAsaWeoo5KTmKRgaAwD7HAw9

╰  ERROR  Error
```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on windows x86_64 [CreateCommand]

**panic**: index out of bounds: index 29, len 13

- [`string_immutable.zig:5638`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/string_immutable.zig#L5638>): `convertUTF8toUTF16InBuffer`
- [`run_command.zig:445`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli/run_command.zig#L445>): `runBinary`
- [`bunx_command.zig:532`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli/bunx_command.zig#L532>): `exec`
- [`cli.zig:1753`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli.zig#L1753>): `start`
- [`cli.zig:63`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/cli.zig#L63>): `start`
- [`main.zig:49`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/main.zig#L49>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/src/startup/exe_common.inl#L78>): `invoke_main`

Features: spawn

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6065402962/">BUN-8DZ</a></strong></sub>

**Comment by nektro** [comment] 2024-11-21 00:59
duplicate of https://github.com/oven-sh/bun/issues/15156

**Closed as not planned by nektro** 2024-11-21 00:59 UTC
Labels: crash, windows
