### ISSUE TITLE
Bun fails to load namespaces in test calls

### ISSUE THREAD

**Issue by tghpereira** [oven-sh/bun#2979] opened 2023-05-21 05:29 UTC
### What version of Bun is running?

0.6.2

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Create a project using the bun template with typescript.
Install package 'reflect-metadata'

```sh
bun add reflect-metadata
```
Create a simple decorator using the 'reflect-metadata' package
```ts

type TInvalidateFactoryDto = { key: string; affect: string[] };
type TInvalidateFactoryType = ({ key, affect }: TInvalidateFactoryDto) => MethodDecorator;
const keyword = {
  cache: {
    invalidate: 'cache:invalidate',
  }
}

function InvalidateFactory(): TInvalidateFactoryType {
  return ({ key, affect }: TInvalidateFactoryDto): MethodDecorator => {
    return (target): void => {
      const context: IInvalidate[] = Reflect.getMetadata(keyword.cache.invalidate, target.constructor) || [];
      context.push({ key, affect });
      Reflect.defineMetadata(keyword.cache.invalidate, context, target.constructor);
    };
  };
}

```

Create and run a simple test by invoking 'reflect-metadata'  and decorator

### What is the expected behavior?

When performing the bun upgrade from version 0.5.8 to 0.6.2 it had problems loading namespaces with typescript.

The calls made by the cli to the 'bun test' command did not correctly point to the "reflect-metadata" package namespace. I'm afraid this problem is not from the "reflect-metadata" package and may affect other projects.
I'm afraid the addition of the new bun testing features may have caused some regression.

Executing the project with the command "bun dev" the loading of the namespaces did not show visible failures, but for the safety of the project that we use bun the solution was to revert the project to version 0.5.8 of bun.

![bug bun](https://github.com/oven-sh/bun/assets/86755966/e63af57c-2393-4bb7-8635-c73eded081ed)

As illustrated in the image, the reflect is imported, but it is not recognized by bun when running the tests

### What do you see instead?

Namespaces are not recognized in ambient of tests.

### Additional information

I tried to guide myself through the documentation and tried several approaches such as forcing the namespace to load, reinstalling bun in wsl, cleaning the cache, etc., but I was unsuccessful.

The solution I had was to return the most stable version of bun to our project.

**Comment by Electroid** [comment] 2023-10-26 18:35
Duplicate of #4677

**Closed as not planned by Electroid** 2023-10-26 18:35 UTC
Labels: bug
