### ISSUE TITLE
Cloudflare Workers Pages Dev incompatible with bun

### ISSUE THREAD

**Issue by TheFruxz** [oven-sh/bun#11384] opened 2024-05-27 03:44 UTC
### What version of Bun is running?

1.1.10+5102a9443

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

- Setup a SvelteKit project with Cloudflare Workers / Pages
- Run `bun run build && bunx --bun wrangler pages dev`
- Error happens (with the second part)

### What is the expected behavior?

It should run the cloudflare wrangler part with support for Bun stuff

### What do you see instead?

I see an error like "eval" is not yet implemented in Bun:
```log
[wrangler:inf] Ready on http://localhost:8788
::bunternal:: [NotImplementedError]: worker_threads.Worker option "eval" is not yet implemented in Bun.
    at new NotImplementedError (internal:shared:19:14)
    at <anonymous> (internal:shared:9:37)
    at new Worker (node:worker_threads:119:14)
    at #ensureWorker (/Users/fruxz/dev/projects/qrcode-tour-de/node_modules/miniflare/dist/src/index.js:5866:12)
    at fetch (/Users/fruxz/dev/projects/qrcode-tour-de/node_modules/miniflare/dist/src/index.js:5878:11)
    at get (/Users/fruxz/dev/projects/qrcode-tour-de/node_modules/miniflare/dist/src/index.js:6199:14)
    at <anonymous> (/Users/fruxz/dev/projects/qrcode-tour-de/node_modules/miniflare/dist/src/index.js:9339:28)
    at processTicksAndRejections (:12:39) {
  code: 'ERR_NOT_IMPLEMENTED',
  originalLine: 19,
  originalColumn: 14
}
5861 |     this.#notifyHandle = new Int32Array(new SharedArrayBuffer(4));
5862 |   }
5863 |   #ensureWorker() {
5864 |     if (this.#worker !== void 0)
5865 |       return;
5866 |     this.#worker = new import_worker_threads.Worker(WORKER_SCRIPT, {
       ^
TypeError: BuildMessage: ModuleNotFound resolving "
const { createRequire } = require("module");
const { workerData } = require("worker_threads");

// Not using parentPort here so we can call receiveMessageOnPort() in host
const { notifyHandle, port, filename } = workerData;

// When running Miniflare from Jest, regular 'require("undici")' will fail here
// with "Error: Cannot find module 'undici'". Instead we need to create a
// 'require' using the '__filename' of the host... :(
const actualRequire = createRequire(filename);
const { Pool, fetch } = actualRequire("undici");

let dispatcherUrl;
let dispatcher;

port.addEventListener("message", async (event) => {
  const { id, method, url, headers, body } = event.data;
  if (dispatcherUrl !== url) {
    dispatcherUrl = url;
    dispatcher = new Pool(url, {
      connect: { rejectUnauthorized: false },
    });
  }
  headers["MF-Op-Sync"] = "true";
  try {
    // body cannot be a ReadableStream, so no need to specify duplex
    const response = await fetch(url, { method, headers, body, dispatcher });
    const responseBody = response.headers.get("MF-Op-Result-Type") === "ReadableStream"
      ? response.body
      : await response.arrayBuffer();
    const transferList = responseBody === null ? undefined : [responseBody];
    port.postMessage(
      {
        id,
        response: {
          status: response.status,
          headers: Object.fromEntries(response.headers),
          body: responseBody,
        }
      },
      transferList
    );
  } catch (error) {
    try {
      port.postMessage({ id, error });
    } catch {
      // If error failed to serialise, post simplified version
      port.postMessage({ id, error: new Error(String(error)) });
    }
  }
  Atomics.store(notifyHandle, /* index */ 0, /* value */ 1);
  Atomics.notify(notifyHandle, /* index */ 0);
});
" (entry point)
      at Worker (native:1:1)
      at new Worker (node:worker_threads:119:14)
      at #ensureWorker (/Users/fruxz/dev/projects/qrcode-tour-de/node_modules/miniflare/dist/src/index.js:5866:12)
      at fetch (/Users/fruxz/dev/projects/qrcode-tour-de/node_modules/miniflare/dist/src/index.js:5265:3)
      at get (/Users/fruxz/dev/projects/qrcode-tour-de/node_modules/miniflare/dist/src/index.js:5919:11)
      at /Users/fruxz/dev/projects/qrcode-tour-de/node_modules/miniflare/dist/src/index.js:9339:28
```

**Comment by Electroid** [comment] 2024-05-27 16:10
Duplicate of https://github.com/oven-sh/bun/issues/4165

**Closed as not planned by Electroid** 2024-05-27 16:10 UTC
Labels: bug
