### ISSUE TITLE
Astro.request.formData() returns null from Astro project with node adaptor served by bun

### ISSUE THREAD

**Issue by pogilvie** [oven-sh/bun#7058] opened 2023-11-12 00:19 UTC
### What version of Bun is running?

1.0.7

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

I'm trying to run an Astro node project with Bun.  The the development experience has been fantastic but I've hit an issue trying deploy my code. Here a below example of an Astro page which uses to the Astro.request.formDate() api to get form values form a simple form submit.  This works in dev mode 

works:   bunx --bun astro dev
works: bunx --bun astro build 
serves page but form does not work:  bun dist/server/entry.mjs

This prints null each time the form is submitted.

The same form run from node does work: node dist/server/entry.mjs 

Unfortunately just running the build from nodes is not an easy workaround because bun specific code in my service so I would need to refactor that out.

```
---
if (Astro.request.method === "POST") {
  const formdata = await Astro.request.formData();
  console.log(formdata.get("pets"));
  return Astro.redirect("/");
}
---
<h1>Test Form</h1>
<form method="POST">
  <label for="pet-select">Choose a pet:</label>
  <select name="pets" id="pet-select">
    <option value="">--Please choose an option--</option>
    <option value="dog">Dog</option>
    <option value="cat">Cat</option>
    <option value="hamster">Hamster</option>
    <option value="parrot">Parrot</option>
    <option value="spider">Spider</option>
    <option value="goldfish">Goldfish</option>
  </select>
  <div>
    <button>Submit</button>
  </div>
</form>
<style>
  label {
    font-family: sans-serif;
    font-size: 1rem;
    padding-right: 10px;
  }

  select {
    font-size: 0.9rem;
    padding: 2px 5px;
  }
</style>

```

### What is the expected behavior?

This line prints the value of the select when the form is submitted.

```
const formdata = await Astro.request.formData();
console.log(formdata.get("pets"));
```

### What do you see instead?

```
learning/bun/astro > bun dist/server/entry.mjs                                                                     astro (main)
03:42:57 PM [@astrojs/node] Server listening on https://127.0.0.1:4321
null
null
null
```

**Comment by Electroid** [comment] 2024-01-18 06:51
Duplicate of #8092

**Closed as not planned by Electroid** 2024-01-18 06:51 UTC
Labels: bug, needs investigate
