### ISSUE TITLE
Bun's crypto is 10 times slower than Node's.

### ISSUE THREAD

**Issue by GTLOLI** [oven-sh/bun#14040] opened 2024-09-19 12:20 UTC
### What version of Bun is running?

1.1.28

### What platform is your computer?

Microsoft Windows NT 10.0.18363.0 x64

### What steps can reproduce the bug?

```
import crypto from "crypto";
class AuthVerify {
    async encryMessage(data) {
        const dataString = JSON.stringify(data);
        const { iv, cipher } = this.createSymKey();
        let encrypted = cipher.update(dataString, 'utf8', 'hex');
        encrypted += cipher.final('hex');
        const authTag = cipher.getAuthTag().toString('hex');
        return {
            content: encrypted,
            iv: iv.toString('hex'),
            tag: authTag,
        };
    }
   
    createSymKey() {
        const iv = crypto.randomBytes(12);
        const cipher = crypto.createCipheriv('aes-128-gcm', '0O0OO0000OO00OO0', iv);
        return {
            iv,
            cipher
        };
    }

    // performance testing
    async testEncrypt() {
        const encryptionTasks = [];
        const start = Date.now();
        for (let i = 0; i < 1000; i++) {
            encryptionTasks.push(this.encryMessage("Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."))
        }
        await Promise.all(encryptionTasks);
        const end = Date.now();
        console.log(`耗时${end - start}ms`);
    }
}

const auth = new AuthVerify();
auth.testEncrypt();
```

### What is the expected behavior?

The performance should be the same as or better than the node

### What do you see instead?

 -----------Bun 494ms  
------------node 36ms  

Bun's crypto is 10 times slower than Node's.

### Additional information

CPU : I7-4710HQ
RAM：12GB

**Comment by Christophvh** [comment] 2024-09-19 14:25
Relevant: https://github.com/oven-sh/bun/issues/13681

**Comment by nektro** [comment] 2024-09-19 22:36
Duplicate of https://github.com/oven-sh/bun/issues/13681
please 👍 and subscribe to that issue for updates

**Closed as not planned by nektro** 2024-09-19 22:36 UTC
Labels: bug, needs triage

**Comment by Jarred-Sumner** [comment] 2024-09-20 06:18
Closing as duplicate for tracking reasons (still planning to fix it)
