### ISSUE TITLE
Bun crashes on Windows when trying to run install

### ISSUE THREAD

**Issue by KiprasJ** [oven-sh/bun#12233] opened 2024-06-28 15:17 UTC
### How can we reproduce the crash?

I trying to move from `yarn` to `bun`. But when I do `bun install` this pops up.
steps done:
1. Remove `yarn.lock`
2. Remove `node_modules`
3. Run `bun install`

### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on windows x86_64 [InstallCommand]

**panic**: reached unreachable code

- [`install.zig:6111`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/install/install.zig#L6111>): `runTasks`
- [`install.zig:13480`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/install/install.zig#L13480>): `isDone`
- [`event_loop.zig:1875`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun.js/event_loop.zig#L1875>): `tick`
- [`filter_run.zig:431`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli/filter_run.zig#L431>): `install`
- [`cli.zig:1492`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli.zig#L1492>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/main.zig#L51>): `main`
- [`int_log10.rs:146`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/num/int_log10.rs#L146>): `core::num::int_log10::panic_for_nonpositive_argument`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5af28` in ntdll.dll

**Comment by dylan-conway** [comment] 2024-06-28 15:30
Can you share the package.json for this project?

**Comment by KiprasJ** [comment] 2024-06-28 16:00
We have a mono repo of 4 packages as well. But that is the root package.json

`{
  "name": "xxxxxxx",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@elastic/apm-rum": "^5.14.0",
    "@hookform/resolvers": "^2.9.11",
    "@tanstack/react-query": "^4.35.6",
    "@tanstack/react-query-devtools": "^4.35.6",
    "axios": "^1.6.8",
    "clsx": "^2.0.0",
    "react": "^18.2.0",
    "react-content-loader": "^6.2.1",
    "react-datepicker": "^4.16.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.51.4",
    "react-intl": "^6.2.5",
    "react-router-dom": "^6.16.0",
    "react-tooltip": "^5.26.4"
  },
  "devDependencies": {
    "@babel/helper-builder-react-jsx-experimental": "^7.12.11",
    "@babel/helper-string-parser": "^7.24.1",
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "@formatjs/cli": "^6.2.9",
    "@testing-library/cypress": "^10.0.1",
    "@testing-library/jest-dom": "^6.4.2",
    "@testing-library/react": "^14.3.1",
    "@testing-library/react-hooks": "^8.0.1",
    "@testing-library/user-event": "^14.5.2",
    "@types/chai": "^4.3.14",
    "@types/googlemaps": "^3.43.3",
    "@types/jest": "^29.5.12",
    "@types/react": "^18.2.39",
    "@types/react-datepicker": "^4.15.0",
    "@types/react-dom": "^18.2.25",
    "@typescript-eslint/eslint-plugin": "^5.46.0",
    "@typescript-eslint/parser": "^5.46.1",
    "babel-loader": "9.1.3",
    "browserslist": "4.23.0",
    "chai": "^4.3.7",
    "cross-env": "^7.0.3",
    "css-loader": "^6.11.0",
    "customize-cra": "^1.0.0",
    "cyclonedx-bom": "^0.0.9",
    "eslint": "^8.57.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-airbnb-typescript": "^18.0.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-config-stylelint": "^21.0.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-chai-friendly": "^0.7.4",
    "eslint-plugin-cypress": "^2.15.2",
    "eslint-plugin-formatjs": "^4.13.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jest": "^28.3.0",
    "eslint-plugin-jsx-a11y": "^6.8.0",
    "eslint-plugin-no-relative-import-paths": "^1.5.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.34.1",
    "eslint-plugin-react-hooks": "^4.6.2",
    "gzipper": "^7.2.0",
    "html-webpack-plugin": "^5.6.0",
    "husky": "^9.0.11",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^29.7.0",
    "jest-canvas-mock": "^2.5.2",
    "jest-fail-on-console": "^2.5.0",
    "jest-junit": "16.0.0",
    "lighthouse": "^9.6.8",
    "lint-staged": "^15.2.2",
    "msw": "^1.3.3",
    "ncp": "^2.0.0",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.38",
    "prettier": "^3.2.5",
    "react-app-rewired": "^2.1.9",
    "reinspect": "^1.1.0",
    "rimraf": "^4.4.1",
    "sass": "^1.75.0",
    "sass-loader": "^14.2.1",
    "ssri": "^10.0.1",
    "start-server-and-test": "^2.0.3",
    "stylelint": "^14.16.1",
    "stylelint-config-css-modules": "^4.4.0",
    "stylelint-config-prettier": "^9.0.5",
    "stylelint-config-standard": "^36.0.0",
    "stylelint-config-standard-scss": "^6.1.0",
    "stylelint-prettier": "^3.0.0",
    "stylelint-scss": "^6.2.1",
    "ts-jest": "29.1.2",
    "ts-loader": "^9.4.2",
    "typescript": "4.7.4",
    "webpack-bundle-analyzer": "^4.7.0"
  },
  "optionalDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^20.0.5",
    "@cypress/react": "^8.0.0",
    "@cypress/webpack-dev-server": "^3.8.0",
    "@cypress/webpack-preprocessor": "^6.0.1",
    "cypress-file-upload": "^5.0.8",
    "cypress-iframe": "^1.0.1"
  },
  "peerDependencies": {
    "postcss": "^8.4.38"
  },
  "resolutions": {
    "ansi-regex": "^5.0.1",
    "braces": "^3.0.2",
    "css-what": "^6.1.0",
    "cypress": "https://registry.yarnpkg.com/@favware/skip-dependency/-/skip-dependency-1.2.1.tgz",
    "decode-uri-component": "^0.4.0",
    "ejs": "^3.1.9",
    "json5": "^2.2.2",
    "nth-check": "^2.0.1",
    "semver": "^7.5.1",
    "set-value": "^4.1.0",
    "unset-value": "^2.0.1"
  },
}
`

**Comment by dylan-conway** [comment] 2024-06-28 16:05
Thanks, I can repro the bug

**Comment by KiprasJ** [comment] 2024-06-28 16:13
Any solutions for me or should I wait for a new version?

**Comment by dylan-conway** [comment] 2024-06-28 16:28
We will have a fix for this in the next release of bun.

The cause of this bug is the `cypress` override, bun isn't expecting to have a tarball version there. For now a workaround would be changing the override to an alias: `"cypress": "npm:@favware/skip-dependency@1.2.1"`

**Closed as completed** 2024-06-28 23:54 UTC
Labels: bug, bun install
