### ISSUE TITLE
[bun i] Segmentation fault at address 0x00000000

### ISSUE THREAD

**Issue by sequencerr** [oven-sh/bun#12515] opened 2024-07-11 14:22 UTC
### How can we reproduce the crash?

same https://github.com/sequencerr/bun-repro-workspaces/tree/postinstall from https://github.com/oven-sh/bun/issues/12438

### Stack Trace (bun.report)

Bun v1.1.19 ([`b7dd57a`](<https://github.com/oven-sh/bun/tree/b7dd57ac32bb120177ce5f3da1bedd1414743d37>)) on windows x86_64 [InstallCommand]

Segmentation fault at address 0x00000000

- ??? at `0x12f58` in MSVCP140.dll
- [`mutex:52`](<https://github.com/oven-sh/bun/blob/b7dd57ac32bb120177ce5f3da1bedd1414743d37/C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/include/mutex#L52>): `std::_Mutex_base::lock`
- `??`
- `uv_run`
- [`http.zig:925`](<https://github.com/oven-sh/bun/blob/b7dd57ac32bb120177ce5f3da1bedd1414743d37/src/http.zig#L925>): `processEvents`
- [`http.zig:814`](<https://github.com/oven-sh/bun/blob/b7dd57ac32bb120177ce5f3da1bedd1414743d37/src/http.zig#L814>): `onStart`
- ??? at `0x17344` in KERNEL32.DLL
- ??? at `0x4cc91` in ntdll.dll

**Comment by sequencerr** [comment] 2024-07-11 14:27
maybe cuz canary

**Comment by Jarred-Sumner** [comment] 2024-07-11 14:29
Duplicate of https://github.com/oven-sh/bun/issues/12514

**Comment by Jarred-Sumner** [comment] 2024-07-11 14:29
Tracking this in #12514

**Closed as not planned by Jarred-Sumner** 2024-07-11 14:29 UTC
Labels: bun install
