### ISSUE TITLE
Support Got HTTP library

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#6427] opened 2023-10-11 22:44 UTC
Context
Repo: https://github.com/sindresorhus/got
This is an HTTP request library for Node.js that it seems to be incompatible with bun, it works using Node.

Possible issue
Maybe Bun is not supporting all the features this lib is using, last time I checked this packages uses brotli compression and was also returning an error 

How to reproduce

// got.ts
```
import got from "got";

async function execute() {
  const response = await got(
    "https://api.github.com/repos/sindresorhus/got/issues?state=open"
  ).json();

  console.log(response);
}

execute();
```

Using `bun run ./got.ts` returns the following error:

```
215 |                 Object.assign(this.options.headers, source.headers);
216 |             }
217 |         });
218 |         this.on('newListener', event => {
219 |             if (event === 'retry' && this.listenerCount('retry') > 0) {
220 |                 throw new Error('A retry listener has been attached already.');
                          ^
error: A retry listener has been attached already.
```

_Originally reported on Discord: [`Support Got HTTP library`](https://discord.com/channels/876711213126520882/1161651644962971698/1161651644962971698)_

**Comment by Electroid** [comment] 2023-10-11 23:51
Duplicate of #3150

**Closed as not planned by Electroid** 2023-10-11 23:51 UTC
Labels: bug, node.js
