### ISSUE TITLE
`process.on("exit")` not running

### ISSUE THREAD

**Issue by DWboutin** [oven-sh/bun#6182] opened 2023-09-29 18:37 UTC
### What version of Bun is running?

1.0.3+25e69c71e70ac8a0a88f9cf15b4057bd7b2a633a

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

Just using `mongodb-memory-server` in it's simplest way

```typescript
beforeAll(async () => {
    mongod = await MongoMemoryServer.create()
    const uri = mongod.getUri()

    mongoose.connect(uri, {
        dbName: 'kiosq',
      })
  })
```

[child_process.on("close")](https://github.com/nodkz/mongodb-memory-server/blob/f0dd48fa25c85f01f5ad224d121f0aa2dce03d2d/packages/mongodb-memory-server-core/src/util/MongoInstance.ts#L480) handler is called before the process is actually exited

### What is the expected behavior?

[child_process.on("close")](https://github.com/nodkz/mongodb-memory-server/blob/f0dd48fa25c85f01f5ad224d121f0aa2dce03d2d/packages/mongodb-memory-server-core/src/util/MongoInstance.ts#L480) handler should be called when exited

### Additional information

https://github.com/nodkz/mongodb-memory-server/issues/801

**Comment by Electroid** [comment] 2024-02-05 21:28
`process.exit` works, the issue appears to be related to `beforeAll`.

```js
process.on('exit', function(code) {
  console.log('Exiting:', code);
});
```

```
Exiting: 0
```

**Comment by Electroid** [comment] 2024-02-05 21:29
Duplicate of #5308

**Closed as not planned by Electroid** 2024-02-05 21:29 UTC
Labels: bug, node.js
