### ISSUE TITLE
String + operator broken

### ISSUE THREAD

**Issue by ShogunPanda** [oven-sh/bun#1772] opened 2023-01-12 09:03 UTC
### What version of Bun is running?

0.4.0

### What platform is your computer?

Darwin 22.1.0 x86_64 i386

### What steps can reproduce the bug?

Execute the following file:

```
const a = "[^aeiou]";
const b = a + "[^aeiouy]*";
console.log(a);
```

### What is the expected behavior?

```
[^aeiou]
```

### What do you see instead?

```
[^aeiou][^aeiouy]*
```

### Additional information

It works fine on bun 0.3.0.

**Comment by Jarred-Sumner** [comment] 2023-01-12 13:45
will fix today

This is a transpiler bug that is caused by inlining + simplification 

As a temporary workaround, try making the variables var or moving it to not be at the top of the scope 

When we join rope strings during simplification, it needs to create a new string instead of mutating the existing one.

**Closed as completed** 2023-01-12 18:14 UTC
Labels: bug, transpiler
