### ISSUE TITLE
[bundler] Do not include `import.meta.require` in bundled code when building with `target: "node"`

### ISSUE THREAD

**Issue by zbauman3** [oven-sh/bun#5154] opened 2023-09-12 20:57 UTC
### What version of Bun is running?

1.0.1

### What platform is your computer?

Darwin 22.6.0 arm64 arm

## Demo Branch

I have a minimal reproduction branch setup here: https://github.com/zbauman3/demos/tree/bun-demo.

## Steps
Create a file that includes via `require`:
```ts
const { readdir } = require('fs/promises');
const result = await readdir('../')
console.log("Hello via Node?");
console.log(result);
```

Then use bun to build that code, target `node` for the runtime:
```ts
await Bun.build({
  entrypoints: ["./src/index.ts"],
  outdir: "./dist",
  target: "node"
});
```

Look at the output code. The body of `__require` tries to access `import.meta.require` – _this is not a Node.js API_:
```js
var __require = (id) => {
  return import.meta.require(id);
};

// src/index.ts
var { readdir } = __require("fs/promises");
var result = await readdir("../");
console.log("Hello via Node?");
console.log(result);
```

Test the code with _any_ version of node:
```
$ node ./dist/index.js
file:///Users/path/to/repo/demos/dist/index.js:2
  return import.meta.require(id);
                     ^

TypeError: (intermediate value).require is not a function
    at __require ..... ..... .....
```

### What is the expected behavior?

The code runs when called via `node`, since this was built with `target: node`.

### What do you see instead?

There is a TypeError:

```
$ node ./dist/index.js
file:///Users/path/to/repo/demos/dist/index.js:2
  return import.meta.require(id);
                     ^

TypeError: (intermediate value).require is not a function
    at __require ..... ..... .....
```

### Additional information

This can be fixed by changing the implementation for `__require` to: 

```js
import { createRequire } from 'node:module'
var __require = createRequire(import.meta.url);
```

**Comment by zbauman3** [comment] 2023-09-12 21:38
I've created a (temporary, not great) workaround by applying this to the output code: 
```ts
const fixNodeRequire = (code: string) => {
  return code.replace(
    /(var|const|let)\s+(\w+\s*)=\s*\(\s*\w+\s*\)\s*=>\s*\{\s*return\s*import\.meta\.require\s*\(\s*\w+\s*\)\s*;?\s*\}\s*;?/i,
    `import{createRequire as zz_requireFix}from'node:module';\n$1 $2=zz_requireFix(import.meta.url);`
  );
};
```

**Comment by ibvodafoneziggo** [comment] 2023-09-14 11:21
Hi @zbauman3,

How are you running this code after bundling?

Currently my implementation is like this:
```
for (const output of result.outputs) {
    const code = await output.text();

    //  Run node-fix-plygin against this.
    const nodeifiedCode = fixNodeRequire(code);
    await Bun.write(output.path, nodeifiedCode);
}
```

I haven't seen any hooks for after-test to change the code yet.

**Comment by zbauman3** [comment] 2023-09-14 11:57
@ibvodafoneziggo

Actually, I've had to abandon using Bun until it's been developed more. #4216 was a big issue because when I bundled code on my machine, then send it to another machine to run, it broke if I used `__dirname`. 

Also, there is no way to mock external modules in Bun, so that makes testing any complex code almost impossible.

**Comment by ibvodafoneziggo** [comment] 2023-09-14 13:42
@zbauman3 Thanks for the information, hopefully there's a fix for the issue in the future. In my case I'm not using __dirname, so hopefully that won't be an issue. 

I've tried Bun testing too and I couldn't get that to work properly given our setup yet, so I'm waiting a bit for that part.

**Comment by ruanjiayou** [comment] 2023-09-15 10:22
yes, you can build and run code by bun .but you can't run build-code by node.

**Comment by cs-clarence** [comment] 2023-09-16 13:46
still broken in 1.0.2

**Comment by mathiasrw** [comment] 2023-10-04 04:06
A number of issues are connected to this

- https://github.com/oven-sh/bun/issues/6168
- https://github.com/oven-sh/bun/issues/5707
- https://github.com/oven-sh/bun/issues/5154
- https://github.com/oven-sh/bun/issues/4861
- https://github.com/oven-sh/bun/issues/2858

Looks like https://github.com/oven-sh/bun/issues/6168#issuecomment-1745990151 got a workaround while we wait for a solution.

**Comment by Electroid** [comment] 2023-10-27 22:16
Duplicate of https://github.com/oven-sh/bun/issues/6168

**Closed as not planned by Electroid** 2023-10-27 22:16 UTC
Labels: bug, bundler
