### ISSUE TITLE
Running vitest with --bun flag hangs "bun run --bun vitest"❌ "bun run vitest" ✅

### ISSUE THREAD

**Issue by cpakken** [oven-sh/bun#10180] opened 2024-04-11 20:32 UTC
### What version of Bun is running?

1.1.3+2615dc742

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64
EDIT: also tested in WSL same behavior

### What steps can reproduce the bug?

Use minimal reproduction 
https://github.com/cpakken/vitest-issue

![image](https://github.com/oven-sh/bun/assets/61718569/9e7d02ec-5297-4920-bf41-01bc2a8e5386)

Also windows firewall for bun pops up while running with --bun command. Does not work even when allowed.

### What is the expected behavior?

Should work

### What do you see instead?

Hangs when vitest is run with --bun

**Comment by cpakken** [comment] 2024-04-11 22:58
Confirmed same behavior in WSL

```bash
bun create github.com/cpakken/vitest-issue
cd vitest-issue
bun run vitest #works
bun run -b vitest #hangs
```
![image](https://github.com/oven-sh/bun/assets/61718569/0560f947-c639-415e-9848-e6f2e672ccdc)
```bash
> bun --revision
1.1.3+2615dc742
> uname -mprs
Linux 5.15.146.1-microsoft-standard-WSL2 x86_64 x86_64

**Comment by birkskyum** [comment] 2024-10-25 00:51
Duplicate of 
- https://github.com/oven-sh/bun/issues/11268

**Closed as not planned by birkskyum** 2024-10-25 00:51 UTC
Labels: bug
