### ISSUE TITLE
Buffer.from is blank for specific base64 strings

### ISSUE THREAD

**Issue by binary-koan** [oven-sh/bun#1184] opened 2022-08-31 09:44 UTC
### Version

0.1.11 (canary build from earlier today)

### Platform

Darwin MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Attempting to encode and then decode a JWT header produces an empty string instead of the original text:

```ts
const encoded = Buffer.from('{"alg":"RS256","typ":"JWT"}', 'utf-8').toString('base64') // 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9'
const decoded = Buffer.from(encoded, 'base64').toString('utf-8') // '' (empty string)
```

### How often does it reproduce? Is there a required condition?

Currently that's the only string I've found that causes the bug (but it's breaking the `jws` / `jsonwebtoken` Node packages)

### What is the expected behavior?

For most strings, this works:

```ts
const encoded = Buffer.from(original, 'utf-8').toString('base64')
const decoded = Buffer.from(encoded, 'base64').toString('utf-8')

console.log(decoded === original) // true
```

### What do you see instead?

It seems Buffer fails to read that base64 string - `Buffer.from('eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9', 'base64')` returns `Uint8Array(0) [  ]`

### Additional information

This may be some conflict between base64 and base64url encodings. Doing the same thing with `base64url` does work as expected:

```ts
const encoded = Buffer.from('{"alg":"RS256","typ":"JWT"}', 'utf-8').toString('base64url')
const decoded = Buffer.from(encoded, 'base64url').toString('utf-8')

console.log(decoded === original) // true
```

I feel like plain Node can parse URL-safe base64 with the `base64` encoding in Buffer, but I think this is also a case where the URL-safe and regular base64 is identical.

Also note that `btoa` and `atob` work correctly with that string.

**Comment by xhyrom** [comment] 2022-08-31 10:12
It's a bug in base64, when you encode a string, it doesn't include =

**Comment by xhyrom** [comment] 2022-08-31 10:12
Duplicate of https://github.com/oven-sh/bun/issues/455

**Closed as not planned by xhyrom** 2022-08-31 10:12 UTC
Labels: bug, needs repro

**Comment by binary-koan** [comment] 2022-08-31 21:46
@xHyroM Happy to summarise this on #455 if it can be fixed at the same time, but I think this is a slightly different issue. When you encode this string as base64 it does not include = in either Node or Bun (Node also gives the result `eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9` without =)

Node in general can also parse base64url strings with the base64 decoder, while it seems Bun is unable to (e.g. `Buffer.from("dGVzdA", "base64")` returns different results in Node and Bun). But unsure if Bun is deliberately diverging here

So I think this bug is in `Buffer#from`, not `Buffer#toString`

**Comment by ElYaiko** [comment] 2022-10-25 02:49
I'm having the same issue when trying to decode a base64 string in bun 0.2.1 with:
`Buffer.from(str, 'base64').toString('binary');`

In node I get:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 = {"alg":"HS256","typ":"JWT"}`

In bun I get:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 = ≻污≧∺午㔲∶∬祴≰∺坊≔}҇Ȩ瑌̼`
