### ISSUE TITLE
Crash during bun install

### ISSUE THREAD

**Issue by rholang** [oven-sh/bun#11357] opened 2024-05-25 21:42 UTC
### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:5119`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5119>): `processDependencyListItem`
- [`install.zig:5177`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5177>): `processDependencyList`
- [`install.zig:5895`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5895>): `runTasks`
- [`install.zig:10411`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L10411>): `installPackages`
- [`filter_run.zig:430`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli/filter_run.zig#L430>): `install`
- [`cli.zig:1461`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L1461>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/src/startup/exe_common.inl#L78>): `invoke_main`
- ??? at `0x1257d` in KERNEL32.DLL

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:43
Duplicate of https://github.com/oven-sh/bun/issues/10565

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:43
To track this issue, please follow along in https://github.com/oven-sh/bun/issues/10565

**Closed as not planned by Jarred-Sumner** 2024-06-04 22:43 UTC
Labels: crash
