### ISSUE TITLE
Import named 'KeyObject' not found in module 'crypto'.

### ISSUE THREAD

**Issue by ThatMarko** [oven-sh/bun#5036] opened 2023-09-12 03:40 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

Using SvelteKit and trying to create JWT with the jose package.

```
import { JWT_SECRET } from '$env/static/private';
import { error } from '@sveltejs/kit';
import * as jose from 'jose';

type JWTPayload = {
	firstName: string;
	lastName: string;
	email: string;
	id: number;
};

export const createAuthJWT = async (data: JWTPayload) => {
	const jwt = await new jose.SignJWT(data)
		.setProtectedHeader({ alg: 'HS256' })
		.sign(new TextEncoder().encode(JWT_SECRET));
	return jwt;
}; 
```

Getting this error:

`Internal server error: Import named 'KeyObject' not found in module 'crypto'.`

### What is the expected behavior?

The module successfully imports and generates the jwt

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/7422135/3af0ae87-00b1-45d1-9f24-4b5cedffea78)

### Additional information

Package.json

```
{
  "name": "markobog.me",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "lint": "prettier --plugin-search-dir . --check . && eslint .",
    "format": "prettier --plugin-search-dir . --write ."
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^2.0.0",
    "@sveltejs/kit": "^1.20.4",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.9",
    "@typescript-eslint/eslint-plugin": "^5.45.0",
    "@typescript-eslint/parser": "^5.45.0",
    "autoprefixer": "^10.4.14",
    "bun-types": "^1.0.1",
    "daisyui": "^3.1.6",
    "drizzle-kit": "^0.19.13",
    "elizabot": "^0.0.3",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-svelte": "^2.30.0",
    "postcss": "^8.4.24",
    "postcss-load-config": "^4.0.1",
    "prettier": "^2.8.0",
    "prettier-plugin-svelte": "^2.10.1",
    "svelte": "^4.0.5",
    "svelte-adapter-bun": "^0.5.0",
    "svelte-check": "^3.4.3",
    "tailwindcss": "^3.3.2",
    "tslib": "^2.4.1",
    "typescript": "^5.0.0",
    "vite": "^4.4.2"
  },
  "type": "module",
  "dependencies": {
    "@libsql/client": "^0.3.4",
    "drizzle-orm": "^0.28.6",
    "jose": "^4.14.6"
  }
}

```

**Comment by bllyanos** [comment] 2023-09-12 03:47
I believe the API for KeyObject is still missing according to the docs https://bun.sh/docs/runtime/nodejs-apis#node-crypto
![image](https://github.com/oven-sh/bun/assets/10113342/77bf98cd-1f25-43e7-b4eb-9a681cffac67)

**Comment by Electroid** [comment] 2023-09-12 04:27
> I believe the API for KeyObject is still missing according to the docs https://bun.sh/docs/runtime/nodejs-apis#node-crypto ![image](https://user-images.githubusercontent.com/10113342/267204740-77bf98cd-1f25-43e7-b4eb-9a681cffac67.png)

Yes, that's correct. Bun needs to implement `KeyObject`, and we'll do this.

**Comment by blackmann** [comment] 2023-09-12 21:11
Is there any way (maybe some existing library) to handle JWTs with bun?

I'm kind of surprised this is not a big deal.

**Comment by sirenkovladd** [comment] 2023-09-12 21:52
Duplicate of https://github.com/oven-sh/bun/issues/2036

**Closed as completed** 2023-10-07 22:22 UTC
Labels: bug, node.js
