### ISSUE TITLE
typescript transpiler incorrectly handles pre-es2022 class fields

### ISSUE THREAD

**Issue by teidesu** [oven-sh/bun#9172] opened 2024-03-01 00:37 UTC
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Darwin 23.2.0 arm64 arm

### What steps can reproduce the bug?

1. write the following to `bun-repro.ts`:
```ts
class Foo {
    constructor(readonly bar: string) {}

    readonly baz = this.bar + ' world'
}

const foo = new Foo('hello')
console.log(foo.baz)
```
2. set `"useDefineForClassFields": false` or `"target": "es2020"` in tsconfig
3. `bun run bun-repro.ts`

### What is the expected behavior?

the script produces `hello world`

### What do you see instead?

the script produces `undefined world`

### Additional information

this happens due to the fact that es2022 class fields are always de-sugared to the beginning of the constructor, but pre-es2022 typescript class fields are de-sugared to the end of the constructor. likely related to #6431

in typescript this is resolved in `tsconfig.json` by either setting `target` to pre-es2022 or `useDefineForClassFields` to false, but bun seems to ignore this field.

`bun build bun-repro.ts` produces:
```js
class Foo {
  bar;
  constructor(bar) {
    this.bar = bar;
  }
  baz = this.bar + " world";
}
var foo = new Foo("hello");
console.log(foo.baz);
```
while the correct output with `useDefineForClassFields=false` in tsconfig would be:
```js
// tsc bun-repro.ts --outfile /dev/stdout --target es2022 --useDefineForClassFields false
class Foo {
    constructor(bar) {
        this.bar = bar;
        this.baz = this.bar + ' world';
    }
}
const foo = new Foo('hello');
console.log(foo.baz);
```

**Comment by Jarred-Sumner** [comment] 2024-03-01 06:51
Duplicate of https://github.com/oven-sh/bun/issues/4612

**Closed as not planned by Jarred-Sumner** 2024-03-01 06:51 UTC
Labels: bug

**Comment by teidesu** [comment] 2024-03-01 07:33
fair, somehow missed it, sorry
