### ISSUE TITLE
no commit matching "semver:^20" found for "uWebSockets.js" (but repository exists)

### ISSUE THREAD

**Issue by subtleGradient** [oven-sh/bun#10526] opened 2024-04-25 23:56 UTC
### What version of Bun is running?

1.1.4+fbe2fe0c3
1.1.5

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Trying to use bun as a package manager.

```json5
{
  // ...
  "dependencies": {
      "uWebSockets.js": "uNetworking/uWebSockets.js#semver:^20"
  }
}
```

```
(base) tom@tom-frens backend % bun add @graphql-mesh/cli
[0.03ms] ".env"
bun add v1.1.4 (fbe2fe0c)
  🔍 Resolving [1/26] error: no commit matching "semver:^20" found for "uWebSockets.js" (but repository exists)

error: InstallFailed

----- bun meta -----
Bun v1.1.4 (fbe2fe0c) macOS Silicon 23.4.0
AddCommand: dotenv bunfig git_dependencies 
HTTP: 22
Elapsed: 263ms | User: 97ms | Sys: 72ms
RSS: 0.26GB | Peak: 0.26GB | Commit: 0.38GB | Faults: 0
----- bun meta -----

0   0x10120387c
1   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
```

https://github.com/ardatan/graphql-mesh/blob/4aef4ff9b0e9c489e1fd906464fdbe107ca19e43/packages/serve-cli/package.json#L58

```
% bun add uWebSockets.js@uNetworking/uWebSockets.js#semver:^20
[0.03ms] ".env"
bun add v1.1.4 (fbe2fe0c)
  🔍 uWebSockets.js [1/2] 
error: package "uWebSockets.js" not found registry.npmjs.org/uWebSockets.js 404
  🔍 regenerator-runtime [122/179] error: no commit matching "semver:^20" found for "uWebSockets.js" (but repository exists)

error: InstallFailed
```

### What is the expected behavior?

install     uWebSockets.js "uNetworking/uWebSockets.js#semver:^20"

### What do you see instead?

error: InstallFailed

### Additional information

```
% bun add 'uWebSockets.js@https://github.com/uNetworking/uWebSockets.js/archive/refs/tags/v20.43.0.tar.gz'
[0.05ms] ".env"
bun add v1.1.4 (fbe2fe0c)
error: uWebSockets.js@https://github.com/uNetworking/uWebSockets.js/archive/refs/tags/v20.43.0.tar.gz failed to resolve
```

---

```
% bun add 'uWebSockets.js@github:uNetworking/uWebSockets.js#v20.43.0'
[0.04ms] ".env"
bun add v1.1.4 (fbe2fe0c)

 installed uWebSockets.js@github:uNetworking/uWebSockets.js#1977b50

 5 packages installed [12.30s]
  Removed: 11
```

But when I add that to `resolutions`, it fails again

```json5
{
  // ...
  "resolutions": {
    "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.43.0"
  },
}
```

```
% bun i
[0.03ms] ".env"
bun install v1.1.4 (fbe2fe0c)
error: uWebSockets.js@github:uNetworking/uWebSockets.js#v20.43.0 failed to resolve
```

**Comment by subtleGradient** [comment] 2024-04-26 12:20
# NOTE: We (Frens.lol) are trying to use Bun in production.

This issue (#10526) is the first critical blocker on the bundling side. 
**I have been forced to switch our bundling to yarn because of this issue**  
(after trying everything I could think of to work around it.)

---

We had to switch from **Bun runtime in production** to ts-node + express for a different issue a little while ago. I've been gradually trying to move back to bun runtime in production, but it hasn't been a priority. I'll try to file a ticket for the production runtime problem soon

**Comment by asgarovf** [comment] 2024-05-03 08:06
Same happens for me on github actions

**Comment by just-maik** [comment] 2024-06-26 09:53
Any updates on this? Cant use GrapgQL-Mesh from The Guild because uNetworking/uWebSockets.js is a peer dependency and can't be installed...

**Comment by Jarred-Sumner** [comment] 2024-06-27 00:11
Duplicate of #5870

**Comment by Jarred-Sumner** [comment] 2024-06-27 00:11
This is being tracked in #5870 

Please follow along there.

In the meantime, if you avoid the `semver:` prefix and instead target a specific tag that will be a workaround

For example:
```
{
  // ...
  "dependencies": {
      "uWebSockets.js": "uNetworking/uWebSockets.js#v20.44.0"
  }
}
```

**Closed as not planned by Jarred-Sumner** 2024-06-27 00:11 UTC
Labels: bug
