### ISSUE TITLE
"illegal hardware instruction" on Raspberry Pi

### ISSUE THREAD

**Issue by pro-sumer** [oven-sh/bun#12210] opened 2024-06-27 19:08 UTC
### What version of Bun is running?

1.1.17+bb66bba1b

### What platform is your computer?

Linux 6.6.31+rpt-rpi-v8 aarch64 unknown

### What steps can reproduce the bug?

Many/(all) bun commands; example:

```
bun update
```

### What is the expected behavior?

Bun executes the requested command

### What do you see instead?

```
zsh: illegal hardware instruction  bun test
```

### Additional information

This started with bun 1.1.16; worked OK before.

**Comment by Jarred-Sumner** [comment] 2024-06-29 09:31
Duplicate of #12076

**Comment by Jarred-Sumner** [comment] 2024-06-29 09:31
We are tracking this in #12076 , please follow along in that issue

**Closed as not planned by Jarred-Sumner** 2024-06-29 09:31 UTC
Labels: bug, needs triage
