### ISSUE TITLE
ZeroMQ Subscriber Error

### ISSUE THREAD

**Issue by mgpai22** [oven-sh/bun#7774] opened 2023-12-21 19:49 UTC
### What version of Bun is running?

1.0.18

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

```
bun install zeromq@6.0.0-beta.19
```

```index.ts
import * as zmq from 'zeromq';

const sock = new zmq.Subscriber
```

```
bun run index.ts
```

### What is the expected behavior?

should complete without any errors

### What do you see instead?

bun: symbol lookup error: /node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node: undefined symbol: uv_async_init

**Comment by mgpai22** [comment] 2023-12-21 19:51
Same issue on `Linux 5.15.0-60-generic x86_64 x86_64`

**Comment by Electroid** [comment] 2023-12-21 21:37
We will fix this.

Duplicate of #5019

**Closed as not planned by Electroid** 2023-12-21 21:37 UTC
Labels: bug
