### ISSUE TITLE
panic when running rspack + vue-loader

### ISSUE THREAD

**Issue by taras-turchenko-moc** [oven-sh/bun#15147] opened 2024-11-14 11:16 UTC
### How can we reproduce the crash?

1. clone repo https://github.com/taras-turchenko-moc/rspack-bun
2. Run build
```sh
docker build -t rspack-bun . && docker run --name rspack-bun rspack-bun; docker rm rspack-bun
```

### Relevant log output

```shell
$ cross-env NODE_ENV=production rspack build
============================================================
Bun v1.1.34 (5e5e7c60) Linux arm64
Linux Kernel v6.11.6 | glibc v2.31
Args: "node" "/myapp/node_modules/.bin/rspack" "build"
Features: Bun.stdin(2) jsc tsconfig(2)
Builtins: "bun:main" "node:assert" "node:buffer" "node:console" "node:constants" "node:crypto" "node:events" "node:fs" "node:module" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:worker_threads" "node:repl" "node:inspector"
Elapsed: 539ms | User: 487ms | Sys: 86ms
RSS: 3.07GB | Peak: 0.31GB | Commit: 3.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.34/Ln15e5e7c6AkggkggC+nwz+DuiE__+hy91Du7sz1D24u3wE2s/s9E+ots3D_A2AK

error: script "build" exited with code 1
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on linux aarch64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `llint_op_call_ignore_result`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`BunProcess.cpp:2646`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/src/bun.js/bindings/BunProcess.cpp#L2646>): `Bun::jsFunctionDrainMicrotaskQueue`

Features: Bun.stdin, dotenv, jsc, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6064264825/">BUN-8D1</a></strong></sub>

**Comment by taras-turchenko-moc** [comment] 2024-11-14 11:17
When running comment without docker everything works fine but docker is must for me and ci

**Comment by taras-turchenko-moc** [comment] 2024-11-14 11:22
Also just found out that running `bun -b run build` locally also panics

```
bun -b run build
$ cross-env NODE_ENV=production rspack build
============================================================
Bun v1.1.34 (5e5e7c60) macOS Silicon
macOS v15.0.1
Args: "node" "/Users/master/Projects/rspack-bun/node_modules/.bin/rspack" "build"
Features: Bun.stdin(2) jsc transpiler_cache(15) tsconfig(2)
Builtins: "bun:main" "node:assert" "node:buffer" "node:console" "node:constants" "node:crypto" "node:events" "node:fs" "node:module" "node:os" "node:path" "node:perf_hooks" "node:process" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:worker_threads" "node:repl" "node:inspector"
Elapsed: 358ms | User: 310ms | Sys: 55ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 1.07GB | Faults: 91

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.34/Mn15e5e7c6AkggkggD___+hvkyCu7p6xCmxgx3B+65w/BmvnujCm770d_A2AK

error: script "build" exited with code 1
```

**Comment by nektro** [comment] 2024-11-14 23:09
duplicate of https://github.com/oven-sh/bun/issues/11628

**Closed as not planned by nektro** 2024-11-14 23:09 UTC
Labels: crash, linux, runtime
