### ISSUE TITLE
Bun Crash report.

### ISSUE THREAD

**Issue by baydunord** [oven-sh/bun#12035] opened 2024-06-21 12:41 UTC
### How can we reproduce the crash?

I got a crash report. Please take a look, if relevant. if not, Please close this issue. 

### Relevant log output

```shell
bun test v1.1.15 (b23ba1fe)
============================================================
Bun v1.1.15 (b23ba1fe) Windows x64
Args: "bun" "test"
Features: jsc
Elapsed: 39104ms | User: 46ms | Sys: 1375ms
RSS: 107.52MB | Peak: 107.52MB | Commit: 0.15GB | Faults: 27121

panic(main thread): Internal Error: Do not pass posix paths to Windows APIs, was given '\usr\bin\python3'. Please open an issue on GitHub with a reproduction.
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
```

### Stack Trace (bun.report)

Bun v1.1.15 ([`b23ba1f`](<https://github.com/oven-sh/bun/tree/b23ba1fe1805891cdf4566331f0c8e87d0a5b758>)) on windows x86_64 [TestCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '\usr\bin\python3'. Please open an issue on GitHub with a reproduction.

- [`Allocator.zig:225`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/deps/zig/lib/std/mem/Allocator.zig#L225>): `allocBytesWithAlignment`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`bun.zig:3320`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/bun.zig#L3320>): `unsafeAssert`
- [`sys.zig:2251`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/sys.zig#L2251>): `getFileAttributes`
- [`fs.zig:394`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/fs.zig#L394>): `kind`
- [`test_command.zig:528`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli/test_command.zig#L528>): `next`
- [`fs.zig:224`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/fs.zig#L224>): `addEntry`
- [`test_command.zig:442`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli/test_command.zig#L442>): `scan`
- [`cli.zig:1546`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli.zig#L1546>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/b23ba1fe1805891cdf4566331f0c8e87d0a5b758/src/cli.zig#L62>): `start`

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:56
Duplicate of https://github.com/oven-sh/bun/issues/10830

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:56
Please follow along in https://github.com/oven-sh/bun/issues/10830

**Closed as not planned by Jarred-Sumner** 2024-08-06 07:56 UTC
Labels: crash, windows, runtime
