### ISSUE TITLE
bun add throws ENOENT error in monorepo

### ISSUE THREAD

**Issue by rikbrown** [oven-sh/bun#7807] opened 2023-12-23 20:48 UTC
### What version of Bun is running?

1.0.19+906f86d6f

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

Create a multi-workspace repo.
In a child workspace, run a `bun add` command (doesn't seem to matter what package I add).
**Intermittently**, it fails

### What is the expected behavior?

Package is added.

### What do you see instead?

```
bun add v1.0.19 (906f86d6)

error: ENOENT

----- bun meta -----
Bun v1.0.19 (906f86d6) macOS Silicon 23.0.0
AddCommand: 
Elapsed: 7ms | User: 12ms | Sys: 7ms
RSS: 23.30MB | Peak: 23.30MB | Commit: 34.62MB | Faults: 0
----- bun meta -----

0   0x10361ee58
1   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
```

### Additional information

Additionally, `bun i` works but this adds it to the root package.json even if run in a subpackage.

**Comment by hdwatts** [comment] 2023-12-24 02:01
I just started encountering this too, on 1.0.18

```
bun add v1.0.18 (36c316a2)

error: ENOENT

----- bun meta -----
Bun v1.0.18 (36c316a2) macOS Silicon 23.1.0
AddCommand: dotenv
Elapsed: 4ms | User: 10ms | Sys: 6ms
RSS: 20.48MB | Peak: 20.48MB | Commit: 34.62MB | Faults: 0
----- bun meta -----

0   0x1030a81e0
1   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord```

**Comment by hdwatts** [comment] 2023-12-24 02:03
Steps I took to resolve

1. `rm bun.lockb` in root directory
2. `bun i` in root directory
3. cd into monorepo package
4. `bun add ...`

**Comment by Electroid** [comment] 2023-12-24 16:01
Duplicate of #7042

**Closed as not planned by Electroid** 2023-12-24 16:01 UTC
Labels: bug, bun install
