### ISSUE TITLE
Error when run with docker or direct bun run dev, on ubuntu 22

### ISSUE THREAD

**Issue by maulanadiooo** [oven-sh/bun#11375] opened 2024-05-26 15:31 UTC
### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](<https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x0000001A

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/ld-temp.o#L0>): `WTF::jscSignalHandler`

Features: jsc, Bun.stdin, dotenv, tsconfig

**Comment by Electroid** [comment] 2024-05-27 16:31
Unfortunately, there is not enough information in the stack trace to reproduce this issue. Could you share your code and package.json so we can reproduce it?

**Comment by Jarred-Sumner** [comment] 2024-06-04 11:37
If you're still running into this, feel free to leave a comment with code for us to reproduce the issue. Closing since there has been no reproduction for a week and we are unable to take action on this

**Closed as not planned by Jarred-Sumner** 2024-06-04 11:37 UTC
Labels: needs repro, crash
