### ISSUE TITLE
Bun Crash During Dependency Installation

### ISSUE THREAD

**Issue by pavelbe** [oven-sh/bun#10689] opened 2024-04-30 10:15 UTC
### How can we reproduce the crash?

Attempting to install dependencies using Bun v1.1.6 on Windows leads to a crash. Steps to reproduce:
1. Open the command line in the project directory.
2. Run the command `bun i`.
3. Observe the installation process, which ends with a crash and the error message "panic(main thread): index out of bounds".

For full context, here is the package.json with the dependencies I was trying to install:

```json 
{ "name": "next-js-board-test", "version": "0.1.0", "private": true, "scripts": { "dev": "next dev", "build": "next build", "start": "next start", "lint": "next lint", "upd": "ncu -i" }, "dependencies": { "@clerk/nextjs": "^5.0.3", "@hookform/resolvers": "^3.3.4", "@radix-ui/react-accordion": "^1.1.2", "@radix-ui/react-alert-dialog": "^1.0.5", "@radix-ui/react-aspect-ratio": "^1.0.3", "@radix-ui/react-avatar": "^1.0.4", "@radix-ui/react-checkbox": "^1.0.4", "@radix-ui/react-collapsible": "^1.0.3", "@radix-ui/react-context-menu": "^2.1.5", "@radix-ui/react-dialog": "^1.0.5", "@radix-ui/react-dropdown-menu": "^2.0.6", "@radix-ui/react-hover-card": "^1.0.7", "@radix-ui/react-label": "^2.0.2", "@radix-ui/react-menubar": "^1.0.4", "@radix-ui/react-navigation-menu": "^1.1.4", "@radix-ui/react-popover": "^1.0.7", "@radix-ui/react-progress": "^1.0.3", "@radix-ui/react-radio-group": "^1.1.3", "@radix-ui/react-scroll-area": "^1.0.5", "@radix-ui/react-select": "^2.0.0", "@radix-ui/react-separator": "^1.0.3", "@radix-ui/react-slider": "^1.1.2", "@radix-ui/react-slot": "^1.0.2", "@radix-ui/react-switch": "^1.0.3", "@radix-ui/react-tabs": "^1.0.4", "@radix-ui/react-toast": "^1.1.5", "@radix-ui/react-toggle": "^1.0.3", "@radix-ui/react-toggle-group": "^1.0.4", "@radix-ui/react-tooltip": "^1.0.7", "class-variance-authority": "^0.7.0", "clsx": "^2.1.1", "cmdk": "^1.0.0", "date-fns": "^3.6.0", "embla-carousel-react": "^8.0.2", "input-otp": "^1.2.4", "lucide-react": "^0.376.0", "next": "14.2.3", "next-themes": "^0.3.0", "react": "^18", "react-day-picker": "^8.10.1", "react-dom": "^18", "react-hook-form": "^7.51.3", "react-resizable-panels": "^2.0.19", "sonner": "^1.4.41", "tailwind-merge": "^2.3.0", "tailwindcss-animate": "^1.0.7", "vaul": "^0.9.0", "zod": "^3.23.5" }, "devDependencies": { "@types/node": "^20", "@types/react": "^18", "@types/react-dom": "^18", "eslint": "^9.1.1", "eslint-config-next": "14.2.3", "postcss": "^8", "prettier": "^3.2.5", "prettier-plugin-tailwindcss": "^0.5.14", "tailwindcss": "^3.4.3", "typescript": "^5" } }
```

### Relevant log output

```shell
bun install v1.1.6 (e58d67b4)
[11.56ms] migrated lockfile from package-lock.json
============================================================
Bun v1.1.6 (e58d67b4) Windows x64
Args: "C:\Users\pavel\.bun\bin\bun.exe", "i"
Features: dotenv extracted_packages(31) lockfile_migration_from_package_lock 
Elapsed: 13753ms | User: 375ms | Sys: 2218ms
RSS: 0.26GB | Peak: 0.27GB | Commit: 0.40GB | Faults: 82584

panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.6 ([`e58d67b`](https://github.com/oven-sh/bun/tree/e58d67b46875280bc9002add4c3fae45472cb346)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:4872`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L4872): `processDependencyListItem`
- [`logger.zig:850`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/logger.zig#L850): `allocPrint`
- [`install.zig:5652`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L5652): `runTasks`
- [`install.zig:10115`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L10115): `installPackages`
- [`install.zig:10795`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/install/install.zig#L10795): `installWithManager`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1304`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L1304): `which`
- [`cli.zig:56`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/cli.zig#L56): `start`
- [`main.zig:52`](https://github.com/oven-sh/bun/blob/e58d67b46875280bc9002add4c3fae45472cb346/src/main.zig#L52): `main`
- `_ZN9hashbrown3raw21RawTable$LT$T$C$A$GT$14reserve_rehash17h6e5acef1e33143a1E`

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:42
Duplicate of Duplicate of https://github.com/oven-sh/bun/issues/10565

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:43
To track this issue, please follow along in https://github.com/oven-sh/bun/issues/10565

**Closed as not planned by Jarred-Sumner** 2024-06-04 22:43 UTC
Labels: bug, crash
