### ISSUE TITLE
Bun does not escape escaped quotations inside package.json scripts

### ISSUE THREAD

**Issue by Informagier** [oven-sh/bun#794] opened 2022-07-19 23:54 UTC
### Version

0.1.4

### Platform

Linux mypc 5.18.11-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 12 22:52:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

When some escaped quotation marks are in the scripts section of ones package.json, bun will not escape these quotation marks.

Example:
```json
"scripts": {
  "bun-test": "echo \"Hello World\""
}
```
When running `bun run bun-test`, it will print the quotation marks, because it just passes the \\" to the shell, instead of putting a simple " there.

### How often does it reproduce? Is there a required condition?

Works every time

### What is the expected behavior?

When running bun-test, I want to see Hello World

### What do you see instead?

I see "Hello World"

### Additional information

The problem is probably in the js_lexer at https://github.com/oven-sh/bun/blob/e5af1ea3bc6cdae9f76f14c4518a189ba6e014cb/src/js_lexer.zig#L1857

**Comment by Informagier** [comment] 2022-07-20 00:13
Btw - why are you creating your own json parser and not using an existing solution?

**Comment by Electroid** [comment] 2023-03-21 17:53
Duplicate of #53, still on our radar to fix.

**Closed as completed by Electroid** 2023-03-21 17:53 UTC
Labels: bug, bun install
