### ISSUE TITLE
Segmentation fault in production

### ISSUE THREAD

**Issue by nervetattoo** [oven-sh/bun#11416] opened 2024-05-28 10:32 UTC
### How can we reproduce the crash?

No log output or nothing until suddenly segfault. This is a live system that has been running without any issues of this type for a year. No recent deployment when this happened either.

### Stack Trace (bun.report)

Bun v1.1.9 ([`bb13798`](<https://github.com/oven-sh/bun/tree/bb13798d9802d26770d8467a200022a2b91f7afd>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`StringImpl.h:1154`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd//build/bun/bun-webkit/include/wtf/text/StringImpl.h#L1154>): `Bun::formatStackTrace`
- [`ZigGlobalObject.cpp:529`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/bun.js/bindings/ZigGlobalObject.cpp#L529>): `computeErrorInfoWithoutPrepareStackTrace`
- [`ZigGlobalObject.cpp:624`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/src/bun.js/bindings/ZigGlobalObject.cpp#L624>): `computeErrorInfo`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd//build/bun/bun-webkit/include/wtf/Function.h#L53>): `WTF::Detail::CallableWrapper<WTF::String (...)(...), WTF::String, JSC::VM&, WTF::Vector<JSC::StackFrame, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, unsigned int&, unsigned int&, WTF::String&, JSC::JSObject*>::call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/ld-temp.o#L0>): `JSC::ErrorInstance::computeErrorInfo`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/ld-temp.o#L0>): `JSC::Heap::runEndPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/ld-temp.o#L0>): `JSC::Heap::runCurrentPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bb13798d9802d26770d8467a200022a2b91f7afd/ld-temp.o#L0>): `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`

**Comment by Jarred-Sumner** [comment] 2024-06-06 12:26
Duplicate of https://github.com/oven-sh/bun/issues/11568

**Comment by Jarred-Sumner** [comment] 2024-06-06 12:27
If you can share the source code or a way to reproduce this, please share and we'll fix. Right now we have no way to reproduce this

**Closed as not planned** 2024-06-06 12:27 UTC
Labels: crash
