### ISSUE TITLE
SegmentationFault (26 or big number): fetch().then()

### ISSUE THREAD

**Issue by carlopi** [oven-sh/bun#614] opened 2022-07-12 07:17 UTC
### Version

0.1.3

### Platform

Linux device 5.10.0-1038-oem #40-Ubuntu SMP Fri Jul 16 15:08:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

`fetch('something').then(Ln=>{console.log("Done?");});` into fetch.js

bun run fetch.js

### How often does it reproduce? Is there a required condition?

40% of times it does: SegmentationFault at 26
Another 40% SegmentationFault with a big number (like 140571065193179 or 139640501134844, always more or less close to 1.4 * 10^14).

Another 20% terminates without any logging.

File 'something' might be present or not, doesn't seems to make a difference.

### What is the expected behavior?

Either fetch being not defined as a function, or fetch working in fetching local files.

### What do you see instead?

```
SegmentationFault at 26


–––– bun meta ––––
Bun v0.1.3 Linux x64 #40-Ubuntu SMP Fri Jul 16 15:08:30 UTC 2021
RunCommand: 
Elapsed: 70ms | User: 34ms | Sys: 9ms
RSS: 69.21MB | Peak: 33.86MB | Commit: 69.21MB | Faults: 1
–––– bun meta ––––

Ask for #help in https://bun.sh/discord or go to https://bun.sh/issues
```

**Comment by FinnRG** [comment] 2022-07-12 08:25
@carlopi Duplicate of https://github.com/oven-sh/bun/issues/337. Please post your findings there.

**Closed as completed by FinnRG** 2022-07-12 08:25 UTC
Labels: bug, needs repro
