### ISSUE TITLE
Cannot build with --sourcemap option when importing PM2 module

### ISSUE THREAD

**Issue by luan-brasilfone** [oven-sh/bun#10713] opened 2024-04-30 23:06 UTC
### What version of Bun is running?

1.1.6+e58d67b46

### What platform is your computer?

Linux 5.15.0-105-generic x86_64 x86_64

### What steps can reproduce the bug?

Install PM2 module ```npm i pm2```
Import it ```import * as pm2 from "pm2"```
Try to build it with ```bun build --compile --sourcemap file.ts```

### What is the expected behavior?

To compile sucessfully

### What do you see instead?

The compiling never ends. No output whatsoever is showed.

### Additional information

My package.json's PM2 module is on version 5.3.1

**Comment by Jarred-Sumner** [comment] 2024-04-30 23:07
Duplicate of #10624

**Comment by Jarred-Sumner** [comment] 2024-04-30 23:07
This was fixed in #10625, and will be released in Bun v1.1.7

To get the fix early, run `bun upgrade --canary`

**Closed as completed by Jarred-Sumner** 2024-04-30 23:07 UTC
Labels: bug
