### ISSUE TITLE
Move the [installed/total-packages] when installing to be first

### ISSUE THREAD

**Issue by Newbie012** [oven-sh/bun#4567] opened 2023-09-08 09:02 UTC
### What is the problem this feature would solve?

When installing using `bun install`, it's pretty fast. too fast that I can barely read what's the status of the installation process.

### What is the feature you are proposing to solve the problem?

Instead of placing it at the end of the the dependency name, move it first, since each dependency name has a different length (which makes it hard to read what's after it)

```diff
bun install v0.8.1 (16b4bf34)
-  🚚 ... [3403/3405] 
+  [3403/3405] 🚚 ... 
```

**Comment by Electroid** [comment] 2023-10-27 19:25
Duplicate of #480

**Closed as not planned by Electroid** 2023-10-27 19:24 UTC
Labels: enhancement, bun install
