### ISSUE TITLE
 " bun add tailwindcss " freeze (stuck) installation and doesn't add package

### ISSUE THREAD

**Issue by GameDevBhavesh** [oven-sh/bun#426] opened 2022-07-08 09:30 UTC
![image](https://user-images.githubusercontent.com/38570988/177962953-b81154a0-efff-4971-8b2d-db898c140b86.png)

**Comment by fzn0x** [comment] 2022-07-08 10:14
In which package did it freeze?

**Comment by FinnRG** [comment] 2022-07-08 14:49
@GameDevBhavesh  I'm unable to reproduce this issue. Are you using the latest version (v0.1.2)? If not, please upgrade using bun upgrade. If you're using the latest version, and you still see this issue, please provide further details like your OS, architecture and a verbose log.

**Comment by Jarred-Sumner** [comment] 2022-09-17 06:57
Should be fixed as of Bun v0.1.12. Please comment if it isn't.

**Closed as completed by Jarred-Sumner** 2022-09-17 06:57 UTC
