### ISSUE TITLE
[Crash] robot.js LoadLibrary failed: A dynamic link library (DLL)

### ISSUE THREAD

**Issue by tiagozip** [oven-sh/bun#12621] opened 2024-07-17 09:14 UTC
### How can we reproduce the crash?

**package.json**
```json
{
  "name": "mousekm",
  "module": "index.js",
  "type": "module",
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "robotjs": "^0.6.0"
  }
}
```
**index.js**
```javascript
import { setInterval } from 'bun:timers';
import robot from 'robotjs';

let previousMousePosition = robot.getMousePos();
let totalDistance = 0;

function calculateDistance(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2));
}

setInterval(() => {
  const currentMousePosition = robot.getMousePos();
  const distance = calculateDistance(
    previousMousePosition.x,
    previousMousePosition.y,
    currentMousePosition.x,
    currentMousePosition.y
  );

  totalDistance += distance;
  previousMousePosition = currentMousePosition;

  const distanceInKilometers = totalDistance / 1000000;
  console.log(`Mouse has traveled: ${distanceInKilometers.toFixed(6)} km`);
}, 100);
````
**jsconfig.json**
```js
{
  "compilerOptions": {
    // Enable latest features
    "lib": ["ESNext", "DOM"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleDetection": "force",
    "jsx": "react-jsx",
    "allowJs": true,

    // Bundler mode
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,

    // Best practices
    "strict": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,

    // Some stricter flags (disabled by default)
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noPropertyAccessFromIndexSignature": false
  }
}
```

### Relevant log output

```shell
1 | var robotjs = require('./build/Release/robotjs.node');
        ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at C:\<path>\node_modules\robotjs\index.js:1:5

Bun v1.1.17 (Windows x64)
============================================================
Bun v1.1.17 (bb66bba1) Windows x64
Args: "C:\Users\HUAWEI\.bun\bin\bun.exe" "run" "index.js"
Features: jsc tsconfig(2) 
Builtins: "bun:main" "node:timers" 
Elapsed: 375ms | User: 62ms | Sys: 93ms
RSS: 100.00MB | Peak: 100.00MB | Commit: 0.14GB | Faults: 24676

panic(main thread): Segmentation fault at address 0x7FFAB780976C
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.17/wr1bb66bbaAiggggE_CU\ntdll.dll+k/gBCU\ntdll.dll6wxbCU\ntdll.dll8vsbCa\KERNEL32.DLL21gRCa\ucrtbase.dlloq2wBCa\ucrtbase.dll089mBsy+2Fkuf+k3gHA20//Bpp09voC
```

### Stack Trace (bun.report)

Bun v1.1.17 ([`bb66bba`](<https://github.com/oven-sh/bun/tree/bb66bba1bf6d57983e7efef7ab706bce12137028>)) on windows x86_64 [RunCommand]

Segmentation fault at address 0x7FFAB780976C

- *1 unknown/js code*
- ??? at `0x83e4f` in ntdll.dll
- ??? at `0x6e30d` in ntdll.dll
- ??? at `0x6d8fe` in ntdll.dll
- ??? at `0x4415b` in KERNEL32.DLL
- ??? at `0xc2ca4` in ucrtbase.dll
- ??? at `0x9bbca` in ucrtbase.dll
- [`Global.zig:123`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/Global.zig#L123>): `exitWide`
- [`Global.zig:106`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/Global.zig#L106>): `exit`
- [`bun_js.zig:313`](<https://github.com/oven-sh/bun/blob/bb66bba1bf6d57983e7efef7ab706bce12137028/src/bun_js.zig#L313>): `start`

**Comment by tiagorangel2011** [comment] 2024-07-17 09:15
Yes

**Comment by dayblox** [comment] 2024-07-19 14:58
Same thing with the [cap](https://www.npmjs.com/package/cap) lib

**Comment by Jarred-Sumner** [comment] 2024-08-08 20:02
RobotJS uses [V8 C++ APIs](https://github.com/octalmage/robotjs/blob/8ae87a91f06f49559f0db387bc2bd1ea01419880/src/robotjs.cc#L447)

@190n is actively implementing support for V8 C++ APIs in Bun

Please follow along in #4290

**Comment by Jarred-Sumner** [comment] 2024-08-08 20:03
Duplicate of #4290

**Closed as not planned by Jarred-Sumner** 2024-08-08 20:03 UTC
Labels: crash, windows, runtime
