### ISSUE TITLE
Package Manager: Existing saved packages move between dependency types if a flag is specified

### ISSUE THREAD

**Issue by jenewland1999** [oven-sh/bun#5901] opened 2023-09-22 09:20 UTC
### What is the problem this feature would solve?

If I have a package defined under `dependencies` object in the `package.json` file and want it under one of the other dependency types (e.g. `devDependencies`) I currently have to run `bun remove <depname>` and then `bun add -D <depname>`.

### What is the feature you are proposing to solve the problem?

This feature would allow a saved package in the `package.json` to move from one dependency type (e.g., `dependencies`, `devDependencies` `peerDependencies`, etc.) to another when using `bun add` for that already existing package.

Example:

Before:

```jsonc
// package.json
{
  "dependencies": {
    "@types/react": "^18.2.0"
  }
}
```

Run `bun add -D @types/react`

After:

```jsonc
// package.json
{
  "devDependencies": {
    "@types/react": "^18.2.0"
  }
}
```

### What alternatives have you considered?

- command alias - too much effort
- use alternative package manager - too slow
- raise an issue on the bun github - oh, wait you're raading that 😉

**Comment by Electroid** [comment] 2023-09-22 17:06
Duplicate of #5714

**Closed as not planned by Electroid** 2023-09-22 17:06 UTC
Labels: enhancement, bun install

**Comment by jenewland1999** [comment] 2023-09-22 21:10
My bad! I did try searching before but guess I didn't try hard enough. 🤦🏻
