### ISSUE TITLE
"Failed to resolve" with very slow Internet

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5210] opened 2023-09-13 05:26 UTC
Hey guys! I can't run bun install or bun add [whatever] when I'm connected to my Starlink network. It stays "Resolving [1/6]" up to 6/6 for a long time and breaks with "failed to resolve". When I'm connected with my regular cable internet, it just works normally. 

I changed the DNS from Google's to Cloudflare's to check if this could be the reason, but it just breaks as well. Any hints?

_Originally reported on Discord: [`Bun install / bun add [whatever] does not work with Starlink internet`](https://discord.com/channels/876711213126520882/1151387948105875487/1151387948105875487)_

**Comment by nektro** [comment] 2024-05-24 05:33
does this still reproduce for you? happy to look into it if so. (you may need to run `bun upgrade`)

**Comment by nektro** [comment] 2024-05-24 05:38
unable to reproduce this with artificial limiting to 780kbps/330kbps internet so I'm going to close this for now. if anyone runs into this, please let us know :)

**Closed as completed by nektro** 2024-05-24 05:38 UTC
Labels: bug, bun install
