### ISSUE TITLE
bun crashes on sv create

### ISSUE THREAD

**Issue by SnowSquire** [oven-sh/bun#15101] opened 2024-11-12 10:29 UTC
### How can we reproduce the crash?

run sv create v0.6.1 with the options below. crashes consistently on windows. maybe related to the clean working directly error in sv create. since the dir was empty at the start.

specifically it crashes when selecting drizzle

### Relevant log output

```shell
bunx sv@latest create lol
T  Welcome to the Svelte CLI! (v0.6.1)
|
o  Which template would you like?
|  SvelteKit minimal
|
o  Add type checking with Typescript?
|  Yes, using Typescript syntax
|
*  Project created
|
o  What would you like to add to your project? (use arrow keys / space bar)
|  prettier, eslint, vitest, tailwindcss, drizzle, lucia
|
o  Preconditions not met ----------------------------+
|                                                    |
|  - clean working directory (Found modified files)  |
|                                                    |
+----------------------------------------------------+
|
o  Preconditions failed. Do you wish to continue?
|  Yes
|
o  tailwindcss: Which plugins would you like to add?
|  none
|
o  drizzle: Which database would you like to use?
|  SQLite
|
o  drizzle: Which SQLite client would you like to use?
|  libSQL
============================================================
```

### Stack Trace (bun.report)

Bun v1.1.34 ([`5e5e7c6`](<https://github.com/oven-sh/bun/tree/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x00000005

- *3 unknown/js code*
- [`LLIntSlowPaths.cpp:946`](<https://github.com/oven-sh/bun/blob/5e5e7c60f1004c79a3f87e1f5470ee19d57f10d0/C:/a/WebKit/WebKit/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp#L946>): `llint_slow_path_get_by_id`
- *2 unknown/js code*
- `llint_entry`

Features: Bun.stdin, Bun.stdout, fetch, jsc

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/5616831444/">BUN-2B1</a></strong></sub>

**Comment by nektro** [comment] 2024-11-13 01:39
duplicate of https://github.com/oven-sh/bun/issues/14926

**Closed as not planned by nektro** 2024-11-13 01:39 UTC
Labels: crash, windows, runtime
