### ISSUE TITLE
return new Response(Bun.file()) is slower than return new Response(await Bun.file().text())

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#13124] opened 2024-08-06 12:45 UTC
### What version of Bun is running?

1.1.21+70ca2b76c

### What platform is your computer?

Linux 6.5.0-44-generic x86_64 x86_64

### What steps can reproduce the bug?

```ts
Bun.serve({
    fetch() {
        return new Response(Bun.file(import.meta.filename));
    },
});
```
```
oha -n 10000 http://localhost:3000
```
Requests/sec: 13213.8996
Success rate: 97.41%

```ts
Bun.serve({
    async fetch() {
        return new Response(await Bun.file(import.meta.filename).text(), {
            headers: { "content-type": "text/plain" },
        });
    },
});
```
```
oha -n 10000 http://localhost:3000
```
Requests/sec: 29597.6378
Success rate: 100.00%

**Comment by cirospaciari** [comment] 2024-08-06 13:06
We did some fixes on the server can you try `bun upgrade --canary` and see if is still happening?

**Comment by huseeiin** [comment] 2024-08-06 14:09
> We did some fixes on the server can you try `bun upgrade --canary` and see if is still happening?

it got much better after upgrading. but there's still some bottleneck. the success rate became 100.00% and the req/s got to ~25k (but 2nd example still wins at ~30k)

> We did some fixes on the server can you try `bun upgrade --canary` and see if is still happening?

**Comment by TiBianMod** [comment] 2024-08-06 17:17
also `Bun.file(u).text()` has a higher memory usage.

> nice to see improvements on `canary`

**Comment by zoto-ff** [comment] 2024-08-06 21:22
#11228

**Comment by Electroid** [comment] 2024-08-07 00:28
Duplicate of https://github.com/oven-sh/bun/issues/11228

**Closed as not planned by Electroid** 2024-08-07 00:28 UTC
Labels: bug, needs triage
