### ISSUE TITLE
SyntaxError: Export named 'HTTPParser' not found in module 'http' - Bun test with Vercel's AI SDK v4.0.10

### ISSUE THREAD

**Issue by pavelsvitek** [oven-sh/bun#15535] opened 2024-12-02 12:22 UTC
### What version of Bun is running?

1.1.38

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

1. `pnpm install ai@^4`
2. `pnpm install @types/bun`
3. create test file (from docs https://sdk.vercel.ai/docs/ai-sdk-core/testing#generatetext)
4. `bun test`

**Notes**

* This issue appears when upgrading from `ai@3` to `ai@4`, but it doesn't seem to be a `ai` package problem - test works well with `vitest` 

```ts
import { generateText } from 'ai';
import { MockLanguageModelV1 } from 'ai/test';
import { expect, it } from 'bun:test';


it('should work', async () => {
  const result = await generateText({
    model: new MockLanguageModelV1({
      doGenerate: async () => ({
        rawCall: { rawPrompt: null, rawSettings: {} },
        finishReason: 'stop',
        usage: { promptTokens: 10, completionTokens: 20 },
        text: `Hello, world!`,
      }),
    }),
    prompt: 'Hello, test!',
  });

  expect(result.text).toInclude('Hello, world!');
});

```

Error

![Image](https://github.com/user-attachments/assets/f3a98d1a-88db-4fb0-9386-21e295f58bf0)

### What is the expected behavior?

Test should run

### What do you see instead?

Test is failing due to `SyntaxError: Export named 'HTTPParser' not found in module 'http'.`

### Additional information

* This issue appears when upgrading from `ai@3` to `ai@4`, but it doesn't seem to be a `ai` package problem - test works well with `vitest`

**Comment by cirospaciari** [comment] 2024-12-03 00:56
`HTTPParser` is a internal API in node.js (not documented) and is not implemented/exposed on bun yet

For reference:
https://github.com/nodejs/node/blob/main/src/node_http_parser.cc
https://github.com/nodejs/node/blob/main/typings/internalBinding/http_parser.d.ts

**Comment by Jarred-Sumner** [comment] 2024-12-04 21:38
Duplicate of https://github.com/oven-sh/bun/issues/13072

**Comment by Jarred-Sumner** [comment] 2024-12-04 21:38
Please follow along in https://github.com/oven-sh/bun/issues/13072

**Closed as not planned by Jarred-Sumner** 2024-12-04 21:38 UTC
Labels: bug, node.js, node:http
