### ISSUE TITLE
error: zlib.createBrotliDecompress is not implemented

### ISSUE THREAD

**Issue by egeominotti** [oven-sh/bun#8308] opened 2024-01-20 20:37 UTC
### What version of Bun is running?

1.0.24+6fa35839c

### What platform is your computer?

Linux 6.1.0-17-arm64 aarch64 unknown

### What steps can reproduce the bug?

When use ccxt last version.

### What is the expected behavior?

![Screenshot 2024-01-20 alle 21 37 37](https://github.com/oven-sh/bun/assets/2592071/59e85875-c646-469a-917d-d7a3ed3f1722)

### What do you see instead?

309 |                 });
310 |                 return;
311 |             }
312 |             // For br
313 |             if (codings === 'br') {
314 |                 body$1 = Stream.pipeline(body$1, zlib__default["default"].createBrotliDecompress(), error => {
                                                       ^
error: zlib.createBrotliDecompress is not implemented
      at node:zlib:2269:65
      at /home/viperblock/skamm-v2/tas/src/dev/node_modules/ccxt/dist/cjs/src/static_dependencies/node-fetch/index.js:314:50
      at node:http:887:29

**Comment by Jarred-Sumner** [comment] 2024-01-21 10:54
Duplicate of #267

**Closed as not planned by Jarred-Sumner** 2024-01-21 10:54 UTC
Labels: bug
