### ISSUE TITLE
Support `node:test` module

### ISSUE THREAD

**Issue by jakub791** [oven-sh/bun#3535] opened 2023-07-05 21:08 UTC
### What version of Bun is running?

0.6.13

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Create a file `main.test.ts` with this code:
```ts
import { describe, expect, test } from "test";

describe("addition", () => {
    test("2 + 2 equals 4", () => {
        expect(2 + 2).toBe(4);
    });
});
```
then run `bun test` to run the tests.

### What is the expected behavior?

The tests should be excuted without any errors.

### What do you see instead?

I get an error
```
Could not resolve: "test". Maybe you need to "bun install"?

import { describe, expect, test } from "test";
```

### Additional information

If I import from `bun:test` instead the code works fine.

**Comment by Electroid** [comment] 2023-07-05 21:39
It looks like the npm package, [`test`](https://www.npmjs.com/package/test) is a port of Node.js's new test runner APIs. It's similar to Jest/Bun, but not exactly the same. We'll need to add support for it, or at least alias it.

**Comment by jakub791** [comment] 2023-07-05 21:52
So `bun:test` will continue to work, but `test` not since it conflicts with an npm package name?

**Comment by TiranexDev** [comment] 2023-07-15 02:15
How about we add the alias only if the file was runned with bun test

**Comment by styfle** [comment] 2024-04-15 21:28
- Related to https://github.com/oven-sh/bun/issues/5090

**Comment by Jarred-Sumner** [comment] 2024-04-15 21:29
Duplicate of https://github.com/oven-sh/bun/issues/5090

**Comment by Jarred-Sumner** [comment] 2024-04-15 21:29
Closing as duplicate

**Closed as not planned by Jarred-Sumner** 2024-04-15 21:29 UTC
Labels: bug, node.js
