### ISSUE TITLE
Windows crash on bun install

### ISSUE THREAD

**Issue by metaspartan** [oven-sh/bun#11653] opened 2024-06-06 16:51 UTC
### Stack Trace (bun.report)

Bun v1.1.13-canary ([`8d6f195`](<https://github.com/oven-sh/bun/tree/8d6f19516f7f9932e9b52695998f0f06ccad2e27>)) on windows x86_64 [InstallCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '\packages\'. Please open an issue on GitHub with a reproduction.

- [`debug.zig:373`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/deps/zig/lib/std/debug.zig#L373>): `panicExtra`
- [`debug.zig:348`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/deps/zig/lib/std/debug.zig#L348>): `panic`
- [`sys_uv.zig:59`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/sys_uv.zig#L59>): `open`
- [`sys.zig:1142`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/sys.zig#L1142>): `open`
- [`install.zig:7703`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/install/install.zig#L7703>): `initWithCLI`
- [`filter_run.zig:403`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/cli/filter_run.zig#L403>): `install`
- [`cli.zig:1461`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/cli.zig#L1461>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/8d6f19516f7f9932e9b52695998f0f06ccad2e27/src/src/startup/exe_common.inl#L78>): `invoke_main`

**Comment by Electroid** [comment] 2024-06-06 20:17
Could you share your package.json?

**Comment by metaspartan** [comment] 2024-06-06 20:27
```
{
  "name": "redacted",
  "version": "1.0.0",
  "description": "redacted",
  "main": "index.ts",
  "scripts": {
    "start": "bun run index.ts",
    "build": "bun build index.ts"
  },
  "dependencies": {
    "@logtail/node": "^0.4.21",
    "dotenv": "^16.4.5",
    "nats.ws": "^1.0.0",
    "typescript": "^5.4.5",
    "ws": "^8.17.0"
  },
  "devDependencies": {
    "@types/bun": "latest",
    "@types/node": "^18.14.1"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "author": "redacted",
  "license": "redacted"
}
```

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:55
Duplicate of https://github.com/oven-sh/bun/issues/11215

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:55
Please follow along in https://github.com/oven-sh/bun/issues/11215

**Closed as not planned by Jarred-Sumner** 2024-08-06 07:55 UTC
Labels: bun install
