### ISSUE TITLE
InstructionError at 0x45CEE60200000000

### ISSUE THREAD

**Issue by FromCppToCarbon** [oven-sh/bun#1447] opened 2022-11-02 12:11 UTC
### What version of Bun is running?

0.2.2

### What platform is your computer?

ubuntu untity 22.10

### What steps can reproduce the bug?

i am trying to run the server http.js  file  which is on the bun. sh site to print welcome to bun  just to make sure bun is working and this is the code  : 
```js
export default {
  port: 3000,
  fetch(request) {
    return new Response("Welcome to Bun!");
  },
};
```

but i get :

```
InstructionError at 0x45CEE60200000000
----- bun meta -----
Bun v0.2.2 (6632135e) Linux x64 #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022
RunCommand: 
Elapsed: 0ms | User: 1ms | Sys: 0ms
RSS: 67.11MB | Peak: 5.93MB | Commit: 67.11MB | Faults: 0
```

### How often does it reproduce? Is there a required condition?

every try 
### What is the expected behavior?

The above error 
### What do you see instead?

InstructionError at 0x45CEE60200000000

**Comment by Electroid** [comment] 2023-10-25 18:51
Duplicate of #1167

**Closed as completed by Electroid** 2023-10-25 18:51 UTC
Labels: bug
