### ISSUE TITLE
Crash with canvas library

### ISSUE THREAD

**Issue by Ken-Yim** [oven-sh/bun#13191] opened 2024-08-09 07:45 UTC
### How can we reproduce the crash?

Bun v1.1.22-canary.96+df33f2b2a (Windows x64)
============================================================
Bun Canary v1.1.22-canary.96 (df33f2b2) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\ken\AppData\Roaming\npm\node_modules\bun\bin\bun.exe" "index.js"
Features: jsc tsconfig(9)
Builtins: "bun:main" "detect-libc" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:net" "node:os" "node:path" "node:querystring" "node:readline" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "ws"
Elapsed: 13015ms | User: 296ms | Sys: 140ms
RSS: 0.17GB | Peak: 0.19GB | Commit: 0.21GB | Faults: 53033

### Relevant log output

```shell
1 | 'use strict'
2 |
3 | const bindings = require('../build/Release/canvas.node')
          ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at C:\Users\ken\Kenfil-Eval-Bun\node_modules\canvas\lib\bindings.js:3:7
      at C:\Users\ken\Kenfil-Eval-Bun\node_modules\canvas\lib\canvas.js:9:7
      at C:\Users\ken\Kenfil-Eval-Bun\node_modules\canvas\index.js:1:7
      at C:\Users\ken\Kenfil-Eval-Bun\index.js:19:23
```

### Stack Trace (bun.report)

Bun v1.1.22 ([`df33f2b`](<https://github.com/oven-sh/bun/tree/df33f2b2a264912c7a742d0c03587082415fbba6>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FFD09943460

- *1 unknown/js code*
- ??? at `0x5177c` in ntdll.dll
- ??? at `0x514d7` in ntdll.dll
- ??? at `0x5117d` in ntdll.dll
- ??? at `0x17fab` in KERNEL32.DLL
- [`exit.cpp:137`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/appcrt/startup/exit.cpp#L137>): `exit_or_terminate_process`
- [`exit.cpp:274`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/appcrt/startup/exit.cpp#L274>): `common_exit`
- [`Global.zig:121`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/Global.zig#L121>): `exit`
- [`javascript.zig:1262`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/bun.js/javascript.zig#L1262>): `globalExit`
- [`shimmer.zig:197`](<https://github.com/oven-sh/bun/blob/df33f2b2a264912c7a742d0c03587082415fbba6/src/bun.js/bindings/shimmer.zig#L197>): `cppFn`

**Comment by Jarred-Sumner** [comment] 2024-08-09 07:52
Duplicate of #5835

**Comment by Jarred-Sumner** [comment] 2024-08-09 07:52
Please try using `canvas@next` instead of `canvas@latest`

We are tracking this in #5835

**Closed as not planned by Jarred-Sumner** 2024-08-09 07:52 UTC
Labels: crash, windows, runtime
