### ISSUE TITLE
TypeError when trying to run Node app in Windows 11

### ISSUE THREAD

**Issue by asampal** [oven-sh/bun#9890] opened 2024-04-03 14:01 UTC
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

I attempted to run my application with bun instead of Node

### What is the expected behavior?

The application should run.

### What do you see instead?

```
C:\Users\asampaleanu\.bun\bin\bun.exe --debug-brk=59845 --expose_debug_as=v8debug C:\devenv\projects\ps\ps\services\igo-terminal-server-ms\igo-ms.js <bunch of parameters>
4 | /**
5 |  * [Server description]
6 |  * @docs https://tools.ietf.org/html/rfc1034
7 |  * @docs https://tools.ietf.org/html/rfc1035
8 |  */
9 | class Server extends udp.Socket {
    ^
TypeError: The value of the superclass's prototype property is not an object or null.
      at C:\devenv\projects\ps\ps\node_modules\dns2\server\udp.js:9:1
      at C:\devenv\projects\ps\ps\node_modules\dns2\server\index.js:1:7
      at C:\devenv\projects\ps\ps\node_modules\dns2\index.js:8:3
      at C:\devenv\projects\ps\ps\services\igo-terminal-server-ms\igo-ms.js:23:5

Process finished with exit code 1
```

**Comment by Electroid** [comment] 2024-04-09 00:22
Duplicate of #1630

**Closed as not planned by Electroid** 2024-04-09 00:22 UTC
Labels: bug
