### ISSUE TITLE
Support cloudflare wrangler

### ISSUE THREAD

**Issue by bkniffler** [oven-sh/bun#7290] opened 2023-11-23 14:20 UTC
### What is the problem this feature would solve?

Error when trying to use wrangler, e.g. to run a test for a cloudflare worker.

### Message
`[bun] Warning: worker_threads.Worker option "execArgv" is not implemented.`

### Code example
```ts
import {expect, test} from 'bun:test'
import {unstable_dev} from 'wrangler'
import {join} from 'path'

const root = join(__dirname, '../../..')
test('durable-objects', async () => {
  const handler  = await unstable_dev(join(root, 'src/index.ts'), {
    config: join(root, 'wrangler.toml'),
    experimental: {
      disableExperimentalWarning: true,
      disableDevRegistry: true
    },
    bundle: false,
    compatibilityDate: '2023-10-10',
    local: true,
    logLevel: 'debug',
  });
  const res =await handler.fetch('http://worker.dev', {});
  const json = await res.json();
  expect(json).toEqual({hello: 'world'});
});
```

### What is the feature you are proposing to solve the problem?

Add support for execArgv and thus for wrangler.

### What alternatives have you considered?

Use vitest/jest.

**Comment by bkniffler** [comment] 2023-11-23 14:21
Here is the execArgv support issue: https://github.com/oven-sh/bun/issues/4130

**Comment by Electroid** [comment] 2023-11-24 01:28
Duplicate of #4130

**Closed as not planned by Electroid** 2023-11-24 01:28 UTC
Labels: enhancement

**Comment by bkniffler** [comment] 2024-03-04 15:07
Still not working yet unfortunately, waiting for https://github.com/oven-sh/bun/issues/8867 to work for unstable_dev, for anyone stumbling upon this

**Comment by bkniffler** [comment] 2024-03-04 15:09
As well as https://github.com/oven-sh/bun/issues/4165

**Comment by jbergstroem** [comment] 2024-12-17 10:10
Just ran across this and it still doesn't fully work for me. Did a reproduction repo here: https://github.com/jbergstroem/bun-wrangler-test
