### ISSUE TITLE
Crash while running `bun run dev` for rsbuild svelte app

### ISSUE THREAD

**Issue by Sovenok-Hacker** [oven-sh/bun#14078] opened 2024-09-21 06:41 UTC
### How can we reproduce the crash?

- Create a project with `bun create rsbuild@latest`, select JavaScript and Svelte

### Relevant log output

```shell
09:38:31 owl@PC sichevnya-frontend → bun run dev
$ rsbuild dev --open

  Rsbuild v1.0.5

  > Local:    http://localhost:3000/
  > Network:  http://192.168.1.17:3000/

start   Compiling...
error   Failed to open start URL.
error   TypeError: Executable not found in $PATH: "/home/owl/sichevnya/sichevnya-frontend/node_modules/@rsbuild/core/compiled/open/xdg-open"
    at spawn (native)
    at spawn (node:child_process:764:8)
    at spawn (node:child_process:2:15)
    at <anonymous> (/home/owl/sichevnya/sichevnya-frontend/node_modules/@rsbuild/core/compiled/open/index.js:264:41)
    at processTicksAndRejections (:12:39)
============================================================
Bun v1.1.29 (6d43b366) Linux x64
Linux Kernel v6.10.10 | glibc v2.40
CPU: sse42 popcnt avx avx2
Args: "node" "/home/owl/sichevnya/sichevnya-frontend/node_modules/.bin/rsbuild" "dev" "--open"
Features: jsc Bun.stdin(2) http_server transpiler_cache(18) 
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:querystring" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:inspector" 
Elapsed: 449ms | User: 519ms | Sys: 121ms
RSS: 1.05GB | Peak: 0.40GB | Commit: 1.05GB | Faults: 0

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.29/ln16d43b36AqgghQui299D+8oP__+rwg0Dy85vyE28ingF4u131D__A2AK
```

### Stack Trace (bun.report)

Bun v1.1.29 ([`6d43b36`](<https://github.com/oven-sh/bun/tree/6d43b366220099042f28c5fa5c66185fe2580539>)) on linux x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`BunProcess.cpp:2645`](<https://github.com/oven-sh/bun/blob/6d43b366220099042f28c5fa5c66185fe2580539/src/bun.js/bindings/BunProcess.cpp#L2645>): `Bun::jsFunctionDrainMicrotaskQueue`

Features: jsc, Bun.stdin, http\_server, transpiler\_cache

**Comment by Sovenok-Hacker** [comment] 2024-09-21 06:53
UPD: Looks like it calls spawn() for non-existent file, but I think it shouldn't crash Bun

**Comment by Jarred-Sumner** [comment] 2024-09-21 08:38
Duplicate of #11628

**Comment by Jarred-Sumner** [comment] 2024-09-21 08:39
We are tracking this in #11628, please follow along there

**Closed as not planned by Jarred-Sumner** 2024-09-21 08:39 UTC
Labels: crash
