### ISSUE TITLE
More detailed error printing in `bun:sqlite`

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5509] opened 2023-09-15 21:43 UTC
_Originally reported on Discord: [`I'm using `bun:sqlite` and I'm getting constrai...`](https://discord.com/channels/876711213126520882/1152355834442027009/1152355835964559401)_

**Comment by Electroid** [comment] 2023-10-27 23:54
Duplicate of #871

**Closed as not planned by Electroid** 2023-10-27 23:54 UTC
