### ISSUE TITLE
fsPromises.open returns number, is not Node.js compatible

### ISSUE THREAD

**Issue by gutenye** [oven-sh/bun#3737] opened 2023-07-22 02:04 UTC
### What version of Bun is running?

0.6.14

### What steps can reproduce the bug?

```ts
import fs from 'fs/promises'
console.log(await fs.open('a.txt'))
```

### What is the expected behavior?

Output `FileHandle` object

### What do you see instead?

Output a `number`  (fd)

### Additional information

Node doc: https://nodejs.org/api/fs.html#fspromisesopenpath-flags-mode
[Bun doc](https://bun.sh/docs/runtime/nodejs-apis#node_fs) does not methon this is missing

**Comment by asilvas** [comment] 2023-07-29 00:03
Duplicate of https://github.com/oven-sh/bun/issues/3167

**Comment by colinhacks** [comment] 2023-09-13 06:06
We're going to track this at #3167

**Closed as completed by colinhacks** 2023-09-13 06:06 UTC
Labels: bug, node.js
