### ISSUE TITLE
dependence error ubuntu 18.04

### ISSUE THREAD

**Issue by vinayyellaram** [oven-sh/bun#383] opened 2022-07-07 17:43 UTC
bun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by bun)
bun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by bun)

**Comment by Mukhammadjon571** [comment] 2022-07-07 18:14
It seems that you have to recompile a libc. The problem is that the version of libc is low. If it is not necessary, it is recommended not to compile libc and soft link because libc is the underlying library of the system.

**Comment by FinnRG** [comment] 2022-07-07 23:34
Duplicate of #255.

**Closed as completed** 2022-07-09 00:15 UTC
