### ISSUE TITLE
Switching Between Bun Versions, Similar to "n"

### ISSUE THREAD

**Issue by jabarihunt** [oven-sh/bun#5876] opened 2023-09-21 22:27 UTC
### What is the problem this feature would solve?

Switching between different versions of Bun instantly.

### What is the feature you are proposing to solve the problem?

A feature similar to the [n package](https://www.npmjs.com/package/n) that allows easy switching between Bun versions, but baked directly into Bun itself.  This would allow switching between versions of Bun much easier.  As of this moment Bun is only on 1.0.2, but as versions increase, a tool like this would be extremely convenient when working across different projects.

### What alternatives have you considered?

Uninstalling/reinstalling different versions of Bun manually. :-/

**Comment by Electroid** [comment] 2023-09-21 22:27
Duplicate of #3917

**Comment by Electroid** [comment] 2023-09-21 22:28
This is something we have considered, but are unlikely to do for now.

**Closed as not planned by Electroid** 2023-09-21 22:27 UTC
Labels: enhancement

**Comment by jabarihunt** [comment] 2023-09-21 22:34
> This is something we have considered, but are unlikely to do for now.

I figured it was a pie in the sky request.  I began my first Bun project last night and immediately ran into an issue that didn't seems to be there in 1.0.1 from what I read.  I didn't want to uninstall/reinstall just to try though.  I immediately wished there was a "n" for bun.
