### ISSUE TITLE
wish bun can import http url

### ISSUE THREAD

**Issue by haozi** [oven-sh/bun#9439] opened 2024-03-15 16:02 UTC
### What is the problem this feature would solve?

Just like deno, can import('htttps://xxxx.ts')

### What is the feature you are proposing to solve the problem?

Just like deno, can import('htttps://xxxx.ts')

**Comment by Zeryther** [comment] 2024-03-15 16:59
FYI This is already on the Bun Roadmap (under Runtime: #159)

**Comment by Electroid** [comment] 2024-03-15 17:01
Duplicate of #38

**Closed as not planned by Electroid** 2024-03-15 17:01 UTC
Labels: enhancement
