### ISSUE TITLE
RSBuild React Crash Report

### ISSUE THREAD

**Issue by nathanmayall** [oven-sh/bun#14977] opened 2024-11-03 22:49 UTC
### How can we reproduce the crash?

https://replit.com/@nathanmayall/Bun-bug?v=1

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on linux x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/ld-temp.o#L0>): `llint_call_javascript`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/ld-temp.o#L0>): `JSC::Interpreter::executeCall`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/ld-temp.o#L0>): `JSC::VM::drainMicrotasks`
- [`BunProcess.cpp:2646`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/BunProcess.cpp#L2646>): `Bun::jsFunctionDrainMicrotaskQueue`
- *2 unknown/js code*
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/ld-temp.o#L0>): `llint_call_javascript`

Features: Bun.stdin, http\_server, jsc, spawn, transpiler\_cache, tsconfig

**Comment by nektro** [comment] 2024-11-08 22:20
duplicate of https://github.com/oven-sh/bun/issues/11628

**Closed as not planned by nektro** 2024-11-08 22:20 UTC
Labels: crash, linux
