### ISSUE TITLE
unable to use express js

### ISSUE THREAD

**Issue by prolaxu** [oven-sh/bun#405] opened 2022-07-08 02:29 UTC
hello guys i am trying to make express js  api with bun i am getting errors like this.please help me out.
![Screenshot from 2022-07-07 14-43-37](https://user-images.githubusercontent.com/54370052/177904654-25e6515c-97f2-45b4-b543-9855523050be.png)

**Comment by depapp** [comment] 2022-07-08 02:56
got same error 👀

**Comment by erra0002** [comment] 2022-07-08 04:21
Duplicate of https://github.com/Jarred-Sumner/bun/issues/258 please close this issue and checkout the discussion there

**Closed as completed** 2022-07-08 05:08 UTC
