### ISSUE TITLE
`bun create react-app` fails when npm isn't installed.

### ISSUE THREAD

**Issue by lwander** [oven-sh/bun#6318] opened 2023-10-05 13:06 UTC
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 6.2.0-33-generic x86_64 x86_64

### What steps can reproduce the bug?

Run `bun create react-app` on a system without npm installed.

### What is the expected behavior?

Return code 0 with working react-app scaffolding

### What do you see instead?

```
$ bun create react-app demo

Creating a new React app in /home/lars/dev/viz/demo.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...


Aborting installation.
Unexpected error. Please report it as a bug:
610 |   }
611 |   get stdio() {
612 |     return this.#stdioObject ??= this.#createStdioObject();
613 |   }
614 | 
615 |   spawn(options) {
                 ^
TypeError: Executable not found in $PATH: "npm"
 code: "ERR_INVALID_ARG_TYPE"

      at spawn (node:child_process:615:14)
      at node:child_process:2:40
      at spawn (/tmp/create-react-app@latest--bunx/node_modules/cross-spawn/index.js:12:20)
      at /tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:383:18
      at new Promise (:1:20)
      at install (/tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:334:9)
      at /tmp/create-react-app@latest--bunx/node_modules/create-react-app/createReactApp.js:461:15
      at processTicksAndRejections (:55:76)


Deleting generated file... package.json
Deleting demo/ from /home/lars/dev/viz
Done.
error: "create-react-app" exited with code 1 (SIGHUP)
```

**Comment by LangLangBart** [comment] 2023-10-05 14:05
### similar tickets
- #5908
	- a user's comment suggesting the use of `bunx --bun create-react-app` was
	unsuccessful without the use of `npm`
- #5995


- maybe wait a little bit until this PR is merged ?
	- https://github.com/facebook/create-react-app/pull/13330

**Comment by Electroid** [comment] 2023-10-30 19:34
Closing as duplicate of #5995

**Closed as not planned by Electroid** 2023-10-30 19:34 UTC
Labels: bug
