### ISSUE TITLE
Bundler: Add an option to retain comments

### ISSUE THREAD

**Issue by Nova-Aurora** [oven-sh/bun#11941] opened 2024-06-18 08:00 UTC
### What is the problem this feature would solve?

I write userscripts, and would like to be able to use certain features which require a bundler - multiple files into one, typescript compiler, etc.

Userscripts must have a block of "comments" at the beginning, which contains the configuration for how they are loaded. They **must** have the proper syntax and formatting, or the script is not loaded properly, if at all. The block looks something like this:
```
// ==UserScript==
// @name        Example script 
// @namespace   Violentmonkey Scripts
// @match       *://example.org/*
// @grant       none
// @version     1.0
// @author      Nova Aurora
// ==/UserScript==
```

The current behavior of ESBuild and Bun Bundler is to strip all comments out when bundling. This breaks userscripts.

### What is the feature you are proposing to solve the problem?

I am proposing, if possible in the Bun Bundler's architecture, to allow for an option to preserve all comments embedded into the source as close as possible to their locations as they are in the source. This is the simplest solution, and the one most applicable to other use cases like development builds and debugging in bundled code.

ESBuild has "legal comments", which allows for certain comments to be emitted, but all supported preserve rules (`@liscense`, `@preserve`, `//!`, `/*!`) do not comply with the userscript syntax rules, so porting "legal comments" to Bun Bundler would not, in their current form, solve the use case.

### What alternatives have you considered?

I've considered alternative bundlers, and I have considered writing a bundler plugin that manually injects the requisite code block back into the bundled file, I have not completed it, so I do not know what the complexity of that solution is, and regardless, is another domain-specific solution to a problem that applies to multiple use cases.

**Comment by kravetsone** [comment] 2024-06-18 14:04
esbuild supports banner/footer, but Bun.build doesnt

https://bun.sh/docs/bundler/vs-esbuild
![image](https://github.com/oven-sh/bun/assets/57632712/09c26880-ef76-48be-a2b5-8df4f72ceb61)

**Comment by Electroid** [comment] 2024-06-18 18:50
Duplicate of #2437

**Closed as not planned by Electroid** 2024-06-18 18:50 UTC
Labels: enhancement

**Comment by Nova-Aurora** [comment] 2024-06-18 18:56
> Duplicate of #2437

A cursory search didn't turn that up, sorry for wasting time with duplicates.

**Comment by Nova-Aurora** [comment] 2024-06-18 18:59
> esbuild supports banner/footer, but Bun.build doesnt
> 
> https://bun.sh/docs/bundler/vs-esbuild ![image](https://private-user-images.githubusercontent.com/57632712/340706459-09c26880-ef76-48be-a2b5-8df4f72ceb61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzcyMzYsIm5iZiI6MTcxODczNjkzNiwicGF0aCI6Ii81NzYzMjcxMi8zNDA3MDY0NTktMDljMjY4ODAtZWY3Ni00OGJlLWEyYjUtOGRmNGY3MmNlYjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE4NTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOWRkNzc1MjcyNDc5YWE4ZWZiM2RlOGUwNWVlNzQ0ZjlkN2IyZDFkZGE4Zjg2YzVlYTg4YThkNmMzZDEyZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.83Hd4DirclRC96WJVXupGDdvRoy-Vn4idjrpO1m_qXA)

:thinking: When I was searching through esbuilds options, I didn't see that. Seems like it's an easier build script fit, thanks!

**Comment by chrisbbreuer** [comment] 2024-07-18 11:10
there probably should be an option to persist `vite-ignore` comments, too. Unsure how to avoid them otherwise
