### ISSUE TITLE
Illegal instruction on version > 1.1.15

### ISSUE THREAD

**Issue by YuriVivaldi** [oven-sh/bun#12363] opened 2024-07-05 10:41 UTC
### What version of Bun is running?

1.1.16-18

### What platform is your computer?

Linux 4.4.143 aarch64 aarch64

### What steps can reproduce the bug?

Simply l run `bun src/main.ts` on a ts project, it fails immediately

### What is the expected behavior?

```shell
root@xxx-xxx:/dir/to/project-server# bun src/main.ts
[L] <MA> START
[L] <WS>        -ON-
[L] <SY>        -ON-
[L] <PL> {R}    -ON-
[L] <PL> {S}    -ON-
[L] <PL>        -ON-
[L] <PL> {A}    -ON-
[L] <AC>        -ON-
[L] <SY> {N}    -ON-
[L] <PL> {M}    -ON-
^C[L] <MA>
        Trying to shut down gracefully... SIGINT
[L] <WS>        -OFF-
[L] <PL> {A}    -OFF-
[L] <PL> {M}    -OFF-
[L] <PL> {R}    -OFF-
[L] <PL>        -OFF-
[L] <SY> {N}    -OFF-
[L] <SY>        -OFF-
[L] <AC>        -OFF- close
[L] <AC>        -OFF-

``` 

### What do you see instead?

```shell
root@xxx-xxx:/dir/to/project-server# bun src/main.ts
Illegal instruction
root@xxx-xxx:/dir/to/project-server#
```

**Comment by Jarred-Sumner** [comment] 2024-07-05 10:51
Duplicate of #12076

**Comment by Jarred-Sumner** [comment] 2024-07-05 10:51
Please follow along in #12076

**Closed as not planned by Jarred-Sumner** 2024-07-05 10:51 UTC
Labels: bug, needs triage
