### ISSUE TITLE
error: Unsupported dependency type github

### ISSUE THREAD

**Issue by neo773** [oven-sh/bun#355] opened 2022-07-07 12:35 UTC
Hi,

I was trying to install a library called hyper-express via bun package manager and got this error

```
neos-MacBook-Pro:bun neo$ bun add hyper-express
bun add v0.1.1


error: Unsupported dependency type github for "github:uNetworking/uWebSockets.js#v20.10.0"
````

Looks like it does not support installing dependencies from git/github yet

**Comment by FinnRG** [comment] 2022-07-07 23:12
Duplicate of #82 .

**Closed as completed** 2022-07-09 00:15 UTC
