### ISSUE TITLE
Bun crash 

### ISSUE THREAD

**Issue by Benlu-ca** [oven-sh/bun#13102] opened 2024-08-05 23:18 UTC
### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on windows x86_64 [AutoCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '\dist\node'. Please open an issue on GitHub with a reproduction.

- [`string_immutable.zig:814`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/string_immutable.zig#L814>): `eqlComptimeCheckLenU8`
- [`encoding.zig:853`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/webcore/encoding.zig#L853>): `Bun__encoding__toString`
- [`sys.zig:1201`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/sys.zig#L1201>): `openatWindowsTMaybeNormalize`
- [`sys.zig:1303`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/sys.zig#L1303>): `openA`
- [`cache.zig:166`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/cache.zig#L166>): `readFileWithAllocator`
- [`bundler.zig:1318`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bundler.zig#L1318>): `parseMaybeReturnFileOnlyAllowSharedBuffer`
- [`string_immutable.zig:806`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/string_immutable.zig#L806>): `eqlComptimeCheckLenU8`
- [`module_loader.zig:2413`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/module_loader.zig#L2413>): `Bun__transpileFile`
- [`xmemory:1501`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/include/xmemory#L1501>): `std::_Compressed_pair<std::default_delete<WTF::Detail::CallableWrapperBase<void,JSC::JSGlobalObject *,JSC::Identifier,WTF::Vector<JSC::Identifier,4,WTF::CrashOnOverflow,16,WTF::FastMalloc> &,JSC::MarkedVector<JSC::JSValue,8,WTF::RecordOverflow> &> >,WTF::Detail::CallableWrapperBase<void,JSC::JSGlobalObject *,JSC::Identifier,WTF::Vector<JSC::Identifier,4,WTF::CrashOnOverflow,16,WTF::FastMalloc> &,JSC::MarkedVector<JSC::JSValue,8,WTF::RecordOverflow> &> *,1>::_Compressed_pair`
- [`Handle.h:60`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/C:/a/bun/bun/build/bun-webkit/include/JavaScriptCore/Handle.h#L60>): `JSC::HandleBase::HandleBase`

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:53
[Duplicate of #12922 ](https://github.com/oven-sh/bun/issues/13102)

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:54
Please follow along in https://github.com/oven-sh/bun/issues/10830

**Closed as not planned by Jarred-Sumner** 2024-08-06 07:54 UTC
Labels: crash, windows
