### ISSUE TITLE
rsbuild dev server crashes

### ISSUE THREAD

**Issue by kevnzac** [oven-sh/bun#12848] opened 2024-07-26 11:00 UTC
### How can we reproduce the crash?

on windows create an rsbuild project:

bun create rsbuild@latest

cd into the project folder and run:

bun i
bun run dev

### Relevant log output

```shell
$ rsbuild dev --open

  Rsbuild v1.0.1-beta.3

  > Network:  http://192.168.1.7:3000/
  > Local:    http://localhost:3000/

start   Compiling...
============================================================
Bun v1.1.20 (ae194892) Windows x64
CPU: sse42 avx avx2 avx512
Args: "node" "E:\rsbproj\node_modules\@rsbuild\core\bin\rsbuild.js" "dev" "--open"
Features: jsc Bun.stdin(2) http_server spawn transpiler_cache(18) tsconfig(2)
Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:v8" "node:inspector"
Elapsed: 23214ms | User: 2765ms | Sys: 953ms
RSS: 0.47GB | Peak: 0.47GB | Commit: 0.66GB | Faults: 126045

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.20/wn1ae19489Aqggh0Csg5v5B___A2AK

error: script "dev" exited with code 3
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- [`JSCellInlines.h:239`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/C:/a/WebKit/WebKit/Source/JavaScriptCore/runtime/JSCellInlines.h#L239>): `JSC::JSCell::isString`
- *3 unknown/js code*

**Comment by dylan-conway** [comment] 2024-07-26 19:24
Duplicate of #11628

**Closed as not planned by dylan-conway** 2024-07-26 19:24 UTC
Labels: crash, windows, runtime
