### ISSUE TITLE
fetch api missing client certificate support

### ISSUE THREAD

**Issue by kahirokunn** [oven-sh/bun#9376] opened 2024-03-12 14:00 UTC
### What version of Bun is running?

1.0.30+1424a196f

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

```js
const { Agent } = require('undici');

fetch(url, {
    dispatcher: new Agent({
        connect: {
            cert: cert,
            key: key,
            ca: ca
        }
    })
});
```

```
UNABLE_TO_VERIFY_LEAF_SIGNATURE: unable to verify the first certificate
 path: "xxxxx"
```

### Additional information

Reference: [Native fetch client certificate support · Issue #48977 · nodejs/node](https://github.com/nodejs/node/issues/48977)

**Comment by Electroid** [comment] 2024-03-12 15:56
Duplicate of #7200

**Closed as not planned by Electroid** 2024-03-12 15:56 UTC
Labels: bug, node.js
