### ISSUE TITLE
Implement Worker option argv and execArgv

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#4075] opened 2023-08-09 01:57 UTC
(Current blocker for #3787)

**Comment by birkskyum** [comment] 2023-08-13 00:49
duplicate of #4130

**Comment by birkskyum** [comment] 2023-09-20 22:12
Also, the worker_threads.Worker option "resourceLimits" would be great to have implemented. It often warns next to argv and execArgv

**Comment by Electroid** [comment] 2023-10-26 22:36
Duplicate of https://github.com/oven-sh/bun/issues/4130

**Closed as not planned by Electroid** 2023-10-26 22:36 UTC
Labels: enhancement, node.js
