### ISSUE TITLE
Issue with default Next.js template

### ISSUE THREAD

**Issue by Tejaswgupta** [oven-sh/bun#498] opened 2022-07-09 14:10 UTC
```
{
  "name": "testproject",
  "version": "0.0.53",
  "scripts": {
    "dev": "next dev",
    "build": "next build"
  },
  "main": "index.js",
  "dependencies": {
    "next": "12.1.3",
    "react": "^18",
    "react-dom": "^18",
    "react-is": "^17.0.2"
  },
  "devDependencies": {
    "@types/react": "^18",
    "bun-framework-next": "^12",
    "typescript": "latest",
    "react-refresh": "0.10.0"
  }
}
```

Command:
```
bun run build
```
Output:
```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        npm install --save-dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

info  - Skipping validation of types .Script error "build" exited with 1 status
```

I tried adding it with
```
bun add @types/react
```

I still get the same error.

**Comment by FinnRG** [comment] 2022-07-09 14:26
Duplicate of #379

**Closed as completed by FinnRG** 2022-07-09 14:26 UTC
