### ISSUE TITLE
error when running simple example from `@xenova/transformers`

### ISSUE THREAD

**Issue by universalmind303** [oven-sh/bun#11825] opened 2024-06-12 23:41 UTC
### What version of Bun is running?

1.1.13+bd6a60512

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```sh
bun add @xenova/transformers
```

```ts
// index.js
import { pipeline } from "@xenova/transformers";

// Allocate a pipeline for sentiment-analysis
const pipe = await pipeline("sentiment-analysis");

const out = await pipe("I love transformers!");

console.log(out);
```

```sh
bun run index.js
```

### What is the expected behavior?

```sh
> node index.js
No model specified. Using default model: "Xenova/distilbert-base-uncased-finetuned-sst-2-english".
[ { label: 'POSITIVE', score: 0.999788761138916 } ]
```

### What do you see instead?

```
❯ bun run index.ts                                                     06/12/2024 06:38:01 PM
No model specified. Using default model: "Xenova/distilbert-base-uncased-finetuned-sst-2-english".
22 |         __classPrivateFieldSet(this, _OnnxruntimeSessionHandler_inferenceSession, new binding_1.binding.InferenceSession(), "f");
23 |         if (typeof pathOrBuffer === 'string') {
24 |             __classPrivateFieldGet(this, _OnnxruntimeSessionHandler_inferenceSession, "f").loadModel(pathOrBuffer, options);
25 |         }
26 |         else {
27 |             __classPrivateFieldGet(this, _OnnxruntimeSessionHandler_inferenceSession, "f").loadModel(pathOrBuffer.buffer, pathOrBuffer.byteOffset, pathOrBuffer.byteLength, options);
                                                                                                ^
error: Error
      at new OnnxruntimeSessionHandler (/Users/me/Development/bun-transformers/node_modules/.deno/onnxruntime-node@1.14.0/node_modules/onnxruntime-node/dist/backend.js:27:92)
      at /Users/me/Development/bun-transformers/node_modules/.deno/onnxruntime-node@1.14.0/node_modules/onnxruntime-node/dist/backend.js:64:29

Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback.
[
  {
    label: "POSITIVE",
    score: 0.999788761138916,
  }
]
```

### Additional information

When running via bun, the js process never terminates either

**Comment by Jarred-Sumner** [comment] 2024-06-12 23:43
Duplicate of https://github.com/oven-sh/bun/issues/4619

**Comment by Jarred-Sumner** [comment] 2024-06-12 23:44
We are tracking this in #4619. Please follow along there.

**Closed as not planned by Jarred-Sumner** 2024-06-12 23:44 UTC
Labels: bug, needs triage
