### ISSUE TITLE
Bun repl not working in Bun 1.1.16 on windows

### ISSUE THREAD

**Issue by lunarW1TCH** [oven-sh/bun#12110] opened 2024-06-24 08:41 UTC
### How can we reproduce the crash?

Just type `bun repl` in terminal

### Stack Trace (bun.report)

Bun v1.1.16 ([`bf7b327`](<https://github.com/oven-sh/bun/tree/bf7b327f68568104a5e40c1944b7b255b02f0745>)) on windows x86_64 [BunxCommand]

Segmentation fault at address 0x7FF64E25FEB8

- ??? at `0x111d0` in VCRUNTIME140.dll
- [`install.zig:9601`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/install/install.zig#L9601>): `parse`
- [`bunx_command.zig:280`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/cli/bunx_command.zig#L280>): `exec`
- [`cli.zig:1527`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/cli.zig#L1527>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/bf7b327f68568104a5e40c1944b7b255b02f0745/src/src/startup/exe_common.inl#L78>): `invoke_main`
- ??? at `0x1257d` in KERNEL32.DLL
- ??? at `0x5aa48` in ntdll.dll

**Comment by Jarred-Sumner** [comment] 2024-06-24 08:50
Duplicate of #12070

**Comment by Jarred-Sumner** [comment] 2024-06-24 08:50
This was fixed in #12071 

To get the fix, please run `bun upgrade --canary`

**Closed as not planned by Jarred-Sumner** 2024-06-24 08:50 UTC
Labels: crash, windows
