### ISSUE TITLE
pm2 does not work on cluster mode, any workaround?

### ISSUE THREAD

**Issue by ironydips** [oven-sh/bun#10821] opened 2024-05-04 09:58 UTC
### What version of Bun is running?

1.1.7+b0b7db5c0

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

When running pm2 start index.js -i 3 --interpreter=bun  instead of running in cluster mode, it works in fork mode.

Any workaround to use all the cores of cpus? any alternatives or solution to this?

bun -v 1.1.7

and pm2 has been installed using bun i -g pm2

### What is the expected behavior?

like in node env, pm2 should  run in `custer` mode instead of `fork` mode when using pm2 index.js -i 3

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/2323273/d11f0b67-e35c-4d27-8a04-e74dc08081af)

### Additional information

Context: I have to run the main file of our app (index.js) in cluster mode, like it happens when we run on node environment.

We have to run multiple instances of our backend application through pm2 so that we can utilise all cores of Cpus, which we have been already doing on our node env, however when switching to Bun environment, pm2 command (pm2 start index.js -i 3) does not run application in cluster mode, rather as you can see in above screenshot it runs on FORK mode, means as different application.

index.js file creates and listens server on port:8001, now if it runs on fork mode, it will try to open port 3 times, which will get rejected after 1st attempt.

**Comment by Electroid** [comment] 2024-05-04 15:59
This is because Bun does not support the `node:cluster` module yet.

Duplicate of #2428

**Closed as not planned by Electroid** 2024-05-04 15:59 UTC
Labels: bug

**Comment by ironydips** [comment] 2024-05-04 19:16
Okay. Any workaround for this? As this is the only pending thing for us to use bun on production. Need to use all 32 cpu cores of our ec2.

**Comment by dienstbereit** [comment] 2024-08-27 08:16
> Okay. Any workaround for this? As this is the only pending thing for us to use bun on production. Need to use all 32 cpu cores of our ec2.

@ironydips have you found a solution in the meantime? With v1.1.25 `node:cluster` is now supported.

**Comment by harryqt** [comment] 2024-09-18 14:45
This issue should be reopened.
Bun v1.1.25 support clustering. but `pm2` still start in `forked` mode: https://github.com/Unitech/pm2/issues/5893#issuecomment-2358616293

**Comment by idavidgeo** [comment] 2024-12-06 00:13
I gave up on waiting, just run X instances (port 3000, 3001, etc..) and balance instances via nginx. It literally 6 lines of config.

**Comment by harryqt** [comment] 2024-12-06 06:34
@idavidgeo https://github.com/Unitech/pm2/issues/5893#issuecomment-2478589544

**Comment by alexkarpen** [comment] 2025-01-19 21:47
> I gave up on waiting, just run X instances (port 3000, 3001, etc..) and balance instances via nginx. It literally 6 lines of config.

can i have these 6 lines please?

**Comment by harryqt** [comment] 2025-01-20 05:55
@alexkarpen you can also try pm2 beta: https://github.com/Unitech/pm2/issues/5893#issuecomment-2478589544

**Comment by idavidgeo** [comment] 2025-01-22 17:19
> > I gave up on waiting, just run X instances (port 3000, 3001, etc..) and balance instances via nginx. It literally 6 lines of config.
> 
> can i have these 6 lines please?

nginx site config file:

upstream load_balanced {
    server 127.0.0.1:3000;
    server 127.0.0.1:3001;
}

server {
    ...
    location /api {
        ...
        proxy_pass http://load_balanced;
    }
}
