### ISSUE TITLE
Supabase CLI does not work

### ISSUE THREAD

**Issue by notramo** [oven-sh/bun#6412] opened 2023-10-11 12:57 UTC
### What version of Bun is running?

latest Docker image

### What platform is your computer?

Linux 6.3.13_1 x86_64 unknown

### What steps can reproduce the bug?

`bun x supabase --help`

### What is the expected behavior?

Same as `pnpx supabase --help`

### What do you see instead?

`error: could not determine executable to run for package supabase`

**Comment by Electroid** [comment] 2023-10-11 18:00
Duplicate of #4959

**Comment by Electroid** [comment] 2023-10-11 18:01
See https://bun.sh/guides/install/trusted for more details on how to fix this.

**Closed as completed** 2023-10-24 22:16 UTC
Labels: bug, bun install

**Comment by Jarred-Sumner** [comment] 2023-12-12 07:35
https://twitter.com/bunjavascript/status/1734470860755566815

![image](https://github.com/oven-sh/bun/assets/709451/7e753f72-e332-432b-b535-7383ed9498cd)


Fixed by @dylan-conway and @paperdave in #7132

This will be part of the Bun v1.0.17 release, which ships in a few hours from the time of writing.
