### ISSUE TITLE
await only works in the top-level scope.

### ISSUE THREAD

**Issue by africakokiri** [oven-sh/bun#13731] opened 2024-09-04 14:08 UTC
### What version of Bun is running?

1.1.26

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

```ts
import { $ } from "bun";

const install = async () => {
  const result = await $`bun install typescript -d`.nothrow().quiet();

  return result;
};

// case 1
console.log("start case 1");

const case1 = await install();
console.log(case1);

console.log("finish case 1\n");

// case 2
(async () => {
  console.log("start case 2");

  const case2 = await install();
  console.log(case2);

  console.log("finish case 2");
})();
```

### What is the expected behavior?

Case 1 works successfully, but case 2 only prints up to start case 2 to the console and nothing else. The code below is the output.

```ts
start case 1
ShellOutput {
  stdout: Buffer(78) [ 10, 105, 110, 115, 116, 97, 108, 108, 101, 100, 32, 116, 121, 112, 101, 115, 99, 114, 105, 112, 116, 64, 53, 46, 53, 46, 52, 32, 119, 105, 116, 104, 32, 98, 105, 110, 97, 114, 105, 101, 115, 58, 10, 32, 45, 32, 116, 115, 99, 10, 32, 45, 32, 116, 115, 115, 101, 114, 118, 101, 114, 10, 10, 91, 49, 56, 46, 48, 48, 109, 115, 93, 32, 100, 111, 110, 101, 10 ],
  stderr: Buffer(42) [ 98, 117, 110, 32, 97, 100, 100, 32, 118, 49, 46, 49, 46, 50, 54, 32, 40, 48, 97, 51, 55, 52, 50, 51, 98, 41, 10, 83, 97, 118, 101, 100, 32, 108, 111, 99, 107, 102, 105, 108, 101, 10 ],
  exitCode: 0,
  text: [Function: text],
  json: [Function: json],
  arrayBuffer: [Function: arrayBuffer],
  bytes: [Function: bytes],
  blob: [Function: blob],
}
finish case 1

start case 2
```

I have no question about case 1 working. What I'm curious about is why case 2 doesn't work. If I remove the await keyword from case 2, the Promise is printed as shown below.

```ts
// case 2
(async () => {
  console.log("start case 2");

  const case2 = install();
  console.log(case2);

  console.log("finish case 2");
})();

// console
start case 2
Promise { <pending> }
finish case 2
```

**Comment by Jarred-Sumner** [comment] 2024-09-06 20:55
Duplicate of https://github.com/oven-sh/bun/issues/13713

**Comment by Jarred-Sumner** [comment] 2024-09-06 20:56
This issue is being tracked in https://github.com/oven-sh/bun/issues/13713

Please follow along there

**Closed as not planned by Jarred-Sumner** 2024-09-06 20:56 UTC
Labels: bug, shell
