### ISSUE TITLE
SFTP - missing symbol called

### ISSUE THREAD

**Issue by 0xtlt** [oven-sh/bun#9115] opened 2024-02-26 11:05 UTC
### What version of Bun is running?

1.0.29+a146856d1

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

```bash
bun init -y
```

```index.ts
// index.ts
import Client from "ssh2-sftp-client";
let sftp = new Client();
```

```package.json
// package.json
...
"dependencies": {
    "@types/ssh2-sftp-client": "^9.0.3",
    "ssh2-sftp-client": "^10.0.3"
  }
...
```

```bash
bun index.ts
```

### What is the expected behavior?

It should run normally

### What do you see instead?

```bash
bun index.ts 
dyld[61842]: missing symbol called
zsh: killed     bun index.ts
```

**Comment by Electroid** [comment] 2024-02-27 17:55
Duplicate of #8228

**Closed as not planned by Electroid** 2024-02-27 17:55 UTC
Labels: bug, crash
