### ISSUE TITLE
Date.toLocaleDateString output differs from node

### ISSUE THREAD

**Issue by alexvcasillas** [oven-sh/bun#7467] opened 2023-12-05 13:21 UTC
### What version of Bun is running?

1.0.14+d8be3e51b

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

1. Open Bun Repl and type the following: `new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC', timeZoneName: 'short' })`
2. Open Node Repl and type the following: `new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'UTC', timeZoneName: 'short' })`

Check that both outputs are not the same

### What is the expected behavior?

Both outputs should be the exact same

### What do you see instead?

Node outputs: `'Dec 5, 2023, UTC'`
Bun outputs: `'Dec 5, 2023 at UTC'`

**Comment by Hanaasagi** [comment] 2023-12-05 15:02
Related to https://github.com/oven-sh/bun/issues/6891

**Comment by Electroid** [comment] 2023-12-05 16:48
Duplicate of #6891

**Closed as not planned by Electroid** 2023-12-05 16:48 UTC
Labels: bug
