### ISSUE TITLE
postgres-js queries hang indefinitely on Bun 1.1.35+

### ISSUE THREAD

**Issue by rohanbojja** [oven-sh/bun#15438] opened 2024-11-27 01:55 UTC
### What version of Bun is running?

1.1.37

### What platform is your computer?

Darwin 24.2.0 x86_64 i386

### What steps can reproduce the bug?

When using the postgres-js library ([porsager/postgres](https://github.com/porsager/postgres)) with Bun versions 1.1.35 and later, most queries fail to resolve indefinitely. The same code works seamlessly on Bun 1.1.34 and Deno.

1. Configure the SQL client with the following settings:
```
export const sqlClient = postgres.default({
  db: config.rdsDbName,
  host: config.rdsHostname,
  password: config.rdsPassword,
  username: config.rdsUsername,
  ssl: { rejectUnauthorized: false },
});
```

2. Execute a simple query using Drizzle ORM (e.g., fetching a ticket):
```
db.query.tickets.findFirst({
  where: eq(tickets.id, ticketId),
});
```

3. The query hangs indefinitely

### What is the expected behavior?

Queries should resolve consistently without hanging, as they do on Bun 1.1.34 and Deno.

### What do you see instead?

Queries hang indefinitely on Bun 1.1.35 and later (tested up to 1.1.37).

### Additional information

**Bun Version:** 1.1.35, 1.1.36, 1.1.37 (bug present)
**Working Version:** 1.1.34
**Library Used:** [postgres-js](https://github.com/porsager/postgres)
**Database:** RDS PostgreSQL
**SSL Config:** { rejectUnauthorized: false }

Let me know if you need more details, or if I should try a different configuration to help debug the issue.

EDIT: clean up DB config

**Comment by Jarred-Sumner** [comment] 2024-11-27 02:26
We do have tests that run postgres.js on every commit: https://github.com/oven-sh/bun/blob/main/test/js/third_party/postgres/postgres.test.ts#L1-L41

But we do not set the flags you have set

**Comment by RiskyMH** [comment] 2024-11-27 06:35
> Interesting - I changed my SQL query a bit, to return fewer columns, and now bun db.ts does terminate, so perhaps the issue is more subtle than I realized?
<sub>(from similar issue https://github.com/oven-sh/bun/issues/15443)</sub>

**Comment by rohanbojja** [comment] 2024-11-27 10:06
> We do have tests that run postgres.js on every commit: https://github.com/oven-sh/bun/blob/main/test/js/third_party/postgres/postgres.test.ts#L1-L41
> 
> But we do not set the flags you have set

Same result with just the SSL flag for RDS. It's very subtle, when I try to run a single query from a one off script, it might just work, but the subsequent ones don't.

```
export const sqlClient = postgres.default({
  db: config.rdsDbName,
  host: config.rdsHostname,
  password: config.rdsPassword,
  username: config.rdsUsername,
  ssl: { rejectUnauthorized: false },
});
```
Will try to find out exact cases where it breaks.

**Comment by esciullo** [comment] 2024-11-27 12:02
If have the same issue with bun version >= `1.1.34`

The following query hand indefinitely.
```typescript
await postgresConnection<[{ message: string }] | []>`select 'Dry run test' as message;`;
```

I'm using `"postgres": "3.4.5"` to connect to an instance of Azure Database for PostgreSQL using a token as password.
```typescript
Postgres connection config: {
  database: "******",
  host: "******",
  port: 5432,
  ssl: true,
  password: [Function: password],
  username: "******",
  max: 1,
}
```

**Comment by TimMensch** [comment] 2024-11-28 01:00
I'm seeing similar failures. Works fine in Node; fails in Bun. First query works every time, too; I have it do a simple user count query as it starts up, and I've never seen that fail. Some other query later will just hang, or I'll get a CONNECTION something error.

Bun 1.1.37, postgres 3.4.5, connecting to a free Supabase Postgres server, if that helps.

Also using ssl for the connection, which seems to be a common theme above. My SSL has a CA cert, if that matters:

```
const ssl = {
    host: userParts.pgHost,
    port: userParts.pgPort,
    servername: userParts.pgHost,
    ca: cert,
    minVersion: "TLSv1.2",
};

const queryClient = postgres(pgUserUrl, {
    idle_timeout: 600,
    keep_alive: 60,
    ssl,
});
```

**Comment by Jarred-Sumner** [comment] 2024-11-28 05:31
Fixed in https://github.com/oven-sh/bun/pull/15452

Please run `bun upgrade --canary` and let us know if you still run into this

**Comment by gusfune** [comment] 2024-11-30 09:48
> [@Jarred-Sumner](https://github.com/Jarred-Sumner) I still have the same issue with Bun 1.1.38

Yes, I can confirm the issue is still happening on 1.1.38.

**Comment by Jarred-Sumner** [comment] 2024-11-30 10:03
@esciullo @gusfune can you provide a complete reproduction github repo where we only need to enter the database credentials? 

The fix in #15452 was for the scenario where:
- Postgres.js throws an error after upgrading from TCP -> TLS
- The error.code we provided was incorrect, and we made sure to return the same error.code that Node returns

When Postgres.js didn't receive the expected error.code, it would immediately retry the connection, leading to an infinite loop. It's possible there's another error code we're missing.

**Closed as completed** 2024-12-03 20:53 UTC
Labels: bug

**Comment by Bidek56** [comment] 2024-12-05 15:56
I can reproduce this issue using Bun 1.1.39 on a MacOS Darwin Kernel Version 23.6.0
Start PG using a Docker container: `docker run --rm -it --name postgres13.10 -e POSTGRES_PASSWORD=mysecretpassword postgres:13.10`

This code hangs:

```
import pg from 'pg'
const { Client } = pg;
const devConnStr = "postgresql://postgres:mysecretpassword@localhost:5432/postgres";
const devClient = new Client({ connectionString: devConnStr });
const res = await devClient.query('SELECT "foo" as message');
console.log(JSON.stringify(res)); 
await devClient.end();
```

Thx

**Comment by nivaldomcj** [comment] 2024-12-05 22:29
I'm having the same issue. Postgres 16 with Bun 1.1.38.

Here is a repository with code that reproduce this behavior: 

https://github.com/nivaldomcj/bun-postgres-hang-issue

**Comment by rhuanbarreto** [comment] 2024-12-06 08:04
@Jarred-Sumner should we reopen the issue?

**Comment by gusfune** [comment] 2024-12-06 15:59
> It's probably related to [this](https://github.com/oven-sh/bun/issues/14951) issue, b/c in Node I get: `Warning: Detected unsettled top-level await`

Could be, but I've identified this same bug in non-top-level await functions. Just to not rule out one specific scenario.

**Comment by Bidek56** [comment] 2024-12-06 16:05
It could be a library issue, b/c [this](https://www.npmjs.com/package/postgres#connection) postgres works fine.

```
import postgres from 'postgres'

const devConnStr = "postgresql://postgres:mysecretpassword@localhost:5432/postgres";
const sql = postgres(devConnStr);

const xs = await sql`SELECT '1' as msg`
console.log(xs);

await sql.end()
```

**Comment by Bidek56** [comment] 2024-12-06 16:21
@nivaldomcj 
you are missing `await devClient.connect()` from your code.

**Comment by sFrady20** [comment] 2024-12-06 18:01
`await client.connect()` fixed many of the issues I was having.

I first tested it on @nivaldomcj 's reproduction and that fixed it.

so then in my case, i was running tests using `bun test` and:
a) there was one query in a test that would hang - i found out that if i excluded 1 json object from being inserted, it would work so i had that one line commented out
b) the bigger issue was in a clean up function in afterAll. it was a simple delete users query and it would hang basically every time.

I found that putting `await client.connect()` in the cleanup function right before the query fixed it. What's even weirder is that it also fixed a) too somehow?

personally i think something was going on with idle connections or something, although i don't know much about how all that is working.

I was under the impression that either drizzle or pg would be connecting for me? also not sure how any queries were ever working if it was necessary to connect manually.

Also the problems i was having were non-top-level await btw.

bun v1.1.39 (tried many different versions incl 1.1.38)
pg v8.13.1
drizzle-orm v0.37.0

**Comment by nivaldomcj** [comment] 2024-12-06 22:44
> [@nivaldomcj](https://github.com/nivaldomcj) you are missing `await client.connect()` from your code.

@sFrady20 @Bidek56 
You're right. I've fixed this detail and indeed the code works.

**Comment by nivaldomcj** [comment] 2024-12-09 20:18
I'm having the same issue again but now when using drizzle-orm. When executing `bun run dev`, it hangs and does not execute the query. 

I've updated the code from https://github.com/nivaldomcj/bun-postgres-hang-issue with the example.

**Comment by cirospaciari** [comment] 2024-12-10 01:00
> https://github.com/nivaldomcj/bun-postgres-hang-issue
Thanks for the code, can you tell what OS are you running and also `bun --revision`?

I was not able to reproduce any hang using the repository mentioned in `1.1.38+bf2f153f5` and `1.1.39-canary.38+00b7d6479` revisions

**Comment by nivaldomcj** [comment] 2024-12-10 18:02
> > https://github.com/nivaldomcj/bun-postgres-hang-issue
> > Thanks for the code, can you tell what OS are you running and also `bun --revision`?
> 
> I was not able to reproduce any hang using the repository mentioned in `1.1.38+bf2f153f5` and `1.1.39-canary.38+00b7d6479` revisions

@cirospaciari 

This is the output of command `bun --revision`: 1.1.38+bf2f153f5.

I'm on macOS 15.1.1 (arm64).

**Comment by nivaldomcj** [comment] 2024-12-11 17:42
@cirospaciari 

I've updated the example of https://github.com/nivaldomcj/bun-postgres-hang-issue with a loop that tries to run a select 100 times.

When running the script pointing to my local database (created using docker), it works, running extremely fast. But when running pointing a external postgres server, it hangs after the ~23 query and does not complete the execution.

If I downgrade the version of bun to 1.1.34 the script runs correctly in both environments (local and pointing to the external database).
