### ISSUE TITLE
Show better bun upgrade progress

### ISSUE THREAD

**Issue by d1y** [oven-sh/bun#10214] opened 2024-04-12 14:04 UTC
### What is the problem this feature would solve?

bun upgrade progress make it more readable

Before:

```bash
Bun 1.1.3 is out! You're on 1.0.33
Downloading [3590209/17497656]
```

After:

```bash
Bun 1.1.3 is out! You're on 1.0.33
Downloading [3.4M/16.6M]
```

### What is the feature you are proposing to solve the problem?

<img width="748" alt="image" src="https://github.com/oven-sh/bun/assets/45585937/868efb20-12b6-43d6-a5ee-8008cf6535f5">

**Comment by huseeiin** [comment] 2024-05-28 10:36
duplicate of #7826

**Closed as completed** 2024-05-31 00:47 UTC
Labels: enhancement
