### ISSUE TITLE
string `Response` does not have `text/plain;charset=UTF-8` Content-Type

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#9887] opened 2024-04-03 10:48 UTC
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Linux 6.5.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

```js
console.log(
	Object.fromEntries(
		new Response("", { headers: { hello: "world" } }).headers
	)
);
```
Both Node.js and Chromium print this:
```js
{ 'content-type': 'text/plain;charset=UTF-8', hello: 'world' }```
```
Bun prints this:
```js
{
  hello: "world",
}
```

**Comment by Electroid** [comment] 2024-04-04 04:32
Duplicate of #8530

**Closed as not planned by Electroid** 2024-04-04 04:32 UTC
Labels: bug
