### ISSUE TITLE
Running bun with --hot flag breaks TFJS on hot-reload

### ISSUE THREAD

**Issue by peacefulotter** [oven-sh/bun#8083] opened 2024-01-10 09:23 UTC
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Linux 6.2.0-39-generic x86_64 x86_64

### What steps can reproduce the bug?

1. Create a bun project with a javascript / typescript file, let's say `main.ts`
2. Install tfjs: `bun i @tensorflow/tfjs-node`
3. Import tfjs, for instance using: `import * as tf from '@tensorflow/tfjs-node'; console.log(tf.version)`
4. Run `bun --hot main.ts` or `bun --bun --hot main.ts`
5. Trigger hot-reload, say by saving the main.ts file in vscode

### What is the expected behavior?

Hot reloading works without throwing an error

### What do you see instead?

```
67 |         "the addon module, please check " +
68 |         "https://github.com/tensorflow/tfjs/blob/master/tfjs-node/" +
69 |         "WINDOWS_TROUBLESHOOTING.md or file an issue.");
70 | }
71 | // tslint:disable-next-line:no-require-imports
72 | var bindings = require(bindingPath);
                    ^
TypeError: symbol 'napi_register_module_v1' not found in native module. Is this a Node API (napi) module?
      at .../node_modules/@tensorflow/tfjs-node/dist/index.js:72:16
      at processTicksAndRejections (:61:77)
```

### Additional information

Related to #5578

**Comment by Electroid** [comment] 2024-01-10 16:21
Duplicate of https://github.com/oven-sh/bun/issues/5578

**Comment by Electroid** [comment] 2024-01-10 16:21
Thanks for reporting, we'll fix this. This is a duplicate of the issue you mentioned.

**Closed as not planned by Electroid** 2024-01-10 16:21 UTC
Labels: bug, napi

**Comment by peacefulotter** [comment] 2024-01-10 16:23
> Thanks for reporting, we'll fix this. This is a duplicate of the issue you mentioned.

Awesome, I wasn't sure if it was a duplicate.
In case, my explanations to replicate the issue is probably the easiest way to debug if needed.
Thanks and best!
