### ISSUE TITLE
TypeError: Socket2 is not a function

### ISSUE THREAD

**Issue by gusfune** [oven-sh/bun#13292] opened 2024-08-14 08:54 UTC
### What version of Bun is running?

1.1.23

### What platform is your computer?

Darwin 23.5.0 arm64 arm

### What steps can reproduce the bug?

Since updating to 1.1.23 using `kafkajs` with Bun is throwing Socket2 error. 

### What is the expected behavior?

No error

### Additional information

Reverting to 1.1.23 has no issue

**Comment by Jarred-Sumner** [comment] 2024-08-14 08:56
Duplicate of #13283

**Comment by Jarred-Sumner** [comment] 2024-08-14 08:56
Sorry about this

The fix for this will go out shortly in Bun v1.1.24

**Closed as not planned by Jarred-Sumner** 2024-08-14 08:56 UTC
Labels: bug, needs triage

**Comment by gusfune** [comment] 2024-08-14 09:02
> Sorry about this
> 
> The fix for this will go out shortly in Bun v1.1.24

Brilliant, thanks a lot for the amazingly fast response!
