### ISSUE TITLE
TextDecoder.decode doesn't match Node/Deno behavior

### ISSUE THREAD

**Issue by janniks** [oven-sh/bun#11645] opened 2024-06-06 11:22 UTC
### What version of Bun is running?

1.1.12

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

Script:
```js
const bytes = Uint8Array.from([
  192, 128, 27, 165, 232, 148, 106, 166, 193, 182, 164, 218, 45, 9, 144, 46,
  217, 133, 134, 229, 210, 58, 53, 184,
]);
console.log(bytes);

const text = new TextDecoder().decode(bytes);
console.log(text);

const match = text.match(/^\u0000*/);
console.log(match);
console.log(match[0].length);
```

### What is the expected behavior?

I am expecting Bun to behave the same as Node/Deno -- this might be an incorrect assumption, but I wanted to report anyway.

`Textdecode.decode` doesn't have zerobytes prefixed. (See the regex match)

Expected / Output Node:
```bash
λ node bun-zerobyte.js
Uint8Array(24) [
  192, 128,  27, 165, 232, 148,
  106, 166, 193, 182, 164, 218,
   45,   9, 144,  46, 217, 133,
  134, 229, 210,  58,  53, 184
]
���j�����-      �.م���:5�
[
  '',
  index: 0,
  input: '��\x1B��j�����-\t�.م���:5�',
  groups: undefined
]
0
```

### What do you see instead?

Bun somehow matches a zero byte in the regex match.

Output:
```bash
λ bun bun-zerobyte.js
Uint8Array(24) [ 192, 128, 27, 165, 232, 148, 106, 166, 193, 182, 164, 218, 45, 9, 144, 46, 217, 133, 134, 229, 210, 58, 53, 184 ]
�j�v��- �.م���:5�
[ "\u0000" ]
1
```

**Comment by Jarred-Sumner** [comment] 2024-06-06 11:28
Confirming this is a bug in Bun.

**Comment by xBZZZZ** [comment] 2024-07-28 16:56
<div>differences bun vs node, deno, chromium, firefox, python3 (<code>str(bytes,"utf-8","replace")</code>) are 2 byte overlong encodings:<ul><li>bun decodes like valid 2 byte encoding</li><li>firefox decodes as <code>"\uFFFD\uFFFD"</code></li></ul><details><summary>bytes</summary><ol start=0><li><tt>11000000</tt>&#9586;this is overlong encoding</li><li><tt>10000000</tt>&#9585;of 0b0</li><li><tt>00011011</tt></li><li><tt>10100101</tt></li><li><tt>11101000</tt></li><li><tt>10010100</tt></li><li><tt>01101010</tt></li><li><tt>10100110</tt></li><li><tt>11000001</tt>&#9586;this is overlong encoding</li><li><tt>10110110</tt>&#9585;of 0b1110110 == "v".codePointAt(0)</li><li><tt>10100100</tt></li><li><tt>11011010</tt></li><li><tt>00101101</tt></li><li><tt>00001001</tt></li><li><tt>10010000</tt></li><li><tt>00101110</tt></li><li><tt>11011001</tt></li><li><tt>10000101</tt></li><li><tt>10000110</tt></li><li><tt>11100101</tt></li><li><tt>11010010</tt></li><li><tt>00111010</tt></li><li><tt>00110101</tt></li><li><tt>10111000</tt></li></ol></details>this issue is duplicate of #9582</div>

**Closed as completed** 2024-08-03 06:01 UTC
Labels: bug, web:encoding
