### ISSUE TITLE
Bun.build watch:true 自动更新

### ISSUE THREAD

**Issue by vamsaya** [oven-sh/bun#13602] opened 2024-08-29 08:51 UTC
### What steps can reproduce the bug?

template.html
```html
<h1>Hello Bun</h1>
```
ui_index.js
```js
import template from "./template.html";
export class UI_INDEX extends HTMLElement {
    static template = template;
}
```
当template.html内容发生变化时，Bun.build应该随之自动更新，所以能否加一个watch功能？
When the content of template. html changes, Bun. build should automatically update accordingly, so can a watch function be added?
```js
const builder = await Bun.build({
    entrypoints: ['ui_index.js'],
    loader: { ".html": "text" },
watch:true
});


### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

**Comment by paperdave** [comment] 2024-08-29 17:51
Duplicate of #5866

**Closed as not planned by paperdave** 2024-08-29 17:51 UTC
Labels: bug, enhancement, bundler, needs triage
