### ISSUE TITLE
Max concurrent of Bun.serve is limited to 50 rps

### ISSUE THREAD

**Issue by SaltyAom** [oven-sh/bun#7195] opened 2023-11-18 04:14 UTC
### What version of Bun is running?

1.0.12

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

I found that when await Promise with a long time to resolve (~1s) is significantly slower than it should be (from 100k to 300).

<img width="1512" alt="Screenshot 2566-11-18 at 10 59 07" src="https://github.com/oven-sh/bun/assets/35027979/a13b881e-5bc1-4900-b4c0-cc484df1559b">

Using this code:
```ts
const sleep = (time: number) => new Promise(resolve => setTimeout(resolve, time))

Bun.serve({
    port: 3000,
    fetch: async () => {
        await sleep(1500)

        return new Response('Hi')
    }
})
```

Using this bombardier command:
```bash
bombardier --fasthttp -c 500 -d 10s http://localhost:3000/
```

Testing with both Bun.sleep and custom sleep function results in the same.

This behavior is likely not expected as HTTP should be working concurrently.

Using aha to inspect request per second, I found that request is limited to 50 request per second but sometimes jump every 1.5 seconds.

<img width="1512" alt="Screenshot 2566-11-18 at 11 02 28" src="https://github.com/oven-sh/bun/assets/35027979/5c30f631-160f-48f5-aab1-a4f4878424a6">

Changing sleep duration to `1000` causes the bottleneck, limited to exactly 50 requests per second.

<img width="1512" alt="Screenshot 2566-11-18 at 11 03 22" src="https://github.com/oven-sh/bun/assets/35027979/edeaa8f1-23f9-4286-8984-89cf01563843">

This may mean that there’s some internal function in Bun that may be limiting the execution of concurrent requests.

Is this expected?

### What is the expected behavior?

Should not be limiting to 50 max concurrent request per seconds

### What do you see instead?

Being limited to 50 rps as describe above

**Comment by Jarred-Sumner** [comment] 2023-11-18 04:16
This is an interesting bug

**Comment by Jarred-Sumner** [comment] 2023-11-18 04:20
This regression began between Bun v1.0.7 and Bun v1.0.8.

**Comment by Jarred-Sumner** [comment] 2023-11-18 04:28
~If we compare profiles between Bun v1.0.7 and Bun v1.0.8, we can see significantly more time spent in `kqueue`.
<img width="1993" alt="image" src="https://github.com/oven-sh/bun/assets/709451/aa8bf8b0-ab82-4eb0-a3e7-70fcebe36971">~ 

edit: this is incorrect, the code was different for each one because I had the wrong tab open

**Comment by Jarred-Sumner** [comment] 2023-11-18 08:17
This issue seems to only apply to macOS.

macOS:
```zig
Summary:
  Success rate: 1.0000
  Total:        24.9805 secs
  Slowest:      0.0636 secs
  Fastest:      0.0251 secs
  Average:      0.0500 secs
  Requests/sec: 2001.5646
```

Linux:
```zig
Summary:
  Success rate: 1.0000
  Total:        10.0963 secs
  Slowest:      0.1008 secs
  Fastest:      0.0144 secs
  Average:      0.0500 secs
  Requests/sec: 19809.1068
```

Code:
```ts
var pending = [];
setInterval(() => {
  const next = pending;
  pending = [];
  for (let fn of next) {
    fn();
  }
}, 50);
const sleep = (time) => {
  const { promise, resolve } = Promise.withResolvers();
  pending.push(resolve);
  return promise;
};
var i = 0;
Bun.serve({
  port: 3000,
  fetch: async () => {
    const j = i++;
    console.time("Elapsed " + j);
    await sleep();
    console.timeEnd("Elapsed " + j);

    return new Response("Hi");
  },
});
```

**Comment by Jarred-Sumner** [comment] 2023-11-18 12:09
Thinking about this more...this is actually expected behavior.

[`listen(2)`](https://man7.org/linux/man-pages/man2/listen.2.html) receives a `backlog`. That backlog is determined mostly by your machine. Most macOS machines default to 128. That means it will enqueue up to 128 connections and any more than that, clients will report connection refused or timeout. 

The backlog can be increased, but it doesn't necessarily mean more connections will go through.

There is also a limit on the number of open sockets available on the machine. On macOS, that usually is about 16k. On Linux, it's typically higher.

I do think there is some performance issue with timers in Bun that should be addressed in the future. 

But I don't think this is actually unexpected behavior. I tried with Node and Deno and they behaved similarly. It's worth verifying other languages experience similar behavior, but based on what I know right now, it seems like this is expected behavior. Very happy to be proven wrong on this.

**Closed as not planned by Jarred-Sumner** 2023-11-18 12:09 UTC
Labels: bug
