### ISSUE TITLE
Bun WebSocket idleTimeout does not work

### ISSUE THREAD

**Issue by sheryy** [oven-sh/bun#5905] opened 2023-09-22 11:39 UTC
### What version of Bun is running?

1.0.2

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Given below is the code of a simple websocket which is configured to close websocket after 4 seconds of being idle. But the websocket never timeout. 

Noteable settings are:     
**idleTimeout**: 4
**sendPings**: false,

According to this [documentation](https://unetworking.github.io/uWebSockets.js/generated/interfaces/WebSocketBehavior.html#idleTimeout) connection should be closed after idle timeout. 

```
const server = Bun.serve({
  port: 5000,
  fetch(request, server) {
    const url = new URL(request.url);
    if (url.pathname === "/ws") {
      if (server.upgrade(request)) {
        return;
      }
      return new Response("Upgrade failed :(", { status: 500 });
    }
    return new Response("Bun");
  },
  websocket: {
    idleTimeout: 4,
    sendPings: false,
    open(ws) {
      console.log(`[${new Date()}] ws-open`);
    },
    message(ws, message) {
      if (typeof message !== "string") return;
      const data = JSON.parse(message);
      ws.send(message);
      console.dir(data);
    },
    close(ws, code, message) {
      console.log(`[${new Date()}] ws-close`);
    },
    drain(ws) {
      console.log(`[${new Date()}] ws-drain`);
    },
    ping(ws, data) {
      console.log(`[${new Date()}] ws-ping`);
    },
    pong(ws, data) {
      console.log(`[${new Date()}] ws-pong`);
    },
  },
});

console.log(`Bun listening on ${server.hostname}:${server.port}`);

```

### What is the expected behavior?

Bun websocket idleTimeout shall work properly. 

### What do you see instead?

Bun websocket doesn't timeout.

**Comment by Electroid** [comment] 2023-09-22 17:04
Duplicate of #1397

**Closed as not planned by Electroid** 2023-09-22 17:04 UTC
Labels: bug

**Comment by sheryy** [comment] 2023-09-23 01:20
The original bug was reported on Bun v0.2. I am using Bun 1.0.2 and the bug still persists.

Is there any plan to fix this issue?
