### ISSUE TITLE
Bun install doesn't install everything from a dependency

### ISSUE THREAD

**Issue by JJBocanegra** [oven-sh/bun#5757] opened 2023-09-19 18:44 UTC
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Run `bun init` in any folder and go with the default settings
2. Run `bun add bcrypt`
3. Check `node_modules/bcrypt` folder, when installed with NPM it has a `lib` folder but with Bun that folder doesn't exists, and is causing issues when I try it in a real project that uses BCrypt

### What is the expected behavior?

The `lib` folder should be inside the `bcrypt` dependency folder

**Comment by Electroid** [comment] 2023-09-19 18:49
Hi, thanks for reporting. We're working on fixing this issue. Duplicate of #4959

**Closed as not planned by Electroid** 2023-09-19 18:49 UTC
Labels: bug, bun install
