### ISSUE TITLE
Bun and Rspack Crashed

### ISSUE THREAD

**Issue by lassejlv** [oven-sh/bun#13242] opened 2024-08-12 06:52 UTC
### How can we reproduce the crash?

By running `bun create rsbuild@latest`. You can find rspack at rspack.dev or rsbuild.dev. Then run `bun --bun dev`

### Relevant log output
```bash
Bun Canary v1.1.23-canary.30 (44476683) macOS Silicon
macOS v14.5
Args: "node" "/Users/lasse/Documents/dev/techcollege-react-app/node_modules/.bin/rsbuild" "dev" "--open"
Features: jsc Bun.stdin(2) http_server spawn(3) tsconfig 
Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:v8" "node:inspector" 
Elapsed: 625ms | User: 585ms | Sys: 103ms
RSS: 0.37GB | Peak: 0.37GB | Commit: 1.03GB | Faults: 1607

panic(main thread): Segmentation fault at address 0x5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.23 ([`4447668`](<https://github.com/oven-sh/bun/tree/444766833c8f163c57eb913037ae6ced84cbf334>)) on macos aarch64 [RunAsNodeCommand]

Segmentation fault at address 0x00000005

- *4 unknown/js code*
- `vmEntryToJavaScript`
- `JSC::Interpreter::executeCall`
- `JSC::runJSMicrotask`
- `JSC::VM::drainMicrotasks`
- `Bun::jsFunctionDrainMicrotaskQueue`

**Comment by Jarred-Sumner** [comment] 2024-09-01 08:58
Duplicate of https://github.com/oven-sh/bun/issues/11628

**Comment by Jarred-Sumner** [comment] 2024-09-01 08:59
Please follow along in https://github.com/oven-sh/bun/issues/11628

Thanks for the repro though, makes it easier

**Closed as not planned by Jarred-Sumner** 2024-09-01 08:59 UTC
Labels: crash, macOS
