### ISSUE TITLE
Property ‘v’ has no initializer and is not definitely assigned in the constructor

### ISSUE THREAD

**Issue by brianmhunt** [oven-sh/bun#15221] opened 2024-11-18 16:46 UTC
### What version of Bun is running?

1.1.35

### What platform is your computer?

OS X

### What steps can reproduce the bug?

```ts
abstract class X {
    abstract init (): void
    constructor () { this.init() }
}

class Y extends X {
    v!: number
    init () { this.v = 123 }
}

console.log(new Y().v)
```

prints `undefined`

### What is the expected behavior?

https://www.typescriptlang.org/play/?#code/FDCGCMGcBcCdQMbQAQIDakpZANZBvYZY5CGeJZASwDsqUAKASgC5kA3AeyoBMiSEnGuQCuSTrGTMCyaAAsqkAHS160gL7BNwdJmwBNZAFMAHtCM0e2PIRIc2NEQFtwR2P2KrGTGfMVL2ZABeZABGACYAZmRNbUFhTjQjJTROAHMGGiMAd2R9ZgCmYCA

![Image](https://github.com/user-attachments/assets/c0ef322c-d1b0-404f-af1c-0fe6a6ec793b)

### What do you see instead?

```ts
❯ cat x.ts
abstract class X {
    abstract init (): void
    constructor () { this.init() }
}

class Y extends X {
    v!: number
    init () { this.v = 123 }
}

console.log(new Y().v)

❯ bun x.ts
undefined
```

### Additional information

Related to:

https://stackoverflow.com/questions/64874221/property-has-no-initializer-and-is-not-definitely-assigned-in-the-constructor

Bun does not seem to honour `"strictPropertyInitialization": false,` or the `!` on `property!: definition` (though those just ignore the error, and tsc in any case compiles).

**Comment by pfgithub** [comment] 2024-11-19 01:54
bun, esbuild, and babel generate:

```diff
class X {
  constructor() {
    this.init();
  }
}

class Y extends X {
+ v;
  init() {
    this.v = 123;
  }
}
console.log(new Y().v);
```

while tsc generates the same thing without `v;`. Including `v` causes javascript to set v to undefined right after calling X's constructor.

> Bun does not seem to honour "strictPropertyInitialization": false, or the ! on property!: definition (though those just ignore the error, and tsc in any case compiles).

Bun does not perform typescript typechecking on your code. To see typescript errors, you have to run `bunx tsc --noEmit`. In typescript, `strictPropertyInitialization` has no effect on the compiled output code.

**Comment by paperdave** [comment] 2024-11-19 03:56
Duplicate of #2060. I have a good comment about the situation https://github.com/oven-sh/bun/issues/2060#issuecomment-2153548604

**Closed as not planned by paperdave** 2024-11-19 03:56 UTC
Labels: bug, typescript, transpiler, confirmed bug

**Comment by brianmhunt** [comment] 2024-11-19 20:21
Thanks for pointing me to that #2060 issue @paperdave .  Rather than confuse the issue for future readers I'll copy from your comment and refer to it from here.

> This makes tsc --target ESNext, bun, esbuild, and other tools transform this to just class Outer extends Base {}

This _appears_ to be partly incorrect/outdated.  TSC _seems_ to work as expected i.e. preserves the values set in the parent constructor, see the Typescript playground I linked in the description [1], which targets ESNext (and produces the correct output as far back as ES2017, perhaps further).

![Image](https://github.com/user-attachments/assets/c1900939-f3a9-49f3-b70e-b413b02bfeb1)
![Image](https://github.com/user-attachments/assets/082d6228-5b3b-425c-9d78-7c27a8abeaa1)

On the other hand esbuild produces code that re-initializes `v` to be `undefined`.  That appears to be configurable via the tsconfig since we're using esbuild, but I cannot recall exactly what parameters (perhaps useDefineForClassFields or some such IIRC).

```ts
❯ bunx esbuild x.ts
class X {
  constructor() {
    this.init();
  }
}
class Y extends X {
  v;
  init() {
    this.v = 123;
  }
}
console.log(new Y().v);
```

Which is to say, the tools appear to be inconsistent.  For us we've a big complex legacy code base that would take significant effort to refactor, so it would be pleasant if bun were consistent with tsc here.

[1] https://www.typescriptlang.org/play/?strictPropertyInitialization=false&esModuleInterop=false&target=99&module=1#code/FDCGCMGcBcCdQMbQAQIDakpZANZBvYZY5CGeJZASwDsqUAKASgC5kA3AeyoBMiSEnGuQCuSTrGTMCyaAAsqkAHS160gL7BNwdJmwBNZAFMAHtCM0e2PIRIc2NEQFtwR2P2KrGTGfMVL2ZABeZABGACYAZmRNbUFhTjQjJTROAHMGGiMAd2R9ZgCmYCA

**Comment by brianmhunt** [comment] 2024-11-19 20:23
Also worth noting that the code from #2060 seems to also work as expected in the TS playground (unless I'm missing something):

![Image](https://github.com/user-attachments/assets/40bac271-1f7d-4a46-82e4-4a60175ce89f)

**Comment by paperdave** [comment] 2024-11-20 03:22
oh interesting. i know theres some way to configure typescript to emit the es class fields. i should've pasted my compilation commands in the linked issue. the solution is for bun to read useDefineForClassFields, falling back to reading `target` to implement the default value. this is still a duplicate of the other issue.

thanks for sharing useDefineForClassFields. i wasn't actually aware of the dedicated option.

> This flag is used as part of migrating to the upcoming standard version of class fields. TypeScript introduced class fields many years before it was ratified in TC39. The latest version of the upcoming specification has a different runtime behavior to TypeScript’s implementation but the same syntax.
> 
> This flag switches to the upcoming ECMA runtime behavior.

Searching the issue tracker, there are some other issues which can be closed as dupe.
