### ISSUE TITLE
Custom Registry doesn’t resolve without trailing slash

### ISSUE THREAD

**Issue by jackHedaya** [oven-sh/bun#9133] opened 2024-02-27 18:12 UTC
### What version of Bun is running?

1.0.29+a146856d1

### What steps can reproduce the bug?

Create `bunfile.toml`

```
[install]
registry = “https://myregistry.com/path/whatever”
```
Incorrectly resolves to `https://myregistry.com/path/<package>`

```
[install]
registry = “https://myregistry.com/path/whatever/”
```
Correctly resolves to `https://myregistry.com/path/whatever/<package>`

**Comment by Electroid** [comment] 2024-02-27 19:09
Duplicate of #5029

**Closed as not planned by Electroid** 2024-02-27 19:09 UTC
Labels: bug, bun install
