### ISSUE TITLE
bun install stuck with some library

### ISSUE THREAD

**Issue by frodoe7** [oven-sh/bun#1208] opened 2022-09-05 00:31 UTC
### Version

0.1.10

### Platform

Darwin Macs-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

I'm trying to install that library : multichain-crypto-wallet

**yarn add multichain-crypto-wallet** works well
but **bun install multichain-crypto-wallet** stuck and fire error

### How often does it reproduce? Is there a required condition?

Always happen

### What is the expected behavior?

The library should be installed in success

### What do you see instead?

It stuck and fires that error

```
error: Unsupported dependency type git for "git+https://github.com/ren-forks/bitgo-utxo-lib.git#b848585e65b42c48b98c207e72d7d3006c9a5da0"


error: Unsupported dependency type git for "git+https://github.com/ethereumjs/ethereumjs-abi.git"
```

**Comment by vuon9** [comment] 2022-09-06 20:09
Duplicate of https://github.com/oven-sh/bun/issues/82

**Comment by xhyrom** [comment] 2022-11-03 15:55
Duplicate of https://github.com/oven-sh/bun/issues/82

**Closed as not planned by xhyrom** 2022-11-03 15:55 UTC
Labels: bug, needs repro
