### ISSUE TITLE
$$21d2adb2.hasBasePath is not a function

### ISSUE THREAD

**Issue by gede-cahya** [oven-sh/bun#908] opened 2022-07-28 23:30 UTC
### Version

0.1.5

### Platform

Linux DESKTOP-T8MROID 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

## Error Page
error when accessing https://localhost:3000:
![image](https://user-images.githubusercontent.com/49280905/181652197-2db0b775-9ba7-4572-b901-04d6cc28801c.png)

**$$21d2adb2.hasBasePath is not a function**
In `bun-framework-next/client.development.tsx` – node_modules.bun:3001:20
```bun
        var currentTransition = ReactCurrentBatchConfig.transition;
        ReactCurrentBatchConfig.transition._updatedFibers = new Set;
        try {
          scope();
        } finally {
        /*         ^ happend here */
          ReactCurrentBatchConfig.transition = prevTransition;
          if (prevTransition === null && currentTransition._updatedFibers) {
            var updatedFibersCount = currentTransition._updatedFibers.size;
```
Stack trace:
```js

  `bun-framework-next/client.development.tsx` node_modules.bun:3001:20
  `c`                                         node_modules.bun:7:6560
  λ()                                         node_modules/bun-framework-next/fallback.development.tsx:33:18
```
Info:
  > bun v0.1.5
  > framework: bun-framework-next@12.1.5
  > wsl #1 SMP Wed Mar 2 00:30:59 UTC 2022 (x64)
  > User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
  > Pathname: /

<details>
<summary>📦package.json</summary>

```
{
  "name": "komik",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "clean": "rm -rf dist out node_modules"
  },
  "dependencies": {
    "axios": "^0.27.2",
    "cheerio": "^1.0.0-rc.12",
    "cloudflare-bypasser": "^0.0.3",
    "cors": "^2.8.5",
    "flowbite": "^1.4.7",
    "flowbite-react": "^0.1.3",
    "next": "^12.2.2",
    "nextjs-cors": "^2.1.1",
    "node-fetch": "^2.6.7",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.4.0",
    "react-is": "^18.2.0",
    "swr": "^1.3.0",
    "tailwindcss": "^3.1.6",
    "tough-cookie": "^4.0.0"
  },
  "devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "autoprefixer": "^10.4.7",
    "bun-framework-next": "^12.1.5",
    "eslint": "8.19.0",
    "eslint-config-next": "12.2.0",
    "postcss": "^8.4.14",
    "react-refresh": "latest"
  }
}
```
</details>

**Comment by TiKevin83** [comment] 2022-07-30 02:12
duplicate of #473

**Closed as completed** 2022-07-30 05:01 UTC
Labels: bug, needs repro
