### ISSUE TITLE
suggestion: please, add URLPattern web api

### ISSUE THREAD

**Issue by MrCarbone** [oven-sh/bun#14732] opened 2024-10-22 06:35 UTC
### What is the problem this feature would solve?

```javascript
const pattern = new URLPattern({ pathname: "/books/:id" });
console.log(pattern.test("https://example.com/books/123")); // true
console.log(pattern.exec("https://example.com/books/123").pathname.groups); // { id: '123' }
```

### What is the feature you are proposing to solve the problem?

for more control on of the url

**Comment by TiBianMod** [comment] 2024-10-22 10:39
https://github.com/oven-sh/bun/issues/2286

**Comment by Electroid** [comment] 2024-10-22 15:25
Duplicate of #2286

**Closed as not planned by Electroid** 2024-10-22 15:25 UTC
Labels: enhancement
