### ISSUE TITLE
Add support for @libsql/client package

### ISSUE THREAD

**Issue by nikivdev** [oven-sh/bun#3407] opened 2023-06-25 23:25 UTC
### What version of Bun is running?

0.6.10

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

try use this package: https://www.npmjs.com/package/@libsql/client

i.e. try run this code:

```
import { createClient } from "@libsql/client"

const config = {
  url: "file:local.db",
}
const db = createClient(config)
const rs = await db.execute("select 1")
console.log(rs)
```

with `tsx` works:

```
tsx run.ts
{
  columns: [ '1' ],
  rows: [ { '1': 1 } ],
  rowsAffected: 0,
  lastInsertRowid: undefined
}
```

with `bun` get this:

```
bun run.ts
[0.33ms] ".env"
dyld[57530]: missing symbol called
fish: Job 1, 'bun run.ts' terminated by signal SIGKILL (Forced quit)
```

Really love using this lib and would love to use it with bun.

**Comment by Jarred-Sumner** [comment] 2023-06-25 23:30
This is happening because better-sqlite3 which is a dependency of @libsql/client is using V8 C++ bindings and that is difficult for Bun to support (as Bun uses JavaScriptCore)

**Comment by Hebilicious** [comment] 2023-08-27 06:59
@Jarred-Sumner is better-sqlite3 support on the roadmap for v1 or is there a workaround ?
Should we add bun support in @libsql/client directly? 

~Just changing the import here should work https://github.com/libsql/libsql-client-ts/blob/main/src/sqlite3.ts
https://github.com/oven-sh/bun/issues/2336 this would be really great to have for these scenarios.~

Edit :  This was more complicated, made a PR there to add support for `bun:sqlite` https://github.com/libsql/libsql-client-ts/pull/71

**Comment by Electroid** [comment] 2024-02-06 17:26
This isn't something we're considering right now. Also, going to close as a duplicate for another tracking issue.

**Comment by Electroid** [comment] 2024-02-06 17:26
Duplicate of #4290

**Closed as not planned by Electroid** 2024-02-06 17:26 UTC
Labels: bug
