### ISSUE TITLE
Segmentation fault when connecting to cassandra-driver

### ISSUE THREAD

**Issue by Darker-Ink** [oven-sh/bun#11890] opened 2024-06-15 15:34 UTC
### How can we reproduce the crash?

Using this simple code:

```ts
import { Client } from "@kastelapp/cassandra-driver"; // custom fork of the library, does not change anything meaningful

const client = new Client({
    keyspace: "keyspace",
    contactPoints: ["localhost"],
    credentials: {
        username: "",
        password: ""
    },
    localDataCenter: "datacenter1"
})

try {
    await client.connect();
    console.log("Connected to Cassandra");
} catch (error) {
    console.error("Failed to connect to Cassandra", error);
}
```
before it can even connect it Segmentation fault's

### Relevant log output

```shell
➜  Backend git:(ink/messages) ✗ bun run src/fixtest.ts
============================================================
Bun v1.1.13 (bd6a6051) Linux x64
Args: "bun" "run" "src/fixtest.ts"
Features: jsc transpiler_cache(2) tsconfig_paths tsconfig
Builtins: "bun:main" "node:buffer" "node:crypto" "node:dns" "node:events" "node:fs" "node:https" "node:net" "node:os" "node:path" "node:stream" "node:string_decoder" "node:tls" "node:url" "node:util" "node:util/types" "node:vm"
Elapsed: 80ms | User: 86ms | Sys: 0ms
RSS: 1.07GB | Peak: 91.56MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x20
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:


[1]    9252 illegal hardware instruction  bun run src/fixtest.ts
➜  Backend git:(ink/messages) ✗
```

### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x00000020

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `end_hquery`

**Comment by Jarred-Sumner** [comment] 2024-06-20 23:57
Duplicate of  https://github.com/oven-sh/bun/issues/11882

**Comment by Jarred-Sumner** [comment] 2024-06-20 23:57
We are tracking this in https://github.com/oven-sh/bun/issues/11882, please follow along in that issue

**Closed as completed by Jarred-Sumner** 2024-06-20 23:57 UTC
Labels: crash, linux, runtime
