### ISSUE TITLE
Add HTTP2 for GRPC connections

### ISSUE THREAD

**Issue by JeissonWeeDev** [oven-sh/bun#10252] opened 2024-04-13 20:10 UTC
### What is the problem this feature would solve?

![image](https://github.com/oven-sh/bun/assets/133667664/813df46a-7162-4cad-a269-29ef2a050f79)

Support for HTTP2 could be added, because some of the servers and APIs that some companies have require the use of GRPC for communication between microservices in an agile and fast way, BUNJS works perfectly as a GRPC client but as a GRPC server I have to use NodeJs v20 now When I run the server using "bun" I have a compilation error, I want to migrate the services I have in Nodejs to Bunjs since it is much faster but I have this limitation of the HTTP2 protocol, greetings bro.

### What is the feature you are proposing to solve the problem?

As I said before, it is to fix the compatibility between the services I have, I want to migrate to the use of BunJs but I have a problem with HTTP2 and I left you evidence of it, here I leave other evidence of the same.

![image](https://github.com/oven-sh/bun/assets/133667664/130de8e7-f03a-41ad-94e0-36a794e63d7b)

### What alternatives have you considered?

For this problem, I use NodeJs in gRPC server instead BunJs

**Comment by Electroid** [comment] 2024-04-15 16:16
Duplicate of #8823

**Closed as not planned by Electroid** 2024-04-15 16:16 UTC
Labels: enhancement

**Comment by moeinrahimi** [comment] 2024-05-28 13:41
please update doc. it's misleading since bun does not support grpc servers
https://github.com/oven-sh/bun/issues/8823
