### ISSUE TITLE
async await loop is not work

### ISSUE THREAD

**Issue by HeesuKim0203** [oven-sh/bun#6363] opened 2023-10-08 07:27 UTC
### What version of Bun is running?

1.0.4

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

I was testing an algorithm that uses inquirer.js to keep getting strings from prompt.
I'm not sure if this is a bug, but I think it's weird, so I'm posting it.

## version
```json
"@types/inquirer": "^9.0.3",
"inquirer": "^8.2.6"
```
## code
```ts
import inquirer from 'inquirer'

const main = ( async () => {
  while(true) {
    try {
      const answers = await prompt();
      console.log('The answers are: ', answers);
    } catch (error : any) {
      console.log(error?.message)
    }
  }
})();

function prompt() {
  return inquirer.prompt([{
      name : "name",
      message : "What is your name?",
      type : "input",
      validate: (hello) => {
        if(!hello.length) {
          return 'Please provide a first name';
        }
        if(hello.length <= 3 || hello.length > 20) {
          return 'Please provide a first name between 4 and 20 characters long';
        }
        return true;
      },
      filter: (hello) => {
        return hello.trim();
      }
    },
  ]) ;
}
```

### What is the expected behavior?

```log
bun index.ts
? What is your name? heesu
The answers are:  {
  name: "heesu"
}
? What is your name? heesu
The answers are:  {
  name: "heesu"
}
? What is your name? heesu
The answers are:  {
  name: "heesu"
}
? What is your name? heesu
The answers are:  {
  name: "heesu"
}
...
...
Loop until you leave the prompt
```

### What do you see instead?

```log
bun index.ts
? What is your name? heesu
The answers are:  {
  name: "heesu"
}
? What is your name? heesu
The answers are:  {
  name: "heesu"
}
? What is your name? 
👇
Forced out of the prompt on the third loop.
```

### Additional information

Works as expected with ts-node(version v10.9.1).

```log
ts-node index.ts
? What is your name? heesu
The answers are:  { name: 'heesu' }
? What is your name? heesu
The answers are:  { name: 'heesu' }
? What is your name? heesu
The answers are:  { name: 'heesu' }
...
...
Loop until you leave the prompt
```

Could you tell me where the problem is? 🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by Jarred-Sumner** [comment] 2023-10-10 22:39
This is a duplicate of #6323

**Closed as not planned by Jarred-Sumner** 2023-10-10 22:39 UTC
Labels: bug
