### ISSUE TITLE
Bun support for ARM based OS

### ISSUE THREAD

**Issue by asumbek** [oven-sh/bun#566] opened 2022-07-11 04:42 UTC
### What is the problem this feature will solve?

Bun binary cannot be executed in Termux (with Ubuntu proot).

![Screenshot_2022-07-11-12-34-59](https://user-images.githubusercontent.com/71205197/178189691-900f1853-3921-441f-95bb-5c09f14564f6.png)

### What is the feature you are proposing to solve the problem?

The feature to solve the problem is to add an ARM based binary for ARM based OS.

**Comment by FinnRG** [comment] 2022-07-11 07:52
Duplicate of #75.

**Closed as completed by FinnRG** 2022-07-11 07:52 UTC
Labels: enhancement
