### ISSUE TITLE
Bun.write() does not work when writing data to a lp device on Linux

### ISSUE THREAD

**Issue by egidiusmengelberg** [oven-sh/bun#12374] opened 2024-07-05 19:29 UTC
### What version of Bun is running?

1.1.18+5a0b93523

### What platform is your computer?

Linux 6.8.0-generic x86_64 x86_64 

### What steps can reproduce the bug?

I'm using `Bun.write('/dev/usb/lp0', label)` to write data to a Zebra labelwriter. This does not print the label. 
But when using node's `writeFile` function it works fine.

The weird thing is I can see the printer react to data being written to it (the data light flashes)

### What is the expected behavior?

writing to the the printer device should print the label.

### What do you see instead?

the data light on the printer flashes

**Comment by billywhizz** [comment] 2024-07-07 20:19
i had a quick look to see what differences there are between these two operations in bun and node.js.

when doing this in Bun, on Linux (Ubuntu 22.04):
```JavaScript
await Bun.write('./foo.txt', 'hello from bun')
```

we see the following syscalls

```shell
openat(AT_FDCWD, "./foo.txt", O_WRONLY|O_CREAT|O_NONBLOCK, 0664) = 12
write(12, "hello from bun", 14)         = 14
ftruncate(12, 14)                       = 0
close(12)                               = 0
```

when doing this in node.js

```JavaScript
const { writeFile } = require('fs')

writeFile('./foo2.txt', 'hello from node', err => {
  if (err) {
    console.error(err.stack)
    return
  }
})
```

we see these syscalls

```shell
openat(AT_FDCWD, "./foo2.txt", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
epoll_ctl(13, EPOLL_CTL_ADD, 16, {events=EPOLLIN, data={u32=16, u64=16}}) = 0
write(17, "hello from node", 15) = 15
close(17)
```

if we look at the differences between the two, we can see the following

- ```Bun.write``` does not truncate the file/device when opening, but it truncates to the size of the write after writing using an explicit fruncate call
- Node truncates the file/device on opening
- Bun opens the file/device with read permission for "other" (0664) while node.js specifies read/write permission (0666) for "other"

I don't have a Zebra available for testing with currently but will see if I can test with another linux printer device that would respond in a similar way. Will also investigate the file truncation issues to understand better why Bun is not truncating when opening - this may be the cause of the different behaviour.

In meantime, @egidiusmengelberg - would you be able to do the following?

- provide a fuller example of some code you are running for both node.js and Bun?
- try to use ```fs.writeFile``` from Bun as in the node.js snippet above and let us know if that behaves any differently

I see slightly different options used when opening the file and using ```fs.writeFile``` in Bun

```shell
openat(AT_FDCWD, "./foo2.txt", O_WRONLY|O_CREAT|O_NOCTTY, 0666) = 12
write(12, "hello from node", 15) = 15
ftruncate(12, 15)           = 0
close(12)                   = 0
```

**Comment by egidiusmengelberg** [comment] 2024-07-08 14:31
Just to clarify: I'm currently using fs.writeFile in **Bun** which works. But **Bun.write** does not.

I have a fuller example right here:

```js
import { writeFile } from 'fs/promises'

const printer = '/dev/usb/lp0'
const id = '1234567890'

const label = `
        ^XA
        ^FO21,80^BY3,3^B7N,5,5,4,24,N^FD${id}^FS
        ^FO87,210^A0,20^FD${id}^FS
        ^XZ
    `

await writeFile(printer, label) //does work
await Bun.write(printer, label) //does not work
```

We use a Zebra ZD-421. The printer uses the default settings. The only thing I changed is the label configuration so it knows what size labels we use.

We want to use USB because we ship a complete package to our clients and do not want to deal with their networks.
USB should be plug and play since just writing raw zpl to the printer seems to work.

If you have any questions let me know!

Thanks for your help.

**Comment by billywhizz** [comment] 2024-07-08 18:16
thanks @egidiusmengelberg - that makes sense re. USB. i had only used these printers on windows previously so didn't realise you could write ZPL direct to the usb device on linux.

that is good that ```fs.writeFile``` is working the same in Bun and node.js as that would be the main concern for Bun. without having a printer to test with I am not sure we would be able to figure out why ```Bun.write``` is behaving differently, but i would guess it is down to the way Bun omits the ```O_TRUNC``` flag when opening the device and does ```ftruncate``` separately after the write. Afaik, this has been done for performance reasons and doubt it will change.

It should be pretty straightforward to reproduce the syscalls as outlined above in a little C program (see below) if you need to investigate further. We don't currently have a Zebra to test with so for now, I would suggest we close this issue as ```fs.writeFile``` is working as expected and won't be any slower than using ```Bun.write``` for this scenario.

feel free to re-open if you think there is more we could do. thx.

```C
#include <unistd.h>
#include <stdlib.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>

int main () {
  int perm = S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH;
  int fd = open("/dev/usb/lp0", O_WRONLY | O_CREAT | O_NONBLOCK, perm);
  if (fd < 0) {
    perror("could not create file");
    exit(1);
  }
  char* zpl = "^XA\n^FO21,80^BY3,3^B7N,5,5,4,24,N^FD${id}^FS\n^FO87,210^A0,20^FD1234567890^FS\n^XZ";
  int len = strlen(zpl);
  int written = write(fd, zpl, len);
  if (written < len) {
    perror("could not write to file");
    exit(2);
  }
  if (ftruncate(fd, len) < 0) {
    perror("could not truncate");
    exit(3);
  }
  close(fd);
  return 0;
}

```

**Closed as completed by billywhizz** 2024-07-08 18:16 UTC
Labels: bug, node.js, needs triage
