### ISSUE TITLE
VSCode on Windows doesn't run

### ISSUE THREAD

**Issue by badalya1** [oven-sh/bun#14669] opened 2024-10-18 17:06 UTC
### What version of Bun is running?

1.1.31

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

1. Create a simple `index.ts`
2. Set a breakpoint
3. Debug file with VSCode debugger on windows
4. Observe nothing.

### What is the expected behavior?

The VSCode debugger should stop at the debugger, showing all local/global scopes.

### What do you see instead?

Nothing happens other that debugger output:
```
--------------------- Bun Inspector ---------------------
Listening:
  ws://127.0.0.1:52561/ha0ubfpuzii?wait=1
Inspect in browser:
  ]8;;https://debug.bun.sh/#127.0.0.1:52561/ha0ubfpuzii\https://debug.bun.sh/#127.0.0.1:52561/ha0ubfpuzii]8;;\
--------------------- Bun Inspector ---------------------
Debugger attached.
```

### Additional information
Extension version `v0.0.15`

When opening `https://debug.bun.sh/#127.0.0.1:52561/ha0ubfpuzii` manually:

Web inspector encounters unhandled error
```
Debugger domain already enabled (at :​undefined:​undefined)​
    ?​ @ Error:​ Debugger domain already enabled
    ?​ @ manifest-7f15da7ddeb3145d.js:​37:​91068)​
    ?​ @ manifest-7f15da7ddeb3145d.js:​37:​90180)​
    ?​ @ manifest-7f15da7ddeb3145d.js:​37:​89186)​
    ?​ @ manifest-7f15da7ddeb3145d.js:​37:​83401)​
    ?​ @ manifest-7f15da7ddeb3145d.js:​37:​1537)​
```

The code does not run. The breakpoints are not hit. Vscode gives into debugging view and that's it.

**Comment by Electroid** [comment] 2024-10-18 21:46
Duplicate of #14674

**Closed as not planned by Electroid** 2024-10-18 21:46 UTC
Labels: bug, debugger
