### ISSUE TITLE
SvelteKit node adapter does not work

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#4574] opened 2023-09-08 12:10 UTC
### What steps can reproduce the bug?

https://github.com/sveltejs/kit/blob/master/packages/kit/src/exports/node/polyfills.js#L33

### What is the expected behavior?

it works

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/24465214/f7b3d7ab-57cb-4572-954f-6f8c1656d060)

### Additional information

Discord convo:

<img width="961" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/338d8cf1-f112-4f47-b395-472cf7f9d896">

Link they shared:

https://github.com/sveltejs/kit/pull/10273#issuecomment-1673888178

**Comment by James-Riordan** [comment] 2023-09-10 00:49
I have the same issue. Upon following the steps located at https://bun.sh/guides/ecosystem/sveltekit, I can only run the SvelteKit application with Node.js with leaving the `--bun` flag out. Here's what happens when I try to run SvelteKit with Bun.

`bun --bun run dev`

Output:
```bash
$ vite dev
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


error when starting dev server:
TypeError: Attempting to change configurable attribute of unconfigurable property.
    at defineProperty (native)
    at installPolyfills (/Users/jamesriordan/Workspaces/Personal/Code/sandbox/test-svelte-bun-app/node_modules/@sveltejs/kit/src/exports/node/polyfills.js:21:15)
    at <anonymous> (/Users/jamesriordan/Workspaces/Personal/Code/sandbox/test-svelte-bun-app/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:31:18)
    at dev (/Users/jamesriordan/Workspaces/Personal/Code/sandbox/test-svelte-bun-app/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:28:6)
    at <anonymous> (/Users/jamesriordan/Workspaces/Personal/Code/sandbox/test-svelte-bun-app/node_modules/@sveltejs/kit/src/exports/vite/index.js:444:52)
    at configureServer (/Users/jamesriordan/Workspaces/Personal/Code/sandbox/test-svelte-bun-app/node_modules/@sveltejs/kit/src/exports/vite/index.js:444:26)
    at <anonymous> (/Users/jamesriordan/Workspaces/Personal/Code/sandbox/test-svelte-bun-app/node_modules/vite/dist/node/chunks/dep-df561101.js:65158:20)
    at processTicksAndRejections (:1:1302)
error: script "dev" exited with code 1 (SIGHUP)
```

**Comment by notramo** [comment] 2023-12-16 11:59
This seems to be fixed in the latest release. I could not reproduce it with the provided instructions, and it works as intended.

**Comment by Jarred-Sumner** [comment] 2024-08-29 09:19
I am pretty confident this particular issue was fixed awhile ago

if any future readers still run into issues with the SvelteKit node adapter when using Bun, please file a new issue and include the error

**Closed as completed by Jarred-Sumner** 2024-08-29 09:19 UTC
Labels: bug, node.js
