### ISSUE TITLE
bun upgrade | unzip

### ISSUE THREAD

**Issue by MRgrav** [oven-sh/bun#12395] opened 2024-07-06 14:10 UTC
### What version of Bun is running?

1.1.16

### What platform is your computer?

Linux 6.9.7-zen1-1-zen x86_64 unknown

### What steps can reproduce the bug?

I don't know why unzip is not detected by bun,  unzip is installed using 
```
sudo pacman -S unzip
```

issue:
```
$ bun upgrade
Bun v1.1.18 is out! You're on v1.1.16
error: Failed to locate "unzip" in PATH. bun upgrade needs "unzip" to work.
```

**Comment by Jarred-Sumner** [comment] 2024-08-08 22:20
Duplicate of #7732

**Closed as not planned by Jarred-Sumner** 2024-08-08 22:20 UTC
Labels: bug, needs triage
