### ISSUE TITLE
install package globally

### ISSUE THREAD

**Issue by titanRoyal** [oven-sh/bun#15534] opened 2024-12-02 08:15 UTC
### How can we reproduce the crash?

when I try to Test local package I run "bun install -g ." it throws this error 
"panic(main thread): Internal Error: Do not pass posix paths to Windows APIs, was given '\package.json'. Please open an issue on GitHub with a reproduction.
oh no: Bun has crashed. This indicates a bug in Bun, not your code."

### Relevant log output

```shell

```

### Stack Trace (bun.report)

Bun v1.1.36 ([`ededc16`](<https://github.com/oven-sh/bun/tree/ededc168cf07afcdbe5ca34495c58df435ea526d>)) on windows x86_64 [AddCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '\package.json'. Please open an issue on GitHub with a reproduction.

- [`string_immutable.zig:2110`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/string_immutable.zig#L2110>): `assertIsValidWindowsPath`
- [`sys.zig:1015`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/sys.zig#L1015>): `openFileAtWindowsNtPath`
- [`sys.zig:1158`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/sys.zig#L1158>): `openFileAtWindowsT`
- [`interpreter.zig:12370`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/shell/interpreter.zig#L12370>): `openat`
- [`install.zig:1009`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/install.zig#L1009>): `isNull`
- [`install.zig:12820`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/install.zig#L12820>): `installPackageWithNameAndResolution`
- [`install.zig:13248`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/install.zig#L13248>): `installPackage`
- [`install.zig:13739`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/install.zig#L13739>): `installPackages`
- [`install.zig:14540`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/install.zig#L14540>): `installWithManager`
- [`install.zig:10675`](<https://github.com/oven-sh/bun/blob/ededc168cf07afcdbe5ca34495c58df435ea526d/src/install/install.zig#L10675>): `updatePackageJSONAndInstallWithManagerWithUpdates`

Features: lockfile\_migration\_from\_package\_lock

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6043445292/">BUN-7ZF</a></strong></sub>

**Comment by RiskyMH** [comment] 2024-12-02 13:48
Duplicate of #13806.

Also if you `bun link` and `bunx <package_name>@link:<package_name>` you can test your package locally (though it would be nice if this was easier).

**Closed as not planned by RiskyMH** 2024-12-02 13:48 UTC
Labels: crash, windows
