### ISSUE TITLE
Out of nowhere: dependency loop error on `bun install`

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#6108] opened 2023-09-27 16:19 UTC
Getting this error on my Mac and inside a Docker devcontainer:
```txt
error: DependencyLoop

----- bun meta -----
Bun v1.0.3 (25e69c71) Linux arm64 #1 SMP Mon Sep 18 21:45:38 UTC 2023
InstallCommand: 
Elapsed: 27ms | User: 10ms | Sys: 22ms
RSS: 36.71MB | Peak: 38.14MB | Commit: 36.71MB | Faults: 0
----- bun meta -----

0   0xaaaae0986698
1   ???
2   ???
3   ???
4   ???
5   ???
```

I suddenly received this error. It was working fine just a few minutes ago (installing deps). I tried removing the Bun cache, uninstalling Bun, and even tried the canary version (currently on 1.0.3), but none of these solutions worked. Has anyone else experienced this issue recently?

> Aha! I know what was wrong. I setup Triplex (a React-Three-Fiber editor), which added moved some dev deps up to be normal dependencies. I did this yesterday, and it worked fine (probably, I haven't do any new clean clone and install since then). But afterwards, Bun ran into issues.

![](https://media.discordapp.net/attachments/1156610881271107594/1156613508939653170/CleanShot_2023-09-27_at_17.28.01.png?ex=65159bc5&is=65144a45&hm=88c377acb563ca0a8d3eece0ee3c1bf8032e9373651018c3b7a73257e72e90a2&=&width=824&height=784)

_Originally reported on Discord: [`Out of nowhere: dependency loop error on `bun install``](https://discord.com/channels/876711213126520882/1156610881271107594/1156610881271107594)_

**Comment by Electroid** [comment] 2023-09-27 16:20
Duplicate of #5789

**Closed as not planned by Electroid** 2023-09-27 16:20 UTC
Labels: bug, crash, bun install
