### ISSUE TITLE
Floating point error

### ISSUE THREAD

**Issue by pheuter** [oven-sh/bun#11035] opened 2024-05-13 12:06 UTC
### Relevant log output

```
Bun v1.1.8 (89d25807) Linux x64 (baseline)
2024-05-13T00:54:15Z app[91852d57f92538] ewr [info]Args: "bun", "./src/jobs/employeeQualificationReminder.ts"
2024-05-13T00:54:15Z app[91852d57f92538] ewr [info]Features: jsc bunfig
2024-05-13T00:54:15Z app[91852d57f92538] ewr [info]Elapsed: 1ms | User: 0ms | Sys: 2ms
2024-05-13T00:54:15Z app[91852d57f92538] ewr [info]RSS: 1.07GB | Peak: 84.94MB | Commit: 1.07GB | Faults: 1
2024-05-13T00:54:15Z app[91852d57f92538] ewr [info]panic(main thread): Floating point error at address 0x564E695F4615
2024-05-13T00:54:15Z app[91852d57f92538] ewr [info]oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on linux x86_64_baseline [AutoCommand]

Floating point exception at address 0x564E695F4615

- `??`

**Comment by Electroid** [comment] 2024-06-07 20:24
Duplicate of #11680

**Comment by Electroid** [comment] 2024-06-07 20:24
This is likely a duplicate of another issue. We've improved stack traces since you made your report, so it's hard to know for sure. Follow along in that issue for updates

**Closed as not planned by Electroid** 2024-06-07 20:24 UTC
Labels: bug, crash
