### ISSUE TITLE
setTimeout and setImmediate broken

### ISSUE THREAD

**Issue by RealPeha** [oven-sh/bun#3810] opened 2023-07-25 19:51 UTC
### What version of Bun is running?

0.7.0

### What platform is your computer?

Linux 6.2.0-26-generic x86_64 x86_64

### What steps can reproduce the bug?

In NodeJS i used code like this to create a loop with given tick rate:

```ts
let tickRate = 1000 / 20; // 20 times per second
let previous = performance.now();

const loop = () => {
  const now = performance.now();
  if (previous + tickRate <= now) {
    const delta = now - previous;
    previous = now;
    // update(delta);
  }
  if (performance.now() - previous < tickRate - 4) {
    setTimeout(loop);
  } else {
    setImmediate(loop);
  }
};

loop()
```

Now ran my code in Bun and my computer is completely frozen...

Then I saw that there are some problems with setTimeout with 0 delay (https://github.com/oven-sh/bun/issues/3333). And i replaced `setTimeout(loop)` with `setTimeout(loop, 1)`. I thought it worked until my computer crashed again after ~30 seconds

Then I measured the memory usage with this code:
```ts
const formatToMB = (value: number) => {
  return Math.round((value / 1024 / 1024) * 100) / 100;
};

setInterval(() => {
  const usage = process.memoryUsage();

  console.log(
    `rss: ${formatToMB(usage.rss)} MB, heap: ${formatToMB(
      usage.heapTotal
    )} MB, used: ${formatToMB(usage.heapUsed)} MB`
  );
}, 1000);
```

And got these results
```
rss: 63.86 MB, heap: 5.46 MB, used: 0.26 MB
rss: 82.24 MB, heap: 9.81 MB, used: 0.27 MB
rss: 102.36 MB, heap: 14.54 MB, used: 0.27 MB
rss: 123.24 MB, heap: 19.47 MB, used: 0.27 MB
rss: 143.49 MB, heap: 24.24 MB, used: 0.27 MB
rss: 164.11 MB, heap: 29.09 MB, used: 0.27 MB
rss: 185.49 MB, heap: 34.16 MB, used: 0.27 MB
rss: 207.11 MB, heap: 39.25 MB, used: 0.27 MB
rss: 227.24 MB, heap: 44 MB, used: 0.27 MB
rss: 246.74 MB, heap: 48.6 MB, used: 0.27 MB
rss: 265.36 MB, heap: 53.04 MB, used: 0.27 MB
```

After i replaced setImmediate with setTimeout with 1 delay

```
// log output interval 5 seconds
rss: 42.74 MB, heap: 0.84 MB, used: 0.26 MB
rss: 43.24 MB, heap: 0.96 MB, used: 0.27 MB
rss: 47.12 MB, heap: 1.07 MB, used: 0.27 MB
rss: 47.37 MB, heap: 1.18 MB, used: 0.27 MB
rss: 47.87 MB, heap: 1.29 MB, used: 0.27 MB
rss: 48.24 MB, heap: 1.4 MB, used: 0.27 MB
rss: 48.62 MB, heap: 1.51 MB, used: 0.27 MB
rss: 48.87 MB, heap: 1.62 MB, used: 0.27 MB
rss: 49.49 MB, heap: 1.73 MB, used: 0.27 MB
rss: 49.87 MB, heap: 1.84 MB, used: 0.27 MB
rss: 50.49 MB, heap: 1.95 MB, used: 0.27 MB
```

Same code running on node
```
rss: 52.18 MB, heap: 11.43 MB, used: 8.07 MB
rss: 52.18 MB, heap: 11.43 MB, used: 7.18 MB
rss: 52.31 MB, heap: 11.43 MB, used: 7.46 MB
rss: 52.31 MB, heap: 11.43 MB, used: 7.16 MB
rss: 52.43 MB, heap: 11.43 MB, used: 7.2 MB
rss: 52.43 MB, heap: 11.43 MB, used: 7.56 MB
rss: 52.43 MB, heap: 11.43 MB, used: 8.41 MB
rss: 52.43 MB, heap: 11.43 MB, used: 7.41 MB
rss: 52.43 MB, heap: 11.43 MB, used: 7.12 MB
rss: 52.43 MB, heap: 11.43 MB, used: 6.93 MB
rss: 52.43 MB, heap: 11.43 MB, used: 7.69 MB
rss: 52.43 MB, heap: 11.68 MB, used: 8.03 MB
```

**Comment by Jarred-Sumner** [comment] 2023-07-26 00:20
If you want to create a tick loop, use `setInterval`

setImmediate runs immediately on the next tick of the event loop. setTimeout(cb, 0) is the same as setImmediate. It doesn't correspond to a timed delay, think of it more like array.push().

The memory usage growth is because the computer has the memory available and using it is faster than not using it. If you want the memory usage to not grow, pass `--smol` to Bun. By default, memory usage will stop growing when it gets closer to running out of memory

This is otherwise a duplicate of #3333

**Closed as not planned by Jarred-Sumner** 2023-07-26 00:20 UTC
Labels: bug
