### ISSUE TITLE
Looking for documentation on using bun to run existing tests 

### ISSUE THREAD

**Issue by eitanavgil** [oven-sh/bun#1194] opened 2022-09-01 15:03 UTC
### Description of the problem

So I have a pretty big mono-repo with 4 apps and many packages, I have many (really... many) tests across the apps and it takes a lot of time to run them. I currently use Jest and react-testing-library.

I am in love with bun and I really want to run these tests in a shorter time using bun, but I could not find as guid of how to run my existing tests via bun. 

When I just run `bun test` as a replacement to `yarn test` - it runs OK but with the same duration. 
if I try `bun wiptest` I get runtime errors (see a few examples below). I do not know if I am missing any configuration or doing something wrong.

I am looking for a document of how to switch existing test to run faster with bun. **I will be happy to write it myself** if I would be able to solve those issues ;) or alternatively get off this idea if I am wrong on this and cannot really improve duration of tests. 

Thanks 
```
Examples of errors I see when i try bun wiptest

ReferenceError: Can't find variable: describe

SyntaxError: Indirectly exported binding name 'BoxProps' is not found.

ReferenceError: Can't find variable: document

ReferenceError: Can't find variable: expect

ReferenceError: Can't find variable: window
```
`

**Comment by xhyrom** [comment] 2022-09-03 22:15
`bun test` => `bun run test` => will run script from package.json like `npm`, `yarn` or `pnpm` but it's faster at startup

With `bun wiptest` you must use `bun:test` package.

More info https://github.com/oven-sh/bun/issues/1062

**Comment by xhyrom** [comment] 2022-09-03 22:15
Duplicate of https://github.com/oven-sh/bun/issues/1062

**Closed as not planned** 2022-09-03 22:15 UTC
Labels: docs
