### ISSUE TITLE
bun install gives error in windows | Project devika

### ISSUE THREAD

**Issue by HarshavardhanNetha** [oven-sh/bun#10973] opened 2024-05-10 06:47 UTC
### How can we reproduce the crash?

run `bun install` from UI folder in the [repo](https://github.com/stitionai/devika), on a windows machine.

Runtime:
Miniconda
Python 3.11
Windows 11x64

### Relevant log output

```shell
bun install v1.1.7 (b0b7db5c)
  🔒 Saving lockfile... ============================================================
Bun v1.1.7 (b0b7db5c) Windows x64
Args: "C:\Users\NAME\AppData\Roaming\npm\\node_modules\bun\bin\bun.exe", "install"
Elapsed: 359ms | User: 0ms | Sys: 15ms
RSS: 53.23MB | Peak: 53.23MB | Commit: 92.04MB | Faults: 13186

panic(main thread): Internal assertion failure
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
<link>
```

### Stack Trace (bun.report)

Bun v1.1.7 ([`b0b7db5`](https://github.com/oven-sh/bun/tree/b0b7db5c060e830801b0273b7ff6e34e3eb5c254)) on windows x86_64 [InstallCommand]

**panic**: Internal assertion failure

- [`debug.zig:373`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L373): `panicExtra`
- [`debug.zig:348`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/deps/zig/lib/std/debug.zig#L348): `panic`
- [`output.zig:356`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/output.zig#L356): `panic`
- [`bun.zig:3159`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/bun.zig#L3159): `assertionFailure`
- [`lockfile.zig:4883`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/lockfile.zig#L4883): `save`
- [`lockfile.zig:1643`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/lockfile.zig#L1643): `saveToDisk`
- [`install.zig:10880`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/install/install.zig#L10880): `installWithManager`
- [`filter_run.zig:428`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli/filter_run.zig#L428): `install`
- [`cli.zig:1440`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L1440): `start`
- [`cli.zig:62`](https://github.com/oven-sh/bun/blob/b0b7db5c060e830801b0273b7ff6e34e3eb5c254/src/cli.zig#L62): `start`

**Comment by dylan-conway** [comment] 2024-05-13 21:31
Duplicate of #10849

**Closed as not planned by dylan-conway** 2024-05-13 21:31 UTC
Labels: bug, crash
