### ISSUE TITLE
Segfault when using better-sqlite3

### ISSUE THREAD

**Issue by Ayden51** [oven-sh/bun#11197] opened 2024-05-20 14:06 UTC
### How can we reproduce the crash?

Step 1: `bun init` - use all defaults.

Step 2: `bun add @paralleldrive/cuid2 better-sqlite3 drizzle-orm`.

Step 3: `bun add -D @types/better-sqlite3 drizzle-kit`.

Step 4: add `"allowSyntheticDefaultImports": true` to `tsconfig.json` file.

**Then, setup a simple Drizzle ORM project with better-sqlite3 as the database.**

Step 5: create a `drizzle.config.ts` file at the root level. The `process.env.DB_URL` are correctly pointed at my db file (tested).
```typescript
import { defineConfig } from "drizzle-kit";

export default defineConfig({
    schema: "./database/schema.ts",
    out: "./database/migrations",
    dialect: "sqlite",
    dbCredentials: {
        url: process.env.DB_URL as string,
    },
    verbose: true,
    strict: true,
});
```
Step 6: create a schema and database connection file in `./database` directory. My `db.ts` file is provided in the **"JavaScript/TypeScript code that reproduces the crash?"** section.

Step 7: run database migration with drizzle-kit CLI: `drizzle-kit generate` and `drizzle-kit migrate`. My database is successfully migrated. I've tested with `drizzle-kit studio` and it worked perfectly in the studio.

Step 8: create an `index.ts` file:
```typescript
import { db } from "./database/db";

const users = await db.query.userTable.findMany();
console.log("🚀 ~ users:", users);
```
Step 9: run the file with `bun index.ts`. Bun crashed right here.

I think there is something wrong with `bun` and `better-sqlite3` because when I change to using `bun:sqlite`, everything works.
```typescript
// import { drizzle } from "drizzle-orm/better-sqlite3";
// import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { Database } from "bun:sqlite";
import * as schema from "./schema";

const sqlite = new Database(process.env.DB_URL);
export const db = drizzle(sqlite, { schema });
```
I've only change the import line in my `db.ts` file and it just worked.

### JavaScript/TypeScript code that reproduces the crash?

```shell
import { drizzle } from "drizzle-orm/better-sqlite3";
import Database from "better-sqlite3";
import * as schema from "./schema";

console.log("🚀 ~ process.env.DB_URL:", process.env.DB_URL);
const sqlite = new Database(process.env.DB_URL);
export const db = drizzle(sqlite, { schema });
```

### Relevant log output

```shell
🚀 ~ process.env.DB_URL: ./database/sqlite.db
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at bindings (D:\CongHuy\Programming\Fullstack\bun-segfault-better-sqlite3\node_modules\bindings\bindings.js:112:48)
      at new Database (D:\CongHuy\Programming\Fullstack\bun-segfault-better-sqlite3\node_modules\better-sqlite3\lib\database.js:48:29)
      at D:\CongHuy\Programming\Fullstack\bun-segfault-better-sqlite3\database\db.ts:6:16

Bun v1.1.8 (Windows x64)
============================================================
Bun v1.1.8 (89d25807) Windows x64
Args: "C:\Users\huydc\.bun\bin\bun.exe", "index.ts"
Features: jsc dotenv tsconfig(2)
Builtins: "bun:main" "node:buffer" "node:crypto" "node:fs" "node:path" "node:string_decoder" "node:util" "node:util/types"
Elapsed: 758ms | User: 156ms | Sys: 31ms
RSS: 0.14GB | Peak: 0.14GB | Commit: 0.18GB | Faults: 34676

panic(main thread): Segmentation fault at address 0x7FFCAEA81620
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.8 ([`89d2580`](https://github.com/oven-sh/bun/tree/89d25807fbf4488d3bfcb116484d0c2cf824f98c)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FFD57FABAE0

- *1 unknown/js code*
- ??? at `0x5deb5` in ntdll.dll
- ??? at `0x5dbab` in ntdll.dll
- ??? at `0x5da8d` in ntdll.dll
- ??? at `0x1e3bb` in KERNEL32.DLL
- ??? at `0x205bc` in ucrtbase.dll
- ??? at `0x2045f` in ucrtbase.dll
- [`Global.zig:123`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/Global.zig#L123): `exitWide`
- [`Global.zig:106`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/Global.zig#L106): `exit`
- [`javascript.zig:941`](https://github.com/oven-sh/bun/blob/89d25807fbf4488d3bfcb116484d0c2cf824f98c/src/bun.js/javascript.zig#L941): `eventLoop`

**Comment by Electroid** [comment] 2024-05-20 15:48
Bun does not support `better-sqlite3` right now due to missing APIs. You can use Bun's built-in SQLite database instead.

**Comment by Electroid** [comment] 2024-05-20 15:48
Duplicate of #4290

**Closed as not planned by Electroid** 2024-05-20 15:48 UTC
Labels: crash

**Comment by Ayden51** [comment] 2024-05-20 18:08
> Bun does not support `better-sqlite3` right now due to missing APIs. You can use Bun's built-in SQLite database instead.

I think it should be clearly stated or have a warning that Bun doesn't support `better-sqlite3` yet somewhere on the `bun:sqlite` docs page just to make things clearer. I've tried searching on Google and couldn't find any pages or articles that said about this.
