### ISSUE TITLE
 Prefilled crash report

### ISSUE THREAD

**Issue by doeixd** [oven-sh/bun#12433] opened 2024-07-08 15:31 UTC
### How can we reproduce the crash?

I was attempting to use better-sqlite3 with drizzle

### Relevant log output

```js
107 |         return opts[p] || p;
108 |       })
109 |     );
110 |     tries.push(n);
111 |     try {
112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                     ^
TypeError: LoadLibrary failed: A dynamic link library (DLL) in
      at bindings (C:\Users\Pglenn\Desktop\convert\Final\amring\node_modules\bindings\bindings.js:112:48)
      at new Database (C:\Users\Pglenn\Desktop\convert\Final\amring\node_modules\better-sqlite3\lib\database.js:48:29)
      at C:\Users\Pglenn\Desktop\convert\Final\amring\drizzle\index.mts:10:16

Bun v1.1.18 (Windows x64)
============================================================
Bun v1.1.18 (5a0b9352) Windows x64
Args: "C:\Users\Pglenn\.bun\bin\bun.exe" ".\steps\create_category_tree.test.mjs" "--inform" "--no-dbg"
Features: jsc Bun.stdin(2) dotenv tsconfig(2)
Builtins: "bun:main" "node:buffer" "node:crypto" "node:domain" "node:fs" "node:fs/promises" "node:http" "node:os" "node:path" "node:process" "node:string_decoder" "node:url" "node:util" "node:util/types" "node-fetch"
Elapsed: 630ms | User: 406ms | Sys: 125ms
RSS: 0.17GB | Peak: 0.17GB | Commit: 0.18GB | Faults: 41711

panic(main thread): Segmentation fault at address 0x7FFDF10F1690
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:


```

### Stack Trace (bun.report)

Bun v1.1.18 ([`5a0b935`](<https://github.com/oven-sh/bun/tree/5a0b93523134ca0043ee7ae84f01003aa4b7ff69>)) on windows x86_64 [AutoCommand]

Segmentation fault at address 0x7FFDF10F1690

- *1 unknown/js code*
- ??? at `0x48abf` in ntdll.dll
- ??? at `0xdb7ed` in ntdll.dll
- ??? at `0xdab14` in ntdll.dll
- ??? at `0x442db` in KERNEL32.DLL
- ??? at `0xa0663` in ucrtbase.dll
- [`Global.zig:123`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/Global.zig#L123>): `exitWide`
- [`Global.zig:106`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/Global.zig#L106>): `exit`
- [`bun_js.zig:307`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/src/bun_js.zig#L307>): `start`
- [`Ref.h:48`](<https://github.com/oven-sh/bun/blob/5a0b93523134ca0043ee7ae84f01003aa4b7ff69/C:/a/bun/bun/build/bun-webkit/include/wtf/Ref.h#L48>): `WTF::DefaultRefDerefTraits<WTF::StringImpl>::refIfNotNull`

**Comment by Jarred-Sumner** [comment] 2024-07-08 22:01
Duplicate of https://github.com/oven-sh/bun/issues/4290

**Comment by Jarred-Sumner** [comment] 2024-07-08 22:01
Please follow along in #4290

**Closed as not planned by Jarred-Sumner** 2024-07-08 22:01 UTC
Labels: crash, windows
