### ISSUE TITLE
Crash installing packages

### ISSUE THREAD

**Issue by Verzach3** [oven-sh/bun#11466] opened 2024-05-30 16:44 UTC
### How can we reproduce the crash?

The error happens with an old package-lock.json my project happens to have, i removed it and bun install worked, this is the [link to my repo](https://github.com/Verzach3/clinic-landing-next/tree/9491c6a5a08ad80ebcb21ec30d2314ecd8d70913) in a commit with the old package-lock.json

### Relevant log output

```shell
[13.81ms] migrated lockfile from package-lock.json
warn: incorrect peer dependency "embla-carousel-react@8.0.0-rc19"
  📦 Installing [74/761] ============================================================
Bun v1.1.10 (5102a944) Windows x64
Args: "C:\Users\gabri\.bun\bin\bun.exe" "install"
Features: extracted_packages(3) lockfile_migration_from_package_lock 
Elapsed: 682ms | User: 125ms | Sys: 765ms
RSS: 0.18GB | Peak: 0.18GB | Commit: 0.29GB | Faults: 45359

panic(main thread): index out of bounds
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.10 ([`5102a94`](<https://github.com/oven-sh/bun/tree/5102a944307d56933a6bb039b99ad76a758b46e4>)) on windows x86_64 [InstallCommand]

**panic**: index out of bounds

- [`install.zig:5119`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5119>): `processDependencyListItem`
- [`install.zig:5177`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5177>): `processDependencyList`
- [`install.zig:5895`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L5895>): `runTasks`
- [`install.zig:10411`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/install/install.zig#L10411>): `installPackages`
- [`filter_run.zig:430`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli/filter_run.zig#L430>): `install`
- [`cli.zig:1461`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L1461>): `start`
- [`cli.zig:62`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/cli.zig#L62>): `start`
- [`main.zig:51`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/main.zig#L51>): `main`
- [`exe_common.inl:78`](<https://github.com/oven-sh/bun/blob/5102a944307d56933a6bb039b99ad76a758b46e4/src/src/startup/exe_common.inl#L78>): `invoke_main`
- ??? at `0x1257d` in KERNEL32.DLL

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:43
Duplicate of https://github.com/oven-sh/bun/issues/10565

**Comment by Jarred-Sumner** [comment] 2024-06-04 22:43
To track this issue, please follow along in https://github.com/oven-sh/bun/issues/10565

**Closed as not planned by Jarred-Sumner** 2024-06-04 22:43 UTC
Labels: crash
