### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by R0N1n-dev** [oven-sh/bun#1013] opened 2022-08-07 09:32 UTC
### Version

illegal instruction

### Platform

Linux ronin-HP-Laptop 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

install bun using script (downloaded baseline build linux x64 0.1.7)
Add to bash
Use any bun command

### How often does it reproduce? Is there a required condition?

Any bun command brings 'illegal instruction'

### What is the expected behavior?

A bun version is displayed
e.g.

bun -v
0.1.7

### What do you see instead?

illegal instruction

**Comment by xhyrom** [comment] 2022-08-07 15:38
Duplicate of https://github.com/oven-sh/bun/issues/1011

**Closed as completed by xhyrom** 2022-08-07 15:38 UTC
Labels: bug, needs repro
