### ISSUE TITLE
PM: "Caret" version installing new major version for suffixed versions

### ISSUE THREAD

**Issue by jpasquers** [oven-sh/bun#6688] opened 2023-10-24 14:56 UTC
### What version of Bun is running?

1.0.7

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

1. Fresh bun project
2. `bun add @material-ui/lab@^4.0.0-alpha.56`
3. `bun pm ls --all` will show:

├── @material-ui/lab@5.0.0-alpha.9

### What is the expected behavior?

The expected behavior would be to not go to the next major version. In this case, the expected version should be `4.0.0-alpha.61`

### What do you see instead?

` @material-ui/lab@5.0.0-alpha.9`

**Comment by Electroid** [comment] 2023-10-24 15:02
We will fix this. Duplicate of #6683

**Comment by Electroid** [comment] 2023-10-24 15:02
Duplicate of #6683

**Closed as not planned by Electroid** 2023-10-24 15:02 UTC
Labels: bug
