### ISSUE TITLE
Instant segfault on Bun versions 1.1.10+ when running a file bundled with bun build

### ISSUE THREAD

**Issue by evelant** [oven-sh/bun#12015] opened 2024-06-20 21:10 UTC
### How can we reproduce the crash?

Still trying to figure out a reproduction. I bundle my app for deployment to fly.io like so: `bun build --target=bun --sourcemap=external --outdir=dist src/index.ts`. Have done this for a long time without issue. Suddenly on bun versions higher than 1.1.9 running the output of the build segfaults instantly. I rolled back to 1.1.5 and it runs without issue.

The segfault happens on linux or macos.

### Relevant log output

```shell
There's not a lot to go on. This is the full output when trying to run the bundled file.


Bun v1.1.10 (5102a944) macOS Silicon
Args: "/etc/profiles/per-user/imagio/bin/bun" "dist/index.js"
Features: jsc dotenv(2) fetch tsconfig_paths(2) tsconfig(4)
Builtins: "bun:main" "node:async_hooks" "node:buffer" "node:child_process" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:readline" "node:stream" "node:stream/promises" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "node:punycode" "node-fetch" "node:diagnostics_channel"
Elapsed: 558ms | User: 471ms | Sys: 90ms
RSS: 0.21GB | Peak: 0.27GB | Commit: 2.15GB | Faults: 1467

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

The same file runs without issue on 1.1.5.
```


### Stack Trace (bun.report)

Bun v1.1.14 ([`7c27f3f`](<https://github.com/oven-sh/bun/tree/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f>)) on linux x86_64_baseline [AutoCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`StringImpl.h:1154`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f//build/bun/bun-webkit/include/wtf/text/StringImpl.h#L1154>): `Bun::formatStackTrace`
- [`ZigGlobalObject.cpp:571`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f/src/bun.js/bindings/ZigGlobalObject.cpp#L571>): `computeErrorInfoWithoutPrepareStackTrace`
- [`ZigGlobalObject.cpp:663`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f/src/bun.js/bindings/ZigGlobalObject.cpp#L663>): `computeErrorInfoWrapper`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f//build/bun/bun-webkit/include/wtf/Function.h#L53>): `WTF::Detail::CallableWrapper<WTF::String (...)(...), WTF::String, JSC::VM&, WTF::Vector<JSC::StackFrame, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, unsigned int&, unsigned int&, WTF::String&, JSC::JSObject*>::call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f/ld-temp.o#L0>): `JSC::ErrorInstance::computeErrorInfo`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f/ld-temp.o#L0>): `JSC::Heap::runEndPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f/ld-temp.o#L0>): `JSC::Heap::runCurrentPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/7c27f3f9b43eff454d2a48b64c5d083a5ae49e9f/ld-temp.o#L0>): `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`

<!-- from bun.report: t2-ArFgDSnuEbdoA13K- -->

**Comment by Jarred-Sumner** [comment] 2024-06-24 03:07
Duplicate of https://github.com/oven-sh/bun/issues/11568

**Comment by Jarred-Sumner** [comment] 2024-06-24 03:08
We are tracking this in https://github.com/oven-sh/bun/issues/11568

Please follow along in that issue

Are you able to provide a reproduction? It would be very helpful as several people have reported this issue but we haven't been able to reproduce it.

**Closed as not planned by Jarred-Sumner** 2024-06-24 03:08 UTC
Labels: crash, linux, runtime
