### ISSUE TITLE
Experiencing a weird issue with all bun commands

### ISSUE THREAD

**Issue by Elko-Lemiso** [oven-sh/bun#336] opened 2022-07-07 07:46 UTC
Installed bun on wsl2 in my home directory. 
Added the path variables to my .bashrc.

When I run any bun command except --help
I get 
```
error: Failed to initialize network thread: SystemOutdated.
HTTP requests will not work. Please file an issue and run strace().
```

**Comment by 3ventic** [comment] 2022-07-07 08:32
duplicate of #233

**Closed as completed** 2022-07-09 00:16 UTC
