### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by colindotfun** [oven-sh/bun#13499] opened 2024-08-24 05:31 UTC
### Relevant log output

```shell
bd
$ next dev
  ▲ Next.js 15.0.0-canary.41
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

/bin/sh: npm: command not found
 ✓ Ready in 2.2s
 ✓ Compiled /src/middleware in 415ms (218 modules)
============================================================
Bun v1.1.25 (fe62a614) macOS Silicon
macOS v15.0
Args: "/Users/colin/.bun/bin/bun" "/Users/colin/Desktop/projects/emmy/node_modules/next/dist/server/lib/start-server.js"
Features: jsc Bun.stderr Bun.stdin dotenv fetch(3) http_server spawn(5) transpiler_cache(7) tsconfig_paths tsconfig
Builtins: "bun:jsc" "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:constants" "node:crypto" "node:dns/promises" "node:events" "node:fs" "node:fs/promises" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:querystring" "node:stream" "node:stream/web" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:vm" "node:zlib" "node:worker_threads" "ws" "node:v8" "node:diagnostics_channel"
Elapsed: 3413ms | User: 1899ms | Sys: 338ms
RSS: 0.57GB | Peak: 0.57GB | Commit: 3.11GB | Faults: 60

panic(main thread): Segmentation fault at address 0x6764657C3D317C6C
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.25/Ma1fe62a61Auoih0D_+4j0D+4j0Du6i0D_u6x3rCu6x3rCuk92rCu6x3rCuk92rCA243yxsnD4m+lm9B
```

### Stack Trace (bun.report)

Bun v1.1.25 ([`fe62a61`](<https://github.com/oven-sh/bun/tree/fe62a614046948ebba260bed87db96287e67921f>)) on macos aarch64 [AutoCommand]

Segmentation fault at address 0x6764657C3D317C6C

- *1 unknown/js code*
- `void WebCore::setSubclassStructureIfNeeded<WebCore::DOMURL>`
- `void WebCore::setSubclassStructureIfNeeded<WebCore::DOMURL>`
- `WebCore::JSDOMConstructor<WebCore::JSDOMURL>::construct`
- *1 unknown/js code*
- `llint_entry`
- `llint_entry`
- `llint_entry`
- `llint_entry`
- `llint_entry`

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:20
Duplicate of https://github.com/oven-sh/bun/issues/13629

**Comment by Jarred-Sumner** [comment] 2024-09-01 04:20
Please follow along in https://github.com/oven-sh/bun/issues/13629. It will get fixed

**Closed as completed by Jarred-Sumner** 2024-09-01 04:20 UTC
Labels: crash, macOS, runtime
