### ISSUE TITLE
eval JS Function doesn't get external variables

### ISSUE THREAD

**Issue by LManeL26** [oven-sh/bun#5981] opened 2023-09-23 21:47 UTC
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Eval function cannot get external variables and functions, such that this.
```
function MyFN(val){
    console.log(val)
}
eval("MyFN('Nice');")
```

### What is the expected behavior?

'Nice'

### What do you see instead?

1 | MyFN('Nice');
   ^
ReferenceError: Can't find variable: MyFN

**Comment by hareeshko** [comment] 2023-09-23 22:45
can you refer to this link, Bun does not support eval. you can use template literal for this execution.

**Comment by kzc** [comment] 2023-09-24 03:03
related: #2875

**Comment by Electroid** [comment] 2023-09-24 15:43
Duplicate of #2875

**Closed as not planned by Electroid** 2023-09-24 15:43 UTC
Labels: bug
