### ISSUE TITLE
Remove cache command doesn't clear it

### ISSUE THREAD

**Issue by akshaybabloo** [oven-sh/bun#4863] opened 2023-09-10 21:44 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.2.0-32-generic x86_64 x86_64

### What steps can reproduce the bug?

Running `bun pm cache rm` doesn't clear the cache, it just prints out the path of the cache.

### What is the expected behavior?

I think it should delete all the contents in `/home/<user>/.bun/install/cache`

### What do you see instead?

Prints out the cache path

**Comment by Hanaasagi** [comment] 2023-09-11 01:26
this could be fixed by #4571

**Comment by jhmaster2000** [comment] 2023-09-12 14:09
Closing as duplicate of #1720

**Closed as not planned by jhmaster2000** 2023-09-12 14:09 UTC
Labels: bug
