### ISSUE TITLE
bignum not working

### ISSUE THREAD

**Issue by mgpai22** [oven-sh/bun#11171] opened 2024-05-18 23:43 UTC
### What version of Bun is running?

v1.1.8

### What platform is your computer?

docker

### What steps can reproduce the bug?

Trying to run the [bpp branch](https://github.com/reqlez/ErgoStratumServer/tree/bpp) using `bun run start.js`

Get this error:
```
 107 |         return opts[p] || p;
 108 |       })
 109 |     );
 110 |     tries.push(n);
 111 |     try {
 112 |       b = opts.path ? requireFunc.resolve(n) : requireFunc(n);
                                                      ^
 TypeError: /app/node_modules/bignum/build/Release/bignum.node: undefined symbol: _ZN2v814ObjectTemplate21SetInternalFieldCountEi
       at bindings (/app/node_modules/bindings/bindings.js:112:48)
       at /app/node_modules/bignum/index.js:1:5
       at /app/lib/algoProperties.js:1:5
       at /app/lib/index.js:5:1
       at /app/start.js:1:5

 Bun v1.1.8 (Linux x64 baseline)

```

**Comment by Electroid** [comment] 2024-05-20 16:06
It looks like [`bignum`](https://www.npmjs.com/package/bignum?activeTab=code) uses the V8 C++ APIs, which Bun does not yet support.

**Comment by Electroid** [comment] 2024-05-20 16:06
Duplicate of #4290

**Closed as not planned by Electroid** 2024-05-20 16:06 UTC
Labels: bug
