### ISSUE TITLE
bun crashes with "wrtc" and "classic-level"

### ISSUE THREAD

**Issue by Aviv1000** [oven-sh/bun#11744] opened 2024-06-10 09:54 UTC
### What version of Bun is running?

1.1.11

### What platform is your computer?

windows x64

### What steps can reproduce the bug?

normal include the libraries

### What do you see instead?

bun crash and exit

**Comment by Jarred-Sumner** [comment] 2024-06-10 10:14
Duplicate of #11615

**Comment by Jarred-Sumner** [comment] 2024-06-10 10:14
Please follow along in #11615

**Closed as not planned by Jarred-Sumner** 2024-06-10 10:14 UTC
Labels: bug, needs triage
