### ISSUE TITLE
execute command bunx create-astro@latest my-astro-project-using-bun, freeze console

### ISSUE THREAD

**Issue by diegorojasj** [oven-sh/bun#5040] opened 2023-09-12 04:45 UTC
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Linux 6.5.2-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

When I try to run the command and select some option, at some point the console freezes.

### What is the expected behavior?

run without issues

### What do you see instead?

![image](https://github.com/oven-sh/bun/assets/69219863/a3cede7b-8d47-4777-ae21-1e05ebd40ef4)

From this part, the console is freeze or sometimes at the beginning.

**Comment by ghiscoding** [comment] 2023-09-12 05:19
seems like duplicate of #4800, #4878 and #4664 as mentioned in PR #5035

**Closed as completed** 2023-12-14 05:52 UTC
Labels: bug
