### ISSUE TITLE
Bun.file().slice().arrayBuffer() returns an ArrayBuffer of wrong size

### ISSUE THREAD

**Issue by gyf304** [oven-sh/bun#12190] opened 2024-06-27 02:51 UTC
### What version of Bun is running?

1.1.17

### What platform is your computer?

Darwin 23.1.0 arm64 arm

### What steps can reproduce the bug?

```typescript
const arrayBuffer = new ArrayBuffer(1000);
const blob = new Blob([arrayBuffer]);

await Bun.write("test.bin", arrayBuffer);
const file = Bun.file("test.bin");

const blobSlice = await blob.slice(0, 100).arrayBuffer();
const fileSlice = await file.slice(0, 100).arrayBuffer();

console.log(blobSlice.byteLength, fileSlice.byteLength);
// expected: 100 100
// actual: 100 1000
```

**Comment by gyf304** [comment] 2024-06-27 18:32
related: #616

**Comment by Electroid** [comment] 2024-06-27 22:57
Thanks for reporting this! This is likely a duplicate of #8215, so we'll track the work there.

**Comment by Electroid** [comment] 2024-06-27 22:57
Duplicate of #8215

**Closed as not planned by Electroid** 2024-06-27 22:57 UTC
Labels: bug, needs triage
