### ISSUE TITLE
setInterval not working properly ?

### ISSUE THREAD

**Issue by aiman-al-masoud** [oven-sh/bun#306] opened 2022-07-06 22:03 UTC
I was trying to run this simple script with setInterval:

setInterval(()=>{console.log("hello world!")}, 2000 )

The text "hello world!"  is only printed out once to the screen, then the program exits on its own. It also seems like there's a spike in CPU usage, corresponding to the instant in which the script is run.

(I'm running bun 0.1.1 on Ubuntu 20.04, kernel 5.13.0-52-generic, with an Intel core i5).

**Comment by Jarred-Sumner** [comment] 2022-07-06 23:17
The cause is the same as #292 , so closing as duplicate

**Closed as not planned by Jarred-Sumner** 2022-07-06 23:17 UTC
