### ISSUE TITLE
bun crashed while init sqlite tables

### ISSUE THREAD

**Issue by donnior** [oven-sh/bun#14887] opened 2024-10-29 09:02 UTC
### How can we reproduce the crash?

My test code:

```
// index.ts
import { Database } from "bun:sqlite";
const db = new Database("mydb_test.sqlite", { create: true });

db.query(`CREATE TABLE IF NOT EXISTS table_a (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    col_a TEXT,
    col_b TEXT,
    col_c TEXT,
    col_d TEXT,
    col_e INTEGER,
    col_f INTEGER,
    col_g INTEGER,
    col_h TEXT,
    col_i TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);`).run()

db.query(`CREATE TABLE IF NOT EXISTS table_b (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    col_a TEXT,
    col_b TEXT,
    col_c TEXT,
    col_d INTEGER,
    col_e INTEGER,
    col_f TEXT,
    col_g TEXT
);`).run()
```

while I run `bun test.ts`, bun crashed with following info: 

============================================================
Bun v1.1.33 (247456b6) Linux x64
Linux Kernel v4.15.0 | glibc v2.27
CPU: sse42 popcnt avx avx2
Args: "bun" "run" "src/index.ts"
Features: jsc transpiler_cache(4) tsconfig(8) tsconfig_paths
Builtins: "bun:main" "bun:sqlite" "node:async_hooks" "node:buffer" "node:crypto" "node:dns" "node:events" "node:fs" "node:http" "node:https" "node:net" "node:os" "node:path" "node:querystring" "node:stream" "node:string_decoder" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:punycode" "node:http2"
Elapsed: 323ms | User: 280ms | Sys: 39ms
RSS: 1.07GB | Peak: 79.36MB | Commit: 1.07GB | Faults: 0

panic(main thread): Segmentation fault at address 0x0
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.33/lr1247456bAhgg8/fumuskE+x3P+lg82Fklxn3Fwjsn3F65p13Fwuvq4Fgv9o3Fq/8n3Fotnn3FA2AA

Illegal instruction (core dumped)

### Stack Trace (bun.report)

Bun v1.1.33 ([`247456b`](<https://github.com/oven-sh/bun/tree/247456b675d4bf4b9cd920e0a080b7002325c0df>)) on linux x86_64 [RunCommand]

Segmentation fault at address 0x00000000

- [`sqlite3.c:39643`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L39643>): `unixLock`
- [`sqlite3.c:25840`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L25840>): `sqlite3PagerSharedLock`
- [`sqlite3.c:73349`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L73349>): `btreeBeginTrans`
- [`sqlite3.c:73839`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L73839>): `sqlite3InitOne`
- [`sqlite3.c:141093`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L141093>): `sqlite3Init`
- [`sqlite3.c:141119`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L141119>): `sqlite3StartTable`
- [`sqlite3.c:174523`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L174523>): `yy_reduce`
- [`sqlite3.c:176211`](<https://github.com/oven-sh/bun/blob/247456b675d4bf4b9cd920e0a080b7002325c0df/src/bun.js/bindings/sqlite/sqlite3.c#L176211>): `sqlite3RunParser`

Features: jsc, transpiler\_cache, tsconfig, tsconfig\_paths, tsconfig\_paths

<sub>Sentry Issue: <strong><a href="https://bun-p9.sentry.io/issues/6027629723/">BUN-7MC</a></strong></sub>

**Comment by donnior** [comment] 2024-10-29 09:09
Is it because the kernel version of my Linux is too low? I saw a description about installation on Bun's website:

> Linux users — The unzip package is required to install Bun. Use sudo apt install unzip to install unzip package. Kernel version 5.6 or higher is strongly recommended, but the minimum is 5.1. Use uname -r to check Kernel version.

**Comment by nektro** [comment] 2024-10-30 01:52
duplicate of https://github.com/oven-sh/bun/issues/14442

this happens because right now we assume glibc is >= 2.28, but we will fix this

**Closed as completed by nektro** 2024-10-30 01:52 UTC
Labels: crash, linux, runtime
