### ISSUE TITLE
Self referencing (circular) imports do not work on Bun but do work on Node

### ISSUE THREAD

**Issue by asplunds** [oven-sh/bun#4566] opened 2023-09-08 08:56 UTC
### What version of Bun is running?

1.0.3

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

I made an example repo [here](https://github.com/asplunds/bun-circular-import)

1. `git clone https://github.com/asplunds/bun-circular-import.git`
2. `cd bun-circular-import`
3. `bun i`

Works (node): `bun run node` (outputs 2)

Fails (bun): `bun run bun` (outputs "ReferenceError: Cannot access uninitialized variable.")

### What is the expected behavior?

Outputs 2

### What do you see instead?

ReferenceError: Cannot access uninitialized variable.

**Comment by asplunds** [comment] 2023-09-26 09:12
Update: this was originally tested on 0.8.1, it has not been fixed on 1.0.3

**Comment by Electroid** [comment] 2023-10-24 13:29
Duplicate of #2927

**Closed as not planned by Electroid** 2023-10-24 13:29 UTC
Labels: bug
