### ISSUE TITLE
Weird behaviour with instanceof and hotreload

### ISSUE THREAD

**Issue by LucyEgan** [oven-sh/bun#13879] opened 2024-09-11 08:18 UTC
### What version of Bun is running?

1.1.26+0a37423ba

### What platform is your computer?

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Not 100% sure on this as not able to make a minimal example yet.
Mostly documenting in case others run into this.

---
Having a CustomError class that extends Error in 1 file.
Which is thrown from some files in the code base.
The file that includes the class isn't the same as the one checking with instanceof after the hot reload, 1 of them is holding onto the old version of the class.
bun started with `bun --hot --inspect=*:3002/bunnies index.ts`

When modifying some files causes the hot reload where the `new CustomError` to not be the same class as the `instanceof CustomError`

### What is the expected behavior?

After hot reload the CustomError class to match across different files

### What do you see instead?

Intermittent behaviour in the hot reloaded CustomError class across different files

### Additional information

The codebase that it happens is large with a lot of custom logic, so it might be something caching related that survives across the hot reloads rather than just all the files in memory

**Comment by Jarred-Sumner** [comment] 2024-09-11 08:23
this is unfortunately expected 

hot reloading reloads another copy of your app, on top of the previous copy without clearing any event listeners or other state beforehand

**Comment by LucyEgan** [comment] 2024-09-11 08:32
@Jarred-Sumner I thought this might of been the case, thanks for confirming that I'm not going insane 🤣.
Its strange that in the simple use case I was trying to recreate it was behaving though, is there anything you can think of that will case it/a way to avoid it?

I noticed in the large application that if I cause a change in the CustomError class file (that the throw and instanceof files import) it will fix it until one of the importing files change again.

Breaks it
```
instanceof.ts << either change this (hot reloads)
throw.ts << or change this (hot reloads)
CustomError.ts
```

Fixes it
```
instanceof.ts
throw.ts
CustomError.ts << change this (hot reloads)
```

**Comment by Jarred-Sumner** [comment] 2024-09-12 06:13
Closing as not planned since this is expected behavior

You can use the `globalThis` object to store global state when necessary in hot reloads, and that can be useful for preventing issuesl ike this by ensuring some code only runs once (memoizing)

**Closed as not planned by Jarred-Sumner** 2024-09-12 06:13 UTC
Labels: bug, needs triage
