### ISSUE TITLE
`worker_threads.Worker` option `"eval"` is not yet implemented

### ISSUE THREAD

**Issue by hong6316** [oven-sh/bun#9816] opened 2024-04-02 01:10 UTC
### What version of Bun is running?

1.1.0

### What platform is your computer?

Linux 5.15.0-60-generic x86_64 x86_64

### What steps can reproduce the bug?

$ bun i -g enactjs/cli#feature/WRQ-364
$ enact create myapp `(ERROR: undefined is not a function...) will be shown but ignore that`
$ cd myapp
$ enact pack -p --verbose

### What is the expected behavior?

no error

### What do you see instead?

errors occurred

> NotImplementedError: worker_threads.Worker option "eval" is not yet implemented in Bun.
 code: "ERR_NOT_IMPLEMENTED"      at new NotImplementedError (internal:shared:19:27)
      at internal:shared:9:73
      at new Worker (node:worker_threads:117:27)
      at initialize (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
      at new ExperimentalWorker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:5)
      at createWorker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/WorkerPool.js:44:12)
      at new BaseWorkerPool (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:22)
      at new WorkerPool (:1:33)
      at new Worker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/index.js:167:26)
      at getWorker (/home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:362:9)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:450:41
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:390:39
      at next (/home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:63:7)
      at forEach (:1:21)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:65:5
      at new Promise (:1:21)
      at throttleAll (/home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:41:10)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:579:1114 |   warned.add(feature), console.warn(new NotImplementedError(feature, issue));
15 | }, $;
16 | 
17 | class NotImplementedError extends Error {
18 |   code;
19 |   constructor(feature, issue) {
                               ^
NotImplementedError: worker_threads.Worker option "stdout" is not yet implemented in Bun.
 code: "ERR_NOT_IMPLEMENTED"      at new NotImplementedError (internal:shared:19:27)
      at internal:shared:9:73
      at new Worker (node:worker_threads:117:27)
      at initialize (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
      at new ExperimentalWorker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:5)
      at createWorker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/WorkerPool.js:44:12)
      at new BaseWorkerPool (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:22)
      at new WorkerPool (:1:33)
      at new Worker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/index.js:167:26)
      at getWorker (/home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:362:9)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:450:41
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:390:39
      at next (/home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:63:7)
      at forEach (:1:21)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:65:5
      at new Promise (:1:21)
      at throttleAll (/home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:41:10)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:579:1114 |   warned.add(feature), console.warn(new NotImplementedError(feature, issue));
15 | }, $;
16 | 
17 | class NotImplementedError extends Error {
18 |   code;
19 |   constructor(feature, issue) {
                               ^
NotImplementedError: worker_threads.Worker option "stderr" is not yet implemented in Bun.
 code: "ERR_NOT_IMPLEMENTED"      at new NotImplementedError (internal:shared:19:27)
      at internal:shared:9:73
      at new Worker (node:worker_threads:117:27)
      at initialize (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
      at new ExperimentalWorker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:5)
      at createWorker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/WorkerPool.js:44:12)
      at new BaseWorkerPool (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:22)
      at new WorkerPool (:1:33)
      at new Worker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/index.js:167:26)
      at getWorker (/home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:362:9)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:450:41
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:390:39
      at next (/home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:63:7)
      at forEach (:1:21)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:65:5
      at new Promise (:1:21)
      at throttleAll (/home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:41:10)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:579:1114 |   warned.add(feature), console.warn(new NotImplementedError(feature, issue));
15 | }, $;
16 | 
17 | class NotImplementedError extends Error {
18 |   code;
19 |   constructor(feature, issue) {
                               ^
NotImplementedError: worker_threads.Worker option "resourceLimits" is not yet implemented in Bun.
 code: "ERR_NOT_IMPLEMENTED"      at new NotImplementedError (internal:shared:19:27)
      at internal:shared:9:73
      at new Worker (node:worker_threads:117:27)
      at initialize (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
      at new ExperimentalWorker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:5)
      at createWorker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/WorkerPool.js:44:12)
      at new BaseWorkerPool (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:22)
      at new WorkerPool (:1:33)
      at new Worker (/home/worker/cli/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/index.js:167:26)
      at getWorker (/home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:362:9)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:450:41
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:390:39
      at next (/home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:63:7)
      at forEach (:1:21)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:65:5
      at new Promise (:1:21)
      at throttleAll (/home/worker/cli/node_modules/terser-webpack-plugin/dist/utils.js:41:10)
      at /home/worker/cli/node_modules/terser-webpack-plugin/dist/index.js:579:11

**Comment by slorber** [comment] 2024-04-02 17:27
I also tried to run Bun 1.1 on a newly initialized Docusaurus site (related issue https://github.com/oven-sh/bun/issues/3426) and got this error.

```bash
yarn create docusaurus
bun --bun run docusaurus build
```

```
NotImplementedError: worker_threads.Worker option "eval" is not yet implemented in Bun.
 code: "ERR_NOT_IMPLEMENTED"

      at new NotImplementedError (internal:shared:19:27)
      at internal:shared:9:73
      at new Worker (node:worker_threads:117:27)
      at initialize (/Users/sebastienlorber/Desktop/website/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
      at new ExperimentalWorker (/Users/sebastienlorber/Desktop/website/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:5)
      at createWorker (/Users/sebastienlorber/Desktop/website/node_modules/jest-worker/build/WorkerPool.js:44:12)
      at new BaseWorkerPool (/Users/sebastienlorber/Desktop/website/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:22)
      at new WorkerPool (:1:33)
      at new Worker (/Users/sebastienlorber/Desktop/website/node_modules/jest-worker/build/index.js:167:26)
      at getWorker (/Users/sebastienlorber/Desktop/website/node_modules/terser-webpack-plugin/dist/index.js:362:9)
      at /Users/sebastienlorber/Desktop/website/node_modules/terser-webpack-plugin/dist/index.js:450:41
      at /Users/sebastienlorber/Desktop/website/node_modules/terser-webpack-plugin/dist/index.js:390:39
      at next (/Users/sebastienlorber/Desktop/website/node_modules/terser-webpack-plugin/dist/utils.js:63:7)
      at forEach (:1:21)
      at /Users/sebastienlorber/Desktop/website/node_modules/terser-webpack-plugin/dist/utils.js:65:5
      at new Promise (:1:21)
      at throttleAll (/Users/sebastienlorber/Desktop/website/node_modules/terser-webpack-plugin/dist/utils.js:41:10)
      at /Users/sebastienlorber/Desktop/website/node_modules/terser-webpack-plugin/dist/index.js:579:11
```

Similarly I got: 

```
NotImplementedError: worker_threads.Worker option "stdout" is not yet implemented in Bun.
NotImplementedError: worker_threads.Worker option "stderr" is not yet implemented in Bun.
NotImplementedError: worker_threads.Worker option "resourceLimits" is not yet implemented in Bun.
```

All coming from `terser-webpack-plugin > jest-worker`

**Comment by Electroid** [comment] 2024-04-08 16:22
Duplicate of #4165

**Closed as completed by Electroid** 2024-04-08 16:22 UTC
Labels: bug, node.js

**Comment by Jarred-Sumner** [comment] 2024-06-04 11:09
Fixed in https://github.com/oven-sh/bun/pull/11537
