### ISSUE TITLE
Bun crashes when trying to install local package globally

### ISSUE THREAD

**Issue by AhmedBaset** [oven-sh/bun#12542] opened 2024-07-13 10:50 UTC
### How can we reproduce the crash?

- Create a simple CLI
- Run `bun install . -g`

`pnpm install . -g` works but bun not

### Relevant log output

```shell
bun add v1.1.20 (ae194892)
============================================================
Bun v1.1.20 (ae194892) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\A7med\.bun\bin\bun.exe" "add" "." "-g"
Elapsed: 33ms | User: 0ms | Sys: 0ms
RSS: 61.42MB | Peak: 61.42MB | Commit: 110.64MB | Faults: 15184

panic(main thread): Internal Error: Do not pass posix paths to Windows APIs, was given '\package.json'. Please open an issue on GitHub with a reproduction.
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
```

### Stack Trace (bun.report)

Bun v1.1.20 ([`ae19489`](<https://github.com/oven-sh/bun/tree/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66>)) on windows x86_64 [AddCommand]

**panic**: Internal Error: Do not pass posix paths to Windows APIs, was given '\package.json'. Please open an issue on GitHub with a reproduction.

- [`mem.zig:4130`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/deps/zig/lib/std/mem.zig#L4130>): `sliceAsBytes`
- [`sys.zig:999`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/sys.zig#L999>): `openFileAtWindowsNtPath`
- [`sys.zig:1142`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/sys.zig#L1142>): `openFileAtWindowsT`
- [`install.zig:1115`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/install/install.zig#L1115>): `verify`
- [`install.zig:12278`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/install/install.zig#L12278>): `installPackageWithNameAndResolution`
- [`install.zig:12693`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/install/install.zig#L12693>): `installPackage`
- [`install.zig:13171`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/install/install.zig#L13171>): `installPackages`
- [`install.zig:13976`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/install/install.zig#L13976>): `installWithManager`
- [`install.zig:10178`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/install/install.zig#L10178>): `updatePackageJSONAndInstallWithManagerWithUpdates`
- [`install.zig:9725`](<https://github.com/oven-sh/bun/blob/ae19489250ab74ee3ea7d5b50fca5d7d2b4e6d66/src/install/install.zig#L9725>): `updatePackageJSONAndInstall`

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:52
Duplicate of https://github.com/oven-sh/bun/issues/11215

**Comment by Jarred-Sumner** [comment] 2024-08-06 07:52
Please follow along in #11215

**Closed as not planned by Jarred-Sumner** 2024-08-06 07:52 UTC
Labels: crash, windows
