### ISSUE TITLE
Error when running next dev (app dir) via --bun

### ISSUE THREAD

**Issue by The-Code-Monkey** [oven-sh/bun#6141] opened 2023-09-28 12:21 UTC
### What version of Bun is running?

1.0.4+387f1260c9dc0cea667b44ec0152fff0cd4def25

### What platform is your computer?

Darwin 22.6.0 arm64 arm

### What steps can reproduce the bug?

Create an app dir next project and run bun --bun next dev

### What is the expected behavior?

Should load the site

### What do you see instead?

```
- error 29 |     let ErrorType = Error;
30 |     if (serializedErr.name === "PageNotFoundError") {
31 |         ErrorType = _utils.PageNotFoundError;
32 |     }
33 |     const err = new ErrorType(serializedErr.message);
34 |     err.stack = serializedErr.stack;
                                 ^
TypeError: The "original" argument must be of type Function
      at /node_modules/next/dist/server/lib/server-ipc/request-utils.js:34:30

```

**Comment by heecheon92** [comment] 2023-10-02 06:23
On bun's guide (https://bun.sh/guides/ecosystem/nextjs)

It mentions 

```
The Next.js [App Router](https://nextjs.org/docs/app) currently relies on Node.js APIs that Bun does not yet implement.
The guide below uses Bun to initialize a project and install dependencies, but it uses Node.js to run the dev server.
```

but "--bun" flag makes the use of bun runtime which currently isn't supported for app directory....

**Comment by Electroid** [comment] 2023-10-27 21:59
Duplicate of #5122

**Closed as not planned by Electroid** 2023-10-27 21:59 UTC
Labels: bug
