### ISSUE TITLE
bunx --bun vite fails when default server port already in use

### ISSUE THREAD

**Issue by leoplaw** [oven-sh/bun#5068] opened 2023-09-12 09:23 UTC
### What version of Bun is running?

1.0.0

### What platform is your computer?

Linux 6.1.10-2.g2a0570b-default x86_64 x86_64

### What steps can reproduce the bug?

Start an instance of Vite server which defaults to port 5173
Start a second instance of Vite server fails

bunx --bun vite

### What is the expected behavior?

Vite server should auto increment the port number until it finds a free port to use, which is the standard Vite behaviour.

### What do you see instead?

bunx --bun vite
331 |       family: isIPv6(address) ? "IPv6" : "IPv4",
332 |       port: this.#server.port
333 |     };
334 |   }
335 | 
336 |   listen(port, host, backlog, onListen) {
                   ^
error: Failed to start server. Is port 5173 in use?
      at listen (node:http:336:16)
      at processTicksAndRejections (:1:2602)

  VITE v4.3.9  ready in 557 ms

**Comment by sirenkovladd** [comment] 2023-09-12 16:09
Maybe related to https://github.com/oven-sh/bun/issues/4358

**Comment by pegiadise** [comment] 2023-09-12 20:45
Duplicate #3767?

**Comment by Electroid** [comment] 2023-10-27 22:06
Duplicate of #3767, which was fixed.

**Closed as completed by Electroid** 2023-10-27 22:06 UTC
Labels: bug
