### ISSUE TITLE
bun shell can't get output when using mp4dump

### ISSUE THREAD

**Issue by lvzhenbo** [oven-sh/bun#12679] opened 2024-07-20 07:44 UTC
### What version of Bun is running?

1.1.20+ae1948925

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

https://github.com/axiomatic-systems/Bento4
```js
import { $ } from "bun";

async function getPssh(file: string) {
  // const mp4dump = Bun.spawn([
  //   "./mp4dump.exe",
  //   "--verbosity",
  //   "3",
  //   "--format",
  //   "json",
  //   file,
  // ]);
  // await mp4dump.exited;
  // if (mp4dump.exitCode !== 0) {
  //   throw new Error(`mp4dump process exited with code ${mp4dump.exitCode}`);
  // }
  const jsonInfo =
    await $`./mp4dump.exe --verbosity 3 --format json ${file}`.json();
  console.log(jsonInfo);

  // const jsonInfo = await new Response(mp4dump.stdout).json();

  let psshData = "";

  for (const temp of jsonInfo) {
    if (temp["name"] === "moov") {
      for (const child of temp["children"]) {
        if (
          "system_id" in child &&
          child["system_id"] ===
            "[ed ef 8b a9 79 d6 4a ce a3 c8 27 dc d5 1d 21 ed]"
        ) {
          psshData = child["data"];
          break;
        }
      }
      break;
    }
  }

  psshData = psshData.replace("[", "").replace("]", "").replace(/\s+/g, "");
  return Buffer.from(psshData, "hex").toString("base64");
}
const filePath = process.argv[2];
getPssh(filePath)
  .then((pssh) => console.log(pssh))
  .catch((error) => console.error(error));

```

### What is the expected behavior?

There should be an output

### What do you see instead?

Nothing.
![image](https://github.com/user-attachments/assets/efd78288-619f-4218-8139-38461d706e37)

### Additional information

Is the program interrupted because the output is too large?

**Comment by Jarred-Sumner** [comment] 2024-07-20 08:59
what if you do
```ts
import { $ } from "bun";

async function getPssh(file: string) {
  // const mp4dump = Bun.spawn([
  //   "./mp4dump.exe",
  //   "--verbosity",
  //   "3",
  //   "--format",
  //   "json",
  //   file,
  // ]);
  // await mp4dump.exited;
  // if (mp4dump.exitCode !== 0) {
  //   throw new Error(`mp4dump process exited with code ${mp4dump.exitCode}`);
  // }
  const jsonInfo =
    await $`./mp4dump.exe --verbosity 3 --format json ${file}`.json();
  console.log(jsonInfo);

  // const jsonInfo = await new Response(mp4dump.stdout).json();

  let psshData = "";

  for (const temp of jsonInfo) {
    if (temp["name"] === "moov") {
      for (const child of temp["children"]) {
        if (
          "system_id" in child &&
          child["system_id"] ===
            "[ed ef 8b a9 79 d6 4a ce a3 c8 27 dc d5 1d 21 ed]"
        ) {
          psshData = child["data"];
          break;
        }
      }
      break;
    }
  }

  psshData = psshData.replace("[", "").replace("]", "").replace(/\s+/g, "");
  return Buffer.from(psshData, "hex").toString("base64");
}
const filePath = process.argv[2];
await getPssh(filePath)
```

**Comment by lvzhenbo** [comment] 2024-07-20 09:06
@Jarred-Sumner  This works, but why, I think it should be the same from the syntax side of the equation

**Comment by Jarred-Sumner** [comment] 2024-07-20 09:14
Fixed by https://github.com/oven-sh/bun/pull/11950

**Comment by Jarred-Sumner** [comment] 2024-09-06 20:56
Duplicate of https://github.com/oven-sh/bun/issues/13713

**Comment by Jarred-Sumner** [comment] 2024-09-06 20:56
This is being tracked in https://github.com/oven-sh/bun/issues/13713

**Closed as not planned by Jarred-Sumner** 2024-09-06 20:56 UTC
Labels: bug, needs triage
