### ISSUE TITLE
Segmentation fault when running AWS CDK

### ISSUE THREAD

**Issue by andreif** [oven-sh/bun#9434] opened 2024-03-15 11:01 UTC
### What version of Bun is running?

1.0.31

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

```dockerfile
FROM --platform=linux/aarch64 oven/bun
RUN bun install -g aws-cdk
RUN bun x cdk init app --language typescript
RUN bun install
RUN sed -i 's/npx ts-node --prefer-ts-exts/bun/g' cdk.json
CMD ["x", "cdk", "synth"]
```

For `--platform=linux/amd64` it hangs forever.

### What is the expected behavior?

It works for node 21.7.4 so I would expect Bun to succeed too.

### What do you see instead?

It's usually a segmentation fault (error 139) or it gets killed
```
Killed

Subprocess exited with error 137
```

**Comment by Zeryther** [comment] 2024-03-15 12:44
Experiencing this too, but I believe it's a duplicate of #5398

**Comment by Electroid** [comment] 2024-03-15 17:04
Duplicate of https://github.com/oven-sh/bun/issues/5398

**Closed as not planned by Electroid** 2024-03-15 17:04 UTC
Labels: bug
