### ISSUE TITLE
error: Unsupported dependency type git for "git+https://github.com/ethereumjs/ethereumjs-abi.git"

### ISSUE THREAD

**Issue by ngmisl** [oven-sh/bun#1089] opened 2022-08-16 21:19 UTC
### Version

0.1.8

### What do you see instead?

bun install v0.1.8
error: Unsupported dependency type git for "git+https://github.com/ethereumjs/ethereumjs-abi.git"

**Comment by xhyrom** [comment] 2022-08-17 12:02
Duplicate of https://github.com/oven-sh/bun/issues/82

**Closed as completed by xhyrom** 2022-08-17 12:02 UTC
Labels: bug, needs repro
