### ISSUE TITLE
Trying to make SSE server with bun.serve()

### ISSUE THREAD

**Issue by hyuzea** [oven-sh/bun#2090] opened 2023-02-16 23:50 UTC
### What version of Bun is running?

0.5.7 (canary)

### What platform is your computer?

ubuntu 22.04

### What steps can reproduce the bug?

sse-server.ts

```js
Bun.serve({
    port: process.env.PORT || 3000,
    fetch(req) {
        const rs = new ReadableStream({
            type: 'direct',
            async pull(c) {
                setInterval(_ => {
                    c.write(`id:${Date.now()}\ndata: {"message":"Welcome"}\n\n`)
                    c.flush(true)
                }, 4000)
            },
            cancel() {
                console.info('stream canceled\n')
            }
        })

        return new Response(rs, {
            headers: {
                'Access-Control-Allow-Origin': 'http://localhost',
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'Connection': 'keep-alive'
            }
        })
    }
})

console.info('Server started on localhost:3000')
```

sse-client.js
```js
     const notifc = new EventSource('http://localhost:3000/sse');

     notifc.addEventListener('message', function (e) {
            try {
                const detail = JSON.parse(e.data)
            } catch(err) {
            }
        })
```
 

### What do you see instead?

![image](https://user-images.githubusercontent.com/3823496/219508083-21af9145-1bd8-4e2e-bdec-2efdd0c74539.png)

### Additional information

this is the working nodejs sse server

```js
const http = require('http');
const port = process.env.PORT || 3000;


const server = http.createServer(async(req, res) => {
    process.env.DEBUG_SSE && console.info(req)

    res.setHeader('Vary', 'Origin')
    req.headers.origin && res.setHeader('Access-Control-Allow-Origin', req.headers.origin)

    if (req.method.toUpperCase() == 'OPTIONS') {
        res.writeHead(200)
        return res.end()
    }

    res.setHeader('Content-Type', 'text/event-stream')
    res.setHeader('Cache-Control', 'no-cache')
    res.setHeader('Connection', 'keep-alive')
    res.writeHead(200);

    setInterval(_ => {
        res.write(`${Date.now()}\ndata: ${JSON.stringify({model:'noop', message:'Welcome'})}\n\n`);
    }, 4000)

});

server.listen(port, () => {
    console.log(`Listening on port ${port}`);
});

```
![image](https://user-images.githubusercontent.com/3823496/219511600-97e3249b-449c-4fa1-8c37-aa7e0484ce45.png)

**Comment by ThatOneBro** [comment] 2023-02-17 01:14
Closing this since it's a duplicate of #2091

**Closed as completed by ThatOneBro** 2023-02-17 01:14 UTC
Labels: bug
