### ISSUE TITLE
sqlite on bun is crash

### ISSUE THREAD

**Issue by jefripunza** [oven-sh/bun#12965] opened 2024-07-31 10:17 UTC
### How can we reproduce the crash?

i use :

import session from "express-session";
import SQLiteStoreFactory from "connect-sqlite3";

const SQLiteStore = SQLiteStoreFactory(session);

app.use(
  session({
    store: new SQLiteStore({
      db: "sessions.sqlite",
      dir: "./database",
      table: "sessions",
    }),
    secret: process.env.SESSION_SECRET as string,
    resave: false,
    saveUninitialized: true,
  })
);

but crash / panic

### Relevant log output

```shell
Bun v1.1.21 (70ca2b76) Windows x64
CPU: sse42 avx avx2
Args: "C:\Users\jefri\.bun\bin\bun.exe" "run" "index.ts"
Features: jsc Bun.stdin(2) dotenv tsconfig(7) 
Builtins: "bun:main" "node:async_hooks" "node:buffer" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:net" "node:os" "node:path" "node:process" "node:querystring" "node:stream" "node:string_decoder" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" 
Elapsed: 150ms | User: 15ms | Sys: 0ms
RSS: 0.16GB | Peak: 0.16GB | Commit: 0.20GB | Faults: 38379
```

### Stack Trace (bun.report)

Bun v1.1.21 ([`70ca2b7`](<https://github.com/oven-sh/bun/tree/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b>)) on windows x86_64 [RunCommand]

**panic**: napi: napi_define_properties
  Error::Error

- [`bun.zig:1394`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.zig#L1394>): `lenSliceTo`
- [`napi.zig:1168`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/napi/napi.zig#L1168>): `napiSpan`
- ??? at `0x1b17` in node_sqlite3.node
- ??? at `0x1af8` in node_sqlite3.node
- ??? at `0xe6ff` in node_sqlite3.node
- [`event_loop.zig:2202`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/event_loop.zig#L2202>): `loop`
- [`event_loop.zig:574`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/event_loop.zig#L574>): `bunVM`
- [`Allocator.zig:328`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/deps/zig/lib/std/mem/Allocator.zig#L328>): `free`
- [`javascript.zig:1445`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/javascript.zig#L1445>): `isWatcherEnabled`
- [`bindings.cpp:4993`](<https://github.com/oven-sh/bun/blob/70ca2b76c3d33f7ceeea43a702b396ab8ffce25b/src/bun.js/bindings/bindings.cpp#L4993>): `builtinNameMap`

**Comment by Jarred-Sumner** [comment] 2024-08-05 02:24
Duplicate of https://github.com/oven-sh/bun/issues/12052

**Comment by Jarred-Sumner** [comment] 2024-08-05 02:24
Please follow along in https://github.com/oven-sh/bun/issues/12052

**Closed as not planned by Jarred-Sumner** 2024-08-05 02:24 UTC
Labels: napi, crash, windows, runtime
