### ISSUE TITLE
Failed to run "bun-repl" due to error InvalidExe

### ISSUE THREAD

**Issue by bconnorwhite** [oven-sh/bun#5312] opened 2023-09-13 21:18 UTC
### What version of Bun is running?

1.0.1+31aec4ebe325982fc0ef27498984b0ad9969162b

### What platform is your computer?

Darwin 22.5.0 arm64 arm

### What steps can reproduce the bug?

Run `bun repl` or `bunx bun-repl`

### What is the expected behavior?

The repl starting

### What do you see instead?

```
error: Failed to run "bun-repl" due to error InvalidExe
```

### Additional information

```
cat ~/.bun/install/global/node_modules/bun-repl/package.json | grep version
  "version": "2.0.5",
```

```
bun run ~/.bun/install/global/node_modules/bun-repl/src/cli.ts        
Welcome to Bun v1.0.1
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
```

**Comment by Sasha95** [comment] 2023-09-13 21:26
![image](https://github.com/oven-sh/bun/assets/12782629/8e235cbf-5962-4afc-9bbe-c3e6c613bda0)

**Comment by Electroid** [comment] 2023-09-13 21:29
@Sasha95 `bun repl` is not the same as the Node.js module, `node:repl`. They're similar concepts, but different.

**Comment by jhmaster2000** [comment] 2023-09-15 00:48
This is an issue with `bunx`, there is nothing the repl can do on its side about this.

**Comment by arthurfiorette** [comment] 2023-10-25 19:22
Hey @Electroid, you can also close this issue :) (Duplicate of #958)

**Comment by Electroid** [comment] 2023-10-25 19:31
Duplicate of #958

**Closed as not planned by Electroid** 2023-10-25 19:31 UTC
Labels: bug, bunx
