### ISSUE TITLE
bun compile project into single executable

### ISSUE THREAD

**Issue by uwussimo** [oven-sh/bun#1139] opened 2022-08-24 13:30 UTC
### What is the problem this feature will solve?

Instead of porting js||ts files, developer will be running single executable on top of Bun/JavaScriptCore. 

### What is the feature you are proposing to solve the problem?

Bun will create an executable that will include bun itself and project files, assets inside like `deno compile`.

### What alternatives have you considered?

Maybe use existing libraies or add support for bun to those like ncc, pkg, etc...

**Comment by kdabir** [comment] 2022-08-27 19:07
related issue to watch: https://github.com/oven-sh/bun/issues/441

**Comment by xhyrom** [comment] 2022-08-28 16:34
Duplicate of https://github.com/oven-sh/bun/issues/441

**Closed as not planned** 2022-08-28 16:35 UTC
Labels: enhancement
