### ISSUE TITLE
Runtime errors stack trace are not the same as node, causing difficulty to understand problem source

### ISSUE THREAD

**Issue by MatteoGauthier** [oven-sh/bun#11217] opened 2024-05-21 08:19 UTC
### What version of Bun is running?

1.1.8+89d25807f

### What platform is your computer?

Darwin 22.6.0 x86_64 i386

### What steps can reproduce the bug?

A runtime error inside a node_modules

My code 

```ts
import { MongoClient, Db } from "mongodb"

const uri = process.env.CACHE_MONGODB_URI as string

async function mergeTables(fromCollectionName: string, toCollectionName: string, idField: string): Promise<void> {
  let client: MongoClient
  try {
    client = new MongoClient(uri)
    await client.connect()
    const db: Db = client.db()

    const fromCollection = db.collection(fromCollectionName)
    const toCollection = db.collection(toCollectionName)

    if (!fromCollection || !toCollection) {
      throw new Error("Collection not found")
    }

    const fromDocuments: any[] = await fromCollection.find({}).toArray()

    for (const document of fromDocuments) {
      const existingDocument: any = await toCollection.findOne({ [idField]: document[idField] })

      if (existingDocument) {
        //                                                                    ⬇️ provoqued error here because of the _id field
        await toCollection.updateOne({ [idField]: document[idField] }, { $set: document })
        console.log(`Updated document with ID ${document[idField]}`)
      } else {
        await toCollection.insertOne(document)
        console.log(`Inserted document with ID ${document[idField]}`)
      }
    }

    if (client) {
      await client.close()
    }
  } catch (err) {
    console.error(err)
  }
}

// Example usage:
await mergeTables("temp", "bentocache", "key")

``` 

### What is the expected behavior?

Error with Node 20

```
MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'
    at UpdateOneOperation.execute (/Users/matteo/snark/player-lynk/back/hudl-bridge/node_modules/mongodb/src/operations/update.ts:150:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at executeOperation (/Users/matteo/snark/player-lynk/back/hudl-bridge/node_modules/mongodb/src/operations/execute_operation.ts:181:12)
    at mergeTables (/Users/matteo/snark/player-lynk/back/hudl-bridge/src/scripts/draft/merge-two-table-mongo.ts:27:9)
    at <anonymous> (/Users/matteo/snark/player-lynk/back/hudl-bridge/src/scripts/draft/merge-two-table-mongo.ts:44:1) {
  errorResponse: {
    index: 0,
    code: 66,
    errmsg: "Performing an update on the path '_id' would modify the immutable field '_id'"
  },
  index: 0,
  code: 66,
  [Symbol(errorLabels)]: Set(0) {}
}
``` 

### What do you see instead?

Error with Bun :

```
104 |      * not subject to semantic versioning compatibility guarantees and may change at any time.
105 |      *
106 |      * @public
107 |      **/
108 |     constructor(message, options) {
109 |         super(message, options);
              ^
error: Performing an update on the path '_id' would modify the immutable field '_id'
 code: "66"

      at new MongoError (/Users/matteo/snark/player-lynk/back/hudl-bridge/node_modules/mongodb/lib/error.js:109:9)
      at new MongoServerError (/Users/matteo/snark/player-lynk/back/hudl-bridge/node_modules/mongodb/lib/error.js:169:9)
      at /Users/matteo/snark/player-lynk/back/hudl-bridge/node_modules/mongodb/lib/operations/update.js:73:19

^C
``` 

### Additional information

I remember a tweet from jarred where he talked about choosing the depth of a stacktrace, maybe it would be interesting to leave a configuration property

**Comment by Electroid** [comment] 2024-05-21 17:01
Duplicate of #185

**Closed as not planned by Electroid** 2024-05-21 17:01 UTC
Labels: bug
