### ISSUE TITLE
Bun.file just not working for me

### ISSUE THREAD

**Issue by atinseau** [oven-sh/bun#2775] opened 2023-04-29 19:47 UTC
### What version of Bun is running?

0.5.9

### What platform is your computer?

Linux 5.4.0-147-generic x86_64 x86_64

### What steps can reproduce the bug?

this is my code

main.ts:

const output = Bun.file('test.txt');
await output.text()

test.txt:

hi

i get this

EBADF: Bad file number
   path: "test.txt"
syscall: "open"
  errno: -9

why ?

### What is the expected behavior?

//

### What do you see instead?

//

### Additional information

//

**Comment by Jarred-Sumner** [comment] 2023-04-30 16:39
> Linux 5.4.0-147-generic x86_64 x86_64

Can you try on a more recent Linux kernel? Something >= 5.15

**Comment by wavded** [comment] 2023-05-18 16:06
Had similar issue. Can confirm that Kernel 5.15 fixed it for me.

**Comment by atinseau** [comment] 2023-05-20 19:19
> Had similar issue. Can confirm that Kernel 5.15 fixed it for me.

I ll check, thanks you

**Comment by Electroid** [comment] 2023-09-20 16:36
Duplicate of #1446

**Closed as not planned by Electroid** 2023-09-20 16:36 UTC
Labels: bug
