### ISSUE TITLE
mssql throwing "socket must be an instance of net.Socket on attempted connection

### ISSUE THREAD

**Issue by ReeceXW** [oven-sh/bun#8066] opened 2024-01-09 13:03 UTC
### What version of Bun is running?

1.0.21+837cbd60d

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Initialize a bun project, install mssql, use a basic example like the following:

```
import * as mssql from "mssql";

await mssql.connect({
    server: "...",
    user: "...",
    password: "...",
    database: "..."
});
```

### What is the expected behavior?

Some sort of success/error response from the database.

### What do you see instead?

A connection error

> socket must be an instance of net.Socket, code: "ESOCKET"

### Additional information

This works running under Node

**Comment by Electroid** [comment] 2024-01-09 16:02
Duplicate of #5147

**Closed as not planned by Electroid** 2024-01-09 16:02 UTC
Labels: bug, node.js

**Comment by ReeceXW** [comment] 2024-01-09 16:47
> Duplicate of #5147

You've closed this because of an open issue that was totally ignored? A major issue that needs to be addressed

**Comment by Electroid** [comment] 2024-01-09 17:49
> > Duplicate of #5147
> 
> You've closed this because of an open issue that was totally ignored? A major issue that needs to be addressed

@ReeceXW It's helpful to close duplicate issues so the context on a particular bug is in one place. That said, I can understand the frustration that this bug has still not been fixed, but indeed we will fix this.
