### ISSUE TITLE
add Bun.buildSync

### ISSUE THREAD

**Issue by huseeiin** [oven-sh/bun#12895] opened 2024-07-28 11:31 UTC
### What is the problem this feature would solve?

like esbuild.buildSync, but for bun

### What is the feature you are proposing to solve the problem?

Bun.buildSync

**Comment by Electroid** [comment] 2024-07-28 18:08
You already opened this issue.

**Comment by Electroid** [comment] 2024-07-28 18:08
Duplicate of #12813

**Closed as not planned by Electroid** 2024-07-28 18:08 UTC
Labels: enhancement

**Comment by huseeiin** [comment] 2024-07-28 20:45
> You already opened this issue.

alzheimers :skull:
