### ISSUE TITLE
DNS Errors when trying to connect to a MongoDB URI

### ISSUE THREAD

**Issue by robobun** [oven-sh/bun#5498] opened 2023-09-15 20:29 UTC
I'm trying to connect to a Mongo Database Atlas but I'm getting a DNS error, on node.js it works just fine.
( it was working before i updated )

Output:
```bash
❯ bun run dev
$ bun --watch ./bot/src/bot.ts
[0.02ms] ".env"
Logging into discord...
Logged In
Connecting to database ...
mongodb+srv://***:***/?retryWrites=true&w=majority
error: srv lookup failed: Timeout while contacting DNS servers
 code: "DNS_ETIMEOUT"
```

Code:
```ts
import { Client } from "discord.js";
import mongoose from "mongoose";
import { IEventHandler } from "../handlers/eventHandler";
import BotSettingsModel from "../models/botSettings"; // Import your Mongoose model

export default {
    name: 'ready',
    once: true,
    async execute(client: Client) {
        console.log('Connecting to database ...');
        console.log(process.env.MONGO_URI)
        await mongoose.connect(process.env.MONGO_URI || '', { maxPoolSize: 20 })
        console.log("Connected to the database!");
        console.log(`Ready! Logged in as ${client.user?.tag}`);
        client.user?.setActivity(`PSO Brasil | League | Bot desenvolvido por @sueroo`);
    }
} as IEventHandler;
```

_Originally reported on Discord: [`DNS Errors when trying to connect to a MongoDB URI`](https://discord.com/channels/876711213126520882/1152337929419620362/1152337929419620362)_

**Comment by TheDanielMoli** [comment] 2024-02-07 17:25
Duplicate of https://github.com/oven-sh/bun/issues/8758 (the issue is in using the SRV record).

`mongodb://` works.

`mongodb+srv://` does not work.

**Comment by cirospaciari** [comment] 2024-11-13 19:44
Cannot reproduce this anymore, if you still facing this issue please reopen and I will investigate it again.

**Closed as completed by cirospaciari** 2024-11-13 19:44 UTC
Labels: bug, node.js
