### ISSUE TITLE
dynamic access of env variable in test fails

### ISSUE THREAD

**Issue by leanderpaul** [oven-sh/bun#7212] opened 2023-11-19 01:34 UTC
### What version of Bun is running?

1.0.11

### What platform is your computer?

Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Dynamically accessing the environment variables in `bun test` fails.

```ts
// env.spec.ts
import { expect, describe, it } from 'bun:test';

describe('Test', () => {
  it('should pass direct access', () => {
    expect(process.env.NODE_ENV).toBe('test');
  });

  it('should pass dynamic access', () => {
    const name = { val: 'NODE_ENV' };
    expect(process.env[name.val]).toBe('test');
  });
});

```

```sh
bun test env.spec.ts
```

The test results in failure as shown in the image below

![image](https://github.com/oven-sh/bun/assets/37008159/5f57c20e-4379-4466-bf75-98620473bba1)

### What is the expected behavior?

The expected behaviour is to be able to access the environment variable even using dynamic access.

### What do you see instead?

I cant access the environment variable using dynamic access and it return `undefined`

**Comment by Electroid** [comment] 2023-11-20 17:19
Duplicate of #4118

**Closed as not planned by Electroid** 2023-11-20 17:19 UTC
Labels: bug, bun:test
