### ISSUE TITLE
repl JSON imports failing

### ISSUE THREAD

**Issue by joshuarossi** [oven-sh/bun#4613] opened 2023-09-08 20:08 UTC
### What version of Bun is running?

1.0

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

initialize a new Bun project
open REPL
try to import the package.json file

### What is the expected behavior?

According to the documentation, I should be able to import JSON in the following way

```
import pkg from "./package.json";
```

### What do you see instead?

I get this error

```
SyntaxError: Missing 'default' import in module './package.json'.
      at /Users/joshrossi/Code/bun_website/$bun$repl.ts:1:181
```

### Additional information

I am using the REPL to test this and see the error.

**Comment by Jarred-Sumner** [comment] 2023-09-08 20:09
Ah, this is an issue in the repl

**Comment by joshuarossi** [comment] 2023-09-09 04:34
thanks, wasn't sure, i was just going through the intro tutorial, and figured i'd play around with the features in the REPL, you can still get it to work, but you need to do `import * as pkg from "./package.json";`

I am always curious why the REPL wouldn't match exactly executing a file...

**Comment by jhmaster2000** [comment] 2023-09-09 09:58
REPLs are kind of unique environments with a unique set of rules and restrictions compared to a normal execution context due to their different context flow, so it's never going to be 1:1 in behavior, it physically can't be given it works differently at fundamental levels.

For example here this happens because of a bug (will fix) in the transpilation of top level import syntax into require() under the hood, which is how the repl actually "supports" top level imports despite them being meant to be static. I had never tested a json import in the repl so it makes sense I'd miss something with those but I already know a likely fix based on the error.

**Comment by joshuarossi** [comment] 2023-09-10 04:32
thanks!

**Comment by jhmaster2000** [comment] 2023-09-11 14:27
@joshuarossi do you mind retrying to reproduce this? I believe this might be fixed now. The REPL command should auto-update so no extra setup or updating needed (but if you can still reproduce the issue could you confirm your repl version by running `.info` inside a repl session?)

**Comment by joshuarossi** [comment] 2023-09-14 21:36
sure, so follow my same steps as before, and also run .info?

**Comment by joshuarossi** [comment] 2023-09-14 21:38
This is what I am seeing...should I upgrade a package or a version?

```
[bun_website] bun repl                                                                                                                                                                                                          
Welcome to Bun.js v1.0.0
Type ".help" for more information.
> import pkg from "./package.json";
SyntaxError: Missing 'default' import in module './package.json'.
      at /Users/joshrossi/Code/bun_website/$bun$repl.ts:1:181
> .info
bun-repl v1.3.1
    Installed at: /Users/joshrossi/.bun/install/global/node_modules/bun-repl
    Bun version: v1.0.0 (822a00c4d508b54f650933a73ca5f4a3af9a7983)
    SWC version: v1.3.27
    Color mode: true
    Debug mode: false
    Current session uptime: 6s
> 
```

**Comment by joshuarossi** [comment] 2023-09-14 21:38
maybe if i reinstall the bun-repl package?

**Comment by jhmaster2000** [comment] 2023-09-15 00:27
> This is what I am seeing...should I upgrade a package or a version?
> 
> ```
> [bun_website] bun repl                                                                                                                                                                                                          
> Welcome to Bun.js v1.0.0
> Type ".help" for more information.
> > import pkg from "./package.json";
> SyntaxError: Missing 'default' import in module './package.json'.
>       at /Users/joshrossi/Code/bun_website/$bun$repl.ts:1:181
> > .info
> bun-repl v1.3.1
>     Installed at: /Users/joshrossi/.bun/install/global/node_modules/bun-repl
>     Bun version: v1.0.0 (822a00c4d508b54f650933a73ca5f4a3af9a7983)
>     SWC version: v1.3.27
>     Color mode: true
>     Debug mode: false
>     Current session uptime: 6s
> > 
> ```

Ok yeah that is a *very* outdated version of the repl, can you follow the steps here to try and force-update it: https://github.com/jhmaster2000/bun-repl/issues/7#issuecomment-1718643970

...and then after getting the right version if it works, try the json import again?

**Comment by joshuarossi** [comment] 2023-09-20 07:54
it worked :) thanks so much for the help

**Closed as completed** 2023-09-20 09:07 UTC
Labels: bug, repl
