### ISSUE TITLE
Bun's docker image has no support for rxjs when used as a runtime image

### ISSUE THREAD

**Issue by 0xciph3r** [oven-sh/bun#6450] opened 2023-10-12 13:17 UTC
### What version of Bun is running?

1.0.2

### What platform is your computer?

Darwin 22.1.0 x86_64 i386

### What steps can reproduce the bug?

I am running a nestjs application that uses rxjs to handle authentication in a oven/bun container, it turns out that when my container image is node, it handles rxjs well but when I switch to oven/bun, I get errors like this:

```bash
TypeError: Cannot call a class constructor without |new|
    at AsyncResource (node:async_hooks:125:14)
159.65.84.237 - - [05/Oct/2023:08:04:02 +0000] "GET /exchange/price HTTP/1.1" - - "-" "axios/0.21.1"
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:5)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:42:8)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:36:15)
    at errorContext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:21:11)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:26:42)
    at doInnerSub (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:59)
    at outerNext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:38)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:34:23)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:53:15)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/observable/innerFrom.js:122:26)
    at processTicksAndRejections (:55:39)
[Nest] 1  - 10/05/2023, 8:04:08 AM   ERROR [ExceptionsHandler] Cannot call a class constructor without |new|
TypeError: Cannot call a class constructor without |new|
    at AsyncResource (node:async_hooks:125:14)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:5)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:42:8)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:36:15)
    at errorContext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:21:11)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:26:42)
    at doInnerSub (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:59)
    at outerNext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:38)
    at <anonymous> ```

### What is the expected behavior?

The expected behaviour is that the oven/bun runtime should be able to handle rxjs and reactive javascript dependencies with ease similar to how it is done on nodejs and without errors

### What do you see instead?


```bash
TypeError: Cannot call a class constructor without |new|
    at AsyncResource (node:async_hooks:125:14)
159.65.84.237 - - [05/Oct/2023:08:04:02 +0000] "GET /exchange/price HTTP/1.1" - - "-" "axios/0.21.1"
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:5)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:42:8)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:36:15)
    at errorContext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:21:11)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:26:42)
    at doInnerSub (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:59)
    at outerNext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:38)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:34:23)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:53:15)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/observable/innerFrom.js:122:26)
    at processTicksAndRejections (:55:39)
[Nest] 1  - 10/05/2023, 8:04:08 AM   ERROR [ExceptionsHandler] Cannot call a class constructor without |new|
TypeError: Cannot call a class constructor without |new|
    at AsyncResource (node:async_hooks:125:14)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:5)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:42:8)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:36:15)
    at errorContext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:21:11)
    at <anonymous> (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Observable.js:26:42)
    at doInnerSub (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:59)
    at outerNext (/usr/src/app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:38)
    at <anonymous> ```

### Additional information

_No response_

**Comment by Electroid** [comment] 2023-10-12 16:54
Duplicate of #5997

**Comment by Electroid** [comment] 2023-10-12 16:55
This was fixed in a newer version of Bun, please upgrade!

**Closed as completed by Electroid** 2023-10-12 16:55 UTC
Labels: bug, node.js
