### ISSUE TITLE
bun panic

### ISSUE THREAD

**Issue by guotie** [oven-sh/bun#12068] opened 2024-06-23 01:34 UTC
### Relevant log output

```shell
Bun v1.1.13 (bd6a6051) Linux x64 (baseline)
Args: "bun" "run" "./tx.js"

Features: jsc extracted_packages(4) fetch(209) http_server WebSocket
Builtins: "bun:main" "node:assert" "node:async_hooks" "node:buffer" "node:child_process" "node:console" "node:crypto" "node:events" "node:fs" "node:http" "node:https" "node:module" "node:net" "node:os" "node:path" "node:perf_hooks" "node:stream" "node:string_decoder" "node:timers" "node:tls" "node:tty" "node:url" "node:util" "node:util/types" "node:zlib" "node:worker_threads" "ws" "node:diagnostics_channel"
Elapsed: 11770304ms | User: 389659ms | Sys: 202103ms
RSS: 1.03GB | Peak: 0.21GB | Commit: 1.03GB | Faults: 1
panic(main thread): Segmentation fault at address 0x0

```
```


### Stack Trace (bun.report)

Bun v1.1.13 ([`bd6a605`](<https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7>)) on linux x86_64_baseline [RunCommand]

Segmentation fault at address 0x00000000

- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `WTF::jscSignalHandler`
- `??`
- [`StringImpl.h:1154`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7//build/bun/bun-webkit/include/wtf/text/StringImpl.h#L1154>): `Bun::formatStackTrace`
- [`ZigGlobalObject.cpp:570`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/bindings/ZigGlobalObject.cpp#L570>): `computeErrorInfoWithoutPrepareStackTrace`
- [`ZigGlobalObject.cpp:665`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/src/bun.js/bindings/ZigGlobalObject.cpp#L665>): `computeErrorInfo`
- [`Function.h:53`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7//build/bun/bun-webkit/include/wtf/Function.h#L53>): `WTF::Detail::CallableWrapper<WTF::String (...)(...), WTF::String, JSC::VM&, WTF::Vector<JSC::StackFrame, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&, unsigned int&, unsigned int&, WTF::String&, JSC::JSObject*>::call`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::ErrorInstance::computeErrorInfo`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::Heap::runEndPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `JSC::Heap::runCurrentPhase`
- [`ld-temp.o:0`](<https://github.com/oven-sh/bun/blob/bd6a6051203ff577240615ff4e242270035a36b7/ld-temp.o#L0>): `WTF::ScopedLambdaFunctor<void (...), JSC::Heap::collectInMutatorThread()::$_0>::implFunction`

<!-- from bun.report: nBXpKsTRDL2XuuedmD2v -->

**Comment by guotie** [comment] 2024-06-23 01:37
it runs in docker, I will try it

**Comment by trylovetom** [comment] 2024-06-24 02:05
same here v1.1.15 bun in alpine

**Comment by Jarred-Sumner** [comment] 2024-06-24 03:08
Duplicate of #11568

**Comment by Jarred-Sumner** [comment] 2024-06-24 03:08
We are tracking this in https://github.com/oven-sh/bun/issues/11568

Please follow along in that issue

Are you able to provide a reproduction? It would be very helpful as several people have reported this issue but we haven't been able to reproduce it.

**Closed as not planned by Jarred-Sumner** 2024-06-24 03:08 UTC
Labels: crash, runtime
